Repository helm/charts, pull requests merged in 2018-03, with the labels that each got.

#3927 [stable/concourse] fixed incorrect values for gitlab auth secrets
  stable/concourse/Chart.yaml
  stable/concourse/templates/secrets.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3930 [stable/traefik] allow use of existing pvc
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/acme-pvc.yaml
  stable/traefik/templates/deployment.yaml
  stable/traefik/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3842 prometheus service annotations for elastisearch-exporter
  stable/elasticsearch-exporter/Chart.yaml
  stable/elasticsearch-exporter/templates/service.yaml
  stable/elasticsearch-exporter/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3899 [incubator/patroni] RBAC role and rolebinding
  incubator/patroni/Chart.yaml
  incubator/patroni/README.md
  incubator/patroni/templates/_helpers.tpl
  incubator/patroni/templates/role-patroni.yaml
  incubator/patroni/templates/rolebinding-patroni.yaml
  incubator/patroni/templates/serviceaccount-patroni.yaml
  incubator/patroni/templates/statefulset-patroni.yaml
  incubator/patroni/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3923 [stable/traefik] Update app version to 1.5.3
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3936 Added so nodePort can be specifed
  stable/mysql/Chart.yaml
  stable/mysql/templates/svc.yaml
  stable/mysql/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3805 [incubator/kafka] Allows alternate scheduler for kafka statefulset
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
  incubator/kafka/templates/statefulset.yaml
  incubator/kafka/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3752 Add FluentD chart
  incubator/fluentd/.helmignore
  incubator/fluentd/Chart.yaml
  incubator/fluentd/templates/NOTES.txt
  incubator/fluentd/templates/_helpers.tpl
  incubator/fluentd/templates/configmap.yaml
  incubator/fluentd/templates/deployment.yaml
  incubator/fluentd/templates/ingress.yaml
  incubator/fluentd/templates/service.yaml
  incubator/fluentd/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3940 [stable/wordpress] removes unused `externalDatabase.rootPassword` param
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
  stable/wordpress/templates/externaldb-secrets.yaml
  stable/wordpress/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3908 zk Add OWNERS
  incubator/zookeeper/Chart.yaml
  incubator/zookeeper/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3911 cockroachdb - add owners
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3802 [stable/postgresql] Allows alternate scheduler for postgresql deployment
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/deployment.yaml
  stable/postgresql/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3960 [stable/docker-registry]: Add support for a predefined NodePort, and predefined PVC
  stable/docker-registry/Chart.yaml
  stable/docker-registry/README.md
  stable/docker-registry/templates/deployment.yaml
  stable/docker-registry/templates/pvc.yaml
  stable/docker-registry/templates/service.yaml
  stable/docker-registry/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3754 [incubator/kafka] Support option to expose Kafka via NodePort
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
  incubator/kafka/templates/NOTES.txt
  incubator/kafka/templates/service-brokers-external.yaml
  incubator/kafka/templates/statefulset.yaml
  incubator/kafka/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3764 [redis] Add support for redisExtraFlags variable
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/templates/deployment.yaml
  stable/redis/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3768 Add nodeSelector config parameter to mongodb chart
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/templates/deployment.yaml
  stable/mongodb/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3776 stable/fluent-bit: automatically restart when configuration changes
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/templates/daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3749 [stable/zetcd] Fix zetcd template when etcd-operator disabled
  stable/zetcd/Chart.yaml
  stable/zetcd/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3892 [incubator/cassandra] Add podAntiAffinity
  incubator/cassandra/Chart.yaml
  incubator/cassandra/templates/cassandra-statefulset.yaml
  incubator/cassandra/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3941 Adding support for nodeSelector to newrelic-infrastructure
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/README.md
  stable/newrelic-infrastructure/templates/daemonset.yaml
  stable/newrelic-infrastructure/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3953 [incubator/patroni] Declare port name so service and endpoint bind correctly
  incubator/patroni/Chart.yaml
  incubator/patroni/templates/svc-patroni.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3931 Make it possible to add tolerations to fluentd-cw
  incubator/fluentd-cloudwatch/Chart.yaml
  incubator/fluentd-cloudwatch/README.md
  incubator/fluentd-cloudwatch/templates/daemonset.yaml
  incubator/fluentd-cloudwatch/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3883 [stable/spinnaker] Spinnaker v1.6.0
  stable/spinnaker/Chart.yaml
  stable/spinnaker/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3956 Make the strategy configurable
  incubator/chartmuseum/Chart.yaml
  incubator/chartmuseum/templates/deployment.yaml
  incubator/chartmuseum/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3962 Removing hardcoded secret name from newrelic-infrastructure
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/templates/daemonset.yaml
  stable/newrelic-infrastructure/templates/secret.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3963 [stable/quassel]: Update postgresql requirement version
  stable/quassel/Chart.yaml
  stable/quassel/requirements.lock
  stable/quassel/requirements.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3968 jaeger: spark: Allow values file configuration of failed and successful CronJob history limits, with defaults
  incubator/jaeger/Chart.yaml
  incubator/jaeger/README.md
  incubator/jaeger/templates/spark-cronjob.yaml
  incubator/jaeger/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3670 Add Artifactory HA helm chart
  stable/artifactory-ha/.helmignore
  stable/artifactory-ha/Chart.yaml
  stable/artifactory-ha/README.md
  stable/artifactory-ha/requirements.lock
  stable/artifactory-ha/requirements.yaml
  stable/artifactory-ha/templates/NOTES.txt
  stable/artifactory-ha/templates/_helpers.tpl
  stable/artifactory-ha/templates/artifactory-binarystore.yaml
  stable/artifactory-ha/templates/artifactory-nfs-pvc.yaml
  stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
  stable/artifactory-ha/templates/artifactory-plugin-inactiveservercleaner.yaml
  stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
  stable/artifactory-ha/templates/artifactory-secrets.yaml
  stable/artifactory-ha/templates/artifactory-service.yaml
  stable/artifactory-ha/templates/nginx-deployment.yaml
  stable/artifactory-ha/templates/nginx-service.yaml
  stable/artifactory-ha/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3938 datadog: support the agent6 in the helm chart
  stable/datadog/Chart.yaml
  stable/datadog/templates/clusterrole.yaml
  stable/datadog/templates/daemonset.yaml
  stable/datadog/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3980 [stable/rabbitmq] Adds fullnameOverride support
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/S

#3992 [incubator/chartmuseum] upgrade to latest version
  incubator/chartmuseum/Chart.yaml
  incubator/chartmuseum/README.md
  incubator/chartmuseum/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3970 [stable/concourse] Enable AWS SSM support for Credential Manager
  stable/concourse/Chart.yaml
  stable/concourse/README.md
  stable/concourse/templates/secrets.yaml
  stable/concourse/templates/web-deployment.yaml
  stable/concourse/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3985 Fix a typo in kubernetes-dashboard
  stable/kubernetes-dashboard/Chart.yaml
  stable/kubernetes-dashboard/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3996 [stable/weave-cloud] Add OWNERS
  stable/weave-cloud/Chart.yaml
  stable/weave-cloud/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3997 [stable/prestashop] Disable check the cookie IP address
  stable/prestashop/Chart.yaml
  stable/prestashop/templates/deployment.yaml
  stable/prestashop/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3954 [incubator/patroni] Removed obsolete admin password option
  incubator/patroni/Chart.yaml
  incubator/patroni/README.md
  incubator/patroni/templates/NOTES.txt
  incubator/patroni/templates/sec-patroni.yaml
  incubator/patroni/templates/statefulset-patroni.yaml
  incubator/patroni/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3995 [stable/fluent-bit] release 0.2.12 (Fluent Bit 0.12.15)
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3998 [stable/rabbitmq-ha] Fix notes to get ports
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4007 [incubator/oauth-proxy] improve docs
  incubator/oauth-proxy/Chart.yaml
  incubator/oauth-proxy/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3942 [incubator/sentry-kubernetes] add missing clusterrole and clusterrolebinding
  incubator/sentry-kubernetes/Chart.yaml
  incubator/sentry-kubernetes/templates/clusterrole.yaml
  incubator/sentry-kubernetes/templates/clusterrolebinding.yaml
  incubator/sentry-kubernetes/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3839 [stable/jenkins] Add affinity settings
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/jenkins-master-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3961 [stable/prometheus] update prometheus.io/port regex
  stable/prometheus/Chart.yaml
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3924 Add KubeDB chart
  stable/kubedb/.helmignore
  stable/kubedb/Chart.yaml
  stable/kubedb/OWNERS
  stable/kubedb/README.md
  stable/kubedb/templates/NOTES.txt
  stable/kubedb/templates/_helpers.tpl
  stable/kubedb/templates/apiregistration.yaml
  stable/kubedb/templates/cluster-role-binding.yaml
  stable/kubedb/templates/cluster-role.yaml
  stable/kubedb/templates/deployment.yaml
  stable/kubedb/templates/service-account.yaml
  stable/kubedb/templates/service.yaml
  stable/kubedb/templates/user-roles.yaml
  stable/kubedb/templates/validating-webhook-configuration.yaml
  stable/kubedb/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3965 [stable/grafana] Change .Values.extraEnv to a list of EnvVar values.
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/deployment.yaml
  stable/grafana/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3909 etcd-operator - Add owners
  stable/etcd-operator/Chart.yaml
  stable/etcd-operator/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S

#4027 [incubator/kafka] Allow configurationOverride of zookeeper.connect
  incubator/kafka/Chart.yaml
  incubator/kafka/OWNERS
  incubator/kafka/templates/_helpers.tpl
  incubator/kafka/templates/configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3944 Add SSL certificate support and AMPQS support
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/templates/NOTES.txt
  stable/rabbitmq-ha/templates/configmap.yaml
  stable/rabbitmq-ha/templates/secret.yaml
  stable/rabbitmq-ha/templates/service.yaml
  stable/rabbitmq-ha/templates/statefulset.yaml
  stable/rabbitmq-ha/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3730 [stable/nginx-ingress] Remove stats exporter
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-daemonset.yaml
  stable/nginx-ingress/templates/controller-deployment.yaml
  stable/nginx-ingress/templates/controller-metrics-service.yaml
  stable/nginx-ingress/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3994 [stable/redis] Adds fullnameOverride support
  stable/redis/Chart.yaml
  stable/redis/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/S

#4053 fix-typo-in-g2-readme
  stable/g2/Chart.yaml
  stable/g2/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4048 Update to ChartMuseum 0.4.1 and add non-root context path support
  incubator/chartmuseum/Chart.yaml
  incubator/chartmuseum/README.md
  incubator/chartmuseum/templates/deployment.yaml
  incubator/chartmuseum/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4030 docker-registry: support more s3 storage options
  stable/docker-registry/Chart.yaml
  stable/docker-registry/README.md
  stable/docker-registry/templates/deployment.yaml
  stable/docker-registry/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3972 [stable/quassel]: Ensure references to postgres dependancy are correct (alternative)
  stable/quassel/Chart.yaml
  stable/quassel/templates/_helpers.tpl
  stable/quassel/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4055 [stable/docker-registry]: fix typo in README
  stable/docker-registry/Chart.yaml
  stable/docker-registry/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4041 [stable/percona-xtradb-cluster] add helm tests
  stable/percona-xtradb-cluster/Chart.yaml
  stable/percona-xtradb-cluster/README.md
  stable/percona-xtradb-cluster/files/functions.sh
  stable/percona-xtradb-cluster/templates/statefulset.yaml
  stable/percona-xtradb-cluster/templates/tests/pxc-test-cm.yaml
  stable/percona-xtradb-cluster/templates/tests/pxc-test.yaml
  stable/percona-xtradb-cluster/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3781 [stable/anchore-engine] add nodeSelector, tolerations, and affinity support
  stable/anchore-engine/Chart.yaml
  stable/anchore-engine/templates/core_deployment.yaml
  stable/anchore-engine/templates/worker_deployment.yaml
  stable/anchore-engine/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3988 [stable/minio]: fix indentation of node selector labels of post-install-create…
  stable/minio/Chart.yaml
  stable/minio/templates/post-install-create-bucket-job.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4031 update nginx-ingress app version to 0.11.0
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4023 [stable/external-dns]: Specify Google Cloud DNS credentials.json via kubernetes secret
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/deployment.yaml
  stable/external-dns/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#2914 [stable/dask] Add updated Dask chart
  stable/dask/Chart.yaml
  stable/dask/README.md
  stable/dask/templates/NOTES.txt
  stable/dask/templates/_helpers.tpl
  stable/dask/templates/dask-jupyter-config.yaml
  stable/dask/templates/dask-jupyter-deployment.yaml
  stable/dask/templates/dask-jupyter-service.yaml
  stable/dask/templates/dask-scheduler-deployment.yaml
  stable/dask/templates/dask-scheduler-service.yaml
  stable/dask/templates/dask-worker-deployment.yaml
  stable/dask/values.yaml
Labels: approved, changes needed, cncf-cla: yes, lgtm, size/L

#4028 [stable/jenkins] Allow more configuration of Jenkins agent service
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/jenkins-agent-svc.yaml
  stable/jenkins/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3696 [stable/sematext-docker-agent] Add support for custom endpoints
  stable/sematext-docker-agent/Chart.yaml
  stable/sematext-docker-agent/README.md
  stable/sematext-docker-agent/templates/configmap.yaml
  stable/sematext-docker-agent/templates/daemonset.yaml
  stable/sematext-docker-agent/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3984 [stable/coredns] update to 1.0.6 and small improvements
  stable/coredns/Chart.yaml
  stable/coredns/templates/deployment.yaml
  stable/coredns/templates/service.yaml
  stable/coredns/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4062 [Grafana] update grafana fullname helper to follow standard
  stable/grafana/Chart.yaml
  stable/grafana/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/S

#4043 [incubator/jaeger] Fix jaeger templates to point agent at proper collector service name
  incubator/jaeger/Chart.yaml
  incubator/jaeger/templates/_helpers.tpl
  incubator/jaeger/templates/agent-ds.yaml
  incubator/jaeger/templates/agent-svc.yaml
  incubator/jaeger/templates/collector-deploy.yaml
  incubator/jaeger/templates/collector-svc.yaml
  incubator/jaeger/templates/query-deploy.yaml
  incubator/jaeger/templates/query-ing.yaml
  incubator/jaeger/templates/query-svc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3987 Add a note about the default state of the API
  incubator/chartmuseum/Chart.yaml
  incubator/chartmuseum/README.md
  incubator/chartmuseum/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3806 Added ingress hosts example for Artifactory chart
  stable/artifactory/Chart.yaml
  stable/artifactory/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4035 Allow to disable data ownership reset
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/server-deployment.yaml
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4065 [stable/consul] Parameterize domain option passed to consul (#4064)
  stable/consul/Chart.yaml
  stable/consul/templates/consul-statefulset.yaml
  stable/consul/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4063 Set Artifactory version 5.9.1
  stable/artifactory-ha/Chart.yaml
  stable/artifactory-ha/README.md
  stable/artifactory-ha/values.yaml
  stable/artifactory/Chart.yaml
  stable/artifactory/README.md
  stable/artifactory/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4073 fix: typo daemonset.useHostPort for nginx-ingress
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/templates/controller-daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4078 [stable/suitecrm] Update deprecated annotation - service.beta.kuberne…
  stable/suitecrm/Chart.yaml
  stable/suitecrm/templates/svc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4080 [stable/prestashop] Update deprecated annotation - service.beta.kuber…
  stable/prestashop/Chart.yaml
  stable/prestashop/templates/deployment.yaml
  stable/prestashop/templates/svc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4081 [stable/sugarcrm] Update deprecated annotation - service.beta.kuberne…
  stable/sugarcrm/Chart.yaml
  stable/sugarcrm/templates/svc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3538 [stable/gcloud-sqlproxy] Allow specifying more than one instance.
  stable/gcloud-sqlproxy/Chart.yaml
  stable/gcloud-sqlproxy/README.md
  stable/gcloud-sqlproxy/templates/NOTES.txt
  stable/gcloud-sqlproxy/templates/deployment.yaml
  stable/gcloud-sqlproxy/templates/svc.yaml
  stable/gcloud-sqlproxy/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3577 [stable/grafana] Improve importing dashboards.
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/dashboards-import-job-configmap.yaml
  stable/grafana/templates/dashboards-import-job.yaml
  stable/grafana/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3884 [stable/percona-xtradb-cluster] add OWNERS
  stable/percona-xtradb-cluster/Chart.yaml
  stable/percona-xtradb-cluster/OWNERS
Labels: approved, changes needed, cncf-cla: yes, lgtm, size/XS

#4085 [stable/mariadb]: Update chart templates
  stable/mariadb/Chart.yaml
  stable/mariadb/templates/_helpers.tpl
  stable/mariadb/templates/configmap.yaml
  stable/mariadb/templates/deployment.yaml
  stable/mariadb/templates/pvc.yaml
  stable/mariadb/templates/secrets.yaml
  stable/mariadb/templates/svc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4083 Deprecate dask-distributed chart
  stable/dask-distributed/Chart.yaml
  stable/dask-distributed/README.md
  stable/dask-distributed/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm, size/S

#4100 [stable/cockroachdb] Add config for public service type
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/README.md
  stable/cockroachdb/templates/cockroachdb-statefulset.yaml
  stable/cockroachdb/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4092 [stable/concourse] Change Concourse links
  stable/concourse/Chart.yaml
  stable/concourse/README.md
  stable/concourse/templates/NOTES.txt
  stable/concourse/templates/worker-svc.yaml
  stable/concourse/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4098 fix-typo-in-goldfish-readme
  incubator/goldfish/Chart.yaml
  incubator/goldfish/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4088 [incubator/jaeger] Add parentheses around 'or' parameters to fix cron-job installation
  incubator/jaeger/Chart.yaml
  incubator/jaeger/templates/spark-cronjob.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4087 Update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4101 [stable/postgresql] Update README.md
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4104 [stable/consul] Fix render error when ingress is enabled
  stable/consul/Chart.yaml
  stable/consul/templates/consul-ingress.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4108 Fix typo in zookeeper
  incubator/zookeeper/Chart.yaml
  incubator/zookeeper/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4094 Fix reference to etcdOperator replica count
  stable/etcd-operator/Chart.yaml
  stable/etcd-operator/templates/operator-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4057 [stable/sonatype-nexus] Add annotation configuration in pvc
  stable/sonatype-nexus/Chart.yaml
  stable/sonatype-nexus/README.md
  stable/sonatype-nexus/templates/pvc.yaml
  stable/sonatype-nexus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3947 Kong v0.12.2 support and flatten ports values
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/templates/NOTES.txt
  stable/kong/templates/deployment.yaml
  stable/kong/templates/service-kong-admin.yaml
  stable/kong/templates/service-kong-proxy.yaml
  stable/kong/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4091 [incubator/chartmuseum] upgrade to 0.4.2
  incubator/chartmuseum/Chart.yaml
  incubator/chartmuseum/README.md
  incubator/chartmuseum/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3910 prometheus - Add owners
  stable/prometheus/Chart.yaml
  stable/prometheus/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3799 Several changes in support of improved helm functionality
  stable/chaoskube/Chart.yaml
  stable/chaoskube/OWNERS
  stable/chaoskube/README.md
  stable/chaoskube/templates/deployment.yaml
  stable/chaoskube/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4120 [stable/cluster-autoscaler] Enable Autodiscovery
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/README.md
  stable/cluster-autoscaler/templates/NOTES.txt
  stable/cluster-autoscaler/templates/deployment.yaml
  stable/cluster-autoscaler/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3811 [stable/mariadb] use credentials in exec probes
  stable/mariadb/Chart.yaml
  stable/mariadb/templates/configmap.yaml
  stable/mariadb/templates/deployment.yaml
  stable/mariadb/templates/pvc.yaml
  stable/mariadb/templates/secrets.yaml
  stable/mariadb/templates/svc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4089 [incubator/zookeeper] Add tolerations for zookeeper pods
  incubator/zookeeper/Chart.yaml
  incubator/zookeeper/README.md
  incubator/zookeeper/templates/statefulset.yaml
  incubator/zookeeper/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4121 Use the correct service name when specifying the ingress backend
  stable/grafana/Chart.yaml
  stable/grafana/templates/ingress.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4123 Typo fix in readme file
  incubator/webpagetest-agent/Chart.yaml
  incubator/webpagetest-agent/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4086 Fixes #3789
  stable/percona-xtradb-cluster/Chart.yaml
  stable/percona-xtradb-cluster/README.md
  stable/percona-xtradb-cluster/templates/statefulset.yaml
  stable/percona-xtradb-cluster/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4117 [stable/selenium] Upgrading Chart to Selenium 3.11.0
  stable/selenium/Chart.yaml
  stable/selenium/README.md
  stable/selenium/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3779 Allow specifying Service annotations
  stable/metabase/Chart.yaml
  stable/metabase/README.md
  stable/metabase/templates/service.yaml
  stable/metabase/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4136 stable/influxdb: fix password generation
  stable/influxdb/Chart.yaml
  stable/influxdb/templates/secret.yaml
  stable/influxdb/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4025 [stable/redis-ha] added option to enable/disable redis AUTH
  stable/redis-ha/Chart.yaml
  stable/redis-ha/templates/NOTES.txt
  stable/redis-ha/templates/redis-auth-secret.yaml
  stable/redis-ha/templates/redis-sentinel-deployment.yaml
  stable/redis-ha/templates/redis-server-deployment.yaml
  stable/redis-ha/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4145 mariadb: fix typo in values.yaml
  stable/mariadb/Chart.yaml
  stable/mariadb/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3973 Enable custom NodePorts for service
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
  stable/wordpress/templates/svc.yaml
  stable/wordpress/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4149 Publish chart for voyager v6.0.0
  stable/voyager/Chart.yaml
  stable/voyager/README.md
  stable/voyager/templates/_helpers.tpl
  stable/voyager/templates/apiregistration.yaml
  stable/voyager/templates/cluster-role-binding.yaml
  stable/voyager/templates/deployment.yaml
  stable/voyager/templates/service-account.yaml
  stable/voyager/templates/user-roles.yaml
  stable/voyager/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4150 Publish swift chart 0.7.3
  stable/swift/Chart.yaml
  stable/swift/README.md
  stable/swift/templates/_helpers.tpl
  stable/swift/templates/cluster-role-binding.yaml
  stable/swift/templates/deployment.yaml
  stable/swift/templates/service-account.yaml
  stable/swift/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4148 Fix ClusterRoleBinding for kubeless chart
  incubator/kubeless/Chart.yaml
  incubator/kubeless/templates/cluster-role-binding.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3955 [stable/external-dns] Enable assume-role creds for aws
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/_helpers.tpl
  stable/external-dns/templates/deployment.yaml
  stable/external-dns/templates/secret.yaml
  stable/external-dns/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3841 [incubator/vault] Add affinity setting
  incubator/vault/Chart.yaml
  incubator/vault/README.md
  incubator/vault/templates/deployment.yaml
  incubator/vault/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3964 Change to make spark home path configurable.
  stable/spark/Chart.yaml
  stable/spark/templates/spark-master-deployment.yaml
  stable/spark/templates/spark-sql-test.yaml
  stable/spark/templates/spark-worker-deployment.yaml
  stable/spark/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4134 [incubator/kafka] Add tolerations for the kafka pods
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
  incubator/kafka/templates/statefulset.yaml
  incubator/kafka/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4135 Update to latest Minio release RELEASE.2018-03-12T21-25-28Z
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4061 stable/cert-manager: add additional users to OWNERS file
  stable/cert-manager/Chart.yaml
  stable/cert-manager/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4076 Create prometheus postgres exporter chart
  stable/prometheus-postgres-exporter/.helmignore
  stable/prometheus-postgres-exporter/Chart.yaml
  stable/prometheus-postgres-exporter/README.md
  stable/prometheus-postgres-exporter/templates/NOTES.txt
  stable/prometheus-postgres-exporter/templates/_helpers.tpl
  stable/prometheus-postgres-exporter/templates/configmap.yaml
  stable/prometheus-postgres-exporter/templates/deployment.yaml
  stable/prometheus-postgres-exporter/templates/secrets.yaml
  stable/prometheus-postgres-exporter/templates/service.yaml
  stable/prometheus-postgres-exporter/templates/serviceaccount.yaml
  stable/prometheus-postgres-exporter/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4174 wordpress: Small fixes in values.yaml
  stable/wordpress/Chart.yaml
  stable/wordpress/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4173 Typo fix in stable/redis-ha/README.md
  stable/redis-ha/Chart.yaml
  stable/redis-ha/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3974 Add a stable Helm chart for MetalLB.
  stable/metallb/.helmignore
  stable/metallb/Chart.yaml
  stable/metallb/README.md
  stable/metallb/templates/NOTES.txt
  stable/metallb/templates/_helpers.tpl
  stable/metallb/templates/config.yaml
  stable/metallb/templates/controller.yaml
  stable/metallb/templates/rbac.yaml
  stable/metallb/templates/service-accounts.yaml
  stable/metallb/templates/speaker.yaml
  stable/metallb/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3991 [stable/sumologic-fluentd] Add support for user defined fluentd configuration
  stable/sumologic-fluentd/Chart.yaml
  stable/sumologic-fluentd/templates/_helpers.tpl
  stable/sumologic-fluentd/templates/clusterrole.yaml
  stable/sumologic-fluentd/templates/clusterrolebinding.yaml
  stable/sumologic-fluentd/templates/configmap.yaml
  stable/sumologic-fluentd/templates/daemonset.yaml
  stable/sumologic-fluentd/templates/secrets.yaml
  stable/sumologic-fluentd/templates/serviceaccount.yaml
  stable/sumologic-fluentd/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4118 Add annotations and service type to zookeeper
  incubator/zookeeper/Chart.yaml
  incubator/zookeeper/templates/NOTES.txt
  incubator/zookeeper/templates/service-clients.yaml
  incubator/zookeeper/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3792 [stable/kube2iam] Add support for boolean flags via extraArgs
  stable/kube2iam/Chart.yaml
  stable/kube2iam/templates/daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3859 [stable/elastalert] Updated image for Elasticsearch 6 support, and other minor chart adjustments
  stable/elastalert/Chart.yaml
  stable/elastalert/README.md
  stable/elastalert/templates/config.yaml
  stable/elastalert/templates/deployment.yaml
  stable/elastalert/templates/rules.yaml
  stable/elastalert/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4190 Typo fix in chartmuseum/README.md
  incubator/chartmuseum/Chart.yaml
  incubator/chartmuseum/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4192 [stable/suitecrm] Allow use of external database
  stable/suitecrm/Chart.yaml
  stable/suitecrm/README.md
  stable/suitecrm/requirements.lock
  stable/suitecrm/requirements.yaml
  stable/suitecrm/templates/NOTES.txt
  stable/suitecrm/templates/_helpers.tpl
  stable/suitecrm/templates/deployment.yaml
  stable/suitecrm/templates/externaldb-secrets.yaml
  stable/suitecrm/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4183 [stable/joomla] Allow use of external database
  stable/joomla/Chart.yaml
  stable/joomla/README.md
  stable/joomla/requirements.lock
  stable/joomla/requirements.yaml
  stable/joomla/templates/NOTES.txt
  stable/joomla/templates/deployment.yaml
  stable/joomla/templates/externaldb-secrets.yaml
  stable/joomla/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4181 [stable/jasperreports] Allow use of external database
  stable/jasperreports/Chart.yaml
  stable/jasperreports/README.md
  stable/jasperreports/requirements.lock
  stable/jasperreports/requirements.yaml
  stable/jasperreports/templates/NOTES.txt
  stable/jasperreports/templates/deployment.yaml
  stable/jasperreports/templates/externaldb-secrets.yaml
  stable/jasperreports/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4184 [stable/moodle] Allow use of external database
  stable/moodle/Chart.yaml
  stable/moodle/README.md
  stable/moodle/requirements.lock
  stable/moodle/requirements.yaml
  stable/moodle/templates/NOTES.txt
  stable/moodle/templates/deployment.yaml
  stable/moodle/templates/externaldb-secrets.yaml
  stable/moodle/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4186 [stable/opencart] Allow use of external database
  stable/opencart/Chart.yaml
  stable/opencart/README.md
  stable/opencart/requirements.lock
  stable/opencart/requirements.yaml
  stable/opencart/templates/NOTES.txt
  stable/opencart/templates/deployment.yaml
  stable/opencart/templates/externaldb-secrets.yaml
  stable/opencart/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4187 [stable/orangehrm] Allow use of external database
  stable/orangehrm/Chart.yaml
  stable/orangehrm/README.md
  stable/orangehrm/requirements.lock
  stable/orangehrm/requirements.yaml
  stable/orangehrm/templates/NOTES.txt
  stable/orangehrm/templates/deployment.yaml
  stable/orangehrm/templates/externaldb-secrets.yaml
  stable/orangehrm/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4182 update incubator/burrow/README.md
  incubator/burrow/Chart.yaml
  incubator/burrow/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4185 Typo fix in cassandra/README.md
  incubator/cassandra/Chart.yaml
  incubator/cassandra/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4188 [stable/prestashop] Allow use of external database
  stable/prestashop/Chart.yaml
  stable/prestashop/README.md
  stable/prestashop/requirements.lock
  stable/prestashop/requirements.yaml
  stable/prestashop/templates/NOTES.txt
  stable/prestashop/templates/deployment.yaml
  stable/prestashop/templates/externaldb-secrets.yaml
  stable/prestashop/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4189 [stable/osclass] Allow use of external database
  stable/osclass/Chart.yaml
  stable/osclass/README.md
  stable/osclass/requirements.lock
  stable/osclass/requirements.yaml
  stable/osclass/templates/NOTES.txt
  stable/osclass/templates/deployment.yaml
  stable/osclass/templates/externaldb-secrets.yaml
  stable/osclass/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4158 helm version upgrade 2.7.2 -> 2.8.2
  test/circle/install.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4193 [stable/sugarcrm] Allow use of external database
  stable/sugarcrm/Chart.yaml
  stable/sugarcrm/README.md
  stable/sugarcrm/requirements.lock
  stable/sugarcrm/requirements.yaml
  stable/sugarcrm/templates/NOTES.txt
  stable/sugarcrm/templates/_helpers.tpl
  stable/sugarcrm/templates/deployment.yaml
  stable/sugarcrm/templates/externaldb-secrets.yaml
  stable/sugarcrm/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4191 [stable/testlink] Allow use of external database
  stable/testlink/Chart.yaml
  stable/testlink/README.md
  stable/testlink/requirements.lock
  stable/testlink/requirements.yaml
  stable/testlink/templates/NOTES.txt
  stable/testlink/templates/_helpers.tpl
  stable/testlink/templates/deployment.yaml
  stable/testlink/templates/externaldb-secrets.yaml
  stable/testlink/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4163 fix dashboard wrong port mapping in notes
  stable/kubernetes-dashboard/Chart.yaml
  stable/kubernetes-dashboard/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4196 [stable/owncloud] Allow use of external database
  stable/owncloud/Chart.yaml
  stable/owncloud/README.md
  stable/owncloud/requirements.lock
  stable/owncloud/requirements.yaml
  stable/owncloud/templates/NOTES.txt
  stable/owncloud/templates/deployment.yaml
  stable/owncloud/templates/externaldb-secrets.yaml
  stable/owncloud/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4197 Typo fix in drone/README.md
  incubator/drone/Chart.yaml
  incubator/drone/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4198 Typo fix in elasticsearch/README.md
  incubator/elasticsearch/Chart.yaml
  incubator/elasticsearch/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4237 This fixes two testing issues
  test/changed.sh
  test/e2e.sh
  test/pr-review.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#4199 Typo fix in etcd/README.md
  incubator/etcd/Chart.yaml
  incubator/etcd/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4235 [stable/sugarcrm] Fix typo in deployment
  stable/sugarcrm/Chart.yaml
  stable/sugarcrm/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4234 [stable/mariadb] Fix some typos
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4208 [stable/wordpress] Fix some typos
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4202 Typo fix in gocd/README.md
  incubator/gocd/Chart.yaml
  incubator/gocd/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4201 Typo fix in fluentd-elasticsearch/README.md
  incubator/fluentd-elasticsearch/Chart.yaml
  incubator/fluentd-elasticsearch/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3929 [incubator/kafka] Simplifies kafka chart by removing configmap
  incubator/kafka/Chart.yaml
  incubator/kafka/templates/_helpers.tpl
  incubator/kafka/templates/configmap.yaml
  incubator/kafka/templates/statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4133 adding filebeat chart
  stable/filebeat/.helmignore
  stable/filebeat/Chart.yaml
  stable/filebeat/README.md
  stable/filebeat/templates/NOTES.txt
  stable/filebeat/templates/_helpers.tpl
  stable/filebeat/templates/clusterrole.yaml
  stable/filebeat/templates/clusterrolebinding.yaml
  stable/filebeat/templates/daemonset.yaml
  stable/filebeat/templates/prospectors-configmap.yaml
  stable/filebeat/templates/secret.yaml
  stable/filebeat/templates/serviceaccount.yaml
  stable/filebeat/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4155 support provided value for consul gossip-key
  stable/consul/Chart.yaml
  stable/consul/README.md
  stable/consul/templates/gossip-secret.yaml
  stable/consul/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
