Repository helm/charts, pull requests merged in 2018-04, with the labels that each got.

#4511 [stable/prometheus] Add extraArgs and extraConfigmapMounts for config-reload
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/server-deployment.yaml
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4578 Typo fix in stash/README.md
  stable/stash/Chart.yaml
  stable/stash/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4575 Typo fix in kubed/README.md
  stable/kubed/Chart.yaml
  stable/kubed/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4574 Typo fix in searchlight/README.md
  stable/searchlight/Chart.yaml
  stable/searchlight/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4573 Typo fix in swift/README.md
  stable/swift/Chart.yaml
  stable/swift/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4576 Typo fix in voyager/README.md
  stable/voyager/Chart.yaml
  stable/voyager/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4585 fix typo in prestashop/README.md
  stable/prestashop/Chart.yaml
  stable/prestashop/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4565 fix typo in testlink readme
  stable/testlink/Chart.yaml
  stable/testlink/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4564 fix typo in moodle readme
  stable/moodle/Chart.yaml
  stable/moodle/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4594 [stable/wordpress] Add wordpressTablePrefix option
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
  stable/wordpress/templates/deployment.yaml
  stable/wordpress/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4556 Update etcd-operator/README.md
  stable/etcd-operator/Chart.yaml
  stable/etcd-operator/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4551 Update table/prometheus-cloudwatch-exporte
  stable/prometheus-cloudwatch-exporter/Chart.yaml
  stable/prometheus-cloudwatch-exporter/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4547 update stable/artifactory/README.md
  stable/artifactory/Chart.yaml
  stable/artifactory/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4596 Fixing version comparisons from strings to semver
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4577 Typo fix in kubedb/README.md
  stable/kubedb/Chart.yaml
  stable/kubedb/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4567 fix typo in concourse's templates
  stable/concourse/Chart.yaml
  stable/concourse/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4546 typo fix in stable/artifactory-ha/README.md
  stable/artifactory-ha/Chart.yaml
  stable/artifactory-ha/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4548 typo fix in bitcoind
  stable/bitcoind/Chart.yaml
  stable/bitcoind/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4550 stable/prometheus-node-exporter/README.md
  stable/prometheus-node-exporter/Chart.yaml
  stable/prometheus-node-exporter/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4606 Fix for version comparison from strings to semver
  stable/redis/Chart.yaml
  stable/redis/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4634 Include pre-releases in the semver ranges
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4607 Fix for version comparisons from strings to semver
  stable/spotify-docker-gc/Chart.yaml
  stable/spotify-docker-gc/templates/daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4600 Fix for version comparison from strings to semver
  stable/kube2iam/Chart.yaml
  stable/kube2iam/templates/daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4597 Fix for version handling with stringe vs semver
  stable/concourse/Chart.yaml
  stable/concourse/templates/worker-statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4598 Fixing version range handling from strings to semver
  stable/datadog/Chart.yaml
  stable/datadog/templates/_helpers.tpl
  stable/datadog/templates/daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4599 Fix for version comparions from strings to semver
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4635 Include pre-releases in the semver ranges
  stable/redis/Chart.yaml
  stable/redis/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4620 Add prometheus pushgateway
  stable/prometheus-pushgateway/.helmignore
  stable/prometheus-pushgateway/Chart.yaml
  stable/prometheus-pushgateway/OWNERS
  stable/prometheus-pushgateway/README.md
  stable/prometheus-pushgateway/templates/NOTES.txt
  stable/prometheus-pushgateway/templates/_helpers.tpl
  stable/prometheus-pushgateway/templates/deployment.yaml
  stable/prometheus-pushgateway/templates/ingress.yaml
  stable/prometheus-pushgateway/templates/service.yaml
  stable/prometheus-pushgateway/templates/serviceaccount.yaml
  stable/prometheus-pushgateway/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4605 Fix for version comparison from strings to semver
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4603 Fix for version comparison from strings to semver
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4602 Fix for version comparison from strings to semver
  stable/minio/Chart.yaml
  stable/minio/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4663 [linting] Temporarily make maintainers optional for linting
  test/circle/yaml-schemas/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4391 Fix SSL certs for docker registry chart
  stable/docker-registry/Chart.yaml
  stable/docker-registry/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4619 Update README.md
  incubator/jaeger/Chart.yaml
  incubator/jaeger/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4671 [stable/drupal] Refactor image property and start using rolling tag
  stable/drupal/Chart.yaml
  stable/drupal/README.md
  stable/drupal/templates/deployment.yaml
  stable/drupal/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4648 [stable/odoo] Refactor image property in values.yaml
  stable/odoo/Chart.yaml
  stable/odoo/README.md
  stable/odoo/templates/deployment.yaml
  stable/odoo/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4674 [stable/redis] Refactor image properties in values.yaml
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/templates/deployment.yaml
  stable/redis/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4679 review wrong service port in pushgateway readme
  stable/prometheus-pushgateway/Chart.yaml
  stable/prometheus-pushgateway/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4654 [stable/phabricator] Refactor image property in values.yaml
  stable/phabricator/Chart.yaml
  stable/phabricator/README.md
  stable/phabricator/templates/deployment.yaml
  stable/phabricator/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4660 [stable/testlink] Refactor image property in values.yaml
  stable/testlink/Chart.yaml
  stable/testlink/README.md
  stable/testlink/templates/deployment.yaml
  stable/testlink/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4659 [stable/suitecrm] Refactor image property in values.yaml
  stable/suitecrm/Chart.yaml
  stable/suitecrm/README.md
  stable/suitecrm/templates/deployment.yaml
  stable/suitecrm/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4658 [stable/sugarcrm] Refactor image property in values.yaml
  stable/sugarcrm/Chart.yaml
  stable/sugarcrm/README.md
  stable/sugarcrm/templates/deployment.yaml
  stable/sugarcrm/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4656 [stable/prestashop] Refactor image property in values.yaml
  stable/prestashop/Chart.yaml
  stable/prestashop/README.md
  stable/prestashop/templates/deployment.yaml
  stable/prestashop/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4657 [stable/redmine] Refactor image property in values.yaml
  stable/redmine/Chart.yaml
  stable/redmine/README.md
  stable/redmine/templates/deployment.yaml
  stable/redmine/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4655 [stable/phpbb] Refactor image property in values.yaml
  stable/phpbb/Chart.yaml
  stable/phpbb/README.md
  stable/phpbb/templates/deployment.yaml
  stable/phpbb/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4653 [stable/parse] Refactor image property in values.yaml
  stable/parse/Chart.yaml
  stable/parse/README.md
  stable/parse/templates/dashboard-deployment.yaml
  stable/parse/templates/server-deployment.yaml
  stable/parse/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4652 [stable/owncloud] Refactor image property in values.yaml
  stable/owncloud/Chart.yaml
  stable/owncloud/README.md
  stable/owncloud/templates/deployment.yaml
  stable/owncloud/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4651 [stable/osclass] Refactor image property in values.yaml
  stable/osclass/Chart.yaml
  stable/osclass/README.md
  stable/osclass/templates/deployment.yaml
  stable/osclass/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4645 [stable/mediawiki] Refactor image property in values.yaml
  stable/mediawiki/Chart.yaml
  stable/mediawiki/README.md
  stable/mediawiki/templates/deployment.yaml
  stable/mediawiki/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4644 [stable/mariadb] Refactor image property in values.yaml
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
  stable/mariadb/templates/deployment.yaml
  stable/mariadb/templates/test-runner.yaml
  stable/mariadb/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4643 [stable/magento] Refactor image property in values.yaml
  stable/magento/Chart.yaml
  stable/magento/README.md
  stable/magento/templates/deployment.yaml
  stable/magento/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4642 [stable/joomla] Refactor image property in values.yaml
  stable/joomla/Chart.yaml
  stable/joomla/README.md
  stable/joomla/templates/deployment.yaml
  stable/joomla/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4641 [stable/jasperreports] Refactor image property in values.yaml
  stable/jasperreports/Chart.yaml
  stable/jasperreports/README.md
  stable/jasperreports/templates/deployment.yaml
  stable/jasperreports/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4637 [stable/dokuwiki] Refactor image property in values.yaml
  stable/dokuwiki/Chart.yaml
  stable/dokuwiki/README.md
  stable/dokuwiki/templates/deployment.yaml
  stable/dokuwiki/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4640 [stable/ghost] Refactor image property in values.yaml
  stable/ghost/Chart.yaml
  stable/ghost/README.md
  stable/ghost/templates/deployment.yaml
  stable/ghost/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4683 Address PR for move to stable PR
  incubator/chartmuseum/Chart.yaml
  incubator/chartmuseum/README.md
  incubator/chartmuseum/templates/NOTES.txt
  incubator/chartmuseum/templates/deployment.yaml
  incubator/chartmuseum/templates/pvc.yaml
  incubator/chartmuseum/templates/secret.yaml
  incubator/chartmuseum/templates/service.yaml
  incubator/chartmuseum/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4698 Add appVersion for luigi
  stable/luigi/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4552 Update ethereum/README.md
  stable/ethereum/Chart.yaml
  stable/ethereum/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3564 Add stable/unbound
  stable/unbound/.helmignore
  stable/unbound/Chart.yaml
  stable/unbound/README.md
  stable/unbound/templates/NOTES.txt
  stable/unbound/templates/_helpers.tpl
  stable/unbound/templates/configmap.yaml
  stable/unbound/templates/deployment.yaml
  stable/unbound/templates/disruption_budget.yaml
  stable/unbound/templates/service.yaml
  stable/unbound/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4555 Update gocd/README.md
  stable/gocd/Chart.yaml
  stable/gocd/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4559 Update jenkins/README.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4563 fix typo in gcp-night-king values.yaml
  stable/gcp-night-king/Chart.yaml
  stable/gcp-night-king/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4566 fix typo in quassel readme
  stable/quassel/Chart.yaml
  stable/quassel/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4582 fix typo in rabbitmq-ha/values.yaml
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4622 Add appVersion for uchiwa
  stable/uchiwa/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4623 Add appVersion for telegraf
  stable/telegraf/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4616 JanusGraph helm chart - initial commit
  stable/janusgraph/.helmignore
  stable/janusgraph/Chart.yaml
  stable/janusgraph/README.md
  stable/janusgraph/requirements.yaml
  stable/janusgraph/templates/NOTES.txt
  stable/janusgraph/templates/_helpers.tpl
  stable/janusgraph/templates/configmap.yaml
  stable/janusgraph/templates/deployment.yaml
  stable/janusgraph/templates/pvc.yaml
  stable/janusgraph/templates/service.yaml
  stable/janusgraph/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4625 Add home and appVersion for sumokube
  stable/sumokube/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4626 Add home key for stackdriver-exporter
  stable/stackdriver-exporter/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4628 Add home key for spartakus
  stable/spartakus/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4630 Add appVersion key for spark
  stable/spark/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4631 Add appVersion key for sensu
  stable/sensu/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4636 Add appVersion key for rocketchat
  stable/rocketchat/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4682 Add rbac and serviceaccount for kube-spot-termination-notice-handler chart
  incubator/kube-spot-termination-notice-handler/Chart.yaml
  incubator/kube-spot-termination-notice-handler/README.md
  incubator/kube-spot-termination-notice-handler/templates/_helpers.tpl
  incubator/kube-spot-termination-notice-handler/templates/daemonset.yaml
  incubator/kube-spot-termination-notice-handler/templates/rbac.yaml
  incubator/kube-spot-termination-notice-handler/templates/serviceaccount.yaml
  incubator/kube-spot-termination-notice-handler/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4689 Add appVersion for rethinkdb
  stable/rethinkdb/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4691 Add appVersion key for openvpn
  stable/openvpn/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4695 Add appVersion key for memcached
  stable/memcached/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4700 Add appVersion for locust
  stable/locust/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4702 Add appVersion key for linkerd
  stable/linkerd/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4703 Add appVersion key for lamp
  stable/lamp/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4522 [stable/traefik] Add Entrypoint whiteListSourceRange support
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/_helpers.tpl
  stable/traefik/templates/configmap.yaml
  stable/traefik/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4553 Update kong/README.md
  stable/kong/Chart.yaml
  stable/kong/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4583 fix typo in osclass/README.md
  stable/osclass/Chart.yaml
  stable/osclass/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4738 correct miss spelling in chartmuseum
  incubator/chartmuseum/Chart.yaml
  incubator/chartmuseum/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4723 Add appVersion key for kafka
  incubator/kafka/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4739 [incubator/chartmuseum] Introduce multi-tenancy option
  incubator/chartmuseum/Chart.yaml
  incubator/chartmuseum/README.md
  incubator/chartmuseum/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4672 fix grammar_mistake
  stable/concourse/Chart.yaml
  stable/concourse/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4542 [stable/concourse] Update Concourse to 3.10
  stable/concourse/Chart.yaml
  stable/concourse/README.md
  stable/concourse/templates/worker-statefulset.yaml
  stable/concourse/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4745 Bump cockroachdb chart to version 2.0.0
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/README.md
  stable/cockroachdb/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4611 Fix missing ghost.fullname in template call.
  stable/ghost/Chart.yaml
  stable/ghost/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4728 Add appVersion for webpagetest-server
  incubator/webpagetest-server/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4726 Add home and appVersion for redis-cache
  incubator/redis-cache/Chart.yaml
  incubator/redis-cache/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4725 Add appVersion key for mysqlha
  incubator/mysqlha/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4724 Add appVersion for kube-registry-proxy
  incubator/kube-registry-proxy/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3983 [stable/nginx-ingress] Add support for extraContainers, extraVolumeMounts and extraVolumes
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-daemonset.yaml
  stable/nginx-ingress/templates/controller-deployment.yaml
  stable/nginx-ingress/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4579 Typo fix in webpagetest-agent/README.md
  incubator/webpagetest-agent/Chart.yaml
  incubator/webpagetest-agent/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4694 Add home and appVersion key for minecraft
  stable/minecraft/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4705 Add appVersion for kube-ops-view
  stable/kube-ops-view/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4715 Add appVersion key for heapster
  stable/heapster/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4716 Add appVersion key for gcloud-sqlproxy
  stable/gcloud-sqlproxy/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4718 Add appVersion key for factorio
  stable/factorio/Chart.yaml
  stable/factorio/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4719 Add appVersion for cassandra
  incubator/cassandra/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4752 [stable/osclass] Fix wrong image format
  stable/osclass/Chart.yaml
  stable/osclass/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4743 Update redis/templates/NOTES.txt
  stable/redis/Chart.yaml
  stable/redis/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4721 Add appVersion key for elasticsearch
  incubator/elasticsearch/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4756 Add home key for elasticsearch-exporter
  stable/elasticsearch-exporter/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4570 stable/metallb: update to 0.5.0
  stable/metallb/Chart.yaml
  stable/metallb/README.md
  stable/metallb/templates/NOTES.txt
  stable/metallb/templates/config.yaml
  stable/metallb/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4757 Add home key for elastalert
  stable/elastalert/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4761 Add home key for fluentd
  incubator/fluentd/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4760 Add home key for fluentd-elasticsearch
  incubator/fluentd-elasticsearch/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4068 Check the health endpoint to see if Vault has been unsealed
  incubator/vault/Chart.yaml
  incubator/vault/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4046 [stable/neo4j] Fix dataVolume Persistence
  stable/neo4j/Chart.yaml
  stable/neo4j/README.md
  stable/neo4j/templates/core-statefulset.yaml
  stable/neo4j/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4758 Add home key for acs-engine-autoscaler
  stable/acs-engine-autoscaler/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4613 Minor Keel upgrade 0.4.2 -> 0.4.7
  stable/keel/Chart.yaml
  stable/keel/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3902 Add incubator/vaultingkube chart
  incubator/vaultingkube/.helmignore
  incubator/vaultingkube/Chart.yaml
  incubator/vaultingkube/README.md
  incubator/vaultingkube/templates/NOTES.txt
  incubator/vaultingkube/templates/_helpers.tpl
  incubator/vaultingkube/templates/deployment.yaml
  incubator/vaultingkube/templates/rbac.yaml
  incubator/vaultingkube/templates/serviceaccount.yaml
  incubator/vaultingkube/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4668 [stable/minio] Support for Minio GCS gateway
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/templates/deployment.yaml
  stable/minio/templates/secrets.yaml
  stable/minio/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4515 Added Elasticsearch Curator chart
  incubator/elasticsearch-curator/.helmignore
  incubator/elasticsearch-curator/Chart.yaml
  incubator/elasticsearch-curator/OWNERS
  incubator/elasticsearch-curator/README.md
  incubator/elasticsearch-curator/templates/NOTES.txt
  incubator/elasticsearch-curator/templates/_helpers.tpl
  incubator/elasticsearch-curator/templates/configmap.yaml
  incubator/elasticsearch-curator/templates/cronjob.yaml
  incubator/elasticsearch-curator/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4740 stable/jasperreports: Small fixes in README
  stable/jasperreports/Chart.yaml
  stable/jasperreports/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4543 fluent-bit pod annotation support
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/templates/daemonset.yaml
  stable/fluent-bit/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4747 fix typo in gocd
  incubator/gocd/Chart.yaml
  incubator/gocd/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4741 Allow the configuration of liveness and readiness times
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/README.md
  stable/mongodb-replicaset/templates/mongodb-statefulset.yaml
  stable/mongodb-replicaset/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4751 fix typo in opencart
  stable/opencart/Chart.yaml
  stable/opencart/README.md
  stable/opencart/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4774 fix zookeeper supported kubernetes version
  incubator/zookeeper/Chart.yaml
  incubator/zookeeper/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4755 Add home and appVersion keys for sentry-kubernetes
  incubator/sentry-kubernetes/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4681 [stable/rabbitmq-ha] Fix NOTES
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm, size/S

#4580 [dex] - initial chart for coreos/dex
  stable/dex/.helmignore
  stable/dex/Chart.yaml
  stable/dex/templates/NOTES.txt
  stable/dex/templates/_helpers.tpl
  stable/dex/templates/deployment.yaml
  stable/dex/templates/job.yaml
  stable/dex/templates/rolebinding.yaml
  stable/dex/templates/secret.yaml
  stable/dex/templates/service.yaml
  stable/dex/templates/serviceaccount.yaml
  stable/dex/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4701 Add MSSQL Master DB persistence
  stable/mssql-linux/Chart.yaml
  stable/mssql-linux/templates/deployment.yaml
  stable/mssql-linux/templates/pvc-master.yaml
  stable/mssql-linux/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4775 update selenium readme
  stable/selenium/Chart.yaml
  stable/selenium/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4610 [stable/rabbitmq-ha] Clustering fixes
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/templates/configmap.yaml
  stable/rabbitmq-ha/templates/service-discovery.yaml
  stable/rabbitmq-ha/templates/statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4114 [stable/rabbitmq-ha] Add option to use existing certificate
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/templates/secret.yaml
  stable/rabbitmq-ha/templates/statefulset.yaml
  stable/rabbitmq-ha/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#2743 adding redis-exporter chart
  stable/prometheus-redis-exporter/.helmignore
  stable/prometheus-redis-exporter/Chart.yaml
  stable/prometheus-redis-exporter/README.md
  stable/prometheus-redis-exporter/templates/NOTES.txt
  stable/prometheus-redis-exporter/templates/_helpers.tpl
  stable/prometheus-redis-exporter/templates/deployment.yaml
  stable/prometheus-redis-exporter/templates/service.yaml
  stable/prometheus-redis-exporter/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4707 Readme fix: default version is 0.12.0
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4783 Update version!
  stable/concourse/Chart.yaml
  stable/concourse/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4786 update readme of traefik
  stable/traefik/Chart.yaml
  stable/traefik/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4771 [drone] Fix ingress path for nginx-ingress
  incubator/drone/Chart.yaml
  incubator/drone/templates/ingress.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4571 [stable/fluent-bit] Cater for full set of Elastic Output Plugin parameters (Auth & TLS)
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/_helpers.tpl
  stable/fluent-bit/templates/cluster-rolebinding.yaml
  stable/fluent-bit/templates/config.yaml
  stable/fluent-bit/templates/daemonset.yaml
  stable/fluent-bit/templates/secret.yaml
  stable/fluent-bit/templates/serviceaccount.yaml
  stable/fluent-bit/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4279 [stable/tensorflow-serving] generic tensorflow model server support
  stable/tensorflow-serving/.helmignore
  stable/tensorflow-serving/Chart.yaml
  stable/tensorflow-serving/README.md
  stable/tensorflow-serving/models/mnist-export.tar.gz
  stable/tensorflow-serving/templates/NOTES.txt
  stable/tensorflow-serving/templates/_helpers.tpl
  stable/tensorflow-serving/templates/deployment.yaml
  stable/tensorflow-serving/templates/pvc.yaml
  stable/tensorflow-serving/templates/service.yaml
  stable/tensorflow-serving/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4792 fix typo in osclass/README.md
  stable/osclass/Chart.yaml
  stable/osclass/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4801 fix typo in quassel
  stable/quassel/Chart.yaml
  stable/quassel/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4800 fix README of SQL Server
  stable/mssql-linux/Chart.yaml
  stable/mssql-linux/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4799 fix readme.md of keycloak
  incubator/keycloak/Chart.yaml
  incubator/keycloak/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4797 fix typo in orangehrm/README.md
  stable/orangehrm/Chart.yaml
  stable/orangehrm/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4796 fix typo in prometheus/values.yaml
  stable/prometheus/Chart.yaml
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4795 fix typo in sugarcrm/README.md
  stable/sugarcrm/Chart.yaml
  stable/sugarcrm/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4794 fix typo in prestashop/README.md
  stable/prestashop/Chart.yaml
  stable/prestashop/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4793 fix typo in rabbitmq-ha/values.yaml
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4790 fix typo in owncloud/README.md
  stable/owncloud/Chart.yaml
  stable/owncloud/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4788 fix typo in testlink/README.md
  stable/testlink/Chart.yaml
  stable/testlink/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4784 Create SA for web component (fixes #4767)
  stable/concourse/Chart.yaml
  stable/concourse/templates/web-serviceaccount.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4777 [stable/artifactory] fixed support for ingress and existingPVC
  stable/artifactory/Chart.yaml
  stable/artifactory/README.md
  stable/artifactory/requirements.lock
  stable/artifactory/templates/artifactory-deployment.yaml
  stable/artifactory/templates/ingress.yaml
  stable/artifactory/templates/nginx-deployment.yaml
  stable/artifactory/templates/nginx-pvc.yaml
  stable/artifactory/templates/nginx-service.yaml
  stable/artifactory/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M
