Repository helm/charts, pull requests merged in 2018-07, with the labels that each got.

#6291 add chart for cerebro
  stable/cerebro/.helmignore
  stable/cerebro/Chart.yaml
  stable/cerebro/OWNERS
  stable/cerebro/README.md
  stable/cerebro/templates/NOTES.txt
  stable/cerebro/templates/_helpers.tpl
  stable/cerebro/templates/deployment.yaml
  stable/cerebro/templates/ingress.yaml
  stable/cerebro/templates/service.yaml
  stable/cerebro/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5234 Adding tomcat 7.0 chart
  stable/tomcat/Chart.yaml
  stable/tomcat/README.md
  stable/tomcat/templates/NOTES.txt
  stable/tomcat/templates/_helpers.tpl
  stable/tomcat/templates/appsrv-svc.yaml
  stable/tomcat/templates/appsrv.yaml
  stable/tomcat/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#6298 [stable/gcloud-sqlproxy] optional secret creation
  stable/gcloud-sqlproxy/Chart.yaml
  stable/gcloud-sqlproxy/README.md
  stable/gcloud-sqlproxy/templates/deployment.yaml
  stable/gcloud-sqlproxy/templates/secrets.yaml
  stable/gcloud-sqlproxy/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6260 [incubator/zookeeper] small typo fix in README.md
  incubator/zookeeper/Chart.yaml
  incubator/zookeeper/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6263 [stable/openldap] typo fix: persitent->persistent
  stable/openldap/Chart.yaml
  stable/openldap/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6342 [stable/keel] update to v0.9.5
  stable/keel/Chart.yaml
  stable/keel/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5198 Bug fix: Add if condition to configurtion mounting section, and menti…
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6186 [stable/nginx-ingress] disable Cluster roles if is a scope ingress
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/templates/clusterrole.yaml
  stable/nginx-ingress/templates/clusterrolebinding.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6262 [incubator/cassandra] Typo fix: persitent->persistent
  incubator/cassandra/Chart.yaml
  incubator/cassandra/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6269 [stable/gocd]Typo fix: heath check->health check
  stable/gocd/Chart.yaml
  stable/gocd/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6348 kafka namespace documentation fix
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6387 added annotations for node-exporter-daemonset
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/node-exporter-daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6122 [stable/jenkins] Make jenkins master pod security context optional
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/jenkins-master-deployment.yaml
  stable/jenkins/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6343 [postgresql] Set update strategy to Recreate.
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5643 [stable/traefik] Minimize downtime during deploy
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/deployment.yaml
  stable/traefik/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5861 [incubator/fluentd-cloudwatch] Update _helpers.tpl template to current version
  incubator/fluentd-cloudwatch/Chart.yaml
  incubator/fluentd-cloudwatch/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/S

#5142 [incubator/elasticsearch] Configurable override names
  incubator/elasticsearch/Chart.yaml
  incubator/elasticsearch/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/S

#2044 [incubator/patroni] Use storageClassName for patroni.
  incubator/patroni/Chart.yaml
  incubator/patroni/templates/statefulset-patroni.yaml
  incubator/patroni/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6328 [stable/drone] Add nodeSelector config parameter
  stable/drone/Chart.yaml
  stable/drone/README.md
  stable/drone/templates/deployment-agent.yaml
  stable/drone/templates/deployment-server.yaml
  stable/drone/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6319 [incubator/haproxy-ingress] Add default-ssl-certificate flag configuration
  incubator/haproxy-ingress/Chart.yaml
  incubator/haproxy-ingress/README.md
  incubator/haproxy-ingress/templates/controller-daemonset.yaml
  incubator/haproxy-ingress/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6401 make config map name unique
  incubator/elasticsearch-curator/Chart.yaml
  incubator/elasticsearch-curator/templates/configmap.yaml
  incubator/elasticsearch-curator/templates/cronjob.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5632 adding JFrog Mission control
  stable/mission-control/.helmignore
  stable/mission-control/Chart.yaml
  stable/mission-control/README.md
  stable/mission-control/charts/elasticsearch/.helmignore
  stable/mission-control/charts/elasticsearch/Chart.yaml
  stable/mission-control/charts/elasticsearch/README.md
  stable/mission-control/charts/elasticsearch/templates/NOTES.txt
  stable/mission-control/charts/elasticsearch/templates/_helpers.tpl
  stable/mission-control/charts/elasticsearch/templates/elasticsearch-deployment.yaml
  stable/mission-control/charts/elasticsearch/templates/elasticsearch-pvc.yaml
  stable/mission-control/charts/elasticsearch/templates/elasticsearch-secret.yaml
  stable/mission-control/charts/elasticsearch/templates/elasticsearch-setup-scripts.yaml
  stable/mission-control/charts/elasticsearch/templates/elasticsearch-svc.yaml
  stable/mission-control/charts/elasticsearch/values.yaml
  stable/mission-control/ci/test-values.yaml
  stable/mission-control/requirements.lock
  stable/mission-control/requirements.yaml
  stable/mission-control/templates/NOTES.txt
  stable/mission-control/templates/_helpers.tpl
  stable/mission-control/templates/hooks/create-user.yaml
  stable/mission-control/templates/ingress.yaml
  stable/mission-control/templates/insight-executor-deployment.yaml
  stable/mission-control/templates/insight-executor-pvc.yaml
  stable/mission-control/templates/insight-executor-svc.yaml
  stable/mission-control/templates/insight-scheduler-deployment.yaml
  stable/mission-control/templates/insight-scheduler-svc.yaml
  stable/mission-control/templates/insight-server-deployment.yaml
  stable/mission-control/templates/insight-server-svc.yaml
  stable/mission-control/templates/mission-control-certs.yaml
  stable/mission-control/templates/mission-control-deployment.yaml
  stable/mission-control/templates/mission-control-pvc.yaml
  stable/mission-control/templates/mission-control-svc.yaml
  stable/mission-control/templates/mongodb-secret.yaml
  stable/mission-control/templates/mongodb-setup-scripts.yaml
  stable/mission-control/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#6117 selenium: use generic env var, not oracle specific env var
  stable/selenium/Chart.yaml
  stable/selenium/templates/chrome-deployment.yaml
  stable/selenium/templates/chromeDebug-deployment.yaml
  stable/selenium/templates/firefox-deployment.yaml
  stable/selenium/templates/firefoxDebug-deployment.yaml
  stable/selenium/templates/hub-deployment.yaml
  stable/selenium/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6235 [stable/influxdb] Allow alternate schedulers
  stable/influxdb/Chart.yaml
  stable/influxdb/templates/deployment.yaml
  stable/influxdb/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6299 [stable/inbucket] Add OWNERS file
  stable/inbucket/.helmignore
  stable/inbucket/Chart.yaml
  stable/inbucket/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S

#6306 [incubator/etcd] Prevent removal of data from INITIAL_CLUSTER_SIZE pods
  incubator/etcd/Chart.yaml
  incubator/etcd/templates/statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6302 Adding optional sidecar containers and volumes
  stable/memcached/Chart.yaml
  stable/memcached/README.md
  stable/memcached/templates/statefulset.yaml
  stable/memcached/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6315 [incubator/couchdb] Allow overriding of full name in couchdb chart
  incubator/couchdb/Chart.yaml
  incubator/couchdb/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/S

#6258 replaced single line DOMAIN in openvpn config with multi-line DOMAIN-…
  stable/openvpn/Chart.yaml
  stable/openvpn/templates/config-openvpn.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6267 [Concourse] add nodeSelector for web
  stable/concourse/Chart.yaml
  stable/concourse/README.md
  stable/concourse/templates/web-deployment.yaml
  stable/concourse/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6000 [stable/selenium] Add hub serviceLoadBalancerIP property
  stable/selenium/Chart.yaml
  stable/selenium/README.md
  stable/selenium/templates/hub-service.yaml
  stable/selenium/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6430 Elasticsearch tolerations
  incubator/elasticsearch/Chart.yaml
  incubator/elasticsearch/README.md
  incubator/elasticsearch/templates/client-deployment.yaml
  incubator/elasticsearch/templates/data-statefulset.yaml
  incubator/elasticsearch/templates/master-statefulset.yaml
  incubator/elasticsearch/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6393 fix typo
  stable/sonarqube/Chart.yaml
  stable/sonarqube/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6439 upgrade cerebro to 0.8.1
  stable/cerebro/Chart.yaml
  stable/cerebro/README.md
  stable/cerebro/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6292 [incubator/common] more logical port
  incubator/common/Chart.yaml
  incubator/common/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#6443 [stable/rabbitmq-ha] align to using same headless config as prometheus
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6406 [stable/wordpress] Add pod tolerations and affinity.
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
  stable/wordpress/templates/deployment.yaml
  stable/wordpress/values-production.yaml
  stable/wordpress/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5776 [stable/gcloud-endpoints] Add appVersion and typo fix: tables lists
  stable/gcloud-endpoints/Chart.yaml
  stable/gcloud-endpoints/README.md
  stable/gcloud-endpoints/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5948 [incubator/mysqlha] Allow configuration of MySQL master and slaves from values.yaml
  incubator/mysqlha/Chart.yaml
  incubator/mysqlha/README.md
  incubator/mysqlha/templates/configmap.yaml
  incubator/mysqlha/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6279 Added 'azuremonitor-containers' chart in incubator
  incubator/azuremonitor-containers/.helmignore
  incubator/azuremonitor-containers/Chart.yaml
  incubator/azuremonitor-containers/OWNERS
  incubator/azuremonitor-containers/README.md
  incubator/azuremonitor-containers/templates/NOTES.txt
  incubator/azuremonitor-containers/templates/_helpers.tpl
  incubator/azuremonitor-containers/templates/omsagent-daemonset.yaml
  incubator/azuremonitor-containers/templates/omsagent-deployment.yaml
  incubator/azuremonitor-containers/templates/omsagent-rbac.yaml
  incubator/azuremonitor-containers/templates/omsagent-rs-configmap.yaml
  incubator/azuremonitor-containers/templates/omsagent-secret.yaml
  incubator/azuremonitor-containers/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#5853 [stable/falco] Add Falco chart
  stable/falco/.helmignore
  stable/falco/Chart.yaml
  stable/falco/OWNERS
  stable/falco/README.md
  stable/falco/rules/falco_rules.local.yaml
  stable/falco/rules/falco_rules.yaml
  stable/falco/templates/NOTES.txt
  stable/falco/templates/_helpers.tpl
  stable/falco/templates/clusterrole.yaml
  stable/falco/templates/clusterrolebinding.yaml
  stable/falco/templates/configmap-rules.yaml
  stable/falco/templates/configmap.yaml
  stable/falco/templates/daemonset.yaml
  stable/falco/templates/deployment.yaml
  stable/falco/templates/serviceaccount.yaml
  stable/falco/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#6454 [stable/eventrouter] Add new configs
  stable/eventrouter/Chart.yaml
  stable/eventrouter/README.md
  stable/eventrouter/templates/configmap.yaml
  stable/eventrouter/templates/deployment.yaml
  stable/eventrouter/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6458 [stable/rabbitmq] Fix some typos
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6463 [stable/dokuwiki] Delete duplicated word and some small typos
  stable/dokuwiki/Chart.yaml
  stable/dokuwiki/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6455 [stable/falco] Fix some small typos
  stable/falco/Chart.yaml
  stable/falco/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4291 Add the ability to add extra env variables
  incubator/fluentd-cloudwatch/Chart.yaml
  incubator/fluentd-cloudwatch/README.md
  incubator/fluentd-cloudwatch/templates/daemonset.yaml
  incubator/fluentd-cloudwatch/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6392 fix typo
  stable/nats/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6445 add configurable path for liveness / readinessProbe
  stable/sonatype-nexus/Chart.yaml
  stable/sonatype-nexus/README.md
  stable/sonatype-nexus/templates/deployment.yaml
  stable/sonatype-nexus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6487 cert-manager: fast-forward to upstream 90742f35
  stable/cert-manager/Chart.yaml
  stable/cert-manager/README.md
  stable/cert-manager/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6499 Adding new parameter to Phabricator chart
  stable/phabricator/Chart.yaml
  stable/phabricator/README.md
  stable/phabricator/templates/deployment.yaml
  stable/phabricator/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6479 added rootUser to values.yaml
  stable/ghost/Chart.yaml
  stable/ghost/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6514 upgrade to curator 5.5.4
  incubator/elasticsearch-curator/Chart.yaml
  incubator/elasticsearch-curator/README.md
  incubator/elasticsearch-curator/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6498 [stable/keycloak] Upgrade to 4.1.0.Final
  stable/keycloak/Chart.yaml
  stable/keycloak/README.md
  stable/keycloak/requirements.lock
  stable/keycloak/requirements.yaml
  stable/keycloak/templates/test/test-pod.yaml
  stable/keycloak/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6515 [stable/chartmuseum] upgrade to app version 0.7.1
  stable/chartmuseum/Chart.yaml
  stable/chartmuseum/README.md
  stable/chartmuseum/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6154 [stable/gocd] Use the gocd-agent-docker-dind image of the tag same as of GoCD app version
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/templates/configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5908 Fix Kafka document
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6551 [stable/wordpress] Fix appVersion
  stable/wordpress/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6549 [stable/moodle] Fix appVersion
  stable/moodle/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6550 [stable/redis] Fix appVersion
  stable/redis/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6554 [stable/mongodb] Fix appVersion
  stable/mongodb/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6555 [stable/dokuwiki] Fix appVersion
  stable/dokuwiki/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6553 [stable/mariadb] Fix appVersion
  stable/mariadb/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6557 Update Zookeeper dependency
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
  incubator/kafka/requirements.lock
  incubator/kafka/requirements.yaml
  incubator/kafka/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#6565 [stable/wordpress] Typo fix in README
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6558 [incubator/elastic-stack] Add fluent-bit option
  incubator/elastic-stack/Chart.yaml
  incubator/elastic-stack/requirements.lock
  incubator/elastic-stack/requirements.yaml
  incubator/elastic-stack/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6511 [stable/prometheus-cloudwatch-exporter] Fixed secret variable parsing for access/secret keys.
  stable/prometheus-cloudwatch-exporter/Chart.yaml
  stable/prometheus-cloudwatch-exporter/templates/deployment.yaml
  stable/prometheus-cloudwatch-exporter/templates/secrets.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6496 Deployment annotations
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/kube-state-metrics-deployment.yaml
  stable/prometheus/templates/server-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6425 [incubator/elasticsearch] updated elasticsearch to version 6.2.4
  incubator/elasticsearch/Chart.yaml
  incubator/elasticsearch/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6412 [stable/docker-registry] remove s3 credential env vars if not specified
  stable/docker-registry/Chart.yaml
  stable/docker-registry/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6594 [redis] Bump redis_exporter to v0.20.2
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/values-production.yaml
  stable/redis/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6596 [stable/sysdig] Improvements to Sysdig Helm Chart
  stable/sysdig/CHANGELOG.md
  stable/sysdig/Chart.yaml
  stable/sysdig/README.md
  stable/sysdig/templates/daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6600 [stable/falco] Add Falco NATS output integration
  stable/falco/CHANGELOG.md
  stable/falco/Chart.yaml
  stable/falco/README.md
  stable/falco/templates/configmap.yaml
  stable/falco/templates/daemonset.yaml
  stable/falco/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6377 [stable/datadog]: update labels to match recommended standards
  stable/datadog/Chart.yaml
  stable/datadog/templates/autoconf-configmap.yaml
  stable/datadog/templates/checksd-configmap.yaml
  stable/datadog/templates/clusterrole.yaml
  stable/datadog/templates/clusterrolebinding.yaml
  stable/datadog/templates/confd-configmap.yaml
  stable/datadog/templates/daemonset.yaml
  stable/datadog/templates/deployment.yaml
  stable/datadog/templates/secrets.yaml
  stable/datadog/templates/service.yaml
  stable/datadog/templates/serviceaccount.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6610 [incubator/elasticsearch-curator] Add support for priorityClasses
  incubator/elasticsearch-curator/Chart.yaml
  incubator/elasticsearch-curator/README.md
  incubator/elasticsearch-curator/templates/cronjob.yaml
  incubator/elasticsearch-curator/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6152 [stable/minio] Bring back config map support
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/templates/configmap.yaml
  stable/minio/templates/deployment.yaml
  stable/minio/templates/pvc.yaml
  stable/minio/templates/statefulset.yaml
  stable/minio/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#6578 [stable/prometheus] support priorityClasses
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/alertmanager-deployment.yaml
  stable/prometheus/templates/kube-state-metrics-deployment.yaml
  stable/prometheus/templates/node-exporter-daemonset.yaml
  stable/prometheus/templates/pushgateway-deployment.yaml
  stable/prometheus/templates/server-deployment.yaml
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6625 cert-manager: fast-forward to upstream 777ce6f4
  stable/cert-manager/Chart.yaml
  stable/cert-manager/README.md
  stable/cert-manager/templates/_helpers.tpl
  stable/cert-manager/templates/deployment.yaml
  stable/cert-manager/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6623 upgrade to latest prometheus release 2.3.2 and alertmanager 0.15.1
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6441 [stable/concourse] add support for custom envvars for the web containers
  stable/concourse/Chart.yaml
  stable/concourse/README.md
  stable/concourse/templates/web-deployment.yaml
  stable/concourse/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6280 [stable/kanister-operator] RBAC changes and kanister profile creation
  stable/kanister-operator/Chart.yaml
  stable/kanister-operator/README.md
  stable/kanister-operator/charts/profile/.helmignore
  stable/kanister-operator/charts/profile/Chart.yaml
  stable/kanister-operator/charts/profile/README.md
  stable/kanister-operator/charts/profile/templates/NOTES.txt
  stable/kanister-operator/charts/profile/templates/_helpers.tpl
  stable/kanister-operator/charts/profile/templates/profile.yaml
  stable/kanister-operator/charts/profile/values.yaml
  stable/kanister-operator/templates/rbac.yaml
  stable/kanister-operator/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5813 [incubator/kube-spot-termination-notice-handler] Add Support for Tolerations
  incubator/kube-spot-termination-notice-handler/Chart.yaml
  incubator/kube-spot-termination-notice-handler/templates/daemonset.yaml
  incubator/kube-spot-termination-notice-handler/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6461 [stable/artifactory] livessProbed->livenessProbed
  stable/artifactory/Chart.yaml
  stable/artifactory/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6462 [stable/artifactory-ha] Typo fix: livessProbed->livenessProbed
  stable/artifactory-ha/Chart.yaml
  stable/artifactory-ha/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6282 [stable/mongodb-replicaset] Prometheus Metrics export
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/README.md
  stable/mongodb-replicaset/init/on-start.sh
  stable/mongodb-replicaset/templates/_helpers.tpl
  stable/mongodb-replicaset/templates/mongodb-metrics-secret.yaml
  stable/mongodb-replicaset/templates/mongodb-service.yaml
  stable/mongodb-replicaset/templates/mongodb-statefulset.yaml
  stable/mongodb-replicaset/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#6015 [stable/traefik] adding support for traefik wildcard certificates
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/_helpers.tpl
  stable/traefik/templates/configmap.yaml
  stable/traefik/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6584 [stable/elasticsearch-exporter] add support for priorityClasses
  stable/elasticsearch-exporter/Chart.yaml
  stable/elasticsearch-exporter/README.md
  stable/elasticsearch-exporter/templates/deployment.yaml
  stable/elasticsearch-exporter/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6586 [stable/oauth2-proxy] Add support for priorityClasses
  stable/oauth2-proxy/Chart.yaml
  stable/oauth2-proxy/README.md
  stable/oauth2-proxy/templates/deployment.yaml
  stable/oauth2-proxy/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6603 [stable/cluster-autoscaler] Add support for priorityClasses
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/README.md
  stable/cluster-autoscaler/templates/deployment.yaml
  stable/cluster-autoscaler/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6604 [stable/minio] Add support for priorityClasses
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/templates/deployment.yaml
  stable/minio/templates/statefulset.yaml
  stable/minio/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6606 [stable/external-dns] Add support for priorityClasses
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/deployment.yaml
  stable/external-dns/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6607 [stable/stolon] Add support for priorityClasses
  stable/stolon/Chart.yaml
  stable/stolon/README.md
  stable/stolon/templates/keeper-statefulset.yaml
  stable/stolon/templates/proxy-deployment.yaml
  stable/stolon/templates/sentinel-deployment.yaml
  stable/stolon/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6332 [stable/filebeat] filebeat fixes
  stable/filebeat/Chart.yaml
  stable/filebeat/templates/daemonset.yaml
  stable/filebeat/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3233 [stable/efs-provisioner] Chart for efs-provisioner, a Kubernetes external-storage provisioner
  stable/efs-provisioner/.helmignore
  stable/efs-provisioner/Chart.yaml
  stable/efs-provisioner/README.md
  stable/efs-provisioner/templates/NOTES.txt
  stable/efs-provisioner/templates/_helpers.tpl
  stable/efs-provisioner/templates/clusterrole.yaml
  stable/efs-provisioner/templates/clusterrolebinding.yaml
  stable/efs-provisioner/templates/deployment.yaml
  stable/efs-provisioner/templates/serviceaccount.yaml
  stable/efs-provisioner/templates/storageclass.yaml
  stable/efs-provisioner/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3345 [spark/stable] Added persistence for notebooks and configuration
  stable/spark/Chart.yaml
  stable/spark/README.md
  stable/spark/templates/spark-zeppelin-config-pvc.yaml
  stable/spark/templates/spark-zeppelin-deployment.yaml
  stable/spark/templates/spark-zeppelin-notebook-pvc.yaml
  stable/spark/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#6378 [incubator/spring-cloud-data-flow] Update to new SCDF version 1.5.2
  incubator/spring-cloud-data-flow/Chart.yaml
  incubator/spring-cloud-data-flow/README.md
  incubator/spring-cloud-data-flow/templates/metrics-deployment-rabbit.yaml
  incubator/spring-cloud-data-flow/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6581 [incubator/elasticsearch] add support for priorityClasses
  incubator/elasticsearch/Chart.yaml
  incubator/elasticsearch/README.md
  incubator/elasticsearch/templates/client-deployment.yaml
  incubator/elasticsearch/templates/data-statefulset.yaml
  incubator/elasticsearch/templates/master-statefulset.yaml
  incubator/elasticsearch/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6582 [stable/chaoskube] Support prioirtyClassNames
  stable/chaoskube/Chart.yaml
  stable/chaoskube/README.md
  stable/chaoskube/templates/deployment.yaml
  stable/chaoskube/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6608 [incubator/zookeeper] Add support for priorityClasses
  incubator/zookeeper/Chart.yaml
  incubator/zookeeper/templates/job-chroots.yaml
  incubator/zookeeper/templates/statefulset.yaml
  incubator/zookeeper/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6609 [stable/docker-registry] Add support for priorityClasses
  stable/docker-registry/Chart.yaml
  stable/docker-registry/README.md
  stable/docker-registry/templates/deployment.yaml
  stable/docker-registry/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6611 [stable/nginx-ingress] Add support for priorityClasses
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-daemonset.yaml
  stable/nginx-ingress/templates/controller-deployment.yaml
  stable/nginx-ingress/templates/default-backend-deployment.yaml
  stable/nginx-ingress/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6583 [stable/consul] Add support for priorityClasses
  stable/consul/Chart.yaml
  stable/consul/README.md
  stable/consul/templates/consul-statefulset.yaml
  stable/consul/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6602 Kong v0.14.0 support
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6616 [stable/verdaccio] deployment strategy, health check updates
  stable/verdaccio/Chart.yaml
  stable/verdaccio/README.md
  stable/verdaccio/templates/deployment.yaml
  stable/verdaccio/templates/service.yaml
  stable/verdaccio/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6585 [stable/kibana] Add support for priorityClasses
  stable/kibana/Chart.yaml
  stable/kibana/README.md
  stable/kibana/templates/deployment.yaml
  stable/kibana/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6595 Cerebro service annotations, image update and configuration overrides
  stable/cerebro/Chart.yaml
  stable/cerebro/README.md
  stable/cerebro/templates/configmap.yaml
  stable/cerebro/templates/deployment.yaml
  stable/cerebro/templates/service.yaml
  stable/cerebro/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6473 [stable/kiam] Adding gateway timeout for readiness probe of kiam server
  stable/kiam/Chart.yaml
  stable/kiam/templates/server-daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5901 [stable/kibana] Support custom labels on Service
  stable/kibana/Chart.yaml
  stable/kibana/README.md
  stable/kibana/templates/service.yaml
  stable/kibana/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3346 [spark/stable] Added Horizontal pod autoscaler according to documentation
  stable/spark/Chart.yaml
  stable/spark/README.md
  stable/spark/templates/spark-worker-hpa.yaml
  stable/spark/values.yaml
Labels: approved, cncf-cla: yes, lgtm, lifecycle/rotten, size/M

#6630 [Incubator/kafka] Upgrade kafka-exporter
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
  incubator/kafka/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6423 [incubator/logstash] updated logstash to version 6.3.1
  incubator/logstash/Chart.yaml
  incubator/logstash/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6338 [stable/concourse] Expose prometheus port in web service
  stable/concourse/Chart.yaml
  stable/concourse/templates/web-svc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6646 stable/cerebro: Add service labels support
  stable/cerebro/Chart.yaml
  stable/cerebro/README.md
  stable/cerebro/templates/service.yaml
  stable/cerebro/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6681 Add new parameter to configure Drupal Installation Profile
  stable/drupal/Chart.yaml
  stable/drupal/README.md
  stable/drupal/templates/deployment.yaml
  stable/drupal/templates/secrets.yaml
  stable/drupal/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6232 [ stable/concourse ] Add optional values for additional volumes and volumeMounts
  stable/concourse/Chart.yaml
  stable/concourse/README.md
  stable/concourse/templates/worker-statefulset.yaml
  stable/concourse/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6544 [stable/selenium] upgrade version to 3.13.0
  stable/selenium/Chart.yaml
  stable/selenium/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6680 [stable/minio] nodeport and externalips support added
  stable/minio/Chart.yaml
  stable/minio/templates/service.yaml
  stable/minio/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6617 [stable/owncloud] template owncloud.fullname in ingress.yaml
  stable/owncloud/Chart.yaml
  stable/owncloud/templates/ingress.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6684 [stable/redis] Add service account to metrics deployment
  stable/redis/Chart.yaml
  stable/redis/templates/metrics-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5850 Update Postgresql version within Concourse chart
  stable/concourse/Chart.yaml
  stable/concourse/requirements.lock
  stable/concourse/requirements.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6469 [stable/kuberos] (New Chart). Kuberos is a handy ODIC configurator so appropriate others can get kubectl config
  stable/kuberos/.helmignore
  stable/kuberos/Chart.yaml
  stable/kuberos/README.md
  stable/kuberos/templates/NOTES.txt
  stable/kuberos/templates/_helpers.tpl
  stable/kuberos/templates/configmap.yaml
  stable/kuberos/templates/deployment.yaml
  stable/kuberos/templates/ingress.yaml
  stable/kuberos/templates/secrets.yaml
  stable/kuberos/templates/service.yaml
  stable/kuberos/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#6685 [stable/redis] Add option to supply extra arguments for metrics
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/templates/metrics-deployment.yaml
  stable/redis/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6764 Bump up gocd version
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6740 incubator/kafka support for additional clouds
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
  incubator/kafka/templates/NOTES.txt
  incubator/kafka/templates/service-brokers-external.yaml
  incubator/kafka/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#5953 [stable/traefik] bump version to 1.6.3
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6780 stable/metrics-server: Add olemarkus to OWNERS
  stable/metrics-server/.helmignore
  stable/metrics-server/Chart.yaml
  stable/metrics-server/OWNERS
Labels: approved, cncf-cla: yes, lgtm

#6783 [stable/redis] move serviceAccountName out of if block
  stable/redis/Chart.yaml
  stable/redis/templates/metrics-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm

#6769 [stable/redis] Fixed typo in README
  stable/redis/Chart.yaml
  stable/redis/README.md
Labels: approved, cncf-cla: yes, lgtm

#6718 incubator/elasticsearch: Add `PodDisruptionBudgets`
  incubator/elasticsearch/Chart.yaml
  incubator/elasticsearch/templates/client-pdb.yaml
  incubator/elasticsearch/templates/data-pdb.yaml
  incubator/elasticsearch/templates/master-pdb.yaml
  incubator/elasticsearch/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6488 Metrics server specs
  stable/metrics-server/Chart.yaml
  stable/metrics-server/README.md
  stable/metrics-server/templates/metrics-server-deployment.yaml
  stable/metrics-server/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6744 [stable/metrics-server] Update RBAC to handle disabled kubelet read-only port
  stable/metrics-server/Chart.yaml
  stable/metrics-server/templates/cluster-role.yaml
Labels: approved, cncf-cla: yes, lgtm

#6792 Fix rabbitmq for non-root container
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/templates/statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm

#6811 Add security context in mongodb chart secondary node
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/statefulset-secondary-rs.yaml
Labels: approved, cncf-cla: yes, lgtm

#6726 [stable/verdaccio] Route all traffic to the service
  stable/verdaccio/Chart.yaml
  stable/verdaccio/templates/ingress.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6751 [stable/filebeat] added optional annotations to daemonset
  stable/filebeat/Chart.yaml
  stable/filebeat/README.md
  stable/filebeat/templates/daemonset.yaml
  stable/filebeat/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6562 [stable/newrelic-infrastructure] version 1.0.0 has been released
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/README.md
  stable/newrelic-infrastructure/templates/daemonset.yaml
  stable/newrelic-infrastructure/templates/rbac.yaml
  stable/newrelic-infrastructure/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6580 [fluentd-elasticsearch] updated docker image to 2.2.0 & disabled resource limits by default
  incubator/fluentd-elasticsearch/Chart.yaml
  incubator/fluentd-elasticsearch/README.md
  incubator/fluentd-elasticsearch/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6785 stable/metrics-server: Add kennethaasan to OWNERS
  stable/metrics-server/Chart.yaml
  stable/metrics-server/OWNERS
Labels: approved, cncf-cla: yes, lgtm

#6777 [stable/ark] Update Heptio Ark for v0.9.0
  stable/ark/Chart.yaml
  stable/ark/README.md
  stable/ark/templates/podvolumebackups.yaml
  stable/ark/templates/podvolumerestores.yaml
  stable/ark/templates/resticrepositories.yaml
  stable/ark/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6662 [stable/gcloud-sqlproxy] Allow for getting credentials via metadata
  stable/gcloud-sqlproxy/Chart.yaml
  stable/gcloud-sqlproxy/templates/NOTES.txt
  stable/gcloud-sqlproxy/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6516 [stable/prometheus-redis-exporter] add option to supply extra arguments
  stable/prometheus-redis-exporter/Chart.yaml
  stable/prometheus-redis-exporter/README.md
  stable/prometheus-redis-exporter/templates/deployment.yaml
  stable/prometheus-redis-exporter/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6167 Rookout Agent Chart
  stable/rookout/.helmignore
  stable/rookout/Chart.yaml
  stable/rookout/README.md
  stable/rookout/templates/NOTES.txt
  stable/rookout/templates/_helpers.tpl
  stable/rookout/templates/deployment.yaml
  stable/rookout/templates/service.yaml
  stable/rookout/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#6829 Use proper docker image for rabbitmq chart
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6808 Changed persistence.size to reflect actual values
  stable/sonarqube/Chart.yaml
  stable/sonarqube/README.md
Labels: approved, cncf-cla: yes, lgtm

#6620 [stable/metrics-server] Metrics server command arguments
  stable/metrics-server/Chart.yaml
  stable/metrics-server/README.md
  stable/metrics-server/templates/metrics-server-deployment.yaml
  stable/metrics-server/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6742 [prometheus-node-exporter] Add ability to customize labels and endpoints, Pod security policy
  stable/prometheus-node-exporter/Chart.yaml
  stable/prometheus-node-exporter/README.md
  stable/prometheus-node-exporter/templates/_helpers.tpl
  stable/prometheus-node-exporter/templates/daemonset.yaml
  stable/prometheus-node-exporter/templates/psp-clusterrole.yaml
  stable/prometheus-node-exporter/templates/psp-clusterrolebinding.yaml
  stable/prometheus-node-exporter/templates/psp.yaml
  stable/prometheus-node-exporter/templates/service.yaml
  stable/prometheus-node-exporter/templates/serviceaccount.yaml
  stable/prometheus-node-exporter/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6682 [stable/spotify-docker-gc] Support tolerations and node selectors
  stable/spotify-docker-gc/Chart.yaml
  stable/spotify-docker-gc/README.md
  stable/spotify-docker-gc/templates/daemonset.yaml
  stable/spotify-docker-gc/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6807 [stable/kibana] Added option to specify nodeport
  stable/kibana/Chart.yaml
  stable/kibana/README.md
  stable/kibana/templates/service.yaml
  stable/kibana/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6838 [stable/filebeat] Add support for priorityClasses
  stable/filebeat/Chart.yaml
  stable/filebeat/README.md
  stable/filebeat/templates/daemonset.yaml
  stable/filebeat/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6679 dex: configure gRPC and generate the certificates (CA/server/client) during deployment
  stable/dex/Chart.yaml
  stable/dex/config/openssl.conf
  stable/dex/templates/config-openssl.yaml
  stable/dex/templates/deployment.yaml
  stable/dex/templates/job-grpc-certs.yaml
  stable/dex/templates/job-web-certs.yaml
  stable/dex/templates/service.yaml
  stable/dex/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#6698 [tensorflow inception] add stable image and tag, fix gpu usage
  incubator/tensorflow-inception/Chart.yaml
  incubator/tensorflow-inception/README.md
  incubator/tensorflow-inception/templates/tensorflow-inception.yaml
  incubator/tensorflow-inception/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M
