Repository helm/charts, pull requests merged in 2018-11, with the labels that each got.

#8731 [stable/elasticsearch] Make pod annotations configurable for PodSecurityPolicy
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/README.md
  stable/elasticsearch/templates/podsecuritypolicy.yaml
  stable/elasticsearch/templates/role.yaml
  stable/elasticsearch/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#8953 [stable/logstash] Add externalTrafficPolicy config
  stable/logstash/Chart.yaml
  stable/logstash/README.md
  stable/logstash/templates/service.yaml
  stable/logstash/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#8911 Adding owner to the Datadog chart
  stable/datadog/Chart.yaml
  stable/datadog/OWNERS
Labels: Contribution Allowed, approved, lgtm, size/XS

#8963 [incubator/elastic-stack] Update Logstash chart version
  incubator/elastic-stack/Chart.yaml
  incubator/elastic-stack/requirements.lock
  incubator/elastic-stack/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#8767 [stable/rabbitmq-ha] Tolerate unready endpoints & podManagementPolicy
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/templates/service-discovery.yaml
  stable/rabbitmq-ha/templates/statefulset.yaml
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#8944 Adopting Helm chart best practices
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/README.md
  incubator/sparkoperator/templates/_helpers.tpl
  incubator/sparkoperator/templates/spark-namespace.yaml
  incubator/sparkoperator/templates/spark-operator-deployment.yaml
  incubator/sparkoperator/templates/spark-operator-rbac.yaml
  incubator/sparkoperator/templates/spark-operator-serviceaccount.yaml
  incubator/sparkoperator/templates/spark-rbac.yaml
  incubator/sparkoperator/templates/spark-serviceaccount.yaml
  incubator/sparkoperator/templates/webhook-cleanup-job.yaml
  incubator/sparkoperator/templates/webhook-init-job.yaml
  incubator/sparkoperator/templates/webhook-service.yaml
  incubator/sparkoperator/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#7795 Adding node-problem-detector stable chart
  stable/node-problem-detector/.helmignore
  stable/node-problem-detector/Chart.yaml
  stable/node-problem-detector/OWNERS
  stable/node-problem-detector/README.md
  stable/node-problem-detector/templates/NOTES.txt
  stable/node-problem-detector/templates/_helpers.tpl
  stable/node-problem-detector/templates/clusterrole.yaml
  stable/node-problem-detector/templates/clusterrolebinding.yaml
  stable/node-problem-detector/templates/daemonset.yaml
  stable/node-problem-detector/templates/serviceaccount.yaml
  stable/node-problem-detector/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#8919 [incubator/fluent-cloudwatch] Fix daemonset.yaml change podAnnotations to annotations
  incubator/fluentd-cloudwatch/Chart.yaml
  incubator/fluentd-cloudwatch/templates/daemonset.yaml
  incubator/fluentd-cloudwatch/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#8725 [stable/concourse] Correct typos related to some environment variables
  stable/concourse/Chart.yaml
  stable/concourse/templates/web-deployment.yaml
  stable/concourse/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#8825 [stable/fluent-bit] Fix indentation of extra params
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/templates/config.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#8930 [stable/redis] re-sync values-production.yaml with values.yaml
  stable/redis/Chart.yaml
  stable/redis/values-production.yaml
  stable/redis/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#8929 [stable/rabbitmq] re-sync values-production.yaml with values.yaml
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/values-production.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#8760 Fix Prometheus and Alertmanager templates to support routePrefix
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/templates/alertmanager/alertmanager.yaml
  stable/prometheus-operator/templates/alertmanager/ingress.yaml
  stable/prometheus-operator/templates/alertmanager/servicemonitor.yaml
  stable/prometheus-operator/templates/grafana/configmaps-datasources.yaml
  stable/prometheus-operator/templates/prometheus/ingress.yaml
  stable/prometheus-operator/templates/prometheus/prometheus.yaml
  stable/prometheus-operator/templates/prometheus/servicemonitor.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#8191 [stable/prometheus] Add example alert config (#966)
  stable/prometheus/Chart.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#8888 [stable/prometheus-operator] fix prometheus ruleSelector example
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#8931 [stable/redis] fix typos on README/comments for service.type
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/values-production.yaml
  stable/redis/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#8910 [stable/concourse] Allow the use of a specific image digest
  stable/concourse/Chart.yaml
  stable/concourse/templates/web-deployment.yaml
  stable/concourse/templates/worker-statefulset.yaml
  stable/concourse/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#8786 Better document cluster agent & Update chart
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/NOTES.txt
  stable/datadog/templates/agent-secret.yaml
  stable/datadog/templates/cluster-agent-deployment.yaml
  stable/datadog/templates/daemonset.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#8983 [stable/elastalert] Upgrade elastalert to 0.1.36
  stable/elastalert/Chart.yaml
  stable/elastalert/README.md
  stable/elastalert/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#8984 [stable/karma] update to v0.16
  stable/karma/Chart.yaml
  stable/karma/README.md
  stable/karma/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#8862 Updating to latest released agent (ciprod10162018-2)
  incubator/azuremonitor-containers/Chart.yaml
  incubator/azuremonitor-containers/README.md
  incubator/azuremonitor-containers/templates/NOTES.txt
  incubator/azuremonitor-containers/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#8974 [stable/traefik] Update traefik to 1.7.4
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#8713 - Adding affinity for kubernetes-dashboard
  stable/kubernetes-dashboard/Chart.yaml
  stable/kubernetes-dashboard/README.md
  stable/kubernetes-dashboard/templates/deployment.yaml
  stable/kubernetes-dashboard/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#8833 [stable/coredns] Adding OWNERS file from chart.yaml
  stable/coredns/.helmignore
  stable/coredns/Chart.yaml
  stable/coredns/OWNERS
Labels: Contribution Allowed, approved, lgtm, size/S

#8987 [stable/prometheus-operator] Upgrade to 0.25.0
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/templates/alertmanager/alertmanager.yaml
  stable/prometheus-operator/templates/prometheus-operator/crd-alertmanager.yaml
  stable/prometheus-operator/templates/prometheus-operator/crd-prometheus.yaml
  stable/prometheus-operator/templates/prometheus-operator/crd-prometheusrules.yaml
  stable/prometheus-operator/templates/prometheus-operator/crd-servicemonitor.yaml
  stable/prometheus-operator/templates/prometheus/additionalAlertRelabelConfigs.yaml
  stable/prometheus-operator/templates/prometheus/prometheus.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#8099 concourse: consume local-users from k8s secret
  stable/concourse/Chart.yaml
  stable/concourse/templates/web-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#8108 Upgrade cluster-autoscaler to v1.12.0
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/templates/clusterrole.yaml
  stable/cluster-autoscaler/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#6547 Redis exporter service port name
  stable/prometheus-redis-exporter/Chart.yaml
  stable/prometheus-redis-exporter/templates/service.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm, size/XS

#8784 [stable/consul] Fix ignoring gossip-key passed via values
  stable/consul/Chart.yaml
  stable/consul/templates/gossip-secret.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#8084 [stable/metricbeat] Set dnsPolicy explicitly to ClusterFirstWithHostNet
  stable/metricbeat/Chart.yaml
  stable/metricbeat/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#8813 [incubator/vault] add override fullname variable
  incubator/vault/Chart.yaml
  incubator/vault/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, size/XS

#8345 [stable/cockroachdb] Bump default RequestCertsImageTag
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/README.md
  stable/cockroachdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#8285 mongodb-replicaset: added resources definition for initContainers
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/README.md
  stable/mongodb-replicaset/templates/mongodb-statefulset.yaml
  stable/mongodb-replicaset/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#8992 set AWS_DEFAULT_REGION for aws-sd provider
  stable/external-dns/Chart.yaml
  stable/external-dns/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#8847 [stable/mongodb] Added authenticationDatabase parameter to connection string
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, size/S

#8478 Allow for annotations to be added to deployment
  stable/mssql-linux/Chart.yaml
  stable/mssql-linux/README.md
  stable/mssql-linux/templates/deployment.yaml
  stable/mssql-linux/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8926 [incubator/cassandra] Made cluster domain name configurable (defaults…
  incubator/cassandra/Chart.yaml
  incubator/cassandra/README.md
  incubator/cassandra/templates/statefulset.yaml
  incubator/cassandra/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#8865 [Blackbox-exporter] Add support for affinity and tolerations
  stable/prometheus-blackbox-exporter/Chart.yaml
  stable/prometheus-blackbox-exporter/README.md
  stable/prometheus-blackbox-exporter/templates/deployment.yaml
  stable/prometheus-blackbox-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#8995 Expose rpc service for remote backups and restores
  stable/influxdb/Chart.yaml
  stable/influxdb/templates/service.yaml
  stable/influxdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#8896 [stable/kibana] Add kibana plugin installed control (#8581)
  stable/kibana/Chart.yaml
  stable/kibana/README.md
  stable/kibana/ci/plugin-install.yaml
  stable/kibana/templates/deployment.yaml
  stable/kibana/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#8997 [stable/prometheus-operator]: Fix cadvisor endpoint for http
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/exporters/kubelet/servicemonitor.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#9002 [stable/postgresql] Fix chart when persistence is enabled
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/_helpers.tpl
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#9003 [stable/ghost] Use minideb as initContainer to change volumes permissions
  stable/ghost/Chart.yaml
  stable/ghost/README.md
  stable/ghost/templates/_helpers.tpl
  stable/ghost/templates/deployment.yaml
  stable/ghost/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#9010 [stable/kube-state-metrics] Enable RBAC by default (needed for securitycontexts)
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
  stable/kube-state-metrics/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#9018 [stable/prometheus] Fixes #9017: Enable deployment from secure image registry
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/alertmanager-deployment.yaml
  stable/prometheus/templates/kube-state-metrics-deployment.yaml
  stable/prometheus/templates/node-exporter-daemonset.yaml
  stable/prometheus/templates/pushgateway-deployment.yaml
  stable/prometheus/templates/server-deployment.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#9021 Fixed note
  stable/ethereum/Chart.yaml
  stable/ethereum/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, size/XS

#8991 [stable/prometheus-node-exporter] Fix typo causing PSP resources not being created
  stable/prometheus-node-exporter/Chart.yaml
  stable/prometheus-node-exporter/templates/psp-clusterrole.yaml
  stable/prometheus-node-exporter/templates/psp-clusterrolebinding.yaml
  stable/prometheus-node-exporter/templates/psp.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#6658 [stable/gcloud-sqlproxy] Add PDB
  stable/gcloud-sqlproxy/Chart.yaml
  stable/gcloud-sqlproxy/templates/pdb.yaml
  stable/gcloud-sqlproxy/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#7923 Issue-7911 setting the gcp credentials value
  stable/pachyderm/Chart.yaml
  stable/pachyderm/README.md
  stable/pachyderm/templates/pachd_secret.yaml
  stable/pachyderm/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test

#9027 [stable/prometheus-operator] Lock kube-state-metrics to newest version
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/requirements.lock
  stable/prometheus-operator/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#8994 Updating image of prometheus-redis-exporter to latest version
  stable/prometheus-redis-exporter/Chart.yaml
  stable/prometheus-redis-exporter/README.md
  stable/prometheus-redis-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#9037 upgrade prometheus
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#8949 Remove `component: halyard` label from install hook
  stable/spinnaker/Chart.yaml
  stable/spinnaker/templates/hooks/install-using-hal.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#9004 [stable/jenkins] resolve json parsing errors when including jobs
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/jobs.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#8913 Add the serviceAccountLabels variable i forgot to document in #8567
  stable/prometheus-pushgateway/Chart.yaml
  stable/prometheus-pushgateway/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#9006 [stable/prometheus-operator] Update dependencies for RBAC, readme
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/requirements.lock
  stable/prometheus-operator/requirements.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#8932 [stable/kong] add migration image params
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/templates/migrations.yaml
  stable/kong/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#9055 Standalone deployment metrics indentation fix
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/deployment-standalone.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#9068 [stable/postgresql] Specify user for the initContainer
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#9051 [stable/logstash] Add nodePort configuration
  stable/logstash/Chart.yaml
  stable/logstash/README.md
  stable/logstash/templates/service.yaml
  stable/logstash/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#8962 [stable/fluent-bit] Upgrade to Fluent Bit v0.14.6
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#8961 Add toleration and affinity knobs for heapster
  stable/heapster/Chart.yaml
  stable/heapster/README.md
  stable/heapster/templates/deployment.yaml
  stable/heapster/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#8423 Correct typos related to AWS deployments
  stable/concourse/Chart.yaml
  stable/concourse/templates/web-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#8745 [test] Update chart testing
  .circleci/config.yml
  test/.dockerignore
  test/.testenv
  test/Dockerfile
  test/build.sh
  test/ct.yaml
  test/e2e.sh
Labels: Contribution Allowed, approved, lgtm, size/M

#9078 [stable/hlf-ord] Minor fix to remove duplicate ports definition
  stable/hlf-ord/Chart.yaml
  stable/hlf-ord/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#9060 Adds support for custom service annotations
  stable/drone/Chart.yaml
  stable/drone/README.md
  stable/drone/templates/service.yaml
  stable/drone/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8094 concourse: move vault auth param to secret
  stable/concourse/Chart.yaml
  stable/concourse/README.md
  stable/concourse/templates/secrets.yaml
  stable/concourse/templates/web-deployment.yaml
  stable/concourse/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#9084 Fix cri option typo and document socket path
  stable/datadog/Chart.yaml
  stable/datadog/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9072 [incubator/kubeless] Update app version to v1.0.0
  incubator/kubeless/Chart.yaml
  incubator/kubeless/README.md
  incubator/kubeless/templates/controller-deployment.yaml
  incubator/kubeless/templates/kubeless-config.yaml
  incubator/kubeless/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XL

#8382 [stable/nats] Add prometheus exporter
  stable/nats/Chart.yaml
  stable/nats/README.md
  stable/nats/templates/_helpers.tpl
  stable/nats/templates/statefulset.yaml
  stable/nats/values-production.yaml
  stable/nats/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#9086 [stable/prometheus-operator] Fix storageSpec parameter name in README.
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#8299 [stable/redis] Set metrics annotations by default
  stable/redis/Chart.yaml
  stable/redis/values-production.yaml
  stable/redis/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9104 [stable/postgresql] Refactor init-container to support more scenarios
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9016 [stable/kured]: update to new release
  stable/kured/Chart.yaml
  stable/kured/README.md
  stable/kured/templates/clusterrole.yaml
  stable/kured/templates/daemonset.yaml
  stable/kured/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#9119 [stable/postgresql] Fix upgradability of metrics deployment.
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/metrics-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9122 [stable/mongodb] Fix primary statefulset
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/statefulset-primary-rs.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#8014 [stable/kubewatch] Add chart label for pods
  stable/kubewatch/Chart.yaml
  stable/kubewatch/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9137 [stable/kubewatch] Edit OWNERS file
  stable/kubewatch/Chart.yaml
  stable/kubewatch/OWNERS
Labels: Contribution Allowed, approved, lgtm, size/S

#9096 [stable/metrics-server] Typo in README.md
  stable/metrics-server/Chart.yaml
  stable/metrics-server/README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#9135 Update to Spark 2.4.0
  stable/spark-history-server/Chart.yaml
  stable/spark-history-server/README.md
  stable/spark-history-server/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#8473 new chart [stable/node-red]
  stable/node-red/.helmignore
  stable/node-red/Chart.yaml
  stable/node-red/OWNERS
  stable/node-red/README.md
  stable/node-red/templates/NOTES.txt
  stable/node-red/templates/_helpers.tpl
  stable/node-red/templates/deployment.yaml
  stable/node-red/templates/ingress.yaml
  stable/node-red/templates/pvc.yaml
  stable/node-red/templates/service.yaml
  stable/node-red/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#8397 Remove duplicated words in documentation
  incubator/webpagetest-server/Chart.yaml
  incubator/webpagetest-server/README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#8333 Move /var/lib/grafana mount before subdirectory mounts
  stable/grafana/Chart.yaml
  stable/grafana/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#8948 [stable/redis-ha] Use sh instead of bash to support alpine image
  stable/redis-ha/Chart.yaml
  stable/redis-ha/templates/NOTES.txt
  stable/redis-ha/templates/redis-ha-configmap.yaml
  stable/redis-ha/templates/redis-ha-statefulset.yaml
  stable/redis-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#7933 Avoid `clusterIP` if not specified.
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/templates/controller-service.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#8106 fx: propogate influx deployment labels to pods
  stable/influxdb/Chart.yaml
  stable/influxdb/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#8973 [stable/envoy] Fix deployment spec
  stable/envoy/Chart.yaml
  stable/envoy/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9132 Remove duplicate environment variable MONGODB_ENABLE_IPV6
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/deployment-standalone.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9112 [stable/keycloak] Use standalone.xml config file when only using 1 replica
  stable/keycloak/Chart.yaml
  stable/keycloak/templates/configmap.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9040 [stable/keycloak] use tcp instead of udp for jgroups
  stable/keycloak/Chart.yaml
  stable/keycloak/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9147 upgrade alertmanager
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm

#9165 [test] Fix setting Helm timeout
  test/ct.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#9164 Update filebeat chart to use 6.4.3 docker image
  stable/filebeat/Chart.yaml
  stable/filebeat/README.md
  stable/filebeat/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9046 [stable/selenium] Add possibility to use affinity and tolerations for…
  stable/selenium/Chart.yaml
  stable/selenium/README.md
  stable/selenium/templates/chrome-deployment.yaml
  stable/selenium/templates/chromeDebug-deployment.yaml
  stable/selenium/templates/firefox-deployment.yaml
  stable/selenium/templates/firefoxDebug-deployment.yaml
  stable/selenium/templates/hub-deployment.yaml
  stable/selenium/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#9169 upgrade logstash
  stable/logstash/Chart.yaml
  stable/logstash/README.md
  stable/logstash/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#9168 upgrade elasticsearch
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/README.md
  stable/elasticsearch/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#9170 upgrade kibana
  stable/kibana/Chart.yaml
  stable/kibana/README.md
  stable/kibana/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#9172 [stable/auditbeat] Update Auditbeat to 6.4.3
  stable/auditbeat/Chart.yaml
  stable/auditbeat/README.md
  stable/auditbeat/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9171 [stable/metricbeat] Update Metricbeat to 6.4.3
  stable/metricbeat/Chart.yaml
  stable/metricbeat/README.md
  stable/metricbeat/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9120 [stable/postgresql] Fix resources parameter and document it.
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#8966 Allow for custom service annotations for prometheus and alertmanager
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/templates/alertmanager/service.yaml
  stable/prometheus-operator/templates/prometheus-operator/service.yaml
  stable/prometheus-operator/templates/prometheus/service.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#9103 Sync etc and general rules with coreos/prometheus-operator
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/alertmanager/rules/all.rules.yaml
  stable/prometheus-operator/templates/alertmanager/rules/kube-etcd.rules.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#8867 [stable/prometheus-operator] Allow annotations on prometheus service
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/templates/prometheus/service.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9183 Fix ReadMe
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9180 stable/unifi/templates/deployment.yaml: fix probes
  stable/unifi/Chart.yaml
  stable/unifi/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9187 [stable/redis] Fix hardcoded serviceName
  stable/redis/Chart.yaml
  stable/redis/templates/redis-master-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9145 Fix broken ingress template for redmine chart
  stable/redmine/Chart.yaml
  stable/redmine/templates/NOTES.txt
  stable/redmine/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9201 [stable/elastic-stack] Update elastic-stack to use latest logstash chart
  stable/elastic-stack/Chart.yaml
  stable/elastic-stack/requirements.lock
  stable/elastic-stack/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9200 Deprecate Buildkite chart
  stable/buildkite/Chart.yaml
  stable/buildkite/README.md
  stable/buildkite/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, size/S

#9154 Allow custom annotations for default rules so that ruleSelector modifications can work
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/templates/alertmanager/rules/all.rules.yaml
  stable/prometheus-operator/templates/alertmanager/rules/kube-etcd.rules.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9223 upgrade grafana
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#9213 [stable/joomla] fix typo in livenessProbe
  stable/joomla/Chart.yaml
  stable/joomla/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9114 [stable/postgresql] Add affinity parameter.
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#9115 [stable/postgresql] Fix invalid StatefulSet volumeClaimTemplates annotations if empty.
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#9061 [stable/mongodb] Support Prometheus monitoring using Prometheus Operator
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/templates/headless-svc-rs.yaml
  stable/mongodb/templates/prometheus-alerting-rule.yaml
  stable/mongodb/templates/prometheus-service-monitor.yaml
  stable/mongodb/templates/statefulset-primary-rs.yaml
  stable/mongodb/templates/statefulset-secondary-rs.yaml
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#9117 [stable/postgresql] Add ability to give postgresql, pg_hba configuration or initdb scripts from parameters.
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/configmap.yaml
  stable/postgresql/templates/initialization-configmap.yaml
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#9233 [stable/parse] Bump mongodb dependency
  stable/parse/Chart.yaml
  stable/parse/requirements.lock
  stable/parse/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#8935 7931; Enable SSL Support
  stable/percona-xtradb-cluster/Chart.yaml
  stable/percona-xtradb-cluster/README.md
  stable/percona-xtradb-cluster/templates/secrets.yaml
  stable/percona-xtradb-cluster/templates/statefulset.yaml
  stable/percona-xtradb-cluster/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#9225 [stable/falco] Update Rules to match Falco version 0.13.0 rules
  stable/falco/CHANGELOG.md
  stable/falco/Chart.yaml
  stable/falco/rules/falco_rules.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#9275 [Datadog] Add /var/run/s6 volume to avoid noexec on some setups
  stable/datadog/Chart.yaml
  stable/datadog/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9130 [stable/kibana] Add PVC support and security context for Kibana
  stable/kibana/Chart.yaml
  stable/kibana/README.md
  stable/kibana/ci/plugin-install.yaml
  stable/kibana/ci/pvc.yaml
  stable/kibana/ci/security-context.yaml
  stable/kibana/templates/deployment.yaml
  stable/kibana/templates/volume-claim.yaml
  stable/kibana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#9255 [incubator/cassandra] update backup image - enable ABS support
  incubator/cassandra/Chart.yaml
  incubator/cassandra/README.md
  incubator/cassandra/templates/backup/cronjob.yaml
  incubator/cassandra/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#7520 [stable/rabbitmq-ha] Fix namespace and labels in prometheus alerts definition
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/templates/alerts.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#9283 [newrelic-infra] Update image to 1.3.1
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/README.md
  stable/newrelic-infrastructure/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9160 Update Helm code of conduct
  code-of-conduct.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#9020 [stable/kong] introduce Kong ingress controller
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/ci/ingressController-values.yaml
  stable/kong/kong-0.5.7.tgz
  stable/kong/templates/_helpers.tpl
  stable/kong/templates/controller-cluster-role.yaml
  stable/kong/templates/controller-deployment.yaml
  stable/kong/templates/controller-rbac-cluster-role-binding.yaml
  stable/kong/templates/controller-rbac-role-binding.yaml
  stable/kong/templates/controller-rbac-role.yaml
  stable/kong/templates/controller-service-account.yaml
  stable/kong/templates/crd-kongconsumer.yaml
  stable/kong/templates/crd-kongcredential.yaml
  stable/kong/templates/crd-kongingress.yaml
  stable/kong/templates/crd-kongplugins.yaml
  stable/kong/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XL

#9319 [ci] Upgrade to chart-testing v2.0.1
  .circleci/config.yml
  test/Dockerfile
  test/build.sh
  test/e2e.sh
Labels: Contribution Allowed, approved, lgtm, size/XS

#9316 Bump mattermost-te to 5.5.0
  stable/mattermost-team-edition/Chart.yaml
  stable/mattermost-team-edition/README.md
  stable/mattermost-team-edition/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#9268 [stable/nats] Add support for extraArgs to NATS
  stable/nats/Chart.yaml
  stable/nats/README.md
  stable/nats/templates/statefulset.yaml
  stable/nats/values-production.yaml
  stable/nats/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9226 Adds tolerations to cassandra statefulset spec
  incubator/cassandra/Chart.yaml
  incubator/cassandra/README.md
  incubator/cassandra/templates/statefulset.yaml
  incubator/cassandra/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#8231 add azure aks to cluster-autoscaling chart
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/README.md
  stable/cluster-autoscaler/templates/deployment.yaml
  stable/cluster-autoscaler/templates/secret.yaml
  stable/cluster-autoscaler/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#8441 [stable/consul] Create rbac for test container
  stable/consul/Chart.yaml
  stable/consul/README.md
  stable/consul/templates/consul-test-clusterrole.yaml
  stable/consul/templates/consul-test-clusterrolebinding.yaml
  stable/consul/templates/consul-test-serviceaccount.yaml
  stable/consul/templates/consul-test.yaml
  stable/consul/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#8599 [stable/superset] support service annotations, use correct healthcheck
  stable/superset/Chart.yaml
  stable/superset/templates/svc.yaml
  stable/superset/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#8736 [stable/rabbitmq-ha] allow override of busybox like in stable/efs-provisioner
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/templates/statefulset.yaml
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#8766 [incubator/kube-janitor] Release 0.1.0
  incubator/kube-janitor/.helmignore
  incubator/kube-janitor/Chart.yaml
  incubator/kube-janitor/templates/_helpers.tpl
  incubator/kube-janitor/templates/cluster-role-binding.yaml
  incubator/kube-janitor/templates/cluster-role.yaml
  incubator/kube-janitor/templates/cron-job.yaml
  incubator/kube-janitor/templates/service-account.yaml
  incubator/kube-janitor/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#9149 [stable/prometheus-operator] fix typo in README.md
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9156 Use a single image for all cases (HDFS, GCS etc)
  stable/spark-history-server/Chart.yaml
  stable/spark-history-server/README.md
  stable/spark-history-server/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#9110 [stable/percona-xtradb-cluster] Pod Disruption Budget
  stable/percona-xtradb-cluster/Chart.yaml
  stable/percona-xtradb-cluster/README.md
  stable/percona-xtradb-cluster/templates/pdb.yaml
  stable/percona-xtradb-cluster/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#9336 Dokuwiki volume-binding-mode info
  stable/dokuwiki/Chart.yaml
  stable/dokuwiki/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#8580 [stable/rabbitmq-ha] Parameterize cluster domain
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/templates/NOTES.txt
  stable/rabbitmq-ha/templates/configmap.yaml
  stable/rabbitmq-ha/templates/statefulset.yaml
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#9335 Phabricator: volume-binding-mode info
  stable/phabricator/Chart.yaml
  stable/phabricator/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#9338 Owncloud: volume-binding-mode info
  stable/owncloud/Chart.yaml
  stable/owncloud/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#9292 [stable/kube-slack] Upgrade image to latest version
  stable/kube-slack/Chart.yaml
  stable/kube-slack/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#8703 [stable/keycloak] fix typo
  stable/keycloak/Chart.yaml
  stable/keycloak/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#9342 [stable/bookstack] Update bookstack to 0.24.2
  stable/bookstack/Chart.yaml
  stable/bookstack/README.md
  stable/bookstack/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#8327 Add mount options to nfs-client-provisioner
  stable/nfs-client-provisioner/Chart.yaml
  stable/nfs-client-provisioner/README.md
  stable/nfs-client-provisioner/templates/deployment.yaml
  stable/nfs-client-provisioner/templates/persistentvolume.yaml
  stable/nfs-client-provisioner/templates/persistentvolumeclaim.yaml
  stable/nfs-client-provisioner/templates/storageclass.yaml
  stable/nfs-client-provisioner/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test

#8975 Add ingressmonitorcontroller
  stable/ingressmonitorcontroller/Chart.yaml
  stable/ingressmonitorcontroller/README.md
  stable/ingressmonitorcontroller/templates/NOTES.txt
  stable/ingressmonitorcontroller/templates/_helpers.tpl
  stable/ingressmonitorcontroller/templates/clusterrole.yaml
  stable/ingressmonitorcontroller/templates/clusterrolebinding.yaml
  stable/ingressmonitorcontroller/templates/configmap.yaml
  stable/ingressmonitorcontroller/templates/deployment.yaml
  stable/ingressmonitorcontroller/templates/role.yaml
  stable/ingressmonitorcontroller/templates/rolebinding.yaml
  stable/ingressmonitorcontroller/templates/serviceaccount.yaml
  stable/ingressmonitorcontroller/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#7557 Spleling
  stable/home-assistant/Chart.yaml
  stable/home-assistant/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#9341 [mssql-linux] fixes and feature requests
  stable/mssql-linux/Chart.yaml
  stable/mssql-linux/OWNERS
  stable/mssql-linux/README.md
  stable/mssql-linux/templates/.helmignore
  stable/mssql-linux/templates/deployment.yaml
  stable/mssql-linux/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#9339 [stable/node-red] adding support disclaimer
  stable/node-red/Chart.yaml
  stable/node-red/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS
