Repository helm/charts, pull requests merged in 2018-02, with the labels that each got.

#3627 [stable/buildkite] Change name of Docker credentials in Pod
  stable/buildkite/Chart.yaml
  stable/buildkite/templates/secret-registry.yaml
  stable/buildkite/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3578 fix a typo in zookeeper readme
  incubator/zookeeper/Chart.yaml
  incubator/zookeeper/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3215 [stable/traefik] Add proxyProtocol support
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/_helpers.tpl
  stable/traefik/templates/configmap.yaml
  stable/traefik/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3589 [stable/kibana] Added value service.externalIPs
  stable/kibana/Chart.yaml
  stable/kibana/README.md
  stable/kibana/templates/service.yaml
  stable/kibana/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3638 Update README.md fix typo suported -> supported
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3556 fix README.md typo
  stable/anchore-engine/Chart.yaml
  stable/anchore-engine/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3628 some typo
  stable/datadog/Chart.yaml
  stable/datadog/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3343 [stable/grafana] change default readinessProbe to /api/health
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3552 Fix external-dns default RBAC API version
  stable/external-dns/Chart.yaml
  stable/external-dns/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3537 [stable/gcloud-sqlproxy] Fix certificate error.
  stable/gcloud-sqlproxy/Chart.yaml
  stable/gcloud-sqlproxy/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3539 [stable/concourse] Fix truncation of postgresql name
  stable/concourse/Chart.yaml
  stable/concourse/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3016 add optional serviceAccountName
  stable/spotify-docker-gc/Chart.yaml
  stable/spotify-docker-gc/README.md
  stable/spotify-docker-gc/templates/daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3500 [stable/prometheus] fix liveness and readiness probe when the prefix …
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/server-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3483 [stable/concourse] Tune fatal errors.
  stable/concourse/Chart.yaml
  stable/concourse/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3569 [stable/sematext-docker-agent] Update chart icon
  stable/sematext-docker-agent/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3595 [stable/kube-state-metrics] allow for namespace flag to be configured
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/templates/deployment.yaml
  stable/kube-state-metrics/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3619 [Datadog] Fix kubeStateMetrics.enabled in values.yaml
  stable/datadog/Chart.yaml
  stable/datadog/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3630 fix a typo in publish-docker.sh
  test/publish-docker.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3633 Fix typos in influxdb
  stable/influxdb/Chart.yaml
  stable/influxdb/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3635 Fix typos in telegraf
  stable/telegraf/Chart.yaml
  stable/telegraf/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2424 [incubator/kubeless] - Add kubeless helm chart
  incubator/kubeless/Chart.yaml
  incubator/kubeless/OWNERS
  incubator/kubeless/README.md
  incubator/kubeless/templates/NOTES.txt
  incubator/kubeless/templates/_helpers.tpl
  incubator/kubeless/templates/cluster-role-binding.yaml
  incubator/kubeless/templates/cluster-role.yaml
  incubator/kubeless/templates/controller-deployment.yaml
  incubator/kubeless/templates/function-crd.yaml
  incubator/kubeless/templates/kafka-headless-svc.yaml
  incubator/kubeless/templates/kafka-stateful.yaml
  incubator/kubeless/templates/kafka-svc.yaml
  incubator/kubeless/templates/service-account.yaml
  incubator/kubeless/templates/ui-deployment.yaml
  incubator/kubeless/templates/ui-svc.yaml
  incubator/kubeless/templates/zk-headless-svc.yaml
  incubator/kubeless/templates/zk-stateful.yaml
  incubator/kubeless/templates/zk-svc.yaml
  incubator/kubeless/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3636 Fix typo in fluent-bit
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3629 [stable/metabase] Fix notes to port forward with namespace
  stable/metabase/Chart.yaml
  stable/metabase/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3637 Update README.md fix typo certficate -> certificate
  stable/traefik/Chart.yaml
  stable/traefik/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3585 [stable/prometheus] Fix node exporter args
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/node-exporter-daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3639 fix typo in burrow Readme
  incubator/burrow/Chart.yaml
  incubator/burrow/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3641 [incubator/jaeger] Fix render error when ingress enabled
  incubator/jaeger/Chart.yaml
  incubator/jaeger/templates/query-ing.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3652 fix typo in chronograf/values.yaml
  stable/chronograf/Chart.yaml
  stable/chronograf/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3657 Fix the Nginx service name shown in NOTES.txt
  stable/artifactory/Chart.yaml
  stable/artifactory/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3658 Updates to stable/msoms
  stable/msoms/Chart.yaml
  stable/msoms/templates/omsagent-daemonset.yaml
  stable/msoms/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3660 [stable/external-dns] Fix Cloudflare config
  stable/external-dns/Chart.yaml
  stable/external-dns/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3664 Fix typo: overide -> override
  stable/heapster/Chart.yaml
  stable/heapster/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3452 deprecate Istio chart in favor for upstream chart
  incubator/istio/Chart.yaml
  incubator/istio/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3587 [stable/kubernetes-dashboard] Add `extraArgs` to `kubernetes-dashboard`
  stable/kubernetes-dashboard/Chart.yaml
  stable/kubernetes-dashboard/README.md
  stable/kubernetes-dashboard/templates/deployment.yaml
  stable/kubernetes-dashboard/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3533 Adjust README to use stable chart repo
  stable/elasticsearch-exporter/Chart.yaml
  stable/elasticsearch-exporter/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3594 [incubator/drone] Startup & metadata fixes
  incubator/drone/Chart.yaml
  incubator/drone/README.md
  incubator/drone/templates/deployment-server.yaml
  incubator/drone/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3666 Typo fix: repostory -> [repository]
  test/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3674 fix typo in test/circle/lint.sh
  test/circle/lint.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3615 [incubator/drone] GCE Ingress Path Fix
  incubator/drone/Chart.yaml
  incubator/drone/templates/ingress.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3676 fix typo in webpage test readme
  incubator/webpagetest-server/Chart.yaml
  incubator/webpagetest-server/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3673 Fix #3669.
  stable/traefik/Chart.yaml
  stable/traefik/templates/configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3620 [Stable/mongodb] Allow to configure readiness and liveness probes for MongoDB chart
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/templates/deployment.yaml
  stable/mongodb/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3675 [stable/kubernetes-dashboard] Fix `extraArgs` documentation
  stable/kubernetes-dashboard/Chart.yaml
  stable/kubernetes-dashboard/README.md
  stable/kubernetes-dashboard/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3683 [incubator][chartmuseum] Allow NodePort to be specified
  incubator/chartmuseum/Chart.yaml
  incubator/chartmuseum/templates/service.yaml
  incubator/chartmuseum/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3693 Fix typo: PostgresSQL -> PostgreSQL
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3694 Update doc for nginx-ingress about externalIPs and hostNetwork=true
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3659 [stable/fluent-bit] Add extra volume and volume mount options
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/templates/daemonset.yaml
  stable/fluent-bit/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3681 Add mesh peer to prometheus alert service
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/alertmanager-service.yaml
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3522 [stable/Prometheus] Support tolerations.
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/alertmanager-deployment.yaml
  stable/prometheus/templates/kube-state-metrics-deployment.yaml
  stable/prometheus/templates/pushgateway-deployment.yaml
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3698 [stable/prometheus] Configurable init container
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/server-deployment.yaml
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3667 Update README.md to fix typo seperated -> separated
  stable/acs-engine-autoscaler/Chart.yaml
  stable/acs-engine-autoscaler/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3247 Allowing configurable sslCertPath for cluster autoscaler
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/README.md
  stable/cluster-autoscaler/templates/deployment.yaml
  stable/cluster-autoscaler/values.yaml
Labels: cncf-cla: yes, size/XS

#1299 [stable/traefik] Allow DNS challenge to be used for getting Letsencrypt Certificate
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/configmap.yaml
  stable/traefik/templates/deployment.yaml
  stable/traefik/templates/dns-provider-secret.yaml
  stable/traefik/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3379 added fluentd-elasticsearch
  incubator/fluentd-elasticsearch/Chart.yaml
  incubator/fluentd-elasticsearch/README.md
  incubator/fluentd-elasticsearch/templates/NOTES.txt
  incubator/fluentd-elasticsearch/templates/_helpers.tpl
  incubator/fluentd-elasticsearch/templates/clusterrole.yaml
  incubator/fluentd-elasticsearch/templates/clusterrolebinding.yaml
  incubator/fluentd-elasticsearch/templates/configmap.yaml
  incubator/fluentd-elasticsearch/templates/daemonset.yaml
  incubator/fluentd-elasticsearch/templates/service-account.yaml
  incubator/fluentd-elasticsearch/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3476 [stable/grafana] Add support for multiple replicas and anti affinity to grafana
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/deployment.yaml
  stable/grafana/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3508 [stable/consul] Clustering improvements
  stable/consul/Chart.yaml
  stable/consul/templates/consul.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3523 [etcd-operator] ensure service account names match if creating rbac
  stable/etcd-operator/Chart.yaml
  stable/etcd-operator/templates/_helpers.tpl
  stable/etcd-operator/templates/backup-operator-clusterrole-binding.yaml
  stable/etcd-operator/templates/backup-operator-deployment.yaml
  stable/etcd-operator/templates/backup-operator-service-account.yaml
  stable/etcd-operator/templates/operator-clusterrole-binding.yaml
  stable/etcd-operator/templates/operator-deployment.yaml
  stable/etcd-operator/templates/operator-service-account.yaml
  stable/etcd-operator/templates/restore-operator-clusterrole-binding.yaml
  stable/etcd-operator/templates/restore-operator-deployment.yaml
  stable/etcd-operator/templates/restore-operator-service-account.yaml
  stable/etcd-operator/values.yaml
Labels: approved, changes needed, cncf-cla: yes, lgtm, size/M

#3712 Fix typos: seperated -> separated
  stable/chronograf/Chart.yaml
  stable/chronograf/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3722 Changes for prometheus ingress RBAC.
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/server-clusterrole.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3716 [stable/kong] Added support for service annotations
  stable/kong/Chart.yaml
  stable/kong/templates/service-kong-admin.yaml
  stable/kong/templates/service-kong-proxy.yaml
  stable/kong/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3677 [mssql-linux] Added feature for persistence and updated README.md
  stable/mssql-linux/Chart.yaml
  stable/mssql-linux/README.md
  stable/mssql-linux/templates/NOTES.txt
  stable/mssql-linux/templates/deployment.yaml
  stable/mssql-linux/templates/pvc-data.yaml
  stable/mssql-linux/templates/pvc-tranlog.yaml
  stable/mssql-linux/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3651 Add initialDelaySeconds and periodSeconds to Logstash livenessProbe, update image
  incubator/logstash/Chart.yaml
  incubator/logstash/README.md
  incubator/logstash/templates/deployment.yaml
  incubator/logstash/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3758 [stable/concourse] Fix substitutions - {} with () in args
  stable/concourse/Chart.yaml
  stable/concourse/templates/web-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3436 [stable/rethinkdb] Support rbac
  stable/rethinkdb/Chart.yaml
  stable/rethinkdb/templates/_helpers.tpl
  stable/rethinkdb/templates/auth/clusterrole.yaml
  stable/rethinkdb/templates/auth/clusterrolebinding.yaml
  stable/rethinkdb/templates/auth/serviceaccount.yaml
  stable/rethinkdb/templates/rethinkdb-admin-service.yaml
  stable/rethinkdb/templates/rethinkdb-cluster-service.yaml
  stable/rethinkdb/templates/rethinkdb-cluster-stateful-set.yaml
  stable/rethinkdb/templates/rethinkdb-cluster-storage-class.yaml
  stable/rethinkdb/templates/rethinkdb-proxy-deployment.yaml
  stable/rethinkdb/templates/rethinkdb-proxy-service.yaml
  stable/rethinkdb/templates/rethinkdb-secrets.yaml
  stable/rethinkdb/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3774 Mount arbitrary configmaps as files.
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/node-exporter-daemonset.yaml
  stable/prometheus/templates/server-deployment.yaml
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3688 fix typo in stable/phpbb/README.md
  stable/phpbb/Chart.yaml
  stable/phpbb/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3690 Typo fix: documentaion -> documentation
  stable/uchiwa/Chart.yaml
  stable/uchiwa/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3655 fix typos
  stable/kong/Chart.yaml
  stable/kong/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3684 [Prometheus] Updated cAdvisor endpoint
  stable/prometheus/Chart.yaml
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3757 [incubator/gocd] Add support for custom annotations
  incubator/gocd/Chart.yaml
  incubator/gocd/templates/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3726 Add podManagementPolicy support to incubator/cassandra
  incubator/cassandra/Chart.yaml
  incubator/cassandra/README.md
  incubator/cassandra/templates/cassandra-statefulset.yaml
  incubator/cassandra/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3546 [stable/prometheus] add path element to ingress definitions
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/alertmanager-ingress.yaml
  stable/prometheus/templates/pushgateway-ingress.yaml
  stable/prometheus/templates/server-ingress.yaml
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3665 [incubator/drone] Add option to disable DinD
  incubator/drone/Chart.yaml
  incubator/drone/README.md
  incubator/drone/templates/deployment-agent.yaml
  incubator/drone/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3692 [stable/artifactory] upgraded Artifactory version
  stable/artifactory/Chart.yaml
  stable/artifactory/README.md
  stable/artifactory/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3717 [incubator/kafka] Added ability to specify nodeSelector (to allow installing on separate node pools)
  incubator/kafka/Chart.yaml
  incubator/kafka/templates/statefulset.yaml
  incubator/kafka/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3719 [incubator/zookeeper] Added ability to customize ZooKeeper's nodeSelector
  incubator/zookeeper/Chart.yaml
  incubator/zookeeper/templates/statefulset.yaml
  incubator/zookeeper/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3744 [stable/minio] Add persistence.existingClaim
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/templates/minio_deployment.yaml
  stable/minio/templates/minio_pvc.yaml
  stable/minio/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3734 [stable/prometheus] Allow set securityContext for node exporter pods
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/node-exporter-daemonset.yaml
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3756 [incubator/logstash] add ability to add custom annotations and labels to the pod
  incubator/logstash/Chart.yaml
  incubator/logstash/README.md
  incubator/logstash/templates/deployment.yaml
  incubator/logstash/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3760 [stable/selenium] Upgrading Chart to Selenium 3.9.1
  stable/selenium/Chart.yaml
  stable/selenium/README.md
  stable/selenium/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3686 add external-dns txt-prefix param to deployment and readme
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3787 [incubator/chartmuseum] update to latest stable image, add new params…
  incubator/chartmuseum/Chart.yaml
  incubator/chartmuseum/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3616 [stable/lamp] fixed missing load mpm event module in apache conf
  stable/lamp/Chart.yaml
  stable/lamp/README.md
  stable/lamp/files/httpd/httpd.conf
  stable/lamp/templates/deployment.yaml
Labels: approved, changes needed, cncf-cla: yes, lgtm, size/XXL

#3663 Adds dnsPolicy as an option to nginx-ingress-controller in values.yaml
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/templates/controller-daemonset.yaml
  stable/nginx-ingress/templates/controller-deployment.yaml
  stable/nginx-ingress/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3704 [stable/percona-xtradb-cluster] move files outside configmaps
  stable/percona-xtradb-cluster/Chart.yaml
  stable/percona-xtradb-cluster/README.md
  stable/percona-xtradb-cluster/files/entrypoint.sh
  stable/percona-xtradb-cluster/files/functions.sh
  stable/percona-xtradb-cluster/files/node.cnf
  stable/percona-xtradb-cluster/templates/config-map_mysql-config.yaml
  stable/percona-xtradb-cluster/templates/config-map_startup-scripts.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3775 [incubator/gocd] Update install repository references to incubator
  incubator/gocd/Chart.yaml
  incubator/gocd/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3542 [incubator/etcd] Add pod assignment configuration options
  incubator/etcd/Chart.yaml
  incubator/etcd/README.md
  incubator/etcd/templates/statefulset.yaml
  incubator/etcd/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3632 Fix bug: property name is incorrect with elasticsearch's chart
  incubator/jaeger/Chart.yaml
  incubator/jaeger/README.md
  incubator/jaeger/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3834 Add OWNERS file to bitnami charts
  stable/dokuwiki/Chart.yaml
  stable/dokuwiki/OWNERS
  stable/jasperreports/Chart.yaml
  stable/jasperreports/OWNERS
  stable/joomla/Chart.yaml
  stable/joomla/OWNERS
  stable/mariadb/Chart.yaml
  stable/mariadb/OWNERS
  stable/mediawiki/Chart.yaml
  stable/mediawiki/OWNERS
  stable/moodle/Chart.yaml
  stable/moodle/OWNERS
  stable/opencart/Chart.yaml
  stable/opencart/OWNERS
  stable/orangehrm/Chart.yaml
  stable/orangehrm/OWNERS
  stable/osclass/Chart.yaml
  stable/osclass/OWNERS
  stable/owncloud/Chart.yaml
  stable/owncloud/OWNERS
  stable/parse/Chart.yaml
  stable/parse/OWNERS
  stable/phpbb/Chart.yaml
  stable/phpbb/OWNERS
  stable/redmine/Chart.yaml
  stable/redmine/OWNERS
  stable/sugarcrm/Chart.yaml
  stable/sugarcrm/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/L

#3735 Small fixes in console print-outs
  stable/lamp/Chart.yaml
  stable/lamp/files/init/init_clone.sh
  stable/lamp/files/init/init_db_clone.sh
  stable/lamp/files/init/init_wp_db.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3708 [stable/postgresql] Add fullnameOverride support
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/S

#3812 [incubator/keycloak] Add rbac support
  incubator/keycloak/Chart.yaml
  incubator/keycloak/README.md
  incubator/keycloak/templates/_helpers.tpl
  incubator/keycloak/templates/rbac.yaml
  incubator/keycloak/templates/serviceaccount.yaml
  incubator/keycloak/templates/statefulset.yaml
  incubator/keycloak/values.yaml
Labels: approved, changes needed, cncf-cla: yes, lgtm, size/M

#3773 [stable/prometheus] use prefixURL in alertmanagers config
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/server-configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3845 [stable/ghost] Update Ghost chart to use latest released version of the ghost image
  stable/ghost/Chart.yaml
  stable/ghost/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3835 [incubator/chartmuseum]: Add support for nodeSelector, tolerations, affinity
  incubator/chartmuseum/Chart.yaml
  incubator/chartmuseum/README.md
  incubator/chartmuseum/templates/deployment.yaml
  incubator/chartmuseum/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3850 Add azuregateway.enabled value to stable/minio chart to enable azure …
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/templates/minio_deployment.yaml
  stable/minio/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3848 Fix fluentd-elasticsearch template
  incubator/fluentd-elasticsearch/Chart.yaml
  incubator/fluentd-elasticsearch/templates/daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3254 [stable/concourse] Refactor values and make secrets optional
  stable/concourse/Chart.yaml
  stable/concourse/OWNERS
  stable/concourse/README.md
  stable/concourse/concourse-keys/host_key
  stable/concourse/concourse-keys/host_key.pub
  stable/concourse/concourse-keys/session_signing_key
  stable/concourse/concourse-keys/worker_key
  stable/concourse/concourse-keys/worker_key.pub
  stable/concourse/requirements.lock
  stable/concourse/requirements.yaml
  stable/concourse/templates/NOTES.txt
  stable/concourse/templates/_helpers.tpl
  stable/concourse/templates/configmap.yaml
  stable/concourse/templates/namespace.yaml
  stable/concourse/templates/secrets.yaml
  stable/concourse/templates/web-deployment.yaml
  stable/concourse/templates/web-role.yaml
  stable/concourse/templates/web-rolebinding.yaml
  stable/concourse/templates/web-serviceaccount.yaml
  stable/concourse/templates/worker-statefulset.yaml
  stable/concourse/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3748 Sentry kubernetes
  incubator/sentry-kubernetes/.helmignore
  incubator/sentry-kubernetes/Chart.yaml
  incubator/sentry-kubernetes/README.md
  incubator/sentry-kubernetes/templates/NOTES.txt
  incubator/sentry-kubernetes/templates/_helpers.tpl
  incubator/sentry-kubernetes/templates/deployment.yaml
  incubator/sentry-kubernetes/templates/secret.yaml
  incubator/sentry-kubernetes/templates/serviceaccount.yaml
  incubator/sentry-kubernetes/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3680 Add a Quassel IRC Helm Chart
  stable/quassel/.helmignore
  stable/quassel/Chart.yaml
  stable/quassel/OWNERS
  stable/quassel/README.md
  stable/quassel/requirements.lock
  stable/quassel/requirements.yaml
  stable/quassel/templates/NOTES.txt
  stable/quassel/templates/_helpers.tpl
  stable/quassel/templates/deployment.yaml
  stable/quassel/templates/pvc.yaml
  stable/quassel/templates/service.yaml
  stable/quassel/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3567 [stable/luigi] Initial Commit
  stable/luigi/.helmignore
  stable/luigi/Chart.yaml
  stable/luigi/README.md
  stable/luigi/requirements.lock
  stable/luigi/requirements.yaml
  stable/luigi/templates/NOTES.txt
  stable/luigi/templates/_helpers.tpl
  stable/luigi/templates/configmap.yaml
  stable/luigi/templates/deployment.yaml
  stable/luigi/templates/ingress_api.yaml
  stable/luigi/templates/ingress_ui.yaml
  stable/luigi/templates/pvc.yaml
  stable/luigi/templates/service.yaml
  stable/luigi/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3406 New helm chart for kanister-operator
  stable/kanister-operator/.helmignore
  stable/kanister-operator/Chart.yaml
  stable/kanister-operator/README.md
  stable/kanister-operator/templates/NOTES.txt
  stable/kanister-operator/templates/_helpers.tpl
  stable/kanister-operator/templates/deployment.yaml
  stable/kanister-operator/templates/rbac.yaml
  stable/kanister-operator/templates/serviceaccount.yaml
  stable/kanister-operator/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3738 Publish Voyager chart for v6.0.0
  stable/voyager/Chart.yaml
  stable/voyager/README.md
  stable/voyager/templates/apiregistration.yaml
  stable/voyager/templates/cluster-role-binding.yaml
  stable/voyager/templates/cluster-role.yaml
  stable/voyager/templates/deployment.yaml
  stable/voyager/templates/service.yaml
  stable/voyager/templates/user-roles.yaml
  stable/voyager/templates/validating-webhook-configuration.yaml
  stable/voyager/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3816 [stable/heapster] Match the label in deployment yaml
  stable/heapster/Chart.yaml
  stable/heapster/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm, size/S

#3813 [stable/prometheus] Change rbac.create default to true and update README
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3705 [stable/jenkins] Add fullnameOverride support
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/_helpers.tpl
  stable/jenkins/templates/test-config.yaml
  stable/jenkins/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3868 Fix typo in Quassel README
  stable/quassel/Chart.yaml
  stable/quassel/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3769 Bump CockroachDB version to v1.1.5
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/README.md
  stable/cockroachdb/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3858 Update readme to reflect move from incubator to stable for cockroachdb
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3856 [stable/aerospike] Add cmd and args options to Aerospike config
  stable/aerospike/Chart.yaml
  stable/aerospike/README.md
  stable/aerospike/templates/statefulset.yaml
  stable/aerospike/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3838 [stable/traefik] Add HTTP-01 challenge + anonymous data collection
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/configmap.yaml
  stable/traefik/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3844 [incubator/logstash] Revamp logstash from Deployment to StatefulSet to support Persisted Queues
  incubator/logstash/Chart.yaml
  incubator/logstash/README.md
  incubator/logstash/templates/NOTES.txt
  incubator/logstash/templates/_helpers.tpl
  incubator/logstash/templates/configmap.yaml
  incubator/logstash/templates/deployment.yaml
  incubator/logstash/templates/ingress.yaml
  incubator/logstash/templates/patterns-config.yaml
  incubator/logstash/templates/pipeline-config.yaml
  incubator/logstash/templates/poddisruptionbudget.yaml
  incubator/logstash/templates/service.yaml
  incubator/logstash/templates/statefulset.yaml
  incubator/logstash/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3709 Update Minio chart to latest release RELEASE.2018-02-09T22-40-05Z
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3370 [stable/phabricator] add ingress and support reverse proxy tls
  stable/phabricator/Chart.yaml
  stable/phabricator/README.md
  stable/phabricator/templates/ingress.yaml
  stable/phabricator/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3626 [spinnaker] Make Jenkins optional
  stable/spinnaker/Chart.yaml
  stable/spinnaker/requirements.lock
  stable/spinnaker/requirements.yaml
  stable/spinnaker/templates/configmap/_jenkins-config.tpl
  stable/spinnaker/templates/configmap/jenkins-jobs.yaml
  stable/spinnaker/templates/configmap/spinnaker-config.yaml
  stable/spinnaker/templates/configmap/test-config.yaml
  stable/spinnaker/templates/hooks/upload-build-image.yaml
  stable/spinnaker/templates/hooks/upload-run-pipeline.yaml
  stable/spinnaker/templates/hooks/upload-run-script.yaml
  stable/spinnaker/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3882 Add OWNERS file for appscode published charts
  stable/g2/.helmignore
  stable/g2/Chart.yaml
  stable/g2/OWNERS
  stable/kubed/.helmignore
  stable/kubed/Chart.yaml
  stable/kubed/OWNERS
  stable/searchlight/.helmignore
  stable/searchlight/Chart.yaml
  stable/searchlight/OWNERS
  stable/stash/.helmignore
  stable/stash/Chart.yaml
  stable/stash/OWNERS
  stable/swift/.helmignore
  stable/swift/Chart.yaml
  stable/swift/OWNERS
  stable/voyager/.helmignore
  stable/voyager/Chart.yaml
  stable/voyager/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/M

#3804 [incubator/zookeeper] Allows alternate scheduler for zookeeper statefulset
  incubator/zookeeper/Chart.yaml
  incubator/zookeeper/README.md
  incubator/zookeeper/templates/statefulset.yaml
  incubator/zookeeper/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3881 Add OWNERS to jenkins chart
  stable/jenkins/Chart.yaml
  stable/jenkins/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3759 [stable/rabbitmq-ha] Enable custom plugin configuration
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/templates/_helpers.tpl
  stable/rabbitmq-ha/templates/configmap.yaml
  stable/rabbitmq-ha/templates/service.yaml
  stable/rabbitmq-ha/templates/serviceaccount.yaml
  stable/rabbitmq-ha/templates/statefulset.yaml
  stable/rabbitmq-ha/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3836 [spinnaker] apply deck port configuration
  stable/spinnaker/Chart.yaml
  stable/spinnaker/templates/deployments/deck.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3895 Publish swift chart 0.7.2
  stable/swift/Chart.yaml
  stable/swift/README.md
  stable/swift/templates/deployment.yaml
  stable/swift/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3886 Jenkins - bump test timeouts
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/test-config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3891 [stable/traefik] Fix version info
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3893 Update postgresql chart maintainers.
  stable/postgresql/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3742 Update CircleCI Python image
  .circleci/config.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3905 [stable/testlink] Fix default SMTP configuration
  stable/testlink/Chart.yaml
  stable/testlink/templates/deployment.yaml
  stable/testlink/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3877 Update README.md with correct default value
  stable/artifactory/Chart.yaml
  stable/artifactory/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3167 [stable/nginx-lego] Convert registry to k8s.gcr.io
  stable/nginx-lego/Chart.yaml
  stable/nginx-lego/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3695 some typo
  stable/lamp/Chart.yaml
  stable/lamp/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3078 consul-readability - seperate resources
  stable/consul/Chart.yaml
  stable/consul/templates/consul-ingress.yaml
  stable/consul/templates/consul-service.yaml
  stable/consul/templates/consul-statefulset.yaml
  stable/consul/templates/gossip-secret.yaml
  stable/consul/templates/pod-dist-budget.yaml
  stable/consul/templates/ui-service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3687 fix typo in README.md
  stable/lamp/Chart.yaml
  stable/lamp/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3907 Bumped helm release for e2e tests
  test/helm-test-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3711 [incubator/gocd] Change the deployment strategy, minor changes in defaults, fixes in PVC.
  incubator/gocd/Chart.yaml
  incubator/gocd/README.md
  incubator/gocd/templates/NOTES.txt
  incubator/gocd/templates/_helpers.tpl
  incubator/gocd/templates/gocd-agent-deployment.yaml
  incubator/gocd/templates/gocd-ea-cluster-role-binding.yaml
  incubator/gocd/templates/gocd-ea-cluster-role.yaml
  incubator/gocd/templates/gocd-ea-service-account.yaml
  incubator/gocd/templates/gocd-server-deployment.yaml
  incubator/gocd/templates/gocd-server-pvc.yaml
  incubator/gocd/templates/ingress.yaml
  incubator/gocd/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3720 [incubator/zookeeper] Makes persistence fully configurable
  incubator/zookeeper/Chart.yaml
  incubator/zookeeper/README.md
  incubator/zookeeper/templates/statefulset.yaml
  incubator/zookeeper/values.yaml
Labels: approved, changes needed, cncf-cla: yes, lgtm, size/M

#3869 [incubator/kafka] Fix schema registry dependency collision
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
  incubator/kafka/requirements.lock
  incubator/kafka/requirements.yaml
  incubator/kafka/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3897 [stable/mongodb-replicaset] Upgrade to MongoDB 3.6
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3405 [stable/redis-ha] add rbac for redis-ha chart
  stable/redis-ha/Chart.yaml
  stable/redis-ha/README.md
  stable/redis-ha/templates/_helpers.tpl
  stable/redis-ha/templates/redis-role.yaml
  stable/redis-ha/templates/redis-rolebinding.yaml
  stable/redis-ha/templates/redis-sentinel-deployment.yaml
  stable/redis-ha/templates/redis-server-deployment.yaml
  stable/redis-ha/templates/redis-serviceaccount.yaml
  stable/redis-ha/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3731 [stable/nginx-ingress] Add affinity and pod disruption budget
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-daemonset.yaml
  stable/nginx-ingress/templates/controller-deployment.yaml
  stable/nginx-ingress/templates/controller-poddisruptionbudget.yaml
  stable/nginx-ingress/templates/default-backend-deployment.yaml
  stable/nginx-ingress/templates/default-backend-poddisruptionbudget.yaml
  stable/nginx-ingress/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3644 Add bitcoind cryptocurrency chart
  stable/bitcoind/.helmignore
  stable/bitcoind/Chart.yaml
  stable/bitcoind/README.md
  stable/bitcoind/templates/NOTES.txt
  stable/bitcoind/templates/_helpers.tpl
  stable/bitcoind/templates/configmap.yaml
  stable/bitcoind/templates/deployment.yaml
  stable/bitcoind/templates/pvc.yaml
  stable/bitcoind/templates/svc.yaml
  stable/bitcoind/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3798 [incubator/jeager] update jeager image versions
  incubator/jaeger/Chart.yaml
  incubator/jaeger/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3887 Add toleration values to newrelic infra chart
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/README.md
  stable/newrelic-infrastructure/templates/daemonset.yaml
  stable/newrelic-infrastructure/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3867 [traefik] - updating to use the latest chart template fullname format
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/NOTES.txt
  stable/traefik/templates/_helpers.tpl
  stable/traefik/templates/acme-pvc.yaml
  stable/traefik/templates/configmap.yaml
  stable/traefik/templates/dashboard-ingress.yaml
  stable/traefik/templates/dashboard-service.yaml
  stable/traefik/templates/default-cert-secret.yaml
  stable/traefik/templates/deployment.yaml
  stable/traefik/templates/dns-provider-secret.yaml
  stable/traefik/templates/rbac.yaml
  stable/traefik/templates/service.yaml
Labels: approved, changes needed, cncf-cla: yes, lgtm, size/L

#3889 fix-typo-in-acs-engine-autoscaler-readme
  stable/acs-engine-autoscaler/Chart.yaml
  stable/acs-engine-autoscaler/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3885 [stable/sumokube] enable customization of DaemonSet's UpdateStrategy
  stable/sumokube/Chart.yaml
  stable/sumokube/README.md
  stable/sumokube/templates/daemonset.yaml
  stable/sumokube/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3872 [stable/traefik] Add affinity config option
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/deployment.yaml
  stable/traefik/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3903 Improve documentation regarding authentication.
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3721 [incubator/kafka] Makes persistence fully configurable
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
  incubator/kafka/templates/configmap.yaml
  incubator/kafka/templates/statefulset.yaml
  incubator/kafka/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3780 [stable/postgresql] add runtime config parameters
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/deployment.yaml
  stable/postgresql/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3777 [stable/prometheus] Use yaml not literal for alertmanagerFiles
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/alertmanager-configmap.yaml
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3794 [incubator/cassandra] Allow customization of securityContext fsGrou…
  incubator/cassandra/Chart.yaml
  incubator/cassandra/templates/cassandra-statefulset.yaml
  incubator/cassandra/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
