Repository helm/charts, pull requests merged in 2018-10, with the labels that each got.

#8017 [stable/dokuwiki] Improve getting LoadBalancer address in chart NOTES…
  stable/dokuwiki/Chart.yaml
  stable/dokuwiki/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm

#8076 [incubator/logstash] Allow explicit setting the clusterIP on service
  incubator/logstash/Chart.yaml
  incubator/logstash/README.md
  incubator/logstash/templates/service.yaml
  incubator/logstash/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8081 [stable/cockroachdb]: Update version to v2.0.6
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/README.md
  stable/cockroachdb/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7961 [stable/percona-xtradb-cluster] Adding pod annotations
  stable/percona-xtradb-cluster/Chart.yaml
  stable/percona-xtradb-cluster/README.md
  stable/percona-xtradb-cluster/templates/statefulset.yaml
  stable/percona-xtradb-cluster/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8025 Expose more minecraft options
  stable/minecraft/Chart.yaml
  stable/minecraft/templates/deployment.yaml
  stable/minecraft/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7232 [incubator/zookeeper] Add secrets to zookeeper
  incubator/zookeeper/Chart.yaml
  incubator/zookeeper/templates/statefulset.yaml
  incubator/zookeeper/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#7549 [incubator/cassandra] Add backup CronJob
  incubator/cassandra/Chart.yaml
  incubator/cassandra/README.md
  incubator/cassandra/templates/_helpers.tpl
  incubator/cassandra/templates/backup/cronjob.yaml
  incubator/cassandra/templates/backup/rbac.yaml
  incubator/cassandra/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8104 [stable/mariadb] Remove unnecessary env. variable on slave pods
  stable/mariadb/Chart.yaml
  stable/mariadb/templates/slave-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm

#8103 [stable/sysdig] Add support for deploying Custom App Checks using Helm Chart
  stable/sysdig/CHANGELOG.md
  stable/sysdig/Chart.yaml
  stable/sysdig/DESIGN.md
  stable/sysdig/README.md
  stable/sysdig/scripts/appchecks2helm
  stable/sysdig/templates/configmap-custom-app-checks.yaml
  stable/sysdig/templates/daemonset.yaml
  stable/sysdig/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8073 add ability to configure deployment strategy
  stable/sonatype-nexus/Chart.yaml
  stable/sonatype-nexus/README.md
  stable/sonatype-nexus/templates/backup-pv.yaml
  stable/sonatype-nexus/templates/deployment.yaml
  stable/sonatype-nexus/templates/pv.yaml
  stable/sonatype-nexus/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8096 [stable/nfs-client-provisioner] Fix typo in README
  stable/nfs-client-provisioner/Chart.yaml
  stable/nfs-client-provisioner/README.md
Labels: Contribution Allowed, approved, lgtm

#7934 Basic auth for https
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/configmap.yaml
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7920 [stable/fluentd-elasticsearch] fix ClusterRoleBinding apiGroups defaults
  stable/fluentd-elasticsearch/Chart.yaml
  stable/fluentd-elasticsearch/templates/clusterrolebinding.yaml
Labels: Contribution Allowed, approved, lgtm

#8120 Upgrade logstash to 6.4.2
  incubator/logstash/Chart.yaml
  incubator/logstash/README.md
  incubator/logstash/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8121 upgrade kibana to 6.4.2
  stable/kibana/Chart.yaml
  stable/kibana/README.md
  stable/kibana/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8122 upgrade filebeat to 6.4.2
  stable/filebeat/Chart.yaml
  stable/filebeat/README.md
  stable/filebeat/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8124 upgrade metricbeat
  stable/metricbeat/Chart.yaml
  stable/metricbeat/README.md
  stable/metricbeat/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8116 [stable/treafik] Upgrade to Træfik v1.7.1
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8127 [stable/grafana] Allow for customisation of livenessProbe and readinessProbe.
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/deployment.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8125 Add TIMEOUT environment variable
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/README.md
  stable/newrelic-infrastructure/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm

#8128 [stable/traefik] Add support for tls-alpn-01 ACME challenge
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/configmap.yaml
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8078 update nginx-ingress README to reflect container version from values.yaml
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
Labels: Contribution Allowed, approved, lgtm

#8100 [incubator/cassandra] update readme SA create to true
  incubator/cassandra/Chart.yaml
  incubator/cassandra/README.md
Labels: Contribution Allowed, approved, lgtm

#8140 [stable/rabbitmq] Allow specifying ulimit and update healthchecks to avoid high CPU usage
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/statefulset.yaml
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7988 [stable/jenkins] Kubernetes 1.9 support as well as automatic apiVersion detection
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/jenkins-master-deployment.yaml
  stable/jenkins/templates/rbac.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8144 [stable/minecraft] upgrade to 1.13.1
  stable/minecraft/Chart.yaml
  stable/minecraft/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7605 Makes azure.json readable from a secret, as per the upstream docs
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/deployment.yaml
  stable/external-dns/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8148 [stable/bookstack] upgrade to 0.24.1
  stable/bookstack/Chart.yaml
  stable/bookstack/README.md
  stable/bookstack/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7381 support for headless services and pod annotations.
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
  stable/mariadb/templates/master-statefulset.yaml
  stable/mariadb/templates/master-svc.yaml
  stable/mariadb/templates/slave-statefulset.yaml
  stable/mariadb/templates/slave-svc.yaml
  stable/mariadb/values-production.yaml
  stable/mariadb/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8146 [stable/rabbitmq] Fix healthchecks
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm

#8158 upgrade to prometheus 2.4.3
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8160 [incubator/fluentd] bump fluentd to 2.3.1
  incubator/fluentd/Chart.yaml
  incubator/fluentd/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8159 [incubator/cassandra] bump cassandra to 3.11.3 and fix charts.yaml
  incubator/cassandra/Chart.yaml
  incubator/cassandra/README.md
  incubator/cassandra/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8161 [incubator/redis-cache] bump redis to 4.0-alpine
  incubator/redis-cache/Chart.yaml
  incubator/redis-cache/README.md
  incubator/redis-cache/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8162 [incubator/vault] bump vault to 0.11.2
  incubator/vault/Chart.yaml
  incubator/vault/README.md
  incubator/vault/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8117 [prometheus-node-exporter] allow setting additional host mounts
  stable/prometheus-node-exporter/Chart.yaml
  stable/prometheus-node-exporter/README.md
  stable/prometheus-node-exporter/templates/daemonset.yaml
  stable/prometheus-node-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7807 [stable/rabbimq] Improve consistensy for persistent storage
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/statefulset.yaml
  stable/rabbitmq/templates/svc-headless.yaml
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8143 chart for Karma - an alertmanager ui
  stable/karma/.helmignore
  stable/karma/Chart.yaml
  stable/karma/OWNERS
  stable/karma/README.md
  stable/karma/ci/test-values.yaml
  stable/karma/templates/NOTES.txt
  stable/karma/templates/_helpers.tpl
  stable/karma/templates/deployment.yaml
  stable/karma/templates/ingress.yaml
  stable/karma/templates/role.yaml
  stable/karma/templates/rolebinding.yaml
  stable/karma/templates/service.yaml
  stable/karma/templates/serviceaccount.yaml
  stable/karma/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8163 [incubator/webpagetest-agent] bump webpagetest-agent to 2018-01-23
  incubator/webpagetest-agent/Chart.yaml
  incubator/webpagetest-agent/README.md
  incubator/webpagetest-agent/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8164 [incubator/webpagetest-server] bump webpagetest-server to 2018-03-08
  incubator/webpagetest-server/Chart.yaml
  incubator/webpagetest-server/README.md
  incubator/webpagetest-server/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8176 cleanup RBAC
  stable/karma/Chart.yaml
  stable/karma/templates/role.yaml
  stable/karma/templates/rolebinding.yaml
Labels: Contribution Allowed, approved, lgtm

#7494 adding chart for prometheus-couchdb-exporters
  stable/prometheus-couchdb-exporter/.helmignore
  stable/prometheus-couchdb-exporter/Chart.yaml
  stable/prometheus-couchdb-exporter/README.md
  stable/prometheus-couchdb-exporter/templates/NOTES.txt
  stable/prometheus-couchdb-exporter/templates/_helpers.tpl
  stable/prometheus-couchdb-exporter/templates/deployment.yaml
  stable/prometheus-couchdb-exporter/templates/ingress.yaml
  stable/prometheus-couchdb-exporter/templates/podsecuritypolicy.yaml
  stable/prometheus-couchdb-exporter/templates/role.yaml
  stable/prometheus-couchdb-exporter/templates/rolebinding.yaml
  stable/prometheus-couchdb-exporter/templates/service.yaml
  stable/prometheus-couchdb-exporter/templates/serviceaccount.yaml
  stable/prometheus-couchdb-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8154 [stable/consul] Add support for tolerations label
  stable/consul/Chart.yaml
  stable/consul/README.md
  stable/consul/templates/consul-statefulset.yaml
  stable/consul/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8178 fix docs
  stable/karma/Chart.yaml
  stable/karma/README.md
  stable/karma/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8109 fix(stable/cockroachdb): Add an explicit selector to the StatefulSet
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/README.md
  stable/cockroachdb/templates/cockroachdb-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm

#8185 [incubator/kafka]: restart job-config OnFailure
  incubator/kafka/Chart.yaml
  incubator/kafka/templates/job-config.yaml
Labels: Contribution Allowed, approved, lgtm

#8079 [stable/keycloak] Add / to end of probe paths
  stable/keycloak/Chart.yaml
  stable/keycloak/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm

#8198 [stable/phpmyadmin] Add kubeapps text to charts READMEs
  stable/phpmyadmin/Chart.yaml
  stable/phpmyadmin/README.md
Labels: Contribution Allowed, approved, lgtm

#8196 [stable/rabbitmq] Add kubeapps text to charts READMEs
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
Labels: Contribution Allowed, approved, lgtm

#8210 [stable/mediawiki] Add kubeapps text to charts READMEs
  stable/mediawiki/Chart.yaml
  stable/mediawiki/README.md
Labels: Contribution Allowed, approved, lgtm

#8211 [stable/mariadb] Add kubeapps text to charts READMEs
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
Labels: Contribution Allowed, approved, lgtm

#8212 [stable/magento] Add kubeapps text to charts READMEs
  stable/magento/Chart.yaml
  stable/magento/README.md
Labels: Contribution Allowed, approved, lgtm

#8213 [stable/joomla] Add kubeapps text to charts READMEs
  stable/joomla/Chart.yaml
  stable/joomla/README.md
Labels: Contribution Allowed, approved, lgtm

#8193 [stable/wordpress] Add kubeapps text to charts READMEs
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
Labels: Contribution Allowed, approved, lgtm

#8194 [stable/redmine] Add kubeapps text to charts READMEs
  stable/redmine/Chart.yaml
  stable/redmine/README.md
Labels: Contribution Allowed, approved, lgtm

#8195 [stable/redis] Add kubeapps text to charts READMEs
  stable/redis/Chart.yaml
  stable/redis/README.md
Labels: Contribution Allowed, approved, lgtm

#8199 [stable/phpbb] Add kubeapps text to charts READMEs
  stable/phpbb/Chart.yaml
  stable/phpbb/README.md
Labels: Contribution Allowed, approved, lgtm

#8200 [stable/phabricator] Add kubeapps text to charts READMEs
  stable/phabricator/Chart.yaml
  stable/phabricator/README.md
Labels: Contribution Allowed, approved, lgtm

#8197 [stable/prestashop] Add kubeapps text to charts READMEs
  stable/prestashop/Chart.yaml
  stable/prestashop/README.md
Labels: Contribution Allowed, approved, lgtm

#8201 [stable/parse] Add kubeapps text to charts READMEs
  stable/parse/Chart.yaml
  stable/parse/README.md
Labels: Contribution Allowed, approved, lgtm

#8202 [stable/owncloud] Add kubeapps text to charts READMEs
  stable/owncloud/Chart.yaml
  stable/owncloud/README.md
Labels: Contribution Allowed, approved, lgtm

#8203 [stable/osclass] Add kubeapps text to charts READMEs
  stable/osclass/Chart.yaml
  stable/osclass/README.md
Labels: Contribution Allowed, approved, lgtm

#8204 [stable/orangehrm] Add kubeapps text to charts READMEs
  stable/orangehrm/Chart.yaml
  stable/orangehrm/README.md
Labels: Contribution Allowed, approved, lgtm

#8205 [stable/opencart] Add kubeapps text to charts READMEs
  stable/opencart/Chart.yaml
  stable/opencart/README.md
Labels: Contribution Allowed, approved, lgtm

#8206 [stable/odoo] Add kubeapps text to charts READMEs
  stable/odoo/Chart.yaml
  stable/odoo/README.md
Labels: Contribution Allowed, approved, lgtm

#8207 [stable/nats] Add kubeapps text to charts READMEs
  stable/nats/Chart.yaml
  stable/nats/README.md
Labels: Contribution Allowed, approved, lgtm

#8208 [stable/moodle] Add kubeapps text to charts READMEs
  stable/moodle/Chart.yaml
  stable/moodle/README.md
Labels: Contribution Allowed, approved, lgtm

#8209 [stable/mongodb] Add kubeapps text to charts READMEs
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
Labels: Contribution Allowed, approved, lgtm

#8214 [stable/jasperreports] Add kubeapps text to charts READMEs
  stable/jasperreports/Chart.yaml
  stable/jasperreports/README.md
Labels: Contribution Allowed, approved, lgtm

#8215 [stable/ghost] Add kubeapps text to charts READMEs
  stable/ghost/Chart.yaml
  stable/ghost/README.md
Labels: Contribution Allowed, approved, lgtm

#8216 [stable/drupal] Add kubeapps text to charts READMEs
  stable/drupal/Chart.yaml
  stable/drupal/README.md
Labels: Contribution Allowed, approved, lgtm

#8217 [stable/dokuwiki] Add kubeapps text to charts READMEs
  stable/dokuwiki/Chart.yaml
  stable/dokuwiki/README.md
Labels: Contribution Allowed, approved, lgtm

#8218 [stable/suitecrm] Add kubeapps text to charts READMEs
  stable/suitecrm/Chart.yaml
  stable/suitecrm/README.md
Labels: Contribution Allowed, approved, lgtm

#8219 [stable/testlink] Add kubeapps text to charts READMEs
  stable/testlink/Chart.yaml
  stable/testlink/README.md
Labels: Contribution Allowed, approved, lgtm

#8031 [stable/kube-hunter] Initial release.
  stable/kube-hunter/.helmignore
  stable/kube-hunter/Chart.yaml
  stable/kube-hunter/OWNERS
  stable/kube-hunter/README.md
  stable/kube-hunter/templates/NOTES.txt
  stable/kube-hunter/templates/_helpers.tpl
  stable/kube-hunter/templates/cronjob.yaml
  stable/kube-hunter/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8080 [incubator/etcd] Change listen urls to have an IP which is required in etcd3
  incubator/etcd/Chart.yaml
  incubator/etcd/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm

#8028 [stable/rabbitmq-ha] Support of Pod Priority for Statefulset
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/templates/statefulset.yaml
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7513 [hl-composer] Add Composer chart
  stable/hl-composer/.helmignore
  stable/hl-composer/Chart.yaml
  stable/hl-composer/OWNERS
  stable/hl-composer/README.md
  stable/hl-composer/templates/NOTES.txt
  stable/hl-composer/templates/_helpers.tpl
  stable/hl-composer/templates/hl-composer-cli-deployment.yaml
  stable/hl-composer/templates/hl-composer-pg-deployment.yaml
  stable/hl-composer/templates/hl-composer-pg-ingress.yaml
  stable/hl-composer/templates/hl-composer-pg-service.yaml
  stable/hl-composer/templates/hl-composer-pvc.yaml
  stable/hl-composer/templates/hl-composer-rest-deployment.yaml
  stable/hl-composer/templates/hl-composer-rest-ingress.yaml
  stable/hl-composer/templates/hl-composer-rest-secret.yaml
  stable/hl-composer/templates/hl-composer-rest-service.yaml
  stable/hl-composer/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7640 [traefik] added ssl.cipherSuites, imageTag and chart version bumped
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/_helpers.tpl
  stable/traefik/templates/configmap.yaml
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7877 Add RootCAs as a configurable value to Traefik chart
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/_helpers.tpl
  stable/traefik/templates/configmap.yaml
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm

#6804 [Incubator/gogs] add crons config.
  incubator/gogs/Chart.yaml
  incubator/gogs/templates/configmap.yaml
  incubator/gogs/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#7328 [stable/kiam] Adding step to annotate namespace
  stable/kiam/Chart.yaml
  stable/kiam/templates/NOTES.txt
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#6483 [stable/prisma]: add Prisma chart
  stable/prisma/.helmignore
  stable/prisma/Chart.yaml
  stable/prisma/OWNERS
  stable/prisma/README.md
  stable/prisma/ci/example-values.yaml
  stable/prisma/requirements.lock
  stable/prisma/requirements.yaml
  stable/prisma/templates/NOTES.txt
  stable/prisma/templates/_helpers.tpl
  stable/prisma/templates/configmap.yaml
  stable/prisma/templates/deployment.yaml
  stable/prisma/templates/ingress.yaml
  stable/prisma/templates/secret.yaml
  stable/prisma/templates/service.yaml
  stable/prisma/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm, size/L

#6426 [stable/unifi] unifi controller chart (New chart)
  stable/unifi/.helmignore
  stable/unifi/Chart.yaml
  stable/unifi/OWNERS
  stable/unifi/README.md
  stable/unifi/templates/NOTES.txt
  stable/unifi/templates/_helpers.tpl
  stable/unifi/templates/controller-svc.yaml
  stable/unifi/templates/deployment.yaml
  stable/unifi/templates/discovery-svc.yaml
  stable/unifi/templates/gui-svc.yaml
  stable/unifi/templates/ingress.yaml
  stable/unifi/templates/pvc.yaml
  stable/unifi/templates/stun-svc.yaml
  stable/unifi/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm, size/XL

#7987 [stable/postgresql] Fix metrics volume arguments
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm

#8233 [stable/traefik] upgrade to 1.7.2
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7707 [incubator/fluent-cloudwatch] Fix fatal bug and Support EC2 instance role
  incubator/fluentd-cloudwatch/Chart.yaml
  incubator/fluentd-cloudwatch/README.md
  incubator/fluentd-cloudwatch/secrets/aws_access_key_id
  incubator/fluentd-cloudwatch/secrets/aws_secret_access_key
  incubator/fluentd-cloudwatch/templates/daemonset.yaml
  incubator/fluentd-cloudwatch/templates/secrets.yaml
  incubator/fluentd-cloudwatch/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8243 add optional ingress for selenium chart
  stable/selenium/Chart.yaml
  stable/selenium/README.md
  stable/selenium/templates/ingress.yaml
  stable/selenium/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8246 Fix init script
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm

#8251 [stable/kube-slack] Upgrade image version to the latest
  stable/kube-slack/Chart.yaml
  stable/kube-slack/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8253 Move gogs to 0.11.66 image
  incubator/gogs/Chart.yaml
  incubator/gogs/README.md
  incubator/gogs/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8255 [stable/rabbitmq] Fix ports on svc-headless.yaml
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/templates/svc-headless.yaml
Labels: Contribution Allowed, approved, lgtm

#8257 [stable/nats] Force random password to start with letter
  stable/nats/Chart.yaml
  stable/nats/templates/_helpers.tpl
  stable/nats/templates/configmap.yaml
Labels: Contribution Allowed, approved, lgtm

#8223 [external-dns] Fix RBAC for istio gateways
  stable/external-dns/Chart.yaml
  stable/external-dns/templates/clusterrole.yaml
Labels: Contribution Allowed, approved, lgtm

#7849 [stable/traefik] Added ability to log itself logs in json format
  stable/traefik/Chart.yaml
  stable/traefik/templates/configmap.yaml
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8248 [kafka] Fix incorrect producer consumer address in notes template
  incubator/kafka/Chart.yaml
  incubator/kafka/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm

#8269 [stable/datadog] Upgrade to latest app version
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/agent-clusterrole.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8276 upgrade metrics server
  stable/metrics-server/Chart.yaml
  stable/metrics-server/README.md
  stable/metrics-server/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8271 [stable/kiam] Dont add prometheus env vars if scrape is false
  stable/kiam/Chart.yaml
  stable/kiam/templates/agent-daemonset.yaml
  stable/kiam/templates/server-daemonset.yaml
Labels: Contribution Allowed, approved, lgtm

#8274 [stable/falco] Resolve cluster hostnames when using hostnetwork
  stable/falco/CHANGELOG.md
  stable/falco/Chart.yaml
  stable/falco/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm

#8266 Add an option to disable anonymous requests to the 5984 port
  incubator/couchdb/Chart.yaml
  incubator/couchdb/templates/statefulset.yaml
  incubator/couchdb/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8165 [stable/postgresql] Add terminationGracePeriodSeconds parameter
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/deployment.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7235 [stable/kiam] Added 3.0 rc1 version support
  stable/kiam/Chart.yaml
  stable/kiam/templates/agent-daemonset.yaml
  stable/kiam/templates/server-daemonset.yaml
  stable/kiam/templates/server-read-clusterrole.yaml
  stable/kiam/templates/server-read-clusterrolebinding.yaml
  stable/kiam/templates/server-write-clusterrole.yaml
  stable/kiam/templates/server-write-clusterrolebinding.yaml
  stable/kiam/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#8188 [stable/keycloak] Add OWNERS and update maintainers
  stable/keycloak/Chart.yaml
  stable/keycloak/OWNERS
Labels: Contribution Allowed, approved, lgtm

#8264 [stable/prometheus] add node-exporter podsecuritypolicy support
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/node-exporter-podsecuritypolicy.yaml
  stable/prometheus/templates/node-exporter-role.yaml
  stable/prometheus/templates/node-exporter-rolebinding.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8277 upgrade auditbeat
  stable/auditbeat/Chart.yaml
  stable/auditbeat/README.md
  stable/auditbeat/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8288 [stable/traefik] Replaced toml block for traefik logs
  stable/traefik/Chart.yaml
  stable/traefik/templates/configmap.yaml
Labels: Contribution Allowed, approved, lgtm

#8290 [stable/magento] Update NOTES.txt setting the database password on up…
  stable/magento/Chart.yaml
  stable/magento/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm

#8234 Spinnaker inline script in values
  stable/spinnaker/Chart.yaml
  stable/spinnaker/README.md
  stable/spinnaker/templates/configmap/additional-configmaps.yaml
  stable/spinnaker/templates/configmap/additional-scripts.yaml
  stable/spinnaker/templates/configmap/halyard-config.yaml
  stable/spinnaker/templates/hooks/install-using-hal.yaml
  stable/spinnaker/templates/ingress/deck.yaml
  stable/spinnaker/templates/ingress/gate.yaml
  stable/spinnaker/templates/secrets/additional-secrets.yaml
  stable/spinnaker/templates/statefulsets/halyard.yaml
  stable/spinnaker/values.yaml
  stable/spinnaker/values_saml.yaml
Labels: Contribution Allowed, approved, lgtm

#8301 update newrelic infra to 1.2.0
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/README.md
  stable/newrelic-infrastructure/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7567 [incubator/elasticsearch] Add nodeAffinity parameters
  incubator/elasticsearch/Chart.yaml
  incubator/elasticsearch/README.md
  incubator/elasticsearch/templates/client-deployment.yaml
  incubator/elasticsearch/templates/data-statefulset.yaml
  incubator/elasticsearch/templates/master-statefulset.yaml
  incubator/elasticsearch/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8132 Add Kibana access notes to output
  stable/kibana/Chart.yaml
  stable/kibana/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm

#8273 Initial commit for Terracotta Server OSS helm chart
  stable/terracotta/.helmignore
  stable/terracotta/Chart.yaml
  stable/terracotta/OWNERS
  stable/terracotta/README.md
  stable/terracotta/templates/NOTES.txt
  stable/terracotta/templates/_helpers.tpl
  stable/terracotta/templates/config.yaml
  stable/terracotta/templates/role.yaml
  stable/terracotta/templates/rolebinding.yaml
  stable/terracotta/templates/service.yaml
  stable/terracotta/templates/serviceaccount.yaml
  stable/terracotta/templates/statefulset.yaml
  stable/terracotta/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8226 [Stable] Add support for configmap, additional volumes and volume mounts sonatype-nexus chart
  stable/sonatype-nexus/Chart.yaml
  stable/sonatype-nexus/README.md
  stable/sonatype-nexus/templates/configmap.yaml
  stable/sonatype-nexus/templates/deployment.yaml
  stable/sonatype-nexus/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8312 Added support for clusterIP and headless services.
  stable/chartmuseum/Chart.yaml
  stable/chartmuseum/README.md
  stable/chartmuseum/templates/service.yaml
  stable/chartmuseum/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8107 add Jaeger-operator to helm charts
  stable/jaeger-operator/.helmignore
  stable/jaeger-operator/Chart.yaml
  stable/jaeger-operator/OWNERS
  stable/jaeger-operator/README.md
  stable/jaeger-operator/templates/NOTES.txt
  stable/jaeger-operator/templates/_helpers.tpl
  stable/jaeger-operator/templates/crd.yaml
  stable/jaeger-operator/templates/deployment.yaml
  stable/jaeger-operator/templates/role-binding.yaml
  stable/jaeger-operator/templates/role.yaml
  stable/jaeger-operator/templates/service-account.yaml
  stable/jaeger-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8082 [incubator/elasticsearch] fix hardcoded busybox image name
  incubator/elasticsearch/Chart.yaml
  incubator/elasticsearch/README.md
  incubator/elasticsearch/templates/client-deployment.yaml
  incubator/elasticsearch/templates/data-statefulset.yaml
  incubator/elasticsearch/templates/master-statefulset.yaml
  incubator/elasticsearch/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8272 [stable/mongodb] - Allow using custom initialization scripts
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/files/docker-entrypoint-initdb.d/README.md
  stable/mongodb/templates/deployment-standalone.yaml
  stable/mongodb/templates/initialization-configmap.yaml
  stable/mongodb/templates/statefulset-primary-rs.yaml
Labels: Contribution Allowed, approved, lgtm

#8287 [stable/mariadb] Expose securityContext parameters in values yaml files
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
  stable/mariadb/templates/master-statefulset.yaml
  stable/mariadb/templates/slave-statefulset.yaml
  stable/mariadb/values-production.yaml
  stable/mariadb/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7266 [stable/stellar-core]: Release 1.0.0 (initial release)
  stable/stellar-core/Chart.yaml
  stable/stellar-core/OWNERS
  stable/stellar-core/README.md
  stable/stellar-core/requirements.lock
  stable/stellar-core/requirements.yaml
  stable/stellar-core/templates/NOTES.txt
  stable/stellar-core/templates/_helpers.tpl
  stable/stellar-core/templates/deployment.yaml
  stable/stellar-core/templates/pvc.yaml
  stable/stellar-core/templates/secret.yaml
  stable/stellar-core/templates/service-http.yaml
  stable/stellar-core/templates/service-peer.yaml
  stable/stellar-core/templates/serviceaccount.yaml
  stable/stellar-core/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#8322 [stable/mariadb] Enable metrics by default in production environment
  stable/mariadb/Chart.yaml
  stable/mariadb/values-production.yaml
Labels: Contribution Allowed, approved, lgtm

#8068 typo fixed
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
Labels: Contribution Allowed, approved, lgtm

#8319 [stable/joomla] Add nodeSelector, tolerations and affinity
  stable/joomla/Chart.yaml
  stable/joomla/README.md
  stable/joomla/templates/deployment.yaml
  stable/joomla/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8335 [stable/wordpress] Simplify ingress configuration for cert-manager
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
  stable/wordpress/templates/ingress.yaml
  stable/wordpress/values-production.yaml
  stable/wordpress/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8115 [stable/mongodb-replicaset] Fix various bootstrap issues
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/README.md
  stable/mongodb-replicaset/init/on-start.sh
  stable/mongodb-replicaset/templates/mongodb-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm

#8192 [stable/keycloak] Update to 4.5.0.Final
  stable/keycloak/Chart.yaml
  stable/keycloak/README.md
  stable/keycloak/templates/configmap.yaml
  stable/keycloak/templates/statefulset.yaml
  stable/keycloak/templates/test/test-pod.yaml
  stable/keycloak/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8131 Fix elastic DNS information output.
  incubator/elasticsearch/Chart.yaml
  incubator/elasticsearch/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm

#8337 [stable/rabbitmq] Log to stdout and add metrics exporter
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/_helpers.tpl
  stable/rabbitmq/templates/statefulset.yaml
  stable/rabbitmq/templates/svc.yaml
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7067 [stable/percona] Add support for nodeSelector and tolerations labels
  stable/percona/Chart.yaml
  stable/percona/README.md
  stable/percona/templates/deployment.yaml
  stable/percona/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#8369 Wordpress tls
  stable/wordpress/Chart.yaml
  stable/wordpress/values-production.yaml
  stable/wordpress/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8370 Bugfix: jaeger-operator should use own serviceAccount
  stable/jaeger-operator/Chart.yaml
  stable/jaeger-operator/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm

#8351 [stable/dokuwiki] Simplify ingress configuration for cert-manager
  stable/dokuwiki/Chart.yaml
  stable/dokuwiki/README.md
  stable/dokuwiki/templates/ingress.yaml
  stable/dokuwiki/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8352 [stable/drupal] Simplify ingress configuration for cert-manager
  stable/drupal/Chart.yaml
  stable/drupal/README.md
  stable/drupal/templates/_helpers.tpl
  stable/drupal/templates/apache-pvc.yaml
  stable/drupal/templates/deployment.yaml
  stable/drupal/templates/drupal-pvc.yaml
  stable/drupal/templates/ingress.yaml
  stable/drupal/templates/secrets.yaml
  stable/drupal/templates/svc.yaml
  stable/drupal/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8362 [stable/mediawiki] Simplify ingress configuration for cert-manager
  stable/mediawiki/Chart.yaml
  stable/mediawiki/README.md
  stable/mediawiki/templates/ingress.yaml
  stable/mediawiki/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8363 [stable/joomla] Simplify ingress configuration for cert-manager
  stable/joomla/Chart.yaml
  stable/joomla/README.md
  stable/joomla/templates/ingress.yaml
  stable/joomla/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8378 [stable/concourse] Fix postgres and ldap deployment variables
  stable/concourse/Chart.yaml
  stable/concourse/templates/web-deployment.yaml
Labels: Contribution Allowed, approved, lgtm

#8358 [stable/traefik] Add a parameter to set acme.onHostRule in traefik.toml
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/configmap.yaml
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8388 Fix RabbitMQ README
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
Labels: Contribution Allowed, approved, lgtm

#7049 [stable/percona-xtradb-cluster] Add tolerations labels
  stable/percona-xtradb-cluster/Chart.yaml
  stable/percona-xtradb-cluster/README.md
  stable/percona-xtradb-cluster/files/entrypoint.sh
  stable/percona-xtradb-cluster/templates/_helpers.tpl
  stable/percona-xtradb-cluster/templates/statefulset.yaml
  stable/percona-xtradb-cluster/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#8372 [stable/ghost] Allow configuring securityContext for ghost chart
  stable/ghost/Chart.yaml
  stable/ghost/README.md
  stable/ghost/templates/deployment.yaml
  stable/ghost/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8377 [stable/redis] NetworkPolicy podSelector should also match "release"
  stable/redis/Chart.yaml
  stable/redis/templates/networkpolicy.yaml
Labels: Contribution Allowed, approved, lgtm

#7580 [incubator/elasticsearch] Add option to add additional ES_JAVA_OPTS parameters
  incubator/elasticsearch/Chart.yaml
  incubator/elasticsearch/README.md
  incubator/elasticsearch/templates/client-deployment.yaml
  incubator/elasticsearch/templates/data-statefulset.yaml
  incubator/elasticsearch/templates/master-statefulset.yaml
  incubator/elasticsearch/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8300 [stable/jenkins] Fix component label in NOTES.txt ...
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm

#8368 Add OWNERS file to stable/openebs
  stable/openebs/.helmignore
  stable/openebs/Chart.yaml
  stable/openebs/OWNERS
Labels: Contribution Allowed, approved, lgtm

#8003 [stable/kiam] update service port name
  stable/kiam/Chart.yaml
  stable/kiam/templates/server-service.yaml
Labels: Contribution Allowed, approved, lgtm

#8398 [incubator/schema-registry] Kafkastore.replication.factor is unused
  incubator/schema-registry/Chart.yaml
  incubator/schema-registry/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8402 upgrade nginx-ingress image
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8404 CoreDNS: amend values.yaml to match template
  stable/coredns/Chart.yaml
  stable/coredns/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8134 [stable/prometheus-postgres-exporter] Added flag for disabling default metrics
  stable/prometheus-postgres-exporter/Chart.yaml
  stable/prometheus-postgres-exporter/README.md
  stable/prometheus-postgres-exporter/templates/deployment.yaml
  stable/prometheus-postgres-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm

#8000 [stable/prometheus-mysql-exporter] split datasource in separate mysql connection vars
  stable/prometheus-mysql-exporter/Chart.yaml
  stable/prometheus-mysql-exporter/README.md
  stable/prometheus-mysql-exporter/templates/deployment.yaml
  stable/prometheus-mysql-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm
