Repository helm/charts, pull requests merged in 2018-05, with the labels that each got.

#5339 Update nginx-ingress image to 0.14.0
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5340 Use defaults in values.yaml (stable/mongodb)
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5349 [stable/external-dns] Update externaldns chart to 0.5.0
  stable/external-dns/Chart.yaml
  stable/external-dns/templates/clusterrole.yaml
  stable/external-dns/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5077 [stable/ghost] Add ingress resource. Fix minor bugs
  stable/ghost/Chart.yaml
  stable/ghost/templates/_helpers.tpl
  stable/ghost/templates/ingress.yaml
  stable/ghost/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5256 Added prometheus scrape annotations
  stable/prometheus-redis-exporter/Chart.yaml
  stable/prometheus-redis-exporter/README.md
  stable/prometheus-redis-exporter/templates/deployment.yaml
  stable/prometheus-redis-exporter/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5262 [stable/anchore-engine] Adds OWNERS file
  stable/anchore-engine/.helmignore
  stable/anchore-engine/Chart.yaml
  stable/anchore-engine/OWNERS
  stable/anchore-engine/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4909 [stable/rabbitmq] Fix workload API
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/templates/_helpers.tpl
  stable/rabbitmq/templates/statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5297 add owner of tf-notebook chart
  stable/tensorflow-notebook/Chart.yaml
  stable/tensorflow-notebook/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5140 [stable/memcached] add fullnameOverride option
  stable/memcached/Chart.yaml
  stable/memcached/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/S

#4950 [stable/grafana] Added ability to specify a different repository for dashboard download
  stable/grafana/Chart.yaml
  stable/grafana/templates/configmap.yaml
  stable/grafana/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4803 [stable/kubernetes-dashboard] set ingress Secure-Backends as default value
  stable/kubernetes-dashboard/Chart.yaml
  stable/kubernetes-dashboard/README.md
  stable/kubernetes-dashboard/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4903 Add support for encrypted connection between zetcd and etcd
  stable/zetcd/Chart.yaml
  stable/zetcd/README.md
  stable/zetcd/templates/deployment.yaml
  stable/zetcd/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4826 [stable] Add a Helm chart for k8s-spot-rescheduler
  stable/k8s-spot-rescheduler/.helmignore
  stable/k8s-spot-rescheduler/Chart.yaml
  stable/k8s-spot-rescheduler/OWNERS
  stable/k8s-spot-rescheduler/README.md
  stable/k8s-spot-rescheduler/templates/NOTES.txt
  stable/k8s-spot-rescheduler/templates/_helpers.tpl
  stable/k8s-spot-rescheduler/templates/clusterrole.yaml
  stable/k8s-spot-rescheduler/templates/clusterrolebinding.yaml
  stable/k8s-spot-rescheduler/templates/deployment.yaml
  stable/k8s-spot-rescheduler/templates/serviceaccount.yaml
  stable/k8s-spot-rescheduler/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4481 added Apache superset charts
  stable/superset/.helmignore
  stable/superset/Chart.yaml
  stable/superset/README.md
  stable/superset/templates/NOTES.txt
  stable/superset/templates/_helpers.tpl
  stable/superset/templates/configmap.yaml
  stable/superset/templates/deployment.yaml
  stable/superset/templates/ingress.yaml
  stable/superset/templates/pvc.yaml
  stable/superset/templates/secret.yaml
  stable/superset/templates/svc.yaml
  stable/superset/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#5367 [stable/redis]Fix registryName
  stable/redis/Chart.yaml
  stable/redis/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/S

#5375 [stable/mongo] Use stable mongodb version in the chart
  stable/mongodb/Chart.yaml
  stable/mongodb/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5374 [stable/sonarqube] Update url in test and probes
  stable/sonarqube/Chart.yaml
  stable/sonarqube/templates/deployment.yaml
  stable/sonarqube/templates/test-config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4422 [stable/prometheus]: Make the security context customizable
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/alertmanager-deployment.yaml
  stable/prometheus/templates/kube-state-metrics-deployment.yaml
  stable/prometheus/templates/pushgateway-deployment.yaml
  stable/prometheus/templates/server-deployment.yaml
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5287 [stable/rethinkdb] Fix proxy service annotations
  stable/rethinkdb/Chart.yaml
  stable/rethinkdb/README.md
  stable/rethinkdb/templates/rethinkdb-proxy-service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3570 Add HackMD to incubator
  stable/hackmd/.helmignore
  stable/hackmd/Chart.yaml
  stable/hackmd/README.md
  stable/hackmd/requirements.lock
  stable/hackmd/requirements.yaml
  stable/hackmd/templates/NOTES.txt
  stable/hackmd/templates/_helpers.tpl
  stable/hackmd/templates/deployment.yaml
  stable/hackmd/templates/ingress.yaml
  stable/hackmd/templates/pvc.yaml
  stable/hackmd/templates/service.yaml
  stable/hackmd/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4277 Update to latest release RELEASE.2018-04-27T23-33-52Z
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/templates/configmap.yaml
  stable/minio/templates/deployment.yaml
  stable/minio/templates/post-install-create-bucket-job.yaml
  stable/minio/templates/statefulset.yaml
  stable/minio/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4175 [incubator/mysqlha] Use volumeClaimTemplates.spec.storageClassName
  incubator/mysqlha/Chart.yaml
  incubator/mysqlha/README.md
  incubator/mysqlha/templates/statefulset.yaml
  incubator/mysqlha/values.yaml
Labels: approved, changes needed, cncf-cla: yes, lgtm, size/M

#4514 [stable/mysql] add option to run sql script post container start
  stable/mysql/Chart.yaml
  stable/mysql/README.md
  stable/mysql/templates/configurationFiles-configmap.yaml
  stable/mysql/templates/deployment.yaml
  stable/mysql/templates/initializationFiles-configmap.yaml
  stable/mysql/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4765 [stable/consul] Provide advanced configuration options for consul (resubmit)
  stable/consul/Chart.yaml
  stable/consul/README.md
  stable/consul/templates/consul-statefulset.yaml
  stable/consul/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5062 New chart dmarc2logstash
  stable/dmarc2logstash/.helmignore
  stable/dmarc2logstash/Chart.yaml
  stable/dmarc2logstash/OWNERS
  stable/dmarc2logstash/README.md
  stable/dmarc2logstash/templates/NOTES.txt
  stable/dmarc2logstash/templates/_helpers.tpl
  stable/dmarc2logstash/templates/configmap.yaml
  stable/dmarc2logstash/templates/deployment.yaml
  stable/dmarc2logstash/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5111 [incubator/cassandra] Standardize labels
  incubator/cassandra/Chart.yaml
  incubator/cassandra/templates/NOTES.txt
  incubator/cassandra/templates/_helpers.tpl
  incubator/cassandra/templates/cassandra-statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5122 [stable/gocd] Support tls for ingress
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/README.md
  stable/gocd/templates/NOTES.txt
  stable/gocd/templates/ingress.yaml
  stable/gocd/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4875 Update Sematext Docker agent image name and other improvements
  stable/sematext-docker-agent/Chart.yaml
  stable/sematext-docker-agent/README.md
  stable/sematext-docker-agent/templates/configmap.yaml
  stable/sematext-docker-agent/templates/daemonset.yaml
  stable/sematext-docker-agent/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4961 Add documentation about MySQL random passwords
  stable/mysql/Chart.yaml
  stable/mysql/README.md
  stable/mysql/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5351 Create a secret for external PostgreSQL instances
  stable/sonarqube/Chart.yaml
  stable/sonarqube/templates/deployment.yaml
  stable/sonarqube/templates/secret.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5324 [stable/concourse] hard antiaffinity for workers
  stable/concourse/Chart.yaml
  stable/concourse/README.md
  stable/concourse/templates/worker-statefulset.yaml
  stable/concourse/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5333 [artifactory-ha] recreation for 5327 for conflicts with other PR
  stable/artifactory-ha/Chart.yaml
  stable/artifactory-ha/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5257 Kong, Cassandra, and PostgreSQL version bump
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/requirements.lock
  stable/kong/requirements.yaml
  stable/kong/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5323 [stable/redis] minimal support for persistence.existingClaim
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/templates/redis-master-statefulset.yaml
  stable/redis/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5136 [stable/grafana] Allow for specification of ldap.toml
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/deployment.yaml
  stable/grafana/templates/secret.yaml
  stable/grafana/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5175 [stable/openvpn] Update resource labels to latest best practices
  stable/openvpn/Chart.yaml
  stable/openvpn/templates/NOTES.txt
  stable/openvpn/templates/_helpers.tpl
  stable/openvpn/templates/certs-pvc.yaml
  stable/openvpn/templates/config-openvpn.yaml
  stable/openvpn/templates/openvpn-deployment.yaml
  stable/openvpn/templates/openvpn-service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5195 add myself as owner of prometheus chart
  stable/prometheus/Chart.yaml
  stable/prometheus/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5291 fix typo in mssql's readme
  stable/mssql-linux/Chart.yaml
  stable/mssql-linux/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5233 Artifactory ha nginx bugfix
  stable/artifactory-ha/Chart.yaml
  stable/artifactory-ha/README.md
  stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
  stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
  stable/artifactory-ha/templates/nginx-deployment.yaml
  stable/artifactory-ha/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5392 Add ExternalDNS configuration docs to nginx-ingress chart
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#5391 [k8s-spot-scheduler] update readme change to stable channel
  stable/k8s-spot-rescheduler/Chart.yaml
  stable/k8s-spot-rescheduler/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5347 [incubator/logstash] Add LoadBalancerIP to values
  incubator/logstash/Chart.yaml
  incubator/logstash/README.md
  incubator/logstash/templates/service.yaml
  incubator/logstash/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5232 Artifactory nginx bugfix
  stable/artifactory/Chart.yaml
  stable/artifactory/README.md
  stable/artifactory/templates/artifactory-deployment.yaml
  stable/artifactory/templates/nginx-deployment.yaml
  stable/artifactory/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5162 Remove bind_ip_all incompatible flag
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/init/on-start.sh
  stable/mongodb-replicaset/templates/mongodb-statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5412 [stable/mediawiki] Allow configuration of svc spec.loadBalancerIP
  stable/mediawiki/Chart.yaml
  stable/mediawiki/templates/svc.yaml
  stable/mediawiki/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5280 [stable/redis] adding pod antiaffinity capability to redis slaves
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/templates/redis-slave-deployment.yaml
  stable/redis/values-production.yaml
  stable/redis/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5151 [stable/consul] Fix statefulset selector
  stable/consul/Chart.yaml
  stable/consul/templates/consul-ingress.yaml
  stable/consul/templates/consul-statefulset.yaml
  stable/consul/templates/gossip-secret.yaml
  stable/consul/templates/pod-dist-budget.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5410 vault - fixing copy pasta for non default namespaces
  incubator/vault/Chart.yaml
  incubator/vault/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5416 [stable/dask] bump version to 0.17.4
  stable/dask/Chart.yaml
  stable/dask/README.md
  stable/dask/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5229 add ingress path for kubernetes-dashboard
  stable/kubernetes-dashboard/Chart.yaml
  stable/kubernetes-dashboard/README.md
  stable/kubernetes-dashboard/templates/ingress.yaml
  stable/kubernetes-dashboard/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5422 [stable/prometheus] typo fix: optinal->optional
  stable/prometheus/Chart.yaml
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5096 [stable/docker-registry] Add optional service clusterIP
  stable/docker-registry/Chart.yaml
  stable/docker-registry/README.md
  stable/docker-registry/templates/service.yaml
  stable/docker-registry/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5190 Dont create configmap without configs
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/templates/daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5337 stable/metallb: update to MetalLB 0.6.2.
  stable/metallb/Chart.yaml
  stable/metallb/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5307 Typo fix in test/README.md: Kuberentes->Kubernetes
  test/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5314 [incubator/drone] Allows DinD environment variables
  incubator/drone/Chart.yaml
  incubator/drone/README.md
  incubator/drone/templates/deployment-agent.yaml
  incubator/drone/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5217 fix PR#3308
  stable/prometheus/Chart.yaml
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5191 [stable/rabbitmq-ha] Add fullnameOverride
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/S

#5172 [stable/neo4j] Update Neo4j to 3.3.4
  stable/neo4j/Chart.yaml
  stable/neo4j/README.md
  stable/neo4j/ci/ci-values.yaml
  stable/neo4j/templates/NOTES.txt
  stable/neo4j/templates/core-statefulset.yaml
  stable/neo4j/templates/poddisruptionbudget.yaml
  stable/neo4j/templates/tests/test-config.yaml
  stable/neo4j/templates/tests/test-neo4j-cluster.yaml
  stable/neo4j/test.sh
  stable/neo4j/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5238 [stable/spinnaker] Fix for k8s 1.9.4 or upper version
  stable/spinnaker/Chart.yaml
  stable/spinnaker/requirements.lock
  stable/spinnaker/requirements.yaml
  stable/spinnaker/templates/configmap/spinnaker-config.yaml
  stable/spinnaker/templates/hooks/create-bucket.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5409 [stable/jenkins] Inherit existing plugins from Jenkins image
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/config.yaml
  stable/jenkins/templates/jenkins-master-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5448 [stable/redis] typo fix: persitent->persistent
  stable/redis/Chart.yaml
  stable/redis/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5469 pod annotations on prometheus-pushgateway pod
  stable/prometheus-pushgateway/Chart.yaml
  stable/prometheus-pushgateway/README.md
  stable/prometheus-pushgateway/templates/deployment.yaml
  stable/prometheus-pushgateway/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5429 [stable/concourse] Add missing release labels to pods
  stable/concourse/Chart.yaml
  stable/concourse/templates/web-deployment.yaml
  stable/concourse/templates/worker-statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5395 [stable/sonatype-nexus] Nexus update version to 3.10.0
  stable/sonatype-nexus/Chart.yaml
  stable/sonatype-nexus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5460 [stable/openvpn] service label selector match pod
  stable/openvpn/Chart.yaml
  stable/openvpn/templates/openvpn-service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5123 Update mysql image documentation
  stable/mysql/Chart.yaml
  stable/mysql/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3466 [incubator/drone] Support secret environment variables in drone server
  incubator/drone/Chart.yaml
  incubator/drone/README.md
  incubator/drone/templates/NOTES.txt
  incubator/drone/templates/deployment-agent.yaml
  incubator/drone/templates/deployment-server.yaml
  incubator/drone/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5405 [stable/kibana] Add fullnameOverride
  stable/kibana/Chart.yaml
  stable/kibana/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/S

#5228 fix typo in jenkins README
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5211 [stable/grafana] Allows alternate scheduler for grafana deployment
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/deployment.yaml
  stable/grafana/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5261 Use configuration options to bind to all interfaces
  stable/hadoop/Chart.yaml
  stable/hadoop/templates/hadoop-configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5302 consul-improvements - ability to reuse gossip-key
  stable/consul/Chart.yaml
  stable/consul/templates/consul-statefulset.yaml
  stable/consul/templates/gossip-secret.yaml
  stable/consul/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5212 [stable/prometheus] Allows alternate scheduler for Prometheus server + alertmanager
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/alertmanager-deployment.yaml
  stable/prometheus/templates/server-deployment.yaml
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5396 [stable/memcached]Typo fix:AnitAffinity->AntiAffinity
  stable/memcached/Chart.yaml
  stable/memcached/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5318 [stable/prometheus] Forcing a new line to be created in the configmap yaml generation
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/server-configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5404 [stable/openvpn] Add option to remove `dhcp-option DOMAIN`
  stable/openvpn/Chart.yaml
  stable/openvpn/README.md
  stable/openvpn/templates/config-openvpn.yaml
  stable/openvpn/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5269 [elastalert] Add flag to use_ssl when connecting to elasticsearch
  stable/elastalert/Chart.yaml
  stable/elastalert/README.md
  stable/elastalert/templates/config.yaml
  stable/elastalert/templates/deployment.yaml
  stable/elastalert/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5420 [stable/fluent-bit] Typo fix: deamon set->daemonset
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5421 [incubator/fluentd-elasticsearch] typo fix: deamon set->daemonset
  incubator/fluentd-elasticsearch/Chart.yaml
  incubator/fluentd-elasticsearch/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5371 [stable/kube-lego] Update link to migration guide
  stable/kube-lego/Chart.yaml
  stable/kube-lego/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5400 [stable/kubernetes-dashboard] typo fix custer->cluster
  stable/kubernetes-dashboard/Chart.yaml
  stable/kubernetes-dashboard/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5343 docker-registry path override
  stable/docker-registry/Chart.yaml
  stable/docker-registry/templates/ingress.yaml
  stable/docker-registry/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5446 [stable/chronograf] typo fix: persitent->persistent
  stable/chronograf/Chart.yaml
  stable/chronograf/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5465 Update owners
  stable/traefik/Chart.yaml
  stable/traefik/OWNERS
  stable/traefik/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#5397 [stable/hadoop] typo fix: anitAffinity->antiAffinity
  stable/hadoop/Chart.yaml
  stable/hadoop/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5299 [stable/grafana] Add custom labels on grafana ingress
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/ingress.yaml
  stable/grafana/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5444 [stable/percona] typo fix: persitent->persistent
  stable/percona/Chart.yaml
  stable/percona/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5443 [stable/mssql-linux] typo fix: randonmized->randomized
  stable/mssql-linux/Chart.yaml
  stable/mssql-linux/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5402 [stable/openvpn] README scripts reflect new labels
  stable/openvpn/Chart.yaml
  stable/openvpn/README.md
  stable/openvpn/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm, size/M

#5440 Fix issue #5438
  incubator/couchdb/Chart.yaml
  incubator/couchdb/templates/statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5445 [stable/percona-xtradb-cluster] typo fix persitent->persistent
  stable/percona-xtradb-cluster/Chart.yaml
  stable/percona-xtradb-cluster/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5450 [stable/grafana] Fix readme storageClass/storageClassName description
  stable/grafana/Chart.yaml
  stable/grafana/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5447 [stable/postgresql] typo fix: persitent->persistent
  stable/postgresql/Chart.yaml
  stable/postgresql/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3457 [incubator/jaeger] Adds ability to utilize a cloud providers firewall for services
  incubator/jaeger/Chart.yaml
  incubator/jaeger/README.md
  incubator/jaeger/templates/_helpers.tpl
  incubator/jaeger/templates/agent-svc.yaml
  incubator/jaeger/templates/collector-svc.yaml
  incubator/jaeger/templates/hotrod-svc.yaml
  incubator/jaeger/templates/query-svc.yaml
  incubator/jaeger/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5028 [incubator/drone] Allows alternate drone schedulers
  incubator/drone/Chart.yaml
  incubator/drone/README.md
  incubator/drone/templates/deployment-agent.yaml
  incubator/drone/templates/deployment-server.yaml
  incubator/drone/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5454 [stable/grafana] add Grafana SMTP credentials
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/deployment.yaml
  stable/grafana/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5470 [stable/rabbitmq] Updating readme to match new default for rbac
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5478 change from using PVC to PVCtemplates for better availbility
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/pvc.yaml
  stable/rabbitmq/templates/statefulset.yaml
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5430 Whitespace issue in prometheus/server-configmap.yaml in issues 5425
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/server-configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5471 [stable/redis] Readme.md usage correction.
  stable/redis/Chart.yaml
  stable/redis/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5352 [incubator/schema-registry] cleaning up after myself (README, ununsed code)
  incubator/schema-registry/Chart.yaml
  incubator/schema-registry/README.md
  incubator/schema-registry/requirements.lock
  incubator/schema-registry/requirements.yaml
  incubator/schema-registry/templates/_helpers.tpl
  incubator/schema-registry/templates/deployment.yaml
  incubator/schema-registry/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5407 [stable/postgresql] PostgreSQL metrics need the right username
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5413 [stable/postgresql] Add Existing secret
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/NOTES.txt
  stable/postgresql/templates/_helpers.tpl
  stable/postgresql/templates/configmap.yaml
  stable/postgresql/templates/deployment.yaml
  stable/postgresql/templates/secrets.yaml
  stable/postgresql/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5461 Add "agent.useHostNetwork" and "agent.dnsPolicy" value to chart.
  incubator/jaeger/Chart.yaml
  incubator/jaeger/README.md
  incubator/jaeger/templates/agent-ds.yaml
  incubator/jaeger/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5428 Issue_5426: Add default antiAffinity example to Kafka
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
  incubator/kafka/templates/NOTES.txt
  incubator/kafka/templates/jmx-configmap.yaml
  incubator/kafka/templates/kafka-exporter.yaml
  incubator/kafka/templates/service-brokers-external.yaml
  incubator/kafka/templates/service-brokers.yaml
  incubator/kafka/templates/service-headless.yaml
  incubator/kafka/templates/servicemonitors.yaml
  incubator/kafka/templates/statefulset.yaml
  incubator/kafka/templates/tests/test_topic_create_consume_produce.yaml
  incubator/kafka/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5498 Fix formatting in drone README
  incubator/drone/Chart.yaml
  incubator/drone/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5336 [incubator/schema-registry] typo fix: zookeper->zookeeper
  incubator/schema-registry/Chart.yaml
  incubator/schema-registry/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5474 Add initial inbucket chart
  stable/inbucket/.helmignore
  stable/inbucket/Chart.yaml
  stable/inbucket/README.md
  stable/inbucket/templates/NOTES.txt
  stable/inbucket/templates/_helpers.tpl
  stable/inbucket/templates/deployment.yaml
  stable/inbucket/templates/ingress.yaml
  stable/inbucket/templates/service.yaml
  stable/inbucket/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5398 [stable/fluent-bit] Update fluent-bit to 0.13.0. Add section for parsers
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/config.yaml
  stable/fluent-bit/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5486 fix gogs service ssh targetPort
  incubator/gogs/Chart.yaml
  incubator/gogs/templates/deployment.yaml
  incubator/gogs/templates/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5497 [stable/consul] Fix service name declaration in the ingress template when using nameOverride (resubmit)
  stable/consul/Chart.yaml
  stable/consul/templates/consul-ingress.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5073 Add support for an optional local consul agent
  incubator/vault/Chart.yaml
  incubator/vault/README.md
  incubator/vault/templates/deployment.yaml
  incubator/vault/templates/tests/test-vault-status.yaml
  incubator/vault/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5091 [stable/kube2iam] Support extra container environment variables
  stable/kube2iam/Chart.yaml
  stable/kube2iam/README.md
  stable/kube2iam/templates/daemonset.yaml
  stable/kube2iam/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5304 Vault tls security - improve tls security and lifecycle hook example
  incubator/vault/Chart.yaml
  incubator/vault/templates/deployment.yaml
  incubator/vault/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5496 fix indent
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5508 [stable/mongodb] adding Release name as selector
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/deployment.yaml
  stable/mongodb/templates/svc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5258 Version 0.1.0 of the Schema-Registry-UI
  stable/schema-registry-ui/.helmignore
  stable/schema-registry-ui/Chart.yaml
  stable/schema-registry-ui/OWNERS
  stable/schema-registry-ui/README.md
  stable/schema-registry-ui/templates/NOTES.txt
  stable/schema-registry-ui/templates/_helpers.tpl
  stable/schema-registry-ui/templates/deployment.yaml
  stable/schema-registry-ui/templates/ingress.yaml
  stable/schema-registry-ui/templates/service.yaml
  stable/schema-registry-ui/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5502 Fix typo in readme.md
  incubator/vault/Chart.yaml
  incubator/vault/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5393 [stable/grafana] Allow overriding deployment strategy
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/deployment.yaml
  stable/grafana/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5495 [stable/redis] Add service for redis exporter
  stable/redis/Chart.yaml
  stable/redis/templates/metrics-svc.yaml
  stable/redis/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5048 [stable/mysql] support imagePullSecrets
  stable/mysql/Chart.yaml
  stable/mysql/README.md
  stable/mysql/templates/deployment.yaml
  stable/mysql/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4419 [stable/influxdb] Add service variables to influx
  stable/influxdb/Chart.yaml
  stable/influxdb/templates/service.yaml
  stable/influxdb/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5074 concourse: Add annotations for web deployment
  stable/concourse/Chart.yaml
  stable/concourse/README.md
  stable/concourse/templates/web-deployment.yaml
  stable/concourse/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5173 [stable/openvpn] Custom annotations for service
  stable/openvpn/Chart.yaml
  stable/openvpn/templates/openvpn-service.yaml
  stable/openvpn/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5051 switches the service ports for mqtt and stomp
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/templates/service-discovery.yaml
  stable/rabbitmq-ha/templates/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5138 [stable/external-dns] Add option to set registry
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/deployment.yaml
  stable/external-dns/templates/service.yaml
  stable/external-dns/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4364 typo:fix tables to table
  stable/weave-cloud/Chart.yaml
  stable/weave-cloud/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5213 [stable/openebs] fix openebs install typo
  stable/openebs/Chart.yaml
  stable/openebs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5475 Adds a newline between notes
  stable/redis/Chart.yaml
  stable/redis/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5506 [stable/msoms] support custom tolerations
  stable/msoms/Chart.yaml
  stable/msoms/templates/omsagent-daemonset.yaml
  stable/msoms/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5518 fix for issues in clustering and persistence
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/statefulset.yaml
  stable/rabbitmq/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5334 Recreation of #5326 for conflicts with other PR
  stable/artifactory/Chart.yaml
  stable/artifactory/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5165 [mssql-linux] Added feature to enable HADR
  stable/mssql-linux/Chart.yaml
  stable/mssql-linux/README.md
  stable/mssql-linux/templates/deployment.yaml
  stable/mssql-linux/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5524 [stable/redis] Fix readme for master service type
  stable/redis/Chart.yaml
  stable/redis/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5435 Adds 'envFromSecret' to grafana chart
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/deployment.yaml
  stable/grafana/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5526 [stable/buildkite] typo fix: [want to xxtra env] -> [want extra env]
  stable/buildkite/Chart.yaml
  stable/buildkite/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5528 [stable/concourse] fix failed links in README.md
  stable/concourse/Chart.yaml
  stable/concourse/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5527 [stable/cluster-autoscaler] fix the failed links in README.md
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5203 Feature/add extra labels and annotations locust
  stable/locust/Chart.yaml
  stable/locust/README.md
  stable/locust/templates/master-svc.yaml
  stable/locust/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5529 stable/prometheus: restore headless svcs, reverting breaking change to the default values
  stable/prometheus/Chart.yaml
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4829 [prometheus] kube-state-metrics v1.3.1
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/kube-state-metrics-clusterrole.yaml
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5561 [stable/sonatype-nexus] Nexus update version to 3.11.0
  stable/sonatype-nexus/Chart.yaml
  stable/sonatype-nexus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5570 [stable/prometheus] Ability to enable admin API
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/server-deployment.yaml
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5564 [stable/sonatype-nexus] Modify ingress rules to allow paths other than /
  stable/sonatype-nexus/Chart.yaml
  stable/sonatype-nexus/README.md
  stable/sonatype-nexus/templates/ingress.yaml
  stable/sonatype-nexus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5386 [stable/grafana]: add RBAC
  stable/grafana/Chart.yaml
  stable/grafana/templates/_helpers.tpl
  stable/grafana/templates/deployment.yaml
  stable/grafana/templates/podsecuritypolicy.yaml
  stable/grafana/templates/role.yaml
  stable/grafana/templates/rolebinding.yaml
  stable/grafana/templates/serviceaccount.yaml
  stable/grafana/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5139 fix typo in README of spinnaker
  stable/spinnaker/Chart.yaml
  stable/spinnaker/config/spinnaker.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5487 Allowing override for all fluentd config files
  incubator/fluentd-elasticsearch/Chart.yaml
  incubator/fluentd-elasticsearch/README.md
  incubator/fluentd-elasticsearch/templates/configmap.yaml
  incubator/fluentd-elasticsearch/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#5532 [stable/consul] Rework affinity settings
  stable/consul/Chart.yaml
  stable/consul/README.md
  stable/consul/templates/consul-statefulset.yaml
  stable/consul/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5311 Added prometheus-rabbitmq-exporter helm chart
  stable/prometheus-rabbitmq-exporter/.helmignore
  stable/prometheus-rabbitmq-exporter/Chart.yaml
  stable/prometheus-rabbitmq-exporter/README.md
  stable/prometheus-rabbitmq-exporter/templates/NOTES.txt
  stable/prometheus-rabbitmq-exporter/templates/_helpers.tpl
  stable/prometheus-rabbitmq-exporter/templates/deployment.yaml
  stable/prometheus-rabbitmq-exporter/templates/service.yaml
  stable/prometheus-rabbitmq-exporter/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L
