Repository helm/charts, pull requests merged in 2018-09, with the labels that each got.

#7481 [stable/nfs-client-provisioner] Rename podSecurityPolicy support
  stable/nfs-client-provisioner/Chart.yaml
  stable/nfs-client-provisioner/README.md
  stable/nfs-client-provisioner/ci/test-values.yaml
  stable/nfs-client-provisioner/templates/clusterrole.yaml
  stable/nfs-client-provisioner/templates/podsecuritypolicy.yaml
  stable/nfs-client-provisioner/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7429 suport wildcard certificates
  stable/grafana/Chart.yaml
  stable/grafana/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm

#7167 [stable/jenkins] add custom jenkins labels to the build agent
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/config.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#6325 [stable/postgresql] Add pg_hba.conf option.
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/configmap.yaml
  stable/postgresql/templates/deployment.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm, size/M

#7482 adding additional env variable for redis-exporter
  stable/prometheus-redis-exporter/Chart.yaml
  stable/prometheus-redis-exporter/README.md
  stable/prometheus-redis-exporter/templates/deployment.yaml
  stable/prometheus-redis-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7283 [stable/postgresql] Allow to keep PVC after 'helm delete'
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/pvc.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#7287 [stable/mongodb-replicaset]: fix syntax error for metrics.resources
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/templates/mongodb-statefulset.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#7495 [stable/datadog] Set dnsPolicy for using hostNetwork
  stable/datadog/Chart.yaml
  stable/datadog/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm

#7497 fix conflict between mounting a file and mounting a folder
  stable/grafana/Chart.yaml
  stable/grafana/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm

#7463 [stable/rocketchat] Bring it back to the present
  stable/rocketchat/Chart.yaml
  stable/rocketchat/OWNERS
  stable/rocketchat/requirements.lock
  stable/rocketchat/requirements.yaml
  stable/rocketchat/templates/_helpers.tpl
  stable/rocketchat/templates/deployment.yaml
  stable/rocketchat/templates/serviceaccount.yaml
  stable/rocketchat/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7500 [stable/nfs-client-provisioner] Make clusterrole(binding) conditional on rbac.create
  stable/nfs-client-provisioner/Chart.yaml
  stable/nfs-client-provisioner/templates/clusterrole.yaml
  stable/nfs-client-provisioner/templates/clusterrolebinding.yaml
Labels: Contribution Allowed, approved, lgtm

#7499 [stable/metrics-server] upgrade metrics-server to v0.3.0
  stable/metrics-server/Chart.yaml
  stable/metrics-server/README.md
  stable/metrics-server/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7351 [stable/nginx-ingress] Fixes #7127 - conditionally define pdb
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-poddisruptionbudget.yaml
  stable/nginx-ingress/templates/default-backend-poddisruptionbudget.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#7262 [incubator/zookeeper]: incorrect terminationGracePeriodSeconds element
  incubator/zookeeper/Chart.yaml
  incubator/zookeeper/templates/statefulset.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#7501 [incubator/elasticsearch] Fix "config is not a table" helm warning + fix wrong cluster.env default value in README
  incubator/elasticsearch/Chart.yaml
  incubator/elasticsearch/README.md
  incubator/elasticsearch/templates/configmap.yaml
  incubator/elasticsearch/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7476 [stable/gocd] Removed extra char from role config instructions
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/README.md
Labels: Contribution Allowed, approved, lgtm

#6005 [stable/redis-ha] Add antiAffinity rules
  stable/redis-ha/Chart.yaml
  stable/redis-ha/README.md
  stable/redis-ha/templates/redis-sentinel-deployment.yaml
  stable/redis-ha/templates/redis-server-deployment.yaml
  stable/redis-ha/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm, size/M

#7512 Render .Values.extraVolumeMounts inside volumeMounts
  stable/fluentd-elasticsearch/Chart.yaml
  stable/fluentd-elasticsearch/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm

#6588 Update CouchDB to version 2.2.0
  incubator/couchdb/Chart.yaml
  incubator/couchdb/README.md
  incubator/couchdb/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm, size/XS

#7507 [stable/bookstack] Add chart for Bookstackapp
  stable/bookstack/.helmignore
  stable/bookstack/Chart.yaml
  stable/bookstack/OWNERS
  stable/bookstack/README.md
  stable/bookstack/requirements.lock
  stable/bookstack/requirements.yaml
  stable/bookstack/templates/NOTES.txt
  stable/bookstack/templates/_helpers.tpl
  stable/bookstack/templates/app-secrets.yaml
  stable/bookstack/templates/deployment.yaml
  stable/bookstack/templates/externaldb-secrets.yaml
  stable/bookstack/templates/ingress.yaml
  stable/bookstack/templates/podsecuritypolicy.yaml
  stable/bookstack/templates/role.yaml
  stable/bookstack/templates/rolebinding.yaml
  stable/bookstack/templates/service.yaml
  stable/bookstack/templates/serviceaccount.yaml
  stable/bookstack/templates/storage-pvc.yaml
  stable/bookstack/templates/uploads-pvc.yaml
  stable/bookstack/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7511 [incubator/elasticsearch] Fix "tolerations" default values {} -> [].
  incubator/elasticsearch/Chart.yaml
  incubator/elasticsearch/README.md
  incubator/elasticsearch/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7517 [stable/filebeat ] Fix policy in the template and default values not consistent
  stable/filebeat/Chart.yaml
  stable/filebeat/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm

#6239 Chart for Spark operator
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/README.md
  incubator/sparkoperator/templates/spark-operator-rbac.yaml
  incubator/sparkoperator/templates/spark-operator.yaml
  incubator/sparkoperator/templates/spark-rbac.yaml
  incubator/sparkoperator/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm, size/L

#7525 Bump up GoCD version
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/templates/configmap.yaml
  stable/gocd/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7327 [stable/datadog] Update README
  stable/datadog/Chart.yaml
  stable/datadog/README.md
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#7401 [stable/filebeat] Allow for additional initContainers
  stable/filebeat/Chart.yaml
  stable/filebeat/README.md
  stable/filebeat/templates/daemonset.yaml
  stable/filebeat/values.yaml
Labels: Contribution Allowed, approved, lgtm

#6810 [kube-state-metrics] review readme
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#7528 [stable/prometheus] upgrade kube-state-metrics
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7435 Fix clusterIP assignment
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/templates/service.yaml
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7519 Add StorageClass parameters
  stable/nfs-server-provisioner/Chart.yaml
  stable/nfs-server-provisioner/README.md
  stable/nfs-server-provisioner/templates/storageclass.yaml
  stable/nfs-server-provisioner/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7502 Add liveness and readiness probes to postgres_exporter
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm

#7533 [stable/kube-ops-view] use a stable tag
  stable/kube-ops-view/Chart.yaml
  stable/kube-ops-view/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7515 [stable/kube-state-metrics] upgrade kube-state-metrics to v1.4.0
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
  stable/kube-state-metrics/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7510 [stable/rabbitmq] Add additional liveness/readiness probe parameters
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/statefulset.yaml
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7538 [fluent-bit]: changed capability detection
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm

#7532 [incubator/kafka] Fix doc typo
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
Labels: Contribution Allowed, approved, lgtm

#7543 [stable/mongodb] Add 'mongodbEnableIPv6' configuration to standalone …
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/deployment-standalone.yaml
Labels: Contribution Allowed, approved, lgtm

#7526 [stable/kibana] better health check in dashboard import init container
  stable/kibana/Chart.yaml
  stable/kibana/templates/configmap-dashboardimport.yaml
Labels: Contribution Allowed, approved, lgtm

#7418 [stable/oauth2-proxy] Add email authentication file support
  stable/oauth2-proxy/Chart.yaml
  stable/oauth2-proxy/README.md
  stable/oauth2-proxy/templates/configmap-authenticated-emails-file.yaml
  stable/oauth2-proxy/templates/deployment.yaml
  stable/oauth2-proxy/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7437 [stable/grafana] Fix deployment strategy when changing from rollingUpdate
  stable/grafana/Chart.yaml
  stable/grafana/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm

#7546 [stable/mongodb] Fix issue starting mongodb replica with persisted data
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/statefulset-arbiter-rs.yaml
  stable/mongodb/templates/statefulset-primary-rs.yaml
  stable/mongodb/templates/statefulset-secondary-rs.yaml
Labels: Contribution Allowed, approved, lgtm

#7316 Updating image from 1.4 to 1.6
  stable/influxdb/Chart.yaml
  stable/influxdb/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: no, lgtm

#7527 [stable/filebeat] Allow for additional operator overrides
  stable/filebeat/Chart.yaml
  stable/filebeat/README.md
  stable/filebeat/templates/daemonset.yaml
  stable/filebeat/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7529 [stable/grafana] grafana secret mount permissions
  stable/grafana/Chart.yaml
  stable/grafana/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm

#7450 Allow replacement of Jenkins config with configMap.
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/config.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7561 [incubator/spring-cloud-data-flow] Update to new SCDF version 1.6.2
  incubator/spring-cloud-data-flow/Chart.yaml
  incubator/spring-cloud-data-flow/README.md
  incubator/spring-cloud-data-flow/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7560 [stable/nginx-ingress] add default values for autoscaler
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7562 [Documentation] Add HPA best practices to review guidelines.
  REVIEW_GUIDELINES.md
Labels: Contribution Allowed, approved, lgtm

#7559 Replace CLA by DCO in review guidelines
  REVIEW_GUIDELINES.md
Labels: Contribution Allowed, approved, lgtm

#7577 [incubator/vault] Upgrade to 0.11.0.
  incubator/vault/Chart.yaml
  incubator/vault/README.md
  incubator/vault/values.yaml
Labels: Contribution Allowed, approved, lgtm

#6936 Fix for kafkaTrigger configuration
  incubator/kubeless/Chart.yaml
  incubator/kubeless/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: no, lgtm

#7579 sentry: bump postgres and redis charts
  stable/sentry/Chart.yaml
  stable/sentry/requirements.lock
  stable/sentry/requirements.yaml
Labels: Contribution Allowed, approved, lgtm

#7420 [stable/dex] Fix default issuer for dex
  stable/dex/Chart.yaml
  stable/dex/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7582 Added functionality to let us join an already existing cluster.
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/README.md
  stable/cockroachdb/templates/cockroachdb-statefulset.yaml
  stable/cockroachdb/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7061 stable/concourse: use the correct work dir in the container preamble
  stable/concourse/Chart.yaml
  stable/concourse/templates/worker-statefulset.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#7588 adding missing documentation and readinessProbe
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/templates/deployment.yaml
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7590 [Documentation] Example ingress for best practices
  REVIEW_GUIDELINES.md
Labels: Contribution Allowed, approved, lgtm

#7479 Fix spark zeppelin storageclass
  stable/spark/Chart.yaml
  stable/spark/README.md
  stable/spark/templates/_helpers.tpl
  stable/spark/templates/spark-zeppelin-deployment.yaml
  stable/spark/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7602 [incubator/vault] Added option for VAULT_LOG_LEVEL.
  incubator/vault/Chart.yaml
  incubator/vault/templates/deployment.yaml
  incubator/vault/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7601 [incubator/elasticsearch] Add myself to OWNERS file for elasticsearch
  incubator/elasticsearch/Chart.yaml
  incubator/elasticsearch/OWNERS
Labels: Contribution Allowed, approved, lgtm

#7246 [hlf-couchdb] Update Owners + bug fixes and best-practices
  stable/hlf-couchdb/.helmignore
  stable/hlf-couchdb/Chart.yaml
  stable/hlf-couchdb/OWNERS
  stable/hlf-couchdb/README.md
  stable/hlf-couchdb/templates/pvc.yaml
  stable/hlf-couchdb/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#7242 [hlf-ca] Update Owners + bug fixes and best-practices
  stable/hlf-ca/.helmignore
  stable/hlf-ca/Chart.yaml
  stable/hlf-ca/OWNERS
  stable/hlf-ca/README.md
  stable/hlf-ca/templates/configmap--config.yaml
  stable/hlf-ca/templates/configmap--db.yaml
  stable/hlf-ca/templates/deployment.yaml
  stable/hlf-ca/templates/pvc.yaml
  stable/hlf-ca/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#7243 [hlf-ord] Update Owners + bug fixes and best-practices
  stable/hlf-ord/.helmignore
  stable/hlf-ord/Chart.yaml
  stable/hlf-ord/OWNERS
  stable/hlf-ord/README.md
  stable/hlf-ord/templates/configmap--ord.yaml
  stable/hlf-ord/templates/deployment.yaml
  stable/hlf-ord/templates/pvc.yaml
  stable/hlf-ord/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#7597 Feature kafka pod annotations
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
  incubator/kafka/templates/statefulset.yaml
  incubator/kafka/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7610 [stable/drone] Upgrade to 0.8.6.
  stable/drone/Chart.yaml
  stable/drone/README.md
  stable/drone/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7611 [stable/grafana] Upgrade grafana to 5.2.4
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7598 add read/liveness probes to the stateful set and test case
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/ci/distributed-values.yaml
  stable/minio/templates/deployment.yaml
  stable/minio/templates/statefulset.yaml
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7237 Use IP address instead of hostname
  incubator/schema-registry/Chart.yaml
  incubator/schema-registry/templates/deployment.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#7612 Set DISCOVERY_SERVICE to use local DNS instead of fully qualified DNS
  incubator/elasticsearch/Chart.yaml
  incubator/elasticsearch/README.md
  incubator/elasticsearch/templates/client-deployment.yaml
  incubator/elasticsearch/templates/data-statefulset.yaml
  incubator/elasticsearch/templates/master-statefulset.yaml
  incubator/elasticsearch/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7613 [stable/metrics-server] Use custom service account name in created ServiceAccount resource
  stable/metrics-server/Chart.yaml
  stable/metrics-server/templates/metrics-server-serviceaccount.yaml
Labels: Contribution Allowed, approved, lgtm

#7615 [stable/external-dns] upgrade external-dns image
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7555 Create a check to test whether --repositories is needed
  stable/spinnaker/Chart.yaml
  stable/spinnaker/templates/configmap/halyard-config.yaml
Labels: Contribution Allowed, approved, lgtm

#7618 [stable/metrics-server] Fix service account references in role bindings
  stable/metrics-server/Chart.yaml
  stable/metrics-server/templates/auth-delegator-crb.yaml
  stable/metrics-server/templates/metrics-server-crb.yaml
  stable/metrics-server/templates/role-binding.yaml
Labels: Contribution Allowed, approved, lgtm

#6354 [incubator/mysqlha] fix the creation of the replication user
  incubator/mysqlha/Chart.yaml
  incubator/mysqlha/templates/configmap.yaml
  incubator/mysqlha/templates/statefulset.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm, size/L

#7593 OpenLDAP Read Only LDIF ConfigMap Fix
  stable/openldap/Chart.yaml
  stable/openldap/templates/configmap-customldif.yaml
  stable/openldap/templates/deployment.yaml
  stable/openldap/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7607 [stable/mongodb] Fix podAnnotations
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/deployment-standalone.yaml
  stable/mongodb/templates/statefulset-arbiter-rs.yaml
  stable/mongodb/templates/statefulset-primary-rs.yaml
  stable/mongodb/templates/statefulset-secondary-rs.yaml
Labels: Contribution Allowed, approved, lgtm

#7586 [stable/prometheus-adapter] Fixing warning when overriding rules.custom
  stable/prometheus-adapter/Chart.yaml
  stable/prometheus-adapter/README.md
  stable/prometheus-adapter/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7614 Update link to GitLab Helm chart documentation
  stable/gitlab-ce/Chart.yaml
  stable/gitlab-ce/README.md
  stable/gitlab-ce/requirements.lock
  stable/gitlab-ce/values.yaml
  stable/gitlab-ee/Chart.yaml
  stable/gitlab-ee/README.md
  stable/gitlab-ee/requirements.lock
  stable/gitlab-ee/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7619 [stable/redis] Rollout new pods on configuration changes
  stable/redis/Chart.yaml
  stable/redis/templates/configmap.yaml
  stable/redis/templates/redis-master-statefulset.yaml
  stable/redis/templates/redis-slave-deployment.yaml
  stable/redis/templates/secret.yaml
  stable/redis/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7604 [stable/nfs-server-provisioner]: add reclaim policy support
  stable/nfs-server-provisioner/Chart.yaml
  stable/nfs-server-provisioner/README.md
  stable/nfs-server-provisioner/templates/storageclass.yaml
  stable/nfs-server-provisioner/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7621 [stable/heapster] upgrade heapster to v1.5.2
  stable/heapster/Chart.yaml
  stable/heapster/README.md
  stable/heapster/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7535 [stable/mariadb] Feature/allow for existing pvc
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
  stable/mariadb/templates/master-statefulset.yaml
  stable/mariadb/values-production.yaml
  stable/mariadb/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7622 [stable/redis] Fail health probes when authentication fails
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/templates/_helpers.tpl
  stable/redis/templates/health-configmap.yaml
  stable/redis/templates/metrics-deployment.yaml
  stable/redis/templates/redis-master-statefulset.yaml
  stable/redis/templates/redis-master-svc.yaml
  stable/redis/templates/redis-slave-deployment.yaml
  stable/redis/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7126 update helm chart to use inbucket version 2.0.0
  stable/inbucket/Chart.yaml
  stable/inbucket/README.md
  stable/inbucket/templates/NOTES.txt
  stable/inbucket/templates/configmap.yaml
  stable/inbucket/templates/deployment.yaml
  stable/inbucket/templates/service.yaml
  stable/inbucket/templates/tests/inbucket-config-test.yaml
  stable/inbucket/templates/tests/inbucket-test.yaml
  stable/inbucket/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#7655 [stable/mongodb] - Add ability to specify kubernetes cluster domain
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/statefulset-arbiter-rs.yaml
  stable/mongodb/templates/statefulset-primary-rs.yaml
  stable/mongodb/templates/statefulset-secondary-rs.yaml
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7321 stable/metallb: update to MetalLB 0.7.3.
  stable/metallb/Chart.yaml
  stable/metallb/templates/rbac.yaml
  stable/metallb/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#7661 Bump up GoCD app version to 18.9.0
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
Labels: Contribution Allowed, approved, lgtm

#7536 [stable/openiban] Add OpenIBAN chart
  stable/openiban/.helmignore
  stable/openiban/Chart.yaml
  stable/openiban/OWNERS
  stable/openiban/README.md
  stable/openiban/templates/NOTES.txt
  stable/openiban/templates/_helpers.tpl
  stable/openiban/templates/deployment.yaml
  stable/openiban/templates/ingress.yaml
  stable/openiban/templates/role.yaml
  stable/openiban/templates/rolebinding.yaml
  stable/openiban/templates/service.yaml
  stable/openiban/templates/serviceaccount.yaml
  stable/openiban/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7627 Deprecate JFrog charts (moved to https://github.com/jfrog/charts)
  stable/artifactory-ha/Chart.yaml
  stable/artifactory-ha/README.md
  stable/artifactory-ha/templates/NOTES.txt
  stable/artifactory/Chart.yaml
  stable/artifactory/README.md
  stable/artifactory/templates/NOTES.txt
  stable/distribution/Chart.yaml
  stable/distribution/README.md
  stable/distribution/templates/NOTES.txt
  stable/mission-control/Chart.yaml
  stable/mission-control/README.md
  stable/mission-control/templates/NOTES.txt
  stable/xray/Chart.yaml
  stable/xray/README.md
  stable/xray/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm

#7629 [stable/elastalert] Add support to custom SSL certificates
  stable/elastalert/Chart.yaml
  stable/elastalert/README.md
  stable/elastalert/templates/config.yaml
  stable/elastalert/templates/deployment.yaml
  stable/elastalert/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7630 Update image
  stable/prometheus-redis-exporter/Chart.yaml
  stable/prometheus-redis-exporter/README.md
  stable/prometheus-redis-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7634 [stable/falco] Make use of shm volume
  stable/falco/CHANGELOG.md
  stable/falco/Chart.yaml
  stable/falco/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm

#7645 [stable/docker-registry] Add securitycontext to satisfy podsecuritypolicy
  stable/docker-registry/Chart.yaml
  stable/docker-registry/templates/NOTES.txt
  stable/docker-registry/templates/deployment.yaml
  stable/docker-registry/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7646 [stable/chartmuseum] Make port-forward hint in NOTES.txt namespace-aware
  stable/chartmuseum/Chart.yaml
  stable/chartmuseum/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm

#7648 Remove gocd chart from incubator (#4124)
  incubator/gocd/.helmignore
  incubator/gocd/Chart.yaml
  incubator/gocd/LICENSE
  incubator/gocd/README.md
  incubator/gocd/templates/NOTES.txt
  incubator/gocd/templates/_helpers.tpl
  incubator/gocd/templates/gocd-agent-deployment.yaml
  incubator/gocd/templates/gocd-agent-homego-pvc.yaml
  incubator/gocd/templates/gocd-ea-cluster-role-binding.yaml
  incubator/gocd/templates/gocd-ea-cluster-role.yaml
  incubator/gocd/templates/gocd-ea-service-account.yaml
  incubator/gocd/templates/gocd-server-deployment.yaml
  incubator/gocd/templates/gocd-server-pvc.yaml
  incubator/gocd/templates/ingress.yaml
  incubator/gocd/templates/service.yaml
  incubator/gocd/templates/test-config.yaml
  incubator/gocd/templates/tests/gocd-test.yaml
  incubator/gocd/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7663 [stable/prometheus] bump to prometheus v2.4.0
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7673 [CI] Use latest chart-testing image
  .circleci/config.yml
  test/Dockerfile
  test/build.sh
  test/e2e.sh
Labels: Contribution Allowed, approved, lgtm

#7678 [stable/datadog] Bump datadog/agent and kube-state-metrics versions
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/requirements.lock
  stable/datadog/requirements.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7665 [stable/elastalert] support basic auth, more retry control, scheduling options
  stable/elastalert/Chart.yaml
  stable/elastalert/README.md
  stable/elastalert/templates/config.yaml
  stable/elastalert/templates/deployment.yaml
  stable/elastalert/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7664 Support tolerations
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/deployment-standalone.yaml
Labels: Contribution Allowed, approved, lgtm

#7638 [stable/gocd] Add agent.env.extraEnvVars
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/README.md
  stable/gocd/templates/gocd-agent-deployment.yaml
  stable/gocd/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7693 [incubator/kafka] SSL support - Disable env from secret when secret is mounted
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
  incubator/kafka/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm

#7685 [stable/verdaccio] Install latest version
  stable/verdaccio/Chart.yaml
  stable/verdaccio/README.md
  stable/verdaccio/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7625 [stable/mysqldump] fix to the correct name to install the chart and set the chart version to 1.0.0
  stable/mysqldump/Chart.yaml
  stable/mysqldump/README.md
Labels: Contribution Allowed, approved, lgtm

#7695 Adds support for nodeSelectors
  stable/memcached/Chart.yaml
  stable/memcached/templates/statefulset.yaml
  stable/memcached/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7711 Fix statefulset / use the correct endpoint for probes and update minio
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/templates/deployment.yaml
  stable/minio/templates/service.yaml
  stable/minio/templates/statefulset.yaml
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7701 [stable/datadog] allow configmaps to use templates
  stable/datadog/Chart.yaml
  stable/datadog/templates/checksd-configmap.yaml
  stable/datadog/templates/confd-configmap.yaml
  stable/datadog/templates/daemonset.yaml
  stable/datadog/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm

#7644 cert-manager: fast-forward to upstream 3945595b
  stable/cert-manager/Chart.yaml
  stable/cert-manager/README.md
  stable/cert-manager/requirements.lock
  stable/cert-manager/requirements.yaml
  stable/cert-manager/templates/00-namespace.yaml
  stable/cert-manager/templates/certificate-crd.yaml
  stable/cert-manager/templates/clusterissuer-crd.yaml
  stable/cert-manager/templates/deployment.yaml
  stable/cert-manager/templates/issuer-crd.yaml
  stable/cert-manager/templates/rbac.yaml
  stable/cert-manager/values.yaml
  stable/cert-manager/webhook/.helmignore
  stable/cert-manager/webhook/Chart.yaml
  stable/cert-manager/webhook/templates/NOTES.txt
  stable/cert-manager/webhook/templates/_helpers.tpl
  stable/cert-manager/webhook/templates/apiservice.yaml
  stable/cert-manager/webhook/templates/ca-sync.yaml
  stable/cert-manager/webhook/templates/deployment.yaml
  stable/cert-manager/webhook/templates/pki.yaml
  stable/cert-manager/webhook/templates/rbac.yaml
  stable/cert-manager/webhook/templates/service.yaml
  stable/cert-manager/webhook/templates/serviceaccount.yaml
  stable/cert-manager/webhook/templates/validating-webhook.yaml
  stable/cert-manager/webhook/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7714 [stable/grafana] Update documentation to be consistent with the values.yaml file
  stable/grafana/Chart.yaml
  stable/grafana/README.md
Labels: Contribution Allowed, approved, lgtm

#7676 [stable/filebeat] raised filebeat version to 6.4.0
  stable/filebeat/Chart.yaml
  stable/filebeat/README.md
  stable/filebeat/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7681 [stable/prometheus-cloudwatch-exporter] health/liveness endpoints added
  stable/prometheus-cloudwatch-exporter/Chart.yaml
  stable/prometheus-cloudwatch-exporter/README.md
  stable/prometheus-cloudwatch-exporter/templates/deployment.yaml
  stable/prometheus-cloudwatch-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7725 [stable/elastalert] only conditionally include certs
  stable/elastalert/Chart.yaml
  stable/elastalert/templates/config.yaml
  stable/elastalert/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7570 [stable/rabbitmq-ha] Added ability to add extra podAnnotations
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/templates/statefulset.yaml
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7150 [incubator/elasticsearch] Add updateStrategy for master and data statefulsets
  incubator/elasticsearch/Chart.yaml
  incubator/elasticsearch/templates/data-statefulset.yaml
  incubator/elasticsearch/templates/master-statefulset.yaml
  incubator/elasticsearch/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#7733 [stable/dmarc2logstash] upgrade image to prevent crashloop on bad dmarc report; upgrade filebeat
  stable/dmarc2logstash/Chart.yaml
  stable/dmarc2logstash/README.md
  stable/dmarc2logstash/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7716 [stable/drone] Added Drone health and metrics endpoints
  stable/drone/Chart.yaml
  stable/drone/README.md
  stable/drone/templates/deployment-agent.yaml
  stable/drone/templates/deployment-server.yaml
  stable/drone/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7448 [stable/home-assistant] OWNERS and convert configurator to sidecar
  stable/home-assistant/.helmignore
  stable/home-assistant/Chart.yaml
  stable/home-assistant/OWNERS
  stable/home-assistant/templates/configurator-deployment.yaml
  stable/home-assistant/templates/configurator-ingress.yaml
  stable/home-assistant/templates/configurator-svc.yaml
  stable/home-assistant/templates/deployment.yaml
  stable/home-assistant/templates/ingress.yaml
  stable/home-assistant/templates/pvc.yaml
  stable/home-assistant/templates/secret.yaml
  stable/home-assistant/templates/service.yaml
  stable/home-assistant/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7749 [stable/graphite] Upgrading Graphite version to 1.1.4
  stable/graphite/Chart.yaml
  stable/graphite/README.md
  stable/graphite/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7040 [stable/grafana] Set plugins as a list
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/configmap.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#7760 [stable/graphite] Upgrading Graphite version to 1.1.4-3
  stable/graphite/Chart.yaml
  stable/graphite/README.md
  stable/graphite/values.yaml
Labels: Contribution Allowed, approved, lgtm

#5401 GoCD - Add extra volumes and volumeMounts options on server and agents
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/README.md
  stable/gocd/templates/gocd-agent-deployment.yaml
  stable/gocd/templates/gocd-server-deployment.yaml
  stable/gocd/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm, size/L

#7757 [incubator/kube-spot-termination-notice-handler] bump versions, etc
  incubator/kube-spot-termination-notice-handler/Chart.yaml
  incubator/kube-spot-termination-notice-handler/README.md
  incubator/kube-spot-termination-notice-handler/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7626 update kapacitor to the latest release and some fixes to match best practices
  stable/kapacitor/Chart.yaml
  stable/kapacitor/README.md
  stable/kapacitor/templates/deployment.yaml
  stable/kapacitor/templates/pvc.yaml
  stable/kapacitor/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7773 incubator/elasticsearch: Don't use `localhost` in hooks
  incubator/elasticsearch/Chart.yaml
  incubator/elasticsearch/templates/configmap.yaml
Labels: Contribution Allowed, approved, lgtm

#7779 Prometheus: Fix AlertManager discovery if chart name is not the default
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/server-configmap.yaml
Labels: Contribution Allowed, approved, lgtm

#7780 [stable/keycloak] Added ability to specify podAnnotations
  stable/keycloak/Chart.yaml
  stable/keycloak/README.md
  stable/keycloak/templates/statefulset.yaml
  stable/keycloak/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7743 Add env value to etcd
  incubator/etcd/Chart.yaml
  incubator/etcd/README.md
  incubator/etcd/templates/statefulset.yaml
  incubator/etcd/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7142 [stable/testlink]: support nodeSelectors
  stable/testlink/Chart.yaml
  stable/testlink/templates/deployment.yaml
  stable/testlink/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#7790 set kapacitor to 1.5.1
  stable/kapacitor/Chart.yaml
  stable/kapacitor/README.md
  stable/kapacitor/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7766 [stable/coredns] allow nodeselector configuration
  stable/coredns/Chart.yaml
  stable/coredns/templates/deployment.yaml
  stable/coredns/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7230 Kibana: support installation of plugins using initContainer
  stable/kibana/Chart.yaml
  stable/kibana/README.md
  stable/kibana/templates/deployment.yaml
  stable/kibana/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#7751 Adding dwardu89 to the owners and maintainers of the spinnaker chart
  stable/spinnaker/Chart.yaml
  stable/spinnaker/OWNERS
Labels: Contribution Allowed, approved, lgtm

#5987 [stable/mattemost-team-edition] Add initial charts for Mattermost Team Edition
  stable/mattermost-team-edition/.helmignore
  stable/mattermost-team-edition/Chart.yaml
  stable/mattermost-team-edition/OWNERS
  stable/mattermost-team-edition/README.md
  stable/mattermost-team-edition/ci/default-values.yaml
  stable/mattermost-team-edition/requirements.lock
  stable/mattermost-team-edition/requirements.yaml
  stable/mattermost-team-edition/templates/NOTES.txt
  stable/mattermost-team-edition/templates/_helpers.tpl
  stable/mattermost-team-edition/templates/config.tpl
  stable/mattermost-team-edition/templates/configmap-config.yaml
  stable/mattermost-team-edition/templates/deployment.yaml
  stable/mattermost-team-edition/templates/ingress.yaml
  stable/mattermost-team-edition/templates/pvc.yaml
  stable/mattermost-team-edition/templates/service.yaml
  stable/mattermost-team-edition/templates/tests/mattermost-config-test.yaml
  stable/mattermost-team-edition/templates/tests/mattermost-test.yaml
  stable/mattermost-team-edition/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm, size/XL

#7838 [stable/spinnaker] Changing email of dwardu89
  stable/spinnaker/Chart.yaml
Labels: Contribution Allowed, approved, lgtm

#7295 Fixed syntax error in prometheus-adapter
  stable/prometheus-adapter/Chart.yaml
  stable/prometheus-adapter/templates/custom-metrics-apiserver-service.yaml
  stable/prometheus-adapter/templates/secret.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#7623 [incubator/kafka]: add reassignPartitions to topic configuration
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
  incubator/kafka/templates/configmap-config.yaml
  incubator/kafka/values.yaml
Labels: Contribution Allowed, approved, lgtm

#7839 [stable/mongodb] Use .Values.existingSecret for standalone deployments
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/deployment-standalone.yaml
Labels: Contribution Allowed, approved, lgtm

#7831 [stable/wordpress] Fix chart not being upgradable
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
  stable/wordpress/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm

#7830 [stable/phpmyadmin] Fix chart not being upgradable
  stable/phpmyadmin/Chart.yaml
  stable/phpmyadmin/README.md
  stable/phpmyadmin/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm

#7816 [stable/suitecrm] Fix chart not being upgradable
  stable/suitecrm/Chart.yaml
  stable/suitecrm/README.md
  stable/suitecrm/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm

#7814 [stable/ghost] Fix chart not being upgradable
  stable/ghost/Chart.yaml
  stable/ghost/README.md
  stable/ghost/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm

#7820 [stable/phpbb] Fix chart not being upgradable
  stable/phpbb/Chart.yaml
  stable/phpbb/README.md
  stable/phpbb/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm

#7817 [stable/osclass] Fix chart not being upgradable
  stable/osclass/Chart.yaml
  stable/osclass/README.md
  stable/osclass/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm

#7818 [stable/jasperreports] Fix chart not being upgradable
  stable/jasperreports/Chart.yaml
  stable/jasperreports/README.md
  stable/jasperreports/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm

#7824 [stable/parse] Fix chart not being upgradable
  stable/parse/Chart.yaml
  stable/parse/README.md
  stable/parse/templates/dashboard-deployment.yaml
  stable/parse/templates/server-deployment.yaml
Labels: Contribution Allowed, approved, lgtm

#7825 [stable/drupal] Fix chart not being upgradable
  stable/drupal/Chart.yaml
  stable/drupal/README.md
  stable/drupal/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm

#7848 [stable/rabbitmq] Fix chart not being upgradable
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm

#7826 [stable/mediawiki] Fix chart not being upgradable
  stable/mediawiki/Chart.yaml
  stable/mediawiki/README.md
  stable/mediawiki/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm

#7852 [stable/mariadb] Fix chart not being upgradable
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
  stable/mariadb/templates/master-statefulset.yaml
  stable/mariadb/templates/slave-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm

#7856 [stable/orangehrm] Fix chart not being upgradable
  stable/orangehrm/Chart.yaml
  stable/orangehrm/README.md
  stable/orangehrm/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm
