Repository helm/charts, pull requests merged in 2018-08, with the labels that each got.

#6940 [stable/magento] - Update mariadb dependency version
  stable/magento/Chart.yaml
  stable/magento/requirements.lock
Labels: approved, cncf-cla: yes, lgtm

#6927 [stable/traefik] Add option for enabling Jaeger or Zipkin tracing
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/configmap.yaml
  stable/traefik/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6935 Schema Registry: Support TLS for Ingress
  incubator/schema-registry/Chart.yaml
  incubator/schema-registry/README.md
  incubator/schema-registry/templates/NOTES.txt
  incubator/schema-registry/templates/ingress.yaml
  incubator/schema-registry/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6846 [stable/traefik] Update API versions, add Kubernetes endpoint config
  stable/traefik/Chart.yaml
  stable/traefik/templates/configmap.yaml
  stable/traefik/templates/deployment.yaml
  stable/traefik/templates/rbac.yaml
  stable/traefik/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6933 [stable/traefik] fine control over accesslog fields
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/configmap.yaml
  stable/traefik/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6836 [rabbitmq] Set securityContext with correct user
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/statefulset.yaml
  stable/rabbitmq/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6946 [stable/rabbitmq] added securityContext
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/values-production.yaml
Labels: approved, cncf-cla: yes, lgtm

#6948 [stable/grafana] Add support for overriding securityContext
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/deployment.yaml
  stable/grafana/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6987 [stable/Jenkins] Add Master.AdminPassword in README
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
Labels: approved, cncf-cla: yes, lgtm

#6945 [stable/cerebro] made revisionHistoryLimit configurable
  stable/cerebro/Chart.yaml
  stable/cerebro/templates/deployment.yaml
  stable/cerebro/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6988 [stable/Jenkins] Update plugins version
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6983 [stable/mediawiki] set default value of `serviceExternalTrafficPolicy` to `Cluster`
  stable/mediawiki/Chart.yaml
  stable/mediawiki/README.md
  stable/mediawiki/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6995 [stable/joomla] set default value of `serviceExternalTrafficPolicy` to `Cluster`
  stable/joomla/Chart.yaml
  stable/joomla/README.md
  stable/joomla/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6982 [stable/odoo] set default value of `serviceExternalTrafficPolicy` to `Cluster`
  stable/odoo/Chart.yaml
  stable/odoo/README.md
  stable/odoo/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6996 [stable/suitecrm] exposes `externalTrafficPolicy` and `sessionAffinity` as chart params
  stable/suitecrm/Chart.yaml
  stable/suitecrm/README.md
  stable/suitecrm/templates/svc.yaml
  stable/suitecrm/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6980 [stable/prestashop] adds `externalTrafficPolicy` configurable chart parameter
  stable/prestashop/Chart.yaml
  stable/prestashop/README.md
  stable/prestashop/templates/svc.yaml
  stable/prestashop/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6963 Schema registry update kafka zk
  incubator/schema-registry/Chart.yaml
  incubator/schema-registry/README.md
  incubator/schema-registry/requirements.lock
  incubator/schema-registry/requirements.yaml
  incubator/schema-registry/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7030 [stable/rabbitmq] Improve notes to access deployed services
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#7028 [stable/phpmyadmin] Improve notes to access deployed services
  stable/phpmyadmin/Chart.yaml
  stable/phpmyadmin/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#7011 [stable/ghost] Improve notes to access deployed services
  stable/ghost/Chart.yaml
  stable/ghost/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#6842 Templatize imagePullSecrets for NATS
  stable/nats/Chart.yaml
  stable/nats/templates/statefulset.yaml
  stable/nats/values-production.yaml
  stable/nats/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7010 [stable/drupal] Improve notes to access deployed services
  stable/drupal/Chart.yaml
  stable/drupal/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#7012 [stable/jasperreports] Improve notes to access deployed services
  stable/jasperreports/Chart.yaml
  stable/jasperreports/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#7013 [stable/joomla] Improve notes to access deployed services
  stable/joomla/Chart.yaml
  stable/joomla/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#7014 [stable/magento] Improve notes to access deployed services
  stable/magento/Chart.yaml
  stable/magento/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#7015 [stable/mediawiki] Improve notes to access deployed services
  stable/mediawiki/Chart.yaml
  stable/mediawiki/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#7018 [stable/moodle] Improve notes to access deployed services
  stable/moodle/Chart.yaml
  stable/moodle/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#7020 [stable/odoo] Improve notes to access deployed services
  stable/odoo/Chart.yaml
  stable/odoo/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#7021 [stable/opencart] Improve notes to access deployed services
  stable/opencart/Chart.yaml
  stable/opencart/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#7022 [stable/orangehrm] Improve notes to access deployed services
  stable/orangehrm/Chart.yaml
  stable/orangehrm/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#7023 [stable/osclass] Improve notes to access deployed services
  stable/osclass/Chart.yaml
  stable/osclass/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#7025 [stable/parse] Improve notes to access deployed services
  stable/parse/Chart.yaml
  stable/parse/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#7026 [stable/phabricator] Improve notes to access deployed services
  stable/phabricator/Chart.yaml
  stable/phabricator/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#7027 [stable/phpbb] Improve notes to access deployed services
  stable/phpbb/Chart.yaml
  stable/phpbb/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#7029 [stable/prestashop] Improve notes to access deployed services
  stable/prestashop/Chart.yaml
  stable/prestashop/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#7031 [stable/redis] Improve notes to access deployed services
  stable/redis/Chart.yaml
  stable/redis/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#7033 [stable/redmine] Improve notes to access deployed services
  stable/redmine/Chart.yaml
  stable/redmine/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#7034 [stable/suitecrm] Improve notes to access deployed services
  stable/suitecrm/Chart.yaml
  stable/suitecrm/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#7037 [stable/wordpress] Improve notes to access deployed services
  stable/wordpress/Chart.yaml
  stable/wordpress/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#7019 [stable/nats] Improve notes to access deployed services
  stable/nats/Chart.yaml
  stable/nats/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#7003 Comment out persistence.storageClass to accomodate K8s default storag…
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7005 Updated readme to reflect default value. Bumped chart version
  incubator/elasticsearch/Chart.yaml
  incubator/elasticsearch/README.md
Labels: approved, cncf-cla: yes, lgtm

#7008 [stable/hazelcast] Fix missing namespace parameter
  stable/hazelcast/Chart.yaml
  stable/hazelcast/templates/statefulset.yaml
  stable/hazelcast/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6966 [incubator/logstash] update to logstash version 6.3.2
  incubator/logstash/Chart.yaml
  incubator/logstash/README.md
  incubator/logstash/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7035 [stable/filebeat] Ability to load the index template in Elasticsearch
  stable/filebeat/Chart.yaml
  stable/filebeat/README.md
  stable/filebeat/templates/daemonset.yaml
  stable/filebeat/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7039 Coredns affinity tolerations
  stable/coredns/Chart.yaml
  stable/coredns/templates/deployment.yaml
  stable/coredns/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6957 [stable/verdaccio] feat(verdaccio): configurable securityContext
  stable/verdaccio/Chart.yaml
  stable/verdaccio/templates/deployment.yaml
  stable/verdaccio/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6979 incubator/cassandra v0.4.2 - Templating for liveness/readiness probes
  incubator/cassandra/Chart.yaml
  incubator/cassandra/README.md
  incubator/cassandra/templates/cassandra-statefulset.yaml
  incubator/cassandra/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6924 doc update for stable/nginx-ingress
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
Labels: approved, cncf-cla: yes, lgtm

#6815 [stable/grafana] Correctly set options.path in dashboardProviders
  stable/grafana/Chart.yaml
  stable/grafana/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6826 [stable/ark] update Ark to 0.9.1
  stable/ark/Chart.yaml
  stable/ark/README.md
  stable/ark/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6950 [stable/keycloak] Update to Keycloak 4.2.1.Final
  stable/keycloak/Chart.yaml
  stable/keycloak/README.md
  stable/keycloak/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6523 [stable/spinnaker] update minio dependency version
  stable/spinnaker/Chart.yaml
  stable/spinnaker/requirements.lock
  stable/spinnaker/requirements.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6722 Update Dask to version 0.18.1
  stable/dask/Chart.yaml
  stable/dask/README.md
  stable/dask/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6745 [stable/nginx-ingress] Upgrade to 0.17.1
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-daemonset.yaml
  stable/nginx-ingress/templates/controller-deployment.yaml
  stable/nginx-ingress/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6931 fix markdown
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/README.md
Labels: approved, cncf-cla: yes, lgtm

#7071 Adding probot stale issue handling config
  .github/stale.yml
Labels: approved, cncf-cla: yes, lgtm

#6999 [stable/ghost] Add option for external database port number
  stable/ghost/Chart.yaml
  stable/ghost/README.md
  stable/ghost/templates/deployment.yaml
  stable/ghost/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6768 [stable/openebs] Upgrade to openebs release 0.6
  stable/openebs/Chart.yaml
  stable/openebs/README.md
  stable/openebs/templates/clusterrole.yaml
  stable/openebs/templates/clusterrolebinding.yaml
  stable/openebs/templates/deployment-maya-apiserver.yaml
  stable/openebs/templates/deployment-maya-provisioner.yaml
  stable/openebs/templates/deployment-maya-snapshot-operator.yaml
  stable/openebs/templates/serviceaccount.yaml
  stable/openebs/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7086 Add support for custom annotations on headless service
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
  incubator/kafka/templates/service-headless.yaml
  incubator/kafka/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#5912 [stable/elastalert] Fix verbose/confusing index names on Elasticsearch 6.x
  stable/elastalert/Chart.yaml
  stable/elastalert/README.md
  stable/elastalert/templates/config.yaml
  stable/elastalert/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6748 [incubator/azuremonitor-containers] Fix typos in readme & notes
  incubator/azuremonitor-containers/Chart.yaml
  incubator/azuremonitor-containers/README.md
  incubator/azuremonitor-containers/templates/NOTES.txt
  incubator/azuremonitor-containers/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6916 Fixing conflict with port definition and extra volume mounts
  incubator/fluentd-elasticsearch/Chart.yaml
  incubator/fluentd-elasticsearch/templates/daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm

#6928 [stable/sentry] Creating the admin user in optionally
  stable/sentry/Chart.yaml
  stable/sentry/README.md
  stable/sentry/templates/hooks/user-create.job.yaml
  stable/sentry/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7100 [stable/traefik] Fix compress option identation when proxy protocol i…
  stable/traefik/Chart.yaml
  stable/traefik/templates/configmap.yaml
Labels: approved, cncf-cla: yes, lgtm

#6687 [stable/neo4j] Add License agreement in replica pod too
  stable/neo4j/Chart.yaml
  stable/neo4j/templates/readreplicas-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7120 Add a new approver
  stable/gocd/Chart.yaml
  stable/gocd/OWNERS
Labels: approved, cncf-cla: yes, lgtm

#6848 [stable/memcached] Add olemarkus as maintainer for this chart
  stable/memcached/.helmignore
  stable/memcached/Chart.yaml
  stable/memcached/OWNERS
Labels: approved, cncf-cla: yes, lgtm

#7096 [stable/mongodb] replicaset.useHostnames option
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/templates/secrets.yaml
  stable/mongodb/templates/statefulset-arbiter-rs.yaml
  stable/mongodb/templates/statefulset-primary-rs.yaml
  stable/mongodb/templates/statefulset-secondary-rs.yaml
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7062 chaoskube: bump chart version to v0.9.0
  stable/chaoskube/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm

#7097 [stable/ghost] Can't evaluate field port in type interface
  stable/ghost/Chart.yaml
  stable/ghost/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm

#7082 [stable/mongodb] Add service annotations
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/templates/headless-svc-rs.yaml
  stable/mongodb/templates/svc-primary-rs.yaml
  stable/mongodb/templates/svc-standalone.yaml
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7101 wordpress: Set ALLOW_EMPTY_PASSWORD correctly
  stable/wordpress/Chart.yaml
  stable/wordpress/templates/deployment.yaml
  stable/wordpress/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6730 Updating the readme for the repo location
  README.md
Labels: approved, cncf-cla: yes, lgtm

#7128 cert-manager: fast-forward to upstream ad30555d
  stable/cert-manager/Chart.yaml
  stable/cert-manager/README.md
  stable/cert-manager/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7129 [stable/kiam] add option to use hostNetwork for server
  stable/kiam/Chart.yaml
  stable/kiam/README.md
  stable/kiam/templates/server-daemonset.yaml
  stable/kiam/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7118 [stable/traefik] set non-nil default values and comment out loadBalancerIP
  stable/traefik/Chart.yaml
  stable/traefik/templates/service.yaml
  stable/traefik/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6813 [stable/traefik] Add KV Provider support in order to make Traefik HA
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/configmap.yaml
  stable/traefik/templates/storeconfig-job.yaml
  stable/traefik/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7084 [stable/gocd] Add support for SSH keys on server and agent (New PR Cr…
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/README.md
  stable/gocd/templates/gocd-agent-deployment.yaml
  stable/gocd/templates/gocd-server-deployment.yaml
  stable/gocd/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6528 [incubator/xray] Typo fix: postgressql->postgresql
  incubator/xray/Chart.yaml
  incubator/xray/README.md
  incubator/xray/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6664 Metabase add ingress labels
  stable/metabase/Chart.yaml
  stable/metabase/README.md
  stable/metabase/templates/ingress.yaml
  stable/metabase/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6964 [stable/cockroachdb] Make chart work with --wait flag on helm install
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/templates/cluster-init.yaml
Labels: approved, cncf-cla: yes, lgtm

#6762 [Incubator/kafka] Fix init container fail when pod restart
  incubator/kafka/Chart.yaml
  incubator/kafka/templates/statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm

#7094 Make mariadb's service supports NodePort mode
  stable/mariadb/Chart.yaml
  stable/mariadb/templates/master-svc.yaml
  stable/mariadb/templates/slave-svc.yaml
  stable/mariadb/values-production.yaml
  stable/mariadb/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6310 [stable/artifactory-ha] bumped version + added support for nginx configmap
  stable/artifactory-ha/.helmignore
  stable/artifactory-ha/Chart.yaml
  stable/artifactory-ha/OWNERS
  stable/artifactory-ha/README.md
  stable/artifactory-ha/templates/_helpers.tpl
  stable/artifactory-ha/templates/artifactory-node-statefulset.yaml
  stable/artifactory-ha/templates/artifactory-primary-statefulset.yaml
  stable/artifactory-ha/templates/artifactory-role.yaml
  stable/artifactory-ha/templates/artifactory-rolebinding.yaml
  stable/artifactory-ha/templates/artifactory-serviceaccount.yaml
  stable/artifactory-ha/templates/nginx-deployment.yaml
  stable/artifactory-ha/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#6449 [stable/mission-control] Bumped version and added RBAC support
  stable/mission-control/.helmignore
  stable/mission-control/Chart.yaml
  stable/mission-control/OWNERS
  stable/mission-control/README.md
  stable/mission-control/templates/_helpers.tpl
  stable/mission-control/templates/hooks/create-user.yaml
  stable/mission-control/templates/insight-executor-deployment.yaml
  stable/mission-control/templates/insight-scheduler-deployment.yaml
  stable/mission-control/templates/insight-server-deployment.yaml
  stable/mission-control/templates/mission-control-deployment.yaml
  stable/mission-control/templates/mission-control-role.yaml
  stable/mission-control/templates/mission-control-rolebinding.yaml
  stable/mission-control/templates/mission-control-serviceaccount.yaml
  stable/mission-control/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#6380 [traefik] remove self as owner
  stable/traefik/Chart.yaml
  stable/traefik/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7080 [stable/minio] Minio subpath misplaced
  stable/minio/Chart.yaml
  stable/minio/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6736 nginx-ingress: Use lists as default in extraVolumes
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6812 [stable/verdaccio]: Document pull policy correctly
  stable/verdaccio/Chart.yaml
  stable/verdaccio/README.md
Labels: approved, cncf-cla: yes, lgtm

#7152 Zookeeper: Add support for custom annotations on the headless service
  incubator/zookeeper/Chart.yaml
  incubator/zookeeper/templates/service-headless.yaml
  incubator/zookeeper/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7123 [stable/mysql] Add ability to modify timezone (#7121)
  stable/mysql/Chart.yaml
  stable/mysql/README.md
  stable/mysql/templates/deployment.yaml
  stable/mysql/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7113 [stable/selenium] upgrade version to 3.14.0
  stable/selenium/Chart.yaml
  stable/selenium/README.md
  stable/selenium/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6082 Add prometheus adapter chart
  stable/prometheus-adapter/Chart.yaml
  stable/prometheus-adapter/README.md
  stable/prometheus-adapter/templates/_helpers.tpl
  stable/prometheus-adapter/templates/custom-metrics-apiserver-auth-delegator-cluster-role-binding.yaml
  stable/prometheus-adapter/templates/custom-metrics-apiserver-auth-reader-role-binding.yaml
  stable/prometheus-adapter/templates/custom-metrics-apiserver-deployment.yaml
  stable/prometheus-adapter/templates/custom-metrics-apiserver-resource-reader-cluster-role-binding.yaml
  stable/prometheus-adapter/templates/custom-metrics-apiserver-service-account.yaml
  stable/prometheus-adapter/templates/custom-metrics-apiserver-service.yaml
  stable/prometheus-adapter/templates/custom-metrics-apiservice.yaml
  stable/prometheus-adapter/templates/custom-metrics-cluster-role.yaml
  stable/prometheus-adapter/templates/custom-metrics-configmap.yaml
  stable/prometheus-adapter/templates/custom-metrics-resource-reader-cluster-role.yaml
  stable/prometheus-adapter/templates/hpa-custom-metrics-cluster-role-binding.yaml
  stable/prometheus-adapter/templates/secret.yaml
  stable/prometheus-adapter/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#6312 [stable/rabbitmq-ha] Updated metrics parameters
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/templates/NOTES.txt
  stable/rabbitmq-ha/templates/statefulset.yaml
  stable/rabbitmq-ha/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6405 [stable/nginx-ingress] Configurable default-backend port
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/default-backend-deployment.yaml
  stable/nginx-ingress/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6990 [stable/stolon] Add option to force-disable stolon auto-cluster-creation
  stable/stolon/Chart.yaml
  stable/stolon/README.md
  stable/stolon/templates/create-cluster-job.yaml
  stable/stolon/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6435 [stable/home-assistant] (new chart) home-assistant
  stable/home-assistant/.helmignore
  stable/home-assistant/Chart.yaml
  stable/home-assistant/README.md
  stable/home-assistant/templates/NOTES.txt
  stable/home-assistant/templates/_helpers.tpl
  stable/home-assistant/templates/configurator-deployment.yaml
  stable/home-assistant/templates/configurator-ingress.yaml
  stable/home-assistant/templates/configurator-secret.yaml
  stable/home-assistant/templates/configurator-svc.yaml
  stable/home-assistant/templates/deployment.yaml
  stable/home-assistant/templates/ingress.yaml
  stable/home-assistant/templates/pvc.yaml
  stable/home-assistant/templates/service.yaml
  stable/home-assistant/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#6820 [stable/grafana] updated grafana to version 5.2.2
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7163 [stable/docker-registry] add support for pod tolerations
  stable/docker-registry/Chart.yaml
  stable/docker-registry/README.md
  stable/docker-registry/templates/deployment.yaml
  stable/docker-registry/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6598 [stable/keel] Added missing Slack Approval Channel
  stable/keel/Chart.yaml
  stable/keel/README.md
  stable/keel/templates/deployment.yaml
  stable/keel/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7176 [stable/cockroachdb]: Update version and fix typos in README
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/README.md
  stable/cockroachdb/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6457 [stable/stolon] Typo fix: perisistent->persistent
  stable/stolon/Chart.yaml
  stable/stolon/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, wontfix

#6752 [stable/sentry] bump sentry, dependency charts, add configmap
  stable/sentry/Chart.yaml
  stable/sentry/README.md
  stable/sentry/requirements.lock
  stable/sentry/requirements.yaml
  stable/sentry/templates/configmap.yaml
  stable/sentry/templates/cron-deployment.yaml
  stable/sentry/templates/hooks/db-init.job.yaml
  stable/sentry/templates/hooks/user-create.job.yaml
  stable/sentry/templates/web-deployment.yaml
  stable/sentry/templates/workers-deployment.yaml
  stable/sentry/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7004 upgrade auditbeat
  stable/auditbeat/Chart.yaml
  stable/auditbeat/README.md
  stable/auditbeat/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6389 fix typo
  stable/hlf-couchdb/Chart.yaml
  stable/hlf-couchdb/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, wontfix

#6962 [stable/jenkins] make pod retention policy setting configurable
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/config.yaml
  stable/jenkins/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7179 stable/memcached: Adds kennethaasan to OWNERS/maintainers
  stable/memcached/Chart.yaml
  stable/memcached/OWNERS
Labels: approved, cncf-cla: yes, lgtm

#7160 [stable/wordpress] fix required string value being parsed as bool
  stable/wordpress/Chart.yaml
  stable/wordpress/templates/deployment.yaml
  stable/wordpress/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6847 stable/memcached: Add support for metrics
  stable/memcached/Chart.yaml
  stable/memcached/README.md
  stable/memcached/templates/statefulset.yaml
  stable/memcached/templates/svc.yaml
  stable/memcached/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6337 [incubator/distribution] added RBAC support
  stable/distribution/.helmignore
  stable/distribution/Chart.yaml
  stable/distribution/OWNERS
  stable/distribution/README.md
  stable/distribution/ci/test-values.yaml
  stable/distribution/requirements.lock
  stable/distribution/requirements.yaml
  stable/distribution/templates/NOTES.txt
  stable/distribution/templates/_helpers.tpl
  stable/distribution/templates/distribution-deployment.yaml
  stable/distribution/templates/distribution-pvc.yaml
  stable/distribution/templates/distribution-role.yaml
  stable/distribution/templates/distribution-rolebinding.yaml
  stable/distribution/templates/distribution-serviceaccount.yaml
  stable/distribution/templates/distribution-svc.yaml
  stable/distribution/templates/distributor-deployment.yaml
  stable/distribution/templates/distributor-pvc.yaml
  stable/distribution/templates/distributor-token.yaml
  stable/distribution/templates/ingress.yaml
  stable/distribution/templates/mongo-connection-secret.yaml
  stable/distribution/templates/redis-connection-secret.yaml
  stable/distribution/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#7155 [incubator/distribution] Deprecating incubator chart
  incubator/distribution/Chart.yaml
  incubator/distribution/README.md
  incubator/distribution/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#7156 [incubator/xray] Deprecating incubator chart
  incubator/xray/Chart.yaml
  incubator/xray/README.md
  incubator/xray/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#6335 [incubator/xray] Bumped Xray version and added RBAC support
  stable/xray/.helmignore
  stable/xray/Chart.yaml
  stable/xray/OWNERS
  stable/xray/README.md
  stable/xray/ci/test-values.yaml
  stable/xray/requirements.lock
  stable/xray/requirements.yaml
  stable/xray/templates/NOTES.txt
  stable/xray/templates/_helpers.tpl
  stable/xray/templates/ingress.yaml
  stable/xray/templates/rabbitmq-ha-configmap.yaml
  stable/xray/templates/xray-analysis-deployment.yaml
  stable/xray/templates/xray-analysis-svc.yaml
  stable/xray/templates/xray-indexer-deployment.yaml
  stable/xray/templates/xray-indexer-svc.yaml
  stable/xray/templates/xray-master-key.yaml
  stable/xray/templates/xray-persist-deployment.yaml
  stable/xray/templates/xray-persist-svc.yaml
  stable/xray/templates/xray-role.yaml
  stable/xray/templates/xray-rolebinding.yaml
  stable/xray/templates/xray-server-deployment.yaml
  stable/xray/templates/xray-server-svc.yaml
  stable/xray/templates/xray-serviceaccount.yaml
  stable/xray/templates/xray-setup-conf.yaml
  stable/xray/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#6779 Update README to change k8s member step
  .circleci/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  REVIEW_GUIDELINES.md
  test/README.md
  test/e2e.sh
Labels: approved, cncf-cla: yes, lgtm

#6414 [stable/k8s-spot-rescheduler] bump k8s-spot-rescheduler to v0.2.0
  stable/k8s-spot-rescheduler/Chart.yaml
  stable/k8s-spot-rescheduler/templates/clusterrole.yaml
  stable/k8s-spot-rescheduler/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#7059 [stable/falco] Update falco_rules.yaml file to use same rules that Falco 0.11.1
  stable/falco/CHANGELOG.md
  stable/falco/Chart.yaml
  stable/falco/rules/falco_rules.yaml
Labels: approved, cncf-cla: yes, lgtm

#7191 [stable/falco] Enable eBPF support for Sysdig Falco helm chart
  stable/falco/CHANGELOG.md
  stable/falco/Chart.yaml
  stable/falco/README.md
  stable/falco/templates/daemonset.yaml
  stable/falco/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7188 [incubator/spring-cloud-data-flow] Update to new SCDF version 1.6.1
  incubator/spring-cloud-data-flow/Chart.yaml
  incubator/spring-cloud-data-flow/README.md
  incubator/spring-cloud-data-flow/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7183 [stable/prometheus-adapter] Enhancements
  stable/prometheus-adapter/.helmignore
  stable/prometheus-adapter/Chart.yaml
  stable/prometheus-adapter/README.md
  stable/prometheus-adapter/templates/NOTES.txt
  stable/prometheus-adapter/templates/_helpers.tpl
  stable/prometheus-adapter/templates/custom-metrics-apiserver-deployment.yaml
  stable/prometheus-adapter/templates/custom-metrics-apiserver-service.yaml
  stable/prometheus-adapter/templates/custom-metrics-configmap.yaml
  stable/prometheus-adapter/templates/secret.yaml
  stable/prometheus-adapter/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#4069 new chart stable/mysqldump
  stable/mysqldump/.helmignore
  stable/mysqldump/Chart.yaml
  stable/mysqldump/OWNERS
  stable/mysqldump/README.md
  stable/mysqldump/files/job.tpl
  stable/mysqldump/templates/NOTES.txt
  stable/mysqldump/templates/_helpers.tpl
  stable/mysqldump/templates/mysqldump-cm.yaml
  stable/mysqldump/templates/mysqldump-cron.yaml
  stable/mysqldump/templates/mysqldump-job.yaml
  stable/mysqldump/templates/mysqldump-pvc.yaml
  stable/mysqldump/templates/mysqldump-script.yaml
  stable/mysqldump/templates/mysqldump-secret.yaml
  stable/mysqldump/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L, wontfix

#6843 [stable/mongodb-replicaset]: use mongodb as port name to allow DNS seedlists
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/templates/mongodb-service.yaml
  stable/mongodb-replicaset/templates/mongodb-statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm

#7198 [stable/sonarqube] Fix loadBalancerIp if statement
  stable/sonarqube/Chart.yaml
  stable/sonarqube/templates/service.yaml
Labels: approved, cncf-cla: yes, lgtm

#7196 Add NodeSelector to CockroachDB Pods
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/templates/cockroachdb-statefulset.yaml
  stable/cockroachdb/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7066 [stable/kibana] Prevent "env: Not a table" warnings
  stable/kibana/Chart.yaml
  stable/kibana/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7178 NOTES: change port-forward to single command
  stable/mysql/Chart.yaml
  stable/mysql/templates/NOTES.txt
Labels: approved, cncf-cla: yes, lgtm

#7139 posgres dynamic volume
  stable/concourse/Chart.yaml
  stable/concourse/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7162 [stable/rabbitmq-ha] add image.pullSecrets
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/templates/statefulset.yaml
  stable/rabbitmq-ha/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6915 Add ingress resources to Kong chart
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/templates/NOTES.txt
  stable/kong/templates/ingress-admin.yaml
  stable/kong/templates/ingress-proxy.yaml
  stable/kong/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7078 [stable/prometheus-rabbitmq-exporter] fix values
  stable/prometheus-rabbitmq-exporter/Chart.yaml
  stable/prometheus-rabbitmq-exporter/README.md
  stable/prometheus-rabbitmq-exporter/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7138 Remove duplicate resources expansion
  stable/janusgraph/Chart.yaml
  stable/janusgraph/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm

#7153 Neo4j remove privileged security context, upgrade to 3.4.x series
  stable/neo4j/Chart.yaml
  stable/neo4j/templates/core-statefulset.yaml
  stable/neo4j/templates/readreplicas-deployment.yaml
  stable/neo4j/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6470 [stable/kured] Add initial chart
  stable/kured/.helmignore
  stable/kured/Chart.yaml
  stable/kured/README.md
  stable/kured/templates/NOTES.txt
  stable/kured/templates/_helpers.tpl
  stable/kured/templates/clusterrole.yaml
  stable/kured/templates/clusterrolebinding.yaml
  stable/kured/templates/daemonset.yaml
  stable/kured/templates/role.yaml
  stable/kured/templates/rolebinding.yaml
  stable/kured/templates/serviceaccount.yaml
  stable/kured/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#6567 Fix RBAC roles for kubewatch
  stable/kubewatch/Chart.yaml
  stable/kubewatch/templates/clusterrole.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6944 [Cassandra] Add Information About DC and Rack Names
  incubator/cassandra/Chart.yaml
  incubator/cassandra/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7076 [incubator/logstash] Adding support for imagePullSecrets
  incubator/logstash/Chart.yaml
  incubator/logstash/README.md
  incubator/logstash/templates/statefulset.yaml
  incubator/logstash/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6433 NFS client provisioner
  stable/nfs-client-provisioner/.helmignore
  stable/nfs-client-provisioner/Chart.yaml
  stable/nfs-client-provisioner/README.md
  stable/nfs-client-provisioner/ci/test-values.yaml
  stable/nfs-client-provisioner/templates/_helpers.tpl
  stable/nfs-client-provisioner/templates/clusterrole.yaml
  stable/nfs-client-provisioner/templates/clusterrolebinding.yaml
  stable/nfs-client-provisioner/templates/deployment.yaml
  stable/nfs-client-provisioner/templates/serviceaccount.yaml
  stable/nfs-client-provisioner/templates/storageclass.yaml
  stable/nfs-client-provisioner/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#7140 [stable/rabbitmq-ha] Add HTTP auth backend
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/templates/configmap.yaml
  stable/rabbitmq-ha/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7164 Configure kubernetes plugin for including namespace value
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/config.yaml
Labels: approved, cncf-cla: yes, lgtm

#7137 [stable/rabbitmq-ha] Use randAlphaNum instead of randAscii to generate random password
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/templates/secret.yaml
Labels: approved, cncf-cla: yes, lgtm

#7215 [stable/prometheus] Add affinity to server & alertmanager
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/alertmanager-deployment.yaml
  stable/prometheus/templates/server-deployment.yaml
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7147 [incubator/kafka] updated default version to latest release
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
  incubator/kafka/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6831 [stable/docker-registry] Improve full name definition
  stable/docker-registry/Chart.yaml
  stable/docker-registry/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm

#7203 [CI] Use latest chart-testing image
  .circleci/config.yml
  test/Dockerfile
  test/build.sh
  test/e2e.sh
Labels: approved, cncf-cla: yes, lgtm

#7064 Fluent-bit chart add splunk support
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/NOTES.txt
  stable/fluent-bit/templates/config.yaml
  stable/fluent-bit/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7112 [incubator/logstash] Add terminationGracePeriodSeconds
  incubator/logstash/Chart.yaml
  incubator/logstash/README.md
  incubator/logstash/templates/statefulset.yaml
  incubator/logstash/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#7130 Add Express Gateway image
  stable/express-gateway/.helmignore
  stable/express-gateway/Chart.yaml
  stable/express-gateway/README.md
  stable/express-gateway/requirements.lock
  stable/express-gateway/requirements.yaml
  stable/express-gateway/templates/NOTES.txt
  stable/express-gateway/templates/_helpers.tpl
  stable/express-gateway/templates/configmap.yaml
  stable/express-gateway/templates/deployment.yaml
  stable/express-gateway/templates/service-eg-admin.yaml
  stable/express-gateway/templates/service-eg-proxy.yaml
  stable/express-gateway/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6477 Make liveness and readiness settings configurable for the metrics con…
  stable/mysql/Chart.yaml
  stable/mysql/README.md
  stable/mysql/templates/deployment.yaml
  stable/mysql/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6992 [incubator/raw] New chart
  incubator/raw/.helmignore
  incubator/raw/Chart.yaml
  incubator/raw/OWNERS
  incubator/raw/README.md
  incubator/raw/templates/NOTES.txt
  incubator/raw/templates/_helpers.tpl
  incubator/raw/templates/resources.yaml
  incubator/raw/values.yaml
Labels: approved, cncf-cla: yes, lgtm

#6695 [stable/datadog] Fix https://github.com/kubernetes/charts/issues/6572
  stable/datadog/Chart.yaml
  stable/datadog/templates/daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
