Repository helm/charts, pull requests merged in 2018-12, with the labels that each got.

#7261 common: fix empty templates exception
  incubator/common/Chart.yaml
  incubator/common/templates/_util.tpl
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm

#9555 add/use unified labels for prometheus components
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/_helpers.tpl
  stable/prometheus/templates/alertmanager-configmap.yaml
  stable/prometheus/templates/alertmanager-deployment.yaml
  stable/prometheus/templates/alertmanager-ingress.yaml
  stable/prometheus/templates/alertmanager-networkpolicy.yaml
  stable/prometheus/templates/alertmanager-pvc.yaml
  stable/prometheus/templates/alertmanager-service.yaml
  stable/prometheus/templates/alertmanager-serviceaccount.yaml
  stable/prometheus/templates/kube-state-metrics-clusterrole.yaml
  stable/prometheus/templates/kube-state-metrics-clusterrolebinding.yaml
  stable/prometheus/templates/kube-state-metrics-deployment.yaml
  stable/prometheus/templates/kube-state-metrics-networkpolicy.yaml
  stable/prometheus/templates/kube-state-metrics-serviceaccount.yaml
  stable/prometheus/templates/kube-state-metrics-svc.yaml
  stable/prometheus/templates/node-exporter-daemonset.yaml
  stable/prometheus/templates/node-exporter-podsecuritypolicy.yaml
  stable/prometheus/templates/node-exporter-role.yaml
  stable/prometheus/templates/node-exporter-rolebinding.yaml
  stable/prometheus/templates/node-exporter-service.yaml
  stable/prometheus/templates/node-exporter-serviceaccount.yaml
  stable/prometheus/templates/pushgateway-deployment.yaml
  stable/prometheus/templates/pushgateway-ingress.yaml
  stable/prometheus/templates/pushgateway-service.yaml
  stable/prometheus/templates/pushgateway-serviceaccount.yaml
  stable/prometheus/templates/server-clusterrole.yaml
  stable/prometheus/templates/server-clusterrolebinding.yaml
  stable/prometheus/templates/server-configmap.yaml
  stable/prometheus/templates/server-deployment.yaml
  stable/prometheus/templates/server-ingress.yaml
  stable/prometheus/templates/server-networkpolicy.yaml
  stable/prometheus/templates/server-pvc.yaml
  stable/prometheus/templates/server-service.yaml
  stable/prometheus/templates/server-serviceaccount.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#9618 [stable/prometheus-node-exporter] add securityContext value
  stable/prometheus-node-exporter/Chart.yaml
  stable/prometheus-node-exporter/README.md
  stable/prometheus-node-exporter/templates/daemonset.yaml
  stable/prometheus-node-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9655 [stable/redis-ha] Fix annotations typo in statefulset
  stable/redis-ha/Chart.yaml
  stable/redis-ha/templates/redis-ha-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9595 securityContext in prometheus-operator needs to be configurable
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/prometheus-operator/deployment.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9643 Updated Notes file to remove component label.
  stable/grafana/Chart.yaml
  stable/grafana/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9681 upgrade pushgateway and node-exporter
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9560 [stable/mongodb] Fix Prometheus monitoring using Prometheus Operator for standalone deployments
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/deployment-standalone.yaml
  stable/mongodb/templates/statefulset-arbiter-rs.yaml
  stable/mongodb/templates/statefulset-primary-rs.yaml
  stable/mongodb/templates/statefulset-secondary-rs.yaml
  stable/mongodb/templates/svc-standalone.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9133 [stable/cloudserver]: add Cloudserver chart
  stable/cloudserver/.helmignore
  stable/cloudserver/Chart.yaml
  stable/cloudserver/OWNERS
  stable/cloudserver/README.md
  stable/cloudserver/requirements.lock
  stable/cloudserver/requirements.yaml
  stable/cloudserver/templates/NOTES.txt
  stable/cloudserver/templates/_helpers.tpl
  stable/cloudserver/templates/api-certificate.yaml
  stable/cloudserver/templates/api-configmap.yaml
  stable/cloudserver/templates/api-deployment.yaml
  stable/cloudserver/templates/api-hpa.yaml
  stable/cloudserver/templates/api-ingress.yaml
  stable/cloudserver/templates/api-secrets.yaml
  stable/cloudserver/templates/api-service.yaml
  stable/cloudserver/templates/api-serviceaccount.yaml
  stable/cloudserver/templates/localdata-deployment.yaml
  stable/cloudserver/templates/localdata-pvc.yaml
  stable/cloudserver/templates/localdata-service.yaml
  stable/cloudserver/templates/localdata-serviceaccount.yaml
  stable/cloudserver/templates/tests/test-cloudserver.yaml
  stable/cloudserver/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XL

#8938 [stable/mongodb-replicaset] fix harcoded busybox image
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/README.md
  stable/mongodb-replicaset/templates/mongodb-statefulset.yaml
  stable/mongodb-replicaset/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#8729 [stable/mongodb-replicaset] Added pullSecrets override
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/README.md
  stable/mongodb-replicaset/templates/mongodb-statefulset.yaml
  stable/mongodb-replicaset/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9384 [stable/influxdb] Move bind_address under rpc header and update image to 1.7
  stable/influxdb/Chart.yaml
  stable/influxdb/OWNERS
  stable/influxdb/README.md
  stable/influxdb/templates/config.yaml
  stable/influxdb/templates/service.yaml
  stable/influxdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#9383 [stable/chronograf] use env vars, and env secret and update image to 1.7
  stable/chronograf/Chart.yaml
  stable/chronograf/OWNERS
  stable/chronograf/README.md
  stable/chronograf/templates/deployment.yaml
  stable/chronograf/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#9687 [stable/redis] allowing redis-exporter to talk to redis when NetworkPolicy is enabled
  stable/redis/Chart.yaml
  stable/redis/templates/networkpolicy.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9356 [stable/auditbeat] updated auditbeat to 6.5.1
  stable/auditbeat/Chart.yaml
  stable/auditbeat/README.md
  stable/auditbeat/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9265 [stable/fluentd-elasticsearch] update chart to use v2.3.2 docker image
  stable/fluentd-elasticsearch/Chart.yaml
  stable/fluentd-elasticsearch/README.md
  stable/fluentd-elasticsearch/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9357 [stable/heartbeat] updated heartbeat to 6.5.1
  stable/heartbeat/Chart.yaml
  stable/heartbeat/README.md
  stable/heartbeat/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9360 [stable/kibana] add Monotek to Owners; Chart -> 1.0
  stable/kibana/Chart.yaml
  stable/kibana/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#3959 [incubator/airflow] Airflow Helm Chart
  stable/airflow/.helmignore
  stable/airflow/Chart.yaml
  stable/airflow/OWNERS
  stable/airflow/README.md
  stable/airflow/examples/minikube-values.yaml
  stable/airflow/requirements.yaml
  stable/airflow/templates/NOTES.txt
  stable/airflow/templates/_helpers.tpl
  stable/airflow/templates/configmap-airflow.yaml
  stable/airflow/templates/configmap-git-clone.yaml
  stable/airflow/templates/configmap-scripts.yaml
  stable/airflow/templates/deployments-flower.yaml
  stable/airflow/templates/deployments-scheduler.yaml
  stable/airflow/templates/deployments-web.yaml
  stable/airflow/templates/ingress-flower.yaml
  stable/airflow/templates/ingress-web.yaml
  stable/airflow/templates/poddisruptionbudget.yaml
  stable/airflow/templates/pvc.yaml
  stable/airflow/templates/role-binding.yaml
  stable/airflow/templates/role.yaml
  stable/airflow/templates/secrets.yaml
  stable/airflow/templates/service-account.yaml
  stable/airflow/templates/service-flower.yaml
  stable/airflow/templates/service-web.yaml
  stable/airflow/templates/service-worker.yaml
  stable/airflow/templates/statefulsets-workers.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#9637 [stable/nginx-ingress] Fixes permissions when running in scoped mode …
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/templates/scoped-clusterrole.yaml
  stable/nginx-ingress/templates/scoped-clusterrolebinding.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#9711 [stable/prometheus-adapter] Upgrading to v0.4.0
  stable/prometheus-adapter/Chart.yaml
  stable/prometheus-adapter/README.md
  stable/prometheus-adapter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9721 [stable/sonarqube] Upgrade chart for new sonarqube images
  stable/sonarqube/Chart.yaml
  stable/sonarqube/README.md
  stable/sonarqube/templates/deployment.yaml
  stable/sonarqube/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#9023 Update MetalLB README.md and values.yaml
  stable/metallb/Chart.yaml
  stable/metallb/README.md
  stable/metallb/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#9514 Deprecating keel chart
  stable/keel/Chart.yaml
  stable/keel/README.md
  stable/keel/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, size/S

#9008 [stable/fluent-bit] Revert to og indentation... or Refactor configuration
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/config.yaml
  stable/fluent-bit/templates/daemonset.yaml
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#9736 [stable/kured] Add pod annotations
  stable/kured/Chart.yaml
  stable/kured/README.md
  stable/kured/templates/daemonset.yaml
  stable/kured/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9737 [stable/karma] add myself to the OWNERS file
  stable/karma/Chart.yaml
  stable/karma/OWNERS
Labels: Contribution Allowed, approved, lgtm, size/XS

#9704 Add @nitisht and @wlan0 as Trusted Collaborators
  stable/minio/Chart.yaml
  stable/minio/OWNERS
Labels: Contribution Allowed, approved, lgtm, size/S

#9531 Update Minio and mc versions
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/templates/deployment.yaml
  stable/minio/templates/pvc.yaml
  stable/minio/templates/statefulset.yaml
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#9574 [stable/postgresql] Merge metrics into master statefulset as sidecar.
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/metrics-deployment.yaml
  stable/postgresql/templates/metrics-svc.yaml
  stable/postgresql/templates/statefulset.yaml
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#9718 [incubator/cassandra] update backup tag to enable file streaming
  incubator/cassandra/Chart.yaml
  incubator/cassandra/README.md
  incubator/cassandra/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9725 upgrade external-dns
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9692 Upgrade grafana
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9685 upgrade elasticsearch to 6.5.1
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/README.md
  stable/elasticsearch/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9729 Add existingSecret configuration key to postgresql chart
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/NOTES.txt
  stable/postgresql/templates/secrets.yaml
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9750 [stable/kibana] update kibana to 6.5.1
  stable/kibana/Chart.yaml
  stable/kibana/README.md
  stable/kibana/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#9658 [stable/kibana] Define successful threshold for kibana pod readiness (#9649)
  stable/kibana/Chart.yaml
  stable/kibana/README.md
  stable/kibana/templates/deployment.yaml
  stable/kibana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9763 [stable/minio] Add S3 gateway support
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/templates/deployment.yaml
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#9771 Add OWNERS file
  stable/ingressmonitorcontroller/.helmignore
  stable/ingressmonitorcontroller/Chart.yaml
  stable/ingressmonitorcontroller/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9767 Add and deprecate incubator/artifactory
  incubator/artifactory/.helmignore
  incubator/artifactory/Chart.yaml
  incubator/artifactory/README.md
  incubator/artifactory/templates/NOTES.txt
  incubator/artifactory/templates/_helpers.tpl
  incubator/artifactory/templates/deployment.yaml
  incubator/artifactory/templates/svc.yaml
  incubator/artifactory/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#9775 Fix broken table in README.md for PostgreSQL chart
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9748 [stable/openebs] update openebs to latest 0.8.0 release
  stable/openebs/Chart.yaml
  stable/openebs/README.md
  stable/openebs/templates/cm-maya-apiserver-config.yaml
  stable/openebs/templates/deployment-maya-apiserver.yaml
  stable/openebs/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#9766 [stable/selenium] Add podAnnotations to Selenium deployments
  stable/selenium/Chart.yaml
  stable/selenium/README.md
  stable/selenium/templates/chrome-deployment.yaml
  stable/selenium/templates/chromeDebug-deployment.yaml
  stable/selenium/templates/firefox-deployment.yaml
  stable/selenium/templates/firefoxDebug-deployment.yaml
  stable/selenium/templates/hub-deployment.yaml
  stable/selenium/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#9686 Add chart for consul-exporter
  stable/prometheus-consul-exporter/.helmignore
  stable/prometheus-consul-exporter/Chart.yaml
  stable/prometheus-consul-exporter/README.md
  stable/prometheus-consul-exporter/templates/NOTES.txt
  stable/prometheus-consul-exporter/templates/_helpers.tpl
  stable/prometheus-consul-exporter/templates/deployment.yaml
  stable/prometheus-consul-exporter/templates/podsecuritypolicy.yaml
  stable/prometheus-consul-exporter/templates/role.yaml
  stable/prometheus-consul-exporter/templates/rolebinding.yaml
  stable/prometheus-consul-exporter/templates/service.yaml
  stable/prometheus-consul-exporter/templates/serviceaccount.yaml
  stable/prometheus-consul-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#9494 [stable/external-dns] Add SecurityContext and bump to 0.5.9
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/deployment.yaml
  stable/external-dns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#9786 Only pass POSTGRESQL_DATABASE if it is set
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9646 [stable/postgresql] Support different affinities, nodeSelectors and tolerations for master & slaves
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/_helpers.tpl
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#9716 [stable/datadog] add configuration for datadog intake server (#9715)
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/cluster-agent-deployment.yaml
  stable/datadog/templates/daemonset.yaml
  stable/datadog/templates/deployment.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#9042 [stable/keycloak] use realm url for probe instead of static welcome page
  stable/keycloak/Chart.yaml
  stable/keycloak/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9815 fix(docs): drone NOTES.txt update
  stable/drone/Chart.yaml
  stable/drone/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9811 [stable/Kube-ops-view] Add securityContext
  stable/kube-ops-view/Chart.yaml
  stable/kube-ops-view/templates/deployment.yaml
  stable/kube-ops-view/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9800 [stable/coredns] Support for fullnameOverride
  stable/coredns/Chart.yaml
  stable/coredns/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9817 Allow setting metabase's ingress path
  stable/metabase/Chart.yaml
  stable/metabase/README.md
  stable/metabase/templates/ingress.yaml
  stable/metabase/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9807 [proposal] adding cpanato to owners file on root
  OWNERS
Labels: Contribution Allowed, approved, lgtm, size/XS

#9821 [incubator/gogs] Add securityContext
  incubator/gogs/Chart.yaml
  incubator/gogs/templates/deployment.yaml
  incubator/gogs/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9707 [stable/mongodb-replicaset] Update peer-finder
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/README.md
  stable/mongodb-replicaset/install/Dockerfile
  stable/mongodb-replicaset/install/Makefile
  stable/mongodb-replicaset/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#9710 [stable/prometheus-operator] Upgrading prometheus version to v2.5.0
  stable/prometheus-operator/CONTRIBUTING.md
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#9779 [stable/elasticsearch] Fix missing updateStrategy parameter in README.
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9813 add aws-alb-ingress-controller
  incubator/aws-alb-ingress-controller/.helmignore
  incubator/aws-alb-ingress-controller/Chart.yaml
  incubator/aws-alb-ingress-controller/README.md
  incubator/aws-alb-ingress-controller/templates/NOTES.txt
  incubator/aws-alb-ingress-controller/templates/_helpers.tpl
  incubator/aws-alb-ingress-controller/templates/clusterrole.yaml
  incubator/aws-alb-ingress-controller/templates/clusterrolebinding.yaml
  incubator/aws-alb-ingress-controller/templates/deployment.yaml
  incubator/aws-alb-ingress-controller/templates/serviceaccount.yaml
  incubator/aws-alb-ingress-controller/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#9780 [stable/postgresql] Add updateStrategy parameter.
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9846 [stable/wordpress] Bump major in the chart version because a major in the app version
  stable/wordpress/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9850 [stable/keycloak] Expose JGROUPS port (default 7600) [#9849]
  stable/keycloak/Chart.yaml
  stable/keycloak/templates/headless-service.yaml
  stable/keycloak/templates/statefulset.yaml
  stable/keycloak/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9742 [stable/elasticsearch] Ingress for Elasticsearch client nodes
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/README.md
  stable/elasticsearch/templates/client-ingress.yaml
  stable/elasticsearch/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#9841 Fix the targetPort of the external broker services
  incubator/kafka/Chart.yaml
  incubator/kafka/templates/service-brokers-external.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9785 Enable Redis in kube-ops-view
  stable/kube-ops-view/Chart.yaml
  stable/kube-ops-view/README.md
  stable/kube-ops-view/requirements.yaml
  stable/kube-ops-view/templates/deployment.yaml
  stable/kube-ops-view/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9861 [stable/MM-te] Fixing labels
  stable/mattermost-team-edition/Chart.yaml
  stable/mattermost-team-edition/templates/configmap-config.yaml
  stable/mattermost-team-edition/templates/deployment.yaml
  stable/mattermost-team-edition/templates/ingress.yaml
  stable/mattermost-team-edition/templates/pvc.yaml
  stable/mattermost-team-edition/templates/service.yaml
  stable/mattermost-team-edition/templates/tests/mattermost-config-test.yaml
  stable/mattermost-team-edition/templates/tests/mattermost-test.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#8977 mssql-linux fullNameOverride value
  stable/mssql-linux/Chart.yaml
  stable/mssql-linux/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9868 [stable/mongodb-replicaset] Update maintainers
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/OWNERS
Labels: Contribution Allowed, approved, lgtm, size/S

#9876 [stable/cockroachdb] Upgrade CockroachDB version to v2.1.2
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/README.md
  stable/cockroachdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9293 add apache ignite helm chart
  stable/ignite/.helmignore
  stable/ignite/Chart.yaml
  stable/ignite/README.md
  stable/ignite/templates/NOTES.txt
  stable/ignite/templates/_helpers.tpl
  stable/ignite/templates/account-role.yaml
  stable/ignite/templates/configmap.yaml
  stable/ignite/templates/persistence-storage-class.yaml
  stable/ignite/templates/role-binding.yaml
  stable/ignite/templates/service-account.yaml
  stable/ignite/templates/stateful-set.yaml
  stable/ignite/templates/svc.yaml
  stable/ignite/templates/wal-storage-class.yaml
  stable/ignite/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#9870 Features/kong ingress controller custom ingress class
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/templates/controller-deployment.yaml
  stable/kong/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9864 [stable/inbucket] fix labels
  stable/inbucket/Chart.yaml
  stable/inbucket/templates/configmap.yaml
  stable/inbucket/templates/deployment.yaml
  stable/inbucket/templates/ingress.yaml
  stable/inbucket/templates/service.yaml
  stable/inbucket/templates/tests/inbucket-config-test.yaml
  stable/inbucket/templates/tests/inbucket-test.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#9863 [stable/fluent-bit] Fix bad space for timeKeep
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/templates/config.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#9878 [stable/fluentd-elasticsearch] fix pullPolicy variable in daemonset
  stable/fluentd-elasticsearch/Chart.yaml
  stable/fluentd-elasticsearch/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9833 Add configurable `podAnnotations` to unifi chart
  stable/unifi/Chart.yaml
  stable/unifi/README.md
  stable/unifi/templates/deployment.yaml
  stable/unifi/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9867 deprecate acs-engine autoscaler as it is no longer maintained
  stable/acs-engine-autoscaler/Chart.yaml
  stable/acs-engine-autoscaler/README.md
  stable/acs-engine-autoscaler/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9840 Fixed webhook and support multiple instances of the operator in the same cluster
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/README.md
  incubator/sparkoperator/templates/spark-namespace.yaml
  incubator/sparkoperator/templates/spark-operator-deployment.yaml
  incubator/sparkoperator/templates/spark-operator-rbac.yaml
  incubator/sparkoperator/templates/webhook-cleanup-job.yaml
  incubator/sparkoperator/templates/webhook-init-job.yaml
  incubator/sparkoperator/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#9879 upgrade grafana
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#8311 [stable/schema-registry-ui] Update README to reflect values.txt
  stable/schema-registry-ui/Chart.yaml
  stable/schema-registry-ui/README.md
Labels: Contribution Allowed, approved, lgtm, lifecycle/stale, ok-to-test, size/S

#9571 [stable/parse] Adapt Chart to non-root container
  stable/parse/Chart.yaml
  stable/parse/README.md
  stable/parse/templates/dashboard-deployment.yaml
  stable/parse/templates/server-deployment.yaml
  stable/parse/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#9887 [stable/parse] Revert pullPolicy to 'IfNotPresent'
  stable/parse/Chart.yaml
  stable/parse/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9759 Corrected DAG persistence configuration key names
  stable/airflow/Chart.yaml
  stable/airflow/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9845 [incubator/schema-registry] update image to 5.0.1
  incubator/schema-registry/Chart.yaml
  incubator/schema-registry/README.md
  incubator/schema-registry/requirements.lock
  incubator/schema-registry/requirements.yaml
  incubator/schema-registry/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9902 Corrected service DNS name
  stable/minio/Chart.yaml
  stable/minio/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, size/XS

#9907 [stable/mongodb-replicaset] Fix tests for cluster with auth
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/templates/tests/mongodb-up-test-pod.yaml
  stable/mongodb-replicaset/tests/mongodb-up-test.sh
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#9901 Exposed more config options
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/README.md
  incubator/sparkoperator/templates/spark-operator-deployment.yaml
  incubator/sparkoperator/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#9852 Update Minio image to latest release and add upgrade strategies
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/templates/deployment.yaml
  stable/minio/templates/statefulset.yaml
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#9917 [stable/postgresql] Remove extra lines in secrets.yaml
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/secrets.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9912 upgrade to kube-ops-view 0.9. Uses metrics api instead of heapster
  stable/kube-ops-view/Chart.yaml
  stable/kube-ops-view/templates/clusterrole.yaml
  stable/kube-ops-view/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#9919 [stable/chaoskube] Add pod annotations
  stable/chaoskube/Chart.yaml
  stable/chaoskube/README.md
  stable/chaoskube/templates/deployment.yaml
  stable/chaoskube/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9929 [stable/cerebro] template initimage
  stable/cerebro/Chart.yaml
  stable/cerebro/README.md
  stable/cerebro/templates/deployment.yaml
  stable/cerebro/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#9827 upgrade fluent-bit
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#9789 [stable/kube-ops-view] Support affinity
  stable/kube-ops-view/Chart.yaml
  stable/kube-ops-view/templates/deployment.yaml
  stable/kube-ops-view/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#9920 [stable/concourse] bump concourse to 4.2.2
  stable/concourse/Chart.yaml
  stable/concourse/README.md
  stable/concourse/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#9921 [stable/dex] bump dex to 2.13.0
  stable/dex/Chart.yaml
  stable/dex/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#9922 [incubator/schema-registry] improved fullname allowing overrides
  incubator/schema-registry/Chart.yaml
  incubator/schema-registry/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9851 Zeppelin: add Ingress and nodeSelector
  stable/zeppelin/Chart.yaml
  stable/zeppelin/README.md
  stable/zeppelin/templates/deployment.yaml
  stable/zeppelin/templates/ingress.yaml
  stable/zeppelin/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#9923 [stable/chartmuseum] bump chartmuseum to v0.8.0
  stable/chartmuseum/Chart.yaml
  stable/chartmuseum/README.md
  stable/chartmuseum/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#9924 [stable/coscale] bump coscale to 3.16.0
  stable/coscale/Chart.yaml
  stable/coscale/README.md
  stable/coscale/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#9926 [stable/dask] bump dask to 1.0.0
  stable/dask/Chart.yaml
  stable/dask/README.md
  stable/dask/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#9931 [stable/factorio] bump factorio to 0.15.39
  stable/factorio/Chart.yaml
  stable/factorio/README.md
  stable/factorio/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#9933 [stable/weave-scope] bump weave-scope to 1.10.1
  stable/weave-scope/Chart.yaml
  stable/weave-scope/README.md
  stable/weave-scope/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#9709 [mongodb/replicaset] Fix to PR-8729
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/templates/mongodb-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9011 [stable/kubernetes-dashboard] #7516 Allow HTTP connection
  stable/kubernetes-dashboard/Chart.yaml
  stable/kubernetes-dashboard/README.md
  stable/kubernetes-dashboard/templates/NOTES.txt
  stable/kubernetes-dashboard/templates/deployment.yaml
  stable/kubernetes-dashboard/templates/svc.yaml
  stable/kubernetes-dashboard/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#9224 [stable/rabbitmq-ha] Fix the statefulset when persistent volume is disabled
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9911 Added ability to configure daemonset update strategy
  incubator/fluentd-cloudwatch/Chart.yaml
  incubator/fluentd-cloudwatch/README.md
  incubator/fluentd-cloudwatch/templates/daemonset.yaml
  incubator/fluentd-cloudwatch/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9882 Add service annotations for prometheus-consul-exporter
  stable/prometheus-consul-exporter/Chart.yaml
  stable/prometheus-consul-exporter/templates/service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9889 [stable/metallb] Update readme with correct values format
  stable/metallb/Chart.yaml
  stable/metallb/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9891 Increase the initialDelaySeconds to 180 seconds
  incubator/gogs/Chart.yaml
  incubator/gogs/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9915 JENKINS: update readme to indicate the correct image that is used by default
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9930 [stable/express-gateway] bump express-gateway to v1.13.0
  stable/express-gateway/Chart.yaml
  stable/express-gateway/README.md
  stable/express-gateway/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#9935 [stable/verdaccio] bump verdaccio to 3.10.0
  stable/verdaccio/Chart.yaml
  stable/verdaccio/README.md
  stable/verdaccio/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#9945 updating images' tags and support org verification toggle
  stable/sonatype-nexus/Chart.yaml
  stable/sonatype-nexus/README.md
  stable/sonatype-nexus/templates/deployment-statefulset.yaml
  stable/sonatype-nexus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9943 CockroachDB: allow init job to connect with network policies
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/templates/cluster-init.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#9937 [stable/metricbeat] fix extraVolumes usage in deployment.yaml
  stable/metricbeat/Chart.yaml
  stable/metricbeat/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#8561 nginx-ingress - Support labels on the metrics service
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-metrics-service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9311 [stable/rabbitmq-ha] Ease the addition/removal of plugins
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/templates/configmap.yaml
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9836 [stable/superset] WIP: Refactoring, additional configs, secure secrets, versionbump
  stable/superset/Chart.yaml
  stable/superset/README.md
  stable/superset/templates/NOTES.txt
  stable/superset/templates/_helpers.tpl
  stable/superset/templates/configmap.yaml
  stable/superset/templates/deployment.yaml
  stable/superset/templates/ingress.yaml
  stable/superset/templates/pvc.yaml
  stable/superset/templates/secret.yaml
  stable/superset/templates/svc.yaml
  stable/superset/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#9960 [stable/mongodb] Add affinities to Statefulsets
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/statefulset-arbiter-rs.yaml
  stable/mongodb/templates/statefulset-primary-rs.yaml
  stable/mongodb/templates/statefulset-secondary-rs.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9222 [stable/rabbitmq-ha] Remove readOnly flag from the config volume
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9966 Allow to override probes, make agent probe less strict
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/cluster-agent-deployment.yaml
  stable/datadog/templates/daemonset.yaml
  stable/datadog/templates/deployment.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#9798 [stable/postgresql] Corrected template notes
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9969 [stable/mariadb] Avoid creating a Deployment for a test client to check connectivity with MariaDB
  stable/mariadb/Chart.yaml
  stable/mariadb/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, size/XS

#9972 [stable/mongodb] Avoid creating a Deployment for a test client to check connectivity with MongoDB
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, size/XS

#9952 [stable/postgresql] When persistence is disabled the empty volume gets added in the wrong spot
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9971 [stable/redis] Avoid creating a Deployment for a test client to check connectivity with Redis
  stable/redis/Chart.yaml
  stable/redis/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9981 [stable/kubewatch] Change logo url
  stable/kubewatch/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9529 [stable/dask] Tolerations for worker deployment
  stable/dask/Chart.yaml
  stable/dask/templates/dask-worker-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#9968 [incubator/jaeger] Adding cassandra latest chart and version 3.11.3
  incubator/jaeger/Chart.yaml
  incubator/jaeger/README.md
  incubator/jaeger/requirements.yaml
  incubator/jaeger/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#6776 [stable\mongodb-replicaset] Metrics logic fixes, Update API version
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/README.md
  stable/mongodb-replicaset/templates/mongodb-metrics-secret.yaml
  stable/mongodb-replicaset/templates/mongodb-statefulset.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#9962 [stable/grafana] Enable extra volume mounts (#9961)
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/deployment.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#9873 [stable/gocd] extra volume mounts without persistence
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/templates/gocd-agent-deployment.yaml
  stable/gocd/templates/gocd-server-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#9735 Agentserviceaccounts
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/README.md
  stable/gocd/templates/_helpers.tpl
  stable/gocd/templates/configmap.yaml
  stable/gocd/templates/gocd-agent-deployment.yaml
  stable/gocd/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#9990 This commit fixes #9954 by removing invalid namespace field
  stable/kong/Chart.yaml
  stable/kong/templates/controller-rbac-role-binding.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9982 [stable/parse] Change logo url
  stable/parse/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9994 Added the externalTrafficPolicy option
  incubator/haproxy-ingress/Chart.yaml
  incubator/haproxy-ingress/README.md
  incubator/haproxy-ingress/templates/controller-service.yaml
  incubator/haproxy-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10017 upgrade grafana
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#6217 fluent-bit: allow use of hostNetwork
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/daemonset.yaml
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, cncf-cla: yes, lgtm, size/S

#9305 Upgrade fluentd-kubernetes-sumologic
  stable/sumologic-fluentd/Chart.yaml
  stable/sumologic-fluentd/templates/_helpers.tpl
  stable/sumologic-fluentd/templates/daemonset.yaml
  stable/sumologic-fluentd/templates/secrets.yaml
  stable/sumologic-fluentd/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#8138 [stable/percona-xtradb-cluster] Fixing random pod names in tests
  stable/percona-xtradb-cluster/Chart.yaml
  stable/percona-xtradb-cluster/templates/tests/pxc-test.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#8960 Add extraPorts option (#8945)
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/daemonset.yaml
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9986 Parameterize all images for mysql chart
  stable/mysql/Chart.yaml
  stable/mysql/README.md
  stable/mysql/templates/deployment.yaml
  stable/mysql/templates/tests/test.yaml
  stable/mysql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10022 [stable/centrifugo] bump centrifugo to v2.0.2
  stable/centrifugo/Chart.yaml
  stable/centrifugo/templates/NOTES.txt
  stable/centrifugo/templates/configmap.yaml
  stable/centrifugo/templates/deployment.yaml
  stable/centrifugo/templates/secret.yaml
  stable/centrifugo/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#9764 add initial chart for helm-exporter
  stable/helm-exporter/.helmignore
  stable/helm-exporter/Chart.yaml
  stable/helm-exporter/OWNERS
  stable/helm-exporter/README.md
  stable/helm-exporter/templates/NOTES.txt
  stable/helm-exporter/templates/_helpers.tpl
  stable/helm-exporter/templates/deployment.yaml
  stable/helm-exporter/templates/service.yaml
  stable/helm-exporter/templates/serviceaccount.yaml
  stable/helm-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#9955 adding kuberhealthy
  stable/kuberhealthy/Chart.yaml
  stable/kuberhealthy/NOTES.txt
  stable/kuberhealthy/OWNERS
  stable/kuberhealthy/README.md
  stable/kuberhealthy/templates/_helpers.tpl
  stable/kuberhealthy/templates/clusterrole.yaml
  stable/kuberhealthy/templates/clusterrolebinding.yaml
  stable/kuberhealthy/templates/configmap.yaml
  stable/kuberhealthy/templates/customresourcedefinition.yaml
  stable/kuberhealthy/templates/deployment.yaml
  stable/kuberhealthy/templates/poddisruptionbudget.yaml
  stable/kuberhealthy/templates/role.yaml
  stable/kuberhealthy/templates/rolebinding.yaml
  stable/kuberhealthy/templates/service.yaml
  stable/kuberhealthy/templates/serviceaccount.yaml
  stable/kuberhealthy/templates/servicemonitor.yaml
  stable/kuberhealthy/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#9647 [stable/prometheus-operator] Update to v0.26.0, address setting empty selectors
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/templates/prometheus/prometheus.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#9803 Unify labels v2
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/alertmanager-networkpolicy.yaml
  stable/prometheus/templates/alertmanager-service-headless.yaml
  stable/prometheus/templates/alertmanager-statefulset.yaml
  stable/prometheus/templates/kube-state-metrics-networkpolicy.yaml
  stable/prometheus/templates/server-networkpolicy.yaml
  stable/prometheus/templates/server-service-headless.yaml
  stable/prometheus/templates/server-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#10026 [mongodb-replicaset] replace MONGODB_URL with --mongodb.uri
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/templates/mongodb-statefulset.yaml
  stable/mongodb-replicaset/tests/mongodb-up-test.sh
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10034 grafana: match label selectors to pod template
  stable/grafana/Chart.yaml
  stable/grafana/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10031 [stable/kong] specify ingress class for Ingress Controller
  stable/kong/Chart.yaml
  stable/kong/templates/controller-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS
