Repository helm/charts, pull requests merged in 2018-06, with the labels that each got.

#5846 [datadog] make the agent pod part of the Guaranteed QoS class
  stable/datadog/Chart.yaml
  stable/datadog/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5613 [stable/datadog] Support node selector for daemon set
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/daemonset.yaml
  stable/datadog/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5859 Chartmuseum svc account
  stable/chartmuseum/Chart.yaml
  stable/chartmuseum/README.md
  stable/chartmuseum/templates/_helpers.tpl
  stable/chartmuseum/templates/deployment.yaml
  stable/chartmuseum/templates/serviceaccount.yaml
  stable/chartmuseum/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5390 Setup eventrouter chart
  stable/eventrouter/.helmignore
  stable/eventrouter/Chart.yaml
  stable/eventrouter/OWNERS
  stable/eventrouter/README.md
  stable/eventrouter/templates/NOTES.txt
  stable/eventrouter/templates/_helpers.tpl
  stable/eventrouter/templates/clusterrole.yaml
  stable/eventrouter/templates/clusterrolebinding.yaml
  stable/eventrouter/templates/configmap.yaml
  stable/eventrouter/templates/deployment.yaml
  stable/eventrouter/templates/serviceaccount.yaml
  stable/eventrouter/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5703 [fluentd-elasticsearch] Add ability to setup livenessProbe on fluentd
  incubator/fluentd-elasticsearch/Chart.yaml
  incubator/fluentd-elasticsearch/README.md
  incubator/fluentd-elasticsearch/templates/daemonset.yaml
  incubator/fluentd-elasticsearch/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4401 rabbitmq-ha add prometheus operator stats and alerts
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/templates/NOTES.txt
  stable/rabbitmq-ha/templates/_helpers.tpl
  stable/rabbitmq-ha/templates/alerts.yaml
  stable/rabbitmq-ha/templates/configmap.yaml
  stable/rabbitmq-ha/templates/secret.yaml
  stable/rabbitmq-ha/templates/service.yaml
  stable/rabbitmq-ha/templates/servicemonitor.yaml
  stable/rabbitmq-ha/templates/statefulset.yaml
  stable/rabbitmq-ha/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5800 [stable/kibana] Make serviceAccountName configurable
  stable/kibana/Chart.yaml
  stable/kibana/README.md
  stable/kibana/templates/deployment.yaml
  stable/kibana/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5603 Add Keycloak Proxy chart
  incubator/keycloak-proxy/.helmignore
  incubator/keycloak-proxy/Chart.yaml
  incubator/keycloak-proxy/README.md
  incubator/keycloak-proxy/templates/NOTES.txt
  incubator/keycloak-proxy/templates/_helpers.tpl
  incubator/keycloak-proxy/templates/configmap.yaml
  incubator/keycloak-proxy/templates/deployment.yaml
  incubator/keycloak-proxy/templates/ingress.yaml
  incubator/keycloak-proxy/templates/service.yaml
  incubator/keycloak-proxy/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5852 [stable/grafana] Relax user restrictions to work around non-numeric 'grafana' user
  stable/grafana/Chart.yaml
  stable/grafana/templates/podsecuritypolicy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5759 [stable/sumologic-fluentd] Upgrade to latest image and expose new configuration options in new image.
  stable/sumologic-fluentd/Chart.yaml
  stable/sumologic-fluentd/README.md
  stable/sumologic-fluentd/templates/daemonset.yaml
  stable/sumologic-fluentd/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5779 Enhance horovod
  stable/horovod/Chart.yaml
  stable/horovod/README.md
  stable/horovod/templates/config.yaml
  stable/horovod/templates/job.yaml
  stable/horovod/templates/statefulset.yaml
  stable/horovod/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5827 refactor image repo setting of gogs
  incubator/gogs/Chart.yaml
  incubator/gogs/README.md
  incubator/gogs/templates/deployment.yaml
  incubator/gogs/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5745 [stable/superset] Add env vars from values or secret
  stable/superset/Chart.yaml
  stable/superset/README.md
  stable/superset/templates/deployment.yaml
  stable/superset/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5830 [stable/gocd] Update GoCD app version to 18.5.0
  stable/gocd/.helmignore
  stable/gocd/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5584 Add keycloak probes config
  incubator/keycloak/Chart.yaml
  incubator/keycloak/README.md
  incubator/keycloak/templates/statefulset.yaml
  incubator/keycloak/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5886 [incubator/keycloak] Fix probes section in readme
  incubator/keycloak/Chart.yaml
  incubator/keycloak/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#5876 [stable/redis] Allow alternate scheduler
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/templates/redis-master-statefulset.yaml
  stable/redis/templates/redis-slave-deployment.yaml
  stable/redis/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5855 fix repository name and version up to 6.2.1
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5872 [stable/sonatype-nexus] Fix conditional for tls to line up with docs
  stable/sonatype-nexus/Chart.yaml
  stable/sonatype-nexus/templates/ingress.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5890 [stable/phpmyadmin] Use string instead of int in the tag
  stable/phpmyadmin/Chart.yaml
  stable/phpmyadmin/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5893 [stable/mongodb] Use string instead of int in the tag
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5894 [stable/mariadb] Use string instead of int in the tag
  stable/mariadb/Chart.yaml
  stable/mariadb/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5892 [stable/redis] Use string instead of int in the tag
  stable/redis/Chart.yaml
  stable/redis/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5920 Add juan131 as owner
  stable/dokuwiki/Chart.yaml
  stable/dokuwiki/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5921 Add juan131 as owner
  stable/drupal/Chart.yaml
  stable/drupal/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5923 Add juan131 as owner
  stable/jasperreports/Chart.yaml
  stable/jasperreports/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5924 Add juan131 as owner
  stable/mariadb/Chart.yaml
  stable/mariadb/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5925 Add juan131 as owner
  stable/magento/Chart.yaml
  stable/magento/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5926 Add juan131 as owner
  stable/joomla/Chart.yaml
  stable/joomla/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5927 Add juan131 as owner
  stable/mediawiki/Chart.yaml
  stable/mediawiki/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5922 Add juan131 as owner
  stable/ghost/Chart.yaml
  stable/ghost/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5928 Add juan131 as owner
  stable/mongodb/Chart.yaml
  stable/mongodb/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5929 Add juan131 as owner
  stable/moodle/Chart.yaml
  stable/moodle/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5930 Add juan131 as owner
  stable/odoo/Chart.yaml
  stable/odoo/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5931 Add juan131 as owner
  stable/opencart/Chart.yaml
  stable/opencart/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5932 Add juan131 as owner
  stable/orangehrm/Chart.yaml
  stable/orangehrm/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5933 Add juan131 as owner
  stable/osclass/Chart.yaml
  stable/osclass/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5934 Add juan131 as owner
  stable/owncloud/Chart.yaml
  stable/owncloud/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5935 Add juan131 as owner
  stable/parse/Chart.yaml
  stable/parse/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5936 Add juan131 as owner
  stable/phabricator/Chart.yaml
  stable/phabricator/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5937 Add juan131 as owner
  stable/phpbb/Chart.yaml
  stable/phpbb/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5938 Add juan131 as owner
  stable/prestashop/Chart.yaml
  stable/prestashop/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5939 Add juan131 as owner
  stable/phpmyadmin/Chart.yaml
  stable/phpmyadmin/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5940 Add juan131 as owner
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5941 Add juan131 as owner
  stable/redis/Chart.yaml
  stable/redis/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5942 Add juan131 as owner
  stable/redmine/Chart.yaml
  stable/redmine/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5943 Add juan131 as owner
  stable/suitecrm/Chart.yaml
  stable/suitecrm/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5944 Add juan131 as owner
  stable/testlink/Chart.yaml
  stable/testlink/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5945 Add juan131 as owner
  stable/wordpress/Chart.yaml
  stable/wordpress/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5946 Typo fix: verion -> version
  stable/sonatype-nexus/Chart.yaml
  stable/sonatype-nexus/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5916 [incubator/kafka] Fix heapOptions template reference
  incubator/kafka/Chart.yaml
  incubator/kafka/templates/statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5616 [stable/traefik] Option to specify minimum TLS version for https entrypoint
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/configmap.yaml
  stable/traefik/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5857 [stable/prometheus] #5856 Set 'global' to a dictionary
  stable/prometheus/Chart.yaml
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5906 Fix typo
  stable/sonatype-nexus/Chart.yaml
  stable/sonatype-nexus/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5569 [fluentd-elasticsearch] add ability to create a service
  incubator/fluentd-elasticsearch/Chart.yaml
  incubator/fluentd-elasticsearch/README.md
  incubator/fluentd-elasticsearch/templates/daemonset.yaml
  incubator/fluentd-elasticsearch/templates/service.yaml
  incubator/fluentd-elasticsearch/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5848 Mediawiki - Several Improvements
  stable/mediawiki/Chart.yaml
  stable/mediawiki/README.md
  stable/mediawiki/requirements.lock
  stable/mediawiki/requirements.yaml
  stable/mediawiki/templates/NOTES.txt
  stable/mediawiki/templates/_helpers.tpl
  stable/mediawiki/templates/apache-pvc.yaml
  stable/mediawiki/templates/deployment.yaml
  stable/mediawiki/templates/externaldb-secrets.yaml
  stable/mediawiki/templates/ingress.yaml
  stable/mediawiki/templates/mediawiki-pvc.yaml
  stable/mediawiki/templates/secrets.yaml
  stable/mediawiki/templates/svc.yaml
  stable/mediawiki/templates/tls-secrets.yaml
  stable/mediawiki/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5847 [CI] Refactor repo sync
  test/repo-sync.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#5231 Use factored out testing lib
  .circleci/config.yml
  .gitignore
  test/.dockerignore
  test/.testenv
  test/Dockerfile
  test/README.md
  test/build.sh
  test/changed.sh
  test/circle/README.md
  test/circle/install.sh
  test/circle/lint.sh
  test/circle/lintconf.yml
  test/circle/yaml-schemas/Chart.yaml
  test/e2e.sh
  test/helm-test-e2e.sh
  test/pr-review.sh
  test/publish-docker.sh
  test/semvercompare.sh
  test/verify-release.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL

#5887 [stable/keycloak] Add option to specify extra init containers
  stable/keycloak/Chart.yaml
  stable/keycloak/README.md
  stable/keycloak/templates/statefulset.yaml
  stable/keycloak/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5843 [stable/mssql-linux] Fix transaction log claim
  stable/mssql-linux/Chart.yaml
  stable/mssql-linux/README.md
  stable/mssql-linux/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5785 [incubator/fluentd-elasticsearch] Extended Readme and added OWNERS file
  incubator/fluentd-elasticsearch/Chart.yaml
  incubator/fluentd-elasticsearch/OWNERS
  incubator/fluentd-elasticsearch/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#5792 use latest grafana release
  stable/grafana/Chart.yaml
  stable/grafana/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5694 [incubator/vault] Add loadBalancerSourceRanges for service type LoadBalancer
  incubator/vault/Chart.yaml
  incubator/vault/README.md
  incubator/vault/templates/service.yaml
  incubator/vault/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5419 [stable/kubernetes-dashboard] add configurable replicaCount
  stable/kubernetes-dashboard/Chart.yaml
  stable/kubernetes-dashboard/README.md
  stable/kubernetes-dashboard/templates/deployment.yaml
  stable/kubernetes-dashboard/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5411 [stable/traefik] Add extrnalIP to values
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5187 Add distributed tensorflow
  stable/distributed-tensorflow/.helmignore
  stable/distributed-tensorflow/Chart.yaml
  stable/distributed-tensorflow/README.md
  stable/distributed-tensorflow/distributed-tf.jpg
  stable/distributed-tensorflow/templates/NOTES.txt
  stable/distributed-tensorflow/templates/_helpers.tpl
  stable/distributed-tensorflow/templates/config.yaml
  stable/distributed-tensorflow/templates/service-ps.yaml
  stable/distributed-tensorflow/templates/service-worker.yaml
  stable/distributed-tensorflow/templates/statefulset-ps.yaml
  stable/distributed-tensorflow/templates/statefulset-worker.yaml
  stable/distributed-tensorflow/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5960 Add "persistence.existingClaim" to documented options
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5979 [CI] Fix repo sync
  test/repo-sync.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5980 [CI] Fix url for indexing
  test/repo-sync.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5981 [CI] Use repo url in sync
  test/repo-sync.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5969 [stable/prometheus] Update Pushgateway image tag
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/pushgateway-deployment.yaml
  stable/prometheus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5383 [stable/datadog] add configurable affinity and tolerations
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/deployment.yaml
  stable/datadog/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4928 [stable/datadog] Add nodeSelector and affinity values for daemonset
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/daemonset.yaml
  stable/datadog/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5967 typo fix permision to permission
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/templates/statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5961 [incubator/kubeless] Adding Kafka Trigger
  incubator/kubeless/Chart.yaml
  incubator/kubeless/README.md
  incubator/kubeless/templates/kafka-controller-cluster-role-binding.yaml
  incubator/kubeless/templates/kafka-controller-cluster-role.yaml
  incubator/kubeless/templates/kafka-controller-deployment.yaml
  incubator/kubeless/templates/kafka-trigger-type-crd.yaml
  incubator/kubeless/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5952 [incubator/sentry-kubernetes] Add release/environment values
  incubator/sentry-kubernetes/Chart.yaml
  incubator/sentry-kubernetes/README.md
  incubator/sentry-kubernetes/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5702 [stable/hubot] New Hubot chart
  stable/hubot/Chart.yaml
  stable/hubot/README.md
  stable/hubot/templates/NOTES.txt
  stable/hubot/templates/_helpers.tpl
  stable/hubot/templates/configmap-scripts.yaml
  stable/hubot/templates/configmap.yaml
  stable/hubot/templates/deployment.yaml
  stable/hubot/templates/ingress.yaml
  stable/hubot/templates/secret.yaml
  stable/hubot/templates/service.yaml
  stable/hubot/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5801 [stable/nginx-ingress] Support initContainers
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-daemonset.yaml
  stable/nginx-ingress/templates/controller-deployment.yaml
  stable/nginx-ingress/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5565 Add haproxy ingress controller
  incubator/haproxy-ingress/.helmignore
  incubator/haproxy-ingress/Chart.yaml
  incubator/haproxy-ingress/OWNERS
  incubator/haproxy-ingress/README.md
  incubator/haproxy-ingress/templates/NOTES.txt
  incubator/haproxy-ingress/templates/_helpers.tpl
  incubator/haproxy-ingress/templates/clusterrole.yaml
  incubator/haproxy-ingress/templates/clusterrolebinding.yaml
  incubator/haproxy-ingress/templates/controller-daemonset.yaml
  incubator/haproxy-ingress/templates/controller-service.yaml
  incubator/haproxy-ingress/templates/default-backend-deployment.yaml
  incubator/haproxy-ingress/templates/default-backend-service.yaml
  incubator/haproxy-ingress/templates/headers.configmap.yaml
  incubator/haproxy-ingress/templates/role.yaml
  incubator/haproxy-ingress/templates/rolebinding.yaml
  incubator/haproxy-ingress/templates/serviceaccount.yaml
  incubator/haproxy-ingress/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#5760 [stable/locust] Added config option for imagePullSecrets in locust chart
  stable/locust/Chart.yaml
  stable/locust/README.md
  stable/locust/templates/master-deploy.yaml
  stable/locust/templates/worker-deploy.yaml
  stable/locust/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5131 [stable/mysql] Add prometheus metrics
  stable/mysql/Chart.yaml
  stable/mysql/README.md
  stable/mysql/templates/deployment.yaml
  stable/mysql/templates/svc.yaml
  stable/mysql/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2820 Added OpenLDAP chart
  stable/openldap/.helmignore
  stable/openldap/Chart.yaml
  stable/openldap/README.md
  stable/openldap/templates/NOTES.txt
  stable/openldap/templates/_helpers.tpl
  stable/openldap/templates/openldap-customldif-configmap.yaml
  stable/openldap/templates/openldap-deployment.yaml
  stable/openldap/templates/openldap-env-configmap.yaml
  stable/openldap/templates/openldap-pvc.yaml
  stable/openldap/templates/openldap-secret.yaml
  stable/openldap/templates/openldap-service.yaml
  stable/openldap/templates/tests/openldap-test-runner.yaml
  stable/openldap/templates/tests/openldap-tests.yaml
  stable/openldap/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5511 Fix Fluentd hanging https://github.com/fluent/fluentd/issues/1630
  incubator/fluentd-cloudwatch/Chart.yaml
  incubator/fluentd-cloudwatch/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4675 Add documentation of the controller.daemonset.useHostPort option
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5557 [stable/newrelic-infrastructure] Retain support for Kubernetes 1.8
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/templates/daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5829 [stable/docker-registry] fix values.yaml imagePullSecrets example
  stable/docker-registry/Chart.yaml
  stable/docker-registry/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6019 [stable/redis] references correct slave service annotation from values.yaml
  stable/redis/Chart.yaml
  stable/redis/templates/redis-slave-svc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5950 [stable/keycloak] option to set realm using start param
  stable/keycloak/Chart.yaml
  stable/keycloak/README.md
  stable/keycloak/templates/configmap.yaml
  stable/keycloak/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6033 [stable/jasperreports] Set dependencies to latest version
  stable/jasperreports/Chart.yaml
  stable/jasperreports/README.md
  stable/jasperreports/requirements.lock
  stable/jasperreports/requirements.yaml
  stable/jasperreports/templates/deployment.yaml
  stable/jasperreports/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6028 [stable/opencart] Move dependencies to latest version
  stable/opencart/Chart.yaml
  stable/opencart/README.md
  stable/opencart/requirements.lock
  stable/opencart/requirements.yaml
  stable/opencart/templates/deployment.yaml
  stable/opencart/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6029 [stable/magento] Set dependencies to latest version
  stable/magento/Chart.yaml
  stable/magento/README.md
  stable/magento/requirements.lock
  stable/magento/requirements.yaml
  stable/magento/templates/deployment.yaml
  stable/magento/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6032 [stable/osclass] Set dependencies to latest version
  stable/osclass/Chart.yaml
  stable/osclass/README.md
  stable/osclass/requirements.lock
  stable/osclass/requirements.yaml
  stable/osclass/templates/deployment.yaml
  stable/osclass/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5898 upgrade Selenium version to 3.12.0
  stable/selenium/Chart.yaml
  stable/selenium/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5607 adding annotations
  stable/prometheus-postgres-exporter/Chart.yaml
  stable/prometheus-postgres-exporter/README.md
  stable/prometheus-postgres-exporter/templates/deployment.yaml
  stable/prometheus-postgres-exporter/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5787 [incubator/drone] Custom command and args to Drone DinD
  incubator/drone/Chart.yaml
  incubator/drone/README.md
  incubator/drone/templates/deployment-agent.yaml
  incubator/drone/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5806 Fix debug mode cannot be enabled when logLevel is specified
  stable/traefik/Chart.yaml
  stable/traefik/templates/configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5783 [stable/mysql] Add existing secret config options
  stable/mysql/Chart.yaml
  stable/mysql/README.md
  stable/mysql/templates/NOTES.txt
  stable/mysql/templates/_helpers.tpl
  stable/mysql/templates/deployment.yaml
  stable/mysql/templates/secrets.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5910 [incubator/elasticsearch] Adding support for nodeSelector
  incubator/elasticsearch/Chart.yaml
  incubator/elasticsearch/README.md
  incubator/elasticsearch/templates/client-deployment.yaml
  incubator/elasticsearch/templates/data-statefulset.yaml
  incubator/elasticsearch/templates/master-statefulset.yaml
  incubator/elasticsearch/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5369 Import grafana dashboards and datasources from cluster
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/clusterrole.yaml
  stable/grafana/templates/clusterrolebinding.yaml
  stable/grafana/templates/configmap-dashboard-provider.yaml
  stable/grafana/templates/deployment.yaml
  stable/grafana/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5330 [stable/kiam] Add Helm chart for kiam
  stable/kiam/.helmignore
  stable/kiam/Chart.yaml
  stable/kiam/README.md
  stable/kiam/ci/test-values.yaml
  stable/kiam/templates/NOTES.txt
  stable/kiam/templates/_helpers.tpl
  stable/kiam/templates/agent-daemonset.yaml
  stable/kiam/templates/agent-secret.yaml
  stable/kiam/templates/agent-serviceaccount.yaml
  stable/kiam/templates/server-clusterrole.yaml
  stable/kiam/templates/server-clusterrolebinding.yaml
  stable/kiam/templates/server-daemonset.yaml
  stable/kiam/templates/server-secret.yaml
  stable/kiam/templates/server-service.yaml
  stable/kiam/templates/server-serviceaccount.yaml
  stable/kiam/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#5974 [incubator/vault] Add ability to define sidecar containers
  incubator/vault/Chart.yaml
  incubator/vault/README.md
  incubator/vault/templates/deployment.yaml
  incubator/vault/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6024 [stable/datadog] add nodePort value in datadog template
  stable/datadog/Chart.yaml
  stable/datadog/templates/service.yaml
  stable/datadog/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6068 [stable/gocd] Update GoCD app version to 18.6.0
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6031 [stable/suitecrm] Use latest dependencies
  stable/suitecrm/Chart.yaml
  stable/suitecrm/README.md
  stable/suitecrm/requirements.lock
  stable/suitecrm/requirements.yaml
  stable/suitecrm/templates/deployment.yaml
  stable/suitecrm/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6034 [stable/phpbb] Set dependencies to latest version
  stable/phpbb/Chart.yaml
  stable/phpbb/README.md
  stable/phpbb/requirements.lock
  stable/phpbb/requirements.yaml
  stable/phpbb/templates/deployment.yaml
  stable/phpbb/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6056 [stable/moodle] Set dependencies to the latest version
  stable/moodle/Chart.yaml
  stable/moodle/README.md
  stable/moodle/requirements.lock
  stable/moodle/requirements.yaml
  stable/moodle/templates/deployment.yaml
  stable/moodle/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6041 [stable/drupal] Set dependencies to the latest version
  stable/drupal/Chart.yaml
  stable/drupal/README.md
  stable/drupal/requirements.lock
  stable/drupal/requirements.yaml
  stable/drupal/templates/deployment.yaml
  stable/drupal/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6037 [stable/parse] Update dependencies to latest version
  stable/parse/Chart.yaml
  stable/parse/README.md
  stable/parse/requirements.lock
  stable/parse/requirements.yaml
  stable/parse/templates/server-deployment.yaml
  stable/parse/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6046 [stable/prestashop] Set dependencies to the latest version
  stable/prestashop/Chart.yaml
  stable/prestashop/README.md
  stable/prestashop/requirements.lock
  stable/prestashop/requirements.yaml
  stable/prestashop/templates/deployment.yaml
  stable/prestashop/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6047 [stable/owncloud] Set dependencies to the latest version
  stable/owncloud/Chart.yaml
  stable/owncloud/README.md
  stable/owncloud/requirements.lock
  stable/owncloud/requirements.yaml
  stable/owncloud/templates/deployment.yaml
  stable/owncloud/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6051 [stable/testlink] Set dependencies to the latest version
  stable/testlink/Chart.yaml
  stable/testlink/README.md
  stable/testlink/requirements.lock
  stable/testlink/requirements.yaml
  stable/testlink/templates/deployment.yaml
  stable/testlink/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6052 [stable/odoo] Set dependencies to the latest version
  stable/odoo/Chart.yaml
  stable/odoo/requirements.lock
  stable/odoo/requirements.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6053 [stable/orangehrm] Set dependencies to the latest version
  stable/orangehrm/Chart.yaml
  stable/orangehrm/README.md
  stable/orangehrm/requirements.lock
  stable/orangehrm/requirements.yaml
  stable/orangehrm/templates/deployment.yaml
  stable/orangehrm/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6054 [stable/redmine] Set dependencies to the latest version
  stable/redmine/Chart.yaml
  stable/redmine/README.md
  stable/redmine/requirements.lock
  stable/redmine/requirements.yaml
  stable/redmine/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6059 [stable/jasperreports] Fix rootUser
  stable/jasperreports/Chart.yaml
  stable/jasperreports/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6060 [stable/opencart] Fix rootUser
  stable/opencart/Chart.yaml
  stable/opencart/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6061 [stable/magento] Fix rootUser
  stable/magento/Chart.yaml
  stable/magento/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6063 [stable/osclass] Fix rootUser in values.yaml
  stable/osclass/Chart.yaml
  stable/osclass/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6049 [stable/phabricator] Set dependencies to the latest version
  stable/phabricator/Chart.yaml
  stable/phabricator/README.md
  stable/phabricator/requirements.lock
  stable/phabricator/requirements.yaml
  stable/phabricator/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6075 [stable/ghost] Set dependencies to the latest version
  stable/ghost/Chart.yaml
  stable/ghost/README.md
  stable/ghost/requirements.lock
  stable/ghost/requirements.yaml
  stable/ghost/templates/deployment.yaml
  stable/ghost/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5822 Adding AWS ACM option to GoCD stable chart to allow SSL
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/README.md
  stable/gocd/templates/service.yaml
  stable/gocd/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6076 [stable/sonatype-nexus] Update image to 3.12.1
  stable/sonatype-nexus/Chart.yaml
  stable/sonatype-nexus/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6042 fix for #6039
  stable/sonarqube/Chart.yaml
  stable/sonarqube/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6084 update PROCESSES.md to clarify promotion process
  PROCESSES.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5871 [stable/kubewatch] - Use maintained bitnami image for kubewatch
  stable/kubewatch/Chart.yaml
  stable/kubewatch/OWNERS
  stable/kubewatch/README.md
  stable/kubewatch/templates/configmap.yaml
  stable/kubewatch/templates/deployment.yaml
  stable/kubewatch/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#6090 [stable/keycloak] Add option to configure sidecars and misc improvements
  stable/keycloak/Chart.yaml
  stable/keycloak/README.md
  stable/keycloak/templates/configmap.yaml
  stable/keycloak/templates/keycloak-secret.yaml
  stable/keycloak/templates/statefulset.yaml
  stable/keycloak/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#6092 [stable/mariadb] Fix configurable parameters
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#6074 [stable/wordpress] Set dependencies to latest version
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
  stable/wordpress/requirements.lock
  stable/wordpress/requirements.yaml
  stable/wordpress/templates/deployment.yaml
  stable/wordpress/templates/tests/test-mariadb-connection.yaml
  stable/wordpress/values-production.yaml
  stable/wordpress/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5971 [stable/redis] add RBAC
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/templates/_helpers.tpl
  stable/redis/templates/metrics-deployment.yaml
  stable/redis/templates/redis-master-statefulset.yaml
  stable/redis/templates/redis-role.yaml
  stable/redis/templates/redis-rolebinding.yaml
  stable/redis/templates/redis-serviceaccount.yaml
  stable/redis/templates/redis-slave-deployment.yaml
  stable/redis/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5824 [incubator/patroni] Correct default zookeeper host to be compatible with zk charts
  incubator/patroni/Chart.yaml
  incubator/patroni/templates/statefulset-patroni.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5631 Adding JFrog Distribution
  incubator/distribution/.helmignore
  incubator/distribution/Chart.yaml
  incubator/distribution/README.md
  incubator/distribution/ci/test-values.yaml
  incubator/distribution/requirements.lock
  incubator/distribution/requirements.yaml
  incubator/distribution/templates/NOTES.txt
  incubator/distribution/templates/_helpers.tpl
  incubator/distribution/templates/distribution-deployment.yaml
  incubator/distribution/templates/distribution-pvc.yaml
  incubator/distribution/templates/distribution-svc.yaml
  incubator/distribution/templates/distributor-deployment.yaml
  incubator/distribution/templates/distributor-pvc.yaml
  incubator/distribution/templates/distributor-token.yaml
  incubator/distribution/templates/mongo-connection-secret.yaml
  incubator/distribution/templates/redis-connection-secret.yaml
  incubator/distribution/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#5770 Kafka release name check
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
  incubator/kafka/templates/_helpers.tpl
  incubator/kafka/templates/statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5704 Split Jenkins readiness and liveness probe periods
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/jenkins-master-deployment.yaml
  stable/jenkins/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5919 cert-manager: fast-forward to upstream 36289cf0
  stable/cert-manager/Chart.yaml
  stable/cert-manager/README.md
  stable/cert-manager/templates/deployment.yaml
  stable/cert-manager/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5903 [stable/stolon] Fix issue with secret deletion during helm upgrade
  stable/stolon/Chart.yaml
  stable/stolon/README.md
  stable/stolon/ci/ci-values.yaml
  stable/stolon/templates/secret.yaml
  stable/stolon/templates/sentinel-deployment.yaml
  stable/stolon/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5649 [stable/artifactory] adding support for edge node and replicator
  stable/artifactory/Chart.yaml
  stable/artifactory/README.md
  stable/artifactory/requirements.lock
  stable/artifactory/requirements.yaml
  stable/artifactory/templates/NOTES.txt
  stable/artifactory/templates/artifactory-deployment.yaml
  stable/artifactory/templates/artifactory-secrets.yaml
  stable/artifactory/templates/artifactory-service.yaml
  stable/artifactory/templates/nginx-deployment.yaml
  stable/artifactory/templates/nginx-replicator-conf.yaml
  stable/artifactory/templates/nginx-service.yaml
  stable/artifactory/templates/replicator-configmap.yaml
  stable/artifactory/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3795 Adds helm chart for heptio/ark
  stable/ark/.helmignore
  stable/ark/Chart.yaml
  stable/ark/README.md
  stable/ark/templates/NOTES.txt
  stable/ark/templates/_helpers.tpl
  stable/ark/templates/backups.yaml
  stable/ark/templates/configmap.yaml
  stable/ark/templates/configs.yaml
  stable/ark/templates/deletebackuprequests.yaml
  stable/ark/templates/deployment.yaml
  stable/ark/templates/downloadrequests.yaml
  stable/ark/templates/hook-delete.yaml
  stable/ark/templates/hook-deploy.yaml
  stable/ark/templates/rbac.yaml
  stable/ark/templates/restores.yaml
  stable/ark/templates/schedules.yaml
  stable/ark/templates/secret.yaml
  stable/ark/templates/serviceaccount-hook.yaml
  stable/ark/templates/serviceaccount-server.yaml
  stable/ark/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#6104 Fixes error introduced by #6042
  stable/sonarqube/Chart.yaml
  stable/sonarqube/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5900 [stable/etcd-operator] Applied pre-install hooks to deployments
  stable/etcd-operator/Chart.yaml
  stable/etcd-operator/templates/backup-etcd-crd.yaml
  stable/etcd-operator/templates/backup-operator-deployment.yaml
  stable/etcd-operator/templates/etcd-cluster-crd.yaml
  stable/etcd-operator/templates/operator-deployment.yaml
  stable/etcd-operator/templates/restore-etcd-crd.yaml
  stable/etcd-operator/templates/restore-operator-deployment.yaml
  stable/etcd-operator/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6130 [stable/mongodb] - Fix probes configuration for standalone deployment
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/deployment-standalone.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5864 [stable/influxdb] Add delete-policy for set-auth
  stable/influxdb/Chart.yaml
  stable/influxdb/templates/post-install-set-auth.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5463 [incubator/kubernetes-vault] add RBAC support and enable more configuration
  incubator/kubernetes-vault/Chart.yaml
  incubator/kubernetes-vault/README.md
  incubator/kubernetes-vault/templates/_helpers.tpl
  incubator/kubernetes-vault/templates/config-map.yaml
  incubator/kubernetes-vault/templates/deployment.yaml
  incubator/kubernetes-vault/templates/rbac.yaml
  incubator/kubernetes-vault/templates/service-account.yaml
  incubator/kubernetes-vault/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5633 adding JFrog Xray
  incubator/xray/.helmignore
  incubator/xray/Chart.yaml
  incubator/xray/README.md
  incubator/xray/ci/test-values.yaml
  incubator/xray/requirements.lock
  incubator/xray/requirements.yaml
  incubator/xray/templates/NOTES.txt
  incubator/xray/templates/_helpers.tpl
  incubator/xray/templates/rabbitmq-ha-configmap.yaml
  incubator/xray/templates/xray-analysis-deployment.yaml
  incubator/xray/templates/xray-analysis-svc.yaml
  incubator/xray/templates/xray-indexer-deployment.yaml
  incubator/xray/templates/xray-indexer-svc.yaml
  incubator/xray/templates/xray-master-key.yaml
  incubator/xray/templates/xray-persist-deployment.yaml
  incubator/xray/templates/xray-persist-svc.yaml
  incubator/xray/templates/xray-server-deployment.yaml
  incubator/xray/templates/xray-server-svc.yaml
  incubator/xray/templates/xray-setup-conf.yaml
  incubator/xray/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#6146 fix scoping issue for serviceaccount. Fixes #6142
  stable/grafana/Chart.yaml
  stable/grafana/templates/clusterrolebinding.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5663 [incubator/elasticsearch] Using DNS discovery instead of kubernetes plugin
  incubator/elasticsearch/Chart.yaml
  incubator/elasticsearch/README.md
  incubator/elasticsearch/templates/client-deployment.yaml
  incubator/elasticsearch/templates/client-svc.yaml
  incubator/elasticsearch/templates/clusterrole.yaml
  incubator/elasticsearch/templates/clusterrolebinding.yaml
  incubator/elasticsearch/templates/configmap.yaml
  incubator/elasticsearch/templates/data-statefulset.yaml
  incubator/elasticsearch/templates/master-statefulset.yaml
  incubator/elasticsearch/templates/master-svc.yaml
  incubator/elasticsearch/templates/service-account.yaml
  incubator/elasticsearch/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5994 Add podAnnotations value for setting annotations on pods
  incubator/jaeger/Chart.yaml
  incubator/jaeger/README.md
  incubator/jaeger/templates/agent-ds.yaml
  incubator/jaeger/templates/collector-deploy.yaml
  incubator/jaeger/templates/query-deploy.yaml
  incubator/jaeger/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5970 [stable/openvpn] Configurable update strategy
  stable/openvpn/Chart.yaml
  stable/openvpn/README.md
  stable/openvpn/templates/openvpn-deployment.yaml
  stable/openvpn/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5990 [incubator/vaultingkube] Update vaultingkube version and add lables to metadata
  incubator/vaultingkube/Chart.yaml
  incubator/vaultingkube/templates/rbac.yaml
  incubator/vaultingkube/templates/serviceaccount.yaml
  incubator/vaultingkube/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5964 Grafana fix extraSecretMounts
  stable/grafana/Chart.yaml
  stable/grafana/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5989 [stable/openvpn] added ability to configure LoadBalancerSourceRanges
  stable/openvpn/Chart.yaml
  stable/openvpn/templates/openvpn-service.yaml
  stable/openvpn/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
