Repository helm/charts, pull requests merged in 2019-03, with the labels that each got.

#11438 [stable/atlantis] Add support for require-approval option to Atlantis chart.
  stable/atlantis/Chart.yaml
  stable/atlantis/README.md
  stable/atlantis/templates/statefulset.yaml
  stable/atlantis/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11212 [stable/minio] Document azuregatway.replicas, fix template conditional logic that ot…
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#11851 [stable/grafana] Allow to define GF admin user and admin password in …
  stable/grafana/Chart.yaml
  stable/grafana/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#11830 [stable/mongodb] Allow MongoDB to be configured with directoryPerDB option
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/templates/deployment-standalone.yaml
  stable/mongodb/templates/statefulset-arbiter-rs.yaml
  stable/mongodb/templates/statefulset-primary-rs.yaml
  stable/mongodb/templates/statefulset-secondary-rs.yaml
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11856 [stable/sysdig] Use latest released agent image version and add options to support eBPF based probe
  stable/sysdig/CHANGELOG.md
  stable/sysdig/Chart.yaml
  stable/sysdig/README.md
  stable/sysdig/templates/daemonset.yaml
  stable/sysdig/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#11171 [stable/metabase] Add log4jProperties
  stable/metabase/Chart.yaml
  stable/metabase/README.md
  stable/metabase/templates/config.yaml
  stable/metabase/templates/deployment.yaml
  stable/metabase/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11862 [filebeat] fix filebeat exporter container port
  stable/filebeat/Chart.yaml
  stable/filebeat/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10779 add collabora-code chart
  stable/collabora-code/.helmignore
  stable/collabora-code/Chart.yaml
  stable/collabora-code/OWNERS
  stable/collabora-code/README.md
  stable/collabora-code/templates/NOTES.txt
  stable/collabora-code/templates/_helpers.tpl
  stable/collabora-code/templates/configmap.yaml
  stable/collabora-code/templates/deployment.yaml
  stable/collabora-code/templates/ingress.yaml
  stable/collabora-code/templates/secret.yaml
  stable/collabora-code/templates/service.yaml
  stable/collabora-code/templates/tests/test-connection.yaml
  stable/collabora-code/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#11842 [stable/redis-ha] feat: implement RBAC
  stable/redis-ha/Chart.yaml
  stable/redis-ha/README.md
  stable/redis-ha/templates/_helpers.tpl
  stable/redis-ha/templates/redis-ha-role.yaml
  stable/redis-ha/templates/redis-ha-rolebinding.yaml
  stable/redis-ha/templates/redis-ha-serviceaccount.yaml
  stable/redis-ha/templates/redis-ha-statefulset.yaml
  stable/redis-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/L

#11873 [stable/dmarc2logstash] Upgrade filebeat to 6.6.0
  stable/dmarc2logstash/Chart.yaml
  stable/dmarc2logstash/README.md
  stable/dmarc2logstash/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#11550 [stable/unifi] Added "unified service" to optionally place everything under one service
  stable/unifi/Chart.yaml
  stable/unifi/README.md
  stable/unifi/templates/controller-svc.yaml
  stable/unifi/templates/discovery-svc.yaml
  stable/unifi/templates/gui-svc.yaml
  stable/unifi/templates/ingress.yaml
  stable/unifi/templates/stun-svc.yaml
  stable/unifi/templates/unified-svc.yaml
  stable/unifi/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#11857 [stable/keycloak] Added support for adding extra pod labels
  stable/keycloak/Chart.yaml
  stable/keycloak/README.md
  stable/keycloak/templates/statefulset.yaml
  stable/keycloak/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11890 hoard mount yaml configuration
  stable/hoard/Chart.yaml
  stable/hoard/README.md
  stable/hoard/templates/configmap.yaml
  stable/hoard/templates/deployment.yaml
  stable/hoard/templates/pvc.yaml
  stable/hoard/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#11893 [stable/wordpress] Allow setting custom sidecar containers
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
  stable/wordpress/templates/deployment.yaml
  stable/wordpress/templates/svc.yaml
  stable/wordpress/values-production.yaml
  stable/wordpress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11868 Add PriorityClassName as option to Keycloak
  stable/keycloak/Chart.yaml
  stable/keycloak/README.md
  stable/keycloak/templates/statefulset.yaml
  stable/keycloak/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11894 [stable/prometheus-operator] Add possibility to scrape kube-scheduler and kube-controller-manager over https
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/exporters/kube-controller-manager/servicemonitor.yaml
  stable/prometheus-operator/templates/exporters/kube-scheduler/servicemonitor.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#11897 upgrade prometheus
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm

#11895 add securitycontext for hazelcast
  stable/hazelcast/Chart.yaml
  stable/hazelcast/templates/statefulset.yaml
  stable/hazelcast/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#11898 [stable/ghost] Fix readiness check when using https
  stable/ghost/Chart.yaml
  stable/ghost/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11874 [stable/elasticsearch] fix readme
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#9366 [graylog] Add Graylog chart
  stable/graylog/Chart.yaml
  stable/graylog/OWNERS
  stable/graylog/README.md
  stable/graylog/requirements.yaml
  stable/graylog/templates/NOTES.txt
  stable/graylog/templates/_helpers.tpl
  stable/graylog/templates/configmap.yaml
  stable/graylog/templates/files-configmap.yaml
  stable/graylog/templates/ingress.yaml
  stable/graylog/templates/master-service.yaml
  stable/graylog/templates/role.yaml
  stable/graylog/templates/rolebinding.yaml
  stable/graylog/templates/secret.yaml
  stable/graylog/templates/serviceaccount.yaml
  stable/graylog/templates/statefulset.yaml
  stable/graylog/templates/tcp-service.yaml
  stable/graylog/templates/udp-service.yaml
  stable/graylog/templates/web-service.yaml
  stable/graylog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XXL

#11156 [stable/kong] Added support for Kong datastore password config through secrets
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/templates/_helpers.tpl
  stable/kong/templates/controller-deployment.yaml
  stable/kong/templates/deployment.yaml
  stable/kong/templates/migrations-post-upgrade.yaml
  stable/kong/templates/migrations-pre-upgrade.yaml
  stable/kong/templates/migrations.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11477 [opa] Able to specify log level and log format
  stable/opa/Chart.yaml
  stable/opa/README.md
  stable/opa/templates/deployment.yaml
  stable/opa/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11594 [stable/fluent-bit] Use release name as full name if contains chart name
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/_helpers.tpl
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#11681 [stable/jaeger-operator] Update image
  stable/jaeger-operator/Chart.yaml
  stable/jaeger-operator/README.md
  stable/jaeger-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#11692 [stable/traefik]: add configurable host ports for deployments
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/deployment.yaml
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#9900 [incubator/orientdb] Initial commit for OrientDB chart
  incubator/orientdb/.helmignore
  incubator/orientdb/Chart.yaml
  incubator/orientdb/README.md
  incubator/orientdb/config/default-distributed-db-config.json
  incubator/orientdb/config/hazelcast.xml
  incubator/orientdb/templates/NOTES.txt
  incubator/orientdb/templates/_helpers.tpl
  incubator/orientdb/templates/config.yaml
  incubator/orientdb/templates/ingress.yaml
  incubator/orientdb/templates/secret.yaml
  incubator/orientdb/templates/service.yaml
  incubator/orientdb/templates/statefulset.yaml
  incubator/orientdb/templates/tests/simple-crud-test.yaml
  incubator/orientdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XL

#11152 [incubator/fluent-cloudwatch] Add security context key
  incubator/fluentd-cloudwatch/Chart.yaml
  incubator/fluentd-cloudwatch/README.md
  incubator/fluentd-cloudwatch/templates/daemonset.yaml
  incubator/fluentd-cloudwatch/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#11914 [incubator/sparkoperator] add ConfigMap update to sparkoperator clusterrole
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/templates/spark-operator-rbac.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11886 Adds resource limits for containers in deploy
  stable/opa/Chart.yaml
  stable/opa/README.md
  stable/opa/templates/deployment.yaml
  stable/opa/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#10928 Configure environment variables for Traefik
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/deployment.yaml
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#11909 use object for rollingUpdate
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/jenkins-master-deployment.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11913 fix: double quotes issue in stable/mariadb
  stable/mariadb/Chart.yaml
  stable/mariadb/templates/role.yaml
  stable/mariadb/templates/rolebinding.yaml
  stable/mariadb/templates/serviceaccount.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11854 add tolerations, affinity and nodeSelector to stackdriver-exporter
  stable/stackdriver-exporter/Chart.yaml
  stable/stackdriver-exporter/README.md
  stable/stackdriver-exporter/templates/deployment.yaml
  stable/stackdriver-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11569 [stable/prometheus-mysql-exporter] Collector flags config
  stable/prometheus-mysql-exporter/Chart.yaml
  stable/prometheus-mysql-exporter/README.md
  stable/prometheus-mysql-exporter/templates/deployment.yaml
  stable/prometheus-mysql-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#11863 [rabbitmq-ha] Set securityContext for rabbitmq container
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/templates/statefulset.yaml
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11937 [stable/prometheus-operator] Add metricRelabelings to node exporter servicemonitor
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/templates/exporters/node-exporter/servicemonitor.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#11081 Modify Ingress template to be easier to --set
  stable/chartmuseum/Chart.yaml
  stable/chartmuseum/README.md
  stable/chartmuseum/templates/ingress.yaml
  stable/chartmuseum/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11074 [stable/drone] Add services permission to pipeline role
  stable/drone/Chart.yaml
  stable/drone/templates/role-pipeline.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#11938 [stable/mariadb] Fix naming of StatefulSets
  stable/mariadb/Chart.yaml
  stable/mariadb/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11344 [incubator/jaeger] Recommended labels, update dependencies
  incubator/jaeger/Chart.yaml
  incubator/jaeger/README.md
  incubator/jaeger/requirements.yaml
  incubator/jaeger/templates/_helpers.tpl
  incubator/jaeger/templates/agent-ds.yaml
  incubator/jaeger/templates/agent-svc.yaml
  incubator/jaeger/templates/cassandra-schema-job.yaml
  incubator/jaeger/templates/collector-deploy.yaml
  incubator/jaeger/templates/collector-svc.yaml
  incubator/jaeger/templates/common-cm.yaml
  incubator/jaeger/templates/hotrod-deploy.yaml
  incubator/jaeger/templates/hotrod-ing.yaml
  incubator/jaeger/templates/hotrod-svc.yaml
  incubator/jaeger/templates/query-deploy.yaml
  incubator/jaeger/templates/query-ing.yaml
  incubator/jaeger/templates/query-svc.yaml
  incubator/jaeger/templates/spark-cronjob.yaml
  incubator/jaeger/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#11667 [stable/logstash] Update logstash to 6.6.1
  stable/logstash/Chart.yaml
  stable/logstash/README.md
  stable/logstash/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#8019 [stable/mattermost-team-edition] Configure everything in one go
  stable/mattermost-team-edition/Chart.yaml
  stable/mattermost-team-edition/README.md
  stable/mattermost-team-edition/ci/extra-values.yaml
  stable/mattermost-team-edition/templates/NOTES.txt
  stable/mattermost-team-edition/templates/_deprecations.tpl
  stable/mattermost-team-edition/templates/_warnings.tpl
  stable/mattermost-team-edition/templates/config.tpl
  stable/mattermost-team-edition/templates/configmap-config.yaml
  stable/mattermost-team-edition/templates/deployment.yaml
  stable/mattermost-team-edition/templates/ingress.yaml
  stable/mattermost-team-edition/templates/pvc.yaml
  stable/mattermost-team-edition/templates/secret-config.yaml
  stable/mattermost-team-edition/templates/service.yaml
  stable/mattermost-team-edition/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XL

#11958 upgrade burrow to 0.24.3
  stable/burrow/Chart.yaml
  stable/burrow/README.md
  stable/burrow/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11957 [stable/kibana] Add customizable service selector
  stable/kibana/Chart.yaml
  stable/kibana/README.md
  stable/kibana/ci/service-values.yaml
  stable/kibana/templates/service.yaml
  stable/kibana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11975 [stable/gocd] Bump up GoCD Version to 19.2.0
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11969 [stable/grafana] add 'file' dashboard type logic to grafana deployment volume mount
  stable/grafana/Chart.yaml
  stable/grafana/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11949 [stable/mongodb] Add init container support
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/templates/deployment-standalone.yaml
  stable/mongodb/templates/statefulset-arbiter-rs.yaml
  stable/mongodb/templates/statefulset-primary-rs.yaml
  stable/mongodb/templates/statefulset-secondary-rs.yaml
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11977 haproxy-ingress: use .controller.tcp to set up TCP ports on controller service
  incubator/haproxy-ingress/Chart.yaml
  incubator/haproxy-ingress/templates/controller-service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9249 [incubator/vault] allow extra init containers to be added
  incubator/vault/Chart.yaml
  incubator/vault/README.md
  incubator/vault/templates/deployment.yaml
  incubator/vault/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11952 [incubator/vault] allow usage of config in existing configmap
  incubator/vault/Chart.yaml
  incubator/vault/README.md
  incubator/vault/templates/configmap.yaml
  incubator/vault/templates/deployment.yaml
  incubator/vault/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9462 [incubator/vault] Use httpGet instead of TCP Socket for liveness check
  incubator/vault/Chart.yaml
  incubator/vault/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11615 [stable/ark] Add init container support
  stable/ark/Chart.yaml
  stable/ark/README.md
  stable/ark/templates/backupstoragelocation.yaml
  stable/ark/templates/deployment.yaml
  stable/ark/templates/restic-daemonset.yaml
  stable/ark/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11995 [stable/wordpress] Fix 'customHTAccessCM'
  stable/wordpress/Chart.yaml
  stable/wordpress/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11997 [stable/grafana] add missing multiline indicator
  stable/grafana/Chart.yaml
  stable/grafana/templates/dashboards-json-configmap.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11966 [stable/memcached] Add ability to specify arbitrary custom labels in memcached helm chart
  stable/memcached/Chart.yaml
  stable/memcached/README.md
  stable/memcached/templates/statefulset.yaml
  stable/memcached/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11222 [stable/prometheus-node-exporter] Fix imagePullSecrets value path
  stable/prometheus-node-exporter/Chart.yaml
  stable/prometheus-node-exporter/templates/serviceaccount.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11811 [stable/prometheus-operator] Add configuration options
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/templates/prometheus-operator/crd-alertmanager.yaml
  stable/prometheus-operator/templates/prometheus-operator/crd-prometheus.yaml
  stable/prometheus-operator/templates/prometheus-operator/crd-prometheusrules.yaml
  stable/prometheus-operator/templates/prometheus-operator/crd-servicemonitor.yaml
  stable/prometheus-operator/templates/prometheus-operator/deployment.yaml
  stable/prometheus-operator/templates/prometheus/prometheus.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#11984 [stable/kured] Update the readme and remove old comment
  stable/kured/Chart.yaml
  stable/kured/README.md
  stable/kured/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11664 [stable/heartbeat] updated heartbeat to 6.6.1
  stable/heartbeat/Chart.yaml
  stable/heartbeat/README.md
  stable/heartbeat/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11928 [cockroachdb] Document that windows hostpath provisioner is not suppo…
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10230 [stable/coredns] Fix wrong service account ref
  stable/coredns/Chart.yaml
  stable/coredns/templates/clusterrolebinding.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11780 [stable/chaoskube] Utilize the podAnnotations for Prometheus scraping
  stable/chaoskube/Chart.yaml
  stable/chaoskube/README.md
  stable/chaoskube/templates/deployment.yaml
  stable/chaoskube/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10450 [stable/selenium] add extraEnvs to deployments
  stable/selenium/Chart.yaml
  stable/selenium/README.md
  stable/selenium/templates/chrome-deployment.yaml
  stable/selenium/templates/chromeDebug-deployment.yaml
  stable/selenium/templates/firefox-deployment.yaml
  stable/selenium/templates/firefoxDebug-deployment.yaml
  stable/selenium/templates/hub-deployment.yaml
  stable/selenium/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12004 add prometheus service monitor to prometheus node exporter
  stable/prometheus-node-exporter/Chart.yaml
  stable/prometheus-node-exporter/README.md
  stable/prometheus-node-exporter/templates/monitor.yaml
  stable/prometheus-node-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11781 Added configuration for provider rfc2136 (see #11779)
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/deployment.yaml
  stable/external-dns/templates/secret.yaml
  stable/external-dns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11945 Add ingress, pod annotations and resources to spark-history-server
  stable/spark-history-server/Chart.yaml
  stable/spark-history-server/README.md
  stable/spark-history-server/templates/deployment.yaml
  stable/spark-history-server/templates/ingress.yaml
  stable/spark-history-server/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11739 [stable/jenkins] Improve documentation - clarify that rbac is needed for autoreload
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12016 Add Hazelcast Metrics, Security Context, Update version
  stable/hazelcast/Chart.yaml
  stable/hazelcast/README.md
  stable/hazelcast/templates/metrics-service.yaml
  stable/hazelcast/templates/statefulset.yaml
  stable/hazelcast/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11922 Adds PodDisruptionBudget to OPA
  stable/opa/Chart.yaml
  stable/opa/README.md
  stable/opa/templates/poddisruptionbudget.yaml
  stable/opa/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#11916 Prometheus scraper config from service -> pod
  stable/kuberhealthy/Chart.yaml
  stable/kuberhealthy/templates/deployment.yaml
  stable/kuberhealthy/templates/service.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#12030 [stable/kafka-manager] Bump Image Tag
  stable/kafka-manager/Chart.yaml
  stable/kafka-manager/OWNERS
  stable/kafka-manager/README.md
  stable/kafka-manager/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#11939 Add an ingress template to the seq chart
  stable/seq/Chart.yaml
  stable/seq/README.md
  stable/seq/templates/ingress.yaml
  stable/seq/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#11876 [stable/concourse] Upgrade to 5.0.0
  stable/concourse/Chart.yaml
  stable/concourse/README.md
  stable/concourse/templates/_helpers.tpl
  stable/concourse/templates/secrets.yaml
  stable/concourse/templates/web-deployment.yaml
  stable/concourse/templates/worker-statefulset.yaml
  stable/concourse/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XXL

#11919 [stable/grafana] allow to define grafana container command in value file
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/deployment.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11716 [stable/kong] fix config var for loadBalancerSourceRanges
  stable/kong/Chart.yaml
  stable/kong/templates/service-kong-proxy.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12024 add prometheus-operator servicemonitor support for helm-exporter
  stable/helm-exporter/Chart.yaml
  stable/helm-exporter/README.md
  stable/helm-exporter/templates/service.yaml
  stable/helm-exporter/templates/servicemonitor.yaml
  stable/helm-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11595 fix typo in readme
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#11960 Allow ingress without host rule
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/config.yaml
  stable/jenkins/templates/jenkins-master-ingress.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11955 [stable/jaeger-operator] Update Jaeger operator permissions
  stable/jaeger-operator/Chart.yaml
  stable/jaeger-operator/templates/role.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12063 [stable/rabbitmq-ha] Fix securityContext for group ID file system per…
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11982 [stable/rabbitmq-ha] Use a more specific docker image tag
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11609 [stable/elasticsearch-exporter] Fix ServiceMonitor port
  stable/elasticsearch-exporter/Chart.yaml
  stable/elasticsearch-exporter/templates/servicemonitor.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#12098 configurable burrow logging
  stable/burrow/Chart.yaml
  stable/burrow/templates/configmap.yaml
  stable/burrow/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11116 [stable/traefik] Add `acme.dnsProvider.ovh` example
  stable/traefik/Chart.yaml
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#11757 [stable/oauth2-proxy] Allow to disable healthChecks for Istio mTLS
  stable/oauth2-proxy/Chart.yaml
  stable/oauth2-proxy/README.md
  stable/oauth2-proxy/templates/deployment.yaml
  stable/oauth2-proxy/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12110 [stable/metrics-server] Add priorityClassName and podAnnotations to metrics server deployment
  stable/metrics-server/Chart.yaml
  stable/metrics-server/README.md
  stable/metrics-server/templates/metrics-server-deployment.yaml
  stable/metrics-server/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12097 bump Spinnaker & Halyard versions for Spinnaker chart
  stable/spinnaker/Chart.yaml
  stable/spinnaker/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12093 [stable/joomla] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/joomla/Chart.yaml
  stable/joomla/README.md
  stable/joomla/templates/_helpers.tpl
  stable/joomla/templates/deployment.yaml
  stable/joomla/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12094 [stable/jasperreports] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/jasperreports/Chart.yaml
  stable/jasperreports/README.md
  stable/jasperreports/templates/_helpers.tpl
  stable/jasperreports/templates/deployment.yaml
  stable/jasperreports/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12095 [stable/drupal] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/drupal/Chart.yaml
  stable/drupal/README.md
  stable/drupal/templates/_helpers.tpl
  stable/drupal/templates/deployment.yaml
  stable/drupal/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12096 [stable/dokuwiki] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/dokuwiki/Chart.yaml
  stable/dokuwiki/README.md
  stable/dokuwiki/templates/_helpers.tpl
  stable/dokuwiki/templates/deployment.yaml
  stable/dokuwiki/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12075 [stable/phpbb] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/phpbb/Chart.yaml
  stable/phpbb/README.md
  stable/phpbb/templates/_helpers.tpl
  stable/phpbb/templates/deployment.yaml
  stable/phpbb/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12076 [stable/phpmyadmin] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/phpmyadmin/Chart.yaml
  stable/phpmyadmin/README.md
  stable/phpmyadmin/templates/_helpers.tpl
  stable/phpmyadmin/templates/deployment.yaml
  stable/phpmyadmin/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12077 [stable/parse] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/parse/Chart.yaml
  stable/parse/README.md
  stable/parse/templates/_helpers.tpl
  stable/parse/templates/dashboard-deployment.yaml
  stable/parse/templates/server-deployment.yaml
  stable/parse/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12078 [stable/owncloud] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/owncloud/Chart.yaml
  stable/owncloud/README.md
  stable/owncloud/templates/_helpers.tpl
  stable/owncloud/templates/deployment.yaml
  stable/owncloud/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12079 [stable/osclass] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/osclass/Chart.yaml
  stable/osclass/README.md
  stable/osclass/templates/_helpers.tpl
  stable/osclass/templates/deployment.yaml
  stable/osclass/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12072 [stable/prestashop] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/prestashop/Chart.yaml
  stable/prestashop/README.md
  stable/prestashop/templates/_helpers.tpl
  stable/prestashop/templates/deployment.yaml
  stable/prestashop/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12073 [stable/postgresql] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/_helpers.tpl
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12074 [stable/phabricator] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/phabricator/Chart.yaml
  stable/phabricator/README.md
  stable/phabricator/templates/_helpers.tpl
  stable/phabricator/templates/deployment.yaml
  stable/phabricator/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12080 [stable/odoo] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/odoo/Chart.yaml
  stable/odoo/README.md
  stable/odoo/templates/_helpers.tpl
  stable/odoo/templates/deployment.yaml
  stable/odoo/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12081 [stable/opencart] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/opencart/Chart.yaml
  stable/opencart/README.md
  stable/opencart/templates/_helpers.tpl
  stable/opencart/templates/deployment.yaml
  stable/opencart/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12067 [stable/testlink] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/testlink/Chart.yaml
  stable/testlink/README.md
  stable/testlink/templates/_helpers.tpl
  stable/testlink/templates/deployment.yaml
  stable/testlink/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12068 [stable/redis] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/templates/_helpers.tpl
  stable/redis/templates/metrics-deployment.yaml
  stable/redis/templates/redis-master-statefulset.yaml
  stable/redis/templates/redis-slave-deployment.yaml
  stable/redis/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12069 [stable/redmine] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/redmine/Chart.yaml
  stable/redmine/README.md
  stable/redmine/templates/_helpers.tpl
  stable/redmine/templates/deployment.yaml
  stable/redmine/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12070 [stable/suitecrm] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/suitecrm/Chart.yaml
  stable/suitecrm/README.md
  stable/suitecrm/templates/_helpers.tpl
  stable/suitecrm/templates/deployment.yaml
  stable/suitecrm/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12071 [stable/rabbitmq] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/_helpers.tpl
  stable/rabbitmq/templates/statefulset.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12082 [stable/orangehrm] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/orangehrm/Chart.yaml
  stable/orangehrm/README.md
  stable/orangehrm/templates/_helpers.tpl
  stable/orangehrm/templates/deployment.yaml
  stable/orangehrm/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12083 [stable/mongodb] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/templates/_helpers.tpl
  stable/mongodb/templates/deployment-standalone.yaml
  stable/mongodb/templates/statefulset-arbiter-rs.yaml
  stable/mongodb/templates/statefulset-primary-rs.yaml
  stable/mongodb/templates/statefulset-secondary-rs.yaml
  stable/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12084 [stable/moodle] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/moodle/Chart.yaml
  stable/moodle/README.md
  stable/moodle/templates/_helpers.tpl
  stable/moodle/templates/deployment.yaml
  stable/moodle/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12085 [stable/nats] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/nats/Chart.yaml
  stable/nats/README.md
  stable/nats/templates/_helpers.tpl
  stable/nats/templates/statefulset.yaml
  stable/nats/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12086 [stable/mediawiki] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/mediawiki/Chart.yaml
  stable/mediawiki/README.md
  stable/mediawiki/templates/_helpers.tpl
  stable/mediawiki/templates/deployment.yaml
  stable/mediawiki/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12087 [stable/mariadb] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
  stable/mariadb/templates/_helpers.tpl
  stable/mariadb/templates/master-statefulset.yaml
  stable/mariadb/templates/slave-statefulset.yaml
  stable/mariadb/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12088 [stable/magento] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/magento/Chart.yaml
  stable/magento/README.md
  stable/magento/templates/_helpers.tpl
  stable/magento/templates/deployment.yaml
  stable/magento/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12091 [stable/ghost] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/ghost/Chart.yaml
  stable/ghost/README.md
  stable/ghost/templates/_helpers.tpl
  stable/ghost/templates/deployment.yaml
  stable/ghost/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12092 [stable/wordpress] Add global 'imagePullSecrets' to overwrite any other existing one
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
  stable/wordpress/templates/_helpers.tpl
  stable/wordpress/templates/deployment.yaml
  stable/wordpress/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12120 [stable/postgresql] Add pullSecrets to volumeContainer and fix comments
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/_helpers.tpl
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12130 [stable/nats] Add global options to values-production
  stable/nats/Chart.yaml
  stable/nats/values-production.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#12123 [stable/mongodb] Add global options to values-production
  stable/mongodb/Chart.yaml
  stable/mongodb/values-production.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#12125 [stable/ghost] Add pullSecrets to volumePermissions image
  stable/ghost/Chart.yaml
  stable/ghost/templates/_helpers.tpl
  stable/ghost/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#12126 [stable/rabbitmq] Add global options to values-production and pullSecrets to metrics
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/values-production.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#12128 [stable/wordpress] Add global options to values-production
  stable/wordpress/Chart.yaml
  stable/wordpress/values-production.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#12129 [stable/redis] Add global options to values-production and pullSecrets to sysctlImage and volumePermissions
  stable/redis/Chart.yaml
  stable/redis/ci/production-values.yaml
  stable/redis/templates/_helpers.tpl
  stable/redis/values-production.yaml
  stable/redis/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#12124 [stable/mariadb] Add global options to values-production and pullSecrets metrics
  stable/mariadb/Chart.yaml
  stable/mariadb/values-production.yaml
  stable/mariadb/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#12127 [stable/postgresql] Fix typo in pullSecret example name
  stable/postgresql/Chart.yaml
  stable/postgresql/values-production.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#10742 Prometheus NATS exporter
  stable/prometheus-nats-exporter/.helmignore
  stable/prometheus-nats-exporter/Chart.yaml
  stable/prometheus-nats-exporter/OWNERS
  stable/prometheus-nats-exporter/README.md
  stable/prometheus-nats-exporter/templates/NOTES.txt
  stable/prometheus-nats-exporter/templates/_helpers.tpl
  stable/prometheus-nats-exporter/templates/deployment.yaml
  stable/prometheus-nats-exporter/templates/service.yaml
  stable/prometheus-nats-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#10762 Add a chart for Mercure.rocks
  stable/mercure/.helmignore
  stable/mercure/Chart.yaml
  stable/mercure/OWNERS
  stable/mercure/README.md
  stable/mercure/templates/NOTES.txt
  stable/mercure/templates/_helpers.tpl
  stable/mercure/templates/configmap.yaml
  stable/mercure/templates/deployment.yaml
  stable/mercure/templates/ingress.yaml
  stable/mercure/templates/secret.yaml
  stable/mercure/templates/service.yaml
  stable/mercure/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#11112 [stable/traefik] Add acme dns resolvers configuration
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/_helpers.tpl
  stable/traefik/templates/configmap.yaml
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#11405 [stable/kube-state-metrics] Add imagePullSecrets in serviceAccount
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
  stable/kube-state-metrics/templates/_helpers.tpl
  stable/kube-state-metrics/templates/deployment.yaml
  stable/kube-state-metrics/templates/serviceaccount.yaml
  stable/kube-state-metrics/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11663 [stable/kibana]updated kibana to 6.6.1
  stable/kibana/Chart.yaml
  stable/kibana/README.md
  stable/kibana/ci/dashboard-values.yaml
  stable/kibana/ci/initcontainers-all-values.yaml
  stable/kibana/ci/plugin-install.yaml
  stable/kibana/ci/url_dashboard-values.yaml
  stable/kibana/templates/configmap-dashboardimport.yaml
  stable/kibana/templates/deployment.yaml
  stable/kibana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#11903 [stable/datadog] Add fullnameOverride and nameOverride in README and values file
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/NOTES.txt
  stable/datadog/templates/_helpers.tpl
  stable/datadog/templates/agent-apiservice.yaml
  stable/datadog/templates/agent-clusterrole.yaml
  stable/datadog/templates/agent-clusterrolebinding-auth-delegator.yaml
  stable/datadog/templates/agent-clusterrolebinding.yaml
  stable/datadog/templates/agent-secret.yaml
  stable/datadog/templates/agent-service-cmd.yaml
  stable/datadog/templates/agent-service-metrics.yaml
  stable/datadog/templates/agent-serviceaccount.yaml
  stable/datadog/templates/agenthpa-rolebinding.yaml
  stable/datadog/templates/checksd-configmap.yaml
  stable/datadog/templates/cluster-agent-deployment.yaml
  stable/datadog/templates/confd-configmap.yaml
  stable/datadog/templates/daemonset.yaml
  stable/datadog/templates/deployment.yaml
  stable/datadog/templates/hpa-clusterrole.yaml
  stable/datadog/templates/hpa-clusterrolebinding.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#11936 [stable/rabbitmq] Add support for Load Definitions
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/configuration.yaml
  stable/rabbitmq/templates/statefulset.yaml
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11990 Added airflow variables support
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/examples/minikube-values.yaml
  stable/airflow/templates/configmap-variables.yaml
  stable/airflow/templates/deployments-scheduler.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#12014 Update to Anchore Engine v0.3.3
  stable/anchore-engine/Chart.yaml
  stable/anchore-engine/README.md
  stable/anchore-engine/requirements.lock
  stable/anchore-engine/templates/NOTES.txt
  stable/anchore-engine/templates/analyzer_deployment.yaml
  stable/anchore-engine/templates/api_deployment.yaml
  stable/anchore-engine/templates/catalog_deployment.yaml
  stable/anchore-engine/templates/enterprise_feeds_deployment.yaml
  stable/anchore-engine/templates/enterprise_ui_deployment.yaml
  stable/anchore-engine/templates/ingress.yaml
  stable/anchore-engine/templates/policy_engine_deployment.yaml
  stable/anchore-engine/templates/simplequeue_deployment.yaml
  stable/anchore-engine/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#12041 [stable/nextcloud] Fix doc for default persistance value
  stable/nextcloud/Chart.yaml
  stable/nextcloud/README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#12061 [stable/magic-namespace] Add TLS capabilities to Tiller deployment
  stable/magic-namespace/Chart.yaml
  stable/magic-namespace/README.md
  stable/magic-namespace/templates/_helpers.tpl
  stable/magic-namespace/templates/secret.yaml
  stable/magic-namespace/templates/tiller-deployment.yaml
  stable/magic-namespace/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12100 Fix bug with no annotations field
  stable/kuberhealthy/Chart.yaml
  stable/kuberhealthy/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#12113 upgrade prometheus
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#12114 [stable/k8s-spot-termination-handler] bump version, add grace period
  stable/k8s-spot-termination-handler/Chart.yaml
  stable/k8s-spot-termination-handler/README.md
  stable/k8s-spot-termination-handler/templates/daemonset.yaml
  stable/k8s-spot-termination-handler/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12133 [stable/grafana] Upgrade sidecar to v0.0.13
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12139 Vault fix antiaffinity
  incubator/vault/Chart.yaml
  incubator/vault/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12148 [stable/filebeat] Update filebeat to 6.6.2
  stable/filebeat/Chart.yaml
  stable/filebeat/README.md
  stable/filebeat/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12156 Fix typo on hostname variable
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/jenkins-master-ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12157 [redis-ha] Master pod set announce IP
  stable/redis-ha/Chart.yaml
  stable/redis-ha/templates/redis-ha-configmap.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#12170 [stable/openvpn] Updated notes to use logs command instead of deprecated log command
  stable/openvpn/Chart.yaml
  stable/openvpn/README.md
  stable/openvpn/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12173 [stable/minio] service.port is not mapped properly
  stable/minio/Chart.yaml
  stable/minio/templates/service.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#12108 [stable/metricbeat] enabled option to resource kind
  stable/metricbeat/Chart.yaml
  stable/metricbeat/README.md
  stable/metricbeat/templates/daemonset.yaml
  stable/metricbeat/templates/deployment.yaml
  stable/metricbeat/templates/secret.yaml
  stable/metricbeat/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#12187 Fixed invalid empty annotations in redis chart template
  stable/redis/Chart.yaml
  stable/redis/templates/redis-master-svc.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test

#11927 [stable/rabbitmq] Added volume permissions
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/_helpers.tpl
  stable/rabbitmq/templates/statefulset.yaml
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11987 [stable/mongodb] Add custom config map for init scripts
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/templates/deployment-standalone.yaml
  stable/mongodb/templates/initialization-configmap.yaml
  stable/mongodb/templates/statefulset-primary-rs.yaml
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M
