Repository helm/charts, pull requests merged in 2019-05, with the labels that each got.

#13427 [stable/grafana] Add secret hash to podspec so grafana pods redeploy on secret regen
  stable/grafana/Chart.yaml
  stable/grafana/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12538 [stable/mysql] New configuration securityContext for the chart mysql
  stable/mysql/Chart.yaml
  stable/mysql/README.md
  stable/mysql/templates/deployment.yaml
  stable/mysql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13387 [stable/redis] Fix: broken netpol
  stable/redis/Chart.yaml
  stable/redis/templates/networkpolicy.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#13431 [stable/home-assistant] some improvements
  stable/home-assistant/Chart.yaml
  stable/home-assistant/templates/deployment.yaml
  stable/home-assistant/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#13434 [stable/ambassador] Make ambassador pro installable from helm chart
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/templates/ambassador-pro-crd.yaml
  stable/ambassador/templates/ambassador-pro-license-key-secret.yaml
  stable/ambassador/templates/ambassador-pro-redis.yaml
  stable/ambassador/templates/ambassador-pro-service.yaml
  stable/ambassador/templates/deployment.yaml
  stable/ambassador/templates/rbac.yaml
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/L

#13432 [stable/airflow] Add checksum annotations to roll deployments
  stable/airflow/Chart.yaml
  stable/airflow/templates/_helpers.tpl
  stable/airflow/templates/configmap-env.yaml
  stable/airflow/templates/configmap-variables-pools.yaml
  stable/airflow/templates/deployments-flower.yaml
  stable/airflow/templates/deployments-scheduler.yaml
  stable/airflow/templates/deployments-web.yaml
  stable/airflow/templates/secret-connections.yaml
  stable/airflow/templates/secret-env.yaml
  stable/airflow/templates/statefulsets-workers.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#13435 added ability to set annotations on service.
  stable/kuberhealthy/Chart.yaml
  stable/kuberhealthy/templates/service.yaml
  stable/kuberhealthy/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#13439 [stable/kong] DRY out wait-for-db container
  stable/kong/Chart.yaml
  stable/kong/templates/_helpers.tpl
  stable/kong/templates/controller-deployment.yaml
  stable/kong/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#13440 [stable/ambassador] Update Ambassador to 0.60.3
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#13452 Removed namespace for clusterRoleBinding
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/templates/spark-operator-rbac.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#13400 [stable/cockroachdb] Allow custom annotations in StatefulSet
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/README.md
  stable/cockroachdb/templates/cockroachdb-statefulset.yaml
  stable/cockroachdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13235 [stable/gocd] Add support for annotations to GoCD Server and Agent
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/README.md
  stable/gocd/templates/gocd-agent-deployment.yaml
  stable/gocd/templates/gocd-server-deployment.yaml
  stable/gocd/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#13463 [stable/kubewatch] Add a parameter to configure the namespace to watch
  stable/kubewatch/Chart.yaml
  stable/kubewatch/README.md
  stable/kubewatch/templates/configmap.yaml
  stable/kubewatch/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13405 Correct customInitContainers Name example
  stable/jenkins/Chart.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#13205 [stable/grafana] Allow Grafana Test pod to run in PSP-enabled cluster
  stable/grafana/Chart.yaml
  stable/grafana/templates/tests/test-podsecuritypolicy.yaml
  stable/grafana/templates/tests/test-role.yaml
  stable/grafana/templates/tests/test-rolebinding.yaml
  stable/grafana/templates/tests/test-serviceaccount.yaml
  stable/grafana/templates/tests/test.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#13455 [stable/nats] Fix hard-coded port definitions
  stable/nats/Chart.yaml
  stable/nats/templates/headless-svc.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13465 Mounting /var/run instead of /var/run/docker.sock so we can get the n…
  stable/instana-agent/Chart.yaml
  stable/instana-agent/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13468 [stable/instana-agent] Remove docker.sock mount in volumes section also
  stable/instana-agent/Chart.yaml
  stable/instana-agent/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#13469 [stable/kong] bump up dependencies
  stable/kong/Chart.yaml
  stable/kong/requirements.lock
  stable/kong/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#13444 [stable/velero] Add CRD clean up Job for CI
  stable/velero/Chart.yaml
  stable/velero/ci/test-values.yaml
  stable/velero/templates/cleanup-crds.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#13413 Allow auto generated password usage
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/deployment-standalone.yaml
  stable/mongodb/templates/secrets.yaml
  stable/mongodb/templates/statefulset-primary-rs.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13104 [stable/datadog] add podLabels option
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/daemonset.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13106 [stable/datadog] setting default daemonset updateStrategy to RollingUpdate
  stable/datadog/Chart.yaml
  stable/datadog/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13470 [stable/postgresql]: Adjust PGDATA to master value
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/statefulset-slaves.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12411 Add get /metrics to nonResourceURLs rbac
  stable/datadog/Chart.yaml
  stable/datadog/templates/clusterrole.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#13511 [stable/jenkins] fix #13467 (wrong deprecation message)
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/deprecation.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#13514 upgrade stable/karma
  stable/karma/Chart.yaml
  stable/karma/README.md
  stable/karma/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#13523 [stable/prometheus-operator] fixed issue in prometheus operator chart's README.md
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12848 [stable/elasticsearch] Add missing marks in README
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13252 Fix unifi NOTES to find correct service
  stable/unifi/Chart.yaml
  stable/unifi/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13519 [stable/cockroachdb] Add ExtraInitAnnotations
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/README.md
  stable/cockroachdb/templates/cluster-init.yaml
  stable/cockroachdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13536 [stable/jenkins] allow templating of customInitContainers
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/jenkins-master-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13487 [stable/mongodb] Add ExternalIP support to chart
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/templates/svc-primary-rs.yaml
  stable/mongodb/templates/svc-standalone.yaml
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13539 [stable/wordpress] Update MariaDB dependency
  stable/wordpress/Chart.yaml
  stable/wordpress/requirements.lock
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13505 [stable/nats] Update configuration path for gnatsd.conf
  stable/nats/Chart.yaml
  stable/nats/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13540 [stable/mm-te] deprecate MM-TE
  stable/mattermost-team-edition/Chart.yaml
  stable/mattermost-team-edition/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#13430 [stable/redis] Enable Kubernetes Cluster DNS domain to be overridden
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/templates/NOTES.txt
  stable/redis/templates/redis-slave-statefulset.yaml
  stable/redis/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13479 [stable/redis] Revert netpol back to original file + addition sentinel port
  stable/redis/Chart.yaml
  stable/redis/templates/networkpolicy.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#13541 [stable/redis] Enable AOF by default
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/values-production.yaml
  stable/redis/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13542 [stable/jenkins] fix wrong pod selector in jenkins-backup
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/jenkins-backup-cronjob.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#13526 [stable/helm-exporter] toggle honorLabels in servicemonitor
  stable/helm-exporter/Chart.yaml
  stable/helm-exporter/templates/servicemonitor.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11159 [incubator/jaeger] Add missing implementation of cmdLineParams for co…
  incubator/jaeger/Chart.yaml
  incubator/jaeger/templates/collector-deploy.yaml
  incubator/jaeger/templates/query-deploy.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12154 [incubator/patroni] Update SCOPE value to fix patroni selector issue
  incubator/patroni/Chart.yaml
  incubator/patroni/templates/ep-patroni.yaml
  incubator/patroni/templates/role-patroni.yaml
  incubator/patroni/templates/rolebinding-patroni.yaml
  incubator/patroni/templates/sec-patroni.yaml
  incubator/patroni/templates/serviceaccount-patroni.yaml
  incubator/patroni/templates/statefulset-patroni.yaml
  incubator/patroni/templates/svc-patroni.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11161 Add helm chart for Apache Solr
  incubator/solr/Chart.yaml
  incubator/solr/README.md
  incubator/solr/requirements.lock
  incubator/solr/requirements.yaml
  incubator/solr/templates/NOTES.txt
  incubator/solr/templates/_helpers.tpl
  incubator/solr/templates/exporter-deployment.yaml
  incubator/solr/templates/poddisruptionbudget.yaml
  incubator/solr/templates/service-headless.yaml
  incubator/solr/templates/service.yaml
  incubator/solr/templates/solr-xml-configmap.yaml
  incubator/solr/templates/statefulset.yaml
  incubator/solr/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XL

#12606 cluster-autoscaler: support managed identity extension in Azure
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/README.md
  stable/cluster-autoscaler/templates/deployment.yaml
  stable/cluster-autoscaler/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13544 [stable/kured] updated new image logation
  stable/kured/Chart.yaml
  stable/kured/README.md
  stable/kured/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12311 [stable/logstash] Make LS_JAVA_OPTS configurable
  stable/logstash/Chart.yaml
  stable/logstash/README.md
  stable/logstash/templates/statefulset.yaml
  stable/logstash/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13424 Add initContainers to ambassador
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/templates/deployment.yaml
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13551 [stable/aerospike] Added tolerations to the aerospike chart
  stable/aerospike/Chart.yaml
  stable/aerospike/README.md
  stable/aerospike/templates/statefulset.yaml
  stable/aerospike/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#13521 [incubator/kafka] Add security context to kafka statefulset
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
  incubator/kafka/templates/statefulset.yaml
  incubator/kafka/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13556 [stable/ambassador] Add HOST_IP environment variable to ambassador container
  stable/ambassador/Chart.yaml
  stable/ambassador/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13560 [stable/elasticsearch-curator] Adds RBAC and PSP support for elasticsearch-curator
  stable/elasticsearch-curator/Chart.yaml
  stable/elasticsearch-curator/README.md
  stable/elasticsearch-curator/templates/_helpers.tpl
  stable/elasticsearch-curator/templates/cronjob.yaml
  stable/elasticsearch-curator/templates/psp.yml
  stable/elasticsearch-curator/templates/role.yaml
  stable/elasticsearch-curator/templates/rolebinding.yaml
  stable/elasticsearch-curator/templates/serviceaccount.yaml
  stable/elasticsearch-curator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#12060 [incubator/sentry-kubernetes] Make LOG_LEVEL env configurable
  incubator/sentry-kubernetes/Chart.yaml
  incubator/sentry-kubernetes/README.md
  incubator/sentry-kubernetes/templates/deployment.yaml
  incubator/sentry-kubernetes/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13283 Add VolumeName for minio nasgateway
  stable/minio/Chart.yaml
  stable/minio/templates/pvc.yaml
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13552 [incubator/kubeless] Fix default namespace for functions
  incubator/kubeless/Chart.yaml
  incubator/kubeless/templates/kubeless-config.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13566 stable/sematext-agent: Update autodisco config manifest
  stable/sematext-agent/Chart.yaml
  stable/sematext-agent/files/autodisco.yml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/L

#13553 [stable/kube-state-metrics] upgrade to 1.6.0
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
  stable/kube-state-metrics/templates/clusterrole.yaml
  stable/kube-state-metrics/templates/deployment.yaml
  stable/kube-state-metrics/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#13524 [stable/home-assistant] added servicemonitor
  stable/home-assistant/Chart.yaml
  stable/home-assistant/templates/servicemonitor.yaml
  stable/home-assistant/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#13576 allow changing of the target port to support TLS termination sidecar
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/jenkins-master-networkpolicy.yaml
  stable/jenkins/templates/jenkins-master-svc.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#12841 Signed-off-by: rstuberg <rstuberg@infoblox.com>
  incubator/vault/Chart.yaml
  incubator/vault/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12706 [stable/metricbeat] add `daemonset.args` and `deployment.args`
  stable/metricbeat/Chart.yaml
  stable/metricbeat/README.md
  stable/metricbeat/templates/daemonset.yaml
  stable/metricbeat/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13590 [incubator/kafka] Correct value name in README for loadBalancerIP array
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13472 [stable/kube-slack] Add more envVars support
  stable/kube-slack/Chart.yaml
  stable/kube-slack/templates/clusterrole.yaml
  stable/kube-slack/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13501 [stable/burrow] move burrow's config to values.yaml
  stable/burrow/Chart.yaml
  stable/burrow/README.md
  stable/burrow/templates/NOTES.txt
  stable/burrow/templates/_helpers.tpl
  stable/burrow/templates/configmap.yaml
  stable/burrow/templates/contracts.yaml
  stable/burrow/templates/deployments.yaml
  stable/burrow/templates/ingress-grpc.yaml
  stable/burrow/templates/ingress-info.yaml
  stable/burrow/templates/service-grpc.yaml
  stable/burrow/templates/service-info.yaml
  stable/burrow/templates/service-peers.yaml
  stable/burrow/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#13607 [stable/mercure] Add pborreli as an approver
  stable/mercure/Chart.yaml
  stable/mercure/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13606 [stable/mercure] Add support for new options
  stable/mercure/Chart.yaml
  stable/mercure/README.md
  stable/mercure/templates/configmap.yaml
  stable/mercure/templates/deployment.yaml
  stable/mercure/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#13471 [stable/traefik] Add option to enable strict SNI checking
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/configmap.yaml
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#13601 [incubator/kafka] added documentation for advertised.listeners when distinct is false
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
  incubator/kafka/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#13323 [stable/traefik] TLS key/value out of scope
  stable/traefik/Chart.yaml
  stable/traefik/templates/configmap.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#13041 [stable/magic-namespace] Fix secret bugs
  stable/magic-namespace/Chart.yaml
  stable/magic-namespace/templates/_helpers.tpl
  stable/magic-namespace/templates/tiller-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#13277 [stable/dex] Update dex to 2.16.0, rollout deployment when configuration change
  stable/dex/Chart.yaml
  stable/dex/OWNERS
  stable/dex/templates/deployment.yaml
  stable/dex/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13529 [stable/ambassador] Allow for ambassador to work better on-prem
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/templates/deployment.yaml
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13624 [stable/mongodb-replicaset] Fix using existing Metrics Secret
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/README.md
  stable/mongodb-replicaset/templates/mongodb-metrics-secret.yaml
  stable/mongodb-replicaset/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12062 [stable/weave-scope] Add readOnly flag
  stable/weave-scope/Chart.yaml
  stable/weave-scope/README.md
  stable/weave-scope/charts/weave-scope-agent/templates/daemonset.yaml
  stable/weave-scope/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13623 [stable/prometheus] use kube-state-metrics v1.6.0
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/kube-state-metrics-clusterrole.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13613 [stable/k8s-spot-termination-handler] fix NOTES.txt with new label style
  stable/k8s-spot-termination-handler/Chart.yaml
  stable/k8s-spot-termination-handler/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13595 [stable/kong] correct wait image for migrations
  stable/kong/Chart.yaml
  stable/kong/templates/migrations-post-upgrade.yaml
  stable/kong/templates/migrations-pre-upgrade.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#11978 [stable/cluster-autoscaler] Add possibility to use iam user keys instead instance role for AWS
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/README.md
  stable/cluster-autoscaler/templates/deployment.yaml
  stable/cluster-autoscaler/templates/secret.yaml
  stable/cluster-autoscaler/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#13630 [stable/mysql] Allow for metric flags to be specified as values
  stable/mysql/Chart.yaml
  stable/mysql/README.md
  stable/mysql/templates/deployment.yaml
  stable/mysql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13636 Enterprise 2.0
  stable/anchore-engine/Chart.yaml
  stable/anchore-engine/README.md
  stable/anchore-engine/enterprise_values.yaml
  stable/anchore-engine/requirements.lock
  stable/anchore-engine/requirements.yaml
  stable/anchore-engine/templates/NOTES.txt
  stable/anchore-engine/templates/_helpers.tpl
  stable/anchore-engine/templates/analyzer_deployment.yaml
  stable/anchore-engine/templates/api_deployment.yaml
  stable/anchore-engine/templates/catalog_deployment.yaml
  stable/anchore-engine/templates/engine_configmap.yaml
  stable/anchore-engine/templates/enterprise_configmap.yaml
  stable/anchore-engine/templates/enterprise_feeds_configmap.yaml
  stable/anchore-engine/templates/enterprise_feeds_deployment.yaml
  stable/anchore-engine/templates/enterprise_ui_config.yaml
  stable/anchore-engine/templates/enterprise_ui_deployment.yaml
  stable/anchore-engine/templates/ingress.yaml
  stable/anchore-engine/templates/policy_engine_deployment.yaml
  stable/anchore-engine/templates/simplequeue_deployment.yaml
  stable/anchore-engine/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XL

#13547 [stable/postgresql] Adapt to new bitnami postgresql bash container
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13147 [stable/prometheus-operator] add missing relabeling values to the README and remove a duplicate entry
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/alertmanager/servicemonitor.yaml
  stable/prometheus-operator/templates/grafana/servicemonitor.yaml
  stable/prometheus-operator/templates/prometheus-operator/servicemonitor.yaml
  stable/prometheus-operator/templates/prometheus/servicemonitor.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#13644 [stable/wordpress] Add 'none' to SMTP protocol accepted values
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13609 [incubator/kubeless] Fix config options in README
  incubator/kubeless/Chart.yaml
  incubator/kubeless/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13310 [stable/coredns] Update labels to follow best practices
  stable/coredns/Chart.yaml
  stable/coredns/templates/clusterrole.yaml
  stable/coredns/templates/clusterrolebinding.yaml
  stable/coredns/templates/configmap.yaml
  stable/coredns/templates/deployment.yaml
  stable/coredns/templates/podsecuritypolicy.yaml
  stable/coredns/templates/service.yaml
  stable/coredns/templates/serviceaccount.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#13534 [stable/logstash] Mount Custom Binary Files
  stable/logstash/Chart.yaml
  stable/logstash/README.md
  stable/logstash/templates/files-config.yaml
  stable/logstash/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13643 [stable/velero] add resourceGroup to VolumeSnapshotLocation
  stable/velero/Chart.yaml
  stable/velero/README.md
  stable/velero/templates/volumesnapshotlocation.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13494 [stable/efs-provisioner] pod annotations fix
  stable/efs-provisioner/Chart.yaml
  stable/efs-provisioner/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13649 [stable/mariadb] Upgrade app version from 10.1 to 10.3
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
  stable/mariadb/values-production.yaml
  stable/mariadb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12437 stable/satisfy: updating image to latest, with fixes
  stable/satisfy/Chart.yaml
  stable/satisfy/README.md
  stable/satisfy/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13653 [stable/postgresql] Fix 'mountPath' for password files.
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/statefulset-slaves.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13545 [stable/kubernetes-dashboard] Clean up cluster-service label
  stable/kubernetes-dashboard/Chart.yaml
  stable/kubernetes-dashboard/templates/deployment.yaml
  stable/kubernetes-dashboard/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#13574 [stable/grafana] Adds imagePullSecrets to test pod
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/tests/test.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13645 [stable/chart] Add deploymentStrategy on HackMD chart
  stable/hackmd/Chart.yaml
  stable/hackmd/README.md
  stable/hackmd/templates/deployment.yaml
  stable/hackmd/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13658 [stable/redmine] Update Redmine dependencies
  stable/redmine/Chart.yaml
  stable/redmine/requirements.lock
  stable/redmine/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13661 stable/ambassador - Update to Ambassador 0.61.0
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13495 [stable/kube-state-metrics] Allows deploying ServiceAccount without RBAC
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
  stable/kube-state-metrics/templates/serviceaccount.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13586 [stable/signalfx-agent] Adding deprication notice
  stable/signalfx-agent/Chart.yaml
  stable/signalfx-agent/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13662 stable/airflow Add support for prometheus rules to the airflow helm chart
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/templates/prometheus-rule.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#13657 [stable/odoo] Update Odoo dependencies
  stable/odoo/Chart.yaml
  stable/odoo/requirements.lock
  stable/odoo/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13625 [stable/prometheus-operator] Bump version dependency
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/requirements.lock
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13618 [stable/sysdig] Enable new_k8s flag by default
  stable/sysdig/CHANGELOG.md
  stable/sysdig/Chart.yaml
  stable/sysdig/README.md
  stable/sysdig/values.yaml
Labels: Contribution Allowed, approved, lgtm

#13676 [stable/falco] Use KUBERNETES_SERVICE_HOST environment variable
  stable/falco/CHANGELOG.md
  stable/falco/Chart.yaml
  stable/falco/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#13682 [stable/postgresql] Set the right env. variable to enable debug
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13683 [stable/airflow] Fix prometheusRule additionalLabels
  stable/airflow/Chart.yaml
  stable/airflow/templates/prometheus-rule.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#13635 [stable/rabbitmq-ha] allow setting different topology keys for anti affinity
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/templates/statefulset.yaml
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9029 [stable/cluster-autoscaler] support dnsPolicy
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/README.md
  stable/cluster-autoscaler/templates/deployment.yaml
  stable/cluster-autoscaler/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#13616 [stable/concourse] Add possibility to set strategy for rollingUpdates (web)
  stable/concourse/Chart.yaml
  stable/concourse/README.md
  stable/concourse/templates/web-deployment.yaml
  stable/concourse/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12281 Allow setting an emptyDir sizeLimit for Prometheus
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/server-deployment.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13670 [stable/mysql] support loadBalancerIP, configurationFilesPath
  stable/mysql/Chart.yaml
  stable/mysql/README.md
  stable/mysql/templates/deployment.yaml
  stable/mysql/templates/svc.yaml
  stable/mysql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#13706 [stable/helm-exporter] Updated image tag to 0.4.0 & added variable for tiller Namespaces
  stable/helm-exporter/Chart.yaml
  stable/helm-exporter/README.md
  stable/helm-exporter/templates/deployment.yaml
  stable/helm-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13686 [stable/prometheus-cloudwatch-exporter] Add scrape timeout option
  stable/prometheus-cloudwatch-exporter/Chart.yaml
  stable/prometheus-cloudwatch-exporter/README.md
  stable/prometheus-cloudwatch-exporter/templates/servicemonitor.yaml
  stable/prometheus-cloudwatch-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12810 [stable/logstash] add extraEnv
  stable/logstash/Chart.yaml
  stable/logstash/README.md
  stable/logstash/templates/statefulset.yaml
  stable/logstash/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13628 [stable/burrow] Update README.md, fix script url error
  stable/burrow/Chart.yaml
  stable/burrow/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13699 [stable/datadog] Fix broken links in README
  stable/datadog/Chart.yaml
  stable/datadog/README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#13269 [Stable/apm-server] Support apm-server 7.0.0
  stable/apm-server/Chart.yaml
  stable/apm-server/templates/daemonset.yaml
  stable/apm-server/templates/deployment.yaml
  stable/apm-server/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13700 [stable/fluent-bit] Add priorityClassName
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/daemonset.yaml
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#13694 [incubator/raw] fix missing newline after yaml document separator
  incubator/raw/Chart.yaml
  incubator/raw/templates/resources.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13722 [stable/chartmuseum] Fix typo in var name
  stable/chartmuseum/Chart.yaml
  stable/chartmuseum/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13690 [stable/traefik] Use chart helper to support SemVer2
  stable/traefik/Chart.yaml
  stable/traefik/templates/_helpers.tpl
  stable/traefik/templates/acme-pvc.yaml
  stable/traefik/templates/config-files.yaml
  stable/traefik/templates/configmap.yaml
  stable/traefik/templates/dashboard-ingress.yaml
  stable/traefik/templates/dashboard-service.yaml
  stable/traefik/templates/default-cert-secret.yaml
  stable/traefik/templates/deployment.yaml
  stable/traefik/templates/dns-provider-secret.yaml
  stable/traefik/templates/hpa.yaml
  stable/traefik/templates/poddisruptionbudget.yaml
  stable/traefik/templates/secret-files.yaml
  stable/traefik/templates/service.yaml
  stable/traefik/templates/storeconfig-job.yaml
  stable/traefik/templates/tests/test-configmap.yaml
  stable/traefik/templates/tests/test.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#13475 [stable/kong] introduce support for dbless Ingress Controller
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/ci/dbless.yaml
  stable/kong/requirements.lock
  stable/kong/requirements.yaml
  stable/kong/templates/_helpers.tpl
  stable/kong/templates/controller-deployment.yaml
  stable/kong/templates/deployment.yaml
  stable/kong/templates/migrations-post-upgrade.yaml
  stable/kong/templates/migrations-pre-upgrade.yaml
  stable/kong/templates/migrations.yaml
  stable/kong/templates/service-kong-proxy.yaml
  stable/kong/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#13054 feat: imporvements to pachyderm chart
  stable/pachyderm/Chart.yaml
  stable/pachyderm/README.md
  stable/pachyderm/templates/etcd_deployment.yaml
  stable/pachyderm/templates/etcd_svc.yaml
  stable/pachyderm/templates/pachd_cluster_role.yaml
  stable/pachyderm/templates/pachd_deployment.yaml
  stable/pachyderm/templates/pachd_rolebinding.yaml
  stable/pachyderm/templates/pachd_sa.yaml
  stable/pachyderm/templates/pachd_secret.yaml
  stable/pachyderm/templates/pachd_svc.yaml
  stable/pachyderm/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#13508 [stable/opa] add namespace selector to OPA webhook resource and bump …
  stable/opa/Chart.yaml
  stable/opa/templates/webhookconfiguration.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#13705 [stable/postgresql] Use tpl so release name can be used in config maps
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13712 [stable/rabbitmq] Update README
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13740 [stable/falco] Upgrade to Falco 0.15.0
  stable/falco/CHANGELOG.md
  stable/falco/Chart.yaml
  stable/falco/README.md
  stable/falco/rules/falco_rules.yaml
  stable/falco/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XL

#13745 [stable/nats] Use a validate helper to detect invalid configurations
  stable/nats/Chart.yaml
  stable/nats/templates/NOTES.txt
  stable/nats/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#13619 [stabel/rocketchat] Improve chart
  stable/rocketchat/Chart.yaml
  stable/rocketchat/OWNERS
  stable/rocketchat/README.md
  stable/rocketchat/ci/ci-values.yaml
  stable/rocketchat/requirements.lock
  stable/rocketchat/requirements.yaml
  stable/rocketchat/templates/_helpers.tpl
  stable/rocketchat/templates/deployment.yaml
  stable/rocketchat/templates/ingress.yaml
  stable/rocketchat/templates/pvc.yaml
  stable/rocketchat/templates/secret.yaml
  stable/rocketchat/templates/secrets.yaml
  stable/rocketchat/templates/service.yaml
  stable/rocketchat/templates/serviceaccount.yaml
  stable/rocketchat/templates/svc.yaml
  stable/rocketchat/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#13744 [stable/falco] cri-o and containerd support for falco 0.15.0
  stable/falco/CHANGELOG.md
  stable/falco/Chart.yaml
  stable/falco/README.md
  stable/falco/templates/daemonset.yaml
  stable/falco/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#13749 [stable/sysdig] Hardcode new_k8s value to true
  stable/sysdig/CHANGELOG.md
  stable/sysdig/Chart.yaml
  stable/sysdig/README.md
  stable/sysdig/templates/configmap.yaml
  stable/sysdig/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#13678 [stable/rabbitmq-ha] Handle management credentials as secret
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/templates/NOTES.txt
  stable/rabbitmq-ha/templates/secret.yaml
  stable/rabbitmq-ha/templates/statefulset.yaml
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#13756 [stable/prometheus-mongodb-exporter] Fix mongodb-exporter default values
  stable/prometheus-mongodb-exporter/Chart.yaml
  stable/prometheus-mongodb-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13546 Adding static IP documentation
  stable/kong/Chart.yaml
  stable/kong/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13770 [stable/anchore] add apiVersion
  stable/anchore-engine/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#13784 [stable/elastalert] add apiVersion
  stable/elastalert/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#13768 [stable/aerospike] add apiVersion
  stable/aerospike/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#13769 [stable/airflow]add apiVersion
  stable/airflow/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#13771 [stable/chronograf] add apiVersion
  stable/chronograf/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#13772 [stable/cloudserver] add apiVersion
  stable/cloudserver/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#13773 [stable/cockroachdb] add apiVersion
  stable/cockroachdb/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#13774 [stable/concourse] add apiVersion
  stable/concourse/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#13776 [stable/consul] add apiVersion
  stable/consul/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#13777 [stable/coredns] add apiVersion
  stable/coredns/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#13778 [stable/cosbench] add apiVersion
  stable/cosbench/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#13780 [stable/dask] add apiVersion
  stable/dask/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#13781 [stable/datadog] add apiVersion
  stable/datadog/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#13561 incubator/azuremonitor-containers - chart update for latest (april 2019) agent release
  incubator/azuremonitor-containers/Chart.yaml
  incubator/azuremonitor-containers/templates/omsagent-daemonset.yaml
  incubator/azuremonitor-containers/templates/omsagent-deployment.yaml
  incubator/azuremonitor-containers/templates/omsagent-rs-configmap.yaml
  incubator/azuremonitor-containers/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#13782 [stable/dex] add apiVersion
  stable/dex/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#13783 [stable/drone] add apiVersion
  stable/drone/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#13785 [stable/elasticsearch] add apiVersion
  stable/elasticsearch/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS
