Repository helm/charts, pull requests merged in 2019-11, with the labels that each got.

#18247 [stable/grafana] Make deployment consistent with configmaps
  stable/grafana/Chart.yaml
  stable/grafana/templates/dashboards-json-configmap.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18501 [incubator/sparkoperator] Added missing RBAC permission for ResourceQ…
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/templates/spark-operator-rbac.yaml
Labels: Contribution Allowed, approved, lgtm

#18447 [bitnami/postgresql] Fix error when running init-container
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18520 [incubator/sparkoperator] Removed deprecated initializers from the Deployment
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/templates/spark-operator-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#18033 [stable/sumologic-fluentd] Update api versions to support k8s 1.16
  stable/sumologic-fluentd/Chart.yaml
  stable/sumologic-fluentd/README.md
  stable/sumologic-fluentd/templates/clusterrole.yaml
  stable/sumologic-fluentd/templates/clusterrolebinding.yaml
  stable/sumologic-fluentd/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17764 [prometheus-cloudwatch-exporter] Upgrade api versions
  stable/prometheus-cloudwatch-exporter/CHANGELOG.md
  stable/prometheus-cloudwatch-exporter/Chart.yaml
  stable/prometheus-cloudwatch-exporter/templates/_helpers.tpl
  stable/prometheus-cloudwatch-exporter/templates/clusterrole.yaml
  stable/prometheus-cloudwatch-exporter/templates/clusterrolebinding.yaml
  stable/prometheus-cloudwatch-exporter/templates/deployment.yaml
  stable/prometheus-cloudwatch-exporter/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18508 [stable/phpmyadmin] Add support for SSL connections with database
  stable/phpmyadmin/Chart.yaml
  stable/phpmyadmin/README.md
  stable/phpmyadmin/templates/certs.yaml
  stable/phpmyadmin/templates/deployment.yaml
  stable/phpmyadmin/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#18522 [stable/cluster-autoscaler] update to latest cluster-autoscaler
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/README.md
  stable/cluster-autoscaler/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18504 add `plugin_dir` configuration to the mysql config
  stable/mariadb/Chart.yaml
  stable/mariadb/values-production.yaml
  stable/mariadb/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#18246 [stable/kong] Add pod security policy to Kong Chart
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/ci/default-values-with-psp.yaml
  stable/kong/ci/ingressController-with-psp.yaml
  stable/kong/templates/controller-service-account.yaml
  stable/kong/templates/deployment.yaml
  stable/kong/templates/migrations-post-upgrade.yaml
  stable/kong/templates/migrations-pre-upgrade.yaml
  stable/kong/templates/migrations.yaml
  stable/kong/templates/psp.yaml
  stable/kong/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18430 [stable/prometheus-operator] Cleanup, Fix more CI problems
  stable/prometheus-operator/CONTRIBUTING.md
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/01-provision-crds-values.yaml
  stable/prometheus-operator/ci/02-test-without-crds-values.yaml
  stable/prometheus-operator/hack/update-ci.sh
  stable/prometheus-operator/templates/prometheus-operator/deployment.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18498 [stable/fluentd] Support custom load balancer IP
  stable/fluentd/Chart.yaml
  stable/fluentd/README.md
  stable/fluentd/templates/service.yaml
  stable/fluentd/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18538 [ci] Upgrade to chart-testing v2.4.0
  .circleci/config.yml
  test/Dockerfile
  test/build.sh
  test/e2e.sh
Labels: Contribution Allowed, approved, lgtm, size/S

#18468 Add parameter for controller service targetPort so they can be overwr…
  incubator/haproxy-ingress/Chart.yaml
  incubator/haproxy-ingress/README.md
  incubator/haproxy-ingress/templates/controller-service.yaml
  incubator/haproxy-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18502 [stable/external-dns] Skip mounting when using managed identity extension
  stable/external-dns/Chart.yaml
  stable/external-dns/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18513 [stable/wordpress] Fix custom htaccess
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
  stable/wordpress/templates/deployment.yaml
  stable/wordpress/values-production.yaml
  stable/wordpress/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#18533 [stable/kubernetes-dashboard] Update to stable "rbac.authorization.k8s.io/v1"
  stable/kubernetes-dashboard/Chart.yaml
  stable/kubernetes-dashboard/templates/clusterrole-readonly.yaml
  stable/kubernetes-dashboard/templates/role.yaml
  stable/kubernetes-dashboard/templates/rolebinding.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18416 [stable/sentry]: fix error in k8s v1.6
  stable/sentry/Chart.yaml
  stable/sentry/templates/cron-deployment.yaml
  stable/sentry/templates/metrics-deployment.yaml
  stable/sentry/templates/web-deployment.yaml
  stable/sentry/templates/workers-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18343 [stable/airflow] add labels/annotations
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/templates/deployments-flower.yaml
  stable/airflow/templates/deployments-scheduler.yaml
  stable/airflow/templates/deployments-web.yaml
  stable/airflow/templates/statefulsets-workers.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18527 [stable/prometheus-node-exporter] Fix maps -> slices, bump version
  stable/prometheus-node-exporter/Chart.yaml
  stable/prometheus-node-exporter/README.md
  stable/prometheus-node-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18116 [incubator/rundeck] New-template-annotations
  incubator/rundeck/Chart.yaml
  incubator/rundeck/README.md
  incubator/rundeck/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18341 [stable/postgresql] Use array as default extraEnvs
  stable/postgresql/Chart.yaml
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17687 [stable/prometheus-blackbox-exporter] removes configmap-reload in favor of a configmap checksum
  stable/prometheus-blackbox-exporter/Chart.yaml
  stable/prometheus-blackbox-exporter/README.md
  stable/prometheus-blackbox-exporter/templates/deployment.yaml
  stable/prometheus-blackbox-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18261 [incubator/kafka] Bump zookeeper helm chart version so all the objects the kafka chart produces adhere to the k8s JSON schema strictly
  incubator/kafka/Chart.yaml
  incubator/kafka/requirements.lock
  incubator/kafka/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18535 [stable/redis-ha] fix affinity conflict with the helm test pod
  stable/redis-ha/Chart.yaml
  stable/redis-ha/templates/redis-ha-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#18518 [stable/redis-ha] Add serviceMonitor resource object
  stable/redis-ha/Chart.yaml
  stable/redis-ha/README.md
  stable/redis-ha/templates/redis-ha-servicemonitor.yaml
  stable/redis-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#16837 [stable/cluster-autoscaler] Support fullnameOverride
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/README.md
  stable/cluster-autoscaler/templates/_helpers.tpl
  stable/cluster-autoscaler/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#17268 [stable/prometheus] migrate API versions from deprecated, removed versions
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/_helpers.tpl
  stable/prometheus/templates/alertmanager-deployment.yaml
  stable/prometheus/templates/alertmanager-podsecuritypolicy.yaml
  stable/prometheus/templates/kube-state-metrics-deployment.yaml
  stable/prometheus/templates/kube-state-metrics-podsecuritypolicy.yaml
  stable/prometheus/templates/node-exporter-daemonset.yaml
  stable/prometheus/templates/node-exporter-podsecuritypolicy.yaml
  stable/prometheus/templates/pushgateway-deployment.yaml
  stable/prometheus/templates/pushgateway-podsecuritypolicy.yaml
  stable/prometheus/templates/server-deployment.yaml
  stable/prometheus/templates/server-podsecuritypolicy.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18112 [stable/prometheus] allow multiple alert files
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/server-configmap.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18400 [stable/jenkins] JCasC auto reload works without ssh keys
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/config.yaml
  stable/jenkins/templates/jenkins-master-deployment.yaml
  stable/jenkins/templates/secret.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#17430 [stable/logdna-agent] add extraEnv, extraVolumes and extraVolumeMounts
  stable/logdna-agent/Chart.yaml
  stable/logdna-agent/README.md
  stable/logdna-agent/templates/daemonset.yaml
  stable/logdna-agent/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18489 [stable/drone] Bump drone version to latest available image v1.6.1
  stable/drone/Chart.yaml
  stable/drone/README.md
  stable/drone/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18478 [stable/prometheus-operator] Remove workaround on service selectors
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/_helpers.tpl
  stable/prometheus-operator/templates/exporters/core-dns/service.yaml
  stable/prometheus-operator/templates/exporters/kube-controller-manager/service.yaml
  stable/prometheus-operator/templates/exporters/kube-dns/service.yaml
  stable/prometheus-operator/templates/exporters/kube-etcd/service.yaml
  stable/prometheus-operator/templates/exporters/kube-proxy/service.yaml
  stable/prometheus-operator/templates/exporters/kube-scheduler/service.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#17587 [stable/traefik] Add startupArguments to storeconfig job
  stable/traefik/Chart.yaml
  stable/traefik/templates/storeconfig-job.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18523 [stable/pomerium] Remove redundant hosts for TLS
  stable/pomerium/Chart.yaml
  stable/pomerium/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18186 [stable/oauth2-proxy] Add securityContext for container
  stable/oauth2-proxy/Chart.yaml
  stable/oauth2-proxy/README.md
  stable/oauth2-proxy/templates/deployment.yaml
  stable/oauth2-proxy/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18600 [stable/redis] Fix metrics.extraArgs
  stable/redis/Chart.yaml
  stable/redis/templates/redis-master-statefulset.yaml
  stable/redis/templates/redis-slave-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18592 [stable/elastalert] Add podAnnotations field
  stable/elastalert/Chart.yaml
  stable/elastalert/README.md
  stable/elastalert/templates/deployment.yaml
  stable/elastalert/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18542 [stable/external-dns] Avoid configuring 'role_arn' in AWS default profile
  stable/external-dns/Chart.yaml
  stable/external-dns/templates/_helpers.tpl
  stable/external-dns/templates/secret.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18549 [stable/parse] Add support for extra env vars
  stable/parse/Chart.yaml
  stable/parse/README.md
  stable/parse/templates/dashboard-deployment.yaml
  stable/parse/templates/server-deployment.yaml
  stable/parse/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18558 [stable/telegraf] Add processor config to telegraf
  stable/telegraf/Chart.yaml
  stable/telegraf/templates/_helpers.tpl
  stable/telegraf/templates/configmap.yaml
  stable/telegraf/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#18564 [stable/prometheus-operator] Major sync of rules, alerts and dashboards from upstream (3rd try)
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/hack/requirements.txt
  stable/prometheus-operator/hack/sync_grafana_dashboards.py
  stable/prometheus-operator/hack/sync_prometheus_rules.py
  stable/prometheus-operator/templates/grafana/dashboards-1.14/apiserver.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/cluster-total.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/controller-manager.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-coredns.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-cluster.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-namespace.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-node.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-pod.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-workload.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-workloads-namespace.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/kubelet.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/namespace-by-pod.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/namespace-by-workload.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/node-cluster-rsrc-use.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/node-rsrc-use.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/persistentvolumesusage.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/pod-total.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/pods.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/prometheus-remote-write.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/proxy.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/scheduler.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/statefulset.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/workload-total.yaml
  stable/prometheus-operator/templates/grafana/dashboards/k8s-coredns.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/general.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/k8s.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-apps.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-resources.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-storage.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system-controller-manager.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system-kubelet.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system-scheduler.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/node-exporter.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/node-exporter.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/node.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/prometheus.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XXL

#18570 [incubator/sparkoperator] add missing permission for validationwebhookconfigurations
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/templates/spark-operator-rbac.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#18573 [stable/ipfs] Bump version of IPFS as it fix few majors bugs
  stable/ipfs/Chart.yaml
  stable/ipfs/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18575 [stable/gocd] Bump gocd version to 19.10.0
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/templates/configmap.yaml
  stable/gocd/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#18594 [stable/newrelic-infrastructure] Update newrelic-infrastructure image version to 1.10.2
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/README.md
  stable/newrelic-infrastructure/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#18596 [stable/jenkins] add master.schedulerName
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/jenkins-master-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#18555 Replace hardcoded port 10254 with variable. This allows to run multiple ingresses
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/templates/controller-daemonset.yaml
  stable/nginx-ingress/templates/controller-deployment.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17055 [stable/sumologic-fluentd] Add support for DaemonSet annotations (#17…
  stable/sumologic-fluentd/Chart.yaml
  stable/sumologic-fluentd/README.md
  stable/sumologic-fluentd/templates/daemonset.yaml
  stable/sumologic-fluentd/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18586 [stable/prometheus-pushgateway] Fix deprecated apiVersion for Deployment
  stable/prometheus-pushgateway/Chart.yaml
  stable/prometheus-pushgateway/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18608 [stable/prometheus-operator] Update prometheus-node-exporter and grafana dependencies
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/requirements.lock
Labels: Contribution Allowed, approved, lgtm, size/XS

#18567 [stable/kong] drop cassandra sub-chart
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/ci/cassandra.yaml
  stable/kong/requirements.lock
  stable/kong/requirements.yaml
  stable/kong/templates/_helpers.tpl
  stable/kong/templates/deployment.yaml
  stable/kong/templates/migrations-post-upgrade.yaml
  stable/kong/templates/migrations-pre-upgrade.yaml
  stable/kong/templates/migrations.yaml
  stable/kong/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#18597 [stable/prometheus-operator] Configurable kubeDns ports
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/exporters/kube-dns/service.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18373 [stable/kured] Change psp apiVersion for K8s 1.16
  stable/kured/Chart.yaml
  stable/kured/templates/_helpers.tpl
  stable/kured/templates/podsecuritypolicy.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16946 [stable/k8s-spot-termination-handler] Call for maintainers for charts with a single OWNER
  stable/k8s-spot-termination-handler/Chart.yaml
  stable/k8s-spot-termination-handler/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18263 [incubator/kafka] fixes #18254
  incubator/kafka/Chart.yaml
  incubator/kafka/requirements.lock
  incubator/kafka/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18605 [stable/kube-slack] add jstriebel to OWNERS
  stable/kube-slack/.helmignore
  stable/kube-slack/Chart.yaml
  stable/kube-slack/OWNERS
Labels: Contribution Allowed, approved, lgtm, size/XS

#18490 [stable/jenkins] Revert direct connection fix in previous version
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/config.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18433 [stable/karma] Add certSecretNames parameter
  stable/karma/Chart.yaml
  stable/karma/README.md
  stable/karma/templates/deployment.yaml
  stable/karma/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18440 [stable/airflow] add workers gracefull termination
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/templates/configmap-scripts.yaml
  stable/airflow/templates/statefulsets-workers.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18556 [stable/wordpress] Fix warning with ingress annotations
  stable/wordpress/Chart.yaml
  stable/wordpress/values-production.yaml
  stable/wordpress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18627 [stable/postgresql] Bump image revision
  stable/postgresql/Chart.yaml
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18363 [stable/prometheus-operator] Remove duplicate namespace values
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/exporters/core-dns/service.yaml
  stable/prometheus-operator/templates/exporters/kube-controller-manager/endpoints.yaml
  stable/prometheus-operator/templates/exporters/kube-controller-manager/service.yaml
  stable/prometheus-operator/templates/exporters/kube-dns/service.yaml
  stable/prometheus-operator/templates/exporters/kube-etcd/endpoints.yaml
  stable/prometheus-operator/templates/exporters/kube-etcd/service.yaml
  stable/prometheus-operator/templates/exporters/kube-proxy/endpoints.yaml
  stable/prometheus-operator/templates/exporters/kube-proxy/service.yaml
  stable/prometheus-operator/templates/exporters/kube-scheduler/endpoints.yaml
  stable/prometheus-operator/templates/exporters/kube-scheduler/service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18619 [stable/prometheus-operator] Prevent creating empty PrometheusRules.
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/hack/sync_prometheus_rules.py
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system-controller-manager.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system-scheduler.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18629 [stable/gocd] Add support for tolerations on both the GoCD server and agent pods
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/README.md
  stable/gocd/templates/gocd-agent-deployment.yaml
  stable/gocd/templates/gocd-server-deployment.yaml
  stable/gocd/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18635 [stalbe/nginx-ingress] Fix wrong apiGroup templating in roles
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/templates/_helpers.tpl
  stable/nginx-ingress/templates/controller-role.yaml
  stable/nginx-ingress/templates/default-backend-role.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18634 [stable/karma] Upgrade to 0.50
  stable/karma/Chart.yaml
  stable/karma/README.md
  stable/karma/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#18636 [stableBumping image versions
  stable/home-assistant/Chart.yaml
  stable/home-assistant/README.md
  stable/home-assistant/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#18380 [stable/dex] Fix ConfigMap creation and add missed config parameter
  stable/dex/Chart.yaml
  stable/dex/README.md
  stable/dex/templates/config-openssl.yaml
  stable/dex/templates/secret.yaml
  stable/dex/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18140 [stable/seq] Feature apiVersion compatibility switch
  stable/seq/Chart.yaml
  stable/seq/templates/_helpers.tpl
  stable/seq/templates/deployment.yaml
  stable/seq/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17147 Fix `output.scheme` notation
  stable/fluentd/Chart.yaml
  stable/fluentd/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17816 Use better way to check ready
  incubator/zookeeper/Chart.yaml
  incubator/zookeeper/templates/config-script.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18590 [stable/ghost] Update values.schema.json to reflect latest format
  stable/ghost/Chart.yaml
  stable/ghost/values.schema.json
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18591 [stable/postgresql] Update values.schema.json to reflect latest format
  stable/postgresql/Chart.yaml
  stable/postgresql/values.schema.json
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18589 [stable/wordpress] Update values.schema.json to reflect latest format
  stable/wordpress/Chart.yaml
  stable/wordpress/values.schema.json
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18650 [stable/kong] Add imagePullPolicy to wait images
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/templates/migrations-post-upgrade.yaml
  stable/kong/templates/migrations-pre-upgrade.yaml
  stable/kong/templates/migrations.yaml
  stable/kong/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18638 [stable/kube-ops-view] Upgrade to 19.9.0
  stable/kube-ops-view/Chart.yaml
  stable/kube-ops-view/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#17736 Handle affinity with templating and add podDisruptionBudget support
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/pdb.yaml
  stable/rabbitmq/templates/statefulset.yaml
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#17682 [stable/dex] Fix compatibility with Helm 3
  stable/dex/Chart.yaml
  stable/dex/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18611 [stable/spring-cloud-data-flow] Add support for disabling Skipper Server
  stable/spring-cloud-data-flow/Chart.yaml
  stable/spring-cloud-data-flow/README.md
  stable/spring-cloud-data-flow/templates/server-config.yaml
  stable/spring-cloud-data-flow/templates/server-deployment.yaml
  stable/spring-cloud-data-flow/templates/skipper-config.yaml
  stable/spring-cloud-data-flow/templates/skipper-deployment.yaml
  stable/spring-cloud-data-flow/templates/skipper-service.yaml
  stable/spring-cloud-data-flow/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#18662 [stable/prometheus-pushgateway] Follow the Call for maintainers
  stable/prometheus-pushgateway/.helmignore
  stable/prometheus-pushgateway/Chart.yaml
  stable/prometheus-pushgateway/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18493 [stable/sonarqube] Upgrade plugins.initContainerImage
  stable/sonarqube/Chart.yaml
  stable/sonarqube/README.md
  stable/sonarqube/templates/deployment.yaml
  stable/sonarqube/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16909 [stable/cerebro] Adding wvidana as collaborator
  stable/cerebro/.helmignore
  stable/cerebro/Chart.yaml
  stable/cerebro/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18674 [stable/redis-ha] Add missing sysctl imagePullPolicy
  stable/redis-ha/Chart.yaml
  stable/redis-ha/templates/redis-ha-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18613 [stable/kong] major breaking change: dbless and KIC by-default
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#18675 [stable/airflow] Typo fix
  stable/airflow/Chart.yaml
  stable/airflow/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18678 [stable/redis-ha] Change sysctl initContainer base image to busybox
  stable/redis-ha/Chart.yaml
  stable/redis-ha/README.md
  stable/redis-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18405 [stable/velero] Add priority classes
  stable/velero/Chart.yaml
  stable/velero/README.md
  stable/velero/templates/cleanup-crds.yaml
  stable/velero/templates/deployment.yaml
  stable/velero/templates/restic-daemonset.yaml
  stable/velero/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18646 [stable/cluster-autoscaler] Allow overriding the Capabilities.KubeVersion.GitVersion
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/README.md
  stable/cluster-autoscaler/templates/_helpers.tpl
  stable/cluster-autoscaler/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18604 [stable/metricbeat] Add rbac replicasets to apps apigroup
  stable/metricbeat/Chart.yaml
  stable/metricbeat/templates/clusterrole.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18687 [stable/grafana] Fix typo minAvailble to minAvailable
  stable/grafana/Chart.yaml
  stable/grafana/templates/poddisruptionbudget.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18103 [stable/jenkins] Change default serviceType to ClusterIP
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18598 [stable/prometheus-pushgateway] Compat k8s 1.16
  stable/prometheus-pushgateway/Chart.yaml
  stable/prometheus-pushgateway/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18719 [stable/memcached] - Add .Release.Namespace
  stable/memcached/Chart.yaml
  stable/memcached/templates/pdb.yaml
  stable/memcached/templates/servicemonitor.yaml
  stable/memcached/templates/statefulset.yaml
  stable/memcached/templates/svc.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#18668 [stable/wordpress] Fixes template reference in tls-secrets.yaml
  stable/wordpress/Chart.yaml
  stable/wordpress/templates/tls-secrets.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18704 [stable/mariadb] fix upgrading existing statefulsets
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
  stable/mariadb/templates/_helpers.tpl
  stable/mariadb/templates/master-statefulset.yaml
  stable/mariadb/templates/slave-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18550 [stable/postgresql] Add support to change the user and password for t…
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/statefulset.yaml
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18707 [stable/postgresql] bump major version
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/_helpers.tpl
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18374 [stable/prometheus-operator] Readme update of kube-proxy metrics bind address, pointing to multiple possible cm locations.
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18734 [stable/prometheus-operator] Allow annotations to be set on datasoure configmaps
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/grafana/configmaps-datasources.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18739 [stable/prometheus-operator] fix annotations typo
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/grafana/configmaps-datasources.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18742 [stable/prometheus-operator] Update grafana dependency
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/requirements.lock
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18750 [incubator/gogs] Add support for defined loadBalancerIP
  incubator/gogs/Chart.yaml
  incubator/gogs/README.md
  incubator/gogs/templates/service.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#17240 [stable/postgresql] add comment about use existed data
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18753 stable/jenkins: Update kubernetes plugin URL
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#18754 [stable/jenkins] support kubernetes credentials provider plugin
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/rbac.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#18755 [stable/redis-ha] Fix misleading README for exporter serviceMonitor
  stable/redis-ha/Chart.yaml
  stable/redis-ha/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17619 [stable/influxdb] changes from deployment to statefulset
  stable/influxdb/Chart.yaml
  stable/influxdb/README.md
  stable/influxdb/templates/pvc.yaml
  stable/influxdb/templates/statefulset.yaml
  stable/influxdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18172 [stable/fluent-bit] Add Retry_Limit parameter support for es output
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/config.yaml
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18379 [stable/kube-slack] Support pulling env vars from secrets
  stable/kube-slack/Chart.yaml
  stable/kube-slack/README.md
  stable/kube-slack/templates/deployment.yaml
  stable/kube-slack/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18626 [stable/sonarqube] add support of secret injection for sonar.properties
  stable/sonarqube/Chart.yaml
  stable/sonarqube/README.md
  stable/sonarqube/templates/deployment.yaml
  stable/sonarqube/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18714 [stable/sonarqube] fix ui test
  stable/sonarqube/Chart.yaml
  stable/sonarqube/templates/tests/test-config.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#18644 [stable/anchore-engine] make image_analyze_timeout_seconds configurable
  stable/anchore-engine/Chart.yaml
  stable/anchore-engine/templates/engine_configmap.yaml
  stable/anchore-engine/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#18716 [stable/sonarqube] configure persistence defaults
  stable/sonarqube/Chart.yaml
  stable/sonarqube/README.md
  stable/sonarqube/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#18441 [stable/postgresl] Point the chart to the postgresql release that includes postgis
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18763 stable/sealed-secrets: allow disable of controller installation
  stable/sealed-secrets/Chart.yaml
  stable/sealed-secrets/README.md
  stable/sealed-secrets/templates/NOTES.txt
  stable/sealed-secrets/templates/deployment.yaml
  stable/sealed-secrets/templates/service.yaml
  stable/sealed-secrets/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18726 [stable/pomerium] Setting Ingress Hosts from policy
  stable/pomerium/Chart.yaml
  stable/pomerium/README.md
  stable/pomerium/templates/NOTES.txt
  stable/pomerium/templates/ingress.yaml
  stable/pomerium/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18630 [stable/mongodb-replicaset] in retry_until only read the last mongo client line
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/init/on-start.sh
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18691 [stable/dokuwiki] bump major version
  stable/dokuwiki/Chart.yaml
  stable/dokuwiki/README.md
  stable/dokuwiki/templates/_helpers.tpl
  stable/dokuwiki/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18712 [stable/kubewatch] bump major version
  stable/kubewatch/Chart.yaml
  stable/kubewatch/README.md
  stable/kubewatch/templates/_helpers.tpl
  stable/kubewatch/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18746 [stable/orangehrm] bump major version
  stable/orangehrm/Chart.yaml
  stable/orangehrm/README.md
  stable/orangehrm/requirements.lock
  stable/orangehrm/requirements.yaml
  stable/orangehrm/templates/_helpers.tpl
  stable/orangehrm/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#16601 [stable/redis-ha] Update version of redis-exporter
  stable/redis-ha/Chart.yaml
  stable/redis-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#18621 [stable/k8s-spot-termination-handler] Add missing 'namespace'
  stable/k8s-spot-termination-handler/Chart.yaml
  stable/k8s-spot-termination-handler/templates/daemonset.yaml
  stable/k8s-spot-termination-handler/templates/serviceaccount.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18770 [stable/redis-ha] Fix Readme based on sysCtl change
  stable/redis-ha/Chart.yaml
  stable/redis-ha/README.md
  stable/redis-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18785 [stable/anchore-engine] set default image_analyze_timeout_seconds to 36000
  stable/anchore-engine/Chart.yaml
  stable/anchore-engine/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#18516 [stable/ambassador] Number of improvements
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/ci/crds.yaml
  stable/ambassador/templates/ambassador-pro-crd.yaml
  stable/ambassador/templates/ambassador-pro-ratelimit.yaml
  stable/ambassador/templates/ambassador-pro-redis.yaml
  stable/ambassador/templates/crd-delete.yaml
  stable/ambassador/templates/crd/authservice.yaml
  stable/ambassador/templates/crd/consulresolver.yaml
  stable/ambassador/templates/crd/filter.yaml
  stable/ambassador/templates/crd/filterpolicy.yaml
  stable/ambassador/templates/crd/kubernetesendpointresolver.yaml
  stable/ambassador/templates/crd/kubernetesserviceresolver.yaml
  stable/ambassador/templates/crd/mapping.yaml
  stable/ambassador/templates/crd/module.yaml
  stable/ambassador/templates/crd/ratelimit.yaml
  stable/ambassador/templates/crd/ratelimitservice.yaml
  stable/ambassador/templates/crd/tcpmapping.yaml
  stable/ambassador/templates/crd/tlscontext.yaml
  stable/ambassador/templates/crd/tracingservice.yaml
  stable/ambassador/templates/crds-rbac.yaml
  stable/ambassador/templates/crds.yaml
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XL

#18786 [stable/ambassador] Upgrade Ambassador Pro 0.9.1→0.10.0
  stable/ambassador/Chart.yaml
  stable/ambassador/OWNERS
  stable/ambassador/README.md
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18500 [stable/redis-ha] Updating Prometheus exporter support in for HAProxy
  stable/redis-ha/Chart.yaml
  stable/redis-ha/templates/redis-haproxy-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#18787 [stable/cerebro] be able to run with readOnlyRootFilesystem PSP
  stable/cerebro/Chart.yaml
  stable/cerebro/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18694 [stable/joomla] major version bump
  stable/joomla/Chart.yaml
  stable/joomla/README.md
  stable/joomla/requirements.lock
  stable/joomla/requirements.yaml
  stable/joomla/templates/_helpers.tpl
  stable/joomla/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18692 [stable/moodle] bump major version
  stable/moodle/Chart.yaml
  stable/moodle/README.md
  stable/moodle/requirements.lock
  stable/moodle/requirements.yaml
  stable/moodle/templates/_helpers.tpl
  stable/moodle/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18693 [stable/jasperreports] major version bump
  stable/jasperreports/Chart.yaml
  stable/jasperreports/README.md
  stable/jasperreports/requirements.lock
  stable/jasperreports/requirements.yaml
  stable/jasperreports/templates/_helpers.tpl
  stable/jasperreports/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18696 [stable/opencart] bump major version
  stable/opencart/Chart.yaml
  stable/opencart/README.md
  stable/opencart/requirements.lock
  stable/opencart/requirements.yaml
  stable/opencart/templates/_helpers.tpl
  stable/opencart/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18705 [stable/mediawiki] bump major version
  stable/mediawiki/Chart.yaml
  stable/mediawiki/README.md
  stable/mediawiki/requirements.lock
  stable/mediawiki/requirements.yaml
  stable/mediawiki/templates/_helpers.tpl
  stable/mediawiki/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18709 [stable/magento] bump major version
  stable/magento/Chart.yaml
  stable/magento/README.md
  stable/magento/requirements.lock
  stable/magento/requirements.yaml
  stable/magento/templates/_helpers.tpl
  stable/magento/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18689 [stable/drupal] major version bump
  stable/drupal/Chart.yaml
  stable/drupal/README.md
  stable/drupal/requirements.lock
  stable/drupal/requirements.yaml
  stable/drupal/templates/_helpers.tpl
  stable/drupal/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18695 [stable/odoo] bump major version
  stable/odoo/Chart.yaml
  stable/odoo/README.md
  stable/odoo/requirements.lock
  stable/odoo/requirements.yaml
  stable/odoo/templates/_helpers.tpl
  stable/odoo/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18700 [stable/osclass] bump major version
  stable/osclass/Chart.yaml
  stable/osclass/README.md
  stable/osclass/requirements.lock
  stable/osclass/requirements.yaml
  stable/osclass/templates/_helpers.tpl
  stable/osclass/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18701 [stable/owncloud] bump major version
  stable/owncloud/Chart.yaml
  stable/owncloud/README.md
  stable/owncloud/requirements.lock
  stable/owncloud/requirements.yaml
  stable/owncloud/templates/_helpers.tpl
  stable/owncloud/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18702 [stable/phpbb] bump major version
  stable/phpbb/Chart.yaml
  stable/phpbb/README.md
  stable/phpbb/requirements.lock
  stable/phpbb/requirements.yaml
  stable/phpbb/templates/_helpers.tpl
  stable/phpbb/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18703 [stable/prestashop] bump major version
  stable/prestashop/Chart.yaml
  stable/prestashop/README.md
  stable/prestashop/requirements.lock
  stable/prestashop/requirements.yaml
  stable/prestashop/templates/_helpers.tpl
  stable/prestashop/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18697 [stable/redmine] bump major version
  stable/redmine/Chart.yaml
  stable/redmine/README.md
  stable/redmine/requirements.lock
  stable/redmine/requirements.yaml
  stable/redmine/templates/_helpers.tpl
  stable/redmine/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18698 [stable/suitecrm] bump major version
  stable/suitecrm/Chart.yaml
  stable/suitecrm/README.md
  stable/suitecrm/requirements.lock
  stable/suitecrm/requirements.yaml
  stable/suitecrm/templates/_helpers.tpl
  stable/suitecrm/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18699 [stable/testlink] bump major version
  stable/testlink/Chart.yaml
  stable/testlink/README.md
  stable/testlink/requirements.lock
  stable/testlink/requirements.yaml
  stable/testlink/templates/_helpers.tpl
  stable/testlink/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18743 [stable/prometheus-operator] add resources field to admissionWebhooks jobs
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
  stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18475 stable/prometheus-postgres-exporter: fix typo in README
  stable/prometheus-postgres-exporter/Chart.yaml
  stable/prometheus-postgres-exporter/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18768 [stable/gocd] - GoCD agents should run postStart lifecycle hooks
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/README.md
  stable/gocd/templates/gocd-agent-deployment.yaml
  stable/gocd/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18769 [stable/gocd] - GoCD server should be able to have sidecar containers
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/README.md
  stable/gocd/templates/gocd-server-deployment.yaml
  stable/gocd/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17036 [stable/stolon] Stolon ssl
  stable/stolon/Chart.yaml
  stable/stolon/README.md
  stable/stolon/templates/certs.yaml
  stable/stolon/templates/hooks/create-cluster-job.yaml
  stable/stolon/templates/hooks/update-cluster-spec-job.yaml
  stable/stolon/templates/keeper-statefulset.yaml
  stable/stolon/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18166 [stable/redis-ha] Replace haproxy-exporter with official haproxy embedded prometheus exporter.
  stable/redis-ha/Chart.yaml
  stable/redis-ha/README.md
  stable/redis-ha/ci/haproxy-enabled-values.yaml
  stable/redis-ha/templates/_configs.tpl
  stable/redis-ha/templates/redis-haproxy-deployment.yaml
  stable/redis-ha/templates/redis-haproxy-service.yaml
  stable/redis-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M
