Repository helm/charts, pull requests merged in 2019-09, with the labels that each got.

#16673 [stable/grafana] Enabling extension of Role and ClusterRole rules.
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/clusterrole.yaml
  stable/grafana/templates/role.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16372 [stable/stackdriver-exporter] Add support for Prometheus Operator ServiceMonitor
  stable/stackdriver-exporter/Chart.yaml
  stable/stackdriver-exporter/README.md
  stable/stackdriver-exporter/templates/servicemonitor.yaml
  stable/stackdriver-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#16580 [stable/minio]: Add additional owners for MinIO Chart
  stable/minio/Chart.yaml
  stable/minio/OWNERS
Labels: Contribution Allowed, approved, lgtm, size/S

#16742 [stable/nextcloud] Allow to add custom labels on Ingress
  stable/nextcloud/Chart.yaml
  stable/nextcloud/README.md
  stable/nextcloud/templates/ingress.yaml
  stable/nextcloud/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16747 [stable/prometheus-operator] bumping Grafana chart version to fix CVE-2019-15043
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/requirements.lock
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16724 [stable/rabbitmq] Use stretch as minideb tag
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16725 [stable/postgresql] Use stretch as minideb tag
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16726 [stable/parse] Use stretch as minideb tag
  stable/parse/Chart.yaml
  stable/parse/README.md
  stable/parse/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16727 [stable/mongodb] Use stretch as minideb tag
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16728 [stable/mariadb] Use stretch as minideb tag
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
  stable/mariadb/values-production.yaml
  stable/mariadb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16729 [stable/ghost] Use stretch as minideb tag
  stable/ghost/Chart.yaml
  stable/ghost/README.md
  stable/ghost/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16723 [stable/redis] Use stretch as minideb tag
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/ci/production-sentinel-values.yaml
  stable/redis/ci/production-values.yaml
  stable/redis/templates/_helpers.tpl
  stable/redis/values-production.yaml
  stable/redis/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16711 [mongodb] Add separate affinity for arbiter pod
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/templates/statefulset-arbiter-rs.yaml
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16782 [stable/sysdig] fix example
  stable/sysdig/CHANGELOG.md
  stable/sysdig/Chart.yaml
  stable/sysdig/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#16788 [stable/pomerium] Pomerium v0.3.0 release
  stable/pomerium/Chart.yaml
  stable/pomerium/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#16739 [stable/jenkins] add support for gcs in backup cronjob
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#16682 [stable/aws-iam-authenticator] Fix README table
  stable/aws-iam-authenticator/Chart.yaml
  stable/aws-iam-authenticator/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16805 [stable/velero] updated velero default version to 1.1.0
  stable/velero/Chart.yaml
  stable/velero/README.md
  stable/velero/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15166 [stable/InfluxDB] Make livenessProbe and readinessProbe path configurable.
  stable/influxdb/Chart.yaml
  stable/influxdb/templates/deployment.yaml
  stable/influxdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16811 [stable/atlantis] Fix wrong arg for config
  stable/atlantis/Chart.yaml
  stable/atlantis/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#16812 [stable/kong] bump up Kong to 1.3
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#16256 [stable/redis-ha] Fix additionalAffinities indentation
  stable/redis-ha/Chart.yaml
  stable/redis-ha/templates/redis-ha-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16624 [stable/nginx-ingress] Add option to deploy deployment and daemonset
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-daemonset.yaml
  stable/nginx-ingress/templates/controller-deployment.yaml
  stable/nginx-ingress/templates/controller-hpa.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16628 [stable/grafana] Support ingress.extraPaths for grafana
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/ingress.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16737 [stable/external-dns] - update RBAC permission when crd.create=true
  stable/external-dns/Chart.yaml
  stable/external-dns/templates/clusterrole.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16656 [stable/metrics-server] bump metrics-server version
  stable/metrics-server/Chart.yaml
  stable/metrics-server/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16745 [stable/redis-ha] Updating OWNERS list.
  stable/redis-ha/Chart.yaml
  stable/redis-ha/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16523 [stable/prometheus-operator] Lower dependency req
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/OWNERS
  stable/prometheus-operator/hack/sync_grafana_dashboards.py
  stable/prometheus-operator/hack/sync_prometheus_rules.py
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-namespace.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-pod.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-workload.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-workloads-namespace.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/nodes.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/pods.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/statefulset.yaml
  stable/prometheus-operator/templates/grafana/dashboards/etcd.yaml
  stable/prometheus-operator/templates/grafana/dashboards/k8s-cluster-rsrc-use.yaml
  stable/prometheus-operator/templates/grafana/dashboards/k8s-node-rsrc-use.yaml
  stable/prometheus-operator/templates/grafana/dashboards/k8s-resources-cluster.yaml
  stable/prometheus-operator/templates/grafana/dashboards/k8s-resources-namespace.yaml
  stable/prometheus-operator/templates/grafana/dashboards/k8s-resources-pod.yaml
  stable/prometheus-operator/templates/grafana/dashboards/k8s-resources-workload.yaml
  stable/prometheus-operator/templates/grafana/dashboards/k8s-resources-workloads-namespace.yaml
  stable/prometheus-operator/templates/grafana/dashboards/nodes.yaml
  stable/prometheus-operator/templates/grafana/dashboards/persistentvolumesusage.yaml
  stable/prometheus-operator/templates/grafana/dashboards/pods.yaml
  stable/prometheus-operator/templates/grafana/dashboards/statefulset.yaml
  stable/prometheus-operator/templates/prometheus-operator/crd-alertmanager.yaml
  stable/prometheus-operator/templates/prometheus-operator/crd-podmonitor.yaml
  stable/prometheus-operator/templates/prometheus-operator/crd-prometheus.yaml
  stable/prometheus-operator/templates/prometheus-operator/crd-prometheusrules.yaml
  stable/prometheus-operator/templates/prometheus-operator/crd-servicemonitor.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/alertmanager.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/general.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/k8s.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-apps.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/node-network.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/node.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules/alertmanager.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules/etcd.yaml
  stable/prometheus-operator/templates/prometheus/rules/general.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules/k8s.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules/kube-apiserver.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules/kube-prometheus-node-alerting.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules/kube-prometheus-node-recording.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules/kube-scheduler.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules/kubernetes-absent.yaml
  stable/prometheus-operator/templates/prometheus/rules/kubernetes-apps.yaml
  stable/prometheus-operator/templates/prometheus/rules/kubernetes-resources.yaml
  stable/prometheus-operator/templates/prometheus/rules/kubernetes-storage.yaml
  stable/prometheus-operator/templates/prometheus/rules/kubernetes-system.yaml
  stable/prometheus-operator/templates/prometheus/rules/node-network.yaml
  stable/prometheus-operator/templates/prometheus/rules/node-time.yaml
  stable/prometheus-operator/templates/prometheus/rules/node.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules/prometheus-operator.yaml
  stable/prometheus-operator/templates/prometheus/rules/prometheus.rules.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XL

#16283 [stable/elasticsearch] add forceIpv6 flag so to be able to run in IPv6 env
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/README.md
  stable/elasticsearch/templates/configmap.yaml
  stable/elasticsearch/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16750 [stable/stackdriver-exporter] Correct servicemonitor name
  stable/stackdriver-exporter/Chart.yaml
  stable/stackdriver-exporter/templates/servicemonitor.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16806 [stable/dex] Add support to always display login screen
  stable/dex/Chart.yaml
  stable/dex/README.md
  stable/dex/templates/secret.yaml
  stable/dex/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16828 [stable/grafana] Fix README.md layout of table broken.
  stable/grafana/Chart.yaml
  stable/grafana/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16817 [stable/elasticsearch-exporter] Add ability to use existing secrets for SSL certs
  stable/elasticsearch-exporter/Chart.yaml
  stable/elasticsearch-exporter/README.md
  stable/elasticsearch-exporter/templates/cert-secret.yaml
  stable/elasticsearch-exporter/templates/deployment.yaml
  stable/elasticsearch-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#16819 [stable/home-assistant] Support zigbee, zwave, host-configs, and other host mounts
  stable/home-assistant/Chart.yaml
  stable/home-assistant/README.md
  stable/home-assistant/templates/deployment.yaml
  stable/home-assistant/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#16835 [stable/prometheus-mongodb-exporter] Redeploy pods on config changes.
  stable/prometheus-mongodb-exporter/Chart.yaml
  stable/prometheus-mongodb-exporter/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16342 small note about kafkaVersion parameter. Change default version
  stable/kafka-manager/Chart.yaml
  stable/kafka-manager/templates/configmap.yaml
  stable/kafka-manager/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16856 [stable/nginx-ingress] Support pod security policies on default backend
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/_helpers.tpl
  stable/nginx-ingress/templates/controller-psp.yaml
  stable/nginx-ingress/templates/controller-role.yaml
  stable/nginx-ingress/templates/controller-rolebinding.yaml
  stable/nginx-ingress/templates/controller-serviceaccount.yaml
  stable/nginx-ingress/templates/default-backend-deployment.yaml
  stable/nginx-ingress/templates/default-backend-psp.yaml
  stable/nginx-ingress/templates/default-backend-role.yaml
  stable/nginx-ingress/templates/default-backend-rolebinding.yaml
  stable/nginx-ingress/templates/default-backend-serviceaccount.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#16864 [stable/anchore-engine] Enterprise 2.1 update
  stable/anchore-engine/Chart.yaml
  stable/anchore-engine/README.md
  stable/anchore-engine/templates/NOTES.txt
  stable/anchore-engine/templates/analyzer_configmap.yaml
  stable/anchore-engine/templates/analyzer_deployment.yaml
  stable/anchore-engine/templates/api_deployment.yaml
  stable/anchore-engine/templates/catalog_deployment.yaml
  stable/anchore-engine/templates/engine_configmap.yaml
  stable/anchore-engine/templates/enterprise_configmap.yaml
  stable/anchore-engine/templates/enterprise_feeds_configmap.yaml
  stable/anchore-engine/templates/enterprise_feeds_deployment.yaml
  stable/anchore-engine/templates/enterprise_ui_config_secret.yaml
  stable/anchore-engine/templates/enterprise_ui_deployment.yaml
  stable/anchore-engine/templates/ingress.yaml
  stable/anchore-engine/templates/policy_engine_deployment.yaml
  stable/anchore-engine/templates/secrets.yaml
  stable/anchore-engine/templates/simplequeue_deployment.yaml
  stable/anchore-engine/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XL

#16780 [stable/rocketchat] Update README with HA configuration info
  stable/rocketchat/Chart.yaml
  stable/rocketchat/README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#16345 [sparkoperator]Support configure `enableBatchScheduler`
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/README.md
  incubator/sparkoperator/templates/spark-operator-deployment.yaml
  incubator/sparkoperator/templates/spark-operator-rbac.yaml
  incubator/sparkoperator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16815 [stable/prometehus-blackbox-exporter] Improve configurability.
  stable/prometheus-blackbox-exporter/Chart.yaml
  stable/prometheus-blackbox-exporter/README.md
  stable/prometheus-blackbox-exporter/templates/deployment.yaml
  stable/prometheus-blackbox-exporter/templates/poddisruptionbudget.yaml
  stable/prometheus-blackbox-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#16843 [stable/phpbb] Add affinity
  stable/phpbb/Chart.yaml
  stable/phpbb/README.md
  stable/phpbb/templates/deployment.yaml
  stable/phpbb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16662 [stable/wordpress] Parameterized the target port for https
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
  stable/wordpress/templates/svc.yaml
  stable/wordpress/values-production.yaml
  stable/wordpress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16730 [stable/external-dns] Added ServiceAccount annotations
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/serviceaccount.yaml
  stable/external-dns/values-production.yaml
  stable/external-dns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16836 [stable/drupal] Add affinity
  stable/drupal/Chart.yaml
  stable/drupal/README.md
  stable/drupal/templates/deployment.yaml
  stable/drupal/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16838 [stable/prestashop] Add affinity
  stable/prestashop/Chart.yaml
  stable/prestashop/README.md
  stable/prestashop/templates/deployment.yaml
  stable/prestashop/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16839 [stable/suitecrm] Add affinity
  stable/suitecrm/Chart.yaml
  stable/suitecrm/README.md
  stable/suitecrm/templates/deployment.yaml
  stable/suitecrm/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16840 [stable/testlink] Add affinity
  stable/testlink/Chart.yaml
  stable/testlink/README.md
  stable/testlink/templates/deployment.yaml
  stable/testlink/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16841 [stable/owncloud] Add affinity
  stable/owncloud/Chart.yaml
  stable/owncloud/README.md
  stable/owncloud/templates/deployment.yaml
  stable/owncloud/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16842 [stable/parse] Add affinity
  stable/parse/Chart.yaml
  stable/parse/README.md
  stable/parse/templates/dashboard-deployment.yaml
  stable/parse/templates/server-deployment.yaml
  stable/parse/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16844 [stable/opencart] Add affinity
  stable/opencart/Chart.yaml
  stable/opencart/README.md
  stable/opencart/templates/deployment.yaml
  stable/opencart/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16845 [stable/orangehrm] Add affinity
  stable/orangehrm/Chart.yaml
  stable/orangehrm/README.md
  stable/orangehrm/templates/deployment.yaml
  stable/orangehrm/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16846 [stable/osclass] Add affinity
  stable/osclass/Chart.yaml
  stable/osclass/README.md
  stable/osclass/templates/deployment.yaml
  stable/osclass/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16847 [stable/jasperreports] Add affinity
  stable/jasperreports/Chart.yaml
  stable/jasperreports/README.md
  stable/jasperreports/templates/deployment.yaml
  stable/jasperreports/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16848 [stable/mediawiki] Add affinity
  stable/mediawiki/Chart.yaml
  stable/mediawiki/README.md
  stable/mediawiki/templates/deployment.yaml
  stable/mediawiki/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16849 [stable/odoo] Add affinity
  stable/odoo/Chart.yaml
  stable/odoo/README.md
  stable/odoo/templates/deployment.yaml
  stable/odoo/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16851 [stable/ghost] Add affinity
  stable/ghost/Chart.yaml
  stable/ghost/README.md
  stable/ghost/templates/deployment.yaml
  stable/ghost/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16833 [stable/redis] Egress network policy for redis cluster
  stable/redis/Chart.yaml
  stable/redis/templates/networkpolicy.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16891 [stable/sysdig] Add configmaps, secrets access and more config settings
  stable/sysdig/CHANGELOG.md
  stable/sysdig/Chart.yaml
  stable/sysdig/templates/clusterrole.yaml
  stable/sysdig/templates/daemonset.yaml
  stable/sysdig/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#16797 [stable/filebeat] Fix image tag in README
  stable/filebeat/Chart.yaml
  stable/filebeat/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#16677 [stable/redis-ha] Add tolerations to HAProxy deployment.
  stable/redis-ha/Chart.yaml
  stable/redis-ha/templates/redis-haproxy-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16906 [stable/ambassador] Bump Ambassador to 0.77.0
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#16814 [stable/prometheus-operator] Sync prometheus operator dashboard and rules
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/hack/sync_grafana_dashboards.py
  stable/prometheus-operator/hack/sync_prometheus_rules.py
  stable/prometheus-operator/templates/grafana/dashboards-1.14/node-cluster-rsrc-use.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/node-rsrc-use.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/node-exporter.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/node-exporter.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XXL

#16896 [stable/grafana]: update grafana
  stable/grafana/Chart.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16004 Fixing restic env issue #15998
  stable/velero/Chart.yaml
  stable/velero/templates/restic-daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16876 [incubator/sparkoperator] Support podAnnotations
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/README.md
  incubator/sparkoperator/templates/spark-operator-deployment.yaml
  incubator/sparkoperator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15978 [stable/concourse] add new parameter for Concourse 5.5
  stable/concourse/Chart.yaml
  stable/concourse/README.md
  stable/concourse/templates/web-deployment.yaml
  stable/concourse/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#16933 [stable/mariadb] fix annotations example
  stable/mariadb/Chart.yaml
  stable/mariadb/values-production.yaml
  stable/mariadb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16936 Fix #10921
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-service.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16354 Add .gitattributes to fix language stats bar
  .gitattributes
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#16918 [stable/grafana] Fix some typo and formats
  stable/grafana/Chart.yaml
  stable/grafana/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16905 [stable/couchbase] Update to version 1.2.1
  stable/couchbase-operator/Chart.yaml
  stable/couchbase-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16824 [stable/redis-ha] Add a dedicated port in haproxy for redis slaves
  stable/redis-ha/Chart.yaml
  stable/redis-ha/README.md
  stable/redis-ha/templates/redis-ha-configmap.yaml
  stable/redis-ha/templates/redis-haproxy-deployment.yaml
  stable/redis-ha/templates/redis-haproxy-service.yaml
  stable/redis-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#16954 [stable/gocd] Bump up GoCD Version to 19.8.0
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#16958 [stable/grafana] add support for deployment labels
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16976 [stable/odoo] Fix Ingress secret for multiple hosts
  stable/odoo/Chart.yaml
  stable/odoo/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16983 [stable/concourse] Bump `imageTag` to match actual released version
  stable/concourse/Chart.yaml
  stable/concourse/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16959 [stable/openebs] Update charts to 1.2.0 release
  stable/openebs/Chart.yaml
  stable/openebs/README.md
  stable/openebs/templates/clusterrole.yaml
  stable/openebs/templates/cm-node-disk-manager.yaml
  stable/openebs/templates/daemonset-ndm.yaml
  stable/openebs/templates/deployment-admission-server.yaml
  stable/openebs/templates/deployment-local-provisioner.yaml
  stable/openebs/templates/deployment-maya-apiserver.yaml
  stable/openebs/templates/deployment-maya-provisioner.yaml
  stable/openebs/templates/deployment-maya-snapshot-operator.yaml
  stable/openebs/templates/deployment-ndm-operator.yaml
  stable/openebs/templates/service-admission-server.yaml
  stable/openebs/templates/service-maya-apiserver.yaml
  stable/openebs/templates/validationwebhook.yaml
  stable/openebs/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#16993 [stable/sematext-agent] simplify volumes and volume mounts
  stable/sematext-agent/Chart.yaml
  stable/sematext-agent/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#16992 [stable/redmine] Update dependencies version
  stable/redmine/Chart.yaml
  stable/redmine/requirements.lock
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16358 [stable/memcached] Add updateStrategy configuration option
  stable/memcached/Chart.yaml
  stable/memcached/README.md
  stable/memcached/templates/statefulset.yaml
  stable/memcached/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16960 [stable/velero] Fix Restic DaemonSet template syntax
  stable/velero/Chart.yaml
  stable/velero/templates/restic-daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#16977 [stable/prometheus-operator] Add conditional for prometheus.ingress.hosts
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/alertmanager/alertmanager.yaml
  stable/prometheus-operator/templates/prometheus/prometheus.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16338 [stable/pomerium] Scale out improvements
  stable/pomerium/Chart.yaml
  stable/pomerium/README.md
  stable/pomerium/templates/authenticate-deployment.yaml
  stable/pomerium/templates/authorize-deployment.yaml
  stable/pomerium/templates/authorize-service.yaml
  stable/pomerium/templates/proxy-deployment.yaml
  stable/pomerium/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#17027 [stable/phpmyadmin] Add miguelaeh to OWNERS
  stable/phpmyadmin/Chart.yaml
  stable/phpmyadmin/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17028 [stable/wordpress] Add miguelaeh to OWNERS
  stable/wordpress/Chart.yaml
  stable/wordpress/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17029 [stable/nats] Add miguelaeh to OWNERS
  stable/nats/Chart.yaml
  stable/nats/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17030 [stable/joomla] Add miguelaeh to OWNERS
  stable/joomla/Chart.yaml
  stable/joomla/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17031 [stable/testlink] Add miguelaeh to OWNERS
  stable/testlink/Chart.yaml
  stable/testlink/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17032 [stable/ghost] Add miguelaeh to OWNERS
  stable/ghost/Chart.yaml
  stable/ghost/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16785 [stable/collabora-code] fixes #14976 reopened due to regression in PR #14981 (v1.0.4)
  stable/collabora-code/Chart.yaml
  stable/collabora-code/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17004 [stable/prometheus-operator] Add walCompression to CRD and bump chart version
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/prometheus-operator/crd-prometheus.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17046 [stable/prometheus-operator] walCompression of wrong type
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/prometheus-operator/crd-prometheus.yaml
  stable/prometheus-operator/templates/prometheus/prometheus.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16531 [stable/traefik] add maxIdleConnsPerHost
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/configmap.yaml
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16709 Fix haproxy check redis master configuration
  stable/redis-ha/Chart.yaml
  stable/redis-ha/README.md
  stable/redis-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16910 [stable/sparkoperator] Fix spark-operator charts issue
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/templates/spark-operator-deployment.yaml
  incubator/sparkoperator/templates/webhook-init-job.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17050 [stable/spring-cloud-data-flow] Update configs for additional vars
  stable/spring-cloud-data-flow/Chart.yaml
  stable/spring-cloud-data-flow/README.md
  stable/spring-cloud-data-flow/templates/server-deployment.yaml
  stable/spring-cloud-data-flow/templates/server-service.yaml
  stable/spring-cloud-data-flow/templates/skipper-deployment.yaml
  stable/spring-cloud-data-flow/templates/skipper-service.yaml
  stable/spring-cloud-data-flow/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#16111 [stable/traefik]: reduce RBAC scope if one namespace is handled
  stable/traefik/Chart.yaml
  stable/traefik/templates/_helpers.tpl
  stable/traefik/templates/rbac.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15902 Fix typo in title and better narrative
  README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#17037 [stable/nginx-ingress] Add substitution for containerPorts from values
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/templates/controller-daemonset.yaml
  stable/nginx-ingress/templates/controller-deployment.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17026 [stable/rabbitmq] Add miguelaeh to OWNERS
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17021 [stable/mongodb] Add miguelaeh to OWNERS
  stable/mongodb/Chart.yaml
  stable/mongodb/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17023 [stable/external-dns] Add miguelaeh to OWNERS
  stable/external-dns/Chart.yaml
  stable/external-dns/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17024 [stable/mariadb] Add miguelaeh to OWNERS
  stable/mariadb/Chart.yaml
  stable/mariadb/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17005 [stable/odoo] Add miguelaeh to OWNERS
  stable/odoo/Chart.yaml
  stable/odoo/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17006 [stable/dokuwiki] Add miguelaeh to OWNERS
  stable/dokuwiki/Chart.yaml
  stable/dokuwiki/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17007 [stable/drupal] Add miguelaeh to OWNERS
  stable/drupal/Chart.yaml
  stable/drupal/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17008 [stable/osclass] Add miguelaeh to OWNERS
  stable/osclass/Chart.yaml
  stable/osclass/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17009 [stable/prestashop] Add miguelaeh to OWNERS
  stable/prestashop/Chart.yaml
  stable/prestashop/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17010 [stable/redmine] Add miguelaeh to OWNERS
  stable/redmine/Chart.yaml
  stable/redmine/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17011 [stable/mediawiki] Add miguelaeh to OWNERS
  stable/mediawiki/Chart.yaml
  stable/mediawiki/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17012 [stable/kubewatch] Add miguelaeh to OWNERS
  stable/kubewatch/Chart.yaml
  stable/kubewatch/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17013 [stable/phpbb] Add miguelaeh to OWNERS
  stable/phpbb/Chart.yaml
  stable/phpbb/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17015 [stable/orangehrm] Add miguelaeh to OWNERS
  stable/orangehrm/Chart.yaml
  stable/orangehrm/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17016 [stable/opencart] Add miguelaeh to OWNERS
  stable/opencart/Chart.yaml
  stable/opencart/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17017 [stable/postgresql] Add miguelaeh to OWNERS
  stable/postgresql/Chart.yaml
  stable/postgresql/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17018 [stable/parse] Add miguelaeh to OWNERS
  stable/parse/Chart.yaml
  stable/parse/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17019 [stable/suitecrm] Add miguelaeh to OWNERS
  stable/suitecrm/Chart.yaml
  stable/suitecrm/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17020 [stable/moodle] Add miguelaeh to OWNERS
  stable/moodle/Chart.yaml
  stable/moodle/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17022 [stable/jasperreports] Add miguelaeh to OWNERS
  stable/jasperreports/Chart.yaml
  stable/jasperreports/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17014 [stable/redis] Add miguelaeh to OWNERS
  stable/redis/Chart.yaml
  stable/redis/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17062 [stable/airflow] Quote command line parameters in create connection script
  stable/airflow/Chart.yaml
  stable/airflow/templates/secret-connections.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#17057 [stable/prometheus-operator] Update kube-state-metrics to 2.3.1 and grafana to 3.8.11.
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/requirements.lock
  stable/prometheus-operator/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17025 [stable/phabricator] Add miguelaeh to OWNERS
  stable/phabricator/Chart.yaml
  stable/phabricator/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17033 [stable/owncloud] Add miguelaeh to OWNERS
  stable/owncloud/Chart.yaml
  stable/owncloud/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17065 [stable/falco] Performs a rollingUpdate when you change rules or sett…
  stable/falco/CHANGELOG.md
  stable/falco/Chart.yaml
  stable/falco/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#17066 [incubator/zookeeper] Fixes setting "zookeeper.log.threshold" option
  incubator/zookeeper/Chart.yaml
  incubator/zookeeper/templates/config-script.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17067 [stable/traefik] Disable acme volume if kvprovider is configured
  stable/traefik/Chart.yaml
  stable/traefik/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17052 [stable/atlantis] Fix typo on `values.yml` for `environmentSecrets`
  stable/atlantis/Chart.yaml
  stable/atlantis/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17081 [stable/ambassador] Bump Ambassador to v0.78.0
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#17084 [stable/prometheus-operator]: upgrade alertmanager
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#16513 [stable/traefik] backoff storeconfig job
  stable/traefik/Chart.yaml
  stable/traefik/templates/storeconfig-job.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#16464 [stable/traefik] Updated acme storage location to be configurable
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/configmap.yaml
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17087 [stable/elasticsearch-exporter] Fix spacing issue in volume mount
  stable/elasticsearch-exporter/Chart.yaml
  stable/elasticsearch-exporter/README.md
  stable/elasticsearch-exporter/templates/deployment.yaml
  stable/elasticsearch-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#16722 [stable/influxdb] Add support for Azure to backup job
  stable/influxdb/Chart.yaml
  stable/influxdb/templates/backup-cronjob.yaml
  stable/influxdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#17095 [stable/redis] Fix svc for redis with sentinel
  stable/redis/Chart.yaml
  stable/redis/templates/redis-with-sentinel-svc.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16949 [stable/jenkins] display error when admin user does not exist.
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/config.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#15345 [incubator/kafka] Adding the ability to define a pod disruption budget for brokers
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
  incubator/kafka/templates/podisruptionbudget.yaml
  incubator/kafka/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17074 [stable/dex] Support frontend config values
  stable/dex/Chart.yaml
  stable/dex/README.md
  stable/dex/templates/secret.yaml
  stable/dex/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17117 [stable/dex] Update default dex app version to v2.19.0
  stable/dex/Chart.yaml
  stable/dex/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16902 Change copyright to "The Helm Authors"
  LICENSE
Labels: Contribution Allowed, approved, lgtm, size/XS

#16331 [stable/nfs-server-provisioner] fix deployment when not creating storage class
  stable/nfs-server-provisioner/Chart.yaml
  stable/nfs-server-provisioner/templates/storageclass.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16741 [incubator/etcd] implement TLS/SSL for client and peers in etcd
  incubator/etcd/Chart.yaml
  incubator/etcd/README.md
  incubator/etcd/templates/_helpers.tpl
  incubator/etcd/templates/statefulset.yaml
  incubator/etcd/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#15801 [stable/prometheus-rabbitmq-exporter] ServiceMonitor Port Bugfix
  stable/prometheus-rabbitmq-exporter/Chart.yaml
  stable/prometheus-rabbitmq-exporter/templates/servicemonitor.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16922 [stable/openldap] Add documentation for 'persistence.existingClaim'
  stable/openldap/Chart.yaml
  stable/openldap/README.md
  stable/openldap/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16877 [stable/metabase] Increase livenessProbe timeout from 5 to 30 seconds
  stable/metabase/Chart.yaml
  stable/metabase/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16394 [stable/prometheus] Added /nodes/metrics permission to prometheus server
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/server-clusterrole.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17130 [stable/grafana] Fix indentation of pod template
  stable/grafana/Chart.yaml
  stable/grafana/templates/_pod.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16929 [stable/jenkins] add master.JCasC.defaultConfig
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/_helpers.tpl
  stable/jenkins/templates/config.yaml
  stable/jenkins/templates/jcasc-config.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#17092 [stable/rabbitmq] Metrics: use ipv4 to connect to rabbit.
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/templates/statefulset.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S
