Repository helm/charts, pull requests merged in 2019-01, with the labels that each got.

#10323 [stable/bookstack] upgrade bookstack to 0.24.3
  stable/bookstack/Chart.yaml
  stable/bookstack/README.md
  stable/bookstack/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10326 upgrade elasticsearch
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/README.md
  stable/elasticsearch/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#10332 [bitnami/postgresql] Fix creating initdb scripts from values.yaml
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/initialization-configmap.yaml
  stable/postgresql/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10325 [stable/prometheus-operator] Use proper k8s image registry
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10312 [stable/redis] Process template directives in affinity parameters
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/templates/redis-master-statefulset.yaml
  stable/redis/templates/redis-slave-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10204 Trim global section to avoid empty line to be indented
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/server-configmap.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10336 [stable/rabbitmq] Add Ingress Path parameter
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/ingress.yaml
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10335 [stable/prestashop] Add ingress
  stable/prestashop/Chart.yaml
  stable/prestashop/README.md
  stable/prestashop/templates/_helpers.tpl
  stable/prestashop/templates/deployment.yaml
  stable/prestashop/templates/externaldb-secrets.yaml
  stable/prestashop/templates/ingress.yaml
  stable/prestashop/templates/prestashop-pvc.yaml
  stable/prestashop/templates/secrets.yaml
  stable/prestashop/templates/svc.yaml
  stable/prestashop/templates/tls-secrets.yaml
  stable/prestashop/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#10337 [stable/elasticsearch] Tag roles for master and data
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/templates/data-statefulset.yaml
  stable/elasticsearch/templates/master-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10338 [stable/mariadb] Add support to existing configMaps as init scripts
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
  stable/mariadb/templates/_helpers.tpl
  stable/mariadb/templates/initialization-configmap.yaml
  stable/mariadb/templates/master-statefulset.yaml
  stable/mariadb/values-production.yaml
  stable/mariadb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#10198 [stable/envoy] bump envoy to 1.9.0
  stable/envoy/.helmignore
  stable/envoy/Chart.yaml
  stable/envoy/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#10199 [stable/hadoop] Hadoop bump to 2.9.0 and some cleanup
  stable/hadoop/Chart.yaml
  stable/hadoop/README.md
  stable/hadoop/templates/NOTES.txt
  stable/hadoop/templates/_helpers.tpl
  stable/hadoop/templates/hadoop-configmap.yaml
  stable/hadoop/templates/hdfs-dn-pdb.yaml
  stable/hadoop/templates/hdfs-dn-pvc.yaml
  stable/hadoop/templates/hdfs-dn-statefulset.yaml
  stable/hadoop/templates/hdfs-dn-svc.yaml
  stable/hadoop/templates/hdfs-nn-pdb.yaml
  stable/hadoop/templates/hdfs-nn-pvc.yaml
  stable/hadoop/templates/hdfs-nn-statefulset.yaml
  stable/hadoop/templates/hdfs-nn-svc.yaml
  stable/hadoop/templates/yarn-nm-pdb.yaml
  stable/hadoop/templates/yarn-nm-statefulset.yaml
  stable/hadoop/templates/yarn-nm-svc.yaml
  stable/hadoop/templates/yarn-rm-pdb.yaml
  stable/hadoop/templates/yarn-rm-statefulset.yaml
  stable/hadoop/templates/yarn-rm-svc.yaml
  stable/hadoop/templates/yarn-ui-svc.yaml
  stable/hadoop/tools/calc_resources.sh
  stable/hadoop/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#10314 [stable/postgresql] Request resource limits for initContainers
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10220 [stable/mm-te] bump MM-te to 5.6.2
  stable/mattermost-team-edition/Chart.yaml
  stable/mattermost-team-edition/README.md
  stable/mattermost-team-edition/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#10263 [stable/kong] Update Kong role to match users params
  stable/kong/Chart.yaml
  stable/kong/templates/controller-rbac-role.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10339 [stable/mongodb-replicaset] Add priority class to pods
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/README.md
  stable/mongodb-replicaset/templates/mongodb-statefulset.yaml
  stable/mongodb-replicaset/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10345 [stable/fluentd-elasticsearch] deprecate fluentd-elasticsearch
  stable/fluentd-elasticsearch/Chart.yaml
  stable/fluentd-elasticsearch/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#10301 Fix node problem detector
  stable/node-problem-detector/Chart.yaml
  stable/node-problem-detector/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#10092 [stable/prometheus-operator] Custom API Group support (#10091)
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/alertmanager/alertmanager.yaml
  stable/prometheus-operator/templates/alertmanager/rules/all.rules.yaml
  stable/prometheus-operator/templates/alertmanager/rules/kube-etcd.rules.yaml
  stable/prometheus-operator/templates/alertmanager/servicemonitor.yaml
  stable/prometheus-operator/templates/exporters/core-dns/servicemonitor.yaml
  stable/prometheus-operator/templates/exporters/kube-api-server/servicemonitor.yaml
  stable/prometheus-operator/templates/exporters/kube-controller-manager/servicemonitor.yaml
  stable/prometheus-operator/templates/exporters/kube-dns/servicemonitor.yaml
  stable/prometheus-operator/templates/exporters/kube-etcd/servicemonitor.yaml
  stable/prometheus-operator/templates/exporters/kube-scheduler/servicemonitor.yaml
  stable/prometheus-operator/templates/exporters/kube-state-metrics/serviceMonitor.yaml
  stable/prometheus-operator/templates/exporters/kubelet/servicemonitor.yaml
  stable/prometheus-operator/templates/exporters/node-exporter/servicemonitor.yaml
  stable/prometheus-operator/templates/prometheus-operator/clusterrole.yaml
  stable/prometheus-operator/templates/prometheus-operator/crd-alertmanager.yaml
  stable/prometheus-operator/templates/prometheus-operator/crd-prometheus.yaml
  stable/prometheus-operator/templates/prometheus-operator/crd-prometheusrules.yaml
  stable/prometheus-operator/templates/prometheus-operator/crd-servicemonitor.yaml
  stable/prometheus-operator/templates/prometheus-operator/deployment.yaml
  stable/prometheus-operator/templates/prometheus-operator/servicemonitor.yaml
  stable/prometheus-operator/templates/prometheus/prometheus.yaml
  stable/prometheus-operator/templates/prometheus/servicemonitor.yaml
  stable/prometheus-operator/templates/prometheus/servicemonitors.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#8959 Adding support for externally defined adapter rules
  stable/prometheus-adapter/Chart.yaml
  stable/prometheus-adapter/README.md
  stable/prometheus-adapter/templates/custom-metrics-apiserver-deployment.yaml
  stable/prometheus-adapter/templates/custom-metrics-configmap.yaml
  stable/prometheus-adapter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#7868 Tomcat improvements
  stable/tomcat/Chart.yaml
  stable/tomcat/README.md
  stable/tomcat/templates/appsrv.yaml
  stable/tomcat/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test

#8314 postgresql/clusterIp
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/svc.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9457 [stable/influx] Add support for pod affinities and tolerations
  stable/influxdb/Chart.yaml
  stable/influxdb/templates/deployment.yaml
  stable/influxdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#9479 [stable/hackmd] Bump version to 1.2.1
  stable/hackmd/Chart.yaml
  stable/hackmd/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#9835 Add configurable `podAnnotations` to openvpn chart
  stable/openvpn/Chart.yaml
  stable/openvpn/README.md
  stable/openvpn/templates/openvpn-deployment.yaml
  stable/openvpn/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10327 upgrade kibana
  stable/kibana/Chart.yaml
  stable/kibana/README.md
  stable/kibana/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#9814 [stable/prometheus-operator]Generate a complete Kubernetes Service
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/NOTES.txt
  stable/prometheus-operator/templates/alertmanager/service.yaml
  stable/prometheus-operator/templates/prometheus-operator/service.yaml
  stable/prometheus-operator/templates/prometheus/service.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#10328 upgrade logstash
  stable/logstash/Chart.yaml
  stable/logstash/README.md
  stable/logstash/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#10329 upgrade auditbeat
  stable/auditbeat/Chart.yaml
  stable/auditbeat/README.md
  stable/auditbeat/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#10347 Makes sense to have rollingUpgrade as default
  stable/prometheus/Chart.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#10262 [stable/ark] Fix home URL and add icon
  stable/ark/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#10272 [stable/prometheus-redis-exporter] Update image to 0.25.0
  stable/prometheus-redis-exporter/Chart.yaml
  stable/prometheus-redis-exporter/README.md
  stable/prometheus-redis-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#10348 upgrade to 6.5.4
  stable/filebeat/Chart.yaml
  stable/filebeat/README.md
  stable/filebeat/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#10352 [stable/karma] update to v0.20
  stable/karma/Chart.yaml
  stable/karma/README.md
  stable/karma/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#10354 [stable/fluentd-elasticsearch] better deprecation info
  stable/fluentd-elasticsearch/Chart.yaml
  stable/fluentd-elasticsearch/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#10346 [stable/mongodb] Fixes Helm install command for MongoDB with a replica set
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10350 [stable/graphite] deprecate chart
  stable/graphite/Chart.yaml
  stable/graphite/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10344 [stable/sonarqube] Fix for issue #10195
  stable/sonarqube/Chart.yaml
  stable/sonarqube/templates/copy-plugins.yaml
  stable/sonarqube/templates/deployment.yaml
  stable/sonarqube/templates/install-plugins.yaml
  stable/sonarqube/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#10377 [stable/rabbitmq] Reduce readiness/liveness probes frequency
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10378 [stable/mariadb] Allow using existingClaim as 'data' directory
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
  stable/mariadb/templates/master-statefulset.yaml
  stable/mariadb/values-production.yaml
  stable/mariadb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#10380 [stable/rabbitmq] Update README.md with readiness probes values
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#9583 [stable/sumlogic-fluentd] Supply SumoLogic collector URL via existing secret
  stable/sumologic-fluentd/Chart.yaml
  stable/sumologic-fluentd/README.md
  stable/sumologic-fluentd/templates/NOTES.txt
  stable/sumologic-fluentd/templates/daemonset.yaml
  stable/sumologic-fluentd/templates/secrets.yaml
  stable/sumologic-fluentd/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#10384 recent change broke additional service monitors
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/prometheus/servicemonitors.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#10353 charts/stable/kiam: define tls secret name instead of tlsFiles
  stable/kiam/Chart.yaml
  stable/kiam/README.md
  stable/kiam/ci/test-values.yaml
  stable/kiam/templates/agent-daemonset.yaml
  stable/kiam/templates/agent-secret.yaml
  stable/kiam/templates/server-daemonset.yaml
  stable/kiam/templates/server-secret.yaml
  stable/kiam/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#10333 [stable/airflow] revert postgres sub-chart values to match stable/pos…
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/templates/configmap-airflow.yaml
  stable/airflow/templates/secrets.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#10359 stable/unifi: Replace "addSetfcap" option with simply adding that capability when "runAsRoot" is not set to true
  stable/unifi/Chart.yaml
  stable/unifi/README.md
  stable/unifi/templates/deployment.yaml
  stable/unifi/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#10388 [stable/redis] Fix redis extra flags
  stable/redis/Chart.yaml
  stable/redis/ci/default-values.yaml
  stable/redis/templates/redis-master-statefulset.yaml
  stable/redis/templates/redis-slave-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#9897 [stable/rabbitmq-ha] Allow defintions to be overwritten in existing secret
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/templates/secret.yaml
  stable/rabbitmq-ha/templates/statefulset.yaml
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10393 [stable/gocd] readme typo
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10294 [stable/postgresql] Fix `initdbScripts`; add `postgresqlExtendedConf` to pass appended configuration via values
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/extended-config-configmap.yaml
  stable/postgresql/templates/initialization-configmap.yaml
  stable/postgresql/templates/statefulset.yaml
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#10394 [stable/phpbb] Avoid setting SMTP env. variables when SMTP parameters are not set
  stable/phpbb/Chart.yaml
  stable/phpbb/templates/NOTES.txt
  stable/phpbb/templates/_helpers.tpl
  stable/phpbb/templates/apache-pvc.yaml
  stable/phpbb/templates/deployment.yaml
  stable/phpbb/templates/externaldb-secrets.yaml
  stable/phpbb/templates/phpbb-pvc.yaml
  stable/phpbb/templates/secrets.yaml
  stable/phpbb/templates/svc.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#9179 [stable/kubernetes-dashboard] - Add support for gce-ingress integration
  stable/kubernetes-dashboard/Chart.yaml
  stable/kubernetes-dashboard/README.md
  stable/kubernetes-dashboard/templates/ingress.yaml
  stable/kubernetes-dashboard/templates/svc.yaml
  stable/kubernetes-dashboard/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#9124 [stable/elasticsearch] better chown in init containers
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/README.md
  stable/elasticsearch/templates/data-statefulset.yaml
  stable/elasticsearch/templates/master-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#10187 minio/ ability to set cluster domain name
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/templates/statefulset.yaml
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10307 [stable/grafana] Fix persistence by chowning /var/lib/grafana
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/deployment.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#10398 [stable/redis] Upgrade exporter to 0.25.0.
  stable/redis/Chart.yaml
  stable/redis/values-production.yaml
  stable/redis/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#10298 [stable/elastabot] allow customization of elastalert index prefix
  stable/elastabot/Chart.yaml
  stable/elastabot/README.md
  stable/elastabot/templates/configmap.yaml
  stable/elastabot/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#10210 [stable/prometheus] added poddisruptionbudgets view to kubeStateMetrics clusterrole
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/kube-state-metrics-clusterrole.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10320 [prometheus-operator] update dependencies
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/requirements.lock
  stable/prometheus-operator/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9141 [stable/rabbitmq-ha] Convert alerts ConfigMap to PrometheusRule
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/templates/alerts.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#10386 Further update of kong role to be dynamic based on ingressClass
  stable/kong/Chart.yaml
  stable/kong/templates/controller-rbac-role.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10403 fixes #10267 when executed with helm template
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/rbac.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10406 Update documentation according to major version 1.0.0
  stable/kubernetes-dashboard/Chart.yaml
  stable/kubernetes-dashboard/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#9630 [incubator/zookeeper] fix headless service targetPort
  incubator/zookeeper/Chart.yaml
  incubator/zookeeper/templates/service-headless.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10392 [stable/external-dns] Conditionally set cloudflare flags
  stable/external-dns/Chart.yaml
  stable/external-dns/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10373 [stable/centrifugo] Update centrifugo to 2.1.0
  stable/centrifugo/.helmignore
  stable/centrifugo/Chart.yaml
  stable/centrifugo/OWNERS
  stable/centrifugo/README.md
  stable/centrifugo/templates/_helpers.tpl
  stable/centrifugo/templates/configmap.yaml
  stable/centrifugo/templates/deployment.yaml
  stable/centrifugo/templates/ingress.yaml
  stable/centrifugo/templates/secret.yaml
  stable/centrifugo/templates/service.yaml
  stable/centrifugo/templates/tests/centrifugo-config-test.yaml
  stable/centrifugo/templates/tests/centrifugo-test.yaml
  stable/centrifugo/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#10364 Allow Labels in Ingress Resource
  stable/consul/Chart.yaml
  stable/consul/templates/consul-ingress.yaml
  stable/consul/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10278 [stable/efs-provisioner] Add support for priorityClasses
  stable/efs-provisioner/Chart.yaml
  stable/efs-provisioner/templates/deployment.yaml
  stable/efs-provisioner/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10261 [stable/cerebro] Add png logo to be displayed in https://hub.helm.sh
  stable/cerebro/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10259 [stable/bitcoind] Add png logo to be displayed in https://hub.helm.sh
  stable/bitcoind/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#10404 [node-problem-detector] parameterize location of logdir to make it run on RHEL and upgrade to latest release
  stable/node-problem-detector/Chart.yaml
  stable/node-problem-detector/README.md
  stable/node-problem-detector/templates/daemonset.yaml
  stable/node-problem-detector/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#10390 [stable/prometheus-operator] Set default for svc monitor selector
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/prometheus/prometheus.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10399 [stable/jenkins] add namespace flag for port-forwarding in jenkins notes
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9796 [stable/falco] Add checksum annotations to DaemonSet so that rolling upgrades work when changing ConfigMaps
  stable/sysdig/CHANGELOG.md
  stable/sysdig/Chart.yaml
  stable/sysdig/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#10411 Fix typo on busybox tag for grafana chart values
  stable/grafana/Chart.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10416 [stable/concourse] Fix variable references in NOTES.txt
  stable/concourse/Chart.yaml
  stable/concourse/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10313 Atlantis ingress bug with port
  stable/atlantis/Chart.yaml
  stable/atlantis/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10371 [stable/memcached] Add pod annotations
  stable/memcached/Chart.yaml
  stable/memcached/README.md
  stable/memcached/templates/statefulset.yaml
  stable/memcached/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9390 Expose livenessProbe and readinessProbe headers to consumer (in stable/wordpress)
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
  stable/wordpress/templates/deployment.yaml
  stable/wordpress/values-production.yaml
  stable/wordpress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#9312 [stable/rabbitmq-ha] Update version rabbitmq exporter to version 0.29.0
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9128 [stable/grafana] Add rbac.pspUseAppArmor value to allow disabling AppArmor
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/podsecuritypolicy.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10423 [stable/mariadb] Support for extraInitContainers like in other popular charts
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
  stable/mariadb/templates/master-statefulset.yaml
  stable/mariadb/templates/slave-statefulset.yaml
  stable/mariadb/values-production.yaml
  stable/mariadb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#10317 [stable/airflow] : support adding connections
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/templates/deployments-scheduler.yaml
  stable/airflow/templates/secret-connections.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#10315 [stable/traefik] feat: add priorityClassName for pods
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/deployment.yaml
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#10061 [stable/sonarqube] Fix mount of configMap
  stable/sonarqube/Chart.yaml
  stable/sonarqube/templates/deployment.yaml
  stable/sonarqube/templates/startup-config.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#10431 [stable/rabbitmq-ha] Support setting cluster_partition_handling
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/templates/configmap.yaml
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10387 [docs] Clarify GCE MIG prefix matching behaviour + examples
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9520 [incubator/zookeeper] Fix passing secrets (#9519)
  incubator/zookeeper/Chart.yaml
  incubator/zookeeper/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10429 Updating secret
  stable/sonatype-nexus/Chart.yaml
  stable/sonatype-nexus/templates/backup-secret.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10435 Add myself to OWNERS for stable/fluentd
  stable/fluentd/Chart.yaml
  stable/fluentd/OWNERS
Labels: Contribution Allowed, approved, lgtm, size/XS

#10444 [stable/elasticsearch] Request resource limits for initContainer
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/README.md
  stable/elasticsearch/templates/client-deployment.yaml
  stable/elasticsearch/templates/data-statefulset.yaml
  stable/elasticsearch/templates/master-statefulset.yaml
  stable/elasticsearch/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#9071 [stable/fluentd] Add nodePort configuration for Fluentd
  stable/fluentd/Chart.yaml
  stable/fluentd/templates/service.yaml
  stable/fluentd/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#10340 Allow pre-created secrets for external database credentials
  stable/sonarqube/Chart.yaml
  stable/sonarqube/README.md
  stable/sonarqube/templates/deployment.yaml
  stable/sonarqube/templates/secret.yaml
  stable/sonarqube/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10448 [stable/elastic-stack] Update elasticsearch and fluentd charts
  stable/elastic-stack/Chart.yaml
  stable/elastic-stack/requirements.lock
  stable/elastic-stack/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10095 [stable/jenkins] add backup cronjob
  stable/jenkins/Chart.yaml
  stable/jenkins/OWNERS
  stable/jenkins/README.md
  stable/jenkins/templates/jenkins-backup-cronjob.yaml
  stable/jenkins/templates/jenkins-backup-rbac.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#10397 [stable/gocd] optional init containers
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/README.md
  stable/gocd/templates/gocd-agent-deployment.yaml
  stable/gocd/templates/gocd-server-deployment.yaml
  stable/gocd/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#8882 [stable/external-dns] Create secret for google service account
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/deployment.yaml
  stable/external-dns/templates/secret.yaml
Labels: Contribution Allowed, size/S

#10449 Remove linki from OWNERS file
  OWNERS
Labels: Contribution Allowed, approved, lgtm, size/XS

#9195 [incubator/etcd] Fix rejoin after failure
  incubator/etcd/Chart.yaml
  incubator/etcd/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10428 [stable/postgresql] Fix syntax error when persistence is disabled and replication enabled
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#10457 [stable/mongodb] Fix indentation on Metrics resources
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/deployment-standalone.yaml
  stable/mongodb/templates/statefulset-primary-rs.yaml
  stable/mongodb/templates/statefulset-secondary-rs.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10413 [stable/spinnaker] fixes yaml code blocks formatting in README
  stable/spinnaker/Chart.yaml
  stable/spinnaker/README.md
Labels: Contribution Allowed, approved, lgtm, size/M

#9067 [stable/elasticsearch] post init job to configure cluster
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/README.md
  stable/elasticsearch/templates/job.yaml
  stable/elasticsearch/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#9778 Add support for SELinux label modification
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/daemonset.yaml
  stable/datadog/templates/deployment.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9654 [stable/mysqldump] Add subpath to mysqldump persistence
  stable/mysqldump/Chart.yaml
  stable/mysqldump/README.md
  stable/mysqldump/files/job.tpl
  stable/mysqldump/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#10223 [stable/jenkins] various
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10468 Fix clusterchecks leader election
  stable/datadog/Chart.yaml
  stable/datadog/templates/NOTES.txt
  stable/datadog/templates/cluster-agent-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10281 [helm/charts] Add annotations support in deployment of cerebro
  stable/cerebro/Chart.yaml
  stable/cerebro/README.md
  stable/cerebro/templates/deployment.yaml
  stable/cerebro/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#10465 [stable/mariadb] Fixes for existing Secrets to work
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
  stable/mariadb/templates/master-statefulset.yaml
  stable/mariadb/templates/secrets.yaml
  stable/mariadb/templates/slave-statefulset.yaml
  stable/mariadb/templates/test-runner.yaml
  stable/mariadb/values-production.yaml
  stable/mariadb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#10432 [stable/wordpress] Fix syntax error when ingress is enabled
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
  stable/wordpress/templates/NOTES.txt
  stable/wordpress/templates/_helpers.tpl
  stable/wordpress/templates/deployment.yaml
  stable/wordpress/templates/ingress.yaml
  stable/wordpress/templates/pvc.yaml
  stable/wordpress/templates/secrets.yaml
  stable/wordpress/templates/svc.yaml
  stable/wordpress/values-production.yaml
  stable/wordpress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#10211 add DD_HOSTNAME, DD_AC_INCLUDE, DD_AC_EXCLUDE to DaemonSet config
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10366 [stable/prometheus-operator] Resolve scraping controller-manager and scheduler outside out the cluster
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/templates/exporters/kube-controller-manager/endpoints.yaml
  stable/prometheus-operator/templates/exporters/kube-controller-manager/service.yaml
  stable/prometheus-operator/templates/exporters/kube-scheduler/endpoints.yaml
  stable/prometheus-operator/templates/exporters/kube-scheduler/service.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#10461 [stable/ghost] Re-define ingress/smtp configuration
  stable/ghost/Chart.yaml
  stable/ghost/README.md
  stable/ghost/templates/deployment.yaml
  stable/ghost/templates/ingress.yaml
  stable/ghost/templates/pvc.yaml
  stable/ghost/templates/secrets.yaml
  stable/ghost/templates/svc.yaml
  stable/ghost/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#10455 sonarqube chart: Fix nil annotations warning
  stable/sonarqube/Chart.yaml
  stable/sonarqube/templates/ingress.yaml
  stable/sonarqube/templates/service.yaml
  stable/sonarqube/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10479 Add sheroy to owners
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/OWNERS
Labels: Contribution Allowed, approved, lgtm, size/S

#10236 [stable/jenkins] add numExecutors as a variable in values file
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/config.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9375 [stable/traefik] Generate self sign default cert
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/default-cert-secret.yaml
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#10184 [stable/jenkins] Fix job definitions in standard values.yaml
  stable/jenkins/Chart.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10486 nginx-ingress add `dnsPolicy` to README.md
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10233 [stable/kong] add doc for NodePort
  stable/kong/Chart.yaml
  stable/kong/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#10175 [incubator/jaeger] fix hotrod demo application
  incubator/jaeger/Chart.yaml
  incubator/jaeger/templates/_helpers.tpl
  incubator/jaeger/templates/common-cm.yaml
  incubator/jaeger/templates/hotrod-deploy.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10140 [stable/jenkins] fix parsing java options
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/jenkins-master-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10238 [stable/redis] Support defining PriorityClass
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/templates/metrics-deployment.yaml
  stable/redis/templates/redis-master-statefulset.yaml
  stable/redis/templates/redis-slave-deployment.yaml
  stable/redis/values-production.yaml
  stable/redis/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#10501 [stable/mongodb] Add mongodbSystemLogVerbosity configuration option
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/templates/deployment-standalone.yaml
  stable/mongodb/templates/statefulset-arbiter-rs.yaml
  stable/mongodb/templates/statefulset-primary-rs.yaml
  stable/mongodb/templates/statefulset-secondary-rs.yaml
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9146 [stable/keycloak] Add hostAliases
  stable/keycloak/Chart.yaml
  stable/keycloak/README.md
  stable/keycloak/templates/statefulset.yaml
  stable/keycloak/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#10253 [stable/ark] Add support for additional environment variables
  stable/ark/Chart.yaml
  stable/ark/README.md
  stable/ark/templates/deployment.yaml
  stable/ark/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#10099 [incubator/fluentd-cloudwatch] Roll out configmap updates
  incubator/fluentd-cloudwatch/Chart.yaml
  incubator/fluentd-cloudwatch/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10469 [stable/mysqldump]
  stable/mysqldump/Chart.yaml
  stable/mysqldump/templates/configmap.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#10503 [stable/keycloak] Refactor CLI scripts
  stable/keycloak/Chart.yaml
  stable/keycloak/scripts/ha.cli
  stable/keycloak/scripts/logging.cli
  stable/keycloak/scripts/node-identifier.cli
  stable/keycloak/scripts/reverse-proxy.cli
  stable/keycloak/templates/configmap.yaml
  stable/keycloak/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#8890 [stable/kubernetes-dashboard] Support pod annotations
  stable/kubernetes-dashboard/Chart.yaml
  stable/kubernetes-dashboard/README.md
  stable/kubernetes-dashboard/templates/deployment.yaml
  stable/kubernetes-dashboard/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#10474 [stable/elasticstack] Add ability to disable elasticsearch]
  stable/elastic-stack/Chart.yaml
  stable/elastic-stack/requirements.lock
  stable/elastic-stack/requirements.yaml
  stable/elastic-stack/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#10512 [stable/elasticsearch] Add individual Java flags for elasticsearch
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/README.md
  stable/elasticsearch/templates/client-deployment.yaml
  stable/elasticsearch/templates/data-statefulset.yaml
  stable/elasticsearch/templates/master-statefulset.yaml
  stable/elasticsearch/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9244 Rabbitmq exporter env vars
  stable/prometheus-rabbitmq-exporter/Chart.yaml
  stable/prometheus-rabbitmq-exporter/README.md
  stable/prometheus-rabbitmq-exporter/templates/deployment.yaml
  stable/prometheus-rabbitmq-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10516 [stable/kong] bump up charts and c* ci test
  stable/kong/Chart.yaml
  stable/kong/ci/cassandra.yaml
  stable/kong/requirements.lock
  stable/kong/requirements.yaml
  stable/kong/templates/controller-deployment.yaml
  stable/kong/templates/deployment.yaml
  stable/kong/templates/migrations-post-upgrade.yaml
  stable/kong/templates/migrations-pre-upgrade.yaml
  stable/kong/templates/migrations.yaml
  stable/kong/values.yaml
Labels: Contribution Allowed, approved, lgtm

#10498 [stable/wordpress] Add service annotations
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
  stable/wordpress/templates/svc.yaml
  stable/wordpress/values-production.yaml
  stable/wordpress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10497 [stable/jenkins] workaround for busybox's cp (Closes: #10471)
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/config.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10499 [stable/openldap] Add deployment strategy configuration
  stable/openldap/Chart.yaml
  stable/openldap/README.md
  stable/openldap/templates/deployment.yaml
  stable/openldap/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10531 [stable/prestashop] Fix labels
  stable/prestashop/Chart.yaml
  stable/prestashop/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10458 [stable/nginx-ingress] Remove checksum/config from DaemonSet template
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/templates/controller-daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10530 [stable/node-problem-detector] add default imagePullPolicy
  stable/node-problem-detector/Chart.yaml
  stable/node-problem-detector/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10520 [stable/elastic-stack] Update elasticsearch chart
  stable/elastic-stack/Chart.yaml
  stable/elastic-stack/requirements.lock
  stable/elastic-stack/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test

#10529 [stable/weave-cloud] use constant container name
  stable/weave-cloud/Chart.yaml
  stable/weave-cloud/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10514 [stable/keycloak] Add Thomas Darimont as maintainer
  stable/keycloak/Chart.yaml
  stable/keycloak/OWNERS
Labels: Contribution Allowed, approved, lgtm, size/XS

#10488 [stable/prometheus-operator] Add sync scripts
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/hack/README.md
  stable/prometheus-operator/hack/sync_grafana_dashboards.py
  stable/prometheus-operator/hack/sync_prometheus_rules.py
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#10534 [stable/jenkins] allow customizing livenessProbe periodSeconds
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/jenkins-master-deployment.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10076 [stable/minio] Add ability to create multiple buckets
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/templates/_helper_create_bucket.txt
  stable/minio/templates/post-install-create-bucket-job.yaml
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#10000 [stable/metricbeat] Add nonResourceURLs of "metrics" to RBAC
  stable/metricbeat/Chart.yaml
  stable/metricbeat/templates/clusterrole.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#10541 Fixes regression of functionality that allows for extra volumes and mounts regardless of whether persistence and ssh is enabled
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/templates/gocd-agent-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10443 [incubator/couchdb] bump couchdb to 2.3.0
  incubator/couchdb/Chart.yaml
  incubator/couchdb/README.md
  incubator/couchdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10396 [stable/sentry] Add support for persistence.existingClaim
  stable/sentry/Chart.yaml
  stable/sentry/README.md
  stable/sentry/templates/pvc.yaml
  stable/sentry/templates/web-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS
