Repository helm/charts, pull requests merged in 2019-04, with the labels that each got.

#12201 [stable/metricbeat] bump metricbeat, add overrideConfig and overrideModules
  stable/metricbeat/Chart.yaml
  stable/metricbeat/README.md
  stable/metricbeat/templates/daemonset.yaml
  stable/metricbeat/templates/deployment.yaml
  stable/metricbeat/templates/secret.yaml
  stable/metricbeat/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#12200 [stable/kibana] bump kibana, set default config empty
  stable/kibana/Chart.yaml
  stable/kibana/README.md
  stable/kibana/ci/dashboard-values.yaml
  stable/kibana/ci/initcontainers-all-values.yaml
  stable/kibana/ci/plugin-install.yaml
  stable/kibana/templates/deployment.yaml
  stable/kibana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12350 [metricbeat] Enable use of PSPs
  stable/metricbeat/Chart.yaml
  stable/metricbeat/README.md
  stable/metricbeat/templates/clusterrole.yaml
  stable/metricbeat/templates/podsecuritypolicy.yaml
  stable/metricbeat/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#8889 Allow to run filebeat pods as privileged
  stable/filebeat/Chart.yaml
  stable/filebeat/README.md
  stable/filebeat/templates/daemonset.yaml
  stable/filebeat/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#12615 [stable/prometheus-mongodb-exporter] Add envs to deployment template
  stable/prometheus-mongodb-exporter/Chart.yaml
  stable/prometheus-mongodb-exporter/README.md
  stable/prometheus-mongodb-exporter/ci/env-values.yaml
  stable/prometheus-mongodb-exporter/templates/deployment.yaml
  stable/prometheus-mongodb-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12714 [stable/datadog] Bump KSM dependency
  stable/datadog/Chart.yaml
  stable/datadog/requirements.lock
  stable/datadog/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12701 [elasticsearch-curator] Enabling the use of secrets in environment
  stable/elasticsearch-curator/Chart.yaml
  stable/elasticsearch-curator/README.md
  stable/elasticsearch-curator/templates/cronjob.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12468 Duplicate entries for affinity rules
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/alertmanager-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12503 Add optional ServiceMonitor and values stub with it disabled by default
  stable/prometheus-cloudwatch-exporter/Chart.yaml
  stable/prometheus-cloudwatch-exporter/README.md
  stable/prometheus-cloudwatch-exporter/templates/servicemonitor.yaml
  stable/prometheus-cloudwatch-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11845 [stable/external-dns] Fix `interval` description
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11696 [stable/curator] - configure pod security context
  stable/elasticsearch-curator/Chart.yaml
  stable/elasticsearch-curator/README.md
  stable/elasticsearch-curator/templates/cronjob.yaml
  stable/elasticsearch-curator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12407 [prometheus-cloudwatch-exporter] Added ingress configuration
  stable/prometheus-cloudwatch-exporter/Chart.yaml
  stable/prometheus-cloudwatch-exporter/README.md
  stable/prometheus-cloudwatch-exporter/templates/ingress.yaml
  stable/prometheus-cloudwatch-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12522 [stable/sysdig] Update README
  stable/sysdig/Chart.yaml
  stable/sysdig/README-AWS.md
  stable/sysdig/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#12595 [stable/kibana] add tests
  stable/kibana/Chart.yaml
  stable/kibana/README.md
  stable/kibana/templates/tests/test-configmap.yaml
  stable/kibana/templates/tests/test.yaml
  stable/kibana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12734 [stable/jenkins] allow templating of volumes
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/jenkins-master-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12737 [stable/sysdig] Bump Sysdig Agent version and use latest logo
  stable/sysdig/CHANGELOG.md
  stable/sysdig/Chart.yaml
  stable/sysdig/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#12439 [stable/falco] Upgrade to Falco 0.14.0
  stable/falco/CHANGELOG.md
  stable/falco/Chart.yaml
  stable/falco/README.md
  stable/falco/rules/falco_rules.local.yaml
  stable/falco/rules/falco_rules.yaml
  stable/falco/templates/_helpers.tpl
  stable/falco/templates/daemonset.yaml
  stable/falco/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#12686 [kubeless] Add functions-namespace config options
  incubator/kubeless/Chart.yaml
  incubator/kubeless/README.md
  incubator/kubeless/templates/kubeless-config.yaml
  incubator/kubeless/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12745 [stable/odoo] Add support to existing PVCs
  stable/odoo/Chart.yaml
  stable/odoo/README.md
  stable/odoo/templates/deployment.yaml
  stable/odoo/templates/pvc.yaml
  stable/odoo/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11946 [incubator/kafka] Rework mechanism to expose Kafka brokers externally
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
  incubator/kafka/templates/rbac.yaml
  incubator/kafka/templates/service-brokers-external.yaml
  incubator/kafka/templates/statefulset.yaml
  incubator/kafka/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12749 Spark history server/azure support
  stable/spark-history-server/Chart.yaml
  stable/spark-history-server/README.md
  stable/spark-history-server/templates/configmap.yaml
  stable/spark-history-server/templates/deployment.yaml
  stable/spark-history-server/templates/ingress.yaml
  stable/spark-history-server/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#12757 [bookstack] Fix persistance path for storage files to match paths mentioned in bookstack docs
  stable/bookstack/Chart.yaml
  stable/bookstack/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12753 Re-add value for Ingress API Version
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/NOTES.txt
  stable/jenkins/templates/jenkins-master-ingress.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12513 [incubator/gogs] Postgres SSLMode
  incubator/gogs/Chart.yaml
  incubator/gogs/README.md
  incubator/gogs/templates/_helpers.tpl
  incubator/gogs/templates/configmap.yaml
  incubator/gogs/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#12750 [stable/postgresql] Add support to specify the volumeMounts' subPath
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12756 [stable/mongodb] Add support to specify the volumeMounts' mountPath & subPath
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/templates/deployment-standalone.yaml
  stable/mongodb/templates/statefulset-primary-rs.yaml
  stable/mongodb/templates/statefulset-secondary-rs.yaml
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12733 [stable/graylog] add namespace in NOTES.txt when get secret
  stable/graylog/Chart.yaml
  stable/graylog/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#12761 [stable/jenkins] Fix wrong comment in values.yaml
  stable/jenkins/Chart.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12762 [stable/falco] Disable ebpf by default
  stable/falco/CHANGELOG.md
  stable/falco/Chart.yaml
  stable/falco/README.md
  stable/falco/ci/ebpf-values.yaml
  stable/falco/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#12759 Update elastic-stack to use correct Kibana chart
  stable/elastic-stack/Chart.yaml
  stable/elastic-stack/requirements.lock
  stable/elastic-stack/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12722 [stable/mongodb] Fix Health Check Probes
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/templates/deployment-standalone.yaml
  stable/mongodb/templates/statefulset-primary-rs.yaml
  stable/mongodb/templates/statefulset-secondary-rs.yaml
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12781 [stable/cerebro] bump image
  stable/cerebro/Chart.yaml
  stable/cerebro/README.md
  stable/cerebro/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12773 [stable/logstash] Add support for custom files
  stable/logstash/Chart.yaml
  stable/logstash/README.md
  stable/logstash/templates/files-config.yaml
  stable/logstash/templates/statefulset.yaml
  stable/logstash/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12721 [stable/rabbitmq] add annotations without dependency if metrics are e…
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/svc.yaml
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12740 [stable/airflow] Update redis requirements version
  stable/airflow/Chart.yaml
  stable/airflow/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12747 [stable/prometheus-node-exporter] configurable host network
  stable/prometheus-node-exporter/Chart.yaml
  stable/prometheus-node-exporter/README.md
  stable/prometheus-node-exporter/templates/daemonset.yaml
  stable/prometheus-node-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12758 [stable/metricbeat][1.6.0] adding support for pod priority
  stable/metricbeat/Chart.yaml
  stable/metricbeat/README.md
  stable/metricbeat/templates/daemonset.yaml
  stable/metricbeat/templates/deployment.yaml
  stable/metricbeat/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12764 Fixed typo in notes
  incubator/kafka/Chart.yaml
  incubator/kafka/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12729 upgrade external dns
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#12700 [stable/dask] add support to dask to use nodeselector, affinity and tolerations
  stable/dask/Chart.yaml
  stable/dask/README.md
  stable/dask/templates/dask-jupyter-deployment.yaml
  stable/dask/templates/dask-scheduler-deployment.yaml
  stable/dask/templates/dask-worker-deployment.yaml
  stable/dask/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12534 [stable/elasticsearch] Add podManagementStrategy
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/README.md
  stable/elasticsearch/templates/data-statefulset.yaml
  stable/elasticsearch/templates/master-statefulset.yaml
  stable/elasticsearch/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10237 Allow AWS role based authentication to Secrets Manager and Systems Manager
  stable/concourse/Chart.yaml
  stable/concourse/README.md
  stable/concourse/templates/web-deployment.yaml
  stable/concourse/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11690 [stable/airflow] Support affinity, nodeSelector and toleration for a…
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/templates/deployments-flower.yaml
  stable/airflow/templates/deployments-scheduler.yaml
  stable/airflow/templates/deployments-web.yaml
  stable/airflow/templates/statefulsets-workers.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#12778 Update templates/service-brokers-external.yaml to use correct targetPort for service type LoadBalancer or NodePort
  incubator/kafka/Chart.yaml
  incubator/kafka/templates/service-brokers-external.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#8157 Initial buzzfeed-sso chart - Oauth over your Kubernetes services
  incubator/buzzfeed-sso/Chart.yaml
  incubator/buzzfeed-sso/OWNERS
  incubator/buzzfeed-sso/README.md
  incubator/buzzfeed-sso/templates/NOTES.txt
  incubator/buzzfeed-sso/templates/_helpers.tpl
  incubator/buzzfeed-sso/templates/auth-deployment.yaml
  incubator/buzzfeed-sso/templates/auth-service.yaml
  incubator/buzzfeed-sso/templates/configmap.yaml
  incubator/buzzfeed-sso/templates/google-secret.yaml
  incubator/buzzfeed-sso/templates/ingress.yaml
  incubator/buzzfeed-sso/templates/proxy-deployment.yaml
  incubator/buzzfeed-sso/templates/proxy-service.yaml
  incubator/buzzfeed-sso/templates/secret.yaml
  incubator/buzzfeed-sso/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XL

#12793 [stable/airflow] Update NOTES file
  stable/airflow/Chart.yaml
  stable/airflow/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#11880 [stable/coredns] Version bump to 1.4.0
  stable/coredns/Chart.yaml
  stable/coredns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12804 [stable/mariadb] Correct description of initdbScript parameter
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
  stable/mariadb/values-production.yaml
  stable/mariadb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11619 [stable/drone] Drone 2.0.0 rc 8 - Creates source-control secret
  stable/drone/Chart.yaml
  stable/drone/templates/NOTES.txt
  stable/drone/templates/secrets.yaml
  stable/drone/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12795 [stable/keycloak] Allow using an existing secret for keycloak admin user
  stable/keycloak/Chart.yaml
  stable/keycloak/README.md
  stable/keycloak/templates/keycloak-secret.yaml
  stable/keycloak/templates/statefulset.yaml
  stable/keycloak/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12802 [stable/postgresql] Correct description of initdbScript parameter
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12744 [stable/rabbitmq] Improve the readiness and liveness probes: now print healthcheck result
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12739 Redis Helm Chart. Add resources to init container in the slave-deployment template
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/templates/redis-slave-deployment.yaml
  stable/redis/values-production.yaml
  stable/redis/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12657 [stable/auditbeat] add environment variables
  stable/auditbeat/Chart.yaml
  stable/auditbeat/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12774 [Stable/jaeger-operator] Update readme
  stable/jaeger-operator/Chart.yaml
  stable/jaeger-operator/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12813 [stable/prometheus-operator] Updated to allow Ingress Capture Groups
  stable/prometheus-operator/.helmignore
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/templates/alertmanager/ingress.yaml
  stable/prometheus-operator/templates/prometheus/ingress.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/L

#12822 Allowing CRD toggling in sealed-secrets chart.
  stable/sealed-secrets/Chart.yaml
  stable/sealed-secrets/README.md
  stable/sealed-secrets/templates/sealedsecret-crd.yaml
  stable/sealed-secrets/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12507 [stable/elasticsearch] add test
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/README.md
  stable/elasticsearch/templates/tests/test-configmap.yaml
  stable/elasticsearch/templates/tests/test.yaml
  stable/elasticsearch/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12800 [stable/prometheus-operator] add support for pod annotations
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/templates/prometheus-operator/deployment.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#12609 Support traefik timeouts
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/configmap.yaml
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12748 [helm/jenkins] Support multiple Jenkins instances in same namespace
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/jcasc-config.yaml
  stable/jenkins/templates/jenkins-master-deployment.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12847 Added labels to pdb.
  stable/memcached/Chart.yaml
  stable/memcached/templates/pdb.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11098 initial commit for wavefront chart
  stable/wavefront/.helmignore
  stable/wavefront/Chart.yaml
  stable/wavefront/OWNERS
  stable/wavefront/README.md
  stable/wavefront/requirements.lock
  stable/wavefront/requirements.yaml
  stable/wavefront/templates/NOTES.txt
  stable/wavefront/templates/_helpers.tpl
  stable/wavefront/templates/api-token-secret.yaml
  stable/wavefront/templates/collector-cluster-role.yaml
  stable/wavefront/templates/collector-config.yaml
  stable/wavefront/templates/collector-deployment.yaml
  stable/wavefront/templates/collector-rbac.yaml
  stable/wavefront/templates/collector-service-account.yaml
  stable/wavefront/templates/proxy-deployment.yaml
  stable/wavefront/templates/proxy-preprocessor-config.yaml
  stable/wavefront/templates/proxy-service.yaml
  stable/wavefront/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XL

#12769 [stable/filebeat] Move beat-exporter containerPort into context block
  stable/filebeat/Chart.yaml
  stable/filebeat/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11139 cassandra-reaper chart (updated)
  incubator/cassandra-reaper/.helmignore
  incubator/cassandra-reaper/Chart.yaml
  incubator/cassandra-reaper/OWNERS
  incubator/cassandra-reaper/README.md
  incubator/cassandra-reaper/templates/_helpers.tpl
  incubator/cassandra-reaper/templates/deployment.yaml
  incubator/cassandra-reaper/templates/ingress.yaml
  incubator/cassandra-reaper/templates/secret.yaml
  incubator/cassandra-reaper/templates/service.yaml
  incubator/cassandra-reaper/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#11206 Add the ability to specify additional labels for pod and statefulset for stable/consul
  stable/consul/Chart.yaml
  stable/consul/README.md
  stable/consul/templates/consul-statefulset.yaml
  stable/consul/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#11670 [stable/fluentd] Update fluentd to v2.4.0
  stable/fluentd/Chart.yaml
  stable/fluentd/README.md
  stable/fluentd/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11534 [stable/newrelic-infrastructure] update to 1.6.0, add psp support
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/README.md
  stable/newrelic-infrastructure/templates/clusterrole.yaml
  stable/newrelic-infrastructure/templates/clusterrolebinding.yaml
  stable/newrelic-infrastructure/templates/podsecuritypolicy.yaml
  stable/newrelic-infrastructure/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12856 Bump to Ambassador 0.53.1.
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#12873 Added support for configmap subPath
  stable/airflow/Chart.yaml
  stable/airflow/templates/deployments-scheduler.yaml
  stable/airflow/templates/deployments-web.yaml
  stable/airflow/templates/statefulsets-workers.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#12886 [stable/minio] clean tabs
  stable/minio/Chart.yaml
  stable/minio/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#11518 [stable/prometheus] Update retention time property
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/server-deployment.yaml
  stable/prometheus/templates/server-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12895 Make grafana default datasource optional
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/templates/grafana/configmaps-datasources.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12878 [incubator/kafka] Update service-brokers-external.yaml to remove incorrect mapping to headless port
  incubator/kafka/Chart.yaml
  incubator/kafka/templates/service-brokers-external.yaml
  incubator/kafka/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12904 [stable/jenkins] Update to match actual defaults in value.yaml
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12670 [stable/ambassador] var for scoping to namespace
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/templates/deployment.yaml
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12916 [incubator/kafka] Update README.md with examples for broker external access
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#12647 [stable/kong] bump up Kong to 1.1
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#12919 [stable/prometheus-operator] Fix default values for prometheus-operator remoteRead/Write
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#12688 [stable/phabricator] Add nodeSelector, affinity and tolerations
  stable/phabricator/Chart.yaml
  stable/phabricator/README.md
  stable/phabricator/templates/deployment.yaml
  stable/phabricator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12783 Add lifecycle hooks option for keycloak container
  stable/keycloak/Chart.yaml
  stable/keycloak/README.md
  stable/keycloak/templates/statefulset.yaml
  stable/keycloak/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12202 [stable/filebeat] set default config empty
  stable/filebeat/Chart.yaml
  stable/filebeat/README.md
  stable/filebeat/templates/daemonset.yaml
  stable/filebeat/templates/secret.yaml
  stable/filebeat/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11281 [stable/coredns] Add service configuration fields
  stable/coredns/Chart.yaml
  stable/coredns/templates/service.yaml
  stable/coredns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12923 added git integration
  stable/home-assistant/Chart.yaml
  stable/home-assistant/README.md
  stable/home-assistant/templates/deployment.yaml
  stable/home-assistant/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12807 [stable/graylog] fix NOTES.txt when service type is NodePort
  stable/graylog/Chart.yaml
  stable/graylog/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#12832 [ark] Fix wrong nesting of bucket prefix on objectStorage
  stable/ark/Chart.yaml
  stable/ark/templates/backupstoragelocation.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12908 [stable/rabbitmq] Support configuration for the rabbitmq metrics exporter
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/statefulset.yaml
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12929 [stable/odoo] Fix service selectors
  stable/odoo/Chart.yaml
  stable/odoo/templates/svc.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12924 fix: remove redundant block
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/alertmanager/alertmanager.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#11430 [stable/ark] Fix prefix param, add restic podannotation and resource
  stable/ark/Chart.yaml
  stable/ark/templates/restic-daemonset.yaml
  stable/ark/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12677 [stable/rabbitmq] Change default clustering method to hostname
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12932 [stable/rabbitmq] Add parameter to indicate 'extraPlugins' to install
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/_helpers.tpl
  stable/rabbitmq/templates/configuration.yaml
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12934 [stable/ark] Upgrade ark version to v0.10.2
  stable/ark/Chart.yaml
  stable/ark/README.md
  stable/ark/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12909 [stable/parse] fix ingress template
  stable/parse/Chart.yaml
  stable/parse/templates/_helpers.tpl
  stable/parse/templates/dashboard-deployment.yaml
  stable/parse/templates/ingress.yaml
  stable/parse/templates/pvc.yaml
  stable/parse/templates/secrets.yaml
  stable/parse/templates/server-deployment.yaml
  stable/parse/templates/svc.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12833 [stable/concourse] preStop Script bug fix
  stable/concourse/Chart.yaml
  stable/concourse/templates/worker-prestop-configmap.yaml
  stable/concourse/templates/worker-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12725 [stable][chartmuseum] Allow use of Bearer Auth
  stable/chartmuseum/Chart.yaml
  stable/chartmuseum/README.md
  stable/chartmuseum/templates/deployment.yaml
  stable/chartmuseum/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#12937 [stable/redis-ha] `podDisruptionBudget` config described.
  stable/redis-ha/Chart.yaml
  stable/redis-ha/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12604 [stable/grafana] test
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/tests/test-configmap.yaml
  stable/grafana/templates/tests/test.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12772 [stable/elasticsearch-curator] Add support for init containers
  stable/elasticsearch-curator/Chart.yaml
  stable/elasticsearch-curator/README.md
  stable/elasticsearch-curator/ci/initcontainer-values.yaml
  stable/elasticsearch-curator/templates/cronjob.yaml
  stable/elasticsearch-curator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12959 [stable/grafana] Update Grafana version to 6.1.3
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12948 [stable/wordpress] Add option for skipping the installation wizard
  stable/wordpress/Chart.yaml
  stable/wordpress/templates/deployment.yaml
  stable/wordpress/values-production.yaml
  stable/wordpress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12966 [stable/drone] Drone 2.0.0 rc 9 - map server.alwaysAuth to environment DRONE_GIT_ALWAYS_AUTH
  stable/drone/Chart.yaml
  stable/drone/templates/deployment-server.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#12946 fix: add hostName to ingress in values.yaml
  stable/jenkins/Chart.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12105 [stable/magic-namespace] Magic namespace bugs
  stable/magic-namespace/Chart.yaml
  stable/magic-namespace/templates/tiller-deployment.yaml
  stable/magic-namespace/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12028 [incubator/rundeck] Creating a Rundeck chart
  incubator/rundeck/.helmignore
  incubator/rundeck/Chart.yaml
  incubator/rundeck/OWNERS
  incubator/rundeck/README.md
  incubator/rundeck/files/nginx/nginx.conf
  incubator/rundeck/templates/NOTES.txt
  incubator/rundeck/templates/_helpers.tpl
  incubator/rundeck/templates/deployment.yaml
  incubator/rundeck/templates/ingress.yaml
  incubator/rundeck/templates/nginx-configmap.yaml
  incubator/rundeck/templates/rundeck-environment-configmap.yaml
  incubator/rundeck/templates/service.yaml
  incubator/rundeck/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#12938 [stable/rabbitmq-ha] Pod Disruption Budget added.
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/templates/pdb.yaml
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12981 [incubator/haproxy-ingress] haproxy-ingress v0.7.1
  incubator/haproxy-ingress/Chart.yaml
  incubator/haproxy-ingress/README.md
  incubator/haproxy-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12581 [stable/schema-registry-ui] Added support for the proxy switch.
  stable/schema-registry-ui/Chart.yaml
  stable/schema-registry-ui/README.md
  stable/schema-registry-ui/templates/deployment.yaml
  stable/schema-registry-ui/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#12969 [stable/jenkins] Add support for service account annotations in jenkins
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/service-account.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12960 [stable/prometheus-operator] Allow metricRelabelings in default kube-state-metrics exporter
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/templates/exporters/kube-state-metrics/serviceMonitor.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#12854 [stable/Postgresql] add runAsUser inside security policy
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/statefulset.yaml
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12992 [stable/redis-ha] Escape special chars before using auth in sed replace clause
  stable/redis-ha/Chart.yaml
  stable/redis-ha/templates/redis-ha-configmap.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12997 [stable/metrics-server] v0.3.2 & other improvements
  stable/metrics-server/Chart.yaml
  stable/metrics-server/README.md
  stable/metrics-server/templates/cluster-role.yaml
  stable/metrics-server/templates/metric-server-service.yaml
  stable/metrics-server/templates/metrics-server-deployment.yaml
  stable/metrics-server/templates/tests/test-version.yaml
  stable/metrics-server/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#12995 [stable/oauth2-proxy] Add options to service.
  stable/oauth2-proxy/Chart.yaml
  stable/oauth2-proxy/README.md
  stable/oauth2-proxy/templates/service.yaml
  stable/oauth2-proxy/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12986 [incubator/cassandra] allow exporter resources
  incubator/cassandra/Chart.yaml
  incubator/cassandra/README.md
  incubator/cassandra/templates/statefulset.yaml
  incubator/cassandra/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13005 [stable/wordpress] Add quote to wordpressSkipInstall
  stable/wordpress/Chart.yaml
  stable/wordpress/values-production.yaml
  stable/wordpress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12944 [stable/openebs] update charts to latest 0.8.2 release
  stable/openebs/Chart.yaml
  stable/openebs/README.md
  stable/openebs/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#13008 [Datadog Values.yaml] Fixing indent
  stable/datadog/Chart.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#12970 stable/cert-manager: deprecate cert-manager chart
  stable/cert-manager/Chart.yaml
  stable/cert-manager/README.md
  stable/cert-manager/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, size/S

#12797 [newrelic-infra] Update to 1.7.0 and add OWNERS
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/OWNERS
  stable/newrelic-infrastructure/README.md
  stable/newrelic-infrastructure/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13009 [stable/wordpress] Explicitly unset nodePort when service is ClusterIP
  stable/wordpress/Chart.yaml
  stable/wordpress/templates/svc.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12962 Update MinIO / mc images
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#11254 [stable/unbound] Add support for externalIP, stubZones and localZones properties
  stable/unbound/Chart.yaml
  stable/unbound/README.md
  stable/unbound/templates/configmap.yaml
  stable/unbound/templates/service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12616 Kiam update 3.2
  stable/kiam/Chart.yaml
  stable/kiam/README.md
  stable/kiam/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13001 [stable/granfana] add skipTlsVerify Variables to sidecar.
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/deployment.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13038 upgrade promteheus pushgateway
  stable/prometheus-pushgateway/Chart.yaml
  stable/prometheus-pushgateway/README.md
  stable/prometheus-pushgateway/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#12875 [stable/wordpress] Allow more flexible TLS configuration.
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
  stable/wordpress/templates/ingress.yaml
  stable/wordpress/values-production.yaml
  stable/wordpress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#13018 [stable/redis] Add missing imagePullPolicy for init-sysctl
  stable/redis/Chart.yaml
  stable/redis/templates/redis-master-statefulset.yaml
  stable/redis/templates/redis-slave-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13044 [stable/rabbitmq] Add parameters to limit the number of scheduler threads.
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/statefulset.yaml
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12713 Initial commit of the gangway chart
  stable/gangway/.helmignore
  stable/gangway/Chart.yaml
  stable/gangway/OWNERS
  stable/gangway/README.md
  stable/gangway/templates/NOTES.txt
  stable/gangway/templates/_helpers.tpl
  stable/gangway/templates/configmap.yaml
  stable/gangway/templates/deployment.yaml
  stable/gangway/templates/ingress.yaml
  stable/gangway/templates/key.yaml
  stable/gangway/templates/service.yaml
  stable/gangway/templates/ssl.yaml
  stable/gangway/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XL

#11608 Utilize resource requests and limits
  stable/efs-provisioner/Chart.yaml
  stable/efs-provisioner/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12145 [stable/kube-state-metrics] add optional prometheus service monitor
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
  stable/kube-state-metrics/templates/monitor.yaml
  stable/kube-state-metrics/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11994 [stable/percona-xtradb-cluster] Add prometheus-operator support
  stable/percona-xtradb-cluster/Chart.yaml
  stable/percona-xtradb-cluster/README.md
  stable/percona-xtradb-cluster/templates/prometheusrule.yaml
  stable/percona-xtradb-cluster/templates/service-metrics.yaml
  stable/percona-xtradb-cluster/templates/servicemonitor.yaml
  stable/percona-xtradb-cluster/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/L

#12205 Added goldpinger helm chart
  stable/goldpinger/.helmignore
  stable/goldpinger/Chart.yaml
  stable/goldpinger/OWNERS
  stable/goldpinger/README.md
  stable/goldpinger/templates/NOTES.txt
  stable/goldpinger/templates/_helpers.tpl
  stable/goldpinger/templates/clusterrole.yaml
  stable/goldpinger/templates/clusterrolebinding.yaml
  stable/goldpinger/templates/daemonset.yaml
  stable/goldpinger/templates/ingress.yaml
  stable/goldpinger/templates/service.yaml
  stable/goldpinger/templates/serviceaccount.yaml
  stable/goldpinger/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#12461 [stable/metallb] Add PSP utilization in speaker's ClusterRole
  stable/metallb/Chart.yaml
  stable/metallb/templates/rbac.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12633 [redis-ha] Added sysctl init container same as in stable/redis
  stable/redis-ha/Chart.yaml
  stable/redis-ha/README.md
  stable/redis-ha/templates/_helpers.tpl
  stable/redis-ha/templates/redis-ha-statefulset.yaml
  stable/redis-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12640 Feature/12619 stable percona add affinity
  stable/percona/Chart.yaml
  stable/percona/README.md
  stable/percona/templates/deployment.yaml
  stable/percona/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12658 [stable/heartbeat] add several config values
  stable/heartbeat/Chart.yaml
  stable/heartbeat/README.md
  stable/heartbeat/templates/daemonset.yaml
  stable/heartbeat/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#12728 [stable/Dex] Fixed hard coded servicePort in ingress template
  stable/dex/Chart.yaml
  stable/dex/templates/ingress.yaml
  stable/dex/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12826 make nodePort configurable
  stable/sentry/Chart.yaml
  stable/sentry/README.md
  stable/sentry/templates/service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12299 [stable/distributed-jmeter] Improve upgrade instructions in NOTES.txt
  stable/distributed-jmeter/Chart.yaml
  stable/distributed-jmeter/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11390 [stable/heapster] minor readme fix
  stable/heapster/Chart.yaml
  stable/heapster/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12066 [stable/apm-server] add @mumoshu to OWNERS
  stable/apm-server/Chart.yaml
  stable/apm-server/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13060 [sysdig/stable] Make accessKey explicit as empty value
  stable/sysdig/CHANGELOG.md
  stable/sysdig/Chart.yaml
  stable/sysdig/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#13067 [stable/prometheus] upgrade prometheus
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#12162 Remove quotes around _SYSTEMD_UNIT value
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/templates/config.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#12190 Sentry support for extra labels
  stable/sentry/Chart.yaml
  stable/sentry/README.md
  stable/sentry/templates/cron-deployment.yaml
  stable/sentry/templates/hooks/db-init.job.yaml
  stable/sentry/templates/hooks/user-create.job.yaml
  stable/sentry/templates/web-deployment.yaml
  stable/sentry/templates/workers-deployment.yaml
  stable/sentry/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#13063 adds mongodb prometheus exporter scrape timeout config option
  stable/prometheus-mongodb-exporter/Chart.yaml
  stable/prometheus-mongodb-exporter/README.md
  stable/prometheus-mongodb-exporter/templates/servicemonitor.yaml
  stable/prometheus-mongodb-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12302 [incubator/kafka] Expose POD_IP
  incubator/kafka/Chart.yaml
  incubator/kafka/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12529 Add GKE CloudSQL support for anchore-engine
  stable/anchore-engine/Chart.yaml
  stable/anchore-engine/README.md
  stable/anchore-engine/templates/analyzer_deployment.yaml
  stable/anchore-engine/templates/api_deployment.yaml
  stable/anchore-engine/templates/catalog_deployment.yaml
  stable/anchore-engine/templates/engine_configmap.yaml
  stable/anchore-engine/templates/enterprise_feeds_deployment.yaml
  stable/anchore-engine/templates/policy_engine_deployment.yaml
  stable/anchore-engine/templates/simplequeue_deployment.yaml
  stable/anchore-engine/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M
