Repository helm/charts, pull requests merged in 2019-07, with the labels that each got.

#12003 [stable/coredns] add optional prometheus service monitor to coredns
  stable/coredns/Chart.yaml
  stable/coredns/templates/monitor.yaml
  stable/coredns/templates/service-metrics.yaml
  stable/coredns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15149 [stable/grafana] fix issue 15134
  stable/grafana/Chart.yaml
  stable/grafana/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14898 [stable/datadog] Make name of dogstatsd socket configurable
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/container-agent.yaml
  stable/datadog/templates/container-agents.yaml
  stable/datadog/templates/deployment.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#15146 [stable/aws-alb-ingress-controller] Adding liveness probe timeout variable ➕
  incubator/aws-alb-ingress-controller/Chart.yaml
  incubator/aws-alb-ingress-controller/README.md
  incubator/aws-alb-ingress-controller/templates/deployment.yaml
  incubator/aws-alb-ingress-controller/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#15155 [stable/nexcloud] Support PostgreSQL database
  stable/nextcloud/Chart.yaml
  stable/nextcloud/README.md
  stable/nextcloud/templates/deployment.yaml
  stable/nextcloud/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15157 [stable/mongodb] Fix markdown symbol
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15194 [stable/fluent-bit] Set to null by default
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#15195 [stable/anchore-engine] Engine Release v0.4.1
  stable/anchore-engine/Chart.yaml
  stable/anchore-engine/templates/analyzer_deployment.yaml
  stable/anchore-engine/templates/api_deployment.yaml
  stable/anchore-engine/templates/catalog_deployment.yaml
  stable/anchore-engine/templates/engine_configmap.yaml
  stable/anchore-engine/templates/enterprise_configmap.yaml
  stable/anchore-engine/templates/enterprise_feeds_configmap.yaml
  stable/anchore-engine/templates/enterprise_feeds_deployment.yaml
  stable/anchore-engine/templates/enterprise_ui_config.yaml
  stable/anchore-engine/templates/enterprise_ui_deployment.yaml
  stable/anchore-engine/templates/ingress.yaml
  stable/anchore-engine/templates/policy_engine_deployment.yaml
  stable/anchore-engine/templates/secrets.yaml
  stable/anchore-engine/templates/simplequeue_deployment.yaml
  stable/anchore-engine/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#15197 [k8s-spot-termination-handler] Adding host network option.
  stable/k8s-spot-termination-handler/Chart.yaml
  stable/k8s-spot-termination-handler/README.md
  stable/k8s-spot-termination-handler/templates/daemonset.yaml
  stable/k8s-spot-termination-handler/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14926 [stable/rabbitmq] enhance readiness-probe to handle pod restart
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15199 [k8s-spot-termination-handler] Updating OWNERS file.
  stable/k8s-spot-termination-handler/Chart.yaml
  stable/k8s-spot-termination-handler/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14830 [stable/k8s-spot-termination-handler] add annotations and updateStrategy
  stable/k8s-spot-termination-handler/Chart.yaml
  stable/k8s-spot-termination-handler/README.md
  stable/k8s-spot-termination-handler/templates/daemonset.yaml
  stable/k8s-spot-termination-handler/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15135 [stable/datadog] Add priorityClassName to Cluster Agent deployment
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/cluster-agent-deployment.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15213 [stable/spinnaker] ensure spinnaker works behind nsx-t ingress
  stable/spinnaker/Chart.yaml
  stable/spinnaker/templates/configmap/additional-profile-configmaps.yaml
  stable/spinnaker/templates/ingress/deck.yaml
  stable/spinnaker/templates/ingress/gate.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15215 [stable/instana-agent] Allow the agent configuration.yaml to be configurable via values.yaml in addition to editing the configmap
  stable/instana-agent/Chart.yaml
  stable/instana-agent/README.md
  stable/instana-agent/templates/configmap.yaml
  stable/instana-agent/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#15184 [stable/mysql] add namespace to test resources
  stable/mysql/Chart.yaml
  stable/mysql/templates/tests/test-configmap.yaml
  stable/mysql/templates/tests/test.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#15214 [stable/kube-state-metrics] Rename ServiceMonitor template
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/templates/servicemonitor.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14833 [stable/jenkins] Adding sub-path option for scraping
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/jenkins-master-servicemonitor.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#15038 stable/concourse: Improve documentation awsSecretsManager template
  stable/concourse/Chart.yaml
  stable/concourse/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15029 [stable/locust] enable secret volumes & envs
  stable/locust/Chart.yaml
  stable/locust/README.md
  stable/locust/templates/master-deploy.yaml
  stable/locust/templates/worker-deploy.yaml
  stable/locust/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15219 [stable/spring-cloud-data-flow] Update to new SCDF version 2.1.2
  stable/spring-cloud-data-flow/Chart.yaml
  stable/spring-cloud-data-flow/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#12206 [stable/elasticsearch] Add options for pre-stop and post-start hooks
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/README.md
  stable/elasticsearch/ci/hooks-values.yaml
  stable/elasticsearch/templates/client-deployment.yaml
  stable/elasticsearch/templates/configmap.yaml
  stable/elasticsearch/templates/data-statefulset.yaml
  stable/elasticsearch/templates/master-statefulset.yaml
  stable/elasticsearch/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#15227 [stable/mariadb] Replace Alpine by minideb as initContainer in documentation
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13293 [stable/prometheus-pushgateway] add optional PodDisruptionBudget
  stable/prometheus-pushgateway/Chart.yaml
  stable/prometheus-pushgateway/README.md
  stable/prometheus-pushgateway/templates/pdb.yaml
  stable/prometheus-pushgateway/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14099 [incubator/sentry-kubernetes] Allow using existing secrets
  incubator/sentry-kubernetes/Chart.yaml
  incubator/sentry-kubernetes/README.md
  incubator/sentry-kubernetes/templates/_helpers.tpl
  incubator/sentry-kubernetes/templates/deployment.yaml
  incubator/sentry-kubernetes/templates/secret.yaml
  incubator/sentry-kubernetes/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15100 [stable/redis] Add --no-auth-warning to health checks
  stable/redis/Chart.yaml
  stable/redis/ci/redis-lib-values.yaml
  stable/redis/templates/health-configmap.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15156 [stable/redis] Collect metrics from sentinels when enabled
  stable/redis/Chart.yaml
  stable/redis/templates/metrics-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#15220 [stable/concourse] Fixes #13025 Worker-only deployments take a list of hostnames & ports
  stable/concourse/CHANGELOG.md
  stable/concourse/Chart.yaml
  stable/concourse/templates/_helpers.tpl
  stable/concourse/templates/required-check.yaml
  stable/concourse/templates/worker-statefulset.yaml
  stable/concourse/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15203 [stable/nginx-ingress] allow nodePort for tcp/udp services (#11917)
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15229 [stable/mongodb] Disable IPv6 by default
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15233 [stable/kube-hunter] upgrade to 312
  stable/kube-hunter/Chart.yaml
  stable/kube-hunter/README.md
  stable/kube-hunter/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#15079 [stable/kong] add nginx custom template feature via config map
  stable/kong/Chart.yaml
  stable/kong/templates/config-custom-server-blocks.yaml
  stable/kong/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15237 [stable/kong] correct check if ingress controller is enabled
  stable/kong/Chart.yaml
  stable/kong/ci/dbless-without-kic.yaml
  stable/kong/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#15202 [stable/jenkins] Add support for namespace specification
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/NOTES.txt
  stable/jenkins/templates/_helpers.tpl
  stable/jenkins/templates/config.yaml
  stable/jenkins/templates/home-pvc.yaml
  stable/jenkins/templates/jcasc-config.yaml
  stable/jenkins/templates/jenkins-agent-svc.yaml
  stable/jenkins/templates/jenkins-backup-cronjob.yaml
  stable/jenkins/templates/jenkins-backup-rbac.yaml
  stable/jenkins/templates/jenkins-master-alerting-rules.yaml
  stable/jenkins/templates/jenkins-master-deployment.yaml
  stable/jenkins/templates/jenkins-master-ingress.yaml
  stable/jenkins/templates/jenkins-master-networkpolicy.yaml
  stable/jenkins/templates/jenkins-master-route.yaml
  stable/jenkins/templates/jenkins-master-servicemonitor.yaml
  stable/jenkins/templates/jenkins-master-svc.yaml
  stable/jenkins/templates/jobs.yaml
  stable/jenkins/templates/rbac.yaml
  stable/jenkins/templates/secret.yaml
  stable/jenkins/templates/service-account-agent.yaml
  stable/jenkins/templates/service-account.yaml
  stable/jenkins/templates/tests/jenkins-test.yaml
  stable/jenkins/templates/tests/test-config.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#15243 [stable/external-dns] Fix labels max length by truncating them
  stable/external-dns/Chart.yaml
  stable/external-dns/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14416 [stable/fluent-bit] add a servicemonitor resource for Prometheus operator
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/servicemonitor.yaml
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15143 [stable/minio] Add missing service account
  stable/minio/Chart.yaml
  stable/minio/templates/serviceaccount.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15256 [stable/mariadb] Update mariadb chart readme to include secret instructions
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15265 [stable/telegraf] Allow ENV vars
  stable/telegraf/Chart.yaml
  stable/telegraf/templates/deployment.yaml
  stable/telegraf/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14941 [stable/concourse] properly cleanup btrfs subvolume and children
  stable/concourse/Chart.yaml
  stable/concourse/templates/worker-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#14503 [stable/atlantis] override configuration via configmap
  stable/atlantis/Chart.yaml
  stable/atlantis/README.md
  stable/atlantis/templates/configmap-config.yaml
  stable/atlantis/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15162 [incubator/couchdb] fix env vars for db container
  incubator/couchdb/Chart.yaml
  incubator/couchdb/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15236 [stable/nginx-ingress] set default values for tcp/udp nodeports
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#15018 [stable/traefik] quote boltdb prefix
  stable/traefik/Chart.yaml
  stable/traefik/templates/configmap.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15239 [stable/prometheus-postgres-exporter] upgrade to new version of postgres exporter
  stable/prometheus-postgres-exporter/Chart.yaml
  stable/prometheus-postgres-exporter/README.md
  stable/prometheus-postgres-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15128 [stable/consul] update to latest
  stable/consul/Chart.yaml
  stable/consul/README.md
  stable/consul/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#15257 [stable/external-dns] Removed duplicated Values.extraArgs in deployment template.
  stable/external-dns/Chart.yaml
  stable/external-dns/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15258 [stable/redis] fix master joining cluster as slave
  stable/redis/Chart.yaml
  stable/redis/templates/redis-master-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#15266 [stable/sentry] Add note about Sentry ownership
  stable/sentry/Chart.yaml
  stable/sentry/README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#15274 stable/sealed-secrets: Add networkPolicy
  stable/sealed-secrets/Chart.yaml
  stable/sealed-secrets/README.md
  stable/sealed-secrets/templates/networkpolicy.yaml
  stable/sealed-secrets/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14679 [stable/etcd-operator] pod annotations
  stable/etcd-operator/Chart.yaml
  stable/etcd-operator/README.md
  stable/etcd-operator/templates/operator-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#15277 [stable/prometheus-operator] Adding TLS params to kube controller manager and kube scheduler
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/templates/exporters/kube-controller-manager/servicemonitor.yaml
  stable/prometheus-operator/templates/exporters/kube-scheduler/servicemonitor.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15261 [stable/kube-state-metrics] Apply best practices for label naming
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/templates/clusterrole.yaml
  stable/kube-state-metrics/templates/clusterrolebinding.yaml
  stable/kube-state-metrics/templates/deployment.yaml
  stable/kube-state-metrics/templates/podsecuritypolicy.yaml
  stable/kube-state-metrics/templates/psp-clusterrole.yaml
  stable/kube-state-metrics/templates/psp-clusterrolebinding.yaml
  stable/kube-state-metrics/templates/service.yaml
  stable/kube-state-metrics/templates/serviceaccount.yaml
  stable/kube-state-metrics/templates/servicemonitor.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15153 [stable/coredns] Update to CoreDNS 1.5.2
  stable/coredns/Chart.yaml
  stable/coredns/templates/deployment.yaml
  stable/coredns/templates/servicemonitor.yaml
  stable/coredns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15103 [stable/concourse] Removes annotation warning messages
  stable/concourse/Chart.yaml
  stable/concourse/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15222 stable/opa: Fix OPA installation script with the right authz rego as …
  stable/opa/Chart.yaml
  stable/opa/templates/deployment.yaml
  stable/opa/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#15208 [chart/solr] Description: Updated Version and Readme
  incubator/solr/Chart.yaml
  incubator/solr/README.md
  incubator/solr/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15139 [stable/mysql] deployment annotations
  stable/mysql/Chart.yaml
  stable/mysql/README.md
  stable/mysql/templates/deployment.yaml
  stable/mysql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15263 [stable/telegraf] Check for service.enabled
  stable/telegraf/Chart.yaml
  stable/telegraf/templates/service.yaml
  stable/telegraf/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15302 [stable/redis] exporter to 1.0.3
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/ci/production-sentinel-values.yaml
  stable/redis/ci/production-values.yaml
  stable/redis/values-production.yaml
  stable/redis/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13680 [stable/external-dns] Bump deployment api version
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/deployment.yaml
  stable/external-dns/values-production.yaml
  stable/external-dns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#14819 [stable/prometheus] Add custom pod labels for prom server
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/server-deployment.yaml
  stable/prometheus/templates/server-statefulset.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15259 [stable/velero] Add value switch for volumesnapshot
  stable/velero/Chart.yaml
  stable/velero/README.md
  stable/velero/templates/volumesnapshotlocation.yaml
  stable/velero/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15276 [stable/redis] Add support to execute Redis as root
  stable/redis/Chart.yaml
  stable/redis/templates/redis-master-statefulset.yaml
  stable/redis/templates/redis-slave-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14028 [stable/minio] add a servicemonitor resource for Prometheus operator
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/templates/servicemonitor.yaml
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15288 [stable/wordpress] Add Prometheus ServiceMonitor
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
  stable/wordpress/templates/servicemonitor.yaml
  stable/wordpress/templates/svc.yaml
  stable/wordpress/values-production.yaml
  stable/wordpress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#15310 stable/sematext-agent: Update autodisco config
  stable/sematext-agent/Chart.yaml
  stable/sematext-agent/files/autodisco.yml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#15299 [stable/external-dns] Remove Google key validation
  stable/external-dns/Chart.yaml
  stable/external-dns/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15292 Finalizers
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/pvc.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15321 hlf-peer: multi channel support
  stable/hlf-peer/Chart.yaml
  stable/hlf-peer/README.md
  stable/hlf-peer/templates/deployment.yaml
  stable/hlf-peer/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15217 [stable/prometheus-redis-exporter] Update image
  stable/prometheus-redis-exporter/Chart.yaml
  stable/prometheus-redis-exporter/README.md
  stable/prometheus-redis-exporter/templates/deployment.yaml
  stable/prometheus-redis-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#14429 [stable/kuberhealthy] fix security context indenting and errant space. Removed bad fsGroup…
  stable/kuberhealthy/Chart.yaml
  stable/kuberhealthy/templates/deployment.yaml
  stable/kuberhealthy/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#15224 [stable/opa] Fixing the liveliness and readiness probe by moving it from container mgmt to container opa
  stable/opa/Chart.yaml
  stable/opa/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#15212 [stable/nexcloud] Multiple config.php file
  stable/nextcloud/Chart.yaml
  stable/nextcloud/README.md
  stable/nextcloud/templates/config.yaml
  stable/nextcloud/templates/deployment.yaml
  stable/nextcloud/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15320 [stable/pomerium] Chart updates for pomerium v0.1.0
  stable/pomerium/Chart.yaml
  stable/pomerium/README.md
  stable/pomerium/ci/default-values.yaml
  stable/pomerium/templates/authenticate-deployment.yaml
  stable/pomerium/templates/authorize-deployment.yaml
  stable/pomerium/templates/configmap.yaml
  stable/pomerium/templates/proxy-deployment.yaml
  stable/pomerium/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#15335 [stable/nginx-ingress] Update OWNERS
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15334 [stable/external-dns] Allow provider.google without mounting secrets
  stable/external-dns/Chart.yaml
  stable/external-dns/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15339 [stable/kibana] Add commented example in values.yaml for envFromSecrets
  stable/kibana/Chart.yaml
  stable/kibana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15254 [stable/sealed-secrets] Support PSP
  stable/sealed-secrets/Chart.yaml
  stable/sealed-secrets/README.md
  stable/sealed-secrets/templates/psp-clusterrole.yaml
  stable/sealed-secrets/templates/psp-clusterrolebinding.yaml
  stable/sealed-secrets/templates/psp.yaml
  stable/sealed-secrets/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15324 [stable/mongodb] loadBalancerSourceRanges can be specified for mongodb Helm chart
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/templates/svc-primary-rs.yaml
  stable/mongodb/templates/svc-standalone.yaml
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15251 [stable/external-dns] Enable PSP
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/psp-clusterrole.yaml
  stable/external-dns/templates/psp-clusterrolebinding.yaml
  stable/external-dns/templates/psp.yaml
  stable/external-dns/values-production.yaml
  stable/external-dns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15347 [stable/sematext-agent] SC-5221 Transfer chart ownership to Ciprian
  stable/sematext-agent/Chart.yaml
  stable/sematext-agent/OWNERS
Labels: Contribution Allowed, approved, lgtm, size/S

#15349 Mysql exporter managing labels
  stable/prometheus-mysql-exporter/Chart.yaml
  stable/prometheus-mysql-exporter/README.md
  stable/prometheus-mysql-exporter/templates/servicemonitor.yaml
  stable/prometheus-mysql-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#15352 [stable/external-dns]Fix typo in values-production
  stable/external-dns/Chart.yaml
  stable/external-dns/values-production.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11153 [stable/sentry] Sentry filestore config
  stable/sentry/Chart.yaml
  stable/sentry/README.md
  stable/sentry/templates/configmap.yaml
  stable/sentry/templates/cron-deployment.yaml
  stable/sentry/templates/pvc.yaml
  stable/sentry/templates/web-deployment.yaml
  stable/sentry/templates/workers-deployment.yaml
  stable/sentry/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#15357 [stable/fluent-bit] add securityContext and podSecurityContext variables
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/daemonset.yaml
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#15338 [stable/kubernetes-dashboard]: Add securityContext to deployment
  stable/kubernetes-dashboard/Chart.yaml
  stable/kubernetes-dashboard/README.md
  stable/kubernetes-dashboard/templates/deployment.yaml
  stable/kubernetes-dashboard/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#15346 [incubator/cassandra-reaper] Fix ingress template failing on no labels
  incubator/cassandra-reaper/Chart.yaml
  incubator/cassandra-reaper/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#15358 [stable/nginx-ingress] Update img
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/role.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15359 [stable/ambassador] Modify clusterrole for ambassador-pro
  stable/ambassador/Chart.yaml
  stable/ambassador/templates/rbac.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#15362 [stable/grafana] Update img
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15367 [incubator/jaeger] FIX - Set elasticsearch password only if used
  incubator/jaeger/Chart.yaml
  incubator/jaeger/templates/collector-deploy.yaml
  incubator/jaeger/templates/query-deploy.yaml
  incubator/jaeger/templates/spark-cronjob.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#15343 [stable/redis] allow user to supply additional configurations for master/slave and sentinel nodes
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/templates/configmap.yaml
  stable/redis/values-production.yaml
  stable/redis/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15382 [stable/grafana] Make sidecar provider configurable to fix sidecar and dashboardProvider issue
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/configmap-dashboard-provider.yaml
  stable/grafana/templates/deployment.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15385 [stable/sentry] add a prefix to helper defines
  stable/sentry/Chart.yaml
  stable/sentry/templates/NOTES.txt
  stable/sentry/templates/_helpers.tpl
  stable/sentry/templates/configmap.yaml
  stable/sentry/templates/cron-deployment.yaml
  stable/sentry/templates/hooks/db-init.job.yaml
  stable/sentry/templates/hooks/user-create.job.yaml
  stable/sentry/templates/ingress.yaml
  stable/sentry/templates/metrics-deployment.yaml
  stable/sentry/templates/metrics-prometheus.yaml
  stable/sentry/templates/metrics-service.yaml
  stable/sentry/templates/pvc.yaml
  stable/sentry/templates/secrets.yaml
  stable/sentry/templates/web-deployment.yaml
  stable/sentry/templates/web-service.yaml
  stable/sentry/templates/workers-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#15387 [stable/nginx-ingress] Fix missing api group in clusterrole
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/templates/clusterrole.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15342 [stable/rabbitmq-ha] Ensure ingress annotations defaults to empty map
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15393 [stable/ambassador] Add AMBASSADOR_NAMESPACE env var to pro container
  stable/ambassador/Chart.yaml
  stable/ambassador/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15402 [stable/prometheus] Upgrade to 2.11.1
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#15405 [stable/sematext-agent] SC-5200 Add support for LA custom configs
  stable/sematext-agent/Chart.yaml
  stable/sematext-agent/README.md
  stable/sematext-agent/templates/configmap-logagent-custom-configs.yaml
  stable/sematext-agent/templates/daemonset.yaml
  stable/sematext-agent/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#14344 [incubator/vault] Add RBAC to vault.
  incubator/vault/Chart.yaml
  incubator/vault/README.md
  incubator/vault/templates/role.yaml
  incubator/vault/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15406 [stable/ambassador] Fix ambassador-pro deployment
  stable/ambassador/Chart.yaml
  stable/ambassador/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15377 [stable/gocd] Update api versions of Deployment, Ingress, RBAC resources
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/README.md
  stable/gocd/templates/gocd-agent-deployment.yaml
  stable/gocd/templates/gocd-server-deployment.yaml
  stable/gocd/templates/ingress.yaml
  stable/gocd/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#15413 [incubator/jaeger] FIX - If elasticsearch password enabled logic
  incubator/jaeger/Chart.yaml
  incubator/jaeger/templates/collector-deploy.yaml
  incubator/jaeger/templates/query-deploy.yaml
  incubator/jaeger/templates/spark-cronjob.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#15408 [stable/prometheus] Upgrade alertmanager
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#15361 [stable/falco] Add support for more options for `falco.yaml`: syscall_event_drops, time_format_iso8601 and httpOutput
  stable/falco/CHANGELOG.md
  stable/falco/Chart.yaml
  stable/falco/README.md
  stable/falco/templates/configmap.yaml
  stable/falco/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#15398 [stable/nginx-ingress] Extend defaultBackend probes
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/default-backend-deployment.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15317 [stable/memcached] Add security context to memcached chart
  stable/memcached/Chart.yaml
  stable/memcached/README.md
  stable/memcached/templates/statefulset.yaml
  stable/memcached/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15439 [stable/nats] Standardize 'fullname' and 'name' macros
  stable/nats/Chart.yaml
  stable/nats/README.md
  stable/nats/templates/_helpers.tpl
  stable/nats/values-production.yaml
  stable/nats/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15425 [stable/rabbitmq] Standardize 'fullname' and 'name' macros
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15427 [stable/postgresql] Standardize 'fullname' and 'name' macros
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/_helpers.tpl
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15428 [stable/phpmyadmin] Standardize 'fullname' and 'name' macros
  stable/phpmyadmin/Chart.yaml
  stable/phpmyadmin/README.md
  stable/phpmyadmin/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15432 [stable/owncloud] Standardize 'fullname' and 'name' macros
  stable/owncloud/Chart.yaml
  stable/owncloud/README.md
  stable/owncloud/templates/_helpers.tpl
  stable/owncloud/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15435 [stable/opencart] Standardize 'fullname' and 'name' macros
  stable/opencart/Chart.yaml
  stable/opencart/README.md
  stable/opencart/templates/_helpers.tpl
  stable/opencart/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15420 [stable/wordpress] Standardize 'fullname' and 'name' macros
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
  stable/wordpress/templates/_helpers.tpl
  stable/wordpress/values-production.yaml
  stable/wordpress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15421 [stable/testlink] Standardize 'fullname' and 'name' macros
  stable/testlink/Chart.yaml
  stable/testlink/README.md
  stable/testlink/templates/_helpers.tpl
  stable/testlink/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15422 [stable/suitecrm] Standardize 'fullname' and 'name' macros
  stable/suitecrm/Chart.yaml
  stable/suitecrm/README.md
  stable/suitecrm/templates/_helpers.tpl
  stable/suitecrm/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15423 [stable/redmine] Standardize 'fullname' and 'name' macros
  stable/redmine/Chart.yaml
  stable/redmine/README.md
  stable/redmine/templates/_helpers.tpl
  stable/redmine/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15424 [stable/redis] Standardize 'fullname' and 'name' macros
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/values-production.yaml
  stable/redis/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15429 [stable/phpbb] Standardize 'fullname' and 'name' macros
  stable/phpbb/Chart.yaml
  stable/phpbb/README.md
  stable/phpbb/templates/_helpers.tpl
  stable/phpbb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15430 [stable/phabricator] Standardize 'fullname' and 'name' macros
  stable/phabricator/Chart.yaml
  stable/phabricator/README.md
  stable/phabricator/templates/_helpers.tpl
  stable/phabricator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#15431 [stable/parse] Standardize 'fullname' and 'name' macros
  stable/parse/Chart.yaml
  stable/parse/README.md
  stable/parse/templates/_helpers.tpl
  stable/parse/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15433 [stable/osclass] Standardize 'fullname' and 'name' macros
  stable/osclass/Chart.yaml
  stable/osclass/README.md
  stable/osclass/templates/_helpers.tpl
  stable/osclass/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15434 [stable/orangehrm] Standardize 'fullname' and 'name' macros
  stable/orangehrm/Chart.yaml
  stable/orangehrm/README.md
  stable/orangehrm/templates/_helpers.tpl
  stable/orangehrm/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15437 [stable/odoo] Standardize 'fullname' and 'name' macros
  stable/odoo/Chart.yaml
  stable/odoo/README.md
  stable/odoo/templates/_helpers.tpl
  stable/odoo/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15355 [stable/fluent-bit] Determine correct PodSecurityPolicy ApiGroup
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/templates/_helpers.tpl
  stable/fluent-bit/templates/cluster-role.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#15438 [stable/dokuwiki] Standardize 'fullname' and 'name' macros
  stable/dokuwiki/Chart.yaml
  stable/dokuwiki/README.md
  stable/dokuwiki/templates/_helpers.tpl
  stable/dokuwiki/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15441 [stable/mongodb] Standardize 'fullname' and 'name' macros
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15442 [stable/mediawiki] Standardize 'fullname' and 'name' macros
  stable/mediawiki/Chart.yaml
  stable/mediawiki/README.md
  stable/mediawiki/templates/_helpers.tpl
  stable/mediawiki/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15443 [stable/mariadb] Standardize 'fullname' and 'name' macros
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
  stable/mariadb/values-production.yaml
  stable/mariadb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15444 [stable/kubewatch] Standardize 'fullname' and 'name' macros
  stable/kubewatch/Chart.yaml
  stable/kubewatch/README.md
  stable/kubewatch/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15445 [stable/joomla] Standardize 'fullname' and 'name' macros
  stable/joomla/Chart.yaml
  stable/joomla/README.md
  stable/joomla/templates/_helpers.tpl
  stable/joomla/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15446 [stable/jasperreports] Standardize 'fullname' and 'name' macros
  stable/jasperreports/Chart.yaml
  stable/jasperreports/README.md
  stable/jasperreports/templates/_helpers.tpl
  stable/jasperreports/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#15449 [stable/drupal] Standardize 'fullname' and 'name' macros
  stable/drupal/Chart.yaml
  stable/drupal/README.md
  stable/drupal/templates/_helpers.tpl
  stable/drupal/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15458 [stable/external-dns] Fix external dns typo
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/deployment.yaml
  stable/external-dns/values-production.yaml
  stable/external-dns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15371 [stable/datadog] Regroup template yaml files
  stable/datadog/Chart.yaml
  stable/datadog/templates/agent-clusterchecks-rbac.yaml
  stable/datadog/templates/agent-clusterchecks-serviceaccount.yaml
  stable/datadog/templates/agent-clusterrole.yaml
  stable/datadog/templates/agent-clusterrolebinding-auth-delegator.yaml
  stable/datadog/templates/agent-clusterrolebinding.yaml
  stable/datadog/templates/agent-rbac.yaml
  stable/datadog/templates/agent-service-cmd.yaml
  stable/datadog/templates/agent-serviceaccount.yaml
  stable/datadog/templates/agent-services.yaml
  stable/datadog/templates/agenthpa-rolebinding.yaml
  stable/datadog/templates/apikey-secret.yaml
  stable/datadog/templates/clusterrolebinding.yaml
  stable/datadog/templates/hpa-clusterrole.yaml
  stable/datadog/templates/hpa-clusterrolebinding.yaml
  stable/datadog/templates/hpa-rbac.yaml
  stable/datadog/templates/rbac.yaml
  stable/datadog/templates/secrets.yaml
  stable/datadog/templates/serviceaccount.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XL

#15461 [incubator/vault] Fix namespace
  incubator/vault/Chart.yaml
  incubator/vault/templates/clusterrolebinding.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15462 [stable/kibana] allow to disable test
  stable/kibana/Chart.yaml
  stable/kibana/README.md
  stable/kibana/templates/tests/test-configmap.yaml
  stable/kibana/templates/tests/test.yaml
  stable/kibana/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#14981 [stable/collabora-code] Add livenessProbe and readinessProbe scheme value option
  stable/collabora-code/Chart.yaml
  stable/collabora-code/README.md
  stable/collabora-code/templates/deployment.yaml
  stable/collabora-code/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15447 [stable/ghost] Standardize 'fullname' and 'name' macros
  stable/ghost/Chart.yaml
  stable/ghost/README.md
  stable/ghost/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13981 [stable/elasticsearch-exporter] Add envs to deployment template
  stable/elasticsearch-exporter/Chart.yaml
  stable/elasticsearch-exporter/README.md
  stable/elasticsearch-exporter/templates/deployment.yaml
  stable/elasticsearch-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15475 [stable/gocd] Gocd bump up docker registry artifact plugin version
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#15476 [stable/dex] Update Dex version to v2.17.0
  stable/dex/Chart.yaml
  stable/dex/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15448 [stable/external-dns] Standardize 'fullname' and 'name' macros
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15426 [stable/prestashop] Standardize 'fullname' and 'name' macros
  stable/prestashop/Chart.yaml
  stable/prestashop/README.md
  stable/prestashop/templates/_helpers.tpl
  stable/prestashop/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15440 [stable/moodle] Standardize 'fullname' and 'name' macros
  stable/moodle/Chart.yaml
  stable/moodle/README.md
  stable/moodle/templates/_helpers.tpl
  stable/moodle/templates/deployment.yaml
  stable/moodle/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15480 [stable/mysqldump]: Add support fir existing secret for mysql password
  stable/mysqldump/Chart.yaml
  stable/mysqldump/README.md
  stable/mysqldump/files/job.tpl
  stable/mysqldump/templates/configmap.yaml
  stable/mysqldump/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#15412 [stable/concourse]: Add a default prefix
  stable/concourse/Chart.yaml
  stable/concourse/README.md
  stable/concourse/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15123 [stable/jaeger-operator] Extract common labels to _helpers.tpl
  stable/jaeger-operator/Chart.yaml
  stable/jaeger-operator/templates/crd.yaml
  stable/jaeger-operator/templates/deployment.yaml
  stable/jaeger-operator/templates/role-binding.yaml
  stable/jaeger-operator/templates/role.yaml
  stable/jaeger-operator/templates/service-account.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#15479 [stable/nginx-ingress] Add autoscaling docs for nginx-ingress
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS
