Repository helm/charts, pull requests merged in 2019-08, with the labels that each got.

#16011 [stable/openebs] update charts to 1.1.0 release
  stable/openebs/Chart.yaml
  stable/openebs/README.md
  stable/openebs/templates/clusterrole.yaml
  stable/openebs/templates/deployment-maya-apiserver.yaml
  stable/openebs/templates/validationwebhook.yaml
  stable/openebs/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15761 [stable/reloader] Update ClusterRole and ClusterRoleBinding to use full name
  stable/reloader/Chart.yaml
  stable/reloader/templates/clusterrole.yaml
  stable/reloader/templates/clusterrolebinding.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16026 [stable/gocd] Bump up GoCD Version to 19.7.0
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16018 [stable/prometheus-operator] PSP and RBAC for webhooks
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/clusterrole.yaml
  stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/clusterrolebinding.yaml
  stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/psp.yaml
  stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/role.yaml
  stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/rolebinding.yaml
  stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/serviceaccount.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15318 [stable/fluentd] Add service annotations
  stable/fluentd/Chart.yaml
  stable/fluentd/README.md
  stable/fluentd/templates/service.yaml
  stable/fluentd/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#13958 [stable/oauth2-proxy] add htpasswd-file components
  stable/oauth2-proxy/Chart.yaml
  stable/oauth2-proxy/README.md
  stable/oauth2-proxy/templates/configmap-htpasswd-file.yaml
  stable/oauth2-proxy/templates/deployment.yaml
  stable/oauth2-proxy/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15997 [stable/ambassador] Ambassador/0.74
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16035 [stable/spring-cloud-data-flow] Update to new SCDF version 2.2.0
  stable/spring-cloud-data-flow/Chart.yaml
  stable/spring-cloud-data-flow/README.md
  stable/spring-cloud-data-flow/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#15964 stable/nginx-ingress Allows customization of the tcp/udp configmap namespace
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/ci/daemonset-tcp-udp-configMapNamespace-values.yaml
  stable/nginx-ingress/ci/deployment-tcp-udp-configMapNamespace-values.yaml
  stable/nginx-ingress/templates/controller-deployment.yaml
  stable/nginx-ingress/templates/controller-service.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#16028 [stable/nginx-ingress] Make nginx-ingress hpa resource configurable
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-hpa.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#16037 [stable/prometheus-operator]: allow to disable time and network default rules
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/templates/prometheus/rules/node-network.yaml
  stable/prometheus-operator/templates/prometheus/rules/node-time.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#16002 [stable/newrelic-infrastructure] Update docs
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16057 [stable/ghost] Update MariaDB dependency version
  stable/ghost/Chart.yaml
  stable/ghost/requirements.lock
  stable/ghost/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16033 [stable/pomerium] Add prometheus operator ServiceMonitor support
  stable/pomerium/Chart.yaml
  stable/pomerium/README.md
  stable/pomerium/templates/authenticate-service.yaml
  stable/pomerium/templates/authorize-service.yaml
  stable/pomerium/templates/proxy-service.yaml
  stable/pomerium/templates/servicemonitor.yaml
  stable/pomerium/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#16058 [stable/newrelic-infrastructure] Update image version
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16059 [stable/hazelcast] Bump Hazelcast version 3.12.2
  stable/hazelcast/Chart.yaml
  stable/hazelcast/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#16063 [stable/parse] Fix issue in secret generation
  stable/parse/Chart.yaml
  stable/parse/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16041 [stable/cluster-autoscaler] add support for configmap for containers environment variables
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/README.md
  stable/cluster-autoscaler/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15963 [stable/jenkins] Provide default job value
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14996 [incubator/kafka] Fix offsets.topic.replication.factor to be derived from .Values.replicas
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
  incubator/kafka/templates/_helpers.tpl
  incubator/kafka/templates/statefulset.yaml
  incubator/kafka/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16068 [stable/jenkins] Use fixed container name
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/jenkins-master-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#16069 [stable/jenkins] update Jenkins plugins to fix security issue
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/ci/casc-values.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#15558 [stable/dex] fixes and improvements
  stable/dex/Chart.yaml
  stable/dex/README.md
  stable/dex/templates/_helpers.tpl
  stable/dex/templates/clusterrole.yaml
  stable/dex/templates/clusterrolebinding.yaml
  stable/dex/templates/config-openssl.yaml
  stable/dex/templates/deployment.yaml
  stable/dex/templates/ingress.yaml
  stable/dex/templates/job-grpc-certs.yaml
  stable/dex/templates/job-web-certs.yaml
  stable/dex/templates/poddisruptionbudget.yaml
  stable/dex/templates/role.yaml
  stable/dex/templates/rolebinding.yaml
  stable/dex/templates/secret.yaml
  stable/dex/templates/service.yaml
  stable/dex/templates/serviceaccount.yaml
  stable/dex/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#16023 [stable/cerebro] upgrade to 0.8.4
  stable/cerebro/Chart.yaml
  stable/cerebro/README.md
  stable/cerebro/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#16061 upgrade pushgateway
  stable/prometheus-pushgateway/Chart.yaml
  stable/prometheus-pushgateway/README.md
  stable/prometheus-pushgateway/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#16077 [stable/minecraft] Minecraft updates. Version bump, memory fix and pod assignment config
  stable/minecraft/Chart.yaml
  stable/minecraft/templates/deployment.yaml
  stable/minecraft/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#16064 [stable/minio] Added pod label capability in minio charts
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/templates/deployment.yaml
  stable/minio/templates/statefulset.yaml
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16075 [stable/prometheus-nats-exporter] fix hardcoded cluster dns name
  stable/prometheus-nats-exporter/Chart.yaml
  stable/prometheus-nats-exporter/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15745 [stable/prometheus-cloudwatch-exporter] Fix documentation typos (README.md)
  stable/prometheus-cloudwatch-exporter/Chart.yaml
  stable/prometheus-cloudwatch-exporter/README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#15154 [stable/prometheus-blackbox-exporter] Fixes issue where containers in deployment were running as root
  stable/prometheus-blackbox-exporter/Chart.yaml
  stable/prometheus-blackbox-exporter/README.md
  stable/prometheus-blackbox-exporter/templates/deployment.yaml
  stable/prometheus-blackbox-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16062 [stable/grafana] Add env vars for download dashboard container
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/deployment.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15992 [stable/external-dns]: coredns etcd backend configuration added
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/deployment.yaml
  stable/external-dns/values-production.yaml
  stable/external-dns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#16034 [stable/minio] update minio and mc
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#16071 [stable/pomerium] v0.2.0 Updates
  stable/pomerium/Chart.yaml
  stable/pomerium/README.md
  stable/pomerium/templates/configmap.yaml
  stable/pomerium/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#16093 [stable/kube-state-metrics] Version bump to 1.7.2
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
  stable/kube-state-metrics/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16091 [stable/openvpn] custom definitions for iptables rules
  stable/openvpn/Chart.yaml
  stable/openvpn/README.md
  stable/openvpn/templates/config-openvpn.yaml
  stable/openvpn/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16095 [stable/external-dns] Updating cluster role for kubernetes 1.14 support
  stable/external-dns/Chart.yaml
  stable/external-dns/templates/clusterrole.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16082 [stable/dex] OWNERS list updated
  stable/dex/Chart.yaml
  stable/dex/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16103 [stable/anchore-engine] update anchore-engine image to v0.4.2
  stable/anchore-engine/Chart.yaml
  stable/anchore-engine/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#16108 [stable/falco] Support pod priority for the daemonset
  stable/falco/CHANGELOG.md
  stable/falco/Chart.yaml
  stable/falco/README.md
  stable/falco/templates/daemonset.yaml
  stable/falco/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#16112 [stable/sealed-secrets] fix RO tmp
  stable/sealed-secrets/Chart.yaml
  stable/sealed-secrets/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16116 [stable/ambassador] Bump ambassador version 0.74.1
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#15210 [stable/traefik]: traefik metrics port when prometheus is enabled
  stable/traefik/Chart.yaml
  stable/traefik/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#16089 [stable/node-problem-detector] fix psp
  stable/node-problem-detector/Chart.yaml
  stable/node-problem-detector/templates/psp-clusterrolebinding.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16122 [stable/karma] Upgrade to 0.42
  stable/karma/Chart.yaml
  stable/karma/README.md
  stable/karma/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#16128 [stable/mongodb] Change image to one that supports initdbScripts
  stable/mongodb/Chart.yaml
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16107 [stable/sysdig] Update to latest agent version
  stable/sysdig/CHANGELOG.md
  stable/sysdig/Chart.yaml
  stable/sysdig/README.md
  stable/sysdig/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15768 [stable/openebs] Fixing nodeSelector and tolerations indentation
  stable/openebs/Chart.yaml
  stable/openebs/templates/deployment-ndm-operator.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16100 [stable/gocd] Update pipeline config API, use getting started repo's build script
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/templates/configmap.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#16130 [stable/minio] Indentation fix for pod label capability
  stable/minio/Chart.yaml
  stable/minio/templates/deployment.yaml
  stable/minio/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16140 [stable/rabbitmq] Add instructions for 'Horizontal Scaling'
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16115 [stable/nginx-ingress] add terminationGracePeriodSeconds option
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/ci/deamonset-hostport-values.yaml
  stable/nginx-ingress/templates/controller-deployment.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16087 [stable/cerebro] fixes #12910
  stable/cerebro/Chart.yaml
  stable/cerebro/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16149 [stable/ambassador] Apro/0.6.0
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/templates/deployment.yaml
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16125 [stable/node-problem-detector] upgrade node-problem-detector to 0.7
  stable/node-problem-detector/Chart.yaml
  stable/node-problem-detector/README.md
  stable/node-problem-detector/templates/daemonset.yaml
  stable/node-problem-detector/templates/service.yaml
  stable/node-problem-detector/templates/servicemonitor.yaml
  stable/node-problem-detector/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#16159 [stable/airflow] Airflow connections values fix
  stable/airflow/Chart.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#16138 [stable/grafana] Add (optional) subPath for extraConfigmapMounts
  stable/grafana/Chart.yaml
  stable/grafana/templates/deployment.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16136 [stable/wordpress] Add a parameter to specify the scheme to generate application URLs
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
  stable/wordpress/templates/deployment.yaml
  stable/wordpress/values-production.yaml
  stable/wordpress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15934 [stable/coredns] Version bump to 1.6.1
  stable/coredns/Chart.yaml
  stable/coredns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16142 [stable/minio] Add Bucket Pod Label Capability for network policy communication when…
  stable/minio/Chart.yaml
  stable/minio/templates/post-install-create-bucket-job.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16162 [stable/external-dns] readd podLabels
  stable/external-dns/Chart.yaml
  stable/external-dns/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16133 [stable/clamav] Add freshclam config
  stable/clamav/Chart.yaml
  stable/clamav/templates/deployment.yaml
  stable/clamav/templates/freshclam-configmap.yaml
  stable/clamav/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#16177 [stable/chart/prometheus-operator] fix prometheus-operator chart readme
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#16169 [stable/jasperreports] Fix deployment notes and typos in values.yaml
  stable/jasperreports/Chart.yaml
  stable/jasperreports/templates/NOTES.txt
  stable/jasperreports/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16153 [stable/concourse] bump to concourse 5.4.1
  stable/concourse/Chart.yaml
  stable/concourse/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16180 [stable/nats] Improve NOTES.txt
  stable/nats/Chart.yaml
  stable/nats/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16185 [stable/rabbitmq] Improve NOTES.txt
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/NOTES.txt
  stable/rabbitmq/templates/statefulset.yaml
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#16172 [stable/minio] Bump version minio
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#15967 [stable/rabbitmq-ha] Update readiness/liveness probes to use `rabbitmqctl status`
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/templates/statefulset.yaml
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15986 [stable/coredns]: extra secret volumes support added
  stable/coredns/Chart.yaml
  stable/coredns/templates/deployment.yaml
  stable/coredns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16175 [stable/external-dns] put podLabels inside the correct section
  stable/external-dns/Chart.yaml
  stable/external-dns/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16189 [stable/kube-state-metrics] update rbac to use new ingress api group …
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/templates/clusterrole.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16179 [stable/prometheus-redis-exporter] Updated version of redis_exporter by oliver006 to version 1.0.4
  stable/prometheus-redis-exporter/Chart.yaml
  stable/prometheus-redis-exporter/README.md
  stable/prometheus-redis-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16124 [stable/minio] Add resources to bucket creation job
  stable/minio/Chart.yaml
  stable/minio/templates/post-install-create-bucket-job.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16139 [stable/nginx-ingress] Remove obsolete stats configuration (#16137)
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/ci/deamonset-hostport-values.yaml
  stable/nginx-ingress/ci/deamonset-stats-values.yaml
  stable/nginx-ingress/ci/deployment-stats-values.yaml
  stable/nginx-ingress/templates/controller-daemonset.yaml
  stable/nginx-ingress/templates/controller-deployment.yaml
  stable/nginx-ingress/templates/controller-stats-service.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#16187 [stable/influxdb] add ability to enable flux service
  stable/influxdb/Chart.yaml
  stable/influxdb/templates/config.yaml
  stable/influxdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16199 [stable/rabbitmq] Fix wrong tab
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/values-production.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15669 [stable/elasticsearch-curator] Update to 5.7.6 by changing docker repository
  stable/elasticsearch-curator/Chart.yaml
  stable/elasticsearch-curator/OWNERS
  stable/elasticsearch-curator/README.md
  stable/elasticsearch-curator/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#16196 [stable/prometheus-operator]: fix pdb docs
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#16161 [incubator/kafka] update NOTES.txt
  incubator/kafka/Chart.yaml
  incubator/kafka/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16214 [stable/redmine] Increased Redmine livenessProbe
  stable/redmine/Chart.yaml
  stable/redmine/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16191 [stable/kong] render .env last in templates
  stable/kong/Chart.yaml
  stable/kong/templates/controller-deployment.yaml
  stable/kong/templates/deployment.yaml
  stable/kong/templates/migrations-post-upgrade.yaml
  stable/kong/templates/migrations-pre-upgrade.yaml
  stable/kong/templates/migrations.yaml
  stable/kong/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16080 [stable/redis-ha] Simplify livenessProbes, remove readinessProbes
  stable/redis-ha/Chart.yaml
  stable/redis-ha/templates/redis-ha-healthchecks.yaml
  stable/redis-ha/templates/redis-ha-statefulset.yaml
  stable/redis-ha/templates/tests/test-redis-ha-configmap.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#16081 [stable/redis-ha] Allow templating in customConfig blocks
  stable/redis-ha/Chart.yaml
  stable/redis-ha/templates/redis-ha-configmap.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15756 [stable/openvpn] Adds dippynark to OWNERS
  stable/openvpn/Chart.yaml
  stable/openvpn/OWNERS
Labels: Contribution Allowed, approved, lgtm, size/S

#16205 [stable/nextcloud] Add flexibility and more configurations
  stable/nextcloud/Chart.yaml
  stable/nextcloud/README.md
  stable/nextcloud/templates/config.yaml
  stable/nextcloud/templates/cronjob.yaml
  stable/nextcloud/templates/deployment.yaml
  stable/nextcloud/templates/nextcloud-pvc.yaml
  stable/nextcloud/templates/php-config.yaml
  stable/nextcloud/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#16186 [stable/mssql-linux] allow using existing secret for sa password (#16…
  stable/mssql-linux/Chart.yaml
  stable/mssql-linux/README.md
  stable/mssql-linux/templates/NOTES.txt
  stable/mssql-linux/templates/_helpers.tpl
  stable/mssql-linux/templates/deployment.yaml
  stable/mssql-linux/templates/secret.yaml
  stable/mssql-linux/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#16210 [stable/prometheus-operator]: fix alertmanagr pdb docs
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#16200 [stable/minio] Fix 'mc policy' command syntax for new mc versions
  stable/minio/Chart.yaml
  stable/minio/templates/_helper_create_bucket.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16183 [stable/cerebro] run with security context and be able to run as non…
  stable/cerebro/Chart.yaml
  stable/cerebro/README.md
  stable/cerebro/templates/deployment.yaml
  stable/cerebro/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#16231 [stable/weave-scope] Allow containers to have extra flags
  stable/weave-scope/Chart.yaml
  stable/weave-scope/README.md
  stable/weave-scope/charts/weave-scope-agent/templates/daemonset.yaml
  stable/weave-scope/charts/weave-scope-frontend/templates/deployment.yaml
  stable/weave-scope/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15706 [incubator/mysqlha] Standardize the `fullnameOverride` and the `nameOverride` mysqlha
  incubator/mysqlha/Chart.yaml
  incubator/mysqlha/README.md
  incubator/mysqlha/templates/_helpers.tpl
  incubator/mysqlha/templates/configmap.yaml
  incubator/mysqlha/templates/secret.yaml
  incubator/mysqlha/templates/statefulset.yaml
  incubator/mysqlha/templates/svc.yaml
  incubator/mysqlha/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#16164 [stable/hlf-ca] Update owners
  stable/hlf-ca/Chart.yaml
  stable/hlf-ca/OWNERS
Labels: Contribution Allowed, approved, lgtm, size/S

#16165 [stable/hlf-ord] Update owners
  stable/hlf-ord/Chart.yaml
  stable/hlf-ord/OWNERS
Labels: Contribution Allowed, approved, lgtm, size/S

#16166 [stable/hlf-peer] Update owners
  stable/hlf-peer/Chart.yaml
  stable/hlf-peer/OWNERS
Labels: Contribution Allowed, approved, lgtm, size/S

#16167 [stable/hlf-couchdb] Update owners
  stable/hlf-couchdb/Chart.yaml
  stable/hlf-couchdb/OWNERS
Labels: Contribution Allowed, approved, lgtm, size/S

#16168 [stable/hl-composer] Update owners
  stable/hl-composer/Chart.yaml
  stable/hl-composer/OWNERS
Labels: Contribution Allowed, approved, lgtm, size/S

#16245 [stable/mongodb] Use bitnami/mongodb-exporter
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16246 [stable/nats] Use bitnami/nats-exporter
  stable/nats/Chart.yaml
  stable/nats/README.md
  stable/nats/values-production.yaml
  stable/nats/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16247 [stable/rabbitmq] Use bitnami/rabbitmq-exporter
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16255 [stable/graylog] enable configuration of initContainer resources
  stable/graylog/Chart.yaml
  stable/graylog/README.md
  stable/graylog/templates/statefulset.yaml
  stable/graylog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16217 [stable/nginx-ingress] replace ambiguous controller.headers option
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/ci/daemonset-headers-values.yaml
  stable/nginx-ingress/ci/deployment-headers-values.yaml
  stable/nginx-ingress/templates/NOTES.txt
  stable/nginx-ingress/templates/addheaders-configmap.yaml
  stable/nginx-ingress/templates/controller-configmap.yaml
  stable/nginx-ingress/templates/proxyheaders-configmap.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#16227 [stable/prometheus-operator] Updating ingress RBAC to access networki…
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/prometheus/clusterrole.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15739 [stable/dex] ADD annotations to grpc and web pods FIX #15451
  stable/dex/Chart.yaml
  stable/dex/README.md
  stable/dex/templates/job-grpc-certs.yaml
  stable/dex/templates/job-web-certs.yaml
  stable/dex/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#16254 [stable/openebs] fix localprovisioner replica
  stable/openebs/Chart.yaml
  stable/openebs/templates/deployment-local-provisioner.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16259 [incubator/sparkoperator] Upgrade version to v1beta1-0.9.0
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#11079 Add kube-downscaler
  incubator/kube-downscaler/Chart.yaml
  incubator/kube-downscaler/README.md
  incubator/kube-downscaler/templates/NOTES.txt
  incubator/kube-downscaler/templates/_helpers.tpl
  incubator/kube-downscaler/templates/clusterrole.yaml
  incubator/kube-downscaler/templates/clusterrolebinding.yaml
  incubator/kube-downscaler/templates/deployment.yaml
  incubator/kube-downscaler/templates/serviceaccount.yaml
  incubator/kube-downscaler/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#11343 [incubator/zookeeper] Support Zookeeper official (3.5.4) image
  incubator/zookeeper/Chart.yaml
  incubator/zookeeper/README.md
  incubator/zookeeper/templates/config-script.yaml
  incubator/zookeeper/templates/statefulset.yaml
  incubator/zookeeper/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#12055 [incubator/honeydipper] an event driven orchestration system
  incubator/honeydipper/.helmignore
  incubator/honeydipper/Chart.yaml
  incubator/honeydipper/OWNERS
  incubator/honeydipper/README.md
  incubator/honeydipper/templates/NOTES.txt
  incubator/honeydipper/templates/_helpers.tpl
  incubator/honeydipper/templates/daemon-deployment.yaml
  incubator/honeydipper/templates/tests/test-webhook-service.yaml
  incubator/honeydipper/templates/webhook-ingress.yaml
  incubator/honeydipper/templates/webhook-service.yaml
  incubator/honeydipper/test-values.yaml
  incubator/honeydipper/test_fixtures/init.yaml
  incubator/honeydipper/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#12552 [stable/dask] Update stable dask with new container versions, better documentation, more options.
  stable/dask/Chart.yaml
  stable/dask/OWNERS
  stable/dask/README.md
  stable/dask/templates/NOTES.txt
  stable/dask/templates/dask-jupyter-config.yaml
  stable/dask/templates/dask-jupyter-deployment.yaml
  stable/dask/templates/dask-jupyter-service.yaml
  stable/dask/templates/dask-scheduler-deployment.yaml
  stable/dask/templates/dask-worker-deployment.yaml
  stable/dask/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#14918 [stable/prometheus-postgres-exporter]: add the ability to create a ServiceMonitor
  stable/prometheus-postgres-exporter/Chart.yaml
  stable/prometheus-postgres-exporter/README.md
  stable/prometheus-postgres-exporter/templates/servicemonitor.yaml
  stable/prometheus-postgres-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#14005 [stable/metallb] Add support for prometheus-operator
  stable/metallb/Chart.yaml
  stable/metallb/templates/prometheusrules.yaml
  stable/metallb/templates/service.yaml
  stable/metallb/templates/servicemonitor.yaml
  stable/metallb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#14671 [stable/neo4j] Add the bolt protocol on port 7687 to the Service
  stable/neo4j/Chart.yaml
  stable/neo4j/templates/core-dns.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14849 [stable/fluent-bit] Adding ES auth secret
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/config.yaml
  stable/fluent-bit/templates/daemonset.yaml
  stable/fluent-bit/templates/secret.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15058 [stable/graylog] Adding namespace flag to finding the master nodes
  stable/graylog/Chart.yaml
  stable/graylog/templates/configmap.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15061 [stable/spinnaker] Fix environment variable name for proxy in Java
  stable/spinnaker/Chart.yaml
  stable/spinnaker/README.md
  stable/spinnaker/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15138 [stable/airflow] Add readinessProbe
  stable/airflow/Chart.yaml
  stable/airflow/requirements.lock
  stable/airflow/templates/deployments-web.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#13728 [stable/traefik] add servicemonitor
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/servicemonitor.yaml
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#13922 [stable/prometheus] Add options to change volume mount propagation (s…
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/node-exporter-daemonset.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15280 [stable/atlantis] for bitbucket server credentials: baseURL name consistency
  stable/atlantis/Chart.yaml
  stable/atlantis/templates/secret-webhook.yaml
  stable/atlantis/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16038 [stable/cloudserver] Add tmacro as maintainer
  stable/cloudserver/Chart.yaml
  stable/cloudserver/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16134 [stable/prometheus-rabbitmq-exporter] Rabbitmq prometheus exporter should use the same name for the port
  stable/prometheus-rabbitmq-exporter/Chart.yaml
  stable/prometheus-rabbitmq-exporter/templates/service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16145 [stable/jenkins] Ability to set custom namespace for ServiceMonitor
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/jenkins-master-servicemonitor.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16092 [stable/kube2iam] Update version in documentation
  stable/kube2iam/Chart.yaml
  stable/kube2iam/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16150 [stable/consul] joinPeers and joinWan stability and reliability improvements
  stable/consul/Chart.yaml
  stable/consul/README.md
  stable/consul/templates/consul-statefulset.yaml
  stable/consul/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#16208 [stable/datadog] Add an option to reference an existing clusterAgent.token
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/NOTES.txt
  stable/datadog/templates/_helpers.tpl
  stable/datadog/templates/agent-clusterchecks-deployment.yaml
  stable/datadog/templates/agent-secret.yaml
  stable/datadog/templates/cluster-agent-deployment.yaml
  stable/datadog/templates/container-agent.yaml
  stable/datadog/templates/container-agents.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16274 [stable/odoo] Increase Odoo livenessProbe initialDelaySeconds
  stable/odoo/Chart.yaml
  stable/odoo/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16281 [stable/prometheus-operator] Fixed README to reflect prometheus deployment template
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16284 [stable/kube-state-metrics] Update liveness- and readinessProbes
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16285 [stable/chartmuseum] added the fix for the issue - service.servicename in values breaking ingress
  stable/chartmuseum/Chart.yaml
  stable/chartmuseum/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16299 [stable/opa] Annotations in deployment template, prometheus endpoint
  stable/opa/Chart.yaml
  stable/opa/README.md
  stable/opa/templates/deployment.yaml
  stable/opa/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#16297 [stable/mysqtl] readme; adding service.type
  stable/mysql/Chart.yaml
  stable/mysql/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16304 [incubator/kubeless] Bump version kubeless to v1.0.4
  incubator/kubeless/Chart.yaml
  incubator/kubeless/README.md
  incubator/kubeless/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#16309 [stable/grafana] updated sidecar container
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16314 [stable/pomerium] Version bump to 0.2.1
  stable/pomerium/Chart.yaml
  stable/pomerium/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#16315 [stable/grafana] fixed sidecar image version
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16288 [stable/airflow] add support for secrets on webserver
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/templates/deployments-web.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#16152 [stable/ambassador] Apro/env+ambassador
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/templates/ambassador-pro-service.yaml
  stable/ambassador/templates/deployment.yaml
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#16268 [stable/mysqldump] Add support for uploading backups to OpenStack
  stable/mysqldump/Chart.yaml
  stable/mysqldump/README.md
  stable/mysqldump/files/job.tpl
  stable/mysqldump/files/openstack-upload.py
  stable/mysqldump/templates/NOTES.txt
  stable/mysqldump/templates/configmap.yaml
  stable/mysqldump/templates/secret.yaml
  stable/mysqldump/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#16325 [stable/ambassador] Bump ambassador to 0.75
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16326 [stable/phpmyadmin] Fix phpMyAdmin logo link.
  stable/phpmyadmin/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15286 [stable/kong] Allow for declarative configuration (#15284)
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/ci/dbless-no-kic-internal-declarative-config-values.yaml
  stable/kong/ci/dbless-no-kic-values.yaml
  stable/kong/ci/dbless-values.yaml
  stable/kong/templates/_helpers.tpl
  stable/kong/templates/config-dbless.yaml
  stable/kong/templates/deployment.yaml
  stable/kong/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#16332 [stable/opa] Adding ability to specify bootstrap policies through values.yaml
  stable/opa/Chart.yaml
  stable/opa/README.md
  stable/opa/templates/deployment.yaml
  stable/opa/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#15574 [incubator/patroni] add schedulerName option
  incubator/patroni/Chart.yaml
  incubator/patroni/README.md
  incubator/patroni/templates/statefulset-patroni.yaml
  incubator/patroni/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16336 [stable/nginx-ingress] Bump version of ingress-nginx to 0.25.1
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/templates/NOTES.txt
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16321 [stable/rocketchat] update to 1.3.1, upgrade mongo to latest helm chart
  stable/rocketchat/Chart.yaml
  stable/rocketchat/README.md
  stable/rocketchat/requirements.lock
  stable/rocketchat/requirements.yaml
  stable/rocketchat/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#12682 Add Chart to deploy Couchbase Operator
  stable/couchbase-operator/.helmignore
  stable/couchbase-operator/Chart.yaml
  stable/couchbase-operator/OWNERS
  stable/couchbase-operator/templates/NOTES.txt
  stable/couchbase-operator/templates/_helpers.tpl
  stable/couchbase-operator/templates/admission-cluster-role-binding.yaml
  stable/couchbase-operator/templates/admission-cluster-role.yaml
  stable/couchbase-operator/templates/admission-deployment.yaml
  stable/couchbase-operator/templates/admission-service-account.yaml
  stable/couchbase-operator/templates/admission-service.yaml
  stable/couchbase-operator/templates/couchbase-cluster-role-binding.yaml
  stable/couchbase-operator/templates/couchbase-cluster-role.yaml
  stable/couchbase-operator/templates/couchbase-deployment.yaml
  stable/couchbase-operator/templates/couchbase-role-template.yaml
  stable/couchbase-operator/templates/couchbase-service-account.yaml
  stable/couchbase-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XL

#16129 [stable/metabase] Add tolerations and affinity
  stable/metabase/Chart.yaml
  stable/metabase/README.md
  stable/metabase/templates/deployment.yaml
  stable/metabase/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#16311 [stable/metallb] Fix helm warnings
  stable/metallb/Chart.yaml
  stable/metallb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14629 [stable/jaeger-operator] Change operator role to a cluster role
  stable/jaeger-operator/Chart.yaml
  stable/jaeger-operator/README.md
  stable/jaeger-operator/templates/deployment.yaml
  stable/jaeger-operator/templates/role-binding.yaml
  stable/jaeger-operator/templates/role.yaml
  stable/jaeger-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S
