Repository helm/charts, pull requests merged in 2019-02, with the labels that each got.

#10975 [stable/kibana]: remove ports from initContainers
  stable/kibana/Chart.yaml
  stable/kibana/README.md
  stable/kibana/ci/authproxy-enabled.yaml
  stable/kibana/ci/disabled-internal-port.yaml
  stable/kibana/templates/deployment.yaml
  stable/kibana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9684 [stable/prometheus-operator] Removed duplicate nodePort in prometheus service
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/prometheus/service.yaml
Labels: Contribution Allowed, approved, lgtm, lifecycle/stale, ok-to-test, size/XS

#11052 [stable/mm-te] Bump MM-te to 5.7.1
  stable/mattermost-team-edition/Chart.yaml
  stable/mattermost-team-edition/README.md
  stable/mattermost-team-edition/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#11036 [stable/drone] adding permission to update deployments for pipeline clusterrole
  stable/drone/Chart.yaml
  stable/drone/templates/role-pipeline.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#10147 [stable/spinnaker] remove ending slash of gate's url
  stable/spinnaker/Chart.yaml
  stable/spinnaker/templates/configmap/halyard-init-script.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#11050 [stable/prometheus-operator] Fix Documentation: prometheusOperator.logFormat code block
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10286 [stable/k8s-spot-termination-handler] Merge [incubator/kube-spot-termination-notice-handler] into this chart
  incubator/kube-spot-termination-notice-handler/.helmignore
  incubator/kube-spot-termination-notice-handler/Chart.yaml
  incubator/kube-spot-termination-notice-handler/README.md
  incubator/kube-spot-termination-notice-handler/templates/NOTES.txt
  incubator/kube-spot-termination-notice-handler/templates/_helpers.tpl
  incubator/kube-spot-termination-notice-handler/templates/daemonset.yaml
  incubator/kube-spot-termination-notice-handler/templates/rbac.yaml
  incubator/kube-spot-termination-notice-handler/templates/serviceaccount.yaml
  incubator/kube-spot-termination-notice-handler/values.yaml
  stable/k8s-spot-termination-handler/Chart.yaml
  stable/k8s-spot-termination-handler/README.md
  stable/k8s-spot-termination-handler/templates/NOTES.txt
  stable/k8s-spot-termination-handler/templates/_helpers.tpl
  stable/k8s-spot-termination-handler/templates/clusterrole.yaml
  stable/k8s-spot-termination-handler/templates/clusterrolebinding.yaml
  stable/k8s-spot-termination-handler/templates/daemonset.yaml
  stable/k8s-spot-termination-handler/templates/serviceaccount.yaml
  stable/k8s-spot-termination-handler/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#11054 [stable/drone] bump version to rc5, simplify container names
  stable/drone/Chart.yaml
  stable/drone/templates/deployment-agent.yaml
  stable/drone/templates/deployment-server.yaml
  stable/drone/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#11075 Add pod security policy support to metrics server
  stable/metrics-server/Chart.yaml
  stable/metrics-server/README.md
  stable/metrics-server/templates/cluster-role.yaml
  stable/metrics-server/templates/psp.yaml
  stable/metrics-server/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11077 [stable/karma] make configchanges roll the deployment
  stable/karma/Chart.yaml
  stable/karma/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#11058 kiam - added missing patch verb on the RBAC configuration for server
  stable/kiam/Chart.yaml
  stable/kiam/templates/server-write-clusterrole.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#11061 Grafana: make change of ownership on init optional
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/deployment.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11093 [stable/mysqldump] add missing rc variable which makes successful jobs fail
  stable/mysqldump/Chart.yaml
  stable/mysqldump/templates/configmap.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#10663 [stable/spinnaker] Option to use external redis
  stable/spinnaker/Chart.yaml
  stable/spinnaker/requirements.lock
  stable/spinnaker/requirements.yaml
  stable/spinnaker/templates/configmap/halyard-init-script.yaml
  stable/spinnaker/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11103 upgrade kube-hunter
  stable/kube-hunter/Chart.yaml
  stable/kube-hunter/README.md
  stable/kube-hunter/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#11094 [stable/kube-state-metrics] Use rbac.authorization.k8s.io/v1 apiVersion in RBAC resources
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/templates/psp-clusterrole.yaml
  stable/kube-state-metrics/templates/psp-clusterrolebinding.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11099 [stable/fluent-bit] Update to 1.0.4
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11065 [incubator/vault] Add loadBalancerIP to configure static LB IP
  incubator/vault/Chart.yaml
  incubator/vault/README.md
  incubator/vault/templates/service.yaml
  incubator/vault/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11100 [stable/mysqldump] option to run additional shell steps
  stable/mysqldump/Chart.yaml
  stable/mysqldump/README.md
  stable/mysqldump/templates/NOTES.txt
  stable/mysqldump/templates/configmap.yaml
  stable/mysqldump/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#11114 [stable/elasticsearch] make readiness probes configurable
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/README.md
  stable/elasticsearch/templates/data-statefulset.yaml
  stable/elasticsearch/templates/master-statefulset.yaml
  stable/elasticsearch/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#10288 [stable/traefik] HorizontalPodAutoscaler
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/hpa.yaml
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#10757 [stable/postgresql] Add support for the official postgres image env vars
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/NOTES.txt
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#11072 Add source for docker image
  stable/fluentd/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10205 [stable/efs-provisioner] Add nodeselector, affinity, podAnnotations
  stable/efs-provisioner/Chart.yaml
  stable/efs-provisioner/README.md
  stable/efs-provisioner/templates/deployment.yaml
  stable/efs-provisioner/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#10740 [stable/oauth2-proxy] Switch to pusher/oauth2_proxy
  stable/oauth2-proxy/Chart.yaml
  stable/oauth2-proxy/OWNERS
  stable/oauth2-proxy/README.md
  stable/oauth2-proxy/templates/NOTES.txt
  stable/oauth2-proxy/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#10906 Allow overriding of parser for tail input
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/config.yaml
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#10612 Allow healthz endpoint as hostport
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-daemonset.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9728 [stable/seq] Fixing data volume mounting
  stable/seq/Chart.yaml
  stable/seq/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#11122 [stable/elasticsearch] Add ability to disable sysctl init container.
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/README.md
  stable/elasticsearch/templates/client-deployment.yaml
  stable/elasticsearch/templates/data-statefulset.yaml
  stable/elasticsearch/templates/master-statefulset.yaml
  stable/elasticsearch/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11029 [stable/redis] Make volumePermissions init container optional
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/templates/redis-master-statefulset.yaml
  stable/redis/values-production.yaml
  stable/redis/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11134 [stable/memcached] Bump memcached version, add tolerations and affinity support
  stable/memcached/Chart.yaml
  stable/memcached/README.md
  stable/memcached/templates/statefulset.yaml
  stable/memcached/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11141 Add missing port-forward example for spin-gate in the NOTES.txt
  stable/spinnaker/Chart.yaml
  stable/spinnaker/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11165 [stable/oauth2-proxy] Allow defining a custom secret
  stable/oauth2-proxy/Chart.yaml
  stable/oauth2-proxy/README.md
  stable/oauth2-proxy/templates/_helpers.tpl
  stable/oauth2-proxy/templates/deployment.yaml
  stable/oauth2-proxy/templates/secret.yaml
  stable/oauth2-proxy/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#11063 [stable/grafana] Fix sidecar label defaults in README.
  stable/grafana/Chart.yaml
  stable/grafana/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#11180 [stable/envoy] Fix template for config files
  stable/envoy/Chart.yaml
  stable/envoy/templates/configmap.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#11160 [stable/elastalert] Allow adding additional global config options
  stable/elastalert/Chart.yaml
  stable/elastalert/README.md
  stable/elastalert/templates/config.yaml
  stable/elastalert/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11155 [stable/wordpress] Enable configuration of AllowOverride
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
  stable/wordpress/templates/_helpers.tpl
  stable/wordpress/templates/deployment.yaml
  stable/wordpress/values-production.yaml
  stable/wordpress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11182 Add README.md to fluentd
  stable/fluentd/Chart.yaml
  stable/fluentd/OWNERS
  stable/fluentd/README.md
Labels: Contribution Allowed, approved, lgtm, size/M

#11177 Added permissions to handle ingress
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/templates/spark-operator-rbac.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#11189 Fix gcs credentials location
  stable/minio/Chart.yaml
  stable/minio/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#11197 Run atlantis container as atlantis user instead of root
  stable/atlantis/Chart.yaml
  stable/atlantis/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11085 [stable/redis-ha] Add Optional Prometheus Exporter Sidecar
  stable/redis-ha/Chart.yaml
  stable/redis-ha/README.md
  stable/redis-ha/templates/redis-ha-statefulset.yaml
  stable/redis-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#11219 Added flag for ingress URL format
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/README.md
  incubator/sparkoperator/templates/spark-operator-deployment.yaml
  incubator/sparkoperator/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#11124 [stable/mariadb] Fix typo of the install example in README
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11227 Fixed bug introduces by previous PR.
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/templates/client-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11162 feat(keycloak): add availability to expose extra port on sts
  stable/keycloak/Chart.yaml
  stable/keycloak/README.md
  stable/keycloak/templates/statefulset.yaml
  stable/keycloak/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#11230 NEXUS: bump the app version to 3.15.2
  stable/sonatype-nexus/Chart.yaml
  stable/sonatype-nexus/README.md
  stable/sonatype-nexus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11246 Atlantis 450
  stable/atlantis/Chart.yaml
  stable/atlantis/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11203 Add the ability to specify pod labels for stable/mysql chart
  stable/mysql/Chart.yaml
  stable/mysql/README.md
  stable/mysql/templates/deployment.yaml
  stable/mysql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11211 [stable/elasticsearch-curator] add dry-run option to chart
  stable/elasticsearch-curator/Chart.yaml
  stable/elasticsearch-curator/README.md
  stable/elasticsearch-curator/templates/cronjob.yaml
  stable/elasticsearch-curator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11176 [incubator/kafka] Tolerations for kafka exporter
  incubator/kafka/Chart.yaml
  incubator/kafka/templates/deployment-kafka-exporter.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11128 [stable/rocketchat] Update to 0.74.1
  stable/rocketchat/Chart.yaml
  stable/rocketchat/README.md
  stable/rocketchat/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#11229 [stable/prometheus-operator] allow setting sessionAffinity
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/prometheus/service.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11234 [stable/prometheus] Added PVC to Pushgateway
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/pushgateway-deployment.yaml
  stable/prometheus/templates/pushgateway-pvc.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11243 Add resources field to redis init containers
  stable/redis/Chart.yaml
  stable/redis/templates/redis-master-statefulset.yaml
  stable/redis/values-production.yaml
  stable/redis/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#9057 Jenkins Configuration as Code
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/NOTES.txt
  stable/jenkins/templates/_helpers.tpl
  stable/jenkins/templates/config.yaml
  stable/jenkins/templates/jcasc_config.yaml
  stable/jenkins/templates/jenkins-master-deployment.yaml
  stable/jenkins/templates/secret.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#11250 [stable/datadog] Adjust release naming in helpers
  stable/datadog/Chart.yaml
  stable/datadog/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11253 [incubator/jaeger] Updating img to 1.9.0
  incubator/jaeger/Chart.yaml
  incubator/jaeger/README.md
  incubator/jaeger/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11263 [stable/wordpress] Fix quote in htaccessoverridenone
  stable/wordpress/Chart.yaml
  stable/wordpress/values-production.yaml
  stable/wordpress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10789 Simplify for unifi
  stable/unifi/Chart.yaml
  stable/unifi/README.md
  stable/unifi/templates/controller-svc.yaml
  stable/unifi/templates/discovery-svc.yaml
  stable/unifi/templates/stun-svc.yaml
  stable/unifi/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#11252 Indent lines related to EnableRawHtmlMarkupFormatter
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/config.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11272 update clusterrole rbacs to be able to fetch clusterresourcequotas from openshift
  stable/datadog/Chart.yaml
  stable/datadog/templates/agent-clusterrole.yaml
  stable/datadog/templates/clusterrole.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#8119 Add distributed JMeter chart
  stable/distributed-jmeter/.helmignore
  stable/distributed-jmeter/Chart.yaml
  stable/distributed-jmeter/OWNERS
  stable/distributed-jmeter/README.md
  stable/distributed-jmeter/templates/NOTES.txt
  stable/distributed-jmeter/templates/_helpers.tpl
  stable/distributed-jmeter/templates/jmeter-master-deployment.yaml
  stable/distributed-jmeter/templates/jmeter-server-deployment.yaml
  stable/distributed-jmeter/templates/jmeter-server-service.yaml
  stable/distributed-jmeter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#9386 adding chart for Satisfy - Composer package hosting
  stable/satisfy/.helmignore
  stable/satisfy/Chart.yaml
  stable/satisfy/OWNERS
  stable/satisfy/README.md
  stable/satisfy/templates/NOTES.txt
  stable/satisfy/templates/_helpers.tpl
  stable/satisfy/templates/deployment.yaml
  stable/satisfy/templates/ingress.yaml
  stable/satisfy/templates/pvc.yaml
  stable/satisfy/templates/secret.yaml
  stable/satisfy/templates/service.yaml
  stable/satisfy/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#10979 [stable/prometheus-mongodb-exporter] Add MongoDB Exporter chart
  stable/prometheus-mongodb-exporter/.helmignore
  stable/prometheus-mongodb-exporter/Chart.yaml
  stable/prometheus-mongodb-exporter/OWNERS
  stable/prometheus-mongodb-exporter/README.md
  stable/prometheus-mongodb-exporter/ci/servicemonitor-disabled-values.yaml
  stable/prometheus-mongodb-exporter/templates/NOTES.txt
  stable/prometheus-mongodb-exporter/templates/_helpers.tpl
  stable/prometheus-mongodb-exporter/templates/deployment.yaml
  stable/prometheus-mongodb-exporter/templates/service.yaml
  stable/prometheus-mongodb-exporter/templates/servicemonitor.yaml
  stable/prometheus-mongodb-exporter/templates/tests/test-connection.yaml
  stable/prometheus-mongodb-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#11107 [prometheus-rabbitmq-export] Add skip_verify to rabbitmq-exporter
  stable/prometheus-rabbitmq-exporter/Chart.yaml
  stable/prometheus-rabbitmq-exporter/README.md
  stable/prometheus-rabbitmq-exporter/templates/deployment.yaml
  stable/prometheus-rabbitmq-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10950 [stable/jenkins] allow running sidecar containers for Jenkins master
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/jenkins-master-deployment.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11199 [stable/kibana] Add support for user-defined init containers
  stable/kibana/Chart.yaml
  stable/kibana/README.md
  stable/kibana/ci/initcontainers-values.yaml
  stable/kibana/templates/deployment.yaml
  stable/kibana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11293 revert indentation to previous working version
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/jenkins-master-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11137 Provide the capability to use LDAP Authentication
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/templates/_helpers.tpl
  stable/airflow/templates/deployments-flower.yaml
  stable/airflow/templates/deployments-scheduler.yaml
  stable/airflow/templates/deployments-web.yaml
  stable/airflow/templates/statefulsets-workers.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#10783 [stable/influxdb] Update image and allow naming release by chart name
  stable/influxdb/Chart.yaml
  stable/influxdb/templates/_helpers.tpl
  stable/influxdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#11262 [stable/traefik]: Add securityContext to deployment
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/deployment.yaml
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11260 [stable/kibana] Add pod custom labels
  stable/kibana/Chart.yaml
  stable/kibana/README.md
  stable/kibana/templates/deployment.yaml
  stable/kibana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11207 Add versioning policies to review guidelines
  REVIEW_GUIDELINES.md
Labels: Contribution Allowed, approved, lgtm, size/S

#8743 [stable/jenkins] Added slave Pod env vars
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/config.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10699 [stable/rabbitmq] Existing secret values switches for password / erlang cookie
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/_helpers.tpl
  stable/rabbitmq/templates/secrets.yaml
  stable/rabbitmq/templates/statefulset.yaml
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11317 Replace Prestashop with Wordpress in README
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11231 [stable/jenkins] Add option to overwrite plugins
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/config.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11044 [stable/prometheus-operator] update dependencies
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/requirements.lock
  stable/prometheus-operator/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10324 Track upstream v3-release tag, use loopback IP for probes
  stable/kiam/Chart.yaml
  stable/kiam/README.md
  stable/kiam/ci/test-values.yaml
  stable/kiam/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11278 [stable/unifi] Revert #10789
  stable/unifi/Chart.yaml
  stable/unifi/README.md
  stable/unifi/templates/controller-svc.yaml
  stable/unifi/templates/discovery-svc.yaml
  stable/unifi/templates/stun-svc.yaml
  stable/unifi/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#8593 [stable/hackmd] bump hackmd (codimd)
  stable/hackmd/Chart.yaml
  stable/hackmd/README.md
  stable/hackmd/templates/deployment.yaml
  stable/hackmd/templates/secret.yaml
  stable/hackmd/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11102 [stable/spinnaker] use spinnaker service settings to set service type
  stable/spinnaker/Chart.yaml
  stable/spinnaker/templates/configmap/halyard-init-script.yaml
  stable/spinnaker/templates/configmap/service-settings.yaml
  stable/spinnaker/templates/hooks/expose-nodeports.yaml
  stable/spinnaker/templates/statefulsets/halyard.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#10939 Mention upgrades
  stable/sentry/Chart.yaml
  stable/sentry/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#11323 [stable/elasticsearch-exporter] ServiceMonitor: set namespace to monitor + Add OWNER and add myself to owners.
  stable/elasticsearch-exporter/.helmignore
  stable/elasticsearch-exporter/Chart.yaml
  stable/elasticsearch-exporter/OWNERS
  stable/elasticsearch-exporter/templates/servicemonitor.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#10922 add nextcloud chart
  stable/nextcloud/.helmignore
  stable/nextcloud/Chart.yaml
  stable/nextcloud/README.md
  stable/nextcloud/requirements.lock
  stable/nextcloud/requirements.yaml
  stable/nextcloud/templates/NOTES.txt
  stable/nextcloud/templates/_helpers.tpl
  stable/nextcloud/templates/db-secret.yaml
  stable/nextcloud/templates/deployment.yaml
  stable/nextcloud/templates/ingress.yaml
  stable/nextcloud/templates/nextcloud-pvc.yaml
  stable/nextcloud/templates/secrets.yaml
  stable/nextcloud/templates/service.yaml
  stable/nextcloud/templates/tests/test-connection.yaml
  stable/nextcloud/values-mariadb.yaml
  stable/nextcloud/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XL

#11305 [stable/fluent-bit] Parametrize flush interval and log level in the S…
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/config.yaml
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#11336 Add redisHost variable, clear up postgresHost mysteries
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/templates/_helpers.tpl
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#11294 Ambassador chart
  stable/ambassador/.helmignore
  stable/ambassador/Chart.yaml
  stable/ambassador/OWNERS
  stable/ambassador/README.md
  stable/ambassador/ci/ci-values.yaml
  stable/ambassador/ci/default-values.yaml
  stable/ambassador/templates/NOTES.txt
  stable/ambassador/templates/_helpers.tpl
  stable/ambassador/templates/admin-service.yaml
  stable/ambassador/templates/config.yaml
  stable/ambassador/templates/deployment.yaml
  stable/ambassador/templates/exporter-config.yaml
  stable/ambassador/templates/rbac.yaml
  stable/ambassador/templates/service.yaml
  stable/ambassador/templates/serviceaccount.yaml
  stable/ambassador/templates/tests/test-ready.yaml
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XL

#11341 Cutting version 1.0.0 release for kuberhealthy
  stable/kuberhealthy/Chart.yaml
  stable/kuberhealthy/README.md
  stable/kuberhealthy/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#11226 [stable/postgresql] Fix "iptables: Permission Denined" error when installing on Istio-enabled cluster.
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11238 [stable/mongodb] Fix clusterIP indent in svc-primary-rs
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/svc-primary-rs.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11346 Update Rocketchat to 0.74.2
  stable/rocketchat/Chart.yaml
  stable/rocketchat/README.md
  stable/rocketchat/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#11339 [stable/jenkins] merge sidecard configs
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/config.yaml
  stable/jenkins/templates/jcasc_config.yaml
  stable/jenkins/templates/jenkins-master-deployment.yaml
  stable/jenkins/templates/secret.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#11338 [stable/oauth2-proxy] Bump default image to version 3.1.0 for TLS upd
  stable/oauth2-proxy/Chart.yaml
  stable/oauth2-proxy/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11314 [stable/prometheus-redis-exporter] Update image to 0.28.0
  stable/prometheus-redis-exporter/Chart.yaml
  stable/prometheus-redis-exporter/README.md
  stable/prometheus-redis-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11348 [stable/mattermost] using team edition's push server
  stable/mattermost-team-edition/Chart.yaml
  stable/mattermost-team-edition/templates/config.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11349 [stable/oauth2_proxy] Update README
  stable/oauth2-proxy/Chart.yaml
  stable/oauth2-proxy/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#11322 [stable/concourse] Remove duplicate line
  stable/concourse/Chart.yaml
  stable/concourse/templates/web-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10202 Add initial version of Sematext agent chart
  stable/sematext-agent/.helmignore
  stable/sematext-agent/Chart.yaml
  stable/sematext-agent/OWNERS
  stable/sematext-agent/README.md
  stable/sematext-agent/files/autodisco.yml
  stable/sematext-agent/templates/NOTES.txt
  stable/sematext-agent/templates/_helpers.tpl
  stable/sematext-agent/templates/clusterrole.yaml
  stable/sematext-agent/templates/clusterrolebinding.yaml
  stable/sematext-agent/templates/configmap-agent-autodisco.yaml
  stable/sematext-agent/templates/configmap-agent.yaml
  stable/sematext-agent/templates/configmap-logagent.yaml
  stable/sematext-agent/templates/daemonset.yaml
  stable/sematext-agent/templates/secret.yaml
  stable/sematext-agent/templates/service.yaml
  stable/sematext-agent/templates/serviceaccount.yaml
  stable/sematext-agent/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XL

#11233 [stable/postgresql] Allow initDb scripts in the form of secrets
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/_helpers.tpl
  stable/postgresql/templates/statefulset.yaml
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11335 Nextcloud chart add OWNERS for further contribution
  stable/nextcloud/Chart.yaml
  stable/nextcloud/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11358 [stable/airflow] Updates README.md with better instructions for installing extra dependencies
  stable/airflow/Chart.yaml
  stable/airflow/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#11357 Implements #11353 : [stable/airflow] install-requirements.sh script s…
  stable/airflow/Chart.yaml
  stable/airflow/templates/deployments-scheduler.yaml
  stable/airflow/templates/deployments-web.yaml
  stable/airflow/templates/statefulsets-workers.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11345 Add me as reviewer, default ServiceMonitor to false
  stable/kuberhealthy/Chart.yaml
  stable/kuberhealthy/OWNERS
  stable/kuberhealthy/README.md
  stable/kuberhealthy/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#11321 [incubator/vault] Add `checksum/config` annotation to pods
  incubator/vault/Chart.yaml
  incubator/vault/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11329 Update fluentd-kubernetes-sumologic to the latest (v2.3.0)
  stable/sumologic-fluentd/Chart.yaml
  stable/sumologic-fluentd/README.md
  stable/sumologic-fluentd/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11359 [stable/prometheus] Change AlertManager reload URL from localhost to 127.0.0.1
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/alertmanager-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9842 move datasources to init container.
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/deployment.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11167 Next agent release (ciprod01092019)
  incubator/azuremonitor-containers/Chart.yaml
  incubator/azuremonitor-containers/README.md
  incubator/azuremonitor-containers/templates/omsagent-daemonset.yaml
  incubator/azuremonitor-containers/templates/omsagent-deployment.yaml
  incubator/azuremonitor-containers/templates/omsagent-rs-configmap.yaml
  incubator/azuremonitor-containers/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#11354 [stable/ambassador] Allow rbac to be namespaced
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/templates/rbac.yaml
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11367 [stable/mongodb] Fix "Can't initialize iptables table 'nat': Permission denied (you must be root)" error when installed on an Istio-enabled cluster.
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/deployment-standalone.yaml
  stable/mongodb/templates/statefulset-arbiter-rs.yaml
  stable/mongodb/templates/statefulset-primary-rs.yaml
  stable/mongodb/templates/statefulset-secondary-rs.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#10059 [stable/selenium] Fixing typos in readme and templates
  stable/selenium/Chart.yaml
  stable/selenium/README.md
  stable/selenium/templates/hub-deployment.yaml
  stable/selenium/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11379 [stable/atlantis] fix naming for secret ref
  stable/atlantis/Chart.yaml
  stable/atlantis/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11383 Add options for volumeMounts and volumes in the Metrics Server chart
  stable/metrics-server/Chart.yaml
  stable/metrics-server/README.md
  stable/metrics-server/templates/metrics-server-deployment.yaml
  stable/metrics-server/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11316 [stable:kube-state-metrics] update kube-state-metrics chart to support kube-state-metrics 1.5.0
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
  stable/kube-state-metrics/templates/clusterrole.yaml
  stable/kube-state-metrics/templates/deployment.yaml
  stable/kube-state-metrics/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11400 [stable/minio] Update minio version and bugfixes
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/templates/NOTES.txt
  stable/minio/templates/_helpers.tpl
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#11409 Upgrade k8s-sidecar
  stable/grafana/Chart.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11129 Separate ClusterRole rules in external-dns RBAC
  stable/external-dns/Chart.yaml
  stable/external-dns/templates/clusterrole.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11053 [newrelic-infra] Add cluster name custom attribute
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/templates/daemonset.yaml
  stable/newrelic-infrastructure/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11166 Updating Jenkins deployment fails appears rollingUpdate needs to be
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/jenkins-master-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11187 Option to expose the slave listener port as host port
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/jenkins-master-deployment.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11411 [stable/jenkins]: #10131
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/config.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11384 [stable/sonarqube] bump version to 7.6
  stable/sonarqube/Chart.yaml
  stable/sonarqube/README.md
  stable/sonarqube/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11413 [stable/jenkins] fix 11412 jenkins sidecars
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/jenkins-master-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#11398 Update Ambassador default replicas and fix README Markdown
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#11366 traefik: bump 1.7.7 → 1.7.9
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/deployment.yaml
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11424 Add another OWNER to Ambassador
  stable/ambassador/Chart.yaml
  stable/ambassador/OWNERS
Labels: Contribution Allowed, approved, lgtm, size/XS

#11428 [airflow] allow multiple existing secrets to be used
  stable/airflow/Chart.yaml
  stable/airflow/templates/_helpers.tpl
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#11397 Revert API_HOST endpoint variable from gate to deck service setting
  stable/spinnaker/Chart.yaml
  stable/spinnaker/templates/configmap/service-settings.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#8054 Vault: Adding ability to open cluster ip in k8s service
  incubator/vault/Chart.yaml
  incubator/vault/README.md
  incubator/vault/templates/deployment.yaml
  incubator/vault/templates/service.yaml
  incubator/vault/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11433 [stable/satisfy] gettting docker image with fixes
  stable/satisfy/Chart.yaml
  stable/satisfy/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11408 Add beat-exporter Prometheus metrics
  stable/filebeat/Chart.yaml
  stable/filebeat/templates/daemonset.yaml
  stable/filebeat/templates/service.yaml
  stable/filebeat/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#11406 [stable/postgresql] Fix wrong securityContext configuration for containers
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#11355 Workaround k8s exec probe timeoutSeconds
  stable/redis/Chart.yaml
  stable/redis/templates/_helpers.tpl
  stable/redis/templates/health-configmap.yaml
  stable/redis/templates/redis-master-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11443 [stable/prometheus-operator] Add vsliouniaev to approvers, reviewers
  stable/prometheus-operator/.helmignore
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11440 [stable/kube-state-metrics] update kube-state-metrics README.md
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#7857 [stable/superset] Use the target port number instead of a name
  stable/superset/Chart.yaml
  stable/superset/templates/svc.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#10982 [master] Fixed broken markdown table;
  stable/selenium/Chart.yaml
  stable/selenium/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11361 Added values to chose init container, additional label for Ingress and deleteDefaultPlugins option.
  stable/sonarqube/Chart.yaml
  stable/sonarqube/README.md
  stable/sonarqube/templates/copy-plugins.yaml
  stable/sonarqube/templates/deployment.yaml
  stable/sonarqube/templates/ingress.yaml
  stable/sonarqube/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#11073 [stable/metabase] Correct env var for jvm options
  stable/metabase/Chart.yaml
  stable/metabase/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#9859 [helm/charts] [stakater/reloader] Add reloader to helm public charts repo
  stable/reloader/.helmignore
  stable/reloader/Chart.yaml
  stable/reloader/OWNERS
  stable/reloader/README.md
  stable/reloader/templates/NOTES.txt
  stable/reloader/templates/_helpers.tpl
  stable/reloader/templates/clusterrole.yaml
  stable/reloader/templates/clusterrolebinding.yaml
  stable/reloader/templates/deployment.yaml
  stable/reloader/templates/role.yaml
  stable/reloader/templates/rolebinding.yaml
  stable/reloader/templates/serviceaccount.yaml
  stable/reloader/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#11378 [stable/redis-ha] Fix typo in redis-ha-statefulset
  stable/redis-ha/Chart.yaml
  stable/redis-ha/templates/redis-ha-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11301 [stable/kong] Integrated optional support for hostPort on admin, proxy and tls.
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#11326 [stable/prometheus-operator] allow to configure operator log level
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/prometheus-operator/deployment.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#11452 [stable/reloader] bump reloader to 0.0.25
  stable/reloader/Chart.yaml
  stable/reloader/README.md
  stable/reloader/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#10940 [stable/aws-iam-authenticator] Add new chart
  stable/aws-iam-authenticator/.helmignore
  stable/aws-iam-authenticator/Chart.yaml
  stable/aws-iam-authenticator/README.md
  stable/aws-iam-authenticator/templates/_helpers.tpl
  stable/aws-iam-authenticator/templates/configmap.yaml
  stable/aws-iam-authenticator/templates/daemonset.yaml
  stable/aws-iam-authenticator/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#10980 Add namespace value nginx ingress
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-servicemonitor.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#11032 [stable/lamp] Make php-fpm configurable
  stable/lamp/Chart.yaml
  stable/lamp/README.md
  stable/lamp/templates/configmap-php.yaml
  stable/lamp/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#11437 Add note to Spinnaker doc about destination path for additionalConfigMaps
  stable/spinnaker/Chart.yaml
  stable/spinnaker/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS
