Repository helm/charts, pull requests merged in 2019-10, with the labels that each got.

#17571 [stable/coredns] Version bump to 1.6.4
  stable/coredns/Chart.yaml
  stable/coredns/README.md
  stable/coredns/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#17572 [stable/gocd] Bump up k8s plugin version to 3.2
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#17568 Remove in Metric deployment double quote for args
  stable/metrics-server/Chart.yaml
  stable/metrics-server/templates/metrics-server-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#17558 [stable/airflow] fix typo in environment variable name
  stable/airflow/Chart.yaml
  stable/airflow/templates/configmap-env.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#17486 [stable/redis-ha] Add support for kubernetes priorityClassName
  stable/redis-ha/Chart.yaml
  stable/redis-ha/README.md
  stable/redis-ha/templates/redis-ha-statefulset.yaml
  stable/redis-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17557 [stable/sealed-secrets] Have optional command args passed to controller
  stable/sealed-secrets/Chart.yaml
  stable/sealed-secrets/README.md
  stable/sealed-secrets/templates/deployment.yaml
  stable/sealed-secrets/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17401 [stable/kibana] Migrate APIs for Kibana 1.16
  stable/kibana/Chart.yaml
  stable/kibana/templates/deployment.yaml
  stable/kibana/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#17114 fixed description: global.postgresql.postgresqlPassword
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17455 [stable/datadog] Add labels + deprecation notice
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/ci/cluster-agent-and-worker-values.yaml
  stable/datadog/ci/default-values.yaml
  stable/datadog/templates/NOTES.txt
  stable/datadog/templates/agent-apiservice.yaml
  stable/datadog/templates/agent-clusterchecks-deployment.yaml
  stable/datadog/templates/agent-clusterchecks-rbac.yaml
  stable/datadog/templates/agent-rbac.yaml
  stable/datadog/templates/agent-secret.yaml
  stable/datadog/templates/agent-services.yaml
  stable/datadog/templates/checksd-configmap.yaml
  stable/datadog/templates/cluster-agent-confd-configmap.yaml
  stable/datadog/templates/cluster-agent-deployment.yaml
  stable/datadog/templates/confd-configmap.yaml
  stable/datadog/templates/daemonset.yaml
  stable/datadog/templates/datadog-yaml-configmap.yaml
  stable/datadog/templates/deployment.yaml
  stable/datadog/templates/hpa-rbac.yaml
  stable/datadog/templates/rbac.yaml
  stable/datadog/templates/secrets.yaml
  stable/datadog/templates/service.yaml
  stable/datadog/templates/system-probe-configmap.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#17567 [stable/cockroachdb]: Update version to v19.1.5
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/README.md
  stable/cockroachdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17569 [stable/cluster-autoscaler] Bump to 1.14.5 and update RBAC permissions
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/templates/clusterrole.yaml
  stable/cluster-autoscaler/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17182 [stable/kong] allow ot override TLS target port
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/templates/service-kong-proxy.yaml
  stable/kong/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17577 Update readme mysql chart
  stable/mysql/Chart.yaml
  stable/mysql/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17593 [stable/kube-state-metrics] Version bump to 1.8.0 / Add myself as maintainer
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/OWNERS
  stable/kube-state-metrics/README.md
  stable/kube-state-metrics/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#17517 [stable/aerospike] upgraded statefulset to apps/v1, needed for kubernetes 1.16
  stable/aerospike/Chart.yaml
  stable/aerospike/README.md
  stable/aerospike/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16099 [stable/airflow] Allow specifying nodePort for Web service
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/templates/service-web.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#17443 [stable/fluent-bit] Add ignore_older parameter support for tail input…
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/config.yaml
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17509 [stable/elasticsearch-curator] Added compatibility for K8s 1.16
  stable/elasticsearch-curator/Chart.yaml
  stable/elasticsearch-curator/templates/_helpers.tpl
  stable/elasticsearch-curator/templates/psp.yml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17579 [stable/ambassador] Added sidecarContainers parameter
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/templates/deployment.yaml
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17599 fix a typo
  stable/rocketchat/Chart.yaml
  stable/rocketchat/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17388 [stable/grafana] Corrected error in README.md dashboard/datasource examples
  stable/grafana/Chart.yaml
  stable/grafana/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17560 [stable/prometheus-blackbox-exporter] updated docker image to 0.15.1
  stable/prometheus-blackbox-exporter/Chart.yaml
  stable/prometheus-blackbox-exporter/README.md
  stable/prometheus-blackbox-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#17448 [incubator/vault] Custom backend
  incubator/vault/Chart.yaml
  incubator/vault/README.md
  incubator/vault/templates/backend-config.yaml
  incubator/vault/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17481 [incubator/solr] Added namespace to SOLR_HOST
  incubator/solr/Chart.yaml
  incubator/solr/README.md
  incubator/solr/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17607 [stable/rabbitmq] Added extra secrets support
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/secrets.yaml
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#17078 [stable/concourse] Concourse v5.6.0
  stable/concourse/Chart.yaml
  stable/concourse/README.md
  stable/concourse/templates/web-deployment.yaml
  stable/concourse/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#17615 [stable/prometheus-to-sd] Add tolerations support for prometheus-to-sd
  stable/prometheus-to-sd/Chart.yaml
  stable/prometheus-to-sd/README.md
  stable/prometheus-to-sd/templates/deployment.yaml
  stable/prometheus-to-sd/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17515 [incubator/solr] Use zookeeper headless service
  incubator/solr/Chart.yaml
  incubator/solr/templates/exporter-deployment.yaml
  incubator/solr/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17613 [stable/nginx-ingress] Make prometheus scrape interval configurable
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-servicemonitor.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17562 [stable/instana-agent] Add agent.host.repository for mounting host repository
  stable/instana-agent/Chart.yaml
  stable/instana-agent/README.md
  stable/instana-agent/templates/daemonset.yaml
  stable/instana-agent/templates/podsecuritypolicy.yaml
  stable/instana-agent/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#17620 [stable/ambassador] Update to Ambassador 0.82.0
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#17536 [stable/selenium] Fixes compatibility with 1.16
  stable/selenium/Chart.yaml
  stable/selenium/templates/_helpers.tpl
  stable/selenium/templates/chrome-deployment.yaml
  stable/selenium/templates/chromeDebug-deployment.yaml
  stable/selenium/templates/firefox-deployment.yaml
  stable/selenium/templates/firefoxDebug-deployment.yaml
  stable/selenium/templates/hub-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#17623 [stable/spinnaker] Support custom local BOM for Halyard deployment.
  stable/spinnaker/Chart.yaml
  stable/spinnaker/README.md
  stable/spinnaker/templates/configmap/bom.yaml
  stable/spinnaker/templates/configmap/halyard-config.yaml
  stable/spinnaker/templates/configmap/halyard-init-script.yaml
  stable/spinnaker/templates/hooks/install-using-hal.yaml
  stable/spinnaker/templates/statefulsets/halyard.yaml
  stable/spinnaker/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#17625 [incubator/sparkoperator] Upgraded to use the latest patch release
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/README.md
  incubator/sparkoperator/templates/crds.yaml
  incubator/sparkoperator/templates/spark-operator-rbac.yaml
  incubator/sparkoperator/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#17614 [stable/grafana] add pod labels as configuration option
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/deployment.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17528 [stable/redis-ha] Fixes compatibility with 1.16
  stable/redis-ha/Chart.yaml
  stable/redis-ha/templates/redis-haproxy-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17441 [stable/cluster-autoscaler]add extraEnv in default values.yaml
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17627 [stable/memcached] Kubernetes 1.16 compatibility
  stable/memcached/Chart.yaml
  stable/memcached/README.md
  stable/memcached/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#17598 fix a typo
  stable/weave-cloud/Chart.yaml
  stable/weave-cloud/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17490 [stable/external-dns] Kubefed support and compatibility, allow external crd resources
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/clusterrole.yaml
  stable/external-dns/templates/deployment.yaml
  stable/external-dns/values-production.yaml
  stable/external-dns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#15746 [stable/gangway] Gangway extra volumes and volumeMounts, document SSL/TLS w/ examples
  stable/gangway/Chart.yaml
  stable/gangway/README.md
  stable/gangway/templates/deployment.yaml
  stable/gangway/templates/service.yaml
  stable/gangway/templates/ssl.yaml
  stable/gangway/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#17640 [stable/prometheus-redis-exporter] Update api versions to support k8s 1.16
  stable/prometheus-redis-exporter/Chart.yaml
  stable/prometheus-redis-exporter/README.md
  stable/prometheus-redis-exporter/templates/deployment.yaml
  stable/prometheus-redis-exporter/templates/podsecuritypolicy.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17597 [stable/rabbitmq-ha] Updating StatefulSet apiVersion for kubernetes 1.16
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/templates/role.yaml
  stable/rabbitmq-ha/templates/rolebinding.yaml
  stable/rabbitmq-ha/templates/service-discovery.yaml
  stable/rabbitmq-ha/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16579 [stable/prometheus-cloudwatch-exporter] added changelog
  stable/prometheus-cloudwatch-exporter/CHANGELOG.md
  stable/prometheus-cloudwatch-exporter/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#17678 [stable/openvpn] Kubernetes 1.16 compatibility
  stable/openvpn/Chart.yaml
  stable/openvpn/templates/certs-pvc.yaml
  stable/openvpn/templates/openvpn-deployment.yaml
  stable/openvpn/templates/openvpn-service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17454 [stable/docker-registry] modify deployment's apiVersion to apps/v1 #17449
  stable/docker-registry/Chart.yaml
  stable/docker-registry/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17645 [stable/filebeat] Update api versions to support k8s 1.16
  stable/filebeat/Chart.yaml
  stable/filebeat/README.md
  stable/filebeat/templates/daemonset.yaml
  stable/filebeat/templates/podsecuritypolicy.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17290 [stable/logstash] Allow templating in elasticsearch host
  stable/logstash/Chart.yaml
  stable/logstash/README.md
  stable/logstash/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17649 [stable/logstash] Update api versions to support k8s 1.16
  stable/logstash/Chart.yaml
  stable/logstash/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17688 [stable/memcached] Update 3.x upgrade docs for StatefulSet installs
  stable/memcached/Chart.yaml
  stable/memcached/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17674 [stable/rabbitmq] Update broken link to NGINX Ingress Annotations docs
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17638 [stable/wordpress] Fix link in README.md
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
  stable/wordpress/values-production.yaml
  stable/wordpress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17660 [stable/joomla] Update broken link to NGINX Ingress Annotations docs
  stable/joomla/Chart.yaml
  stable/joomla/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17662 [stable/mongodb] Update broken link to NGINX Ingress Annotations docs
  stable/mongodb/Chart.yaml
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17663 [stable/moodle] Update broken link to NGINX Ingress Annotations docs
  stable/moodle/Chart.yaml
  stable/moodle/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17664 [stable/nats] Update broken link to NGINX Ingress Annotations docs
  stable/nats/Chart.yaml
  stable/nats/values-production.yaml
  stable/nats/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17665 [stable/odoo] Update broken link to NGINX Ingress Annotations docs
  stable/odoo/Chart.yaml
  stable/odoo/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17666 [stable/opencart] Update broken link to NGINX Ingress Annotations docs
  stable/opencart/Chart.yaml
  stable/opencart/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17667 [stable/orangehrm] Update broken link to NGINX Ingress Annotations docs
  stable/orangehrm/Chart.yaml
  stable/orangehrm/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17668 [stable/osclass] Update broken link to NGINX Ingress Annotations docs
  stable/osclass/Chart.yaml
  stable/osclass/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17670 [stable/parse] Update broken link to NGINX Ingress Annotations docs
  stable/parse/Chart.yaml
  stable/parse/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17671 [stable/phabricator] Update broken link to NGINX Ingress Annotations docs
  stable/phabricator/Chart.yaml
  stable/phabricator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17672 [stable/phpbb] Update broken link to NGINX Ingress Annotations docs
  stable/phpbb/Chart.yaml
  stable/phpbb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17673 [stable/prestashop] Update broken link to NGINX Ingress Annotations docs
  stable/prestashop/Chart.yaml
  stable/prestashop/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17675 [stable/redmine] Update broken link to NGINX Ingress Annotations docs
  stable/redmine/Chart.yaml
  stable/redmine/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17676 [stable/suitecrm] Update broken link to NGINX Ingress Annotations docs
  stable/suitecrm/Chart.yaml
  stable/suitecrm/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17677 [stable/testlink] Update broken link to NGINX Ingress Annotations docs
  stable/testlink/Chart.yaml
  stable/testlink/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17642 [stable/mysql] Update api versions to support k8s 1.16
  stable/mysql/Chart.yaml
  stable/mysql/README.md
  stable/mysql/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17661 [stable/mediawiki] Update broken link to NGINX Ingress Annotations docs
  stable/mediawiki/Chart.yaml
  stable/mediawiki/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17690 [newrelic-infra] Updated the image version to 1.9.5
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/README.md
  stable/newrelic-infrastructure/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#17692 [stable/postgresql] Add upgrading instructions to the README.md
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16829 [stable/external-dns] Add support for creating Azure secret
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/_helpers.tpl
  stable/external-dns/templates/deployment.yaml
  stable/external-dns/templates/secret.yaml
  stable/external-dns/values-production.yaml
  stable/external-dns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#17277 incubator/azuremonitor-containers - (set image repo corresponding cloud and doc updates)
  incubator/azuremonitor-containers/Chart.yaml
  incubator/azuremonitor-containers/README.md
  incubator/azuremonitor-containers/templates/NOTES.txt
  incubator/azuremonitor-containers/templates/omsagent-daemonset.yaml
  incubator/azuremonitor-containers/templates/omsagent-deployment.yaml
  incubator/azuremonitor-containers/templates/omsagent-rs-configmap.yaml
  incubator/azuremonitor-containers/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#17695 [stable/grafana] add namespace metadata for tests
  stable/grafana/Chart.yaml
  stable/grafana/templates/tests/test-configmap.yaml
  stable/grafana/templates/tests/test-podsecuritypolicy.yaml
  stable/grafana/templates/tests/test-role.yaml
  stable/grafana/templates/tests/test-rolebinding.yaml
  stable/grafana/templates/tests/test-serviceaccount.yaml
  stable/grafana/templates/tests/test.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17602 [stable/redis-ha] Fix missing priorityClassName definition for haproxy
  stable/redis-ha/Chart.yaml
  stable/redis-ha/templates/redis-haproxy-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17596 [stable/spinnaker] Correct kubeConfig value casing typo
  stable/spinnaker/Chart.yaml
  stable/spinnaker/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17710 [incubator/jaeger] Update image
  incubator/jaeger/Chart.yaml
  incubator/jaeger/README.md
  incubator/jaeger/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#16668 [stable/kiam] Add pre-deprecation notice
  stable/kiam/Chart.yaml
  stable/kiam/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17698 [incubator/vault] Update readme for missed nodeSelector and tolerations
  incubator/vault/Chart.yaml
  incubator/vault/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17403 [stable/openebs] Updated ndm daemonset api version
  stable/openebs/Chart.yaml
  stable/openebs/templates/daemonset-ndm.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17529 [stable/minio] feat: fix invalid yaml generation for podAnnotations
  stable/minio/Chart.yaml
  stable/minio/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17709 [incubator/kafka] Add priorityClassName
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
  incubator/kafka/templates/statefulset.yaml
  incubator/kafka/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17520 [stable/tensorflow-notebook] Fixes compatibility with 1.16
  stable/tensorflow-notebook/Chart.yaml
  stable/tensorflow-notebook/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17521 [stable/tensorflow-serving] Fixes compatibility with 1.16
  stable/tensorflow-serving/Chart.yaml
  stable/tensorflow-serving/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17387 [stable/prometheus-operator] Only use job alpha feature if available
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
  stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17417 [stable/prometheus-operator] Sync prometheus rules to fix KubeVersionMismatch false positive on GKE < 1.14
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/node-exporter.yaml
  stable/prometheus-operator/templates/prometheus/rules/kubernetes-system.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#17543 [stable/prometheus-operator] Allow config-reloader containers resources to be unset
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/prometheus-operator/deployment.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17705 [stable/gocd] Add information about adding plugins
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17497 [stable/kong] Kong prometheus servicemonitor label
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/templates/servicemonitor.yaml
  stable/kong/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17626 [incubator/vault] Change vault api address to use http instead of https
  incubator/vault/Chart.yaml
  incubator/vault/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15383 [stable/prometheus] add the option to add alert_relabel_configs in prometheus.yml
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/server-configmap.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15928 [stable/prometheus-operator] PodEndpoint support
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/templates/prometheus/podmonitors.yaml
  stable/prometheus-operator/templates/prometheus/prometheus.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#17694 [stable/prometheus-postgres-exporter] Fix compatibility with k8s 1.16
  stable/prometheus-postgres-exporter/Chart.yaml
  stable/prometheus-postgres-exporter/templates/deployment.yaml
  stable/prometheus-postgres-exporter/templates/podsecuritypolicy.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17145 [incubator/honeydipper] release 0.1.3 enabling annotations on service
  incubator/honeydipper/Chart.yaml
  incubator/honeydipper/README.md
  incubator/honeydipper/templates/daemon-deployment.yaml
  incubator/honeydipper/templates/webhook-ingress.yaml
  incubator/honeydipper/templates/webhook-service.yaml
  incubator/honeydipper/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#17464 [stable/prometheus-operator] Update grafana to 3.8.15
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/requirements.lock
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17728 [stable/pomerium] Fix extraneous newline in configuration
  stable/pomerium/Chart.yaml
  stable/pomerium/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#17287 [stable/mongodb] Feature: explicit service name
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/templates/NOTES.txt
  stable/mongodb/templates/_helpers.tpl
  stable/mongodb/templates/ingress.yaml
  stable/mongodb/templates/svc-headless-rs.yaml
  stable/mongodb/templates/svc-primary-rs.yaml
  stable/mongodb/templates/svc-standalone.yaml
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#17659 [stable/jasperreports] Update broken link to NGINX Ingress Annotations docs
  stable/jasperreports/Chart.yaml
  stable/jasperreports/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17729 [stable/mariadb] added configuration support for metrics container probes
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
  stable/mariadb/templates/master-statefulset.yaml
  stable/mariadb/templates/slave-statefulset.yaml
  stable/mariadb/values-production.yaml
  stable/mariadb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#17559 [stable/redis-ha] Wait for service announce to be ready before popula…
  stable/redis-ha/Chart.yaml
  stable/redis-ha/README.md
  stable/redis-ha/templates/_configs.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17699 [stable/node-red] bumping docker image to latest official v1.0.1 version
  stable/node-red/Chart.yaml
  stable/node-red/README.md
  stable/node-red/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17657 [stable/drupal] Update broken link to NGINX Ingress Annotations docs
  stable/drupal/Chart.yaml
  stable/drupal/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17658 [stable/ghost] Update broken link to NGINX Ingress Annotations docs
  stable/ghost/Chart.yaml
  stable/ghost/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17669 [stable/owncloud] Update broken link to NGINX Ingress Annotations docs
  stable/owncloud/Chart.yaml
  stable/owncloud/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17656 [stable/dokuwiki] Update broken link to NGINX Ingress Annotations docs
  stable/dokuwiki/Chart.yaml
  stable/dokuwiki/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#15620 [stable/rabbitmq] Fix healthchecks for non-bitnami images
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/templates/healthchecks.yaml
  stable/rabbitmq/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#17643 [stable/elasticsearch] Update api versions to support k8s 1.16
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/README.md
  stable/elasticsearch/templates/client-deployment.yaml
  stable/elasticsearch/templates/data-statefulset.yaml
  stable/elasticsearch/templates/master-statefulset.yaml
  stable/elasticsearch/templates/podsecuritypolicy.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17700 [stable/home-assistant] bumping docker image to 0.99.3 and vscode server version
  stable/home-assistant/Chart.yaml
  stable/home-assistant/README.md
  stable/home-assistant/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#16945 [stable/efs-provisioner]Call for maintainers for charts with a single OWNER
  stable/efs-provisioner/Chart.yaml
  stable/efs-provisioner/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17610 [stable/prometheus-operator] Add annotate AlertManager Secret
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/templates/alertmanager/secret.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17621 [stable/efs-provisioner] Update apiVersions for Kubernetes 1.16
  stable/efs-provisioner/Chart.yaml
  stable/efs-provisioner/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17753 [stable/metrics-server] Fixes compatibility with 1.16
  stable/metrics-server/Chart.yaml
  stable/metrics-server/templates/psp.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#17080 [stable/datadog] Configure DD_APM_NON_LOCAL_TRAFFIC
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/container-agent.yaml
  stable/datadog/templates/container-agents.yaml
  stable/datadog/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17749 [stable/nginx-ingress] fix HPA to target correct Deployment version
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/templates/controller-hpa.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16632 [stable/graylog] Support graylog.ingress.extraPaths
  stable/graylog/Chart.yaml
  stable/graylog/README.md
  stable/graylog/templates/ingress.yaml
  stable/graylog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17726 [stable/graylog] Bump graylog image version, 3.1.2-1
  stable/graylog/Chart.yaml
  stable/graylog/README.md
  stable/graylog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17747 [stable/grafana] Add headless service for statefulset
  stable/grafana/Chart.yaml
  stable/grafana/templates/headless-service.yaml
  stable/grafana/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17758 [stable/wordpress] fix for issue #17727
  stable/wordpress/Chart.yaml
  stable/wordpress/templates/_helpers.tpl
  stable/wordpress/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17502 [stable/mongodb] fix failing liveness probe during long running mongodb recovery
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/statefulset-primary-rs.yaml
  stable/mongodb/templates/statefulset-secondary-rs.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17755 [stable/node-red] adding pod annotations to node-red chart
  stable/node-red/Chart.yaml
  stable/node-red/README.md
  stable/node-red/templates/deployment.yaml
  stable/node-red/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#17759 [stable/ambassador] Add PodDisruptionBudget
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/templates/NOTES.txt
  stable/ambassador/templates/pdb.yaml
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17382 [stable/prometheus-operator] Add support for creating a Service and Ingress for each Prometheus replica
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/templates/prometheus/ingressperreplica.yaml
  stable/prometheus-operator/templates/prometheus/serviceperreplica.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#17774 [stable/prometheus-operator] Update grafana to latest version
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/requirements.lock
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17770 [stable/goldpinger] add extraEnv
  stable/goldpinger/Chart.yaml
  stable/goldpinger/README.md
  stable/goldpinger/templates/daemonset.yaml
  stable/goldpinger/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#17776 [stable/rocketchat] Added new vars to values.yaml and changed templates/deployment.yaml f…
  stable/rocketchat/Chart.yaml
  stable/rocketchat/README.md
  stable/rocketchat/templates/deployment.yaml
  stable/rocketchat/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17754 [stable/sentry] Update environment variables mapping in configmap
  stable/sentry/Chart.yaml
  stable/sentry/README.md
  stable/sentry/templates/configmap.yaml
  stable/sentry/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#17781 [stable/nginx-ingress] respect build numbers usage in nginx-ingress versioning (#17775)
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/templates/_helpers.tpl
  stable/nginx-ingress/templates/addheaders-configmap.yaml
  stable/nginx-ingress/templates/admission-webhooks/job-patch/clusterrole.yaml
  stable/nginx-ingress/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
  stable/nginx-ingress/templates/admission-webhooks/job-patch/job-createSecret.yaml
  stable/nginx-ingress/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
  stable/nginx-ingress/templates/admission-webhooks/job-patch/psp.yaml
  stable/nginx-ingress/templates/admission-webhooks/job-patch/role.yaml
  stable/nginx-ingress/templates/admission-webhooks/job-patch/rolebinding.yaml
  stable/nginx-ingress/templates/admission-webhooks/job-patch/serviceaccount.yaml
  stable/nginx-ingress/templates/admission-webhooks/validating-webhook.yaml
  stable/nginx-ingress/templates/clusterrole.yaml
  stable/nginx-ingress/templates/clusterrolebinding.yaml
  stable/nginx-ingress/templates/controller-configmap.yaml
  stable/nginx-ingress/templates/controller-daemonset.yaml
  stable/nginx-ingress/templates/controller-deployment.yaml
  stable/nginx-ingress/templates/controller-hpa.yaml
  stable/nginx-ingress/templates/controller-metrics-service.yaml
  stable/nginx-ingress/templates/controller-poddisruptionbudget.yaml
  stable/nginx-ingress/templates/controller-prometheusrules.yaml
  stable/nginx-ingress/templates/controller-psp.yaml
  stable/nginx-ingress/templates/controller-role.yaml
  stable/nginx-ingress/templates/controller-rolebinding.yaml
  stable/nginx-ingress/templates/controller-service.yaml
  stable/nginx-ingress/templates/controller-serviceaccount.yaml
  stable/nginx-ingress/templates/controller-servicemonitor.yaml
  stable/nginx-ingress/templates/controller-webhook-service.yaml
  stable/nginx-ingress/templates/default-backend-deployment.yaml
  stable/nginx-ingress/templates/default-backend-poddisruptionbudget.yaml
  stable/nginx-ingress/templates/default-backend-psp.yaml
  stable/nginx-ingress/templates/default-backend-role.yaml
  stable/nginx-ingress/templates/default-backend-rolebinding.yaml
  stable/nginx-ingress/templates/default-backend-service.yaml
  stable/nginx-ingress/templates/default-backend-serviceaccount.yaml
  stable/nginx-ingress/templates/proxyheaders-configmap.yaml
  stable/nginx-ingress/templates/tcp-configmap.yaml
  stable/nginx-ingress/templates/udp-configmap.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#17756 [stable/minecraft] adding pod annotations to the minecraft chart
  stable/minecraft/Chart.yaml
  stable/minecraft/templates/deployment.yaml
  stable/minecraft/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#15861 [stable/datadog] Allow custom agent configuration
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/daemonset.yaml
  stable/datadog/templates/datadog-yaml-configmap.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#17799 [stable/ambassador] Update to Ambassador 0.83.0.
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#17757 [stable/grafana] Add variable to disable creating test resources
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/tests/test-configmap.yaml
  stable/grafana/templates/tests/test-podsecuritypolicy.yaml
  stable/grafana/templates/tests/test-role.yaml
  stable/grafana/templates/tests/test-rolebinding.yaml
  stable/grafana/templates/tests/test-serviceaccount.yaml
  stable/grafana/templates/tests/test.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17686 [stable/influxdb] Add Pod Annotations to Deployment
  stable/influxdb/Chart.yaml
  stable/influxdb/templates/deployment.yaml
  stable/influxdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17778 [stable/pomerium] Pomerium v0.4.0 Release
  stable/pomerium/Chart.yaml
  stable/pomerium/README.md
  stable/pomerium/templates/authenticate-deployment.yaml
  stable/pomerium/templates/authorize-deployment.yaml
  stable/pomerium/templates/proxy-deployment.yaml
  stable/pomerium/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#17576 [stable/external-dns] Add support for use Cloudflare API token
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/deployment.yaml
  stable/external-dns/templates/secret.yaml
  stable/external-dns/values-production.yaml
  stable/external-dns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#17760 [stable/redis-ha] Add securityContext to HAProxy Deployment
  stable/redis-ha/Chart.yaml
  stable/redis-ha/README.md
  stable/redis-ha/templates/redis-haproxy-deployment.yaml
  stable/redis-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17706 [stable/redis] Add support for custom labels on redis services
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/templates/metrics-svc.yaml
  stable/redis/templates/redis-master-svc.yaml
  stable/redis/templates/redis-slave-svc.yaml
  stable/redis/templates/redis-with-sentinel-svc.yaml
  stable/redis/values-production.yaml
  stable/redis/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17819 [stable/grafana] Avoid data key with an empty value in templates/dash…
  stable/grafana/Chart.yaml
  stable/grafana/templates/dashboards-json-configmap.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#16593 [stable/oauth2-proxy] Breaking change: upgrade to v4.0.0
  stable/oauth2-proxy/Chart.yaml
  stable/oauth2-proxy/OWNERS
  stable/oauth2-proxy/README.md
  stable/oauth2-proxy/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17828 [stable/aerospike] add labels/annotations
  stable/aerospike/Chart.yaml
  stable/aerospike/README.md
  stable/aerospike/templates/statefulset.yaml
  stable/aerospike/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17818 [stable/prometheus-operator] Allow to add annotations to the serviceacount
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/prometheus/serviceaccount.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#17428 [stable/spinnaker] Add support for skipping k8s permissions check at startup
  stable/spinnaker/Chart.yaml
  stable/spinnaker/templates/_helpers.tpl
  stable/spinnaker/templates/configmap/halyard-config.yaml
  stable/spinnaker/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#17116 [stable/sonarqube] Update default service type to ClusterIP
  stable/sonarqube/Chart.yaml
  stable/sonarqube/README.md
  stable/sonarqube/templates/deployment.yaml
  stable/sonarqube/templates/service.yaml
  stable/sonarqube/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#17801 [stable/ambassador] Update to Ambassador Pro 0.9.0
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/templates/ambassador-pro-auth.yaml
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17798 [stable/instana-agent] Update apiVersions for DaemonSet, PodSecurityPolicy
  stable/instana-agent/Chart.yaml
  stable/instana-agent/templates/clusterrole.yaml
  stable/instana-agent/templates/daemonset.yaml
  stable/instana-agent/templates/podsecuritypolicy.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#17817 [stable/kube-state-metrics] Avoid spec.template.spec.containers.0.res…
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17641 [stable/sonarqube] Update api versions to support k8s 1.16
  stable/sonarqube/Chart.yaml
  stable/sonarqube/README.md
  stable/sonarqube/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17804 [stable/prometheus-operator] add 'scrapeTimeout' to node-exporter servicemonitor
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/templates/exporters/node-exporter/servicemonitor.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#16361 [stable/elasticsearch-exporter] Add support for PodSecurityPolicies, ServiceAccounts
  stable/elasticsearch-exporter/Chart.yaml
  stable/elasticsearch-exporter/README.md
  stable/elasticsearch-exporter/templates/deployment.yaml
  stable/elasticsearch-exporter/templates/podsecuritypolicies.yaml
  stable/elasticsearch-exporter/templates/role.yaml
  stable/elasticsearch-exporter/templates/rolebinding.yaml
  stable/elasticsearch-exporter/templates/serviceaccount.yaml
  stable/elasticsearch-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#17831 [stable/grafana] Update Grafana to 6.4.2
  stable/grafana/Chart.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17838 [stable/fluent-bit] Use apps/v1 api for DaemonSet if k8s > 1.9
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/templates/_helpers.tpl
  stable/fluent-bit/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S
