Repository helm/charts, pull requests merged in 2019-06, with the labels that each got.

#13569 [stable/chart] prometheus-operator: missing nodeAffinity field in values
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#13665 [stable/sentry] Support loadBalancerSourceRanges on Service template
  stable/sentry/Chart.yaml
  stable/sentry/README.md
  stable/sentry/templates/service.yaml
  stable/sentry/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14246 [stable/anchore-engine] Add ability to use existing service account for CloudSQL.
  stable/anchore-engine/Chart.yaml
  stable/anchore-engine/README.md
  stable/anchore-engine/templates/analyzer_deployment.yaml
  stable/anchore-engine/templates/api_deployment.yaml
  stable/anchore-engine/templates/catalog_deployment.yaml
  stable/anchore-engine/templates/enterprise_feeds_deployment.yaml
  stable/anchore-engine/templates/enterprise_ui_deployment.yaml
  stable/anchore-engine/templates/policy_engine_deployment.yaml
  stable/anchore-engine/templates/simplequeue_deployment.yaml
  stable/anchore-engine/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#14325 [stable/grafana] add namespace metadata
  stable/grafana/Chart.yaml
  stable/grafana/templates/configmap-dashboard-provider.yaml
  stable/grafana/templates/configmap.yaml
  stable/grafana/templates/dashboards-json-configmap.yaml
  stable/grafana/templates/deployment.yaml
  stable/grafana/templates/ingress.yaml
  stable/grafana/templates/podsecuritypolicy.yaml
  stable/grafana/templates/pvc.yaml
  stable/grafana/templates/role.yaml
  stable/grafana/templates/rolebinding.yaml
  stable/grafana/templates/secret.yaml
  stable/grafana/templates/service.yaml
  stable/grafana/templates/serviceaccount.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test

#14347 [stable/gce-ingress] allow key in secret to be overridden
  stable/gce-ingress/Chart.yaml
  stable/gce-ingress/README.md
  stable/gce-ingress/templates/deployment-controller.yaml
  stable/gce-ingress/templates/service.yaml
  stable/gce-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#14362 [stable/percona] updates to support alternate k8s scheduler
  stable/percona/Chart.yaml
  stable/percona/README.md
  stable/percona/templates/deployment.yaml
  stable/percona/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test

#14367 [stable/redis-ha] updates to support alternate k8s scheduler
  stable/redis-ha/Chart.yaml
  stable/redis-ha/README.md
  stable/redis-ha/templates/redis-ha-statefulset.yaml
  stable/redis-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test

#14357 [stable/grafana] updates to support alternate k8s scheduler
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/deployment.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14389 [stable/prometheus-adapter] conditionally register external metrics API (#13716)
  stable/prometheus-adapter/Chart.yaml
  stable/prometheus-adapter/ci/default-values.yaml
  stable/prometheus-adapter/ci/external-rules-values.yaml
  stable/prometheus-adapter/templates/external-metrics-apiservice.yaml
  stable/prometheus-adapter/templates/external-metrics-cluster-role.yaml
  stable/prometheus-adapter/templates/hpa-external-metrics-cluster-role-binding.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14378 [stable/velero] Make restic pod volume path configurable
  stable/velero/Chart.yaml
  stable/velero/README.md
  stable/velero/templates/restic-daemonset.yaml
  stable/velero/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14394 [stable/fluent-bit] Upgrade to v1.1.2 (SECURITY UPDATES)
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test

#14359 [stable/mongodb] updates to support alternate k8s scheduler
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/templates/deployment-standalone.yaml
  stable/mongodb/templates/statefulset-arbiter-rs.yaml
  stable/mongodb/templates/statefulset-primary-rs.yaml
  stable/mongodb/templates/statefulset-secondary-rs.yaml
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14379 [stable/velero] optionally deploy restic daemonset as privileged pods
  stable/velero/Chart.yaml
  stable/velero/README.md
  stable/velero/templates/restic-daemonset.yaml
  stable/velero/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14387 [stable/prometheus-operator] Update components,cleanup
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/requirements.lock
  stable/prometheus-operator/requirements.yaml
  stable/prometheus-operator/templates/prometheus/role-specificNamespace.yaml
  stable/prometheus-operator/templates/prometheus/rolebinding-specificNamespace.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#14395 [stabled/elasticsearch-exporter] add custom labels to the service and set service http port name
  stable/elasticsearch-exporter/Chart.yaml
  stable/elasticsearch-exporter/README.md
  stable/elasticsearch-exporter/templates/service.yaml
  stable/elasticsearch-exporter/templates/servicemonitor.yaml
  stable/elasticsearch-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#14392 [stable/seq] Version change to GA and add baseURI setting
  stable/seq/Chart.yaml
  stable/seq/README.md
  stable/seq/templates/deployment.yaml
  stable/seq/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14374 [stable/sysdig] New Agent upstream release 0.90.2
  stable/sysdig/CHANGELOG.md
  stable/sysdig/Chart.yaml
  stable/sysdig/README.md
  stable/sysdig/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#14402 [stable/node-red] Update version node-red to 0.20.5
  stable/node-red/Chart.yaml
  stable/node-red/README.md
  stable/node-red/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#14401 [stable/postgresql] Ensure intContainer creates the data directory.
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#14410 [stable/home-assistant] remove probes from optional configuration containers
  stable/home-assistant/Chart.yaml
  stable/home-assistant/templates/deployment.yaml
  stable/home-assistant/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#13992 [stable/airflow] Fix unknown field scheduler
  stable/airflow/Chart.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#14380 [stable/atlantis] Adding options for labels, disable test, fix items to README.md
  stable/atlantis/Chart.yaml
  stable/atlantis/README.md
  stable/atlantis/templates/ingress.yaml
  stable/atlantis/templates/statefulset.yaml
  stable/atlantis/templates/tests/test-atlantis-configmap.yaml
  stable/atlantis/templates/tests/test-atlantis-pod.yaml
  stable/atlantis/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#14370 [stable/postgresql] Improve readiness probe
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#14350 [incubator/cassandra] updates to support an alternate k8s scheduler
  incubator/cassandra/Chart.yaml
  incubator/cassandra/README.md
  incubator/cassandra/templates/statefulset.yaml
  incubator/cassandra/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14399 [stable/metricbeat] Fix 'secrets.yaml' to make `ExtraSecrets`work.
  stable/metricbeat/Chart.yaml
  stable/metricbeat/templates/secret.yaml
  stable/metricbeat/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14358 [stable/mariadb] updates to support alternate k8s scheduler
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
  stable/mariadb/templates/master-statefulset.yaml
  stable/mariadb/templates/slave-statefulset.yaml
  stable/mariadb/values-production.yaml
  stable/mariadb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14369 [stable/postgresql] servicemonitor resource for prometheus operator
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/servicemonitor.yaml
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#14166 [stable/logstash]: add podManagementPolicy in statefulset
  stable/logstash/Chart.yaml
  stable/logstash/README.md
  stable/logstash/templates/statefulset.yaml
  stable/logstash/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14447 [stable/chart] Create configmap on helm upgrade too
  stable/mercure/Chart.yaml
  stable/mercure/templates/configmap.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#14438 [stable/fluentd] add Prometheus metrics
  stable/fluentd/Chart.yaml
  stable/fluentd/README.md
  stable/fluentd/templates/configmap.yaml
  stable/fluentd/templates/deployment.yaml
  stable/fluentd/templates/service.yaml
  stable/fluentd/templates/servicemonitor.yaml
  stable/fluentd/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#14108 [incubator/vault] Fix liveness & readiness probes
  incubator/vault/Chart.yaml
  incubator/vault/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14434 [stable/verdaccio] Update README.md
  stable/verdaccio/Chart.yaml
  stable/verdaccio/README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#14449 [stable/cockroachdb] bump chart to 19.1.1
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/README.md
  stable/cockroachdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#12723 [stable/prometheus-rabbitmq-exporter] Adding Prometheus Operator Service Monitor
  stable/prometheus-rabbitmq-exporter/Chart.yaml
  stable/prometheus-rabbitmq-exporter/README.md
  stable/prometheus-rabbitmq-exporter/templates/monitor.yaml
  stable/prometheus-rabbitmq-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#14067 stable/k8s-spot-termination-handler] no way to set verbose on the deamonset #14065
  stable/k8s-spot-termination-handler/Chart.yaml
  stable/k8s-spot-termination-handler/README.md
  stable/k8s-spot-termination-handler/templates/daemonset.yaml
  stable/k8s-spot-termination-handler/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#14457 [stable/wordpress] Add javsalgar to the list of OWNERS
  stable/wordpress/Chart.yaml
  stable/wordpress/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14459 [stable/suitecrm] Add javsalgar to the list of OWNERS
  stable/suitecrm/Chart.yaml
  stable/suitecrm/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14480 [stable/kubewatch] Add javsalgar to the list of OWNERS
  stable/kubewatch/Chart.yaml
  stable/kubewatch/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#12562 [incubator/vault] Add priorityClassName for pods and minReadySeconds for deployment
  incubator/vault/Chart.yaml
  incubator/vault/README.md
  incubator/vault/templates/deployment.yaml
  incubator/vault/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#12857 Added warning about configuration difference from MetalLB docs
  stable/metallb/Chart.yaml
  stable/metallb/README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#14109 [stable/helm-exporter] Add OWNERS to helmignore
  stable/helm-exporter/.helmignore
  stable/helm-exporter/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14226 [stable/external-dns] adding aws-batch-change-size parameter
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/deployment.yaml
  stable/external-dns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14458 [stable/testlink] Add javsalgar to the list of OWNERS
  stable/testlink/Chart.yaml
  stable/testlink/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test

#12415 add: pomerium identity-aware access proxy
  stable/pomerium/.helmignore
  stable/pomerium/Chart.yaml
  stable/pomerium/OWNERS
  stable/pomerium/README.md
  stable/pomerium/templates/NOTES.txt
  stable/pomerium/templates/_helpers.tpl
  stable/pomerium/templates/authenticate-deployment.yaml
  stable/pomerium/templates/authenticate-service.yaml
  stable/pomerium/templates/authorize-deployment.yaml
  stable/pomerium/templates/authorize-service.yaml
  stable/pomerium/templates/configmap.yaml
  stable/pomerium/templates/ingress.yaml
  stable/pomerium/templates/proxy-deployment.yaml
  stable/pomerium/templates/proxy-service.yaml
  stable/pomerium/templates/secret.yaml
  stable/pomerium/templates/tls-secrets.yaml
  stable/pomerium/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XXL

#13697 [stable/spring-cloud-data-flow] Added support for external databases and RabbitMQ-HA
  stable/spring-cloud-data-flow/Chart.yaml
  stable/spring-cloud-data-flow/README.md
  stable/spring-cloud-data-flow/requirements.lock
  stable/spring-cloud-data-flow/requirements.yaml
  stable/spring-cloud-data-flow/templates/NOTES.txt
  stable/spring-cloud-data-flow/templates/_helpers.tpl
  stable/spring-cloud-data-flow/templates/database-secret.yaml
  stable/spring-cloud-data-flow/templates/server-config.yaml
  stable/spring-cloud-data-flow/templates/server-deployment.yaml
  stable/spring-cloud-data-flow/templates/skipper-config.yaml
  stable/spring-cloud-data-flow/templates/skipper-deployment.yaml
  stable/spring-cloud-data-flow/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#14482 [stable/jasperreports] Add javsalgar to the list of OWNERS
  stable/jasperreports/Chart.yaml
  stable/jasperreports/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14484 [stable/drupal] Add javsalgar to the list of OWNERS
  stable/drupal/Chart.yaml
  stable/drupal/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14485 [stable/dokuwiki] Add javsalgar to the list of OWNERS
  stable/dokuwiki/Chart.yaml
  stable/dokuwiki/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14487 [stable/mysqldump] removed persistentVolumeClaimPolicy from volumeclaim
  stable/mysqldump/Chart.yaml
  stable/mysqldump/README.md
  stable/mysqldump/templates/pvc.yaml
  stable/mysqldump/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test

#14460 [stable/redmine] Add javsalgar to the list of OWNERS
  stable/redmine/Chart.yaml
  stable/redmine/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14462 [stable/rabbitmq] Add javsalgar to the list of OWNERS
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14463 [stable/prestashop] Add javsalgar to the list of OWNERS
  stable/prestashop/Chart.yaml
  stable/prestashop/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14464 [stable/postgresql] Add javsalgar to the list of OWNERS
  stable/postgresql/Chart.yaml
  stable/postgresql/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14465 [stable/phpmyadmin] Add javsalgar to the list of OWNERS
  stable/phpmyadmin/Chart.yaml
  stable/phpmyadmin/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14424 [stable/sonarqube] Configure ingress correctly if no path is set and ensure that default paths are configured correctly
  stable/sonarqube/Chart.yaml
  stable/sonarqube/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14437 [stable/sonatype-nexus] Fix ingress when proxy service is renamed
  stable/sonatype-nexus/Chart.yaml
  stable/sonatype-nexus/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14461 [stable/redis] Add javsalgar to the list of OWNERS
  stable/redis/Chart.yaml
  stable/redis/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14466 [stable/phpbb] Add javsalgar to the list of OWNERS
  stable/phpbb/Chart.yaml
  stable/phpbb/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14467 [stable/phabricator] Add javsalgar to the list of OWNERS
  stable/phabricator/Chart.yaml
  stable/phabricator/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14468 [stable/parse] Add javsalgar to the list of OWNERS
  stable/parse/Chart.yaml
  stable/parse/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14469 [stable/owncloud] Add javsalgar to the list of OWNERS
  stable/owncloud/Chart.yaml
  stable/owncloud/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14470 [stable/osclass] Add javsalgar to the list of OWNERS
  stable/osclass/Chart.yaml
  stable/osclass/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14471 [stable/orangehrm] Add javsalgar to the list of OWNERS
  stable/orangehrm/Chart.yaml
  stable/orangehrm/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14472 [stable/opencart] Add javsalgar to the list of OWNERS
  stable/opencart/Chart.yaml
  stable/opencart/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14473 [stable/odoo] Add javsalgar to the list of OWNERS
  stable/odoo/Chart.yaml
  stable/odoo/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14474 [stable/nats] Add javsalgar to the list of OWNERS
  stable/nats/Chart.yaml
  stable/nats/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14475 [stable/moodle] Add javsalgar to the list of OWNERS
  stable/moodle/Chart.yaml
  stable/moodle/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14476 [stable/mongodb] Add javsalgar to the list of OWNERS
  stable/mongodb/Chart.yaml
  stable/mongodb/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14477 [stable/mediawiki] Add javsalgar to the list of OWNERS
  stable/mediawiki/Chart.yaml
  stable/mediawiki/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14479 [stable/magento] Add javsalgar to the list of OWNERS
  stable/magento/Chart.yaml
  stable/magento/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14481 [stable/joomla] Add javsalgar to the list of OWNERS
  stable/joomla/Chart.yaml
  stable/joomla/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14422 [stable/kured] add support for priorityClassName
  stable/kured/Chart.yaml
  stable/kured/README.md
  stable/kured/templates/daemonset.yaml
  stable/kured/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14486 [stable/elasticsearchexporter] fix bug in template when adding labels
  stable/elasticsearch-exporter/Chart.yaml
  stable/elasticsearch-exporter/templates/service.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#14513 Adding priority class support 🔺
  stable/k8s-spot-rescheduler/Chart.yaml
  stable/k8s-spot-rescheduler/README.md
  stable/k8s-spot-rescheduler/templates/deployment.yaml
  stable/k8s-spot-rescheduler/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14499 [stable/jenkins] add example for EmptyDir volume
  stable/jenkins/Chart.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#14441 added missing $ to .Release.Namespace fix for #14412
  stable/grafana/Chart.yaml
  stable/grafana/templates/dashboards-json-configmap.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14138 [stable/rocketchat] Add Affinities, podAntiAffinity and PodDisruptionBudget
  stable/rocketchat/Chart.yaml
  stable/rocketchat/README.md
  stable/rocketchat/templates/deployment.yaml
  stable/rocketchat/templates/poddisruptionbudget.yaml
  stable/rocketchat/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#14517 [stable/prometheus-redis-exporter] Support image pullSecrets
  stable/prometheus-redis-exporter/Chart.yaml
  stable/prometheus-redis-exporter/README.md
  stable/prometheus-redis-exporter/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14483 [stable/ghost] Add javsalgar to the list of OWNERS
  stable/ghost/Chart.yaml
  stable/ghost/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14478 [stable/mariadb] Add javsalgar to the list of OWNERS
  stable/mariadb/Chart.yaml
  stable/mariadb/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14516 [stable/postgresql] Make readiness probe compatible for most postgresql images
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/_helpers.tpl
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14525 added me to prometheus-nats-exporter/OWNERS
  stable/prometheus-nats-exporter/Chart.yaml
  stable/prometheus-nats-exporter/OWNERS
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#14444 [stable/opa] Add sideEffects to webhook config
  stable/opa/Chart.yaml
  stable/opa/templates/webhookconfiguration.yaml
  stable/opa/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#13612 [stable/magento] use chart name instead of unexistant template definition
  stable/magento/Chart.yaml
  stable/magento/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14125 [stable/traefik] Add configurable logLevel
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/configmap.yaml
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#14518 [stable/opa] Added a namespace selector config to admission controller
  stable/opa/Chart.yaml
  stable/opa/README.md
  stable/opa/templates/webhookconfiguration.yaml
  stable/opa/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#14530 stable/prometheus-adapter: add me as new owner
  stable/prometheus-adapter/Chart.yaml
  stable/prometheus-adapter/OWNERS
Labels: Contribution Allowed, approved, lgtm, size/XS

#14532 [incubator/kafka] Adding zookeeper fullnameOverride
  incubator/kafka/Chart.yaml
  incubator/kafka/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test

#14523 [stable/kube-state-metrics] Add Kubernetes to keywords list
  stable/kube-state-metrics/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14165 [stable/kafka-manager] use service.port for addClusters.sh during bootstrap
  stable/kafka-manager/Chart.yaml
  stable/kafka-manager/templates/configmap.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14531 Revert upgrade hook
  stable/mercure/Chart.yaml
  stable/mercure/templates/configmap.yaml
  stable/mercure/templates/secret.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#14537 [stable/velero] Remove myself as maintainer
  stable/velero/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#14442 [stable/helm-exporter] Add support for using ingress
  stable/helm-exporter/Chart.yaml
  stable/helm-exporter/README.md
  stable/helm-exporter/templates/ingress.yaml
  stable/helm-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#14413 [stable/sonarqube] Allow use of custom cacerts
  stable/sonarqube/Chart.yaml
  stable/sonarqube/README.md
  stable/sonarqube/templates/deployment.yaml
  stable/sonarqube/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#14540 [stable/postgresql] Fix data permission error on pod restart (#14538)
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14443 [stable/mongodb] Add securityContext to MongoDB metrics sidecar container
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/deployment-standalone.yaml
  stable/mongodb/templates/statefulset-primary-rs.yaml
  stable/mongodb/templates/statefulset-secondary-rs.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14415 [stable/wordpress] Add update strategy
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
  stable/wordpress/templates/deployment.yaml
  stable/wordpress/values-production.yaml
  stable/wordpress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#14439 [stable/nats] Fix ValidationError: unknown field "serviceName"
  stable/nats/Chart.yaml
  stable/nats/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14491 [stable/rabbitmq] fix Error: enoent with forceBoot on new install (see #13485)
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14541 [stable/metrics-server] - Fix indentation for service labels.
  stable/metrics-server/Chart.yaml
  stable/metrics-server/templates/metric-server-service.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#14404 [stable/velero] Make Restic resource requests and limits configurable
  stable/velero/Chart.yaml
  stable/velero/README.md
  stable/velero/templates/restic-daemonset.yaml
  stable/velero/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14554 [stable/rabbitmq] Update image to new bash container
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/statefulset.yaml
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14520 Patch 1
  stable/karma/Chart.yaml
  stable/karma/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14539 [stable/elasticsearch] Rolling update statefulsets and deployment on configmap change
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/ci/updatestrategy-values.yaml
  stable/elasticsearch/templates/client-deployment.yaml
  stable/elasticsearch/templates/data-statefulset.yaml
  stable/elasticsearch/templates/master-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#14551 [stable/prometheus-operator] Kubelet relabelings.
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/templates/exporters/kubelet/servicemonitor.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#14510 [stable/postgresql] README.md - fix minor typos
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14508 [stable/prometheus-adapter] add new resourceRules in values
  stable/prometheus-adapter/Chart.yaml
  stable/prometheus-adapter/README.md
  stable/prometheus-adapter/templates/NOTES.txt
  stable/prometheus-adapter/templates/custom-metrics-configmap.yaml
  stable/prometheus-adapter/templates/resource-metrics-apiservice.yaml
  stable/prometheus-adapter/templates/resource-metrics-cluster-role-binding.yaml
  stable/prometheus-adapter/templates/resource-metrics-cluster-role.yaml
  stable/prometheus-adapter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#14569 [stable/sonarqube] Add support for multiple Loadbalancer Ranges
  stable/sonarqube/Chart.yaml
  stable/sonarqube/templates/service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14572 [stable/prometheus-operator] Support for `replicaExternalLabelName` and `prometheusExternalLabelName`
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/test-values.yaml
  stable/prometheus-operator/templates/prometheus/prometheus.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#14575 [stable/airflow] Add livenessPath config to airflow web deployment
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/templates/deployments-web.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#14355 [stable/sentry] Add metrics exporter
  stable/sentry/Chart.yaml
  stable/sentry/README.md
  stable/sentry/templates/configmap.yaml
  stable/sentry/templates/metrics-deployment.yaml
  stable/sentry/templates/metrics-prometheus.yaml
  stable/sentry/templates/metrics-service.yaml
  stable/sentry/templates/web-service.yaml
  stable/sentry/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#14583 [stable/sematext-agent] SC-4896 Rename Logsene to Logs
  stable/sematext-agent/Chart.yaml
  stable/sematext-agent/README.md
  stable/sematext-agent/templates/NOTES.txt
  stable/sematext-agent/templates/daemonset.yaml
  stable/sematext-agent/templates/secret.yaml
  stable/sematext-agent/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#14587 [stable/mongodb] Expose metrics port on 'primary' svc
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/headless-svc-rs.yaml
  stable/mongodb/templates/svc-primary-rs.yaml
  stable/mongodb/templates/svc-standalone.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14591 [stable/datadog]Remove `logs_collect_all` condition for mounting containers log directories
  stable/datadog/Chart.yaml
  stable/datadog/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14594 [stable/chart] Added CRDs for Resolvers
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/templates/crds.yaml
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#14550 [stable/elasticsearch] Move logging configuration to values.yaml
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/README.md
  stable/elasticsearch/templates/configmap.yaml
  stable/elasticsearch/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#14360 [stable/mssql-linux] updates to support alternate k8s scheduler
  stable/mssql-linux/Chart.yaml
  stable/mssql-linux/README.md
  stable/mssql-linux/templates/deployment.yaml
  stable/mssql-linux/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14414 [incubator/cassandra-k8s-operator] Add charts for the Orange's Cassandra Kubernetes operator
  incubator/cassandra-operator/Chart.yaml
  incubator/cassandra-operator/OWNERS
  incubator/cassandra-operator/readme.md
  incubator/cassandra-operator/templates/NOTES.txt
  incubator/cassandra-operator/templates/_functions.tpl
  incubator/cassandra-operator/templates/db_v1alpha1_cassandracluster_crd.yaml
  incubator/cassandra-operator/templates/deployment.yaml
  incubator/cassandra-operator/templates/role.yaml
  incubator/cassandra-operator/templates/rolebinding.yaml
  incubator/cassandra-operator/templates/service.yaml
  incubator/cassandra-operator/templates/service_account.yaml
  incubator/cassandra-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#14603 [stable/velero] Add VMware team as maintainers
  stable/velero/Chart.yaml
  stable/velero/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14604 [stable/ambassador] fix: update rbac so ambassador does not ask to see namespaces with namespaced rbac
  stable/ambassador/Chart.yaml
  stable/ambassador/templates/rbac.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#14452 [stable/openvpn] add certificate revocation list support
  stable/openvpn/Chart.yaml
  stable/openvpn/README.md
  stable/openvpn/templates/NOTES.txt
  stable/openvpn/templates/config-openvpn.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#14576 [stable/metrics-server] Fixing indentation issue.
  stable/metrics-server/Chart.yaml
  stable/metrics-server/templates/metric-server-service.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#14619 [stable/openvpn] allow setting up ta.key and overriding cipher.
  stable/openvpn/Chart.yaml
  stable/openvpn/README.md
  stable/openvpn/templates/config-openvpn.yaml
  stable/openvpn/templates/openvpn-deployment.yaml
  stable/openvpn/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#14611 [stable/prometheus-operator] Mark **An example template** explicitly as comment
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14534 [stable/prometheus-redis-exporter] Add servicemonitor support
  stable/prometheus-redis-exporter/Chart.yaml
  stable/prometheus-redis-exporter/README.md
  stable/prometheus-redis-exporter/templates/service.yaml
  stable/prometheus-redis-exporter/templates/servicemonitor.yaml
  stable/prometheus-redis-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#14558 [stable/grafana] Bump version
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#14528 [stable/prometheus-nats-exporter] upgrade to official image
  stable/prometheus-nats-exporter/Chart.yaml
  stable/prometheus-nats-exporter/README.md
  stable/prometheus-nats-exporter/templates/NOTES.txt
  stable/prometheus-nats-exporter/templates/deployment.yaml
  stable/prometheus-nats-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#14621 [stable/telegraf] telegraf updated from 1.9-alpine to 1.10-alpine
  stable/telegraf/Chart.yaml
  stable/telegraf/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14606 [stable/kong] fix link to Custom Resource Definitions in README.md
  stable/kong/Chart.yaml
  stable/kong/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14626 [stable/sentry] add checksum annotations
  stable/sentry/Chart.yaml
  stable/sentry/templates/cron-deployment.yaml
  stable/sentry/templates/web-deployment.yaml
  stable/sentry/templates/workers-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14555 [stable/magento] Deprecate Magento chart
  stable/magento/Chart.yaml
  stable/magento/README.md
  stable/magento/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#14618 [stable/nextcloud] Bump mariadb dep, add probes config to README
  stable/nextcloud/Chart.yaml
  stable/nextcloud/README.md
  stable/nextcloud/requirements.lock
  stable/nextcloud/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#14676 [stable/rocketchat] bump app version to 1.1.1
  stable/rocketchat/Chart.yaml
  stable/rocketchat/README.md
  stable/rocketchat/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#14663 [stable/cluster-autoscaler] Fixed indentation in deployment
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14675 [stable/metricbeat] Template dnsPolicy and hostNetwork
  stable/metricbeat/Chart.yaml
  stable/metricbeat/README.md
  stable/metricbeat/templates/daemonset.yaml
  stable/metricbeat/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14680 [stable/nextcloud] More consistent values and secrets
  stable/nextcloud/Chart.yaml
  stable/nextcloud/README.md
  stable/nextcloud/templates/deployment.yaml
  stable/nextcloud/templates/secrets.yaml
  stable/nextcloud/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#14666 [stable/redis] Unify and document production values
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/ci/production-sentinel-values.yaml
  stable/redis/ci/production-values.yaml
  stable/redis/values-production.yaml
  stable/redis/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#14667 [stable/rabbitmq] Unify and document production values
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#14664 [stable/postgresql] Allow templating of extra env vars
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14419 [stable/wordpress] Remove tls default values
  stable/wordpress/Chart.yaml
  stable/wordpress/values-production.yaml
  stable/wordpress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#14669 [stable/postgresql] Unify and document production values
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#14687 [stable/nats] Unify and document production values
  stable/nats/Chart.yaml
  stable/nats/README.md
  stable/nats/values-production.yaml
  stable/nats/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#14685 [incubator/fluentd-cloudwatch] fix documentation for the removed key `fluentdConfig`
  incubator/fluentd-cloudwatch/Chart.yaml
  incubator/fluentd-cloudwatch/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#14570 [stable/prometheus-adapter] Add priorityClassName
  stable/prometheus-adapter/Chart.yaml
  stable/prometheus-adapter/README.md
  stable/prometheus-adapter/templates/custom-metrics-apiserver-deployment.yaml
  stable/prometheus-adapter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#14599 [incubator/schema-registry] Add support for prometheus jmx exporter &…
  incubator/schema-registry/Chart.yaml
  incubator/schema-registry/README.md
  incubator/schema-registry/templates/deployment.yaml
  incubator/schema-registry/templates/jmx-configmap.yaml
  incubator/schema-registry/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#13190 [stable/oauth2-proxy] add undocumented ingress.{path,annotations,hosts,tls} to README
  stable/oauth2-proxy/Chart.yaml
  stable/oauth2-proxy/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14328 [stable/prometheus-snmp-exporter] add namespace metadata
  stable/prometheus-snmp-exporter/Chart.yaml
  stable/prometheus-snmp-exporter/templates/configmap.yaml
  stable/prometheus-snmp-exporter/templates/deployment.yaml
  stable/prometheus-snmp-exporter/templates/ingress.yaml
  stable/prometheus-snmp-exporter/templates/role.yaml
  stable/prometheus-snmp-exporter/templates/rolebinding.yaml
  stable/prometheus-snmp-exporter/templates/service.yaml
  stable/prometheus-snmp-exporter/templates/serviceaccount.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#14693 [stable/mariadb] Unify and document production values
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
  stable/mariadb/values-production.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#14665 [stable/wordpress] Unify and document production values
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
  stable/wordpress/values-production.yaml
  stable/wordpress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#14691 [stable/mongodb] Unify and document production values
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M
