Repository helm/charts, pull requests merged in 2019-12, with the labels that each got.

#19273 [stable/coredns] Update container image to 1.6.5
  stable/coredns/Chart.yaml
  stable/coredns/README.md
  stable/coredns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19195 [stable/fluentd] fix replica count conflict
  stable/fluentd/Chart.yaml
  stable/fluentd/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#17547 [stable/nfs-server-provisioner] Add compatibility with k8s 1.16
  stable/nfs-server-provisioner/Chart.yaml
  stable/nfs-server-provisioner/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19207 [incubator/cassandra-operator] Introduce crds directory for compatibi…
  incubator/cassandra-operator/Chart.yaml
  incubator/cassandra-operator/README.md
  incubator/cassandra-operator/crds/db_v1alpha1_cassandracluster_crd.yaml
  incubator/cassandra-operator/templates/crds.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18815 [stable/kube2iam] Add in imagePullSecrets configuration
  stable/kube2iam/Chart.yaml
  stable/kube2iam/README.md
  stable/kube2iam/templates/_helpers.tpl
  stable/kube2iam/templates/daemonset.yaml
  stable/kube2iam/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19269 [stable/home-assistant] Make deployment's probes customizable
  stable/home-assistant/Chart.yaml
  stable/home-assistant/README.md
  stable/home-assistant/templates/deployment.yaml
  stable/home-assistant/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18459 [stable/pgadmin] Add missing volumeMounts to deployment
  stable/pgadmin/Chart.yaml
  stable/pgadmin/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19274 [incubator/jaeger] Make TTL for cassandra data configurable
  incubator/jaeger/Chart.yaml
  incubator/jaeger/README.md
  incubator/jaeger/templates/cassandra-schema-job.yaml
  incubator/jaeger/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#19281 [stable/sealed-secrets] Upgrade to latest 0.9.6 release
  stable/sealed-secrets/Chart.yaml
  stable/sealed-secrets/README.md
  stable/sealed-secrets/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17188 [stable/filebeat] Add Filebeat config volume mount to init container
  stable/filebeat/Chart.yaml
  stable/filebeat/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18175 [stable/stolon] Add OWNERS file
  stable/stolon/Chart.yaml
  stable/stolon/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19277 [incubator/jaeger]Option to provide sampling strategies file
  incubator/jaeger/Chart.yaml
  incubator/jaeger/README.md
  incubator/jaeger/templates/collector-configmap.yaml
  incubator/jaeger/templates/collector-deploy.yaml
  incubator/jaeger/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#19203 [stable/cloudserver] fix replica count conflict
  stable/cloudserver/Chart.yaml
  stable/cloudserver/templates/api-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#19200 [stable/neo4j] fix replica count conflict
  stable/neo4j/Chart.yaml
  stable/neo4j/templates/readreplicas-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#19202 [stable/contour] fix replica count conflict
  stable/contour/Chart.yaml
  stable/contour/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#18632 [stable/eventrouter] Make eventrouter compatible with k8s >= 1.16
  stable/eventrouter/Chart.yaml
  stable/eventrouter/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18686 [stable/karma] Add deployment.annotations parameter
  stable/karma/Chart.yaml
  stable/karma/README.md
  stable/karma/templates/deployment.yaml
  stable/karma/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19084 [stable/consul] Adding path option to ingress
  stable/consul/Chart.yaml
  stable/consul/README.md
  stable/consul/templates/consul-ingress.yaml
  stable/consul/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19103 [stable/velero] Add logLevel and logFormat Velero
  stable/velero/Chart.yaml
  stable/velero/README.md
  stable/velero/templates/deployment.yaml
  stable/velero/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19094 [stable/nextcloud] Add php-fpm+nginx support
  stable/nextcloud/Chart.yaml
  stable/nextcloud/README.md
  stable/nextcloud/templates/deployment.yaml
  stable/nextcloud/templates/nginx-config.yaml
  stable/nextcloud/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#18391 incubator/fluentd-cloudwatch Added annotations for the service account
  incubator/fluentd-cloudwatch/Chart.yaml
  incubator/fluentd-cloudwatch/README.md
  incubator/fluentd-cloudwatch/templates/serviceaccount.yaml
  incubator/fluentd-cloudwatch/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18521 [stable/metabase] Allowing loadBalancerSourceRanges to be specified.
  stable/metabase/Chart.yaml
  stable/metabase/README.md
  stable/metabase/templates/service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19048 [stable/jenkins] enable agent master security
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, size/XS

#18212 [stable/stolon] add prometheus service monitor
  stable/stolon/Chart.yaml
  stable/stolon/README.md
  stable/stolon/templates/keeper-statefulset.yaml
  stable/stolon/templates/metrics-service.yaml
  stable/stolon/templates/metrics-servicemonitor.yaml
  stable/stolon/templates/proxy-deployment.yaml
  stable/stolon/templates/sentinel-deployment.yaml
  stable/stolon/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18737 [stable/prometheus] Add myself to OWNERS
  stable/prometheus/Chart.yaml
  stable/prometheus/OWNERS
Labels: Contribution Allowed, approved, lgtm, size/S

#19123 [stable/grafana] Update to grafana 6.5.0
  stable/grafana/Chart.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19276 [stable/prometheus-rabbitmq-exporter] Fix ServiceMonitor + adds alerts
  stable/prometheus-rabbitmq-exporter/Chart.yaml
  stable/prometheus-rabbitmq-exporter/templates/prometheusrule.yaml
  stable/prometheus-rabbitmq-exporter/templates/service.yaml
  stable/prometheus-rabbitmq-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19291 [stable/metabase] Being maintainer of the chart
  stable/metabase/Chart.yaml
  stable/metabase/OWNERS
Labels: Contribution Allowed, approved, lgtm, size/XS

#19290 [stable/postgresql] add HA comment
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17533 [stable/metabase] Fixes compatibility with 1.16
  stable/metabase/Chart.yaml
  stable/metabase/templates/_helpers.tpl
  stable/metabase/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19278 [stable/dex] Enabling to control whether cluster role and cluster role binding will be created
  stable/dex/Chart.yaml
  stable/dex/README.md
  stable/dex/templates/clusterrole.yaml
  stable/dex/templates/clusterrolebinding.yaml
  stable/dex/templates/role.yaml
  stable/dex/templates/rolebinding.yaml
  stable/dex/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19124 [stable/metabase] add namespace argument to all templates
  stable/metabase/Chart.yaml
  stable/metabase/templates/config.yaml
  stable/metabase/templates/database-secret.yaml
  stable/metabase/templates/deployment.yaml
  stable/metabase/templates/ingress.yaml
  stable/metabase/templates/service.yaml
  stable/metabase/templates/ssl-secret.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19244 [stable/mongodb] Add JSON Schema
  stable/mongodb/Chart.yaml
  stable/mongodb/values.schema.json
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#19247 [stable/rabbitmq] Add JSON Schema
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/values.schema.json
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19252 [stable/mariadb] Add JSON Schema
  stable/mariadb/Chart.yaml
  stable/mariadb/values.schema.json
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#19255 [stable/drupal] Add JSON Schema & standardize ingress configuration
  stable/drupal/Chart.yaml
  stable/drupal/README.md
  stable/drupal/templates/ingress.yaml
  stable/drupal/templates/tls-secrets.yaml
  stable/drupal/values.schema.json
  stable/drupal/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#19257 [stable/joomla] Add JSON Schema & standardize ingress configuration
  stable/joomla/Chart.yaml
  stable/joomla/README.md
  stable/joomla/templates/ingress.yaml
  stable/joomla/values.schema.json
  stable/joomla/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#19293 [stable/nextcloud] Add annotations at pod/deployment level
  stable/nextcloud/Chart.yaml
  stable/nextcloud/README.md
  stable/nextcloud/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19222 [stable/redis Add JSON Schema
  stable/redis/Chart.yaml
  stable/redis/values.schema.json
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#19294 [stable/mercure] Support for v0.8 and modernize the chart
  stable/mercure/Chart.yaml
  stable/mercure/README.md
  stable/mercure/templates/NOTES.txt
  stable/mercure/templates/_helpers.tpl
  stable/mercure/templates/backend-config.yaml
  stable/mercure/templates/configmap.yaml
  stable/mercure/templates/deployment.yaml
  stable/mercure/templates/ingress.yaml
  stable/mercure/templates/secret.yaml
  stable/mercure/templates/service.yaml
  stable/mercure/templates/serviceaccount.yaml
  stable/mercure/templates/tests/test-connection.yaml
  stable/mercure/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/L

#19253 [incubator/kafka]. Add ability to set ServiceMonitor namespace to realese namespace
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
  incubator/kafka/templates/_helpers.tpl
  incubator/kafka/templates/servicemonitors.yaml
  incubator/kafka/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#18794 stable/wavefront: add coredns
  stable/wavefront/Chart.yaml
  stable/wavefront/examples/discovery-config-values.yaml
  stable/wavefront/templates/collector-config.yaml
  stable/wavefront/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19271 [stable/graylog] Fix services nodePorts, initContainer env, kubectl
  stable/graylog/Chart.yaml
  stable/graylog/README.md
  stable/graylog/templates/statefulset.yaml
  stable/graylog/templates/tcp-service.yaml
  stable/graylog/templates/udp-service.yaml
  stable/graylog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#17869 [stable/redis-ha] use master group name not used in haproxy tcp-check…
  stable/redis-ha/Chart.yaml
  stable/redis-ha/README.md
  stable/redis-ha/templates/_configs.tpl
  stable/redis-ha/templates/_helpers.tpl
  stable/redis-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19265 [stable/redis-ha] Make namespaces of resources configurable.
  stable/redis-ha/Chart.yaml
  stable/redis-ha/templates/redis-auth-secret.yaml
  stable/redis-ha/templates/redis-ha-announce-service.yaml
  stable/redis-ha/templates/redis-ha-configmap.yaml
  stable/redis-ha/templates/redis-ha-pdb.yaml
  stable/redis-ha/templates/redis-ha-role.yaml
  stable/redis-ha/templates/redis-ha-rolebinding.yaml
  stable/redis-ha/templates/redis-ha-service.yaml
  stable/redis-ha/templates/redis-ha-serviceaccount.yaml
  stable/redis-ha/templates/redis-ha-servicemonitor.yaml
  stable/redis-ha/templates/redis-ha-statefulset.yaml
  stable/redis-ha/templates/redis-haproxy-deployment.yaml
  stable/redis-ha/templates/redis-haproxy-service.yaml
  stable/redis-ha/templates/redis-haproxy-serviceaccount.yaml
  stable/redis-ha/templates/redis-haproxy-servicemonitor.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17791 [stable/jenkins] Support for Jenkins native SSL / HTTPS
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/NOTES.txt
  stable/jenkins/templates/jenkins-master-deployment.yaml
  stable/jenkins/templates/secret-https-jks.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#19315 [stable/pomerium] Update Pomerium to 0.5.1 release
  stable/pomerium/Chart.yaml
  stable/pomerium/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#18517 [stable/etcd-operator] Default etcdOperator.tolerations in values.yaml
  stable/etcd-operator/Chart.yaml
  stable/etcd-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18789 [stable/jenkins] update default plugin versions
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#19221 [stable/pgadmin] improved README.md
  stable/pgadmin/Chart.yaml
  stable/pgadmin/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19304 [stable/rabbitmq] Add NetworkPolicy simple support.
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/ci/default-values.yaml
  stable/rabbitmq/ci/networkpolicy-values.yaml
  stable/rabbitmq/templates/networkpolicy.yaml
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#19331 [stable/mariadb] Fix JSON schema
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
  stable/mariadb/templates/master-statefulset.yaml
  stable/mariadb/templates/secrets.yaml
  stable/mariadb/values-production.yaml
  stable/mariadb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19102 [stable/prometheus-operator] Fix labels of prometheus and alertmanager
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/alertmanager/service.yaml
  stable/prometheus-operator/templates/prometheus/service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19332 [stable/drupal] Fix JSON schema
  stable/drupal/Chart.yaml
  stable/drupal/requirements.lock
  stable/drupal/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18561 [stable/sonarqube] handle sonarqube 8.0 "run.sh" directory
  stable/sonarqube/Chart.yaml
  stable/sonarqube/README.md
  stable/sonarqube/templates/config.yaml
  stable/sonarqube/templates/copy-plugins.yaml
  stable/sonarqube/templates/deployment.yaml
  stable/sonarqube/templates/install-plugins.yaml
  stable/sonarqube/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18993 [stable/cockroachdb] Complete refactor and capabilities extension
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/README.md
  stable/cockroachdb/templates/NOTES.txt
  stable/cockroachdb/templates/_helpers.tpl
  stable/cockroachdb/templates/cluster-init.yaml
  stable/cockroachdb/templates/clusterrole.yaml
  stable/cockroachdb/templates/clusterrolebinding.yaml
  stable/cockroachdb/templates/job.init.yaml
  stable/cockroachdb/templates/networkpolicy.yaml
  stable/cockroachdb/templates/pdb.yaml
  stable/cockroachdb/templates/poddisruptionbudget.yaml
  stable/cockroachdb/templates/role.yaml
  stable/cockroachdb/templates/rolebinding.yaml
  stable/cockroachdb/templates/secret.registry.yaml
  stable/cockroachdb/templates/service-discovery.yaml
  stable/cockroachdb/templates/service.discovery.yaml
  stable/cockroachdb/templates/service.public.yaml
  stable/cockroachdb/templates/service.yaml
  stable/cockroachdb/templates/serviceaccount.yaml
  stable/cockroachdb/templates/statefulset.yaml
  stable/cockroachdb/templates/tests/client-test.yaml
  stable/cockroachdb/templates/tests/client.yaml
  stable/cockroachdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XXL

#19322 [stable/sonatype-nexus] Fix trailing white space trimming in service template
  stable/sonatype-nexus/Chart.yaml
  stable/sonatype-nexus/templates/service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19342 [stable/cockroachdb] Fix statefulset resource templating
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#19338 [stable/redis-ha] Fix extraArgs option for redis-ha exporter
  stable/redis-ha/Chart.yaml
  stable/redis-ha/templates/redis-ha-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#19348 [stable/ambassador] Allow Configuration of Ambassador Readiness and Liveness Probe Values
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/templates/deployment.yaml
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#19337 [stable/redis] Fix JSON schema
  stable/redis/Chart.yaml
  stable/redis/templates/_helpers.tpl
  stable/redis/values-production.yaml
  stable/redis/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19314 [stable/graylog] Remove privileged initContainer mode; update Graylog version
  stable/graylog/Chart.yaml
  stable/graylog/README.md
  stable/graylog/templates/NOTES.txt
  stable/graylog/templates/job.yaml
  stable/graylog/templates/master-service.yaml
  stable/graylog/templates/statefulset.yaml
  stable/graylog/templates/tcp-service.yaml
  stable/graylog/templates/udp-service.yaml
  stable/graylog/templates/web-service.yaml
  stable/graylog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19350 [stable/chartmuseum] upgrade to v0.10.0
  stable/chartmuseum/Chart.yaml
  stable/chartmuseum/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#19359 [stable/gocd] Bump up GoCD Version to 19.11.0
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19176 [stable/airflow] Fix for #19175
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/templates/deployments-scheduler.yaml
  stable/airflow/templates/deployments-web.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#19355 [stable/gocd] Update OWNERS lists
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/OWNERS
Labels: Contribution Allowed, approved, lgtm, size/S

#19329 [stable/external-dns] Add ServiceMonitor object
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/servicemonitor.yaml
  stable/external-dns/values-production.yaml
  stable/external-dns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19007 [stable/redmine] Add option to use existingSecret for external db
  stable/redmine/Chart.yaml
  stable/redmine/README.md
  stable/redmine/templates/deployment.yaml
  stable/redmine/templates/externaldb-secrets.yaml
  stable/redmine/templates/secrets.yaml
  stable/redmine/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19368 [stable/sentry]: adds extra AWS S3 variables used in configmap
  stable/sentry/Chart.yaml
  stable/sentry/README.md
  stable/sentry/templates/configmap.yaml
  stable/sentry/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19339 [stable/rabbitmq] Fix affinity templating
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/ci/affinity-toleration-values.yaml
  stable/rabbitmq/templates/_helpers.tpl
  stable/rabbitmq/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19336 [stable/nginx-ingress] Fix parameters in Readme.md
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19321 [stable/chaoskube] Fix wrong label in docs
  stable/chaoskube/Chart.yaml
  stable/chaoskube/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19209 [stable/etcd-operator] Introduce crds directory for compatibility with Helm v3
  stable/etcd-operator/Chart.yaml
  stable/etcd-operator/crds/etcd-cluster-crd.yaml
  stable/etcd-operator/templates/crds.yaml
  stable/etcd-operator/templates/etcd-cluster-crd.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#19328 [stable/newrelic-infrastructure] Add some globals
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/README.md
  stable/newrelic-infrastructure/templates/NOTES.txt
  stable/newrelic-infrastructure/templates/_helpers.tpl
  stable/newrelic-infrastructure/templates/daemonset.yaml
  stable/newrelic-infrastructure/templates/secret.yaml
  stable/newrelic-infrastructure/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#19370 [stable/mysql] Option to create a custom service account
  stable/mysql/Chart.yaml
  stable/mysql/README.md
  stable/mysql/templates/_helpers.tpl
  stable/mysql/templates/deployment.yaml
  stable/mysql/templates/serviceaccount.yaml
  stable/mysql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18073 [stable/oauth2-proxy] feature: add PodDisruptionBudget.
  stable/oauth2-proxy/Chart.yaml
  stable/oauth2-proxy/README.md
  stable/oauth2-proxy/default-values.yaml
  stable/oauth2-proxy/pdb-values.yaml
  stable/oauth2-proxy/templates/poddisruptionbudget.yaml
  stable/oauth2-proxy/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#19356 [stable/verdaccio] Render clusterIP only if set
  stable/verdaccio/Chart.yaml
  stable/verdaccio/templates/service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19358 stable/jenkins make agent.slaveConnectTimeout configurable
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/_helpers.tpl
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18784 [stable/kube2iam] Update the kube2iam apiVersion for k8s 1.16 compatibility
  stable/kube2iam/Chart.yaml
  stable/kube2iam/templates/clusterrole.yaml
  stable/kube2iam/templates/clusterrolebinding.yaml
  stable/kube2iam/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18921 [stable/sonatype-nexus]update-nexus-version
  stable/sonatype-nexus/Chart.yaml
  stable/sonatype-nexus/README.md
  stable/sonatype-nexus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19353 [stable/velero] Update Velero to v1.2.0
  stable/velero/Chart.yaml
  stable/velero/README.md
  stable/velero/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19380 [stable/telegraf] add support for annotations on services
  stable/telegraf/Chart.yaml
  stable/telegraf/templates/service.yaml
  stable/telegraf/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19142 Fix duplicative label in the Solr service template.
  incubator/solr/Chart.yaml
  incubator/solr/templates/service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19245 [stable/minio] Fix helm 3 install error
  stable/minio/Chart.yaml
  stable/minio/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19385 [incubator/jaeger] Add autoscaler for collector
  incubator/jaeger/Chart.yaml
  incubator/jaeger/README.md
  incubator/jaeger/templates/collector-deploy.yaml
  incubator/jaeger/templates/collector-hpa.yaml
  incubator/jaeger/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#19212 [stable/jaeger-operator] make compatible with helm3
  stable/jaeger-operator/Chart.yaml
  stable/jaeger-operator/README.md
  stable/jaeger-operator/templates/crds.yaml
  stable/jaeger-operator/templates/crds/crd.yaml
  stable/jaeger-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#19360 [stable/prometheus-operator] Service labels shall also be reflected on prometheus-operator
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/prometheus-operator/service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19388 [stable/mariadb] Mariadb credentials as mounted files
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
  stable/mariadb/templates/master-statefulset.yaml
  stable/mariadb/templates/slave-statefulset.yaml
  stable/mariadb/values-production.yaml
  stable/mariadb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XL

#19400 [stable/weave-scope] Fixes apiVersion typo for K8s 1.16
  stable/weave-scope/Chart.yaml
  stable/weave-scope/charts/weave-scope-agent/Chart.yaml
  stable/weave-scope/charts/weave-scope-cluster-agent/Chart.yaml
  stable/weave-scope/charts/weave-scope-cluster-agent/templates/deployment.yaml
  stable/weave-scope/charts/weave-scope-frontend/Chart.yaml
  stable/weave-scope/charts/weave-scope-frontend/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#19403 [stable/hazelcast] Change service to headless by default, extract readOnlyRootFilesystem (#85)
  stable/hazelcast/Chart.yaml
  stable/hazelcast/README.adoc
  stable/hazelcast/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#19394 [stable/oauth2-proxy] fix PodDisruptionBudget.
  stable/oauth2-proxy/Chart.yaml
  stable/oauth2-proxy/ci/default-values.yaml
  stable/oauth2-proxy/ci/pdb-values.yaml
  stable/oauth2-proxy/templates/poddisruptionbudget.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#19402 [stable/jaeger-operator] fix for helm 3
  stable/jaeger-operator/Chart.yaml
  stable/jaeger-operator/crds/crd.yaml
  stable/jaeger-operator/templates/_helpers.tpl
  stable/jaeger-operator/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#19406 Fix validation issue with Helm 3
  stable/sematext-agent/Chart.yaml
  stable/sematext-agent/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#19352 [incubator/azuremonitor-containers] add additional parameters and update the instructions for Helm3
  incubator/azuremonitor-containers/Chart.yaml
  incubator/azuremonitor-containers/README.md
  incubator/azuremonitor-containers/templates/NOTES.txt
  incubator/azuremonitor-containers/templates/omsagent-daemonset.yaml
  incubator/azuremonitor-containers/templates/omsagent-deployment.yaml
  incubator/azuremonitor-containers/templates/omsagent-rs-configmap.yaml
  incubator/azuremonitor-containers/templates/omsagent-secret.yaml
  incubator/azuremonitor-containers/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19177 [stable/grafana] Fix conflict when using multiple grafana providers
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/_pod.tpl
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19414 [stable/airflow] bug fix to make git sync work with branches other then master
  stable/airflow/Chart.yaml
  stable/airflow/templates/configmap-git-clone.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#19133 [stable/fluentd] Remove duplicate pvc resource (#19131)
  stable/fluentd/Chart.yaml
  stable/fluentd/templates/pvc.yaml
  stable/fluentd/templates/pvc.yml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19376 [incubator/jaeger] feature: Cassandra TLS option
  incubator/jaeger/Chart.yaml
  incubator/jaeger/README.md
  incubator/jaeger/templates/cassandra-schema-job.yaml
  incubator/jaeger/templates/collector-deploy.yaml
  incubator/jaeger/templates/query-deploy.yaml
  incubator/jaeger/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#18411 [stable/prometheus] does not support semver compatible chart versioning.
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19440 [incubator/kafka] Changed KAFKA_ADVERTISED_LISTENERS use a fully-qualified DNS name.
  incubator/kafka/Chart.yaml
  incubator/kafka/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19431 [stable/spring-cloud-data-flow] Update to new SCDF version 2.3.0
  stable/spring-cloud-data-flow/Chart.yaml
  stable/spring-cloud-data-flow/README.md
  stable/spring-cloud-data-flow/requirements.lock
  stable/spring-cloud-data-flow/requirements.yaml
  stable/spring-cloud-data-flow/templates/grafana-configmap.yaml
  stable/spring-cloud-data-flow/templates/grafana-secret.yaml
  stable/spring-cloud-data-flow/templates/prometheus-proxy-clusterrolebinding.yaml
  stable/spring-cloud-data-flow/templates/prometheus-proxy-deployment.yaml
  stable/spring-cloud-data-flow/templates/prometheus-proxy-service.yaml
  stable/spring-cloud-data-flow/templates/prometheus-proxy-serviceaccount.yaml
  stable/spring-cloud-data-flow/templates/server-config.yaml
  stable/spring-cloud-data-flow/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#19438 [incubator/jaeger] hotfix for Cassandra TLS value
  incubator/jaeger/Chart.yaml
  incubator/jaeger/templates/collector-deploy.yaml
  incubator/jaeger/templates/query-deploy.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#17979 [stable/prometheus] Support ingress.extraPaths
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/alertmanager-ingress.yaml
  stable/prometheus/templates/pushgateway-ingress.yaml
  stable/prometheus/templates/server-ingress.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#16692 fix #16690 - stable/prometheus - fails with empty clusterrole ruleset
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/alertmanager-clusterrole.yaml
  stable/prometheus/templates/pushgateway-clusterrole.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19335 [stable/prometheus-operator] Fix conditions in the default rule templates
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/hack/sync_prometheus_rules.py
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system-kubelet.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/prometheus.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19016 [stable/grafana] Fix typo in grafana chart README
  stable/grafana/Chart.yaml
  stable/grafana/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19423 [incubator/solr] Add image pullSecrets
  incubator/solr/Chart.yaml
  incubator/solr/README.md
  incubator/solr/templates/_helpers.tpl
  incubator/solr/templates/exporter-deployment.yaml
  incubator/solr/templates/statefulset.yaml
  incubator/solr/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19433 [stable/redis-ha] Fix app version in chart
  stable/redis-ha/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19201 [stable/mysql] #5154 MySql: Allow to override deployment strategy
  stable/mysql/Chart.yaml
  stable/mysql/README.md
  stable/mysql/templates/deployment.yaml
  stable/mysql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19422 [stable/airflow] fix service name typo in notes
  stable/airflow/Chart.yaml
  stable/airflow/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18970 [stable/couchbase] Update to version 1.2.2
  stable/couchbase-operator/Chart.yaml
  stable/couchbase-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19439 [stable/centrifugo] Helm3: Do not render ClusterIP if it is empty
  stable/centrifugo/Chart.yaml
  stable/centrifugo/templates/service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18665 [stable/openldap] Fixed NOTES.txt of openldap
  stable/openldap/Chart.yaml
  stable/openldap/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19233 [stable/falco] Add affinity to falco chart
  stable/falco/Chart.yaml
  stable/falco/README.md
  stable/falco/templates/daemonset.yaml
  stable/falco/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17693 [stable/openvpn] Add tolerations support for openvpn
  stable/openvpn/Chart.yaml
  stable/openvpn/README.md
  stable/openvpn/templates/openvpn-deployment.yaml
  stable/openvpn/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18996 [stable/airflow] fix typo in readme for session affinity
  stable/airflow/Chart.yaml
  stable/airflow/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#17107 [stable/prometheus] Pushgateway deployment strategy type
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/pushgateway-deployment.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19365 [incubator/jaeger] Fix indent of tolerations
  incubator/jaeger/Chart.yaml
  incubator/jaeger/templates/spark-cronjob.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19062 add to Grafana documentation some missing services parameters which appear in the service template
  stable/grafana/Chart.yaml
  stable/grafana/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19005 [stable/redmine] Option to create a custom service account
  stable/redmine/Chart.yaml
  stable/redmine/README.md
  stable/redmine/templates/_helpers.tpl
  stable/redmine/templates/deployment.yaml
  stable/redmine/templates/serviceaccount.yaml
  stable/redmine/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18637 stable/prometheus: Add service session affinity
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/alertmanager-service.yaml
  stable/prometheus/templates/server-service.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19429 [stable/drone] added the ability to override DRONE_RPC_SERVER
  stable/drone/Chart.yaml
  stable/drone/README.md
  stable/drone/templates/_helpers.tpl
  stable/drone/templates/deployment-agent.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19473 [stable/spring-cloud-data-flow] Add task scheduler launcher url
  stable/spring-cloud-data-flow/Chart.yaml
  stable/spring-cloud-data-flow/templates/server-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#19186 [stable/elasticsearch-curator] Fixed values for helm hooks and added CI test for it
  stable/elasticsearch-curator/Chart.yaml
  stable/elasticsearch-curator/ci/default-values.yaml
  stable/elasticsearch-curator/ci/hooks-values.yaml
  stable/elasticsearch-curator/templates/hooks/job.install.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17794 [stable/elasticsearch] Ensure selectors match template labels
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/templates/data-statefulset.yaml
  stable/elasticsearch/templates/master-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19287 [stable/contour] manage crds with v3/v2
  stable/contour/Chart.yaml
  stable/contour/README.md
  stable/contour/crds/httpproxies.yaml
  stable/contour/crds/ingressroutes.yaml
  stable/contour/crds/tlscertificatedelegations.yaml
  stable/contour/templates/cleanup-crds.yaml
  stable/contour/templates/clusterrole.yaml
  stable/contour/templates/crds.yaml
  stable/contour/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#18492 stable/velero: Update Velero to v1.2.0
  stable/velero/Chart.yaml
  stable/velero/README.md
  stable/velero/templates/NOTES.txt
  stable/velero/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#19405 Replace lwander with ezimanyi in OWNERS for spinnaker chart
  stable/spinnaker/Chart.yaml
  stable/spinnaker/OWNERS
Labels: Contribution Allowed, approved, lgtm, size/S

#19480 [stable/opa] Fix default OPA values.yaml and update to latest
  stable/opa/Chart.yaml
  stable/opa/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#19476 stable/atlantis [19474]: correct format on defaultTFVersion value
  stable/atlantis/Chart.yaml
  stable/atlantis/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#19472 [stable/prometheus] Improve server file names to reflect official docs
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19434 [stable/mongodb] Add extraEnvVars
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/templates/_helpers.tpl
  stable/mongodb/templates/deployment-standalone.yaml
  stable/mongodb/templates/statefulset-arbiter-rs.yaml
  stable/mongodb/templates/statefulset-primary-rs.yaml
  stable/mongodb/templates/statefulset-secondary-rs.yaml
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#19451 stable/external-dns: Add support for log format flag for external DNS
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/deployment.yaml
  stable/external-dns/values-production.yaml
  stable/external-dns/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#19463 [stable/rabbitmq] Fix metrics service port.
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/templates/svc.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#19303 [stable/minio] add PodDisruptionBudget
  stable/minio/Chart.yaml
  stable/minio/templates/poddisruptionbudget.yaml
  stable/minio/templates/post-install-create-bucket-job.yaml
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19404 [stable/postgresql] Improve 'extraEnv' example in values
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#19236 [incubator/sparkoperator] Introduce crds directory for compatibility with Helm v3
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/README.md
  incubator/sparkoperator/crds/crds.yaml
  incubator/sparkoperator/templates/crds.yaml
  incubator/sparkoperator/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XXL

#18164 [stable/distributed-tensorflow] Add Dysproz to OWNERS, update owner in Chart.yml
  stable/distributed-tensorflow/Chart.yaml
  stable/distributed-tensorflow/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19494 Fix scheme assignment and selector labels for statefulset headless svc
  stable/minio/Chart.yaml
  stable/minio/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#19511 [stable/ambassador] Upgrade Ambassador Pro 0.10.0→0.11.0
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
  stable/ambassador/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#19486 [stable/mysql] Add optional passwords support #(19485)
  stable/mysql/Chart.yaml
  stable/mysql/templates/deployment.yaml
  stable/mysql/templates/secrets.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#16871 [stable/sumologic-fluentd] Update sumologic fluentd collector to 2.4.2
  stable/sumologic-fluentd/Chart.yaml
  stable/sumologic-fluentd/files/file.source.containers.conf
  stable/sumologic-fluentd/files/file.source.docker.conf
  stable/sumologic-fluentd/files/file.source.kubernetes.conf
  stable/sumologic-fluentd/files/fluent.file.conf
  stable/sumologic-fluentd/files/fluent.forward.conf
  stable/sumologic-fluentd/files/fluent.systemd.conf
  stable/sumologic-fluentd/files/out.sumo.conf
  stable/sumologic-fluentd/files/systemd.source.containers.conf
  stable/sumologic-fluentd/files/systemd.source.systemd.conf
  stable/sumologic-fluentd/templates/configmap-user.yaml
  stable/sumologic-fluentd/templates/configmap.yaml
  stable/sumologic-fluentd/templates/daemonset.yaml
  stable/sumologic-fluentd/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XXL

#19512 [stable/telegraph] Added Support for volume mounts on deployment
  stable/telegraf/Chart.yaml
  stable/telegraf/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#19483 stable/fluent-bit: add input.systemd.stripUnderscores
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/config.yaml
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19514 [stable/spinnaker] allow for extra s3 args
  stable/spinnaker/Chart.yaml
  stable/spinnaker/templates/configmap/halyard-config.yaml
  stable/spinnaker/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#19289 [stable/stolon] upgrade api version for kubernetes 1.16+
  stable/stolon/Chart.yaml
  stable/stolon/templates/keeper-statefulset.yaml
  stable/stolon/templates/proxy-deployment.yaml
  stable/stolon/templates/sentinel-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19510 [stable/spinnaker] remove unused feature flag for jobs
  stable/spinnaker/Chart.yaml
  stable/spinnaker/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#19184 [stable/weave-scope] Fix compatibility for Kubernetes 1.16, update weave-scope to 1.12.0
  stable/weave-scope/Chart.yaml
  stable/weave-scope/charts/weave-scope-agent/Chart.yaml
  stable/weave-scope/charts/weave-scope-cluster-agent/Chart.yaml
  stable/weave-scope/charts/weave-scope-frontend/Chart.yaml
  stable/weave-scope/charts/weave-scope-frontend/templates/_helpers.tpl
  stable/weave-scope/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#17716 [stable/hackmd] Support kubernetes >= 1.16
  stable/hackmd/Chart.yaml
  stable/hackmd/templates/deployment.yaml
  stable/hackmd/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18358 [stable/atlantis] Fix typo in README.md for orgWhitelist
  stable/atlantis/Chart.yaml
  stable/atlantis/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS
