Repository helm/charts, pull requests merged in 2020-09, with the labels that each got.

#23651 [stable/airflow] version 7.6.0
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/UPGRADE.md
  stable/airflow/examples/google-gke/custom-values.yaml
  stable/airflow/templates/config/configmap-env.yaml
  stable/airflow/templates/config/configmap-scripts-git.yaml
  stable/airflow/templates/config/configmap-scripts.yaml
  stable/airflow/templates/config/configmap-variables-pools.yaml
  stable/airflow/templates/config/secret-connections.yaml
  stable/airflow/templates/flower/flower-deployment.yaml
  stable/airflow/templates/flower/flower-ingress.yaml
  stable/airflow/templates/flower/flower-pdb.yaml
  stable/airflow/templates/flower/flower-service.yaml
  stable/airflow/templates/monitoring/prometheus-rule.yaml
  stable/airflow/templates/monitoring/service-monitor.yaml
  stable/airflow/templates/rbac/airflow-role.yaml
  stable/airflow/templates/rbac/airflow-rolebinding.yaml
  stable/airflow/templates/rbac/airflow-serviceaccount.yaml
  stable/airflow/templates/scheduler/scheduler-deployment.yaml
  stable/airflow/templates/scheduler/scheduler-pdb.yaml
  stable/airflow/templates/webserver/webserver-deployment.yaml
  stable/airflow/templates/webserver/webserver-ingress.yaml
  stable/airflow/templates/webserver/webserver-pdb.yaml
  stable/airflow/templates/webserver/webserver-service.yaml
  stable/airflow/templates/worker/worker-hpa.yaml
  stable/airflow/templates/worker/worker-pdb.yaml
  stable/airflow/templates/worker/worker-service.yaml
  stable/airflow/templates/worker/worker-statefulset.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/L

#23642 stable/mysql with x protocol
  stable/mysql/Chart.yaml
  stable/mysql/README.md
  stable/mysql/templates/NOTES.txt
  stable/mysql/templates/deployment.yaml
  stable/mysql/templates/svc.yaml
  stable/mysql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23409 [stable/kube-ops-view] add environment variables
  stable/kube-ops-view/Chart.yaml
  stable/kube-ops-view/README.md
  stable/kube-ops-view/templates/deployment.yaml
  stable/kube-ops-view/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23664 [stable/spark-history-server] Add service nodeport
  stable/spark-history-server/Chart.yaml
  stable/spark-history-server/README.md
  stable/spark-history-server/templates/service.yaml
  stable/spark-history-server/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#23662 [stable/grafana] deprecate chart
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/ci/with-dashboard-values.yaml
  stable/grafana/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, size/M

#23668 [stable/opa] Fix prometheus servicemonitor discovery configuration
  stable/opa/Chart.yaml
  stable/opa/README.md
  stable/opa/templates/deployment.yaml
  stable/opa/templates/service.yaml
  stable/opa/templates/servicemonitor.yaml
  stable/opa/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#23670 [stable/chartmuseum] fixed name of service account
  stable/chartmuseum/Chart.yaml
  stable/chartmuseum/templates/deployment.yaml
  stable/chartmuseum/templates/serviceaccount.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23679 [stable/jenkins] correct chart description
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#22925 [incubator/sentry-kubernetes] Make EVENT_LEVELS env configurable
  incubator/sentry-kubernetes/Chart.yaml
  incubator/sentry-kubernetes/README.md
  incubator/sentry-kubernetes/templates/deployment.yaml
  incubator/sentry-kubernetes/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#23682 [stable/vsphere-cpi] Update for CPI v1.2.1
  stable/vsphere-cpi/Chart.yaml
  stable/vsphere-cpi/README.md
  stable/vsphere-cpi/templates/common.yaml
  stable/vsphere-cpi/templates/configmap.yaml
  stable/vsphere-cpi/templates/daemonset.yaml
  stable/vsphere-cpi/templates/ingress.yaml
  stable/vsphere-cpi/templates/podsecuritypolicy.yaml
  stable/vsphere-cpi/templates/role-binding.yaml
  stable/vsphere-cpi/templates/role.yaml
  stable/vsphere-cpi/templates/secret.yaml
  stable/vsphere-cpi/templates/service-account.yaml
  stable/vsphere-cpi/templates/service.yaml
  stable/vsphere-cpi/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#23686 [stable/grafana] update deprecation notice
  stable/grafana/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#23684 [stable/seq] Add an easy way to set the cache size limit
  stable/seq/Chart.yaml
  stable/seq/README.md
  stable/seq/templates/deployment.yaml
  stable/seq/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#23701 [prometheus-nats-exporter] deprecate
  stable/prometheus-nats-exporter/Chart.yaml
  stable/prometheus-nats-exporter/README.md
  stable/prometheus-nats-exporter/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, size/S

#23694 [prometheus-adapter] deprecate chart
  stable/prometheus-adapter/Chart.yaml
  stable/prometheus-adapter/README.md
  stable/prometheus-adapter/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23697 [prometheus-consul-exporter] deprecate chart
  stable/prometheus-consul-exporter/Chart.yaml
  stable/prometheus-consul-exporter/README.md
  stable/prometheus-consul-exporter/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23695 [prometheus-blackbox-exporter] deprecate chart
  stable/prometheus-blackbox-exporter/Chart.yaml
  stable/prometheus-blackbox-exporter/README.md
  stable/prometheus-blackbox-exporter/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23696 [prometheus-cloudwatch-exporter] deprecate chart
  stable/prometheus-cloudwatch-exporter/Chart.yaml
  stable/prometheus-cloudwatch-exporter/README.md
  stable/prometheus-cloudwatch-exporter/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23700 [prometheus-mysql-exporter] deprecate
  stable/prometheus-mysql-exporter/Chart.yaml
  stable/prometheus-mysql-exporter/README.md
  stable/prometheus-mysql-exporter/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23702 [prometheus-node-exporter] deprecate
  stable/prometheus-node-exporter/Chart.yaml
  stable/prometheus-node-exporter/README.md
  stable/prometheus-node-exporter/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23703 [prometheus-postgres-exporter] deprecate
  stable/prometheus-postgres-exporter/Chart.yaml
  stable/prometheus-postgres-exporter/README.md
  stable/prometheus-postgres-exporter/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23704 [prometheus-pushgateway] deprecate
  stable/prometheus-pushgateway/Chart.yaml
  stable/prometheus-pushgateway/README.md
  stable/prometheus-pushgateway/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23705 [prometheus-rabbitmq-exporter] deprecate
  stable/prometheus-rabbitmq-exporter/Chart.yaml
  stable/prometheus-rabbitmq-exporter/README.md
  stable/prometheus-rabbitmq-exporter/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23706 [prometheus-redis-exporter] deprecate
  stable/prometheus-redis-exporter/Chart.yaml
  stable/prometheus-redis-exporter/README.md
  stable/prometheus-redis-exporter/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23708 [prometheus-snmp-exporter] deprecate
  stable/prometheus-snmp-exporter/Chart.yaml
  stable/prometheus-snmp-exporter/README.md
  stable/prometheus-snmp-exporter/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23699 [prometheus-mongodb-exporter] deprecate
  stable/prometheus-mongodb-exporter/Chart.yaml
  stable/prometheus-mongodb-exporter/README.md
  stable/prometheus-mongodb-exporter/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23692 [prometheus] deprecate chart
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23698 [prometheus-couchdb-exporter] deprecate chart
  stable/prometheus-couchdb-exporter/Chart.yaml
  stable/prometheus-couchdb-exporter/README.md
  stable/prometheus-couchdb-exporter/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23707 [prometheus-to-sd] deprecate
  stable/prometheus-to-sd/Chart.yaml
  stable/prometheus-to-sd/README.md
  stable/prometheus-to-sd/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23654 [incubator/rundeck] Option to run additional sidecars in the pod
  incubator/rundeck/Chart.yaml
  incubator/rundeck/README.md
  incubator/rundeck/templates/deployment.yaml
  incubator/rundeck/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23658 [stable/spinnaker] fix node selector and taints for hooks
  stable/spinnaker/Chart.yaml
  stable/spinnaker/templates/hooks/cleanup.yaml
  stable/spinnaker/templates/hooks/install-using-hal.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23717 [stable/metrics-server] Configurable test image
  stable/metrics-server/Chart.yaml
  stable/metrics-server/README.md
  stable/metrics-server/templates/tests/test-version.yaml
  stable/metrics-server/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23714 [stable/unifi] deprecate unifi helm chart
  stable/unifi/Chart.yaml
  stable/unifi/README.md
  stable/unifi/templates/NOTES.txt
Labels: Contribution Allowed, approved, size/S

#23720 [stable/rocketchat] updating RocketChat version to 3.6.0
  stable/rocketchat/Chart.yaml
  stable/rocketchat/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23725 [stable/airflow] Update redis.existingSecretKey option to align w/ stable/redis
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/UPGRADE.md
  stable/airflow/examples/google-gke/custom-values.yaml
  stable/airflow/templates/_helpers.tpl
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#23734 Updaing notice on charts repo deprecation
  README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#23738 [stable/prometheus-operator] deprecate chart
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, size/S

#23740 [stable/chaoskube] Implement imagePullSecrets for the deployment.
  stable/chaoskube/Chart.yaml
  stable/chaoskube/README.md
  stable/chaoskube/templates/deployment.yaml
  stable/chaoskube/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#23747 [stable/mongodb-replicaset] Deprecate chart
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/README.md
  stable/mongodb-replicaset/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, size/M

#23746 [stable/rabbitmq-ha] Deprecate chart
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23729 [stable/karma] Upgrade karma to v0.70
  stable/karma/Chart.yaml
  stable/karma/README.md
  stable/karma/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#23753 [stable/dex] Add priorityClassName
  stable/dex/Chart.yaml
  stable/dex/templates/deployment.yaml
  stable/dex/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23440 GitHub pull request template: Update chart best practices link
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23752 [stable/hlf-peer] Fix metrics configuration
  stable/hlf-peer/Chart.yaml
  stable/hlf-peer/README.md
  stable/hlf-peer/templates/configmap--peer.yaml
  stable/hlf-peer/templates/deployment.yaml
  stable/hlf-peer/templates/service.yaml
  stable/hlf-peer/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#23754 [stable/hlf-ord] Fix metrics configuration
  stable/hlf-ord/Chart.yaml
  stable/hlf-ord/README.md
  stable/hlf-ord/templates/configmap--ord.yaml
  stable/hlf-ord/templates/deployment.yaml
  stable/hlf-ord/templates/service.yaml
  stable/hlf-ord/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#23681 [incubator/jenkins-operator]: Deprecate the chart
  incubator/jenkins-operator/Chart.yaml
  incubator/jenkins-operator/README.md
  incubator/jenkins-operator/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21559 [stable/zeppelin] Zeppelin uses latest api versions
  stable/zeppelin/Chart.yaml
  stable/zeppelin/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23755 [stable/selenium]: Add volumes to firefox pods
  stable/selenium/Chart.yaml
  stable/selenium/README.md
  stable/selenium/templates/firefox-daemonset.yaml
  stable/selenium/templates/firefox-deployment.yaml
  stable/selenium/templates/firefoxDebug-daemonset.yaml
  stable/selenium/templates/firefoxDebug-deployment.yaml
  stable/selenium/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#23762 [stable/oauth2-proxy] Quote ingress host as it may contain special char
  stable/oauth2-proxy/Chart.yaml
  stable/oauth2-proxy/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23735 [stable/airflow] release 7.8.0
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/UPGRADE.md
  stable/airflow/templates/scheduler/scheduler-deployment.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#23773 [stable/gitlab-ee] Removing the logo as it is not accessible
  stable/gitlab-ee/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#23772 [stable/gitlab-ce] Removing the icon as it is not accessible
  stable/gitlab-ce/Chart.yaml
Labels: Contribution Allowed, approved, size/XS

#23780 [stable/gocd] Deprecate stable gocd helm chart
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/README.md
Labels: Contribution Allowed, approved, lgtm, size/M

#23710 [stable/fluent-bit] Configurable test images
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/tests/test.yaml
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23778 [incubator/azuremonitor-containers] updates for agent release ciprod09162020 & win-ciprod09162020
  incubator/azuremonitor-containers/Chart.yaml
  incubator/azuremonitor-containers/templates/omsagent-arc-k8s-crd.yaml
  incubator/azuremonitor-containers/templates/omsagent-daemonset-windows.yaml
  incubator/azuremonitor-containers/templates/omsagent-rbac.yaml
  incubator/azuremonitor-containers/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#23748 [stable/airflow] explicitly allow event watching
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/UPGRADE.md
  stable/airflow/templates/rbac/airflow-role.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#23781 [incubator/buzzfeed-sso] Fix ingress template
  incubator/buzzfeed-sso/Chart.yaml
  incubator/buzzfeed-sso/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23593 stable/kafka-manager
  stable/kafka-manager/Chart.yaml
  stable/kafka-manager/requirements.lock
  stable/kafka-manager/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23800 [stable/gocd] Bump up GoCD Version to 20.8.0
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#23485 [incubator/druid] overlord is broken when gCloudStorage.enabled is true (#23484)
  incubator/druid/Chart.yaml
  incubator/druid/templates/overlord/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23805 [incubator/druid] Add asdf2014 to OWNERS
  incubator/druid/Chart.yaml
  incubator/druid/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23813 [stable/prometheus-pushgateway] Fix typo
  stable/prometheus-pushgateway/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#23563 [stable/ignite] add priorityClassName support
  stable/ignite/Chart.yaml
  stable/ignite/README.md
  stable/ignite/templates/stateful-set.yaml
  stable/ignite/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23812 [incubator/azuremonitor-containers] updates for hotfix agent release ciprod09252020 & win-ciprod09252020
  incubator/azuremonitor-containers/Chart.yaml
  incubator/azuremonitor-containers/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23818 [stable/airflow] release 7.10.0
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/UPGRADE.md
  stable/airflow/templates/_helpers.tpl
  stable/airflow/templates/config/configmap-env.yaml
  stable/airflow/templates/config/configmap-scripts.yaml
  stable/airflow/templates/config/configmap-variables-pools.yaml
  stable/airflow/templates/flower/flower-deployment.yaml
  stable/airflow/templates/flower/flower-ingress.yaml
  stable/airflow/templates/flower/flower-service.yaml
  stable/airflow/templates/rbac/airflow-serviceaccount.yaml
  stable/airflow/templates/scheduler/scheduler-deployment.yaml
  stable/airflow/templates/webserver/webserver-deployment.yaml
  stable/airflow/templates/webserver/webserver-ingress.yaml
  stable/airflow/templates/webserver/webserver-prometheus-rule.yaml
  stable/airflow/templates/webserver/webserver-service-monitor.yaml
  stable/airflow/templates/webserver/webserver-service.yaml
  stable/airflow/templates/worker/worker-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/L

#23561 [incubator/druid] Add securityContext and fix local storage mounting path
  incubator/druid/Chart.yaml
  incubator/druid/README.md
  incubator/druid/templates/historical/statefulset.yaml
  incubator/druid/templates/middleManager/statefulset.yaml
  incubator/druid/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23751 [stable/airflow] remove maver1ck from OWNERS
  stable/airflow/Chart.yaml
  stable/airflow/OWNERS
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS
