Repository helm/charts, pull requests merged in 2020-10, with the labels that each got.

#23826 [stable/node-problem-detector] Customize rollout strategy
  stable/node-problem-detector/Chart.yaml
  stable/node-problem-detector/README.md
  stable/node-problem-detector/templates/daemonset.yaml
  stable/node-problem-detector/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#23659 [stable/coredns] Let externalIPs be configurable
  stable/coredns/Chart.yaml
  stable/coredns/README.md
  stable/coredns/templates/service.yaml
  stable/coredns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23802 [stable/airflow] Adding airflow scheduler existing secret connections option
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/UPGRADE.md
  stable/airflow/templates/config/secret-connections.yaml
  stable/airflow/templates/scheduler/scheduler-deployment.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#23841 [stable/atlantis] deprecating chart
  stable/atlantis/Chart.yaml
  stable/atlantis/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#23843 [stable/airflow] release 7.11.1
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/UPGRADE.md
  stable/airflow/templates/config/secret-connections.yaml
  stable/airflow/templates/pvc-logs.yaml
  stable/airflow/templates/pvc.yaml
  stable/airflow/templates/scheduler/scheduler-deployment.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/L

#23810 [stable/chartmuseum] Add runAsNonRoot, supplementalGroups and containerSecurityContext as security options
  stable/chartmuseum/Chart.yaml
  stable/chartmuseum/README.md
  stable/chartmuseum/templates/deployment.yaml
  stable/chartmuseum/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23844 [stable/kibana] deprecating kibana chart
  stable/kibana/Chart.yaml
  stable/kibana/README.md
  stable/kibana/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, size/S

#23851 [stable/airflow] improve docs
  stable/airflow/Chart.yaml
  stable/airflow/README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/L

#23855 [stable/atlantis] fix typo in chart.yaml
  stable/atlantis/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#23858 [stable/airflow] remove newline from connections secret name
  stable/airflow/Chart.yaml
  stable/airflow/templates/scheduler/scheduler-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#23866 [stable/instana-agent] Chart version 1.0.31
  stable/instana-agent/Chart.yaml
  stable/instana-agent/README.md
  stable/instana-agent/templates/configmap.yaml
  stable/instana-agent/templates/daemonset.yaml
  stable/instana-agent/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#23865 [stable/gangway] Add optional serviceAccount for gangway chart
  stable/gangway/Chart.yaml
  stable/gangway/README.md
  stable/gangway/templates/deployment.yaml
  stable/gangway/templates/serviceAccount.yaml
  stable/gangway/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#23876 [incubator/sparkoperator] fixes ISSUE-23875
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/README.md
  incubator/sparkoperator/templates/crd-cleanup-job.yaml
  incubator/sparkoperator/templates/webhook-cleanup-job.yaml
  incubator/sparkoperator/templates/webhook-init-job.yaml
  incubator/sparkoperator/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#23882 [stable/airflow] improve docs
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/L

#23795 [incubator/rundeck] Make "data" volume configurable from values file.
  incubator/rundeck/Chart.yaml
  incubator/rundeck/templates/deployment.yaml
  incubator/rundeck/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23887 [incubator/sparkoperator] fix invalid webhook init job
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/templates/webhook-init-job.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#23895 [stable/instana-agent] Chart version 1.0.32
  stable/instana-agent/Chart.yaml
  stable/instana-agent/README.md
  stable/instana-agent/templates/daemonset.yaml
  stable/instana-agent/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#23834 [stable/selenium] Enabled use of runAsDaemonSet when scheduling a node firefoxDebug Pod
  stable/selenium/Chart.yaml
  stable/selenium/templates/firefoxDebug-daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23867 [stable/airflow] provide additional labels configuration
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/UPGRADE.md
  stable/airflow/templates/flower/flower-ingress.yaml
  stable/airflow/templates/webserver/webserver-ingress.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#23903 [stable/metabase] Allow MAX_SESSION_AGE and MB_SESSION_COOKIES to be set from values.yaml
  stable/metabase/Chart.yaml
  stable/metabase/README.md
  stable/metabase/templates/deployment.yaml
  stable/metabase/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23915 [stable/airflow] remove newlines in connections[].extra
  stable/airflow/Chart.yaml
  stable/airflow/templates/config/secret-connections.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#23901 [stable/vsphere-cpi] Fix failing installation when mapping values are specified
  stable/vsphere-cpi/Chart.yaml
  stable/vsphere-cpi/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23873 [stable/dex] Add tolerations, affinity and nodeSelector to grpc-certs/web-certs jobs
  stable/dex/Chart.yaml
  stable/dex/README.md
  stable/dex/templates/job-grpc-certs.yaml
  stable/dex/templates/job-web-certs.yaml
  stable/dex/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#23923 [stable/karma] upgrade to v0.72
  stable/karma/Chart.yaml
  stable/karma/README.md
  stable/karma/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#23921 GH Actions to automate gh-pages
  .github/workflows/sync-readmes.yaml
  .github/workflows/sync-repos.yaml
  incubator/README.md
  stable/README.md
Labels: Contribution Allowed, approved, lgtm, size/L

#23925 [stable/spark-history-server] Add support for default account and Workload Identity when accessing GCS backend
  stable/spark-history-server/Chart.yaml
  stable/spark-history-server/README.md
  stable/spark-history-server/templates/deployment.yaml
  stable/spark-history-server/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#23920 [stable/stolon] Make STKEEPER_PG_LISTEN_ADDRESS configurable
  stable/stolon/Chart.yaml
  stable/stolon/templates/keeper-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23922 Karma pod labels and annotations
  stable/karma/Chart.yaml
  stable/karma/README.md
  stable/karma/templates/deployment.yaml
  stable/karma/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23902 [incubator/druid] Add missing ingress.yaml to druid router
  incubator/druid/Chart.yaml
  incubator/druid/templates/router/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test

#23919 [stable/kuberhealthy] Deprecate chart
  stable/kuberhealthy/Chart.yaml
  stable/kuberhealthy/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#23927 [stable/airflow] create flower oauthDomains config
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/UPGRADE.md
  stable/airflow/templates/flower/flower-deployment.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#23322 [stable/percona-xtradb-cluster] Add resources value to init containers
  stable/percona-xtradb-cluster/Chart.yaml
  stable/percona-xtradb-cluster/README.md
  stable/percona-xtradb-cluster/templates/statefulset.yaml
  stable/percona-xtradb-cluster/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23933 [incubator/kube-downscaler] - Add priorityClassName and update image tag
  incubator/kube-downscaler/Chart.yaml
  incubator/kube-downscaler/README.md
  incubator/kube-downscaler/templates/deployment.yaml
  incubator/kube-downscaler/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23937 [stable/traefik] Update cloudflare environment variables
  stable/traefik/Chart.yaml
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#23645 [stable/rocketchat] Ingress tls secretName only if configured
  stable/rocketchat/Chart.yaml
  stable/rocketchat/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23951 [stable/airflow] remove trailing newlines
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/templates/config/configmap-env.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#23941 [stable/traefik] Update traefik version from 1.7.24 to 1.7.25
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23948 [stable/instana-agent] Chart version 1.0.33
  stable/instana-agent/Chart.yaml
  stable/instana-agent/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#23936 [stable/sealed-secrets] Add Prometheus + Grafana monitoring resources
  stable/sealed-secrets/Chart.yaml
  stable/sealed-secrets/README.md
  stable/sealed-secrets/dashboards/sealed-secrets-controller.json
  stable/sealed-secrets/templates/configmap-dashboards.yaml
  stable/sealed-secrets/templates/servicemonitor.yaml
  stable/sealed-secrets/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#23840 [mysqldump] deprecate mysqldump chart
  stable/mysqldump/Chart.yaml
  stable/mysqldump/README.md
  stable/mysqldump/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, size/S

#23954 Making the deprecation notice more prominent
  README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#23960 [stable/traefik] Update traefik version from 1.7.25 to 1.7.26
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23827 [stable/chaoskube] Implement filter by Kind feature for chaoskube deployment.
  stable/chaoskube/Chart.yaml
  stable/chaoskube/README.md
  stable/chaoskube/templates/deployment.yaml
  stable/chaoskube/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23972 [incubator/druid] update chart repo dependency references
  incubator/druid/Chart.yaml
  incubator/druid/requirements.lock
  incubator/druid/requirements.yaml
  test/ct.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#23976 Updating the README to the new repo locations
  README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#23978 [incubator/patroni] update chart repo dependency references
  incubator/patroni/Chart.yaml
  incubator/patroni/requirements.lock
  incubator/patroni/requirements.yaml
Labels: Contribution Allowed, approved, lgtm

#23979 [incubator/schema-registry] update chart repo dependency references
  incubator/schema-registry/Chart.yaml
  incubator/schema-registry/requirements.lock
  incubator/schema-registry/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#23983 [stable/cloudserver] update chart repo dependency references
  stable/cloudserver/Chart.yaml
  stable/cloudserver/requirements.lock
  stable/cloudserver/requirements.yaml
Labels: Contribution Allowed, approved, size/S

#23977 [incubator/kafka] update chart repo dependency references
  incubator/kafka/Chart.yaml
  incubator/kafka/requirements.lock
  incubator/kafka/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#23980 [incubator/solr] update chart repo dependency references
  incubator/solr/Chart.yaml
  incubator/solr/requirements.lock
  incubator/solr/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#23964 DEPRECATED [incubator/haproxy-ingress] deprecation notice
  incubator/haproxy-ingress/Chart.yaml
  incubator/haproxy-ingress/README.md
  incubator/haproxy-ingress/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23797 [stable/coredns] Version bump to 1.7.1
  stable/coredns/Chart.yaml
  stable/coredns/README.md
  stable/coredns/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#23975 stable/sealed-secrets Upgrade version of sealed-secrets to v0.13.1
  stable/sealed-secrets/Chart.yaml
  stable/sealed-secrets/README.md
  stable/sealed-secrets/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23981 [stable/airflow] update chart repo dependency references
  stable/airflow/Chart.yaml
  stable/airflow/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#23984 [stable/elastic-stack] update chart repo dependency references
  stable/elastic-stack/Chart.yaml
  stable/elastic-stack/requirements.lock
  stable/elastic-stack/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#23986 [stable/graylog] update chart repo dependency references
  stable/graylog/Chart.yaml
  stable/graylog/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#23987 [stable/hackmd] update chart repo dependency references
  stable/hackmd/Chart.yaml
  stable/hackmd/requirements.lock
  stable/hackmd/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#23988 [stable/hlf-ca] update chart repo dependency references
  stable/hlf-ca/Chart.yaml
  stable/hlf-ca/requirements.lock
  stable/hlf-ca/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#23989 [stable/hubot] update chart repo dependency references
  stable/hubot/Chart.yaml
  stable/hubot/requirements.lock
  stable/hubot/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#23990 [stable/janusgraph] update chart repo dependency references
  stable/janusgraph/Chart.yaml
  stable/janusgraph/requirements.yaml
Labels: Contribution Allowed, approved, lgtm

#23991 [stable/kafka-manager] update chart repo dependency references
  stable/kafka-manager/Chart.yaml
  stable/kafka-manager/requirements.lock
  stable/kafka-manager/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#23992 [stable/kube-ops-view] update chart repo dependency references
  stable/kube-ops-view/Chart.yaml
  stable/kube-ops-view/requirements.lock
  stable/kube-ops-view/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#23994 [stable/mcrouter] update chart repo dependency references
  stable/mcrouter/Chart.yaml
  stable/mcrouter/requirements.lock
  stable/mcrouter/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#23996 [stable/quassel] update chart repo dependency references
  stable/quassel/Chart.yaml
  stable/quassel/requirements.lock
  stable/quassel/requirements.yaml
Labels: Contribution Allowed, approved, lgtm

#23997 [stable/rocketchat] update chart repo dependency references
  stable/rocketchat/Chart.yaml
  stable/rocketchat/requirements.lock
  stable/rocketchat/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#24000 [stable/sentry] update chart repo dependency references
  stable/sentry/Chart.yaml
  stable/sentry/requirements.lock
  stable/sentry/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#24001 [stable/spinnaker] update chart repo dependency references
  stable/spinnaker/Chart.yaml
  stable/spinnaker/requirements.lock
  stable/spinnaker/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#24004 [stable/vault-operator] update chart repo dependency references
  stable/vault-operator/Chart.yaml
  stable/vault-operator/requirements.lock
  stable/vault-operator/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, size/S
