Repository helm/charts, pull requests merged in 2020-02, with the labels that each got.

#20456 [stable/metabase] allow setting jetty options
  stable/metabase/Chart.yaml
  stable/metabase/README.md
  stable/metabase/templates/deployment.yaml
  stable/metabase/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20477 [stable/gocd] Quote ingress host
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
  stable/gocd/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20490 [stable/grafana] Fix a typo in the Grafana chart notes
  stable/grafana/Chart.yaml
  stable/grafana/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20475 [stable/metabase] interpolate liveness and readiness probes
  stable/metabase/Chart.yaml
  stable/metabase/README.md
  stable/metabase/templates/deployment.yaml
  stable/metabase/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#20478 [stable/rabbitmq] Add PrometheusRule.
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/prometheusrule.yaml
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#20437 [stable/redis] Allow DNS egress to resolve hostnames
  stable/redis/Chart.yaml
  stable/redis/templates/networkpolicy.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20409 [stable/prometheus-blackbox-exporter] add "allowIcmp" setting
  stable/prometheus-blackbox-exporter/Chart.yaml
  stable/prometheus-blackbox-exporter/README.md
  stable/prometheus-blackbox-exporter/ci/icmp-values.yaml
  stable/prometheus-blackbox-exporter/templates/deployment.yaml
  stable/prometheus-blackbox-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20517 [stable/spring-cloud-data-flow] Update to new SCDF version 2.4.0
  stable/spring-cloud-data-flow/Chart.yaml
  stable/spring-cloud-data-flow/README.md
  stable/spring-cloud-data-flow/requirements.lock
  stable/spring-cloud-data-flow/requirements.yaml
  stable/spring-cloud-data-flow/templates/_helpers.tpl
  stable/spring-cloud-data-flow/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#20507 [stable/atlantis] update alantis version
  stable/atlantis/Chart.yaml
  stable/atlantis/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19317 [stable/prometheus-redis-exporter] Update image for exporter
  stable/prometheus-redis-exporter/Chart.yaml
  stable/prometheus-redis-exporter/README.md
  stable/prometheus-redis-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20523 [stable/moodle] Set MOODLE_SKIP_INSTALL environment variable
  stable/moodle/Chart.yaml
  stable/moodle/README.md
  stable/moodle/templates/deployment.yaml
  stable/moodle/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#20526 [stable/seq] use deployment strategy `Recreate`
  stable/seq/Chart.yaml
  stable/seq/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#20530 [stable/pgadmin] removed abundance curly bracket
  stable/pgadmin/Chart.yaml
  stable/pgadmin/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19260 [stable/nfs-server-provisioner] New nfs-provisioner with NFSv3 support
  stable/nfs-server-provisioner/Chart.yaml
  stable/nfs-server-provisioner/OWNERS
  stable/nfs-server-provisioner/README.md
  stable/nfs-server-provisioner/templates/service.yaml
  stable/nfs-server-provisioner/templates/statefulset.yaml
  stable/nfs-server-provisioner/templates/storageclass.yaml
  stable/nfs-server-provisioner/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/L

#20493 [stable/superset] Update Maintainers List
  stable/superset/Chart.yaml
  stable/superset/OWNERS
  stable/superset/ci/superset_security-values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20533 Rr/strategy
  stable/pgadmin/Chart.yaml
  stable/pgadmin/README.md
  stable/pgadmin/templates/deployment.yaml
  stable/pgadmin/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20531 [stable/testlink] add service annotations
  stable/testlink/Chart.yaml
  stable/testlink/README.md
  stable/testlink/templates/_helpers.tpl
  stable/testlink/templates/svc.yaml
  stable/testlink/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#20538 [grafana] update grafana sidecar to 0.1.75
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#20518 [stable/nginx-ingress] allow clusterIP values to be set empty
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-metrics-service.yaml
  stable/nginx-ingress/templates/controller-service.yaml
  stable/nginx-ingress/templates/controller-webhook-service.yaml
  stable/nginx-ingress/templates/default-backend-service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20543 [stable/kube-state-metrics] Version bump to 1.9.4
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
  stable/kube-state-metrics/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#20529 [stable/nginx-ingress] Add sessionAffinity to controller service
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-service.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20540 [stable/pgadmin] abundance curly bracket
  stable/pgadmin/Chart.yaml
  stable/pgadmin/README.md
  stable/pgadmin/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#20228 [stable/airflow] fix(requirements): updated versions
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/requirements.lock
  stable/airflow/requirements.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#20550 [stable/graylog] Allow provisioner job to run as using the same ServiceAccount
  stable/graylog/Chart.yaml
  stable/graylog/README.md
  stable/graylog/templates/job.yaml
  stable/graylog/templates/role.yaml
  stable/graylog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20479 [stable/postgresql]: auto features for hardened OpenShift clusters
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#20425 [stable/cockroachdb] Allow TLS secrets for certificates
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/README.md
  stable/cockroachdb/templates/clusterrole.yaml
  stable/cockroachdb/templates/clusterrolebinding.yaml
  stable/cockroachdb/templates/job.init.yaml
  stable/cockroachdb/templates/role.yaml
  stable/cockroachdb/templates/statefulset.yaml
  stable/cockroachdb/templates/tests/client.yaml
  stable/cockroachdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#20558 [stable/grafana] Make watch METHOD of dashboard sidecar configurable
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/_pod.tpl
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20567 [stable/cockroachdb]: Update version to v19.2.3
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/README.md
  stable/cockroachdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20570 Fixed validation
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/README.md
  incubator/sparkoperator/templates/crds.yaml
Labels: Contribution Allowed, approved, lgtm, size/XXL

#20576 [stable/newrelic-infrastructure] Add missing cluster role permissions for secrets
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/templates/clusterrole.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#20066 Fix typo
  stable/datadog/Chart.yaml
  stable/datadog/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20506 [stable/mongodb-replicaset] Add feature to annotate resulting statefulset
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/README.md
  stable/mongodb-replicaset/templates/mongodb-statefulset.yaml
  stable/mongodb-replicaset/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20415 [stable/drone] add logs, database and private repo pull-secret configs
  stable/drone/Chart.yaml
  stable/drone/README.md
  stable/drone/templates/deployment-server.yaml
  stable/drone/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#20580 [stable/sealed-secrets] Support specifying pod annotations.
  stable/sealed-secrets/Chart.yaml
  stable/sealed-secrets/README.md
  stable/sealed-secrets/templates/deployment.yaml
  stable/sealed-secrets/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20590 [stable/datadog] clarify that nonLocalTraffic must be set to true to use APM
  stable/datadog/Chart.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#20280 [stable/oauth2-proxy] Add htpasswd file checksum to annotations
  stable/oauth2-proxy/Chart.yaml
  stable/oauth2-proxy/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20589 [stable/elasticsearch-exporter] Feature flap the flag es.uri
  stable/elasticsearch-exporter/Chart.yaml
  stable/elasticsearch-exporter/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20591 [stable/drone] add back support for ingress in k8s < 1.14
  stable/drone/Chart.yaml
  stable/drone/templates/_helpers.tpl
  stable/drone/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20603 [stable/pgadmin] version 4.17 to 4.18
  stable/pgadmin/Chart.yaml
  stable/pgadmin/README.md
  stable/pgadmin/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20592 [stable/k8s-spot-rescheduler] upgrade apiVersion
  stable/k8s-spot-rescheduler/Chart.yaml
  stable/k8s-spot-rescheduler/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20488 [stable/spinnaker] Fix the wrong config path for minio image tag
  stable/spinnaker/Chart.yaml
  stable/spinnaker/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20267 [stable/jenkins] FIX #20262
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/rbac.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#20604 [stable/newrelic-infrastructure] Permissions and privileged mode additions
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/templates/clusterrole.yaml
  stable/newrelic-infrastructure/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#20588 [stable/ambassador] Add deprecation warning to helm chart
  stable/ambassador/Chart.yaml
  stable/ambassador/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#20534 [stable/collabora-code] add option to specify a path for readiness and liveness probes
  stable/collabora-code/Chart.yaml
  stable/collabora-code/README.md
  stable/collabora-code/templates/deployment.yaml
  stable/collabora-code/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#20579 [stable/metabase] Support fullnameOverride in _helpers.tpl
  stable/metabase/Chart.yaml
  stable/metabase/README.md
  stable/metabase/templates/_helpers.tpl
  stable/metabase/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20511 [incubator/cassandra] Change configOverrides to use an initContainer
  incubator/cassandra/Chart.yaml
  incubator/cassandra/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#20516 [stable/graylog] Add support for extra options in the Graylog chart
  stable/graylog/Chart.yaml
  stable/graylog/README.md
  stable/graylog/templates/_helpers.tpl
  stable/graylog/templates/configmap.yaml
  stable/graylog/templates/files-configmap.yaml
  stable/graylog/templates/ingress.yaml
  stable/graylog/templates/job.yaml
  stable/graylog/templates/master-service.yaml
  stable/graylog/templates/rolebinding.yaml
  stable/graylog/templates/secret.yaml
  stable/graylog/templates/serviceaccount.yaml
  stable/graylog/templates/statefulset.yaml
  stable/graylog/templates/tcp-service.yaml
  stable/graylog/templates/udp-service.yaml
  stable/graylog/templates/web-service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#20627 [stable/hazelcast] Adapt for Hazelcast 4.0 (#94)
  stable/hazelcast/Chart.yaml
  stable/hazelcast/templates/mancenter-statefulset.yaml
  stable/hazelcast/templates/statefulset.yaml
  stable/hazelcast/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#20637 [stable/parse] Replace stretch by buster in minideb secondary containers
  stable/parse/Chart.yaml
  stable/parse/README.md
  stable/parse/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20632 [stable/mongodb] Replace stretch by buster in minideb secondary containers
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20633 [stable/mariadb] Replace stretch by buster in minideb secondary containers
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
  stable/mariadb/values-production.yaml
  stable/mariadb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20635 [stable/rabbitmq] Replace stretch by buster in minideb secondary containers
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20636 [stable/postgresql] Replace stretch by buster in minideb secondary containers
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20634 [stable/redis] Replace stretch by buster in minideb secondary containers
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/values-production.yaml
  stable/redis/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20631 [stable/ghost] Replace stretch by buster in minideb secondary containers
  stable/ghost/Chart.yaml
  stable/ghost/README.md
  stable/ghost/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20641 [incubator/sparkoperator] Upgraded the operator version
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/README.md
  incubator/sparkoperator/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#20615 [stable/nginx-ingress] Fix typo in description of "sessionAffinity"
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20201 [stable/cockroachdb]: correct and update README
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#20616 stable/rocket.chat upgrade version to 2.4.9
  stable/rocketchat/Chart.yaml
  stable/rocketchat/README.md
  stable/rocketchat/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20651 [stable/nats] fix service templates for setting `loadBalancerIP`
  stable/nats/Chart.yaml
  stable/nats/templates/client-svc.yaml
  stable/nats/templates/cluster-svc.yaml
  stable/nats/templates/monitoring-svc.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20653 [stable/redis] fix service templates for setting `loadBalancerIP`
  stable/redis/Chart.yaml
  stable/redis/templates/metrics-svc.yaml
  stable/redis/templates/redis-with-sentinel-svc.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20642 [stable/nats] Configure number of connect retries for implicit routes
  stable/nats/Chart.yaml
  stable/nats/README.md
  stable/nats/templates/configmap.yaml
  stable/nats/values-production.yaml
  stable/nats/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20654 [stable/sealed-secrets] Update to v0.9.7
  stable/sealed-secrets/Chart.yaml
  stable/sealed-secrets/README.md
  stable/sealed-secrets/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20655 [stable/sealed-secrets] Add fsGroup for v0.9.7
  stable/sealed-secrets/Chart.yaml
  stable/sealed-secrets/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20657 [stable/lamp] Add support for new deployment and ingress APIs in Kubernetes 1.16+
  stable/lamp/Chart.yaml
  stable/lamp/templates/deployment.yaml
  stable/lamp/templates/ingress-services.yaml
  stable/lamp/templates/ingress-www.yaml
  stable/lamp/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20599 [stable/postgresql] add docs for existingSecret structure
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20607 [stable/pgadmin] Server Definitions implementation
  stable/pgadmin/Chart.yaml
  stable/pgadmin/README.md
  stable/pgadmin/templates/_helpers.tpl
  stable/pgadmin/templates/deployment.yaml
  stable/pgadmin/templates/secrets.yaml
  stable/pgadmin/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#20683 [stable/external-dns] Adapt docs to Helm 3
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20662 [stable/mongodb] Adapt docs to Helm 3
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20664 [stable/nats] Adapt docs to Helm 3
  stable/nats/Chart.yaml
  stable/nats/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20673 [stable/phpmyadmin] Adapt docs to Helm 3
  stable/phpmyadmin/Chart.yaml
  stable/phpmyadmin/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20674 [stable/postgresql] Adapt docs to Helm 3
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20676 [stable/rabbitmq] Adapt docs to Helm 3
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20677 [stable/redis] Adapt docs to Helm 3
  stable/redis/Chart.yaml
  stable/redis/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20680 [stable/testlink] Adapt docs to Helm 3
  stable/testlink/Chart.yaml
  stable/testlink/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20681 [stable/wordpress] Adapt docs to Helm 3
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
  stable/wordpress/values-production.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20682 [stable/drupal] Adapt docs to Helm 3
  stable/drupal/Chart.yaml
  stable/drupal/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20684 [stable/ghost] Adapt docs to Helm 3
  stable/ghost/Chart.yaml
  stable/ghost/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20685 [stable/jasperreports] Adapt docs to Helm 3
  stable/jasperreports/Chart.yaml
  stable/jasperreports/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20686 [stable/joomla] Adapt docs to Helm 3
  stable/joomla/Chart.yaml
  stable/joomla/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20687 [stable/kubewatch] Adapt docs to Helm 3
  stable/kubewatch/Chart.yaml
  stable/kubewatch/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20688 [stable/mariadb] Adapt docs to Helm 3
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20689 [stable/mediawiki] Adapt docs to Helm 3
  stable/mediawiki/Chart.yaml
  stable/mediawiki/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20661 [stable/dokuwiki] Adapt docs to Helm 3
  stable/dokuwiki/Chart.yaml
  stable/dokuwiki/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20663 [stable/moodle] Adapt docs to Helm 3
  stable/moodle/Chart.yaml
  stable/moodle/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20665 [stable/odoo] Adapt docs to Helm 3
  stable/odoo/Chart.yaml
  stable/odoo/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20666 [stable/opencart] Adapt docs to Helm 3
  stable/opencart/Chart.yaml
  stable/opencart/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20667 [stable/orangehrm] Adapt docs to Helm 3
  stable/orangehrm/Chart.yaml
  stable/orangehrm/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20668 [stable/osclass] Adapt docs to Helm 3
  stable/osclass/Chart.yaml
  stable/osclass/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20669 [stable/owncloud] Adapt docs to Helm 3
  stable/owncloud/Chart.yaml
  stable/owncloud/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20670 [stable/parse] Adapt docs to Helm 3
  stable/parse/Chart.yaml
  stable/parse/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20671 [stable/phabricator] Adapt docs to Helm 3
  stable/phabricator/Chart.yaml
  stable/phabricator/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20672 [stable/phpbb] Adapt docs to Helm 3
  stable/phpbb/Chart.yaml
  stable/phpbb/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20675 [stable/prestashop] Adapt docs to Helm 3
  stable/prestashop/Chart.yaml
  stable/prestashop/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20678 [stable/redmine] Adapt docs to Helm 3
  stable/redmine/Chart.yaml
  stable/redmine/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20679 [stable/suitecrm] Adapt docs to Helm 3
  stable/suitecrm/Chart.yaml
  stable/suitecrm/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20690 [stable/sealed-secrets] Add priorityClassName to sealed-secrets
  stable/sealed-secrets/Chart.yaml
  stable/sealed-secrets/README.md
  stable/sealed-secrets/templates/deployment.yaml
  stable/sealed-secrets/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20612 [stable/vsphere-cpi] Improved Security for vSphere CPI
  stable/vsphere-cpi/Chart.yaml
  stable/vsphere-cpi/README.md
  stable/vsphere-cpi/templates/common.yaml
  stable/vsphere-cpi/templates/configmap.yaml
  stable/vsphere-cpi/templates/daemonset.yaml
  stable/vsphere-cpi/templates/ingress.yaml
  stable/vsphere-cpi/templates/podsecuritypolicy.yaml
  stable/vsphere-cpi/templates/role-binding.yaml
  stable/vsphere-cpi/templates/secret.yaml
  stable/vsphere-cpi/templates/service-account.yaml
  stable/vsphere-cpi/templates/service.yaml
  stable/vsphere-cpi/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#20524 [stable/anchore-engine] added default admin password helper
  stable/anchore-engine/Chart.yaml
  stable/anchore-engine/templates/_helpers.tpl
  stable/anchore-engine/templates/api_deployment.yaml
  stable/anchore-engine/templates/secrets.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20628 [stable/opa] Add affinity settings to OPA deployment
  stable/opa/Chart.yaml
  stable/opa/README.md
  stable/opa/templates/deployment.yaml
  stable/opa/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#20322 [stable/elasticsearch-exporter] Allow PrometheusRules to be templated.
  stable/elasticsearch-exporter/Chart.yaml
  stable/elasticsearch-exporter/README.md
  stable/elasticsearch-exporter/templates/prometheusrule.yaml
  stable/elasticsearch-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#20650 [stable/graylog] Enable support for listening on HTTPS
  stable/graylog/Chart.yaml
  stable/graylog/README.md
  stable/graylog/templates/_helpers.tpl
  stable/graylog/templates/configmap.yaml
  stable/graylog/templates/headless-service.yaml
  stable/graylog/templates/master-service.yaml
  stable/graylog/templates/statefulset.yaml
  stable/graylog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#20652 [stable/redis] added PV selectors
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/templates/redis-master-statefulset.yaml
  stable/redis/templates/redis-slave-statefulset.yaml
  stable/redis/values-production.yaml
  stable/redis/values.schema.json
  stable/redis/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#20583 [stable/fluent-bit] Add tag to kubernetes-audit in fluent-bit chart.
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/config.yaml
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20692 [stable/newrelic-infrastructure] Add secure port and ksm label config options
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/README.md
  stable/newrelic-infrastructure/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#20554 [stable/fluentd] Fix manifest errors when using autoscaling + persistence
  stable/fluentd/Chart.yaml
  stable/fluentd/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20702 [incubator/sparkoperator] Allow leader election to be customized
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/README.md
  incubator/sparkoperator/ci/test-values.yaml
  incubator/sparkoperator/templates/_helpers.tpl
  incubator/sparkoperator/templates/spark-operator-deployment.yaml
  incubator/sparkoperator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#20706 [stable/instana-agent] Chart version 1.0.22
  stable/instana-agent/Chart.yaml
  stable/instana-agent/README.md
  stable/instana-agent/templates/daemonset.yaml
  stable/instana-agent/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#20717 [stable/redis] allow all pods from chart to talk to eachother
  stable/redis/Chart.yaml
  stable/redis/templates/networkpolicy.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#20649 [stable/minio] Set service name to HTTP/HTTPS rather than Service
  stable/minio/Chart.yaml
  stable/minio/templates/deployment.yaml
  stable/minio/templates/service.yaml
  stable/minio/templates/servicemonitor.yaml
  stable/minio/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#20725 [stable/nginx-ingress] Apply default backend service command line argument if one is configured
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/templates/controller-daemonset.yaml
  stable/nginx-ingress/templates/controller-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20630 [stable/elasticsearch] Update to 6.8.6 + Fix plugin install initcontainer which would fail if plugin already exists.
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/templates/_helpers.tpl
  stable/elasticsearch/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#20660 Replaced broken link in unbound readme
  stable/unbound/Chart.yaml
  stable/unbound/README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#20716 [stable/openebs] Update the detail for get support
  stable/openebs/Chart.yaml
  stable/openebs/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#20704 [stable/external-dns] Add support for the TransIP provider
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/_helpers.tpl
  stable/external-dns/templates/deployment.yaml
  stable/external-dns/templates/secret.yaml
  stable/external-dns/values-production.yaml
  stable/external-dns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#20730 [stable/hazelcast] Add option for configuring MC_CONTEXT_PATH
  stable/hazelcast/Chart.yaml
  stable/hazelcast/README.adoc
  stable/hazelcast/templates/NOTES.txt
  stable/hazelcast/templates/mancenter-statefulset.yaml
  stable/hazelcast/templates/tests/test-management-center.yaml
  stable/hazelcast/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#20762 [stable/hazelcast] Clean up context path (#99)
  stable/hazelcast/Chart.yaml
  stable/hazelcast/templates/NOTES.txt
  stable/hazelcast/templates/tests/test-management-center.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#20760 [stable/influxdb]Fix indentations
  stable/influxdb/Chart.yaml
  stable/influxdb/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20698 [stable/cockroachdb]: Update version to v19.2.4
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/README.md
  stable/cockroachdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19699 [incubator/schema-registry] Template health check
  incubator/schema-registry/Chart.yaml
  incubator/schema-registry/templates/deployment.yaml
  incubator/schema-registry/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#20763 [stable/unifi] add deploymentannotations, bump chart version
  stable/unifi/Chart.yaml
  stable/unifi/README.md
  stable/unifi/templates/deployment.yaml
  stable/unifi/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20751 [stable/pgadmin] update api versions
  stable/pgadmin/Chart.yaml
  stable/pgadmin/templates/_helpers.tpl
  stable/pgadmin/templates/deployment.yaml
  stable/pgadmin/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20770 [stable/influxdb] labels, serviceaccount and remove clusterIP specificity
  stable/influxdb/Chart.yaml
  stable/influxdb/README.md
  stable/influxdb/templates/_helpers.tpl
  stable/influxdb/templates/backup-cronjob.yaml
  stable/influxdb/templates/config.yaml
  stable/influxdb/templates/ingress.yaml
  stable/influxdb/templates/init-config.yaml
  stable/influxdb/templates/meta-config.yaml
  stable/influxdb/templates/meta-service.yaml
  stable/influxdb/templates/meta-statefulset.yaml
  stable/influxdb/templates/post-install-set-auth.yaml
  stable/influxdb/templates/secret.yaml
  stable/influxdb/templates/service.yaml
  stable/influxdb/templates/serviceaccount.yaml
  stable/influxdb/templates/statefulset.yaml
  stable/influxdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#20776 [stable/influxdb] fix: labels
  stable/influxdb/Chart.yaml
  stable/influxdb/templates/backup-cronjob.yaml
  stable/influxdb/templates/meta-statefulset.yaml
  stable/influxdb/templates/post-install-set-auth.yaml
  stable/influxdb/templates/service.yaml
  stable/influxdb/templates/serviceaccount.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20764 [stable/nginx-ingress] fix psp for daemonsets with userHostPort
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/templates/controller-psp.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20595 [stable/external-dns] Add triggerLoopOnEvent option to trigger sync loop on create/update/delete events.
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/deployment.yaml
  stable/external-dns/values-production.yaml
  stable/external-dns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20773 [stable/openebs] update charts to 1.7.0 release
  stable/openebs/Chart.yaml
  stable/openebs/README.md
  stable/openebs/templates/daemonset-ndm.yaml
  stable/openebs/templates/deployment-maya-apiserver.yaml
  stable/openebs/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#20780 [stable/Influxdb] make mounting of GSA key optional for backups to GCS
  stable/influxdb/Chart.yaml
  stable/influxdb/OWNERS
  stable/influxdb/templates/backup-cronjob.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20781 [stable/influxdb] use named ports
  stable/influxdb/Chart.yaml
  stable/influxdb/templates/meta-service.yaml
  stable/influxdb/templates/service.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#20787 [stable/influxdb] Refactor configmap by using implicit default values
  stable/influxdb/Chart.yaml
  stable/influxdb/templates/NOTES.txt
  stable/influxdb/templates/backup-cronjob.yaml
  stable/influxdb/templates/config.yaml
  stable/influxdb/templates/configmap.yaml
  stable/influxdb/templates/meta-configmap.yaml
  stable/influxdb/templates/meta-service.yaml
  stable/influxdb/templates/meta-statefulset.yaml
  stable/influxdb/templates/post-install-set-auth.yaml
  stable/influxdb/templates/service.yaml
  stable/influxdb/templates/statefulset.yaml
  stable/influxdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XL

#20768 [stable/fluent-bit] update to fluent-bit v1.3.7
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#20792 [stable/telegraf] Add nodeSelector support
  stable/telegraf/Chart.yaml
  stable/telegraf/templates/deployment.yaml
  stable/telegraf/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#20794 [stable/minecraft] Add failure/successThreshold and timeoutSeconds conf
  stable/minecraft/Chart.yaml
  stable/minecraft/templates/deployment.yaml
  stable/minecraft/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20744 [stable/datadog] add ability to use a configmap to provide the
  stable/datadog/Chart.yaml
  stable/datadog/templates/cluster-agent-config-configmap.yaml
  stable/datadog/templates/cluster-agent-deployment.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#20766 [stable/minio] Fixes Post-install-create-bucket-job fails on openshift
  stable/minio/Chart.yaml
  stable/minio/templates/_helper_create_bucket.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20788 [stable/influxdb] Use include function instead of template.
  stable/influxdb/Chart.yaml
  stable/influxdb/templates/NOTES.txt
  stable/influxdb/templates/backup-cronjob.yaml
  stable/influxdb/templates/ingress.yaml
  stable/influxdb/templates/post-install-set-auth.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#20799 [stable/minio]: update default images to latest
  stable/minio/Chart.yaml
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20784 [stable/graylog]: use correct object path for existing root secret
  stable/graylog/Chart.yaml
  stable/graylog/templates/job.yaml
  stable/graylog/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20732 [bitnami/redis] Use buster in CI
  stable/redis/Chart.yaml
  stable/redis/ci/insecure-sentinel-values.yaml
  stable/redis/ci/production-sentinel-values.yaml
  stable/redis/ci/production-values.yaml
  stable/redis/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20047 [stable/spinnaker] Template Annotations for Spinnaker HAL Cleanup Job
  stable/spinnaker/Chart.yaml
  stable/spinnaker/templates/hooks/cleanup.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20765 [stable/newrelic-infrastructure] Upgrade k8s integration with new configuration option for integrations configuration
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/README.md
  stable/newrelic-infrastructure/templates/configmap.yaml
  stable/newrelic-infrastructure/templates/daemonset.yaml
  stable/newrelic-infrastructure/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#20759 [stable/minio] exclude job from service selector
  stable/minio/Chart.yaml
  stable/minio/templates/post-install-create-bucket-job.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20750 [stable/prometheus-adapter] Upgrading to v0.6.0
  stable/prometheus-adapter/Chart.yaml
  stable/prometheus-adapter/README.md
  stable/prometheus-adapter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20800 [stable/influxdb] probes
  stable/influxdb/Chart.yaml
  stable/influxdb/templates/meta-statefulset.yaml
  stable/influxdb/templates/statefulset.yaml
  stable/influxdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#20775 [stable/kapacitor] Add myself as a maintainer for kapacitor.
  stable/kapacitor/Chart.yaml
  stable/kapacitor/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20812 [stable/influxdb] Update image
  stable/influxdb/Chart.yaml
  stable/influxdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#20719 [stable/fluent-bit] Add Logstash_Prefix_Key as an optional parameter
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/config.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20819 stable/prometheus-adapter: pass empty array if rules are empty (#19616)
  stable/prometheus-adapter/Chart.yaml
  stable/prometheus-adapter/templates/custom-metrics-configmap.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20391 [stable/rabbitmq-ha] Add support for additional pod affinity settings.
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/templates/statefulset.yaml
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S
