Repository helm/charts, pull requests merged in 2020-01, with the labels that each got.

#18670 [incubator/fluentd-cloudwatch] Add configurable volumes and volumeMounts
  incubator/fluentd-cloudwatch/Chart.yaml
  incubator/fluentd-cloudwatch/README.md
  incubator/fluentd-cloudwatch/templates/daemonset.yaml
  incubator/fluentd-cloudwatch/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19803 [stable/kube-ops-view] Upgrade redis and also enable when testing
  stable/kube-ops-view/Chart.yaml
  stable/kube-ops-view/ci/redis-enabled-values.yaml
  stable/kube-ops-view/requirements.lock
  stable/kube-ops-view/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#19822 [stable/minio] Enable Readiness checks for MinIO chart
  stable/minio/Chart.yaml
  stable/minio/templates/statefulset.yaml
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#19205 [stable/spinnaker] #19172 Give extra params to hal deploy apply command
  stable/spinnaker/Chart.yaml
  stable/spinnaker/README.md
  stable/spinnaker/templates/configmap/halyard-config.yaml
  stable/spinnaker/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19794 [stable/grafana] - Add allowUiUpdates for Grafana 6.5
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/configmap-dashboard-provider.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19610 [stable/pomerium] Bump pomerium image to 0.5.2
  stable/pomerium/Chart.yaml
  stable/pomerium/README.md
  stable/pomerium/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#19795 [stable/coredns] Update deprecated api version
  stable/coredns/Chart.yaml
  stable/coredns/templates/podsecuritypolicy.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19449 [stable/redmine] Redmine mail receive
  stable/redmine/Chart.yaml
  stable/redmine/README.md
  stable/redmine/templates/_helpers.tpl
  stable/redmine/templates/cronjob.yaml
  stable/redmine/templates/mail-receiver-configmap.yaml
  stable/redmine/templates/secrets.yaml
  stable/redmine/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XL

#19828 [stable/prometheus-operator] Fix wrong CRD links
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#19816 [stable/nginx-ingress] Update to stable "rbac.authorization.k8s.io/v1"
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/templates/clusterrole.yaml
  stable/nginx-ingress/templates/clusterrolebinding.yaml
  stable/nginx-ingress/templates/controller-role.yaml
  stable/nginx-ingress/templates/controller-rolebinding.yaml
  stable/nginx-ingress/templates/default-backend-role.yaml
  stable/nginx-ingress/templates/default-backend-rolebinding.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19727 [stable/spring-cloud-data-flow] Add support for restricting load bala…
  stable/spring-cloud-data-flow/Chart.yaml
  stable/spring-cloud-data-flow/README.md
  stable/spring-cloud-data-flow/templates/server-service.yaml
  stable/spring-cloud-data-flow/templates/skipper-deployment.yaml
  stable/spring-cloud-data-flow/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18986 [stable/grafana] Namespace override
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/NOTES.txt
  stable/grafana/templates/_helpers.tpl
  stable/grafana/templates/clusterrolebinding.yaml
  stable/grafana/templates/configmap-dashboard-provider.yaml
  stable/grafana/templates/configmap.yaml
  stable/grafana/templates/dashboards-json-configmap.yaml
  stable/grafana/templates/deployment.yaml
  stable/grafana/templates/headless-service.yaml
  stable/grafana/templates/ingress.yaml
  stable/grafana/templates/poddisruptionbudget.yaml
  stable/grafana/templates/podsecuritypolicy.yaml
  stable/grafana/templates/pvc.yaml
  stable/grafana/templates/role.yaml
  stable/grafana/templates/rolebinding.yaml
  stable/grafana/templates/secret-env.yaml
  stable/grafana/templates/secret.yaml
  stable/grafana/templates/service.yaml
  stable/grafana/templates/serviceaccount.yaml
  stable/grafana/templates/statefulset.yaml
  stable/grafana/templates/tests/test-configmap.yaml
  stable/grafana/templates/tests/test-podsecuritypolicy.yaml
  stable/grafana/templates/tests/test-role.yaml
  stable/grafana/templates/tests/test-rolebinding.yaml
  stable/grafana/templates/tests/test-serviceaccount.yaml
  stable/grafana/templates/tests/test.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#18990 [stable/kube-state-metrics] Namespace override
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
  stable/kube-state-metrics/templates/NOTES.txt
  stable/kube-state-metrics/templates/_helpers.tpl
  stable/kube-state-metrics/templates/clusterrolebinding.yaml
  stable/kube-state-metrics/templates/deployment.yaml
  stable/kube-state-metrics/templates/psp-clusterrolebinding.yaml
  stable/kube-state-metrics/templates/service.yaml
  stable/kube-state-metrics/templates/serviceaccount.yaml
  stable/kube-state-metrics/templates/servicemonitor.yaml
  stable/kube-state-metrics/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19829 [stable/efs-provisioner] Upgrade EFS provisioner
  stable/efs-provisioner/Chart.yaml
  stable/efs-provisioner/README.md
  stable/efs-provisioner/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19818 [stable/atlantis] Add service account annotations
  stable/atlantis/Chart.yaml
  stable/atlantis/README.md
  stable/atlantis/templates/serviceaccount.yaml
  stable/atlantis/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19838 [stable/coredns]: Fix incorrect rendering
  stable/coredns/Chart.yaml
  stable/coredns/templates/podsecuritypolicy.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19734 [stable/jenkins] copy scriptapprovals when overwriteConfig enabled
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/config.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19841 [stable/instana-agent] Chart version 1.0.21
  stable/instana-agent/Chart.yaml
  stable/instana-agent/README.md
  stable/instana-agent/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#19839 [stable/external-dns] fixes kubernetes-sigs/external-dns#1262 AWS ARN issues
  stable/external-dns/Chart.yaml
  stable/external-dns/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19601 [stable/influxdb] Set the default user from an existing secret
  stable/influxdb/Chart.yaml
  stable/influxdb/README.md
  stable/influxdb/templates/NOTES.txt
  stable/influxdb/templates/post-install-set-auth.yaml
  stable/influxdb/templates/secret.yaml
  stable/influxdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19832 [stable/redis] fix runAsUser incompatible types for comparison
  stable/redis/Chart.yaml
  stable/redis/templates/redis-master-statefulset.yaml
  stable/redis/templates/redis-slave-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19835 [stable/prometheus-operator] remove namespace from global resources
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/mutatingWebhookConfiguration.yaml
  stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/validatingWebhookConfiguration.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19588 [stable/redis-ha] Add maxclients option for sentinel configuration
  stable/redis-ha/Chart.yaml
  stable/redis-ha/templates/_configs.tpl
  stable/redis-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#19821 [stable/kong] revamp and simplify readme
  stable/kong/Chart.yaml
  stable/kong/FAQs.md
  stable/kong/README.md
  stable/kong/templates/NOTES.txt
  stable/kong/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XL

#19840 [stable/kong] 0.33: misc updates
  stable/kong/Chart.yaml
  stable/kong/FAQs.md
  stable/kong/README.md
  stable/kong/requirements.lock
  stable/kong/requirements.yaml
  stable/kong/templates/_helpers.tpl
  stable/kong/templates/controller-cluster-role.yaml
  stable/kong/templates/controller-pdb.yaml
  stable/kong/templates/controller-rbac-cluster-role-binding.yaml
  stable/kong/templates/controller-rbac-resources.yaml
  stable/kong/templates/controller-rbac-role-binding.yaml
  stable/kong/templates/controller-rbac-role.yaml
  stable/kong/templates/crd-kongconsumer.yaml
  stable/kong/templates/crd-kongcredential.yaml
  stable/kong/templates/crd-kongplugins.yaml
  stable/kong/templates/custom-resource-definitions.yaml
  stable/kong/templates/deployment.yaml
  stable/kong/templates/migrations-post-upgrade.yaml
  stable/kong/templates/migrations-pre-upgrade.yaml
  stable/kong/templates/migrations.yaml
  stable/kong/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XXL

#19852 [stable/kong] fix whitespace handling for license
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19851 [stable/spark-history-server] Remove duplicate configmap keys
  stable/spark-history-server/Chart.yaml
  stable/spark-history-server/templates/configmap.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#17071 [stable/prometheus] add server.extraFlags values array
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/server-deployment.yaml
  stable/prometheus/templates/server-statefulset.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19846 [stable/influxdb] Add release label into chart.
  stable/influxdb/Chart.yaml
  stable/influxdb/README.md
  stable/influxdb/templates/service.yaml
  stable/influxdb/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19837 [stable/openebs] Add PodSecurityPolicy (PSP)
  stable/openebs/Chart.yaml
  stable/openebs/README.md
  stable/openebs/templates/psp-clusterrole.yaml
  stable/openebs/templates/psp-clusterrolebinding.yaml
  stable/openebs/templates/psp.yaml
  stable/openebs/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19141 [stable/prometheus] server.env default value should be an array
  stable/prometheus/Chart.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19866 [stable/external-dns] Only inject DO_TOKEN when actually provided
  stable/external-dns/Chart.yaml
  stable/external-dns/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19815 [stable/sysdig] Enable K8s audit log feature for Sysdig Agent
  stable/sysdig/CHANGELOG.md
  stable/sysdig/Chart.yaml
  stable/sysdig/README.md
  stable/sysdig/templates/auditsink.yaml
  stable/sysdig/templates/configmap.yaml
  stable/sysdig/templates/service.yaml
  stable/sysdig/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#19882 [stable/minio]: Update to latest release
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19885 [stable/kong] bump up ingress controller to 0.7
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#19704 [stable/prometheus-operator] Add namespace to all PrometheusRule objects
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/hack/sync_prometheus_rules.py
  stable/prometheus-operator/templates/prometheus/rules-1.14/alertmanager.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/etcd.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/general.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/k8s.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kube-apiserver-error.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kube-apiserver.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kube-prometheus-node-recording.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kube-scheduler.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-absent.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-apps.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-resources.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-storage.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system-controller-manager.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system-kubelet.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system-scheduler.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/node-exporter.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/node-exporter.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/node-network.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/node-time.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/node.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/prometheus-operator.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/prometheus.yaml
  stable/prometheus-operator/templates/prometheus/rules/alertmanager.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules/etcd.yaml
  stable/prometheus-operator/templates/prometheus/rules/general.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules/k8s.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules/kube-apiserver.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules/kube-prometheus-node-alerting.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules/kube-prometheus-node-recording.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules/kube-scheduler.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules/kubernetes-absent.yaml
  stable/prometheus-operator/templates/prometheus/rules/kubernetes-apps.yaml
  stable/prometheus-operator/templates/prometheus/rules/kubernetes-resources.yaml
  stable/prometheus-operator/templates/prometheus/rules/kubernetes-storage.yaml
  stable/prometheus-operator/templates/prometheus/rules/kubernetes-system.yaml
  stable/prometheus-operator/templates/prometheus/rules/node-network.yaml
  stable/prometheus-operator/templates/prometheus/rules/node-time.yaml
  stable/prometheus-operator/templates/prometheus/rules/node.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules/prometheus-operator.yaml
  stable/prometheus-operator/templates/prometheus/rules/prometheus.rules.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#19887 [stable/kong] fix Job securityContext indentation
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/templates/migrations-post-upgrade.yaml
  stable/kong/templates/migrations-pre-upgrade.yaml
  stable/kong/templates/migrations.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19854 [stable/kong] 0.34.2 ci consolidation and readme fixes
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/ci/dbless-no-kic-values.yaml
  stable/kong/ci/dbless-values.yaml
  stable/kong/ci/default-values-with-psp.yaml
  stable/kong/ci/ingress-with-hosts.yaml
  stable/kong/ci/ingress-without-hosts.yaml
  stable/kong/ci/ingressController-db.yaml
  stable/kong/ci/ingressController-dbless.yaml
  stable/kong/ci/ingressController-with-psp.yaml
  stable/kong/ci/ingressController-with-webhook.yaml
  stable/kong/ci/loadbalancer-values.yaml
  stable/kong/ci/test1-values.yaml
  stable/kong/ci/test2-values.yaml
  stable/kong/ci/test3-values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#19833 [stable/external-dns] Add missing flags related to processing sources, kubefed related (Reopening #17494)
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/deployment.yaml
  stable/external-dns/values-production.yaml
  stable/external-dns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19881 [stable/nginx-ingress] Bump nginx-ingress version to 0.26.2
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19900 [stable/pomerium] Add option to configure forward-auth automatically
  stable/pomerium/Chart.yaml
  stable/pomerium/README.md
  stable/pomerium/templates/_helpers.tpl
  stable/pomerium/templates/configmap.yaml
  stable/pomerium/templates/ingress.yaml
  stable/pomerium/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#19875 [stable/prometheus-operator] fix comment in values.yaml (kubeScheduler)
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19907 [bitnami/ghost] Provide a way to disable readiness/liveness probes
  stable/ghost/Chart.yaml
  stable/ghost/README.md
  stable/ghost/templates/NOTES.txt
  stable/ghost/templates/deployment.yaml
  stable/ghost/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19877 [stable/datadog] fix `useConfigMap` when `useDedicatedContainers=true`
  stable/datadog/Chart.yaml
  stable/datadog/templates/container-agent.yaml
  stable/datadog/templates/container-process-agent.yaml
  stable/datadog/templates/container-trace-agent.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19856 [stable/kong] 0.35 update all standard labels
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/templates/_helpers.tpl
  stable/kong/templates/admission-webhook.yaml
  stable/kong/templates/config-custom-server-blocks.yaml
  stable/kong/templates/config-dbless.yaml
  stable/kong/templates/controller-rbac-resources.yaml
  stable/kong/templates/controller-service-account.yaml
  stable/kong/templates/custom-resource-definitions.yaml
  stable/kong/templates/deployment.yaml
  stable/kong/templates/ingress-admin.yaml
  stable/kong/templates/ingress-manager.yaml
  stable/kong/templates/ingress-portal-api.yaml
  stable/kong/templates/ingress-portal.yaml
  stable/kong/templates/ingress-proxy.yaml
  stable/kong/templates/migrations-post-upgrade.yaml
  stable/kong/templates/migrations-pre-upgrade.yaml
  stable/kong/templates/migrations.yaml
  stable/kong/templates/pdb.yaml
  stable/kong/templates/psp.yaml
  stable/kong/templates/service-kong-admin.yaml
  stable/kong/templates/service-kong-manager.yaml
  stable/kong/templates/service-kong-portal-api.yaml
  stable/kong/templates/service-kong-portal.yaml
  stable/kong/templates/service-kong-proxy.yaml
  stable/kong/templates/servicemonitor.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#19914 [stable/kong] 0.35.1 mutliple small fixes
  stable/kong/Chart.yaml
  stable/kong/OWNERS
  stable/kong/README.md
  stable/kong/templates/NOTES.txt
  stable/kong/templates/custom-resource-definitions.yaml
  stable/kong/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#19910 jenkins: fix case sense on OverwriteConfig condition in config.yaml
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/config.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#19886 [stable/nginx-ingress] Fix ClusterRole creation when using namespaces
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/templates/clusterrole.yaml
  stable/nginx-ingress/templates/clusterrolebinding.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19916 [stable/kong] Improve deployment label selector to not change on chart upgrades
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/templates/_helpers.tpl
  stable/kong/templates/deployment.yaml
  stable/kong/templates/service-kong-admin.yaml
  stable/kong/templates/service-kong-manager.yaml
  stable/kong/templates/service-kong-portal-api.yaml
  stable/kong/templates/service-kong-portal.yaml
  stable/kong/templates/service-kong-proxy.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#19935 [stable/sysdig] Enable Sysdig Secure by default
  stable/sysdig/CHANGELOG.md
  stable/sysdig/Chart.yaml
  stable/sysdig/README.md
  stable/sysdig/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#19938 [stable/sentry] Makes changing the secreyKey possible
  stable/sentry/Chart.yaml
  stable/sentry/README.md
  stable/sentry/templates/_helpers.tpl
  stable/sentry/templates/cron-deployment.yaml
  stable/sentry/templates/hooks/db-init.job.yaml
  stable/sentry/templates/hooks/user-create.job.yaml
  stable/sentry/templates/secrets.yaml
  stable/sentry/templates/web-deployment.yaml
  stable/sentry/templates/workers-deployment.yaml
  stable/sentry/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19858 [stable/nginx-ingress] Add fine-grained host port range in psp
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/templates/controller-psp.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19944 [stable/hazelcast] Add missing LOGGING_LEVEL env variables (#88)
  stable/hazelcast/Chart.yaml
  stable/hazelcast/README.adoc
  stable/hazelcast/templates/statefulset.yaml
  stable/hazelcast/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#19946 [stable/kong] Add missing watch permissions to custom resources
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/templates/controller-rbac-resources.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19707 [stable/prometheus-blackbox-exporter] Fix PodDisruptionBudget configuration
  stable/prometheus-blackbox-exporter/Chart.yaml
  stable/prometheus-blackbox-exporter/README.md
  stable/prometheus-blackbox-exporter/templates/poddisruptionbudget.yaml
  stable/prometheus-blackbox-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19765 [stable/nginx-ingress] If clusterIPs are set, they will automatically be quoted
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-metrics-service.yaml
  stable/nginx-ingress/templates/controller-service.yaml
  stable/nginx-ingress/templates/controller-webhook-service.yaml
  stable/nginx-ingress/templates/default-backend-service.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#19949 [stable/minio] Decouple directory root from the mountPath
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/templates/deployment.yaml
  stable/minio/templates/statefulset.yaml
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19932 stable/mssql-linux Allow a NodePort to be specified.
  stable/mssql-linux/Chart.yaml
  stable/mssql-linux/README.md
  stable/mssql-linux/templates/service.yaml
  stable/mssql-linux/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19955 [stable/kong] 0.36.2 timeout and admission controller fixes
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/ci/default-values.yaml
  stable/kong/ci/test1-values.yaml
  stable/kong/ci/test2-values.yaml
  stable/kong/ci/test3-values.yaml
  stable/kong/templates/admission-webhook.yaml
  stable/kong/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#19379 stable/prometheus Updated README.md with instructions for configuring pod scraping
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19936 [stable/prometheus-pushgateway] Allow to specify nodePort
  stable/prometheus-pushgateway/Chart.yaml
  stable/prometheus-pushgateway/README.md
  stable/prometheus-pushgateway/templates/service.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#19942 [incubator/haproxy-ingress] add source ip preservation detail
  incubator/haproxy-ingress/Chart.yaml
  incubator/haproxy-ingress/README.md
  incubator/haproxy-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19834 [stable/mediawiki] Add Mediawiki host parameter
  stable/mediawiki/Chart.yaml
  stable/mediawiki/README.md
  stable/mediawiki/templates/NOTES.txt
  stable/mediawiki/templates/_helpers.tpl
  stable/mediawiki/templates/deployment.yaml
  stable/mediawiki/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#19970 File system 'fs-12345678' does not exist
  stable/efs-provisioner/Chart.yaml
  stable/efs-provisioner/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19918 [stable/coredns] Align default zone configuration with k8s docs
  stable/coredns/Chart.yaml
  stable/coredns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19883 [stable/jenkins] fix deprecated config name used
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/config.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19975 [stable/coredns] Fix typo in values.yaml
  stable/coredns/Chart.yaml
  stable/coredns/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#19913 [stable/datadog] fix dd_site and dd_dd_url env var
  stable/datadog/Chart.yaml
  stable/datadog/templates/container-agent.yaml
  stable/datadog/templates/containers-common-env.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19848 [stable/prometheus-operator] - add tlsConfig to prometheus servicemonitor
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/prometheus/servicemonitor.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19927 [stable/prometheus] update prometheus to 2.15.2 and also all other used images to newest …
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/alertmanager-podsecuritypolicy.yaml
  stable/prometheus/templates/kube-state-metrics-podsecuritypolicy.yaml
  stable/prometheus/templates/pushgateway-podsecuritypolicy.yaml
  stable/prometheus/templates/server-podsecuritypolicy.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19967 [stable/chartmuseum] Add support for LoadBalancer and loadBalancerSourceRanges
  stable/chartmuseum/Chart.yaml
  stable/chartmuseum/README.md
  stable/chartmuseum/templates/service.yaml
  stable/chartmuseum/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#19984 Revert - File system 'fs-12345678' does not exist
  stable/efs-provisioner/Chart.yaml
  stable/efs-provisioner/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19983 [incubator/schema-registry] Deployment extensions/v1beta1 to apps/v1
  incubator/schema-registry/Chart.yaml
  incubator/schema-registry/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19969 [stable/prometheus-operator] fix typo for prometheus Operator Service…
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19990 [stable/cockroachdb]: Update version to v19.2.2
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/README.md
  stable/cockroachdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19904 [stable/minio] fix handling of extraArgs config
  stable/minio/Chart.yaml
  stable/minio/templates/_helpers.tpl
  stable/minio/templates/deployment.yaml
  stable/minio/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#20005 [stable/graylog] Update mongodb-replicaset dependency version.
  stable/graylog/Chart.yaml
  stable/graylog/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20006 Fix typo in mongodb README
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20004 [stable/prometheus] Add Missing ClusterRole Permissions for Kube-state-metrics
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/kube-state-metrics-clusterrole.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20011 [stable/node-red] Add values of paths for livenessProbe and readinessProbe
  stable/node-red/Chart.yaml
  stable/node-red/README.md
  stable/node-red/templates/deployment.yaml
  stable/node-red/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#19214 [stable/tomcat] Added failureThreshold on livenessProbe and timeoutSeconds
  stable/tomcat/Chart.yaml
  stable/tomcat/templates/appsrv.yaml
  stable/tomcat/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19712 [stable/drone] drone server and restricted pod security policies
  stable/drone/Chart.yaml
  stable/drone/README.md
  stable/drone/templates/NOTES.txt
  stable/drone/templates/deployment-server.yaml
  stable/drone/templates/service.yaml
  stable/drone/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20018 [stable/sentry] fix: reverts changes to sentry secrets template
  stable/sentry/Chart.yaml
  stable/sentry/templates/secrets.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19912 [stable/redis-ha] add persistentVolume.reclaimPolicy
  stable/redis-ha/Chart.yaml
  stable/redis-ha/README.md
  stable/redis-ha/templates/redis-ha-statefulset.yaml
  stable/redis-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#20003 [stable/pomerium] Allow service and deployment specific annotations
  stable/pomerium/Chart.yaml
  stable/pomerium/README.md
  stable/pomerium/templates/authenticate-deployment.yaml
  stable/pomerium/templates/authenticate-service.yaml
  stable/pomerium/templates/authorize-deployment.yaml
  stable/pomerium/templates/authorize-service.yaml
  stable/pomerium/templates/proxy-deployment.yaml
  stable/pomerium/templates/proxy-service.yaml
  stable/pomerium/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#16040 [stable/prometheus-pushgateway] Add persistence support
  stable/prometheus-pushgateway/Chart.yaml
  stable/prometheus-pushgateway/README.md
  stable/prometheus-pushgateway/templates/deployment.yaml
  stable/prometheus-pushgateway/templates/pushgateway-pvc.yaml
  stable/prometheus-pushgateway/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#19961 [promethesus-adapter] use the new tag name
  stable/prometheus-adapter/Chart.yaml
  stable/prometheus-adapter/README.md
  stable/prometheus-adapter/templates/custom-metrics-configmap.yaml
  stable/prometheus-adapter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#20041 [stable/sysdig] Remove auditLog.clusterIP value
  stable/sysdig/CHANGELOG.md
  stable/sysdig/Chart.yaml
  stable/sysdig/README.md
  stable/sysdig/templates/auditsink.yaml
  stable/sysdig/templates/service.yaml
  stable/sysdig/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#19992 [stable/kong] servicemonitor.yaml: error converting YAML to JSON #19956
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/templates/servicemonitor.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20039 workaround ELB healthcheck ssl bug
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/templates/service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20028 [stable/kube-state-metrics] Version bump to 1.9.1
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
  stable/kube-state-metrics/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#20051 [stable/kong] Add check for config changes
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20012 [stable/schema-registry-ui] Deployment apps/v1beta1 to apps/v1
  stable/schema-registry-ui/Chart.yaml
  stable/schema-registry-ui/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#19622 [stable/fluent-bit]add use_journal
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/config.yaml
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19761 [stable/mercure] Add support for new features
  stable/mercure/Chart.yaml
  stable/mercure/README.md
  stable/mercure/templates/configmap.yaml
  stable/mercure/templates/deployment.yaml
  stable/mercure/templates/secret.yaml
  stable/mercure/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#20063 [stable/nginx-ingress] Remove duplicated hostPorts entries in psp
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/templates/controller-psp.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20026 [stable/prometheus] Add option to set labels for Prometheus AlertManager pods
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/alertmanager-deployment.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#16381 [stable/openvpn] systemd-resolved, ip_forward, nodeport, ubuntu fixes
  stable/openvpn/Chart.yaml
  stable/openvpn/README.md
  stable/openvpn/templates/config-openvpn.yaml
  stable/openvpn/templates/openvpn-deployment.yaml
  stable/openvpn/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#20067 [stable/jenkins]
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/jenkins-agent-svc.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#19924 [stable/mongodb-replicaset] Added default values to missing keys in Values.yaml
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20069 [stable/nginx-ingress] Bump nginx-ingress version to 0.27.0
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-daemonset.yaml
  stable/nginx-ingress/templates/controller-deployment.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20048 [stable/prometheus-pushgateway] Fix persistence support
  stable/prometheus-pushgateway/Chart.yaml
  stable/prometheus-pushgateway/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20056 [stable/prometheus] Added remote_write and remote_read for prometheus
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/server-configmap.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19500 [stable/mariadb] inject `mariadb-replication-password` from secret on…
  stable/mariadb/Chart.yaml
  stable/mariadb/templates/master-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20072 [stable/prometheus] Add Telemetry port to Kube-state-metrics
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/kube-state-metrics-deployment.yaml
  stable/prometheus/templates/kube-state-metrics-svc.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19364 [stable/sonarqube] Add ability to add/mount extra volumes
  stable/sonarqube/Chart.yaml
  stable/sonarqube/README.md
  stable/sonarqube/templates/deployment.yaml
  stable/sonarqube/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20077 [stable/metrics-server] Support custom sidecar containers
  stable/metrics-server/Chart.yaml
  stable/metrics-server/README.md
  stable/metrics-server/templates/metrics-server-deployment.yaml
  stable/metrics-server/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#20088 [stable/stolon] add image.pullSecrets
  stable/stolon/Chart.yaml
  stable/stolon/README.md
  stable/stolon/templates/keeper-statefulset.yaml
  stable/stolon/templates/proxy-deployment.yaml
  stable/stolon/templates/sentinel-deployment.yaml
  stable/stolon/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#19811 [stable/prometheus-operator] add runbook_url prefix (#19810)
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/hack/sync_prometheus_rules.py
  stable/prometheus-operator/templates/prometheus/rules-1.14/k8s.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kube-apiserver-error.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-absent.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-apps.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-resources.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-storage.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system-controller-manager.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system-kubelet.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system-scheduler.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/node-exporter.yaml
  stable/prometheus-operator/templates/prometheus/rules/kubernetes-absent.yaml
  stable/prometheus-operator/templates/prometheus/rules/kubernetes-apps.yaml
  stable/prometheus-operator/templates/prometheus/rules/kubernetes-resources.yaml
  stable/prometheus-operator/templates/prometheus/rules/kubernetes-storage.yaml
  stable/prometheus-operator/templates/prometheus/rules/kubernetes-system.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#20076 [stable/nginx-ingress]: remove excessive - symbol
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/templates/controller-daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20092 [stable/minio] Added support for ingress labels, which are required with some ingres…
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/templates/ingress.yaml
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20025 Add additional values to enhance flexibility of helm-exporter
  stable/helm-exporter/Chart.yaml
  stable/helm-exporter/templates/deployment.yaml
  stable/helm-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20099 [stable/kong] 0.36.5 grpc protocol for plugin execution
  stable/kong/Chart.yaml
  stable/kong/README.md
  stable/kong/templates/custom-resource-definitions.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#20094 [incubator/hoverfly]: Add Openshift Route Creation for Admin & Proxy Interfaces
  incubator/hoverfly/Chart.yaml
  incubator/hoverfly/README.md
  incubator/hoverfly/templates/route.yaml
  incubator/hoverfly/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19538 [stable/prometheus-operator] Limit app namespace alert scope
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/hack/sync_prometheus_rules.py
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-apps.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-storage.yaml
  stable/prometheus-operator/templates/prometheus/rules/kubernetes-apps.yaml
  stable/prometheus-operator/templates/prometheus/rules/kubernetes-storage.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#20106 [stable/sentry] fix: do not fail user-create container when user already exists
  stable/sentry/Chart.yaml
  stable/sentry/templates/hooks/user-create.job.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19836 [stable/sonarqube] upgrades LTS to latest patch
  REVIEW_GUIDELINES.md
  stable/sonarqube/Chart.yaml
  stable/sonarqube/README.md
  stable/sonarqube/templates/ingress.yaml
  stable/sonarqube/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20110 [incubator/kafka] Add Prometheus Operator PrometheusRules
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
  incubator/kafka/templates/_helpers.tpl
  incubator/kafka/templates/prometheusrules.yaml
  incubator/kafka/templates/servicemonitors.yaml
  incubator/kafka/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#20103 [stable/kube-state-metrics] Version bump to 1.9.2
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
  stable/kube-state-metrics/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#19115 [stable/elasticsearch-exporter] Enabling environment from secrets
  stable/elasticsearch-exporter/Chart.yaml
  stable/elasticsearch-exporter/README.md
  stable/elasticsearch-exporter/templates/deployment.yaml
  stable/elasticsearch-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20149 [stable/kong] 0.36.6 deprecate Kong chart
  stable/kong/Chart.yaml
  stable/kong/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#20096 [stable/prometheus-operator] Update grafana chart version
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/requirements.lock
  stable/prometheus-operator/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20159 [stable/nats] Fix args for metrics
  stable/nats/Chart.yaml
  stable/nats/templates/deployment.yaml
  stable/nats/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20086 [stable/phpmyadmin] Fix an SSL certificates directory conflict
  stable/phpmyadmin/Chart.yaml
  stable/phpmyadmin/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20161 [stolon/stable] fixed image pull secrets
  stable/stolon/Chart.yaml
  stable/stolon/templates/keeper-statefulset.yaml
  stable/stolon/templates/proxy-deployment.yaml
  stable/stolon/templates/sentinel-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#20163 [stable/unifi] Add ability to specify additional jvm options and config files
  stable/unifi/Chart.yaml
  stable/unifi/README.md
  stable/unifi/templates/configmap.yaml
  stable/unifi/templates/deployment.yaml
  stable/unifi/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19991 [stable/prometheus-operator] AlertManager RBAC: move from ClusterRole to Role
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/alertmanager/psp-role.yaml
  stable/prometheus-operator/templates/alertmanager/psp-rolebinding.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20105 [stable/jenkins] Add correct PodLabel for NetworkPolicy
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/config.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20117 [stable/openebs] Update charts to 1.6.0 release
  stable/openebs/Chart.yaml
  stable/openebs/README.md
  stable/openebs/templates/clusterrole.yaml
  stable/openebs/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#20172 [stable/owncloud] Set deployment strategy with values
  stable/owncloud/Chart.yaml
  stable/owncloud/README.md
  stable/owncloud/templates/deployment.yaml
  stable/owncloud/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20034 [stable/dex] Upgrade dex to 2.21.0.
  stable/dex/Chart.yaml
  stable/dex/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#20176 [stable/rabbitmq] Fix prometheus scrape port
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/values-production.yaml
  stable/rabbitmq/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20175 [stable/nginx-ingress]: make pod dnsConfig configurable
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-daemonset.yaml
  stable/nginx-ingress/templates/controller-deployment.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19441 [stable/traefik] switch service protocols to where SSL is configured first
  stable/traefik/Chart.yaml
  stable/traefik/templates/service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20064 [state/elasticsearch] add pullSecrets in README.md
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20112 [stable/Add json_date_format to backend.http configuration
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/config.yaml
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20087 Update README.md
  stable/grafana/Chart.yaml
  stable/grafana/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20182 [stable/grafana] Enabling environment variables to be composed from secrets.
  stable/grafana/Chart.yaml
  stable/grafana/templates/_pod.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20097 [stable/mongodb] add additional options (sidecars, volumes)
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/templates/deployment-standalone.yaml
  stable/mongodb/templates/statefulset-arbiter-rs.yaml
  stable/mongodb/templates/statefulset-primary-rs.yaml
  stable/mongodb/templates/statefulset-secondary-rs.yaml
  stable/mongodb/values-production.yaml
  stable/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#20113 [stable/redis] Fix the NOTES label when using NetworkPolicy
  stable/redis/Chart.yaml
  stable/redis/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19930 [stable/prometheus] prometheus.io/scrape-slow for scraping slow target
  stable/prometheus/Chart.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#20178 [stable/newrelic-infrastructure] Upgrade image version to 1.12.0
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/README.md
  stable/newrelic-infrastructure/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#19466 [stable/prometheus-adapter] Allow prometheus-adapter to start in hostNetwork mode
  stable/prometheus-adapter/Chart.yaml
  stable/prometheus-adapter/templates/custom-metrics-apiserver-deployment.yaml
  stable/prometheus-adapter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19545 [stable/sonarqube] Support plugins that need copying to lib
  stable/sonarqube/Chart.yaml
  stable/sonarqube/README.md
  stable/sonarqube/templates/copy-plugins.yaml
  stable/sonarqube/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19608 [stable/drone] Add support for Drone License Key
  stable/drone/Chart.yaml
  stable/drone/README.md
  stable/drone/templates/_helpers.tpl
  stable/drone/templates/deployment-server.yaml
  stable/drone/templates/secrets.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#20185 [stable/clamav] Let the user choose the api version of their deployment.
  stable/clamav/Chart.yaml
  stable/clamav/README.md
  stable/clamav/templates/deployment.yaml
  stable/clamav/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#20190 [stable/prometheus] fix: alertmanager to use /-/ready as readiness probe
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/alertmanager-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20194 [stable/prometheus-operator] Fix metric relabeling
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#15564 [stable/spinnaker] Add ecr as docker registry with --password-command parameter
  stable/spinnaker/Chart.yaml
  stable/spinnaker/README.md
  stable/spinnaker/templates/configmap/halyard-config.yaml
  stable/spinnaker/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20177 [stable/sonarqube]: download sonarqube plugins in parallel
  stable/sonarqube/Chart.yaml
  stable/sonarqube/templates/install-plugins.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS
