Repository helm/charts, pull requests merged in 2020-03, with the labels that each got.

#21110 Added fullname as prefix for init-scripts configmap name.
  stable/stolon/Chart.yaml
  stable/stolon/templates/hooks/init-db-job.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#21101 [stable/kured] Upgrade to latest version 1.3.0
  stable/kured/Chart.yaml
  stable/kured/README.md
  stable/kured/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21140 [stable/eventrouter] update eventrouter to v0.3
  stable/eventrouter/Chart.yaml
  stable/eventrouter/README.md
  stable/eventrouter/templates/configmap.yaml
  stable/eventrouter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21155 [stable/minio] annotation fix
  stable/minio/Chart.yaml
  stable/minio/templates/post-install-create-bucket-job.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21148 [stable/prometheus] Use ksm chart for ksm
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/requirements.yaml
  stable/prometheus/templates/kube-state-metrics-clusterrole.yaml
  stable/prometheus/templates/kube-state-metrics-clusterrolebinding.yaml
  stable/prometheus/templates/kube-state-metrics-deployment.yaml
  stable/prometheus/templates/kube-state-metrics-networkpolicy.yaml
  stable/prometheus/templates/kube-state-metrics-pdb.yaml
  stable/prometheus/templates/kube-state-metrics-podsecuritypolicy.yaml
  stable/prometheus/templates/kube-state-metrics-serviceaccount.yaml
  stable/prometheus/templates/kube-state-metrics-svc.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#20648 chore: use the new api for ingress
  stable/grafana/Chart.yaml
  stable/grafana/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21150 [stable/mongodb] updateStrategy added when useStatefulSet is true and serviceName added.
  stable/mongodb/Chart.yaml
  stable/mongodb/templates/deployment-standalone.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21172 [stable/wordpress] Fix issue with port number when using external dbs
  stable/wordpress/Chart.yaml
  stable/wordpress/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20745 [mssql/linux] Allow setting tolerations, affinity, and securityContext
  stable/mssql-linux/Chart.yaml
  stable/mssql-linux/README.md
  stable/mssql-linux/templates/deployment.yaml
  stable/mssql-linux/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#21173 [stable/hazelcast] Add runAsGroup in SecurityContext (#101)
  stable/hazelcast/Chart.yaml
  stable/hazelcast/README.adoc
  stable/hazelcast/templates/mancenter-statefulset.yaml
  stable/hazelcast/templates/statefulset.yaml
  stable/hazelcast/templates/tests/test-hazelcast.yaml
  stable/hazelcast/templates/tests/test-management-center.yaml
  stable/hazelcast/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21174 [stable/hazelcast-jet] Add runAsGroup in SecurityContext (#101)
  stable/hazelcast-jet/Chart.yaml
  stable/hazelcast-jet/README.adoc
  stable/hazelcast-jet/templates/management-center-deployment.yaml
  stable/hazelcast-jet/templates/statefulset.yaml
  stable/hazelcast-jet/templates/tests/test-hazelcast-jet.yaml
  stable/hazelcast-jet/templates/tests/test-management-center.yaml
  stable/hazelcast-jet/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21083 [stable/sealed-secrets] Add podLabels support
  stable/sealed-secrets/Chart.yaml
  stable/sealed-secrets/README.md
  stable/sealed-secrets/templates/deployment.yaml
  stable/sealed-secrets/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21184 [stable/nginx-ingress] match minReplicas to the documentation
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21075 [stable/influxdb] Additional auth job variables
  stable/influxdb/Chart.yaml
  stable/influxdb/templates/post-install-set-auth.yaml
  stable/influxdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21182 [stable/hazelcast-jet] Merge pull request #93 from gurbuzali/jet-4.0
  stable/hazelcast-jet/Chart.yaml
  stable/hazelcast-jet/README.adoc
  stable/hazelcast-jet/templates/NOTES.txt
  stable/hazelcast-jet/templates/management-center-deployment.yaml
  stable/hazelcast-jet/templates/management-center-service.yaml
  stable/hazelcast-jet/templates/statefulset.yaml
  stable/hazelcast-jet/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/L

#21213 [stable/sysdig] Upgrade to latest agent version (9.6.1)
  stable/sysdig/CHANGELOG.md
  stable/sysdig/Chart.yaml
  stable/sysdig/README.md
  stable/sysdig/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#21187 [stable/newrelic-infrastructure] Bump chart to latest version
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/README.md
  stable/newrelic-infrastructure/templates/daemonset.yaml
  stable/newrelic-infrastructure/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21188 [stable/postgresql] Add sidecars support
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/statefulset-slaves.yaml
  stable/postgresql/templates/statefulset.yaml
  stable/postgresql/values-production.yaml
  stable/postgresql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21205 [stable/jenkins] update pluging versions
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#21207 [stable/consul] updated templating for ingress host
  stable/consul/Chart.yaml
  stable/consul/templates/consul-ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21210 [stable/nextcloud] add subPath option
  stable/nextcloud/Chart.yaml
  stable/nextcloud/README.md
  stable/nextcloud/templates/deployment.yaml
  stable/nextcloud/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19876 [stable/elasticsearch-curator] Update README.md
  stable/elasticsearch-curator/Chart.yaml
  stable/elasticsearch-curator/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21208 [stable/prometheus] Support tmpl files which are not YAML
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/alertmanager-configmap.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21217 [stable/airflow] be able to change git sync target
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/templates/deployments-scheduler.yaml
  stable/airflow/templates/deployments-web.yaml
  stable/airflow/templates/statefulsets-workers.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#21219 [stable/hazelcast-jet] Merge pull request #103 from eminn/security-context
  stable/hazelcast-jet/Chart.yaml
  stable/hazelcast-jet/README.adoc
  stable/hazelcast-jet/templates/management-center-deployment.yaml
  stable/hazelcast-jet/templates/statefulset.yaml
  stable/hazelcast-jet/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#20887 [stable/traefik] Add distinct container SecurityContext tunable (#20743)
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/deployment.yaml
  stable/traefik/templates/storeconfig-job.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19637 Make liveness and readiness probes configurable
  stable/rocketchat/Chart.yaml
  stable/rocketchat/README.md
  stable/rocketchat/templates/deployment.yaml
  stable/rocketchat/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21151 [stable/drone] Add deprecation note in favor of official Charts
  stable/drone/Chart.yaml
  stable/drone/README.md
  stable/drone/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21072 [stable/jenkins] Allow configuring terminationGracePeriodSeconds
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/jenkins-master-deployment.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#21225 [stable/falco] allow gRPC configuration using values
  stable/falco/CHANGELOG.md
  stable/falco/Chart.yaml
  stable/falco/README.md
  stable/falco/templates/configmap.yaml
  stable/falco/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#21196 [stable/grafana] Use selectorLabels helper in headless service
  stable/grafana/Chart.yaml
  stable/grafana/templates/headless-service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20209 [stable/redis-ha] Fix label selector of haproxy servicemonitor
  stable/redis-ha/Chart.yaml
  stable/redis-ha/templates/redis-haproxy-servicemonitor.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21231 [stable/influxdb] Add deprecation notice.
  stable/influxdb/Chart.yaml
  stable/influxdb/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#21234 [stable/kapacitor] Add deprecation notice.
  stable/kapacitor/Chart.yaml
  stable/kapacitor/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#21238 [stable/sealed-secrets] Upgrade to v0.10.0
  stable/sealed-secrets/Chart.yaml
  stable/sealed-secrets/README.md
  stable/sealed-secrets/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21214 chore(grafana): update grafana version
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/requirements.lock
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21239 [stable/hazelcast-jet] Merge pull request #104 from eminn/fsGroup-helm3-fix
  stable/hazelcast-jet/Chart.yaml
  stable/hazelcast-jet/templates/management-center-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#21178 [stable/cerebro] Add ability to set tls skip verify via vaules file
  stable/cerebro/Chart.yaml
  stable/cerebro/README.md
  stable/cerebro/templates/configmap.yaml
  stable/cerebro/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21079 [stable/kube-state-metrics] Add missing permission for volumeattachment collector
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/templates/clusterrole.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21218 [stable/hazelcast] make configurable securityContext at statefulset spec level (#102)
  stable/hazelcast/Chart.yaml
  stable/hazelcast/templates/mancenter-statefulset.yaml
  stable/hazelcast/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18620 [stable/elastic-stack] update requirements for 1.16
  stable/elastic-stack/Chart.yaml
  stable/elastic-stack/requirements.lock
  stable/elastic-stack/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#20875 [stable/mongodb-replicaset] feature: add support for extra containers and volumes
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/README.md
  stable/mongodb-replicaset/templates/mongodb-statefulset.yaml
  stable/mongodb-replicaset/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21123 [sonatype-nexus] provide granular resource requests to nexus backup container
  stable/sonatype-nexus/Chart.yaml
  stable/sonatype-nexus/README.md
  stable/sonatype-nexus/templates/deployment-statefulset.yaml
  stable/sonatype-nexus/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#21190 [stable/prometheus-operator] Add ThanosRuler resources to ClusterRole
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/prometheus-operator/clusterrole.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21253 fix hard-coded path and default to "/"
  stable/prometheus-pushgateway/Chart.yaml
  stable/prometheus-pushgateway/templates/ingress.yaml
  stable/prometheus-pushgateway/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21245 [stable/kube-state-metrics] Enable all collectors by default
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
  stable/kube-state-metrics/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#21255 [stable/sonatype-nexus] - Deprecate sonatype-nexus chart
  stable/sonatype-nexus/Chart.yaml
  stable/sonatype-nexus/README.md
  stable/sonatype-nexus/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, size/S

#21204 [stable/cluster-autoscaler] reuse existing service account
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/README.md
  stable/cluster-autoscaler/templates/_helpers.tpl
  stable/cluster-autoscaler/templates/clusterrolebinding.yaml
  stable/cluster-autoscaler/templates/deployment.yaml
  stable/cluster-autoscaler/templates/rolebinding.yaml
  stable/cluster-autoscaler/templates/serviceaccount.yaml
  stable/cluster-autoscaler/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21263 [prometheus/stable] auto import of dashboards with helm template(helm 3)
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/hack/sync_grafana_dashboards.py
  stable/prometheus-operator/templates/grafana/dashboards-1.14/apiserver.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/cluster-total.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/controller-manager.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/etcd.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-coredns.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-cluster.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-namespace.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-node.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-pod.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-workload.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-workloads-namespace.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/kubelet.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/namespace-by-pod.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/namespace-by-workload.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/node-cluster-rsrc-use.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/node-rsrc-use.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/nodes.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/persistentvolumesusage.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/pod-total.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/pods.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/prometheus-remote-write.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/prometheus.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/proxy.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/scheduler.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/statefulset.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/workload-total.yaml
  stable/prometheus-operator/templates/grafana/dashboards/etcd.yaml
  stable/prometheus-operator/templates/grafana/dashboards/k8s-cluster-rsrc-use.yaml
  stable/prometheus-operator/templates/grafana/dashboards/k8s-node-rsrc-use.yaml
  stable/prometheus-operator/templates/grafana/dashboards/k8s-resources-cluster.yaml
  stable/prometheus-operator/templates/grafana/dashboards/k8s-resources-namespace.yaml
  stable/prometheus-operator/templates/grafana/dashboards/k8s-resources-pod.yaml
  stable/prometheus-operator/templates/grafana/dashboards/k8s-resources-workload.yaml
  stable/prometheus-operator/templates/grafana/dashboards/k8s-resources-workloads-namespace.yaml
  stable/prometheus-operator/templates/grafana/dashboards/nodes.yaml
  stable/prometheus-operator/templates/grafana/dashboards/persistentvolumesusage.yaml
  stable/prometheus-operator/templates/grafana/dashboards/pods.yaml
  stable/prometheus-operator/templates/grafana/dashboards/statefulset.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#19986 [stable/kube-state-metrics] Only create PSP RBAC if rbac.create is true.
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
  stable/kube-state-metrics/templates/psp-clusterrole.yaml
  stable/kube-state-metrics/templates/psp-clusterrolebinding.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21259 [stable/prometheus-redis-exporter] Fix secret key path in deployment
  stable/prometheus-redis-exporter/Chart.yaml
  stable/prometheus-redis-exporter/README.md
  stable/prometheus-redis-exporter/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20874 [stable/elasticsearch-curator] load envs from secrets first
  stable/elasticsearch-curator/Chart.yaml
  stable/elasticsearch-curator/templates/cronjob.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#18989 [stable/memcached] fixes updateStrategy for Deployment
  stable/memcached/Chart.yaml
  stable/memcached/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21132 [stable/prometheus-operator] add enforcedNamespaceLabel option to the prom operator
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/prometheus/prometheus.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21268 [stable/datadog] Revert "Mount the directory containing the CRI socket instead of the socket itself"
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/templates/container-agent.yaml
  stable/datadog/templates/container-process-agent.yaml
  stable/datadog/templates/containers-init.yaml
  stable/datadog/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21260 [stable/nginx-ingress] add instruction to make it work with nlb
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
Labels: Contribution Allowed, approved, lgtm, size/M

#21272 [stable/minecraft] configurable upgrade strategy type
  stable/minecraft/Chart.yaml
  stable/minecraft/templates/deployment.yaml
  stable/minecraft/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#21203 [stable/mongodb-replicaset] Namespace override
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/README.md
  stable/mongodb-replicaset/templates/NOTES.txt
  stable/mongodb-replicaset/templates/_helpers.tpl
  stable/mongodb-replicaset/templates/mongodb-admin-secret.yaml
  stable/mongodb-replicaset/templates/mongodb-ca-secret.yaml
  stable/mongodb-replicaset/templates/mongodb-init-configmap.yaml
  stable/mongodb-replicaset/templates/mongodb-keyfile-secret.yaml
  stable/mongodb-replicaset/templates/mongodb-metrics-secret.yaml
  stable/mongodb-replicaset/templates/mongodb-mongodb-configmap.yaml
  stable/mongodb-replicaset/templates/mongodb-poddisruptionbudget.yaml
  stable/mongodb-replicaset/templates/mongodb-service-client.yaml
  stable/mongodb-replicaset/templates/mongodb-service.yaml
  stable/mongodb-replicaset/templates/mongodb-statefulset.yaml
  stable/mongodb-replicaset/templates/tests/mongodb-up-test-configmap.yaml
  stable/mongodb-replicaset/templates/tests/mongodb-up-test-pod.yaml
  stable/mongodb-replicaset/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21282 [stable/nginx-ingress] fix(values): move maxmindLicenseKey under controller
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21289 [stable/prometheus] Set rollingUpdate to null when strategy is Recreate
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/alertmanager-deployment.yaml
  stable/prometheus/templates/pushgateway-deployment.yaml
  stable/prometheus/templates/server-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21236 [stable/postgresql] Updated helper functions to use KubeVersion.Version instead of deprecated KubeVersion.GitVerson
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21267 stable/graylog Adding the possibility of specifying your own URI for the GeoLite DDBB location
  stable/graylog/Chart.yaml
  stable/graylog/README.md
  stable/graylog/templates/configmap.yaml
  stable/graylog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21048 [stable/elasticsearch] Adds imagePullSecrets to test image
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/templates/tests/test.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21261 [stable/prometheus-operator] Fix roles for k8s >1.15
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/alertmanager/psp-role.yaml
  stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/clusterrole.yaml
  stable/prometheus-operator/templates/prometheus-operator/psp-clusterrole.yaml
  stable/prometheus-operator/templates/prometheus/psp-clusterrole.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#19668 [stable/fluentd] Enable use of statefulset without autoscaling
  stable/fluentd/Chart.yaml
  stable/fluentd/README.md
  stable/fluentd/templates/deployment.yaml
  stable/fluentd/templates/pvc.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21291 [stable/external-dns]use the latest GH link of externaldns
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/values-production.yaml
  stable/external-dns/values.yaml
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21308 [stable/postgresql] Revert #21236
  stable/postgresql/Chart.yaml
  stable/postgresql/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20656 [stable/rabbitmq-ha] Added 'topicPermission' key in definitions.json secret
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/templates/_helpers.tpl
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21232 [stable/telegraf] Add deprecation notice.
  stable/telegraf/Chart.yaml
  stable/telegraf/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#21247 [stable/kapacitor] Chart deprecation
  stable/kapacitor/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#21233 [stable/chronograf] Add deprecation notice.
  stable/chronograf/Chart.yaml
  stable/chronograf/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#21246 [stable/influxdb] Chart deprecation
  stable/influxdb/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#21275 [stable/pgadmin] deprecated
  stable/pgadmin/Chart.yaml
  stable/pgadmin/README.md
  stable/pgadmin/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21241 [stable/unifi] Adding captive portal service
  stable/unifi/Chart.yaml
  stable/unifi/README.md
  stable/unifi/templates/captive-ingress.yaml
  stable/unifi/templates/captive-svc.yaml
  stable/unifi/templates/deployment.yaml
  stable/unifi/templates/unified-svc.yaml
  stable/unifi/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#20914 [stable/chaoskube] Support adding pod labels.
  stable/chaoskube/Chart.yaml
  stable/chaoskube/README.md
  stable/chaoskube/templates/deployment.yaml
  stable/chaoskube/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21315 [stable/minio] allow ingress to have empty host
  stable/minio/Chart.yaml
  stable/minio/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21318 [stable/minio] remove references for old env docs
  stable/minio/Chart.yaml
  stable/minio/templates/deployment.yaml
  stable/minio/templates/statefulset.yaml
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21320 [stable/unifi] hotfix: fixing ingress name + nodePorts references
  stable/unifi/Chart.yaml
  stable/unifi/templates/captive-svc.yaml
  stable/unifi/templates/unified-svc.yaml
  stable/unifi/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21321 [stable/unifi] Ingress was not referring to the good service
  stable/unifi/Chart.yaml
  stable/unifi/templates/captive-ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21317 [stable/datadog] Fix trace agent and useConfigMap
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/templates/container-trace-agent.yaml
  stable/datadog/templates/datadog-yaml-configmap.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21311 [stable/cluster-autoscaler] ClusterRole leases and version bump to 1.17.1
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/README.md
  stable/cluster-autoscaler/templates/clusterrole.yaml
  stable/cluster-autoscaler/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21310 [stable/rabbitmq] Move chart to distributed bitnami repository
  stable/rabbitmq/Chart.yaml
  stable/rabbitmq/README.md
  stable/rabbitmq/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21285 [stable/external-dns] Added custom volume support
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/deployment.yaml
  stable/external-dns/values-production.yaml
  stable/external-dns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21298 [stable/datadog] Honor image pull policy in init containers
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/docs/Migration_1.x_to_2.x.md
  stable/datadog/templates/containers-init.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21333 [stable/redis] Move chart to distributed bitnami repository
  stable/redis/Chart.yaml
  stable/redis/README.md
  stable/redis/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21024 [stable/airflow]Add optional security context to airflow deployments
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/templates/deployments-flower.yaml
  stable/airflow/templates/deployments-scheduler.yaml
  stable/airflow/templates/deployments-web.yaml
  stable/airflow/templates/statefulsets-workers.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21322 [stable/nginx-ingress] Allow projected volumes in controller-psp.yaml
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/templates/controller-psp.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21350 [stable/instana-agent] Chart version 1.0.24
  stable/instana-agent/Chart.yaml
  stable/instana-agent/README.md
Labels: Contribution Allowed, approved, lgtm, size/M

#21353 Fixed a compatibility issue with K8s 1.11
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/templates/crds.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#21304 [stable/prometheus-operator] Bump operator version. Closes #20503
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21346 [stable/external-dns] Fix for mounting CA certs from host
  stable/external-dns/Chart.yaml
  stable/external-dns/templates/psp.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21334 [stable/node-problem-detector] Add custom labels to daemonset
  stable/node-problem-detector/Chart.yaml
  stable/node-problem-detector/README.md
  stable/node-problem-detector/templates/daemonset.yaml
  stable/node-problem-detector/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#21251 [stable/prometheus-operator] Allow to override AlertManager's target port
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/alertmanager/service.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21305 [stable/atlantis] Updating AWS to not require 'credentials' for use with IRSA
  stable/atlantis/Chart.yaml
  stable/atlantis/templates/secret-aws.yaml
  stable/atlantis/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21357 [stable/sysdig] Update latest agent version (9.7.0)
  stable/sysdig/CHANGELOG.md
  stable/sysdig/Chart.yaml
  stable/sysdig/README.md
  stable/sysdig/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#21271 [stable/prometheus-operator] Update grafana version to include fix from #21196
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/requirements.lock
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21368 stable/airflow minor fixes
  stable/airflow/Chart.yaml
  stable/airflow/templates/deployments-scheduler.yaml
  stable/airflow/templates/secret-connections.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#21256 [stable/postgresql] - Fix readme typo
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21360 [stable/node-problem-detector]: Bump to 0.8.1 NPD
  stable/node-problem-detector/Chart.yaml
  stable/node-problem-detector/README.md
  stable/node-problem-detector/templates/daemonset.yaml
  stable/node-problem-detector/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20696 [stable/kube-ops-view] Add nodeSelector
  stable/kube-ops-view/Chart.yaml
  stable/kube-ops-view/templates/deployment.yaml
  stable/kube-ops-view/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20623 [stable/home-assistant] feat: Make service port name configurable
  stable/home-assistant/Chart.yaml
  stable/home-assistant/README.md
  stable/home-assistant/templates/service.yaml
  stable/home-assistant/templates/servicemonitor.yaml
  stable/home-assistant/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21379 [stable/openebs] Update jiva image default to 1.7.1
  stable/openebs/Chart.yaml
  stable/openebs/README.md
  stable/openebs/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21408 [stable/postgresql] Move chart to distributed bitnami repository
  stable/postgresql/Chart.yaml
  stable/postgresql/README.md
  stable/postgresql/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21393 [stable/kubewatch] Move chart to distributed bitnami repository
  stable/kubewatch/Chart.yaml
  stable/kubewatch/README.md
  stable/kubewatch/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21396 [stable/external] Move chart to distributed bitnami repository
  stable/external-dns/Chart.yaml
  stable/external-dns/README.md
  stable/external-dns/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21398 [stable/mongodb] Move chart to distributed bitnami repository
  stable/mongodb/Chart.yaml
  stable/mongodb/README.md
  stable/mongodb/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21387 [stable/prometheus-redis-exporter] Add support for Prometheus Operator Rules
  stable/prometheus-redis-exporter/Chart.yaml
  stable/prometheus-redis-exporter/README.md
  stable/prometheus-redis-exporter/templates/prometheusrule.yaml
  stable/prometheus-redis-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21407 [stable/phpmyadmin] Move chart to distributed bitnami repository
  stable/phpmyadmin/Chart.yaml
  stable/phpmyadmin/README.md
  stable/phpmyadmin/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21410 [stable/parse] Move chart to distributed bitnami repository
  stable/parse/Chart.yaml
  stable/parse/README.md
  stable/parse/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21411 [stable/phabricator] Move chart to distributed bitnami repository
  stable/phabricator/Chart.yaml
  stable/phabricator/README.md
  stable/phabricator/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21413 [stable/suitecrm] Move chart to distributed bitnami repository
  stable/suitecrm/Chart.yaml
  stable/suitecrm/README.md
  stable/suitecrm/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21414 [stable/testlink] Move chart to distributed bitnami repository
  stable/testlink/Chart.yaml
  stable/testlink/README.md
  stable/testlink/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21415 [stable/wordpress] Move chart to distributed bitnami repository
  stable/wordpress/Chart.yaml
  stable/wordpress/README.md
  stable/wordpress/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21416 [stable/nats] Move chart to distributed bitnami repository
  stable/nats/Chart.yaml
  stable/nats/README.md
  stable/nats/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21417 [stable/mariadb] Move chart to distributed bitnami repository
  stable/mariadb/Chart.yaml
  stable/mariadb/README.md
  stable/mariadb/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21418 [stable/redmine] Move chart to distributed bitnami repository
  stable/redmine/Chart.yaml
  stable/redmine/README.md
  stable/redmine/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21380 [stable/falco] Make kernel module dir writable
  stable/falco/CHANGELOG.md
  stable/falco/Chart.yaml
  stable/falco/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#21391 [stable/jasperreports] Move chart to distributed bitnami repository
  stable/jasperreports/Chart.yaml
  stable/jasperreports/README.md
  stable/jasperreports/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21392 [stable/joomla] Move chart to distributed bitnami repository
  stable/joomla/Chart.yaml
  stable/joomla/README.md
  stable/joomla/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21394 [stable/dokuwiki] Move chart to distributed bitnami repository
  stable/dokuwiki/Chart.yaml
  stable/dokuwiki/README.md
  stable/dokuwiki/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21395 [stable/drupal] Move chart to distributed bitnami repository
  stable/drupal/Chart.yaml
  stable/drupal/README.md
  stable/drupal/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21397 [stable/ghost] Move chart to distributed bitnami repository
  stable/ghost/Chart.yaml
  stable/ghost/README.md
  stable/ghost/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21399 [stable/mediawiki] Move chart to distributed bitnami repository
  stable/mediawiki/Chart.yaml
  stable/mediawiki/README.md
  stable/mediawiki/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21400 [stable/moodle] Move chart to distributed bitnami repository
  stable/moodle/Chart.yaml
  stable/moodle/README.md
  stable/moodle/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21402 [stable/orangehrm] Move chart to distributed bitnami repository
  stable/orangehrm/Chart.yaml
  stable/orangehrm/README.md
  stable/orangehrm/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21403 [stable/osclass] Move chart to distributed bitnami repository
  stable/osclass/Chart.yaml
  stable/osclass/README.md
  stable/osclass/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21404 [stable/owncloud] Move chart to distributed bitnami repository
  stable/owncloud/Chart.yaml
  stable/owncloud/README.md
  stable/owncloud/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21405 [stable/opencart] Move chart to distributed bitnami repository
  stable/opencart/Chart.yaml
  stable/opencart/README.md
  stable/opencart/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21406 [stable/odoo] Move chart to distributed bitnami repository
  stable/odoo/Chart.yaml
  stable/odoo/README.md
  stable/odoo/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21409 [stable/prestashop] Move chart to distributed bitnami repository
  stable/prestashop/Chart.yaml
  stable/prestashop/README.md
  stable/prestashop/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21412 [stable/phpbb] Move chart to distributed bitnami repository
  stable/phpbb/Chart.yaml
  stable/phpbb/README.md
  stable/phpbb/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21423 [stable/airflow] adding podLabels to web, scheduler, flower and worker pods
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/templates/deployments-flower.yaml
  stable/airflow/templates/deployments-scheduler.yaml
  stable/airflow/templates/deployments-web.yaml
  stable/airflow/templates/statefulsets-workers.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#21373 [stable/minio] tls scheme variable incorrectly scoped
  stable/minio/Chart.yaml
  stable/minio/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#21369 [stable/datadog] add `datadog.env` in all containers
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/templates/containers-common-env.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#21424 [stable/prometheus-pushgateway] upgrade to latest release
  stable/prometheus-pushgateway/Chart.yaml
  stable/prometheus-pushgateway/README.md
  stable/prometheus-pushgateway/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#21385 [incubator/haproxy-ingress] Made terminationGracePeriodSeconds configurable
  incubator/haproxy-ingress/Chart.yaml
  incubator/haproxy-ingress/README.md
  incubator/haproxy-ingress/templates/controller-daemonset.yaml
  incubator/haproxy-ingress/templates/controller-deployment.yaml
  incubator/haproxy-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21420 [stable/datadog] Introduce processAgent.processCollection
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/container-process-agent.yaml
  stable/datadog/templates/daemonset.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#21426 stable/airflow: revert initdb order change
  stable/airflow/Chart.yaml
  stable/airflow/templates/deployments-scheduler.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#21436 [stable/falco] certs configuration and service for Falco gRPC server
  stable/falco/CHANGELOG.md
  stable/falco/Chart.yaml
  stable/falco/README.md
  stable/falco/templates/configmap.yaml
  stable/falco/templates/daemonset.yaml
  stable/falco/templates/secret-certs.yaml
  stable/falco/templates/service.yaml
  stable/falco/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#21435 [stable/newrelic-infrastructure] Upgrade the New Relic k8s integration to v1.16.0
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/README.md
  stable/newrelic-infrastructure/templates/daemonset.yaml
  stable/newrelic-infrastructure/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#21431 [stable/grafana] adding examples for enabling githubauth
  stable/grafana/Chart.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20613 [stable/kafka-manager] Ensure manager job gets run on an amd64 node in hybrid clusters
  stable/kafka-manager/Chart.yaml
  stable/kafka-manager/templates/job.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21455 [stable/chartmuseum] Add serviceMonitor to chartmuseum chart
  stable/chartmuseum/Chart.yaml
  stable/chartmuseum/README.md
  stable/chartmuseum/templates/servicemonitor.yaml
  stable/chartmuseum/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21386 [stable/datadog] Fix typo and update docs
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/templates/container-agent.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21447 [stable/minio] Fix templating error starting with go 1.14 (#21446)
  stable/minio/Chart.yaml
  stable/minio/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#20917 [stable/spinnaker] update spinnaker dependencies
  stable/spinnaker/Chart.yaml
  stable/spinnaker/requirements.lock
  stable/spinnaker/requirements.yaml
  stable/spinnaker/templates/configmap/halyard-config.yaml
  stable/spinnaker/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21340 [stable/kube-state-metrics] Add PodDisruptionBudget
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
  stable/kube-state-metrics/templates/pdb.yaml
  stable/kube-state-metrics/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19985 [stable/prometheus-snmp-exporter] Fix serviceMonitor params
  stable/prometheus-snmp-exporter/Chart.yaml
  stable/prometheus-snmp-exporter/README.md
  stable/prometheus-snmp-exporter/templates/servicemonitor.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21448 [stable/openebs] update openebs charts to 1.8.0 release
  stable/openebs/Chart.yaml
  stable/openebs/README.md
  stable/openebs/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21466 [stable/jenkins] Add `master.jenkinsHome` and `master.jenkinsRef` options
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/config.yaml
  stable/jenkins/templates/jenkins-backup-cronjob.yaml
  stable/jenkins/templates/jenkins-master-deployment.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M
