Repository helm/charts, pull requests merged in 2020-05, with the labels that each got.

#22163 Updated README to match what's in the README of operator itself
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#22214 [stable/airflow] partially revert #22162
  stable/airflow/Chart.yaml
  stable/airflow/templates/configmap-git-clone.yaml
  stable/airflow/templates/deployments-scheduler.yaml
  stable/airflow/templates/deployments-web.yaml
  stable/airflow/templates/statefulsets-workers.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#22075 [stable/grafana] Removed extra schedulerName field
  stable/grafana/Chart.yaml
  stable/grafana/templates/_pod.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22213 [stable/grafana] Much cleaner sed expression without backslashes.
  stable/grafana/Chart.yaml
  stable/grafana/templates/configmap.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22225 [stable/nextcloud] support statically assigning nodePort
  stable/nextcloud/Chart.yaml
  stable/nextcloud/README.md
  stable/nextcloud/templates/service.yaml
  stable/nextcloud/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22226 [stable/nextcloud] Fix pullPolicy default in README
  stable/nextcloud/Chart.yaml
  stable/nextcloud/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#21900 [stable/elasticsearch-exporter] Add option to disable client cert auth in Elasticsearch exporter
  stable/elasticsearch-exporter/Chart.yaml
  stable/elasticsearch-exporter/README.md
  stable/elasticsearch-exporter/templates/deployment.yaml
  stable/elasticsearch-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22197 [stable/nextcloud] Remove broken attempt to mute logging of assets
  stable/nextcloud/Chart.yaml
  stable/nextcloud/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22097 [stable/sealed-secrets] Do not set port names.
  stable/sealed-secrets/Chart.yaml
  stable/sealed-secrets/templates/service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21202 [stable/fluentd] Fix missing serviceName in HPA
  stable/fluentd/Chart.yaml
  stable/fluentd/templates/_helpers.tpl
  stable/fluentd/templates/hpa.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22242 [stable/airflow] allow specification of probe scheme
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/templates/deployments-web.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#22246 [stable/datadog] Remove old and misleading KSM option from value file
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#22239 [stable/prometheus-operator] Use servicePerReplica.port for the ingressPerReplica port value
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/prometheus/ingressperreplica.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21636 [stable/elasticsearch-exporter] Add options to set relabel configuration for metrics
  stable/elasticsearch-exporter/Chart.yaml
  stable/elasticsearch-exporter/README.md
  stable/elasticsearch-exporter/templates/servicemonitor.yaml
  stable/elasticsearch-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22221 [stable/spring-cloud-data-flow] Use release namespace for prometheus-proxy serviceaccount
  stable/spring-cloud-data-flow/Chart.yaml
  stable/spring-cloud-data-flow/templates/prometheus-proxy-clusterrolebinding.yaml
  stable/spring-cloud-data-flow/templates/prometheus-proxy-serviceaccount.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#22134 [stable/locust] Fixes the format of the tolerations parameter
  stable/locust/Chart.yaml
  stable/locust/README.md
  stable/locust/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22247 [stable/prometheus-operator]: Fix typo in Helm hook
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/crds/crd-thanosrulers.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22249 [stable/prometheus-operator]Fix range loop for ingresses
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/alertmanager/ingressperreplica.yaml
  stable/prometheus-operator/templates/prometheus/ingressperreplica.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22193 [stable/anchor-engine] Fix broken update bash command
  stable/anchore-engine/Chart.yaml
  stable/anchore-engine/templates/engine_upgrade_job.yaml
  stable/anchore-engine/templates/enterprise_upgrade_job.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#22251 [stable/grafana] Adding option into securityContext for setting primary group ID for containers in POD
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/NOTES.txt
  stable/grafana/templates/_pod.tpl
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22244 [stable/datadog] KSM update and add doc for secret creation
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/requirements.lock
  stable/datadog/requirements.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#22260 [stable/sysdig] Upgrade to latest Sysdig Agent version (10.0.0)
  stable/sysdig/CHANGELOG.md
  stable/sysdig/Chart.yaml
  stable/sysdig/README.md
  stable/sysdig/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#22261 [stable/airflow] Changed eq to and
  stable/airflow/Chart.yaml
  stable/airflow/templates/configmap-git-clone.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#22218 [stable/superset] fix init startup script for superset entrypoint.
  stable/superset/Chart.yaml
  stable/superset/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22168 [incubator/kafka] fix commands documentation in NOTES.txt
  incubator/kafka/Chart.yaml
  incubator/kafka/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22274 [stable/airflow] Added resources limit to git-clone initcontainer
  stable/airflow/Chart.yaml
  stable/airflow/templates/deployments-scheduler.yaml
  stable/airflow/templates/deployments-web.yaml
  stable/airflow/templates/statefulsets-workers.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#21532 [stable/datadog] adding init container resource requests to the system probe init container
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/templates/system-probe-init.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22281 [stable/airflow] Fix handling of multiline vars
  stable/airflow/Chart.yaml
  stable/airflow/templates/configmap-variables-pools.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#22254 [stable/spring-cloud-data-flow] Add Ingress resource
  stable/spring-cloud-data-flow/Chart.yaml
  stable/spring-cloud-data-flow/README.md
  stable/spring-cloud-data-flow/templates/NOTES.txt
  stable/spring-cloud-data-flow/templates/ingress.yaml
  stable/spring-cloud-data-flow/templates/prometheus-proxy-service.yaml
  stable/spring-cloud-data-flow/templates/server-config.yaml
  stable/spring-cloud-data-flow/templates/server-deployment.yaml
  stable/spring-cloud-data-flow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/L

#22264 [stable/grafana] Add extraContainerVolumes
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/_pod.tpl
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21300 [stable/datadog] Make the datadog agent resilient to docker daemon restarts
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/_helpers.tpl
  stable/datadog/templates/container-agent.yaml
  stable/datadog/templates/container-process-agent.yaml
  stable/datadog/templates/container-trace-agent.yaml
  stable/datadog/templates/containers-common-env.yaml
  stable/datadog/templates/containers-init-linux.yaml
  stable/datadog/templates/daemonset.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#22290 [stable/k8s-spot-termination-handler] add security context definition
  stable/k8s-spot-termination-handler/Chart.yaml
  stable/k8s-spot-termination-handler/README.md
  stable/k8s-spot-termination-handler/templates/daemonset.yaml
  stable/k8s-spot-termination-handler/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21390 [incubator/kafka] Added external.labels to external services
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
  incubator/kafka/templates/service-brokers-external.yaml
  incubator/kafka/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22293 [stable/nextcloud] Create option to specify extra deployment volumes
  stable/nextcloud/Chart.yaml
  stable/nextcloud/README.md
  stable/nextcloud/templates/deployment.yaml
  stable/nextcloud/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22297 [stable/airflow] added option to specify git-clone initContainer custom resources
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/templates/deployments-scheduler.yaml
  stable/airflow/templates/deployments-web.yaml
  stable/airflow/templates/statefulsets-workers.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#22308 [stable/spring-cloud-data-flow] Support for extra env vars
  stable/spring-cloud-data-flow/Chart.yaml
  stable/spring-cloud-data-flow/README.md
  stable/spring-cloud-data-flow/templates/server-deployment.yaml
  stable/spring-cloud-data-flow/templates/skipper-deployment.yaml
  stable/spring-cloud-data-flow/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#22313 [stable/spring-cloud-data-flow] Update to new SCDF version 2.5.0
  stable/spring-cloud-data-flow/Chart.yaml
  stable/spring-cloud-data-flow/README.md
  stable/spring-cloud-data-flow/templates/server-config.yaml
  stable/spring-cloud-data-flow/templates/server-deployment.yaml
  stable/spring-cloud-data-flow/templates/skipper-deployment.yaml
  stable/spring-cloud-data-flow/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#22300 [stable/prometheus] Configure enableServiceLinks for server
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/server-statefulset.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21793 [stable/karma] change default livenessProbe.path to /health
  stable/karma/Chart.yaml
  stable/karma/README.md
  stable/karma/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#21940 [stable/kong] mark the chart as deprecated
  stable/kong/Chart.yaml
  stable/kong/ci/test1-values.yaml
  stable/kong/ci/test2-values.yaml
  stable/kong/ci/test3-values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#21819 [stable/rabbitmq-ha] Fix timeouts in liveness/readiness probe
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22283 [stable/jenkins] Make node executor mode configurable
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/_helpers.tpl
  stable/jenkins/templates/config.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22210 [stable/selenium] Add liveness probes and preStop hooks on browsers
  stable/selenium/Chart.yaml
  stable/selenium/README.md
  stable/selenium/templates/chrome-daemonset.yaml
  stable/selenium/templates/chrome-deployment.yaml
  stable/selenium/templates/chromeDebug-daemonset.yaml
  stable/selenium/templates/chromeDebug-deployment.yaml
  stable/selenium/templates/firefox-daemonset.yaml
  stable/selenium/templates/firefox-deployment.yaml
  stable/selenium/templates/firefoxDebug-daemonset.yaml
  stable/selenium/templates/firefoxDebug-deployment.yaml
  stable/selenium/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#22325 [stable/spark-history-server] add Custom S3 endpoint option
  stable/spark-history-server/Chart.yaml
  stable/spark-history-server/README.md
  stable/spark-history-server/templates/deployment.yaml
  stable/spark-history-server/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#22321 [stable/rocketchart] updated repository and tag
  stable/rocketchat/Chart.yaml
  stable/rocketchat/README.md
  stable/rocketchat/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22335 [stable/airflow] DAGs serialization without git-sync for web pods
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/templates/configmap-env.yaml
  stable/airflow/templates/deployments-web.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#22349 [stable/prometheus] to 2.18.1
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22320 [stable/metabase] Upgrade metabase to 0.35.3
  stable/metabase/Chart.yaml
  stable/metabase/README.md
  stable/metabase/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22333 [stable/kube2iam] bump kube2iam image and appVersion to v0.10.9
  stable/kube2iam/Chart.yaml
  stable/kube2iam/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#22315 [stable/chartmuseum] Update apiVersion for Kubernetes 1.16 support
  stable/chartmuseum/Chart.yaml
  stable/chartmuseum/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22302 #22269 [cluster-autoscaler] Adding cluster-autoscaler-priority-expander Config Map
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/README.md
  stable/cluster-autoscaler/templates/priority-expander-configmap.yaml
  stable/cluster-autoscaler/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22350 [stable/prometheus] Fix default non-HA state for alert-manager statefulset
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/alertmanager-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22369 [Sealed secrets/optional] runAs and fsGroup have to be optional
  stable/sealed-secrets/Chart.yaml
  stable/sealed-secrets/README.md
  stable/sealed-secrets/templates/deployment.yaml
  stable/sealed-secrets/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22362 [stable/home-assistant]: ServiceMonitor bearerTokenSecret requires a SecretKeySelector
  stable/home-assistant/Chart.yaml
  stable/home-assistant/templates/servicemonitor.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22379 [stable/datadog] Update the example for `datadog.securityContext`
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22372 [stable/openebs] Add the opportunity to change docker registry
  stable/openebs/Chart.yaml
  stable/openebs/README.md
  stable/openebs/templates/daemonset-ndm.yaml
  stable/openebs/templates/deployment-admission-server.yaml
  stable/openebs/templates/deployment-local-provisioner.yaml
  stable/openebs/templates/deployment-maya-apiserver.yaml
  stable/openebs/templates/deployment-maya-provisioner.yaml
  stable/openebs/templates/deployment-maya-snapshot-operator.yaml
  stable/openebs/templates/deployment-ndm-operator.yaml
  stable/openebs/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22319 [stable/anchore-engine] use capabilities in order to support older in…
  stable/anchore-engine/Chart.yaml
  stable/anchore-engine/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#22326 [stable/aws-iam-authenticator] Add apps/v1 support
  stable/aws-iam-authenticator/Chart.yaml
  stable/aws-iam-authenticator/templates/_helpers.tpl
  stable/aws-iam-authenticator/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22384 [stable/cerebro] bump image
  stable/cerebro/Chart.yaml
  stable/cerebro/README.md
  stable/cerebro/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22318 [stable/jenkins] Jenkins default configuration options
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/_helpers.tpl
  stable/jenkins/templates/config.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22387 [stable/nextcloud] possibility to change deploy strategy
  stable/nextcloud/Chart.yaml
  stable/nextcloud/README.md
  stable/nextcloud/templates/deployment.yaml
  stable/nextcloud/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22386 [stable/prometheus] Fix default non-HA state for alertmanager
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/alertmanager-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21796 [stable/prometheus-blackbox-exporter] Add pod security policy
  stable/prometheus-blackbox-exporter/Chart.yaml
  stable/prometheus-blackbox-exporter/README.md
  stable/prometheus-blackbox-exporter/templates/daemonset.yaml
  stable/prometheus-blackbox-exporter/templates/podsecuritypolicy.yaml
  stable/prometheus-blackbox-exporter/templates/role.yaml
  stable/prometheus-blackbox-exporter/templates/rolebinding.yaml
  stable/prometheus-blackbox-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22181 [stable/oauth2-proxy] Add podSecurityContext
  stable/oauth2-proxy/Chart.yaml
  stable/oauth2-proxy/README.md
  stable/oauth2-proxy/ci/pod-security-context-values.yaml
  stable/oauth2-proxy/templates/deployment.yaml
  stable/oauth2-proxy/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22224 [stable/dex] Make web.allowedOrigins configurable using values file
  stable/dex/Chart.yaml
  stable/dex/README.md
  stable/dex/templates/secret.yaml
  stable/dex/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22201 [stable/prometheus-blackbox-exporter] Add vars for liveness and readyness
  stable/prometheus-blackbox-exporter/Chart.yaml
  stable/prometheus-blackbox-exporter/README.md
  stable/prometheus-blackbox-exporter/templates/daemonset.yaml
  stable/prometheus-blackbox-exporter/templates/deployment.yaml
  stable/prometheus-blackbox-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22391 [stable/prometheus] Fix incorrect rendering of enableServiceLinks
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/server-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22396 [stable/autoscaler] scale-down-delay parameter name
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#22398 stable/prometheus-operator README.md markup fix
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22410 [stable/openebs]: update openebs charts to 1.10.0 release
  stable/openebs/Chart.yaml
  stable/openebs/README.md
  stable/openebs/templates/clusterrole.yaml
  stable/openebs/templates/daemonset-ndm.yaml
  stable/openebs/templates/deployment-maya-apiserver.yaml
  stable/openebs/templates/deployment-ndm-operator.yaml
  stable/openebs/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#22316 [stable/docker-registry] Update apiVersion for Kubernetes 1.16 support
  stable/docker-registry/Chart.yaml
  stable/docker-registry/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22414 [stable/datadog] Update the DCA RBAC to allow it to create events in the HPA
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/templates/agent-rbac.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#22158 [incubator/solr] Fix messed up configuration option table
  incubator/solr/Chart.yaml
  incubator/solr/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22380 [stable/grafana] Fix typo
  stable/grafana/Chart.yaml
  stable/grafana/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21531 [incubator/solr]. Add support for tolerations
  incubator/solr/Chart.yaml
  incubator/solr/README.md
  incubator/solr/templates/statefulset.yaml
  incubator/solr/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22406 [stable/nginx-ingress] to 0.32.0
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22420 [stable/kube-state-metrics] Version bump to 1.9.6
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
  stable/kube-state-metrics/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#22403 [stable/jenkins] add k8s plugin config parameters
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/_helpers.tpl
  stable/jenkins/templates/config.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22419 [stable/fluent-bit] Enabling dnsConfig option in the Chart
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/daemonset.yaml
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21605 [stable/kube2iam] - add labels to ServiceMonitor
  stable/kube2iam/Chart.yaml
  stable/kube2iam/README.md
  stable/kube2iam/templates/servicemonitor.yaml
  stable/kube2iam/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21986 [incubator/patroni] Update patroni to 1.5-p5
  incubator/patroni/Chart.yaml
  incubator/patroni/README.md
  incubator/patroni/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22378 [stable/prometheus] Add Namespace to applicable Resources
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/_helpers.tpl
  stable/prometheus/templates/alertmanager-clusterrolebinding.yaml
  stable/prometheus/templates/alertmanager-configmap.yaml
  stable/prometheus/templates/alertmanager-deployment.yaml
  stable/prometheus/templates/alertmanager-ingress.yaml
  stable/prometheus/templates/alertmanager-networkpolicy.yaml
  stable/prometheus/templates/alertmanager-pdb.yaml
  stable/prometheus/templates/alertmanager-pvc.yaml
  stable/prometheus/templates/alertmanager-service-headless.yaml
  stable/prometheus/templates/alertmanager-service.yaml
  stable/prometheus/templates/alertmanager-serviceaccount.yaml
  stable/prometheus/templates/alertmanager-statefulset.yaml
  stable/prometheus/templates/node-exporter-daemonset.yaml
  stable/prometheus/templates/node-exporter-role.yaml
  stable/prometheus/templates/node-exporter-rolebinding.yaml
  stable/prometheus/templates/node-exporter-service.yaml
  stable/prometheus/templates/node-exporter-serviceaccount.yaml
  stable/prometheus/templates/pushgateway-clusterrolebinding.yaml
  stable/prometheus/templates/pushgateway-deployment.yaml
  stable/prometheus/templates/pushgateway-ingress.yaml
  stable/prometheus/templates/pushgateway-networkpolicy.yaml
  stable/prometheus/templates/pushgateway-pdb.yaml
  stable/prometheus/templates/pushgateway-pvc.yaml
  stable/prometheus/templates/pushgateway-service.yaml
  stable/prometheus/templates/pushgateway-serviceaccount.yaml
  stable/prometheus/templates/server-clusterrolebinding.yaml
  stable/prometheus/templates/server-configmap.yaml
  stable/prometheus/templates/server-deployment.yaml
  stable/prometheus/templates/server-ingress.yaml
  stable/prometheus/templates/server-networkpolicy.yaml
  stable/prometheus/templates/server-pdb.yaml
  stable/prometheus/templates/server-pvc.yaml
  stable/prometheus/templates/server-service-headless.yaml
  stable/prometheus/templates/server-service.yaml
  stable/prometheus/templates/server-serviceaccount.yaml
  stable/prometheus/templates/server-statefulset.yaml
  stable/prometheus/templates/server-vpa.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22432 stable/unifi implements subPath functionality
  stable/unifi/Chart.yaml
  stable/unifi/README.md
  stable/unifi/templates/deployment.yaml
  stable/unifi/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22400 [stable/jenkins] Adding override for ingress paths
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/jenkins-master-ingress.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22434 [incubator/sparkoperator] Add webhookNamespaceSelector
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/README.md
  incubator/sparkoperator/ci/test-values.yaml
  incubator/sparkoperator/templates/spark-operator-deployment.yaml
  incubator/sparkoperator/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#22431 [stable/jenkins] Render agent.nodeSelector in pod template JCasC
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/ci/other-values.yaml
  stable/jenkins/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, size/S

#22437 [stable/neo4j] Deprecated. replacement: https://github.com/neo4j-contrib/neo4j-helm
  stable/neo4j/Chart.yaml
  stable/neo4j/README.md
  stable/neo4j/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, size/S

#22438 [stable/spring-cloud-data-flow] Update to new SCDF version 2.5.1
  stable/spring-cloud-data-flow/Chart.yaml
  stable/spring-cloud-data-flow/README.md
  stable/spring-cloud-data-flow/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#22124 [stable/jenkins] Cleanup agent.yamlTemplate rendering in XML config
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22440 [stable/anchore-engine] Allow loading custom CA certificate
  stable/anchore-engine/Chart.yaml
  stable/anchore-engine/templates/analyzer_deployment.yaml
  stable/anchore-engine/templates/api_deployment.yaml
  stable/anchore-engine/templates/catalog_deployment.yaml
  stable/anchore-engine/templates/engine_upgrade_job.yaml
  stable/anchore-engine/templates/enterprise_feeds_deployment.yaml
  stable/anchore-engine/templates/enterprise_upgrade_job.yaml
  stable/anchore-engine/templates/policy_engine_deployment.yaml
  stable/anchore-engine/templates/simplequeue_deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#22007 [stable/graylog] Adding option to define environment variables in raw yaml format
  stable/graylog/Chart.yaml
  stable/graylog/README.md
  stable/graylog/templates/statefulset.yaml
  stable/graylog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22445 [stable/openebs]: fix README image repository typo
  stable/openebs/Chart.yaml
  stable/openebs/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21756 stable/chartmuseum fix: missing labels in secret object
  stable/chartmuseum/Chart.yaml
  stable/chartmuseum/README.md
  stable/chartmuseum/templates/secret.yaml
  stable/chartmuseum/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22005 [stable/rabbitmq-ha] add configuration for initContainer
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/templates/statefulset.yaml
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#22439 [stable/efs-provisioner] Add podLabels support
  stable/efs-provisioner/Chart.yaml
  stable/efs-provisioner/README.md
  stable/efs-provisioner/templates/deployment.yaml
  stable/efs-provisioner/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22241 [stable/mongodb-replicaset] Update MongoDB Exporter
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/README.md
  stable/mongodb-replicaset/templates/mongodb-statefulset.yaml
  stable/mongodb-replicaset/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22451 [stable/anchore-engine] Fix upgrade jobs
  stable/anchore-engine/Chart.yaml
  stable/anchore-engine/templates/analyzer_deployment.yaml
  stable/anchore-engine/templates/api_deployment.yaml
  stable/anchore-engine/templates/catalog_deployment.yaml
  stable/anchore-engine/templates/engine_upgrade_job.yaml
  stable/anchore-engine/templates/enterprise_feeds_deployment.yaml
  stable/anchore-engine/templates/enterprise_ui_deployment.yaml
  stable/anchore-engine/templates/enterprise_upgrade_job.yaml
  stable/anchore-engine/templates/policy_engine_deployment.yaml
  stable/anchore-engine/templates/simplequeue_deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#22457 [stable/datadog] Allow pre-release versions as docker image tag
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22442 [stable/airflow] update to airflow 1.10.10
  stable/airflow/Chart.yaml
  stable/airflow/OWNERS
  stable/airflow/README.md
  stable/airflow/examples/minikube-values.yaml
  stable/airflow/requirements.yaml
  stable/airflow/templates/NOTES.txt
  stable/airflow/templates/_helpers.tpl
  stable/airflow/templates/configmap-env.yaml
  stable/airflow/templates/configmap-git-clone.yaml
  stable/airflow/templates/configmap-scripts.yaml
  stable/airflow/templates/configmap-variables-pools.yaml
  stable/airflow/templates/deployments-flower.yaml
  stable/airflow/templates/deployments-scheduler.yaml
  stable/airflow/templates/deployments-web.yaml
  stable/airflow/templates/hpa-worker.yaml
  stable/airflow/templates/ingress-flower.yaml
  stable/airflow/templates/ingress-web.yaml
  stable/airflow/templates/monitoring-prometheus-rule.yaml
  stable/airflow/templates/monitoring-service-monitor.yaml
  stable/airflow/templates/pdb-sheduler.yaml
  stable/airflow/templates/poddisruptionbudget.yaml
  stable/airflow/templates/pvc-logs.yaml
  stable/airflow/templates/pvc.yaml
  stable/airflow/templates/role-binding.yaml
  stable/airflow/templates/role.yaml
  stable/airflow/templates/secret-connections.yaml
  stable/airflow/templates/service-account.yaml
  stable/airflow/templates/service-flower.yaml
  stable/airflow/templates/service-web.yaml
  stable/airflow/templates/service-worker.yaml
  stable/airflow/templates/statefulsets-workers.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XXL

#22216 [stable/kured] Update kured to 1.4.0
  stable/kured/Chart.yaml
  stable/kured/README.md
  stable/kured/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22330 [stable/cerebro] mixed up liveness and readiness probe conditions
  stable/cerebro/Chart.yaml
  stable/cerebro/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22453 [stable/unifi] Adding secretName variable to customCert
  stable/unifi/Chart.yaml
  stable/unifi/README.md
  stable/unifi/templates/deployment.yaml
  stable/unifi/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22460 [stable/hazelcast] Merge pull request #121 from eminn/fix-custom-volume
  stable/hazelcast/Chart.yaml
  stable/hazelcast/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#22455 [stable/grafana] Remove duplicate roleref in grafana rolebinding
  stable/grafana/Chart.yaml
  stable/grafana/templates/rolebinding.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22471 [stable/airflow] 7.0.1 hotfix
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/templates/_helpers.tpl
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#22470 [stable/minio] Fix TLS can't be enabled
  stable/minio/Chart.yaml
  stable/minio/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22443 [stable/jenkins] Render agent.envVars in kubernetes pod template JCasC
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/ci/other-values.yaml
  stable/jenkins/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22272 [stable/prometheus-cloudwatch-exporter] Enable to set an existing service account name
  stable/prometheus-cloudwatch-exporter/Chart.yaml
  stable/prometheus-cloudwatch-exporter/README.md
  stable/prometheus-cloudwatch-exporter/templates/_helpers.tpl
  stable/prometheus-cloudwatch-exporter/templates/clusterrolebinding.yaml
  stable/prometheus-cloudwatch-exporter/templates/deployment.yaml
  stable/prometheus-cloudwatch-exporter/templates/serviceaccount.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22476 [stable/graylog] allow image pull secrects in graylog and cleaned up README.md
  stable/graylog/Chart.yaml
  stable/graylog/README.md
  stable/graylog/templates/statefulset.yaml
  stable/graylog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#22469 [stable/mysql] MySQL chart version bump to 1.6.4
  stable/mysql/Chart.yaml
  stable/mysql/templates/deployment.yaml
  stable/mysql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22425 [stable/nginx-ingress] Add support for controller SA annotations
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-serviceaccount.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21880 [incubator/zookeeper] Ensure headless service force registers DNS
  incubator/zookeeper/Chart.yaml
  incubator/zookeeper/templates/service-headless.yaml
  incubator/zookeeper/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22482 [stable/newrelic-infrastructure] Update image version to 1.21.0
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/README.md
  stable/newrelic-infrastructure/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22495 [stable/kube-state-metrics]disable VPA collectors by default
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#22405 [stable/cluster-autoscaler] Fix default image on README
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22122 [stable/kube-state-metrics] Allow specification of additional volume types in podSecurityPolicy of kube-state-metrics
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
  stable/kube-state-metrics/templates/podsecuritypolicy.yaml
  stable/kube-state-metrics/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22505 [stable/hazelcast] Fixes issue #105 (#127)
  stable/hazelcast/Chart.yaml
  stable/hazelcast/templates/mancenter-statefulset.yaml
  stable/hazelcast/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#22485 [stable/fluent-bit] Added output es Logstash_DateFormat parameter
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/config.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22436 [stable/datadog] Fixes "merging map" warning messages with Helm 2
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22506 [stable/airflow] 7.1.0 release
  stable/airflow/.helmignore
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/UPGRADE.md
  stable/airflow/examples/google-gke/custom-values.yaml
  stable/airflow/examples/google-gke/k8s_resources/certificate.yaml
  stable/airflow/examples/google-gke/k8s_resources/configmap-webserver.yaml
  stable/airflow/examples/google-gke/k8s_resources/secret-fernet-key.yaml
  stable/airflow/examples/google-gke/k8s_resources/secret-git-keys.yaml
  stable/airflow/examples/google-gke/k8s_resources/secret-mysql-password.yaml
  stable/airflow/examples/google-gke/k8s_resources/secret-redis-password.yaml
  stable/airflow/examples/minikube-values.yaml
  stable/airflow/examples/minikube/custom-values.yaml
  stable/airflow/templates/_helpers.tpl
  stable/airflow/templates/configmap-env.yaml
  stable/airflow/templates/configmap-scripts-git.yaml
  stable/airflow/templates/configmap-scripts.yaml
  stable/airflow/templates/deployments-flower.yaml
  stable/airflow/templates/deployments-scheduler.yaml
  stable/airflow/templates/deployments-web.yaml
  stable/airflow/templates/pvc-logs.yaml
  stable/airflow/templates/pvc.yaml
  stable/airflow/templates/statefulsets-workers.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XXL

#22513 [stable/sematext-agent] Use agent defaults for JOURNAL_DIR
  stable/sematext-agent/Chart.yaml
  stable/sematext-agent/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#22518 [stable/minecraft] Use mc-monitor instead of deprecated mcstatus command.
  stable/minecraft/Chart.yaml
  stable/minecraft/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#22493 [stable/graylog]: Update Graylog Ingress Api version.
  stable/graylog/Chart.yaml
  stable/graylog/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22523 [stable/airflow] 7.1.1 hotfix
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/UPGRADE.md
  stable/airflow/examples/google-gke/custom-values.yaml
  stable/airflow/examples/minikube/custom-values.yaml
  stable/airflow/templates/deployments-scheduler.yaml
  stable/airflow/templates/deployments-web.yaml
  stable/airflow/templates/pdb-sheduler.yaml
  stable/airflow/templates/statefulsets-workers.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#22463 [stable/datadog] ADD UDS socket for trace agent
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/ci/dogstastd-socket.yaml
  stable/datadog/templates/cluster-agent-deployment.yaml
  stable/datadog/templates/container-agent.yaml
  stable/datadog/templates/container-trace-agent.yaml
  stable/datadog/templates/containers-common-env.yaml
  stable/datadog/templates/daemonset-volumes-linux.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#22381 stable/chartmuseum: Allow to define a schedulerName
  stable/chartmuseum/Chart.yaml
  stable/chartmuseum/README.md
  stable/chartmuseum/templates/deployment.yaml
  stable/chartmuseum/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22462 [stable/nginx-ingress] Allow pulling images by digest
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/admission-webhooks/job-patch/job-createSecret.yaml
  stable/nginx-ingress/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
  stable/nginx-ingress/templates/controller-daemonset.yaml
  stable/nginx-ingress/templates/controller-deployment.yaml
  stable/nginx-ingress/templates/default-backend-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22489 [stable/ambassador] Flag ambassador chart as deprecated
  stable/ambassador/Chart.yaml
  stable/ambassador/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, size/S

#22543 [stable/elastalert] Support referencing ES credentials from secret
  stable/elastalert/Chart.yaml
  stable/elastalert/README.md
  stable/elastalert/templates/deployment.yaml
  stable/elastalert/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#22501 stable/opa Updating documentation in values.yaml
  stable/opa/Chart.yaml
  stable/opa/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22408 [stable/jenkins] Configure UI security in default JCasC
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/ci/casc-values.yaml
  stable/jenkins/templates/_helpers.tpl
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22503 [stable/openebs] Add support for configurable filterconfigs.state.
  stable/openebs/Chart.yaml
  stable/openebs/README.md
  stable/openebs/templates/cm-node-disk-manager.yaml
  stable/openebs/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22563 [stable/graylog] Fixed Graylog readme.md - Incorrectly named variable
  stable/graylog/Chart.yaml
  stable/graylog/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22549 [stable/hazelcast] inject checksum of hazelcast.yaml into statefulset as an annotion (#126)
  stable/hazelcast/Chart.yaml
  stable/hazelcast/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#22541 [stable/prometheus-redis-exporter] fix targetLabels
  stable/prometheus-redis-exporter/Chart.yaml
  stable/prometheus-redis-exporter/templates/servicemonitor.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22530 [stable/jenkins] add existingSecret for admin credentials
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/jenkins-master-deployment.yaml
  stable/jenkins/templates/secret.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22568 [stable/sematext-agent] enable pods/log cluster roles
  stable/sematext-agent/Chart.yaml
  stable/sematext-agent/templates/clusterrole.yaml
  stable/sematext-agent/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#22562 [stable/datadog] Add affinity to cluster agent deployment
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22526 [stable/jenkins] Added auto detection for Ingress API Version
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/jenkins-master-ingress.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#22581 [stable/gocd] Bump up GoCD Version to 20.4.0
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#22525 [stable/mercure] Automatically Roll Deployments
  stable/mercure/Chart.yaml
  stable/mercure/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#20905 [stable/openldap] Fix helm3 ClusterIP updates
  stable/openldap/Chart.yaml
  stable/openldap/README.md
  stable/openldap/templates/service.yaml
  stable/openldap/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22585 [stable/mercure] Add support for Mercure 0.10
  stable/mercure/Chart.yaml
  stable/mercure/README.md
  stable/mercure/templates/configmap.yaml
  stable/mercure/templates/deployment.yaml
  stable/mercure/templates/secret.yaml
  stable/mercure/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22584 [stable/datadog] Fix an agent warning at startup because of a deprecated parameter
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/templates/container-agent.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#22579 [stable/nginx-ldapauth-proxy] Remove deprecated APIversion
  stable/nginx-ldapauth-proxy/Chart.yaml
  stable/nginx-ldapauth-proxy/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22589 [stable/datadog] Fix templating errors when passing the cluster agent config as yaml
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/templates/cluster-agent-config-configmap.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#22567 [stable/jenkins] Allow templating of all string values except type for kubernetes volumes plugin xml
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22597 [incubator/sparkoperator] Upgraded the image version
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/README.md
  incubator/sparkoperator/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#19827 [stable/traefik] Add more options for Prometheus Service
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/templates/prometheus-service.yaml
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22588 [incubator/fluentd-cloudwatch] Update api version for daemonset to apps/v1
  incubator/fluentd-cloudwatch/Chart.yaml
  incubator/fluentd-cloudwatch/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS
