Repository helm/charts, pull requests merged in 2020-07, with the labels that each got.

#23006 [stable/grafana] Create grafana secret for ldap even if admin password is passed via file
  stable/grafana/Chart.yaml
  stable/grafana/templates/secret.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22879 [stable/prometheus-operator] Ensure all rules can be toggled
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/hack/sync_prometheus_rules.py
  stable/prometheus-operator/templates/prometheus/rules-1.14/kube-prometheus-general.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kube-state-metrics.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubelet.rules.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23030 incubator/kube-downscaler - fix a regression about namespaces
  incubator/kube-downscaler/Chart.yaml
  incubator/kube-downscaler/README.md
  incubator/kube-downscaler/templates/clusterrole.yaml
  incubator/kube-downscaler/templates/deployment.yaml
  incubator/kube-downscaler/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23028 [stable/prometheus-cloudwatch-exporter] additional docu on service account usage
  stable/prometheus-cloudwatch-exporter/Chart.yaml
  stable/prometheus-cloudwatch-exporter/README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#22950 [stable/karma] Upgrade karma to v0.68
  stable/karma/Chart.yaml
  stable/karma/README.md
  stable/karma/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#22960 [stable/grafana] Fix sed replacing special sources
  stable/grafana/Chart.yaml
  stable/grafana/templates/configmap.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23013 [stable/coredns] Version bump to 1.7.0
  stable/coredns/Chart.yaml
  stable/coredns/README.md
  stable/coredns/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#23035 Mount system-probe.yaml in the process-agent container when enabled
  stable/datadog/Chart.yaml
  stable/datadog/templates/container-process-agent.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23015 [stable/prometheus] Fix rbac for get ingress info
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/server-clusterrole.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23045 [stable/jenkins] fix blueocean dependency issue
  stable/jenkins/Chart.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23056 [Stable/Efs-Provisioner] add namespace to deployment/sa
  stable/efs-provisioner/Chart.yaml
  stable/efs-provisioner/templates/deployment.yaml
  stable/efs-provisioner/templates/serviceaccount.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#23044 [incubator/druid] modify the default value by nano-quickstart to decrease memory cost
  incubator/druid/Chart.yaml
  incubator/druid/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22891 [stable/prometheus-operator] Update grafana Chart
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/requirements.lock
  stable/prometheus-operator/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23055 [stable/kured] Deprecate the kured-chart
  stable/kured/Chart.yaml
  stable/kured/README.md
  stable/kured/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22590 stable/grafana Grafana statefulset pod labels
  stable/grafana/Chart.yaml
  stable/grafana/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22580 [stable/cluster-autoscaler] Fix empty annotations
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/templates/serviceaccount.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22646 [stable/traefik] Update traefik version from 1.7.23 to 1.7.24
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22999 [stable/datadog] Fix a bunch of nil defaults
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22988 [stable/prometheus-operator] Replace configmap-reload image
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#23066 [stable/datadog] Merge several pending PRs
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/cluster-agent-deployment.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#22847 [stable/jenkins] Fix typo in document of stable jenkins
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#22927 [stable/prometheus-operator] kubelet servicemonitor skip tls verify
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/exporters/kubelet/servicemonitor.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22893 Added cacert option to Cerebro
  stable/cerebro/Chart.yaml
  stable/cerebro/README.md
  stable/cerebro/templates/configmap.yaml
  stable/cerebro/templates/deployment.yaml
  stable/cerebro/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21506 [stable/docker-registry] LoadBalancer settings
  stable/docker-registry/Chart.yaml
  stable/docker-registry/README.md
  stable/docker-registry/templates/service.yaml
  stable/docker-registry/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22638 [stable/mcrouter] create a template for api version
  stable/mcrouter/Chart.yaml
  stable/mcrouter/templates/_helpers.tpl
  stable/mcrouter/templates/daemonset.yaml
  stable/mcrouter/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#23004 [incubator/rundeck] envSecret, awsConfigSecret, kubeConfigSecret, extraConfigSecret, nginx req size
  incubator/rundeck/Chart.yaml
  incubator/rundeck/README.md
  incubator/rundeck/files/nginx/nginx.conf
  incubator/rundeck/templates/deployment.yaml
  incubator/rundeck/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#23052 [stable/grafana] trigger re-deployment if envRenderSecret has been changed.
  stable/grafana/Chart.yaml
  stable/grafana/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23073 [stable/prometheus-operator] Update hyperkube image
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22787 [stable/jenkins] increase retries for sidecar reload
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/config.yaml
  stable/jenkins/templates/jenkins-master-deployment.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#23076 [stable/sealed-secrets] update version to 0.12.4
  stable/sealed-secrets/Chart.yaml
  stable/sealed-secrets/README.md
  stable/sealed-secrets/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22529 [stable/datadog] Add PSP and SCC
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/ci/psp-test.yaml
  stable/datadog/templates/agent-psp.yaml
  stable/datadog/templates/agent-scc.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#23018 [stable/datadog] add orchestrator-explorer option
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/agent-rbac.yaml
  stable/datadog/templates/cluster-agent-deployment.yaml
  stable/datadog/templates/container-process-agent.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22706 [stable/jenkins] Add networkPolicy podLabels
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/jenkins-master-networkpolicy.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23060 [incubator/buzzfeed-sso] Split Deployment Support
  incubator/buzzfeed-sso/Chart.yaml
  incubator/buzzfeed-sso/README.md
  incubator/buzzfeed-sso/templates/NOTES.txt
  incubator/buzzfeed-sso/templates/auth-deployment.yaml
  incubator/buzzfeed-sso/templates/auth-service.yaml
  incubator/buzzfeed-sso/templates/configmap.yaml
  incubator/buzzfeed-sso/templates/google-secret.yaml
  incubator/buzzfeed-sso/templates/ingress.yaml
  incubator/buzzfeed-sso/templates/proxy-deployment.yaml
  incubator/buzzfeed-sso/templates/proxy-service.yaml
  incubator/buzzfeed-sso/templates/secret.yaml
  incubator/buzzfeed-sso/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#23080 [stable/datadog] Align ENV var handling (avoid ranging through them to allow any K8S valid syntax)
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/templates/agent-clusterchecks-deployment.yaml
  stable/datadog/templates/container-agent.yaml
  stable/datadog/templates/container-process-agent.yaml
  stable/datadog/templates/container-system-probe.yaml
  stable/datadog/templates/container-trace-agent.yaml
  stable/datadog/templates/containers-common-env.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#23088 [stable/datadog] fix PodSecurityContext seLinux section
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#22323 [stable/mongodb-replicaset] Make unguiculus/mongodb-install multiarch…
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/install/Makefile
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22931 [stable/selenium] Add ability to pass additional pod labels for all pods
  stable/selenium/Chart.yaml
  stable/selenium/README.md
  stable/selenium/templates/chrome-daemonset.yaml
  stable/selenium/templates/chrome-deployment.yaml
  stable/selenium/templates/chromeDebug-daemonset.yaml
  stable/selenium/templates/chromeDebug-deployment.yaml
  stable/selenium/templates/firefox-daemonset.yaml
  stable/selenium/templates/firefox-deployment.yaml
  stable/selenium/templates/firefoxDebug-daemonset.yaml
  stable/selenium/templates/firefoxDebug-deployment.yaml
  stable/selenium/templates/hub-deployment.yaml
  stable/selenium/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#23053 [stable/prometheus-pushgateway] Fix networkPolicy podSelector and ingress rule
  stable/prometheus-pushgateway/Chart.yaml
  stable/prometheus-pushgateway/templates/networkpolicy.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22947 [stable/mysql] Add support for extra environment variables (#22945)
  stable/mysql/Chart.yaml
  stable/mysql/README.md
  stable/mysql/templates/deployment.yaml
  stable/mysql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22164 [incubator/aws-alb-ingress-controller] Fix a typo in the aws-alb-ingress-controller chart README
  incubator/aws-alb-ingress-controller/Chart.yaml
  incubator/aws-alb-ingress-controller/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22494 [stabel/katafygio] Correct indentation of 'volumes' property
  stable/katafygio/Chart.yaml
  stable/katafygio/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23092 stable/cluster-autoscaler
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/README.md
  stable/cluster-autoscaler/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23075 [stable/mysql] MySQL chart version bump to 1.6.6
  stable/mysql/Chart.yaml
  stable/mysql/README.md
  stable/mysql/templates/tests/test.yaml
  stable/mysql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22971 [stable/mongodb-replicaset] Warning fixed, made client service optional (#22209, #22759).
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/README.md
  stable/mongodb-replicaset/templates/mongodb-service-client.yaml
  stable/mongodb-replicaset/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22952 [stable/prometheus-mongodb-exporter] Add serviceMonitor targetLabels and service labels
  stable/prometheus-mongodb-exporter/Chart.yaml
  stable/prometheus-mongodb-exporter/README.md
  stable/prometheus-mongodb-exporter/templates/service.yaml
  stable/prometheus-mongodb-exporter/templates/servicemonitor.yaml
  stable/prometheus-mongodb-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23036 [stable/airflow] Adding basic auth values for flower
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/UPGRADE.md
  stable/airflow/templates/_helpers.tpl
  stable/airflow/templates/deployments-flower.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#23024 [stable/prometheus-operator] Sync dashboards and rules for #22081
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/apiserver.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-cluster.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-namespace.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-node.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-pod.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-workload.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-workloads-namespace.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/alertmanager.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/k8s.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kube-apiserver-availability.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kube-apiserver-slos.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kube-apiserver.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-apps.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-resources.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/node-exporter.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/node.rules.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XL

#23049 [stable/prometheus] add support for running without cluster-admin privileges
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/alertmanager-clusterrole.yaml
  stable/prometheus/templates/alertmanager-clusterrolebinding.yaml
  stable/prometheus/templates/alertmanager-role.yaml
  stable/prometheus/templates/alertmanager-rolebinding.yaml
  stable/prometheus/templates/server-clusterrole.yaml
  stable/prometheus/templates/server-clusterrolebinding.yaml
  stable/prometheus/templates/server-rolebinding.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#23111 [stable/grafana]update the grafana to 7.0.5
  stable/grafana/Chart.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22949 [stable/prometheus-operator] remove namespace field from non-namespaced resources
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/alertmanager/psp.yaml
  stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/clusterrolebinding.yaml
  stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/psp.yaml
  stable/prometheus-operator/templates/prometheus-operator/psp.yaml
  stable/prometheus-operator/templates/prometheus/psp.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23112 [stable/prometheus-operator] Treat alertmanager additionalPeers as YAML
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/alertmanager/alertmanager.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23000 [stable/cockroachdb] deprecating this cockroachdb chart repository
  stable/cockroachdb/Chart.yaml
  stable/cockroachdb/README.md
  stable/cockroachdb/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#23099 [incubator/azuremonitor-containers] updates linux agent image to ciprod06302020 and add tolerations for windows ds
  incubator/azuremonitor-containers/Chart.yaml
  incubator/azuremonitor-containers/templates/omsagent-daemonset-windows.yaml
  incubator/azuremonitor-containers/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23125 [incubator/sparkoperator] Add scheduling.volcano.sh to apiGroup in spark-operator-rbac.yaml
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/templates/spark-operator-rbac.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#23116 [stable/prometheus] Improve Prometheus Server Probes. Fix MD Syntax Issues in README.
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/server-deployment.yaml
  stable/prometheus/templates/server-statefulset.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22998 [stable/nginx-ingress] add controller.podAnnotationConfigChecksum
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-deployment.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23089 [incubator/aws-alb-ingress-controller] Bump chart version bump to 1.0.2
  incubator/aws-alb-ingress-controller/Chart.yaml
  incubator/aws-alb-ingress-controller/README.md
  incubator/aws-alb-ingress-controller/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22653 [incubator/rundeck] add support for init containers and custom volumes
  incubator/rundeck/Chart.yaml
  incubator/rundeck/README.md
  incubator/rundeck/templates/deployment.yaml
  incubator/rundeck/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#23115 [incubator/druid] modify the default value(the previously pr is closed, I can't reopen it. #23072)
  incubator/druid/Chart.yaml
  incubator/druid/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22956 [stable/dex] Add imagePullSecrets
  stable/dex/Chart.yaml
  stable/dex/README.md
  stable/dex/templates/deployment.yaml
  stable/dex/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#22900 [stable/prometheus-operator] possibility to add annotations to default dashboards
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/hack/sync_grafana_dashboards.py
  stable/prometheus-operator/templates/grafana/dashboards-1.14/apiserver.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/cluster-total.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/controller-manager.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/etcd.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-cluster.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-namespace.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-node.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-pod.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-workload.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-workloads-namespace.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/kubelet.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/namespace-by-pod.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/namespace-by-workload.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/node-cluster-rsrc-use.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/node-rsrc-use.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/nodes.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/persistentvolumesusage.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/pod-total.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/prometheus-remote-write.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/prometheus.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/proxy.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/scheduler.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/statefulset.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/workload-total.yaml
  stable/prometheus-operator/templates/grafana/dashboards/etcd.yaml
  stable/prometheus-operator/templates/grafana/dashboards/k8s-cluster-rsrc-use.yaml
  stable/prometheus-operator/templates/grafana/dashboards/k8s-node-rsrc-use.yaml
  stable/prometheus-operator/templates/grafana/dashboards/k8s-resources-cluster.yaml
  stable/prometheus-operator/templates/grafana/dashboards/k8s-resources-namespace.yaml
  stable/prometheus-operator/templates/grafana/dashboards/k8s-resources-pod.yaml
  stable/prometheus-operator/templates/grafana/dashboards/k8s-resources-workload.yaml
  stable/prometheus-operator/templates/grafana/dashboards/k8s-resources-workloads-namespace.yaml
  stable/prometheus-operator/templates/grafana/dashboards/nodes.yaml
  stable/prometheus-operator/templates/grafana/dashboards/persistentvolumesusage.yaml
  stable/prometheus-operator/templates/grafana/dashboards/pods.yaml
  stable/prometheus-operator/templates/grafana/dashboards/statefulset.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#23136 [stable/prometheus-operator] Added option to disable availability rules
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/hack/sync_prometheus_rules.py
  stable/prometheus-operator/templates/prometheus/rules-1.14/kube-apiserver-availability.rules.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23086 [stable/datadog] add systemProbe.collectDNSStats
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/templates/system-probe-configmap.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23122 [stable/atlantis] Add envFrom secrets option
  stable/atlantis/Chart.yaml
  stable/atlantis/README.md
  stable/atlantis/templates/statefulset.yaml
  stable/atlantis/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22392 [stable/fluent-bit] Added `input.tail.exclude_path` parameter
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/config.yaml
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23146 [stable/datadog] Fix daemonset generation if `datadog.securityContext==nil`
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/ci/securitycontext-nil.yaml
  stable/datadog/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#23079 [stable/datadog] Small chart tweaks for cluster agent
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22023 [stable/ignite] Ignite features
  stable/ignite/Chart.yaml
  stable/ignite/README.md
  stable/ignite/templates/stateful-set.yaml
  stable/ignite/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22394 [stable/minio] Prevent hook error on upgrade
  stable/minio/Chart.yaml
  stable/minio/templates/post-install-create-bucket-job.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23153 [stable/hlf-peer] (URGENT) Configure chaincode builder and chaincode runtime image
  stable/hlf-peer/Chart.yaml
  stable/hlf-peer/README.md
  stable/hlf-peer/templates/configmap--peer.yaml
  stable/hlf-peer/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#23137 Mount always ref/secrets.
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/jenkins-master-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23175 [stable/jenkins] Fix overwritePluginsFromImage and syntax error
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/ci/other-values.yaml
  stable/jenkins/templates/config.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#23176 [stable/jenkins] Fix master.slaveJenkinsUrl
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, size/XS

#23046 [stable/mongodb-replicaset] liveness/startupProbe tuning
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/README.md
  stable/mongodb-replicaset/templates/mongodb-statefulset.yaml
  stable/mongodb-replicaset/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#23130 [stable/grafana] Update the app version to 7.0.5
  stable/grafana/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23162 [stable/atlantis] Use newer ingress API to be compatible with Kubernetes 1.16
  stable/atlantis/Chart.yaml
  stable/atlantis/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23154 [stable/datadog] Change to use specified port instead of default
  stable/datadog/Chart.yaml
  stable/datadog/templates/agent-apiservice.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#23161 [stable/oauth2-proxy] Use newer ingress API to be compatible with Kubernetes 1.16
  stable/oauth2-proxy/Chart.yaml
  stable/oauth2-proxy/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#23165 [incubator/buzzfeed-sso] Allow Independent auth Ingress
  incubator/buzzfeed-sso/Chart.yaml
  incubator/buzzfeed-sso/README.md
  incubator/buzzfeed-sso/templates/ingress.yaml
  incubator/buzzfeed-sso/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23191 [stable/jenkins] update agent image
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#23166 [stable/datadog] fix daemonset templates for go 1.14
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#23151 [stable/prometheus-node-exporter] Version bump to 1.0.1
  stable/prometheus-node-exporter/Chart.yaml
  stable/prometheus-node-exporter/README.md
  stable/prometheus-node-exporter/ci/port-values.yaml
  stable/prometheus-node-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23147 [stable/prometheus-operator] Version bump, deprecation of additionalScrapeConfigsExternal
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/ci/02-test-without-crds-values.yaml
  stable/prometheus-operator/templates/prometheus/prometheus.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#23190 [stable/opa] Add extra{containers,ports,volumes} to OPA deployment
  stable/opa/Chart.yaml
  stable/opa/README.md
  stable/opa/templates/deployment.yaml
  stable/opa/templates/service.yaml
  stable/opa/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#23150 [stable/prometheus-operator] Version bump alertmanager and prometheus
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23199 [stable/datadog] Always add os in nodeSelector based on `targetSystem`
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/templates/_helpers.tpl
  stable/datadog/templates/agent-clusterchecks-deployment.yaml
  stable/datadog/templates/cluster-agent-deployment.yaml
  stable/datadog/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#23192 [stable/kibana] possility customize url for dashboard import script
  stable/kibana/Chart.yaml
  stable/kibana/README.md
  stable/kibana/templates/configmap-dashboardimport.yaml
  stable/kibana/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#23169 [stable/fluentd] Add podLabels
  stable/fluentd/Chart.yaml
  stable/fluentd/README.md
  stable/fluentd/templates/deployment.yaml
  stable/fluentd/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23211 [stable/instana-agent] Chart version 1.0.29
  stable/instana-agent/Chart.yaml
  stable/instana-agent/README.md
  stable/instana-agent/templates/_helpers.tpl
  stable/instana-agent/templates/clusterrole.yaml
  stable/instana-agent/templates/daemonset.yaml
  stable/instana-agent/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#22828 [stable/spinnaker] Add option to specify storageclass for halyard persistence data volume
  stable/spinnaker/Chart.yaml
  stable/spinnaker/templates/statefulsets/halyard.yaml
  stable/spinnaker/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23208 [stable/percona-xtradb-cluster] Fixes #23207
  stable/percona-xtradb-cluster/Chart.yaml
  stable/percona-xtradb-cluster/README.md
  stable/percona-xtradb-cluster/templates/statefulset.yaml
  stable/percona-xtradb-cluster/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23129 [incubator/cockroachdb] deprecate missing chart
  incubator/cockroachdb/.helmignore
  incubator/cockroachdb/Chart.yaml
  incubator/cockroachdb/README.md
  incubator/cockroachdb/templates/NOTES.txt
  incubator/cockroachdb/templates/_helpers.tpl
  incubator/cockroachdb/templates/deployment.yaml
  incubator/cockroachdb/templates/ingress.yaml
  incubator/cockroachdb/templates/service.yaml
  incubator/cockroachdb/templates/serviceaccount.yaml
  incubator/cockroachdb/templates/tests/test-connection.yaml
  incubator/cockroachdb/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#23212 [incubator/azuremonitor-containers] updates for hotfix release ciprod07152020
  incubator/azuremonitor-containers/Chart.yaml
  incubator/azuremonitor-containers/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23195 [stable/grafana] Allow specifying checksum for docker images
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/_pod.tpl
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#23206 [stable/hlf-peer] Add docker config.json secret for private registry
  stable/hlf-peer/Chart.yaml
  stable/hlf-peer/README.md
  stable/hlf-peer/templates/deployment.yaml
  stable/hlf-peer/templates/secret.yaml
  stable/hlf-peer/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#23219 [stable/efs-provisioner] Enable ability to set annotations on service account
  stable/efs-provisioner/Chart.yaml
  stable/efs-provisioner/README.md
  stable/efs-provisioner/templates/serviceaccount.yaml
  stable/efs-provisioner/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#23221 [stable/metabase] Allow MB_SITE_URL to be set from values.yaml
  stable/metabase/Chart.yaml
  stable/metabase/README.md
  stable/metabase/templates/deployment.yaml
  stable/metabase/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23216 [stable/elasticsearch-exporter]: customize log flags
  stable/elasticsearch-exporter/Chart.yaml
  stable/elasticsearch-exporter/README.md
  stable/elasticsearch-exporter/templates/deployment.yaml
  stable/elasticsearch-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#23194 [stable/prometheus-operator] Add docker checksum option
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/alertmanager/alertmanager.yaml
  stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
  stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml
  stable/prometheus-operator/templates/prometheus-operator/cleanup-crds.yaml
  stable/prometheus-operator/templates/prometheus-operator/deployment.yaml
  stable/prometheus-operator/templates/prometheus/prometheus.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#23233 [stable/datadog] Add podSecurity.securityContext
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/agent-psp.yaml
  stable/datadog/templates/agent-scc.yaml
  stable/datadog/templates/daemonset.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#23222 [incubator/docker-registry] deprecate missing chart
  incubator/docker-registry/.helmignore
  incubator/docker-registry/Chart.yaml
  incubator/docker-registry/README.md
  incubator/docker-registry/templates/NOTES.txt
  incubator/docker-registry/templates/_helpers.tpl
  incubator/docker-registry/templates/deployment.yaml
  incubator/docker-registry/templates/ingress.yaml
  incubator/docker-registry/templates/service.yaml
  incubator/docker-registry/templates/serviceaccount.yaml
  incubator/docker-registry/templates/tests/test-connection.yaml
  incubator/docker-registry/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#23223 [incubator/drone] deprecate missing chart
  incubator/drone/.helmignore
  incubator/drone/Chart.yaml
  incubator/drone/README.md
  incubator/drone/templates/NOTES.txt
  incubator/drone/templates/_helpers.tpl
  incubator/drone/templates/deployment.yaml
  incubator/drone/templates/ingress.yaml
  incubator/drone/templates/service.yaml
  incubator/drone/templates/serviceaccount.yaml
  incubator/drone/templates/tests/test-connection.yaml
  incubator/drone/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#23225 [incubator/grafana] deprecate missing chart
  incubator/grafana/.helmignore
  incubator/grafana/Chart.yaml
  incubator/grafana/README.md
  incubator/grafana/templates/NOTES.txt
  incubator/grafana/templates/_helpers.tpl
  incubator/grafana/templates/deployment.yaml
  incubator/grafana/templates/ingress.yaml
  incubator/grafana/templates/service.yaml
  incubator/grafana/templates/serviceaccount.yaml
  incubator/grafana/templates/tests/test-connection.yaml
  incubator/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#23230 [incubator/mongodb-replicaset] deprecate missing chart
  incubator/mongodb-replicaset/.helmignore
  incubator/mongodb-replicaset/Chart.yaml
  incubator/mongodb-replicaset/README.md
  incubator/mongodb-replicaset/templates/NOTES.txt
  incubator/mongodb-replicaset/templates/_helpers.tpl
  incubator/mongodb-replicaset/templates/deployment.yaml
  incubator/mongodb-replicaset/templates/ingress.yaml
  incubator/mongodb-replicaset/templates/service.yaml
  incubator/mongodb-replicaset/templates/serviceaccount.yaml
  incubator/mongodb-replicaset/templates/tests/test-connection.yaml
  incubator/mongodb-replicaset/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#23231 [incubator/neo4j] deprecate missing chart
  incubator/neo4j/.helmignore
  incubator/neo4j/Chart.yaml
  incubator/neo4j/README.md
  incubator/neo4j/templates/NOTES.txt
  incubator/neo4j/templates/_helpers.tpl
  incubator/neo4j/templates/deployment.yaml
  incubator/neo4j/templates/ingress.yaml
  incubator/neo4j/templates/service.yaml
  incubator/neo4j/templates/serviceaccount.yaml
  incubator/neo4j/templates/tests/test-connection.yaml
  incubator/neo4j/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#23236 [incubator/spark] deprecate missing chart
  incubator/spark/.helmignore
  incubator/spark/Chart.yaml
  incubator/spark/README.md
  incubator/spark/templates/NOTES.txt
  incubator/spark/templates/_helpers.tpl
  incubator/spark/templates/deployment.yaml
  incubator/spark/templates/ingress.yaml
  incubator/spark/templates/service.yaml
  incubator/spark/templates/serviceaccount.yaml
  incubator/spark/templates/tests/test-connection.yaml
  incubator/spark/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#23240 [stable/grafana] Don't specify default digest for docker images
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23224 [incubator/gocd] deprecate missing chart
  incubator/gocd/.helmignore
  incubator/gocd/Chart.yaml
  incubator/gocd/README.md
  incubator/gocd/templates/NOTES.txt
  incubator/gocd/templates/_helpers.tpl
  incubator/gocd/templates/deployment.yaml
  incubator/gocd/templates/ingress.yaml
  incubator/gocd/templates/service.yaml
  incubator/gocd/templates/serviceaccount.yaml
  incubator/gocd/templates/tests/test-connection.yaml
  incubator/gocd/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#23245 [stable/prometheus-adapter] Upgrading to v0.7.0
  stable/prometheus-adapter/Chart.yaml
  stable/prometheus-adapter/README.md
  stable/prometheus-adapter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23210 [stable/kube-state-metrics] Fix STS role for Autosharding
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/templates/stsdiscovery-role.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23229 [incubator/mongodb] deprecate missing chart
  incubator/mongodb/.helmignore
  incubator/mongodb/Chart.yaml
  incubator/mongodb/README.md
  incubator/mongodb/templates/NOTES.txt
  incubator/mongodb/templates/_helpers.tpl
  incubator/mongodb/templates/deployment.yaml
  incubator/mongodb/templates/ingress.yaml
  incubator/mongodb/templates/service.yaml
  incubator/mongodb/templates/serviceaccount.yaml
  incubator/mongodb/templates/tests/test-connection.yaml
  incubator/mongodb/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#23213 [stable/nginx-ingress] Update Controller image registry to .gcr.io
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-daemonset.yaml
  stable/nginx-ingress/templates/controller-deployment.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23220 [incubator/consul] deprecate missing chart
  incubator/consul/.helmignore
  incubator/consul/Chart.yaml
  incubator/consul/README.md
  incubator/consul/templates/NOTES.txt
  incubator/consul/templates/_helpers.tpl
  incubator/consul/templates/deployment.yaml
  incubator/consul/templates/ingress.yaml
  incubator/consul/templates/service.yaml
  incubator/consul/templates/serviceaccount.yaml
  incubator/consul/templates/tests/test-connection.yaml
  incubator/consul/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#23235 [incubator/prometheus] deprecate missing chart
  incubator/prometheus/.helmignore
  incubator/prometheus/Chart.yaml
  incubator/prometheus/README.md
  incubator/prometheus/templates/NOTES.txt
  incubator/prometheus/templates/_helpers.tpl
  incubator/prometheus/templates/deployment.yaml
  incubator/prometheus/templates/ingress.yaml
  incubator/prometheus/templates/service.yaml
  incubator/prometheus/templates/serviceaccount.yaml
  incubator/prometheus/templates/tests/test-connection.yaml
  incubator/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#23237 [stable/falco] deprecate missing chart
  stable/falco/.helmignore
  stable/falco/Chart.yaml
  stable/falco/README.md
  stable/falco/templates/NOTES.txt
  stable/falco/templates/_helpers.tpl
  stable/falco/templates/deployment.yaml
  stable/falco/templates/ingress.yaml
  stable/falco/templates/service.yaml
  stable/falco/templates/serviceaccount.yaml
  stable/falco/templates/tests/test-connection.yaml
  stable/falco/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#23226 [incubator/kube-ops-view] deprecate missing chart
  incubator/kube-ops-view/.helmignore
  incubator/kube-ops-view/Chart.yaml
  incubator/kube-ops-view/README.md
  incubator/kube-ops-view/templates/NOTES.txt
  incubator/kube-ops-view/templates/_helpers.tpl
  incubator/kube-ops-view/templates/deployment.yaml
  incubator/kube-ops-view/templates/ingress.yaml
  incubator/kube-ops-view/templates/service.yaml
  incubator/kube-ops-view/templates/serviceaccount.yaml
  incubator/kube-ops-view/templates/tests/test-connection.yaml
  incubator/kube-ops-view/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#23217 [stable/atlantis] Update atlantis to v0.14.0
  stable/atlantis/Chart.yaml
  stable/atlantis/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22842 [stable/fluentd] Expose replicaCount in values file
  stable/fluentd/Chart.yaml
  stable/fluentd/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23227 [incubator/kube-spot-termination-notice-handler] deprecate missing chart
  incubator/kube-spot-termination-notice-handler/.helmignore
  incubator/kube-spot-termination-notice-handler/Chart.yaml
  incubator/kube-spot-termination-notice-handler/README.md
  incubator/kube-spot-termination-notice-handler/templates/NOTES.txt
  incubator/kube-spot-termination-notice-handler/templates/_helpers.tpl
  incubator/kube-spot-termination-notice-handler/templates/deployment.yaml
  incubator/kube-spot-termination-notice-handler/templates/ingress.yaml
  incubator/kube-spot-termination-notice-handler/templates/service.yaml
  incubator/kube-spot-termination-notice-handler/templates/serviceaccount.yaml
  incubator/kube-spot-termination-notice-handler/templates/tests/test-connection.yaml
  incubator/kube-spot-termination-notice-handler/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#23074 [stable/fluent-bit] Add support for init containers
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/daemonset.yaml
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23097 [stable/janusgraph] bump k8s api to stable
  stable/janusgraph/Chart.yaml
  stable/janusgraph/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22834 [stable/prometheus-consul-exporter] Fix PSP apiVersion
  stable/prometheus-consul-exporter/Chart.yaml
  stable/prometheus-consul-exporter/templates/podsecuritypolicy.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#18569 [stable/quassel] Update image and deployment apiVersion
  stable/quassel/Chart.yaml
  stable/quassel/templates/deployment.yaml
  stable/quassel/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22717 [stable/kube2iam] allow to customize liveness probe configuration
  stable/kube2iam/Chart.yaml
  stable/kube2iam/README.md
  stable/kube2iam/templates/daemonset.yaml
  stable/kube2iam/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22818 [Stable/rethinkdb] Fix rethinkdb cluster ip field is immutable
  stable/rethinkdb/Chart.yaml
  stable/rethinkdb/templates/rethinkdb-proxy-service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23234 [incubator/oauth-proxy] deprecate missing chart
  incubator/oauth-proxy/.helmignore
  incubator/oauth-proxy/Chart.yaml
  incubator/oauth-proxy/README.md
  incubator/oauth-proxy/templates/NOTES.txt
  incubator/oauth-proxy/templates/_helpers.tpl
  incubator/oauth-proxy/templates/deployment.yaml
  incubator/oauth-proxy/templates/ingress.yaml
  incubator/oauth-proxy/templates/service.yaml
  incubator/oauth-proxy/templates/serviceaccount.yaml
  incubator/oauth-proxy/templates/tests/test-connection.yaml
  incubator/oauth-proxy/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#23251 Support 1.2.0-3.0.0 release
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/README.md
  incubator/sparkoperator/ci/test-values.yaml
  incubator/sparkoperator/templates/crds.yaml
  incubator/sparkoperator/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XXL

#23248 [incubator/schema-registry] Upgrade kafka subchart to support apps/v1 API for StatefulSet
  incubator/schema-registry/Chart.yaml
  incubator/schema-registry/requirements.lock
  incubator/schema-registry/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22782 [stable/jenkins] Reorder README parameters into sections for readability
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
Labels: Contribution Allowed, approved, lgtm, size/L

#22850 [stable/kube-state-metrics] added resource config to values.yaml
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23063 [stable/datadog] Add support for scaling on DatadogMetrics
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/templates/agent-rbac.yaml
  stable/datadog/templates/cluster-agent-deployment.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#23064 [stable/datadog] Support admission controller
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/templates/agent-rbac.yaml
  stable/datadog/templates/agent-services.yaml
  stable/datadog/templates/cluster-agent-deployment.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#23257 [stable/nginx-ingress] Fix regex in ingress config.
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#23266 [incubator/sparkoperator] Removed status section from generated CRDs
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/templates/crds.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#23042 [stable/minio] Support imagePullSecrets for StatefulSet.
  stable/minio/Chart.yaml
  stable/minio/templates/_helpers.tpl
  stable/minio/templates/deployment.yaml
  stable/minio/templates/post-install-create-bucket-job.yaml
  stable/minio/templates/post-install-prometheus-metrics-job.yaml
  stable/minio/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#23262 [stable/prometheus-mongodb-exporter] Possibility to also add a custom key in the existing secret
  stable/prometheus-mongodb-exporter/Chart.yaml
  stable/prometheus-mongodb-exporter/README.md
  stable/prometheus-mongodb-exporter/templates/deployment.yaml
  stable/prometheus-mongodb-exporter/templates/secret.yaml
  stable/prometheus-mongodb-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23253 [stable/prometheus] bump alertmanager v0.21.0 and prometheus v2.19.2
  stable/prometheus/Chart.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23258 [stable/envoy] Fix typo for envoy
  stable/envoy/Chart.yaml
  stable/envoy/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23186 [stable/prometheus] Organized Templates Directory. Add ".gitignore".
  stable/prometheus/.gitignore
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/configmaps/alertmanager.yaml
  stable/prometheus/templates/configmaps/server.yaml
  stable/prometheus/templates/daemonsets/node-exporter.yaml
  stable/prometheus/templates/deployments/alertmanager.yaml
  stable/prometheus/templates/deployments/pushgateway.yaml
  stable/prometheus/templates/deployments/server.yaml
  stable/prometheus/templates/ingresses/alertmanager.yaml
  stable/prometheus/templates/ingresses/pushgateway.yaml
  stable/prometheus/templates/ingresses/server.yaml
  stable/prometheus/templates/networkpolicies/alertmanager.yaml
  stable/prometheus/templates/networkpolicies/pushgateway.yaml
  stable/prometheus/templates/networkpolicies/server.yaml
  stable/prometheus/templates/persistentvolumeclaims/alertmanager.yaml
  stable/prometheus/templates/persistentvolumeclaims/pushgateway.yaml
  stable/prometheus/templates/persistentvolumeclaims/server.yaml
  stable/prometheus/templates/poddisruptionbudgets/alertmanager.yaml
  stable/prometheus/templates/poddisruptionbudgets/pushgateway.yaml
  stable/prometheus/templates/poddisruptionbudgets/server.yaml
  stable/prometheus/templates/podsecuritypolicies/alertmanager.yaml
  stable/prometheus/templates/podsecuritypolicies/node-exporter.yaml
  stable/prometheus/templates/podsecuritypolicies/pushgateway.yaml
  stable/prometheus/templates/podsecuritypolicies/server.yaml
  stable/prometheus/templates/rbac/alertmanager-clusterrole.yaml
  stable/prometheus/templates/rbac/alertmanager-clusterrolebinding.yaml
  stable/prometheus/templates/rbac/alertmanager-role.yaml
  stable/prometheus/templates/rbac/alertmanager-rolebinding.yaml
  stable/prometheus/templates/rbac/alertmanager-serviceaccount.yaml
  stable/prometheus/templates/rbac/node-exporter-role.yaml
  stable/prometheus/templates/rbac/node-exporter-rolebinding.yaml
  stable/prometheus/templates/rbac/node-exporter-serviceaccount.yaml
  stable/prometheus/templates/rbac/pushgateway-clusterrole.yaml
  stable/prometheus/templates/rbac/pushgateway-clusterrolebinding.yaml
  stable/prometheus/templates/rbac/pushgateway-serviceaccount.yaml
  stable/prometheus/templates/rbac/server-clusterrole.yaml
  stable/prometheus/templates/rbac/server-clusterrolebinding.yaml
  stable/prometheus/templates/rbac/server-rolebinding.yaml
  stable/prometheus/templates/rbac/server-serviceaccount.yaml
  stable/prometheus/templates/services/alertmanager-headless.yaml
  stable/prometheus/templates/services/alertmanager.yaml
  stable/prometheus/templates/services/node-exporter.yaml
  stable/prometheus/templates/services/pushgateway.yaml
  stable/prometheus/templates/services/server-headless.yaml
  stable/prometheus/templates/services/server.yaml
  stable/prometheus/templates/statefulsets/alertmanager.yaml
  stable/prometheus/templates/statefulsets/server.yaml
  stable/prometheus/templates/verticalpodautoscalers/server.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23260 [stable/prometheus-operator] Fix ordering
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23276 [stable/prometheus] Add a New Maintainer and Owner
  stable/prometheus/Chart.yaml
  stable/prometheus/OWNERS
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23286 [stable/prometheus-operator] fix additionalScrapeConfigsSecret
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/prometheus/prometheus.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23047 [stable/prometheus-operator] Add volume mounts and volume
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/alertmanager/alertmanager.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23289 [stable/prometheus-redis-exporter] Add ServiceMonitor metricRelabelings
  stable/prometheus-redis-exporter/Chart.yaml
  stable/prometheus-redis-exporter/README.md
  stable/prometheus-redis-exporter/templates/servicemonitor.yaml
  stable/prometheus-redis-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23291 [stable/elasticsearch-exporter] Add ServiceMonitor metricRelabeling
  stable/elasticsearch-exporter/Chart.yaml
  stable/elasticsearch-exporter/README.md
  stable/elasticsearch-exporter/templates/servicemonitor.yaml
  stable/elasticsearch-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test

#23264 [stable/grafana]Add "Sidecar for notifiers" feature
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/_pod.tpl
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#23299 [stable/prometheus] Disable "enableServiceLinks" on Kubernetes prior 1.13
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/statefulsets/server.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test

#23275 [stable/nginx] ingress add hpa for default backend
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/default-backend-deployment.yaml
  stable/nginx-ingress/templates/default-backend-hpa.yaml
  stable/nginx-ingress/templates/default-backend-poddisruptionbudget.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#23022 [prometheus-operator] Fixing scope issue (#23014)
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/grafana/configmap-dashboards.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS
