Repository helm/charts, pull requests merged in 2020-11, with the labels that each got.

#23968 [stable/kube-state-metrics] Update apiVersion for clusterrole
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/templates/clusterrole.yaml
  stable/kube-state-metrics/templates/clusterrolebinding.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#23914 [stable/coredns] Properly indent pod annotations
  stable/coredns/Chart.yaml
  stable/coredns/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23832 [stable/node-problem-detector] Deprecate node-problem-detector Chart
  stable/node-problem-detector/Chart.yaml
  stable/node-problem-detector/README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#24014 [stable/pomerium] Upate logo
  stable/pomerium/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#24016 [stable/sysdig] Deprecating sysdig chart
  stable/sysdig/Chart.yaml
  stable/sysdig/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#24021 [stable/airflow] depreciate chart
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/UPGRADE.md
  stable/airflow/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#24011 [stable/graylog] deprecate graylog chart
  stable/graylog/Chart.yaml
  stable/graylog/README.md
  stable/graylog/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, size/S

#23889 [stable/lamp] Adding quote to git sync wait
  stable/lamp/Chart.yaml
  stable/lamp/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#24055 [incubator/mysqlha] add repo archive notice
  incubator/mysqlha/Chart.yaml
  incubator/mysqlha/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24037 [incubator/cassandra] add repo archive notice
  incubator/cassandra/Chart.yaml
  incubator/cassandra/README.md
Labels: Contribution Allowed, approved, lgtm

#24193 [stable/spark-history-server] add repo archive notice
  stable/spark-history-server/Chart.yaml
  stable/spark-history-server/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24067 [incubator/sparkoperator] add repo archive notice
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24041 [incubator/druid] add repo archive notice
  incubator/druid/Chart.yaml
  incubator/druid/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24032 [incubator/aws-alb-ingress-controller] add repo archive notice
  incubator/aws-alb-ingress-controller/Chart.yaml
  incubator/aws-alb-ingress-controller/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24033 [incubator/azuremonitor-containers] add repo archive notice
  incubator/azuremonitor-containers/Chart.yaml
  incubator/azuremonitor-containers/README.md
Labels: Contribution Allowed, approved, lgtm

#24034 [incubator/buzzfeed-sso] add repo archive notice
  incubator/buzzfeed-sso/Chart.yaml
  incubator/buzzfeed-sso/README.md
Labels: Contribution Allowed, approved, lgtm

#24040 [incubator/common] add repo archive notice
  incubator/common/Chart.yaml
  incubator/common/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24042 [incubator/etcd] add repo archive notice
  incubator/etcd/Chart.yaml
  incubator/etcd/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24047 [incubator/hoverfly] add repo archive notice
  incubator/hoverfly/Chart.yaml
  incubator/hoverfly/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24048 [incubator/kafka] add repo archive notice
  incubator/kafka/Chart.yaml
  incubator/kafka/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24050 [incubator/kube-downscaler] add repo archive notice
  incubator/kube-downscaler/Chart.yaml
  incubator/kube-downscaler/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24051 [incubator/kube-janitor] add repo archive notice
  incubator/kube-janitor/Chart.yaml
  incubator/kube-janitor/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24052 [incubator/kube-registry-proxy] add repo archive notice
  incubator/kube-registry-proxy/Chart.yaml
  incubator/kube-registry-proxy/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24053 [incubator/kubeless] add repo archive notice
  incubator/kubeless/Chart.yaml
  incubator/kubeless/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24054 [incubator/kubernetes-vault] add repo archive notice
  incubator/kubernetes-vault/Chart.yaml
  incubator/kubernetes-vault/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24056 [incubator/orientdb] add repo archive notice
  incubator/orientdb/Chart.yaml
  incubator/orientdb/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24057 [incubator/patroni] add repo archive notice
  incubator/patroni/Chart.yaml
  incubator/patroni/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24061 [incubator/redis-cache] add repo archive notice
  incubator/redis-cache/Chart.yaml
  incubator/redis-cache/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24063 [incubator/rundeck] add repo archive notice
  incubator/rundeck/Chart.yaml
  incubator/rundeck/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24064 [incubator/schema-registry] add repo archive notice
  incubator/schema-registry/Chart.yaml
  incubator/schema-registry/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24065 [incubator/sentry-kubernetes] add repo archive notice
  incubator/sentry-kubernetes/Chart.yaml
  incubator/sentry-kubernetes/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24066 [incubator/solr] add repo archive notice
  incubator/solr/Chart.yaml
  incubator/solr/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24069 [incubator/vault] add repo archive notice
  incubator/vault/Chart.yaml
  incubator/vault/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24073 [incubator/zookeeper] add repo archive notice
  incubator/zookeeper/Chart.yaml
  incubator/zookeeper/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24074 [stable/couchbase-operator] add repo archive notice
  stable/couchbase-operator/Chart.yaml
  stable/couchbase-operator/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24075 [stable/nginx-ldapauth-proxy] add repo archive notice
  stable/nginx-ldapauth-proxy/Chart.yaml
  stable/nginx-ldapauth-proxy/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24076 [stable/aerospike] add repo archive notice
  stable/aerospike/Chart.yaml
  stable/aerospike/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24077 [stable/apm-server] add repo archive notice
  stable/apm-server/Chart.yaml
  stable/apm-server/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24079 [stable/aws-iam-authenticator] add repo archive notice
  stable/aws-iam-authenticator/Chart.yaml
  stable/aws-iam-authenticator/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24080 [stable/bitcoind] add repo archive notice
  stable/bitcoind/Chart.yaml
  stable/bitcoind/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24082 [stable/burrow] add repo archive notice
  stable/burrow/Chart.yaml
  stable/burrow/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24083 [stable/centrifugo] add repo archive notice
  stable/centrifugo/Chart.yaml
  stable/centrifugo/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24084 [stable/cerebro] add repo archive notice
  stable/cerebro/Chart.yaml
  stable/cerebro/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24085 [stable/chaoskube] add repo archive notice
  stable/chaoskube/Chart.yaml
  stable/chaoskube/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24086 [stable/chartmuseum] add repo archive notice
  stable/chartmuseum/Chart.yaml
  stable/chartmuseum/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24089 [stable/collabora-code] add repo archive notice
  stable/collabora-code/Chart.yaml
  stable/collabora-code/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24091 [stable/coredns] add repo archive notice
  stable/coredns/Chart.yaml
  stable/coredns/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24092 [stable/cosbench] add repo archive notice
  stable/cosbench/Chart.yaml
  stable/cosbench/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24093 [stable/coscale] add repo archive notice
  stable/coscale/Chart.yaml
  stable/coscale/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24094 [stable/dex] add repo archive notice
  stable/dex/Chart.yaml
  stable/dex/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24095 [stable/distributed-jmeter] add repo archive notice
  stable/distributed-jmeter/Chart.yaml
  stable/distributed-jmeter/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24096 [stable/distributed-tensorflow] add repo archive notice
  stable/distributed-tensorflow/Chart.yaml
  stable/distributed-tensorflow/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24097 [stable/docker-registry] add repo archive notice
  stable/docker-registry/Chart.yaml
  stable/docker-registry/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24098 [stable/efs-provisioner] add repo archive notice
  stable/efs-provisioner/Chart.yaml
  stable/efs-provisioner/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24099 [stable/elastic-stack] add repo archive notice
  stable/elastic-stack/Chart.yaml
  stable/elastic-stack/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24100 [stable/elasticsearch-curator] add repo archive notice
  stable/elasticsearch-curator/Chart.yaml
  stable/elasticsearch-curator/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24102 [stable/envoy] add repo archive notice
  stable/envoy/Chart.yaml
  stable/envoy/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24103 [stable/etcd-operator] add repo archive notice
  stable/etcd-operator/Chart.yaml
  stable/etcd-operator/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24105 [stable/eventrouter] add repo archive notice
  stable/eventrouter/Chart.yaml
  stable/eventrouter/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24108 [stable/filebeat] add repo archive notice
  stable/filebeat/Chart.yaml
  stable/filebeat/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24109 [stable/fluent-bit] add repo archive notice
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24110 [stable/fluentd] add repo archive notice
  stable/fluentd/Chart.yaml
  stable/fluentd/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24111 [stable/gangway] add repo archive notice
  stable/gangway/Chart.yaml
  stable/gangway/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24112 [stable/gce-ingress] add repo archive notice
  stable/gce-ingress/Chart.yaml
  stable/gce-ingress/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24113 [stable/gcp-night-king] add repo archive notice
  stable/gcp-night-king/Chart.yaml
  stable/gcp-night-king/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24115 [stable/hackmd] add repo archive notice
  stable/hackmd/Chart.yaml
  stable/hackmd/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24116 [stable/hadoop] add repo archive notice
  stable/hadoop/Chart.yaml
  stable/hadoop/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24118 [stable/heartbeat] add repo archive notice
  stable/heartbeat/Chart.yaml
  stable/heartbeat/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24120 [stable/hlf-ca] add repo archive notice
  stable/hlf-ca/Chart.yaml
  stable/hlf-ca/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24121 [stable/hlf-couchdb] add repo archive notice
  stable/hlf-couchdb/Chart.yaml
  stable/hlf-couchdb/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24122 [stable/hlf-ord] add repo archive notice
  stable/hlf-ord/Chart.yaml
  stable/hlf-ord/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24123 [stable/hlf-peer] add repo archive notice
  stable/hlf-peer/Chart.yaml
  stable/hlf-peer/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24124 [stable/hoard] add repo archive notice
  stable/hoard/Chart.yaml
  stable/hoard/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24126 [stable/hubot] add repo archive notice
  stable/hubot/Chart.yaml
  stable/hubot/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24127 [stable/ignite] add repo archive notice
  stable/ignite/Chart.yaml
  stable/ignite/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24128 [stable/inbucket] add repo archive notice
  stable/inbucket/Chart.yaml
  stable/inbucket/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24129 [stable/ingressmonitorcontroller] add repo archive notice
  stable/ingressmonitorcontroller/Chart.yaml
  stable/ingressmonitorcontroller/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24130 [stable/instana-agent] add repo archive notice
  stable/instana-agent/Chart.yaml
  stable/instana-agent/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24132 [stable/janusgraph] add repo archive notice
  stable/janusgraph/Chart.yaml
  stable/janusgraph/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24133 [stable/k8s-spot-rescheduler] add repo archive notice
  stable/k8s-spot-rescheduler/Chart.yaml
  stable/k8s-spot-rescheduler/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24134 [stable/k8s-spot-termination-handler] add repo archive notice
  stable/k8s-spot-termination-handler/Chart.yaml
  stable/k8s-spot-termination-handler/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24135 [stable/kafka-manager] add repo archive notice
  stable/kafka-manager/Chart.yaml
  stable/kafka-manager/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24137 [stable/karma] add repo archive notice
  stable/karma/Chart.yaml
  stable/karma/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24138 [stable/katafygio] add repo archive notice
  stable/katafygio/Chart.yaml
  stable/katafygio/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24139 [stable/kube-hunter] add repo archive notice
  stable/kube-hunter/Chart.yaml
  stable/kube-hunter/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24140 [stable/kube-ops-view] add repo archive notice
  stable/kube-ops-view/Chart.yaml
  stable/kube-ops-view/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24141 [stable/kube-slack] add repo archive notice
  stable/kube-slack/Chart.yaml
  stable/kube-slack/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24142 [stable/kube-state-metrics] add repo archive notice
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24147 [stable/locust] add repo archive notice
  stable/locust/Chart.yaml
  stable/locust/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24148 [stable/logdna-agent] add repo archive notice
  stable/logdna-agent/Chart.yaml
  stable/logdna-agent/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24153 [stable/memcached] add repo archive notice
  stable/memcached/Chart.yaml
  stable/memcached/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24154 [stable/mercure] add repo archive notice
  stable/mercure/Chart.yaml
  stable/mercure/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24155 [stable/metabase] add repo archive notice
  stable/metabase/Chart.yaml
  stable/metabase/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24156 [stable/metricbeat] add repo archive notice
  stable/metricbeat/Chart.yaml
  stable/metricbeat/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24159 [stable/mssql-linux] add repo archive notice
  stable/mssql-linux/Chart.yaml
  stable/mssql-linux/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24160 [stable/mysql] add repo archive notice
  stable/mysql/Chart.yaml
  stable/mysql/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24162 [stable/newrelic-infrastructure] add repo archive notice
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24163 [stable/nfs-client-provisioner] add repo archive notice
  stable/nfs-client-provisioner/Chart.yaml
  stable/nfs-client-provisioner/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24164 [stable/nfs-server-provisioner] add repo archive notice
  stable/nfs-server-provisioner/Chart.yaml
  stable/nfs-server-provisioner/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24165 [stable/node-problem-detector] add repo archive notice
  stable/node-problem-detector/Chart.yaml
  stable/node-problem-detector/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24166 [stable/oauth2-proxy] add repo archive notice
  stable/oauth2-proxy/Chart.yaml
  stable/oauth2-proxy/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24167 [stable/opa] add repo archive notice
  stable/opa/Chart.yaml
  stable/opa/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24168 [stable/openiban] add repo archive notice
  stable/openiban/Chart.yaml
  stable/openiban/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24169 [stable/openldap] add repo archive notice
  stable/openldap/Chart.yaml
  stable/openldap/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24170 [stable/openvpn] add repo archive notice
  stable/openvpn/Chart.yaml
  stable/openvpn/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24172 [stable/percona-xtradb-cluster] add repo archive notice
  stable/percona-xtradb-cluster/Chart.yaml
  stable/percona-xtradb-cluster/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24173 [stable/percona] add repo archive notice
  stable/percona/Chart.yaml
  stable/percona/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24174 [stable/pomerium] add repo archive notice
  stable/pomerium/Chart.yaml
  stable/pomerium/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24177 [stable/quassel] add repo archive notice
  stable/quassel/Chart.yaml
  stable/quassel/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24178 [stable/redis-ha] add repo archive notice
  stable/redis-ha/Chart.yaml
  stable/redis-ha/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24179 [stable/rethinkdb] add repo archive notice
  stable/rethinkdb/Chart.yaml
  stable/rethinkdb/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24181 [stable/rocketchat] add repo archive notice
  stable/rocketchat/Chart.yaml
  stable/rocketchat/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24182 [stable/rookout] add repo archive notice
  stable/rookout/Chart.yaml
  stable/rookout/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24184 [stable/satisfy] add repo archive notice
  stable/satisfy/Chart.yaml
  stable/satisfy/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24185 [stable/schema-registry-ui] add repo archive notice
  stable/schema-registry-ui/Chart.yaml
  stable/schema-registry-ui/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24186 [stable/sealed-secrets] add repo archive notice
  stable/sealed-secrets/Chart.yaml
  stable/sealed-secrets/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24187 [stable/selenium] add repo archive notice
  stable/selenium/Chart.yaml
  stable/selenium/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24189 [stable/sentry] add repo archive notice
  stable/sentry/Chart.yaml
  stable/sentry/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24190 [stable/seq] add repo archive notice
  stable/seq/Chart.yaml
  stable/seq/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24191 [stable/signalsciences] add repo archive notice
  stable/signalsciences/Chart.yaml
  stable/signalsciences/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24192 [stable/socat-tunneller] add repo archive notice
  stable/socat-tunneller/Chart.yaml
  stable/socat-tunneller/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24194 [stable/spark] add repo archive notice
  stable/spark/Chart.yaml
  stable/spark/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24196 [stable/spinnaker] add repo archive notice
  stable/spinnaker/Chart.yaml
  stable/spinnaker/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24198 [stable/stackdriver-exporter] add repo archive notice
  stable/stackdriver-exporter/Chart.yaml
  stable/stackdriver-exporter/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24200 [stable/stolon] add repo archive notice
  stable/stolon/Chart.yaml
  stable/stolon/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24201 [stable/sumokube] add repo archive notice
  stable/sumokube/Chart.yaml
  stable/sumokube/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24203 [stable/superset] add repo archive notice
  stable/superset/Chart.yaml
  stable/superset/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24204 [stable/tensorflow-notebook] add repo archive notice
  stable/tensorflow-notebook/Chart.yaml
  stable/tensorflow-notebook/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24205 [stable/tensorflow-serving] add repo archive notice #24136
  stable/tensorflow-serving/Chart.yaml
  stable/tensorflow-serving/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#24206 [stable/terracotta] add repo archive notice
  stable/terracotta/Chart.yaml
  stable/terracotta/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24207 [stable/tomcat] add repo archive notice
  stable/tomcat/Chart.yaml
  stable/tomcat/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24208 [stable/traefik] add repo archive notice
  stable/traefik/Chart.yaml
  stable/traefik/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24210 [stable/unbound] add repo archive notice
  stable/unbound/Chart.yaml
  stable/unbound/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24211 [stable/vault-operator] add repo archive notice
  stable/vault-operator/Chart.yaml
  stable/vault-operator/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24212 [stable/verdaccio] add repo archive notice
  stable/verdaccio/Chart.yaml
  stable/verdaccio/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24213 [stable/vsphere-cpi] add repo archive notice
  stable/vsphere-cpi/Chart.yaml
  stable/vsphere-cpi/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24214 [stable/weave-cloud] add repo archive notice
  stable/weave-cloud/Chart.yaml
  stable/weave-cloud/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24215 [stable/weave-scope] add repo archive notice
  stable/weave-scope/Chart.yaml
  stable/weave-scope/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24216 [stable/zeppelin] add repo archive notice
  stable/zeppelin/Chart.yaml
  stable/zeppelin/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24219 [stable/spark-history-server] servicePort should retrieve from Values
  stable/spark-history-server/Chart.yaml
  stable/spark-history-server/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#24221 [stable/elasticsearch-exporter] Deprecate chart
  stable/elasticsearch-exporter/Chart.yaml
  stable/elasticsearch-exporter/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#24049 [incubator/keycloak-proxy] add repo archive notice
  incubator/keycloak-proxy/Chart.yaml
  incubator/keycloak-proxy/README.md
  incubator/keycloak-proxy/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#24045 [incubator/goldfish] add repo archive notice
  incubator/goldfish/Chart.yaml
  incubator/goldfish/README.md
  incubator/goldfish/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#24038 [incubator/check-mk] add repo archive notice
  incubator/check-mk/Chart.yaml
  incubator/check-mk/README.md
  incubator/check-mk/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#24043 [incubator/fluentd-cloudwatch] add repo archive notice
  incubator/fluentd-cloudwatch/Chart.yaml
  incubator/fluentd-cloudwatch/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24044 [incubator/gogs] add repo archive notice
  incubator/gogs/Chart.yaml
  incubator/gogs/README.md
  incubator/gogs/requirements.lock
  incubator/gogs/requirements.yaml
  incubator/gogs/templates/_helpers.tpl
  incubator/gogs/templates/deployment.yaml
  incubator/gogs/templates/secrets.yaml
  incubator/gogs/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#24058 [incubator/puppet-forge] add repo archive notice
  incubator/puppet-forge/Chart.yaml
  incubator/puppet-forge/README.md
  incubator/puppet-forge/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#24059 [incubator/raw] add repo archive notice
  incubator/raw/Chart.yaml
  incubator/raw/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#24070 [incubator/vaultingkube] add repo archive notice
  incubator/vaultingkube/Chart.yaml
  incubator/vaultingkube/README.md
  incubator/vaultingkube/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#24062 [incubator/riemann] add repo archive notice
  incubator/riemann/Chart.yaml
  incubator/riemann/README.md
  incubator/riemann/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/S
