Repository helm/charts, pull requests merged in 2020-08, with the labels that each got.

#23414 [stable/minio] add deprecation notice for minio chart
  stable/minio/Chart.yaml
  stable/minio/OWNERS
  stable/minio/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23411 [stable/kube-state-metrics] Add annotations for serviceAccount
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
  stable/kube-state-metrics/templates/serviceaccount.yaml
  stable/kube-state-metrics/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23378 [stable/jenkins] Add support for initializing Jenkins master only once
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/config.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23412 [stable/grafana] Avoid creating a secret with empty LDAP config
  stable/grafana/Chart.yaml
  stable/grafana/templates/secret.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23399 [stable/grafana] enable UNIQUE_FILENAMES variable options for kiwigrid/k8s-sidecar
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/_pod.tpl
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23421 [stable/prometheus-blackbox-exporter] remove replicas and strategy keys from daemonset template
  stable/prometheus-blackbox-exporter/Chart.yaml
  stable/prometheus-blackbox-exporter/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23430 [stable/opa] allow hostNetwork setting on OPA pod
  stable/opa/Chart.yaml
  stable/opa/README.md
  stable/opa/templates/deployment.yaml
  stable/opa/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#23319 [stable/prometheus-blackbox-exporter] fix(helm#23318): PodSecurityPolicy NET_RAW capability
  stable/prometheus-blackbox-exporter/Chart.yaml
  stable/prometheus-blackbox-exporter/templates/podsecuritypolicy.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23273 [stable/prometheus-blackbox-exporter] added network policy
  stable/prometheus-blackbox-exporter/Chart.yaml
  stable/prometheus-blackbox-exporter/README.md
  stable/prometheus-blackbox-exporter/ci/networkpolicy-values.yaml
  stable/prometheus-blackbox-exporter/templates/networkpolicy.yaml
  stable/prometheus-blackbox-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#23423 [stable/grafana] Typo: missing a backtick in README.md
  stable/grafana/Chart.yaml
  stable/grafana/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23431 [stable/satisfy] upgrade to use apps/v1
  stable/satisfy/Chart.yaml
  stable/satisfy/templates/_helpers.tpl
  stable/satisfy/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23353 [stable/prometheus-operator] add missing Grafana Annotations to k8s-coredns dashboard
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-coredns.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23437 [incubator/kube-downscaler] Bump to 20.5.0 and update default values to match
  incubator/kube-downscaler/Chart.yaml
  incubator/kube-downscaler/README.md
  incubator/kube-downscaler/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#23384 [stable/datadog] Deprecate stable/datadog
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, size/M

#20084 [stable/etcd-operator] EtcdCluster CRD image override
  stable/etcd-operator/Chart.yaml
  stable/etcd-operator/templates/etcd-cluster-crd.yaml
  stable/etcd-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23449 [stable/rabbitmq-ha] Upgrade RabbitMQ to 3.8.6 version
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23366 [stable/spinnaker]: add taint and node selector
  stable/spinnaker/Chart.yaml
  stable/spinnaker/templates/statefulsets/halyard.yaml
  stable/spinnaker/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23459 [stable/envoy] Added loadBalancerSourceRanges for Service objects
  stable/envoy/Chart.yaml
  stable/envoy/README.md
  stable/envoy/templates/service.yaml
  stable/envoy/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23461 [incubator/cassandra] Support for additional volumes and sidecars
  incubator/cassandra/Chart.yaml
  incubator/cassandra/README.md
  incubator/cassandra/templates/statefulset.yaml
  incubator/cassandra/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#23479 [stable/metabase] Upgrade metabase to 0.36.3
  stable/metabase/Chart.yaml
  stable/metabase/README.md
  stable/metabase/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23454 [stable/elasticsearch-exporter] Make sampleLimit adjustable
  stable/elasticsearch-exporter/Chart.yaml
  stable/elasticsearch-exporter/README.md
  stable/elasticsearch-exporter/templates/servicemonitor.yaml
  stable/elasticsearch-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#23470 [incubator/etcd] Update StatefulSet apiVersion to apps/v1
  incubator/etcd/Chart.yaml
  incubator/etcd/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23367 [stable/stolon] support secrets for initdb pod
  stable/stolon/Chart.yaml
  stable/stolon/templates/hooks/init-db-job.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#23468 [stable/graylog] provisioner job hook
  stable/graylog/Chart.yaml
  stable/graylog/README.md
  stable/graylog/templates/job.yaml
  stable/graylog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23469 [stable/coredns] Prevent port template failures if the optional use_tcp parameter is not set
  stable/coredns/Chart.yaml
  stable/coredns/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23473 [stable/janusgraph] NodeSelector configuration support
  stable/janusgraph/Chart.yaml
  stable/janusgraph/templates/deployment.yaml
  stable/janusgraph/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23504 [stable/airflow] improve celery worker graceful shutdown
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/UPGRADE.md
  stable/airflow/examples/google-gke/custom-values.yaml
  stable/airflow/templates/configmap-scripts.yaml
  stable/airflow/templates/statefulsets-workers.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#23506 [stable/prometheus] update prometheus to 2.20.1 and cm reloader to 0.4.0
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#23416 [stable/logstash] Added envFrom support to logstash container
  stable/logstash/Chart.yaml
  stable/logstash/README.md
  stable/logstash/templates/statefulset.yaml
  stable/logstash/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23482 [stable/openldap] Support setting container image log level
  stable/openldap/Chart.yaml
  stable/openldap/README.md
  stable/openldap/templates/deployment.yaml
  stable/openldap/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23520 [stable/spring-cloud-data-flow] Update to new SCDF version 2.5.3
  stable/spring-cloud-data-flow/Chart.yaml
  stable/spring-cloud-data-flow/README.md
  stable/spring-cloud-data-flow/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#23522 [stable/spring-cloud-data-flow] Update to new SCDF version 2.6.0
  stable/spring-cloud-data-flow/Chart.yaml
  stable/spring-cloud-data-flow/README.md
  stable/spring-cloud-data-flow/templates/server-deployment.yaml
  stable/spring-cloud-data-flow/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#23500 [stable/airflow] Remove connection before adding it
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/templates/secret-connections.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#22658 [stable/nfs-client-provisioner] Added ability to configure accessModes
  stable/nfs-client-provisioner/Chart.yaml
  stable/nfs-client-provisioner/README.md
  stable/nfs-client-provisioner/templates/persistentvolume.yaml
  stable/nfs-client-provisioner/templates/persistentvolumeclaim.yaml
  stable/nfs-client-provisioner/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#23509 [stable/anchore-engine] deprecate chart
  stable/anchore-engine/Chart.yaml
  stable/anchore-engine/README.md
  stable/anchore-engine/charts/postgresql/Chart.yaml
  stable/anchore-engine/charts/postgresql/README.md
  stable/anchore-engine/charts/postgresql/templates/NOTES.txt
  stable/anchore-engine/charts/postgresql/templates/_helpers.tpl
  stable/anchore-engine/charts/postgresql/templates/configmap.yaml
  stable/anchore-engine/charts/postgresql/templates/deployment.yaml
  stable/anchore-engine/charts/postgresql/templates/networkpolicy.yaml
  stable/anchore-engine/charts/postgresql/templates/pvc.yaml
  stable/anchore-engine/charts/postgresql/templates/secrets.yaml
  stable/anchore-engine/charts/postgresql/templates/svc.yaml
  stable/anchore-engine/charts/postgresql/values.yaml
  stable/anchore-engine/requirements.lock
  stable/anchore-engine/requirements.yaml
  stable/anchore-engine/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XXL

#23558 [stable/instana-agent] Chart version 1.0.30
  stable/instana-agent/Chart.yaml
  stable/instana-agent/templates/_helpers.tpl
  stable/instana-agent/templates/clusterrole.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#23556 [stable/opa] add extraArgs to opa container
  stable/opa/Chart.yaml
  stable/opa/README.md
  stable/opa/templates/deployment.yaml
  stable/opa/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#23557 stable/chartmuseum: Fix condition for setting schedulerName
  stable/chartmuseum/Chart.yaml
  stable/chartmuseum/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23534 [stable/spinnaker] Add the option to allow "live manifest calls" by Clouddriver when deploying Kubernetes Cluster resources
  stable/spinnaker/Chart.yaml
  stable/spinnaker/templates/configmap/halyard-config.yaml
  stable/spinnaker/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#23567 [stable/incubator] remove failing icon/logo links
  incubator/artifactory/Chart.yaml
  incubator/distribution/Chart.yaml
  incubator/elastic-stack/Chart.yaml
  incubator/xray/Chart.yaml
  incubator/xray/ci/test-values.yaml
  stable/artifactory-ha/Chart.yaml
  stable/artifactory/Chart.yaml
  stable/distribution/Chart.yaml
  stable/elastic-stack/Chart.yaml
  stable/mission-control/Chart.yaml
  stable/mission-control/ci/test-values.yaml
  stable/xray/Chart.yaml
  stable/xray/ci/test-values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#23571 [incubator/spring-cloud-data-flow] Fix missing icon from deprecated chart
  incubator/spring-cloud-data-flow/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#23560 [stable/airflow] enable database properties configuration for external database
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/UPGRADE.md
  stable/airflow/templates/_helpers.tpl
  stable/airflow/templates/configmap-env.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#22823 [stable/nginx-ingress] Update nginx-ingress README for deprecation
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, size/S

#23486 [stable/metallb] Deprecate chart in favour of the bitnami maintained one.
  stable/metallb/Chart.yaml
  stable/metallb/README.md
  stable/metallb/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, size/S

#23574 [stable/rabbitmq-ha] Upgrade RabbitMQ to 3.8.7 version
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23448 stable/jenkins - Feature: Support Resource Root URL in Ingress
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/jenkins-master-ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23429 stable/jenkins - Changes as per JENKINS-47112
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23604 [stable/gocd] Bump up GoCD Version to 20.7.0
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23305 [stable/cluster-autoscaler] Deprecating chart
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23379 [stable/unifi] Docs: Fix name of cert secret
  stable/unifi/Chart.yaml
  stable/unifi/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23621 [stable/opa] Adding imagePullSecret to OPA
  stable/opa/Chart.yaml
  stable/opa/templates/deployment.yaml
  stable/opa/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23633 [stable/rocketchat] fix incompatible types for comparison (replicaCount)
  stable/rocketchat/Chart.yaml
  stable/rocketchat/templates/poddisruptionbudget.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#23626 [stable/mysqldump] fix mysqldump install for newer helm3 versions
  stable/mysqldump/Chart.yaml
  stable/mysqldump/templates/configmap.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#23586 [stable/cluster-overprovisioner] Deprecate cluster-overprovisioner
  stable/cluster-overprovisioner/Chart.yaml
  stable/cluster-overprovisioner/README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#23627 [stable/nextcloud] deprecate nextcloud helm chart
  stable/nextcloud/Chart.yaml
  stable/nextcloud/README.md
  stable/nextcloud/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, size/S

#23632 [incubator/buzzfeed-sso] Add support for multiple paths for the same host
  incubator/buzzfeed-sso/Chart.yaml
  incubator/buzzfeed-sso/templates/ingress.yaml
  incubator/buzzfeed-sso/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#23295 [stable/spring-cloud-data-flow] Move chart to distributed bitnami repository
  stable/spring-cloud-data-flow/Chart.yaml
  stable/spring-cloud-data-flow/README.md
  stable/spring-cloud-data-flow/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M
