Repository helm/charts, pull requests merged in 2020-04, with the labels that each got.

#21713 [stable/sematext-agent] replicasets roles
  stable/sematext-agent/Chart.yaml
  stable/sematext-agent/templates/clusterrole.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#21562 [stable/prometheus-operator] Update Grafana chart dependency to include fix from #21442
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/requirements.lock
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21711 [stable/sysdig] Use latest Sysdig Agent version (9.8.0)
  stable/sysdig/CHANGELOG.md
  stable/sysdig/Chart.yaml
  stable/sysdig/README.md
  stable/sysdig/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#21609 [stable/grafana] Add option testFramework.imagePullPolicy
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/tests/test.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21676 [stable/oauth2-proxy] Upgrade to v5.1.0.
  stable/oauth2-proxy/Chart.yaml
  stable/oauth2-proxy/README.md
  stable/oauth2-proxy/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#21659 [incubator/cassandra] Disable Cassandra exporter and service monitor by default.
  incubator/cassandra/Chart.yaml
  incubator/cassandra/templates/servicemonitor.yaml
  incubator/cassandra/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#20560 [stable/signalsciences] updated for new signalsciences version and best practices
  stable/signalsciences/Chart.yaml
  stable/signalsciences/README.md
  stable/signalsciences/templates/daemonset.yaml
  stable/signalsciences/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#20942 [stable/neo4j] Neo4j fixes
  stable/neo4j/Chart.yaml
  stable/neo4j/README.md
  stable/neo4j/templates/core-dns.yaml
  stable/neo4j/templates/core-statefulset.yaml
  stable/neo4j/templates/poddisruptionbudget.yaml
  stable/neo4j/templates/readreplicas-deployment.yaml
  stable/neo4j/templates/readreplicas-hpa.yaml
  stable/neo4j/templates/secret.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#21619 [ci] Print helm version in job lint-charts in order to make debugging of issues more easy
  .circleci/config.yml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21581 [stable/prometheus-operator] Fix KubeVersion condition in coredns dashboard
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-coredns.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21706 [stable/home-assistant] added token support for servicemonitor
  stable/home-assistant/Chart.yaml
  stable/home-assistant/README.md
  stable/home-assistant/templates/servicemonitor.yaml
  stable/home-assistant/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#21707 [stable/cerebro] Add support for adding labels and annotations to pod
  stable/cerebro/Chart.yaml
  stable/cerebro/README.md
  stable/cerebro/templates/deployment.yaml
  stable/cerebro/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21721 [stable/dex] version 2.23.0 + support for metrics.
  stable/dex/Chart.yaml
  stable/dex/templates/deployment.yaml
  stable/dex/templates/secret.yaml
  stable/dex/templates/service.yaml
  stable/dex/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21717 Added option externalTrafficPolicy
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/templates/service.yaml
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21344 [stable/rabbitmq-ha] Added volume permissions
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21726 [stable/prometheus-blackbox-exporter] Add serviceAccount support
  stable/prometheus-blackbox-exporter/Chart.yaml
  stable/prometheus-blackbox-exporter/README.md
  stable/prometheus-blackbox-exporter/templates/_helpers.tpl
  stable/prometheus-blackbox-exporter/templates/deployment.yaml
  stable/prometheus-blackbox-exporter/templates/serviceaccount.yaml
  stable/prometheus-blackbox-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21723 Bmailhe jenkins
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/jenkins-master-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21653 [stable/prometheus-operator] Conditional cAdvisor metrics for kubelet's serviceMonitor
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/exporters/kubelet/servicemonitor.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21708 [stable/nginx-ingress] Adding ability to specify an override value for the release label
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/NOTES.txt
  stable/nginx-ingress/templates/_helpers.tpl
  stable/nginx-ingress/templates/addheaders-configmap.yaml
  stable/nginx-ingress/templates/admission-webhooks/job-patch/clusterrole.yaml
  stable/nginx-ingress/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
  stable/nginx-ingress/templates/admission-webhooks/job-patch/job-createSecret.yaml
  stable/nginx-ingress/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
  stable/nginx-ingress/templates/admission-webhooks/job-patch/psp.yaml
  stable/nginx-ingress/templates/admission-webhooks/job-patch/role.yaml
  stable/nginx-ingress/templates/admission-webhooks/job-patch/rolebinding.yaml
  stable/nginx-ingress/templates/admission-webhooks/job-patch/serviceaccount.yaml
  stable/nginx-ingress/templates/admission-webhooks/validating-webhook.yaml
  stable/nginx-ingress/templates/clusterrole.yaml
  stable/nginx-ingress/templates/clusterrolebinding.yaml
  stable/nginx-ingress/templates/controller-configmap.yaml
  stable/nginx-ingress/templates/controller-daemonset.yaml
  stable/nginx-ingress/templates/controller-deployment.yaml
  stable/nginx-ingress/templates/controller-hpa.yaml
  stable/nginx-ingress/templates/controller-metrics-service.yaml
  stable/nginx-ingress/templates/controller-poddisruptionbudget.yaml
  stable/nginx-ingress/templates/controller-prometheusrules.yaml
  stable/nginx-ingress/templates/controller-psp.yaml
  stable/nginx-ingress/templates/controller-role.yaml
  stable/nginx-ingress/templates/controller-rolebinding.yaml
  stable/nginx-ingress/templates/controller-service.yaml
  stable/nginx-ingress/templates/controller-serviceaccount.yaml
  stable/nginx-ingress/templates/controller-servicemonitor.yaml
  stable/nginx-ingress/templates/controller-webhook-service.yaml
  stable/nginx-ingress/templates/default-backend-deployment.yaml
  stable/nginx-ingress/templates/default-backend-poddisruptionbudget.yaml
  stable/nginx-ingress/templates/default-backend-psp.yaml
  stable/nginx-ingress/templates/default-backend-role.yaml
  stable/nginx-ingress/templates/default-backend-rolebinding.yaml
  stable/nginx-ingress/templates/default-backend-service.yaml
  stable/nginx-ingress/templates/default-backend-serviceaccount.yaml
  stable/nginx-ingress/templates/proxyheaders-configmap.yaml
  stable/nginx-ingress/templates/tcp-configmap.yaml
  stable/nginx-ingress/templates/udp-configmap.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#21715 [stable/oauth2-proxy] use proper scope in usage of secret name helper
  stable/oauth2-proxy/Chart.yaml
  stable/oauth2-proxy/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21733 Upgrade chart-testing
  .circleci/config.yml
  test/Dockerfile
  test/build.sh
  test/e2e.sh
Labels: Contribution Allowed, approved, lgtm

#21671 [stable/jenkins] Add support for custom pod templates
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/ci/casc-values.yaml
  stable/jenkins/templates/_helpers.tpl
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21462 [stable/prometheus-operator] Use disableCompaction value
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/prometheus/prometheus.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21587 [stable/home-assistant] Add AppDaemon
  stable/home-assistant/Chart.yaml
  stable/home-assistant/README.md
  stable/home-assistant/templates/appdaemon-ingress.yaml
  stable/home-assistant/templates/deployment.yaml
  stable/home-assistant/templates/secret.yaml
  stable/home-assistant/templates/service.yaml
  stable/home-assistant/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/L

#21762 Update deprecation timeline COVID-19
  README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#21700 [stable/rabbitmq-ha] Add a selector to persistentVolumeClaims to be able to target an existing persistentVolume
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/templates/statefulset.yaml
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21704 [stable/mongodb-replicaset] feature: Add support for secret annotations when auth is enabled
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/README.md
  stable/mongodb-replicaset/templates/mongodb-admin-secret.yaml
  stable/mongodb-replicaset/templates/mongodb-keyfile-secret.yaml
  stable/mongodb-replicaset/templates/mongodb-metrics-secret.yaml
  stable/mongodb-replicaset/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21693 [stable/metrics-server] Enhance doc/example for priorityClassName (#2…
  stable/metrics-server/Chart.yaml
  stable/metrics-server/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#18856 Kube 1.16 removed deprecated api
  incubator/mysqlha/Chart.yaml
  incubator/mysqlha/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21757 [stable/jenkins]: Define jenkinsHome variable to use in range blocks
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/config.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21773 [stable/jenkins] configure agent.args in values.yaml
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/_helpers.tpl
  stable/jenkins/templates/config.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#21744 [stable/cluster-autoscaler] fix: use serviceAccount.name for SA name if defined
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/README.md
  stable/cluster-autoscaler/templates/_helpers.tpl
  stable/cluster-autoscaler/templates/clusterrolebinding.yaml
  stable/cluster-autoscaler/templates/deployment.yaml
  stable/cluster-autoscaler/templates/rolebinding.yaml
  stable/cluster-autoscaler/templates/serviceaccount.yaml
  stable/cluster-autoscaler/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21777 [stable/redis-ha] Fixed unused env section.
  stable/redis-ha/Chart.yaml
  stable/redis-ha/templates/redis-ha-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#21670 [stable/node-problem-detector] Add support for extra volumes
  stable/node-problem-detector/Chart.yaml
  stable/node-problem-detector/README.md
  stable/node-problem-detector/templates/daemonset.yaml
  stable/node-problem-detector/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#20483 [stable/fluent-bit] Fix for google_service_credentials, fixes #20482
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21787 [stable/several] Fix typo in deprecation comment
  stable/dokuwiki/Chart.yaml
  stable/drupal/Chart.yaml
  stable/external-dns/Chart.yaml
  stable/ghost/Chart.yaml
  stable/jasperreports/Chart.yaml
  stable/joomla/Chart.yaml
  stable/kubewatch/Chart.yaml
  stable/mariadb/Chart.yaml
  stable/mediawiki/Chart.yaml
  stable/mongodb/Chart.yaml
  stable/moodle/Chart.yaml
  stable/nats/Chart.yaml
  stable/odoo/Chart.yaml
  stable/opencart/Chart.yaml
  stable/orangehrm/Chart.yaml
  stable/osclass/Chart.yaml
  stable/owncloud/Chart.yaml
  stable/parse/Chart.yaml
  stable/phabricator/Chart.yaml
  stable/phpbb/Chart.yaml
  stable/phpmyadmin/Chart.yaml
  stable/postgresql/Chart.yaml
  stable/prestashop/Chart.yaml
  stable/redmine/Chart.yaml
  stable/suitecrm/Chart.yaml
  stable/testlink/Chart.yaml
  stable/wordpress/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#20293 [stable/sentry] Add option to disable dbInit job hook
  stable/sentry/Chart.yaml
  stable/sentry/README.md
  stable/sentry/templates/hooks/db-init.job.yaml
  stable/sentry/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21766 [stable/datadog] fix leader election
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/templates/containers-init.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#21633 stable/jenkins update kubernetes plugin to 1.25.1, add 'events' r…
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/rbac.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21550 [stable/datadog] Add Windows support and minor fixes
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/_helpers.tpl
  stable/datadog/templates/agent-apiservice.yaml
  stable/datadog/templates/agent-clusterchecks-deployment.yaml
  stable/datadog/templates/cluster-agent-deployment.yaml
  stable/datadog/templates/container-agent.yaml
  stable/datadog/templates/container-process-agent.yaml
  stable/datadog/templates/container-trace-agent.yaml
  stable/datadog/templates/containers-init-linux.yaml
  stable/datadog/templates/containers-init-windows.yaml
  stable/datadog/templates/daemonset-volumes-linux.yaml
  stable/datadog/templates/daemonset-volumes-windows.yaml
  stable/datadog/templates/daemonset.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#21685 [stable/prometheus-pushgateway] configureable deployment strategy
  stable/prometheus-pushgateway/Chart.yaml
  stable/prometheus-pushgateway/README.md
  stable/prometheus-pushgateway/templates/deployment.yaml
  stable/prometheus-pushgateway/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21712 [stable/newrelic-infrastructure] Fix templating for feature to disable KSM parsing
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#21801 [stable/nginx-ingress] Adding ability to add labels to the controller and default backend deployment
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-deployment.yaml
  stable/nginx-ingress/templates/default-backend-deployment.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21795 [stable/cluster-autoscaler] fix: use correct reference to serviceAccount in _helpers.tpl
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21764 [anchore/stable] fix environment setting from existingSecret
  stable/anchore-engine/Chart.yaml
  stable/anchore-engine/templates/api_deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21740 [stable/rabbitmq-ha] Fix security context for init container
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21776 [stable/prometheus-blackbox-exporter] Add PrometheusRule support
  stable/prometheus-blackbox-exporter/Chart.yaml
  stable/prometheus-blackbox-exporter/README.md
  stable/prometheus-blackbox-exporter/templates/prometheusrule.yaml
  stable/prometheus-blackbox-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#21802 [stable/prometheus-operator]: additionalScrapeConfigs in docs must be `[]` not the `{}`
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21761 [stable/node-problem-detector] Update the daemonset template volume mount to use hostpath.logdir variable
  stable/node-problem-detector/Chart.yaml
  stable/node-problem-detector/README.md
  stable/node-problem-detector/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#21816 [stable/newrelic-infrastructure] Update newrelic-infrastructure image version to 1.18.0
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/README.md
  stable/newrelic-infrastructure/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21822 [stable/sysdig] Add a hack to implement watches on Helm based Operator
  stable/sysdig/CHANGELOG.md
  stable/sysdig/Chart.yaml
  stable/sysdig/templates/_helpers.tpl
  stable/sysdig/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#21682 [stable/superset] Make it possible to configure start up
  stable/superset/Chart.yaml
  stable/superset/README.md
  stable/superset/templates/deployment.yaml
  stable/superset/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#21742 [incubator/sparkoperator] Support tolerations
  incubator/sparkoperator/Chart.yaml
  incubator/sparkoperator/README.md
  incubator/sparkoperator/ci/test-values.yaml
  incubator/sparkoperator/templates/spark-operator-deployment.yaml
  incubator/sparkoperator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21831 [stable/karma] Upgrade karma to v0.60.
  stable/karma/Chart.yaml
  stable/karma/README.md
  stable/karma/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#21823 stable/goldpinter: Only use pullSecrets if defined in values.yaml
  stable/goldpinger/Chart.yaml
  stable/goldpinger/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21832 [stable/metrics-server] Add release.Namespace in meta
  stable/metrics-server/Chart.yaml
  stable/metrics-server/templates/auth-delegator-crb.yaml
  stable/metrics-server/templates/metric-server-service.yaml
  stable/metrics-server/templates/metrics-server-deployment.yaml
  stable/metrics-server/templates/metrics-server-serviceaccount.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21824 [stable/prometheus-operator] fix: remove status field in CRDs
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/crds/crd-alertmanager.yaml
  stable/prometheus-operator/crds/crd-podmonitor.yaml
  stable/prometheus-operator/crds/crd-prometheus.yaml
  stable/prometheus-operator/crds/crd-prometheusrules.yaml
  stable/prometheus-operator/crds/crd-servicemonitor.yaml
  stable/prometheus-operator/crds/crd-thanosrulers.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21800 [stable/elastalert]: improve templates - add variables for override fullname of chart
  stable/elastalert/Chart.yaml
  stable/elastalert/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21837 [stable/prometheus-operator] Adding initContainer capabilites in prometheus specs template
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/prometheus/prometheus.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21825 [stable/sysdig] Add SCC if Openshift is detected
  stable/sysdig/CHANGELOG.md
  stable/sysdig/Chart.yaml
  stable/sysdig/README.md
  stable/sysdig/templates/securitycontextconstraint.yaml
  stable/sysdig/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21839 [stable/selenium] Fix selenium configuration
  stable/selenium/Chart.yaml
  stable/selenium/README.md
  stable/selenium/templates/hub-deployment.yaml
  stable/selenium/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20091 [stable/minio]: fix extraArgs values being ignored by minio binary inside pod
  stable/minio/Chart.yaml
  stable/minio/templates/_helpers.tpl
  stable/minio/templates/deployment.yaml
  stable/minio/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21774 [stable/prometheus] Added extraInitContainers to match server
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/alertmanager-deployment.yaml
  stable/prometheus/templates/node-exporter-daemonset.yaml
  stable/prometheus/templates/pushgateway-deployment.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21838 stable/prometheus-cloudwatch-exporter Add prometheusRule creation.
  stable/prometheus-cloudwatch-exporter/CHANGELOG.md
  stable/prometheus-cloudwatch-exporter/Chart.yaml
  stable/prometheus-cloudwatch-exporter/README.md
  stable/prometheus-cloudwatch-exporter/templates/prometheusrule.yaml
  stable/prometheus-cloudwatch-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21805 [stable/prometheus] add hostAliases
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/server-deployment.yaml
  stable/prometheus/templates/server-statefulset.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21851 Updating useConfigMap & customAgentConfig param desc
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#21848 [stable/prometheus-redis-exporter] Add support for tolerations and affinity
  stable/prometheus-redis-exporter/Chart.yaml
  stable/prometheus-redis-exporter/README.md
  stable/prometheus-redis-exporter/templates/deployment.yaml
  stable/prometheus-redis-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21850 [stable/elastalert] Add ServiceAccount and PodSecurityPolicy to Elastalert
  stable/elastalert/Chart.yaml
  stable/elastalert/README.md
  stable/elastalert/templates/_helpers.tpl
  stable/elastalert/templates/deployment.yaml
  stable/elastalert/templates/podsecuritypolicy.yaml
  stable/elastalert/templates/role.yaml
  stable/elastalert/templates/rolebinding.yaml
  stable/elastalert/templates/serviceaccount.yaml
  stable/elastalert/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#21863 [stable/unifi] add custom cert options
  stable/unifi/Chart.yaml
  stable/unifi/README.md
  stable/unifi/templates/deployment.yaml
  stable/unifi/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21710 [stable/grafana]: Only replace variable datasources in shared dashboards
  stable/grafana/Chart.yaml
  stable/grafana/templates/configmap.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21877 [stable/prometheus] Cleanup kube state metrics.
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/_helpers.tpl
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#21672 [stable/jenkins] Support multiple agents
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/_helpers.tpl
  stable/jenkins/templates/config.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#21274 [stable/rabbitmq-ha] Install alerts when built-in Prometheus support …
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/templates/alerts.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21886 [stable/airflow] Update README.md Postgres details to match values
  stable/airflow/Chart.yaml
  stable/airflow/README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#21888 [stable/home-assistant] fix templates with go 1.14
  stable/home-assistant/Chart.yaml
  stable/home-assistant/templates/appdaemon-ingress.yaml
  stable/home-assistant/templates/configurator-ingress.yaml
  stable/home-assistant/templates/deployment.yaml
  stable/home-assistant/templates/vscode-ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21883 [stable/nginx-ingress] Fix documentation Validating webhook
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21890 [stable/chartmuseum] Add option to specify priorityClass to deployment
  stable/chartmuseum/Chart.yaml
  stable/chartmuseum/README.md
  stable/chartmuseum/templates/deployment.yaml
  stable/chartmuseum/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21868 [stable/node-problem-detector] Customizable securityContext
  stable/node-problem-detector/Chart.yaml
  stable/node-problem-detector/README.md
  stable/node-problem-detector/templates/daemonset.yaml
  stable/node-problem-detector/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#21892 [stable/stolon] Fix sentinel annotations
  stable/stolon/Chart.yaml
  stable/stolon/templates/sentinel-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#21897 stable/prometheus-operator: Add PSP annotations var
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/alertmanager/psp.yaml
  stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/psp.yaml
  stable/prometheus-operator/templates/prometheus-operator/psp.yaml
  stable/prometheus-operator/templates/prometheus/psp.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21457 stable/airflow: add initcontainer initdb option
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/templates/configmap-git-clone.yaml
  stable/airflow/templates/configmap-scripts.yaml
  stable/airflow/templates/deployments-scheduler.yaml
  stable/airflow/templates/deployments-web.yaml
  stable/airflow/templates/statefulsets-workers.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21869 [stable/node-problem-detector] remove flag--name which not working
  stable/node-problem-detector/Chart.yaml
  stable/node-problem-detector/README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#21915 [stable/kube-slack] Kube slack image from different CR
  stable/kube-slack/Chart.yaml
  stable/kube-slack/templates/deployment.yaml
  stable/kube-slack/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21640 [stable/elastic-stack] update filebeat for 1.16
  stable/elastic-stack/Chart.yaml
  stable/elastic-stack/README.md
  stable/elastic-stack/requirements.lock
  stable/elastic-stack/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21918 [stable/prometheus-adapter] Defining a variable for listen port
  stable/prometheus-adapter/Chart.yaml
  stable/prometheus-adapter/README.md
  stable/prometheus-adapter/templates/custom-metrics-apiserver-deployment.yaml
  stable/prometheus-adapter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21265 [stable/kube2iam] Allow setting a custom secret name to use for AWS credentials
  stable/kube2iam/Chart.yaml
  stable/kube2iam/README.md
  stable/kube2iam/templates/daemonset.yaml
  stable/kube2iam/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21599 stabel/jenkins: Feature: whitelist ip ranges and namespaces for agents connections
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/_helpers.tpl
  stable/jenkins/templates/jenkins-master-networkpolicy.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21873 [stable/nginx-ingress] fix servicemonitor selector
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/templates/controller-daemonset.yaml
  stable/nginx-ingress/templates/controller-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21718 [incubator/aws-alb-ingress-controller] reuse existing service account
  incubator/aws-alb-ingress-controller/Chart.yaml
  incubator/aws-alb-ingress-controller/README.md
  incubator/aws-alb-ingress-controller/templates/_helpers.tpl
  incubator/aws-alb-ingress-controller/templates/clusterrolebinding.yaml
  incubator/aws-alb-ingress-controller/templates/deployment.yaml
  incubator/aws-alb-ingress-controller/templates/serviceaccount.yaml
  incubator/aws-alb-ingress-controller/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#21807 [stable/prisma] Add missing config params supported by Prisma docker image
  stable/prisma/Chart.yaml
  stable/prisma/README.md
  stable/prisma/templates/configmap.yaml
  stable/prisma/templates/deployment.yaml
  stable/prisma/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21818 [stable/minio] fix identation for make-bucket-job
  stable/minio/Chart.yaml
  stable/minio/templates/post-install-create-bucket-job.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21728 [stable/hazelcast] Update README (#108)
  stable/hazelcast/Chart.yaml
  stable/hazelcast/README.adoc
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#21727 [stable/hazelcast-jet] Update README (#108)
  stable/hazelcast-jet/Chart.yaml
  stable/hazelcast-jet/README.adoc
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21445 [incubator/buzzfeed-sso] upgrade deprecated Kubernetes APIs
  incubator/buzzfeed-sso/Chart.yaml
  incubator/buzzfeed-sso/templates/_helpers.tpl
  incubator/buzzfeed-sso/templates/auth-deployment.yaml
  incubator/buzzfeed-sso/templates/ingress.yaml
  incubator/buzzfeed-sso/templates/proxy-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21858 [stable/mysql] add basic affinity support (#12054)
  stable/mysql/Chart.yaml
  stable/mysql/README.md
  stable/mysql/templates/deployment.yaml
  stable/mysql/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21930 [stable/sematext-agent] Update the docs for Helm 3
  stable/sematext-agent/Chart.yaml
  stable/sematext-agent/OWNERS
  stable/sematext-agent/README.md
  stable/sematext-agent/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#21926 [stable/openebs] update charts to 1.9.0 release
  stable/openebs/Chart.yaml
  stable/openebs/README.md
  stable/openebs/templates/daemonset-ndm.yaml
  stable/openebs/templates/deployment-admission-server.yaml
  stable/openebs/templates/deployment-local-provisioner.yaml
  stable/openebs/templates/deployment-maya-provisioner.yaml
  stable/openebs/templates/deployment-maya-snapshot-operator.yaml
  stable/openebs/templates/deployment-ndm-operator.yaml
  stable/openebs/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#21932 [stable/sysdig] Upgrade Sysdig Agent to its latest version (9.9.0)
  stable/sysdig/CHANGELOG.md
  stable/sysdig/Chart.yaml
  stable/sysdig/README.md
  stable/sysdig/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#21443 [stable/anchore-engine] Update apiVersion for ingress
  stable/anchore-engine/Chart.yaml
  stable/anchore-engine/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21628 Fix chart_best_practices links in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21943 [stable/instana-agent] Chart version 1.0.27
  stable/instana-agent/Chart.yaml
  stable/instana-agent/templates/clusterrole.yaml
  stable/instana-agent/templates/downloadsecret.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#21952 [stable/airflow] Fix airflow-preinitdb initContainer call
  stable/airflow/Chart.yaml
  stable/airflow/templates/deployments-scheduler.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#21939 [stable/hazelcast] Use VolumeClaimTemplates instead of PersistentVolumeClaim for Hot Restart (#119)
  stable/hazelcast/Chart.yaml
  stable/hazelcast/templates/mancenter-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#21938 [stable/node-problem-detector] fix and improve doc
  stable/node-problem-detector/Chart.yaml
  stable/node-problem-detector/README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#21956 [stable/home-assistant] fix port for VSCode extension
  stable/home-assistant/Chart.yaml
  stable/home-assistant/templates/service.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#21966 [stable/sealed-secrets]feat: Update to 0.12.2
  stable/sealed-secrets/Chart.yaml
  stable/sealed-secrets/README.md
  stable/sealed-secrets/templates/cluster-role.yaml
  stable/sealed-secrets/templates/sealedsecret-crd.yaml
  stable/sealed-secrets/templates/service.yaml
  stable/sealed-secrets/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21965 [stable/grafana] prefer .Values.image.tag over .Chart.AppVersion for "app.kubernetes.io/version" label
  stable/grafana/Chart.yaml
  stable/grafana/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21976 [stable/prometheus] Fix rollingUpdate: null indentation Recreate
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/alertmanager-deployment.yaml
  stable/prometheus/templates/pushgateway-deployment.yaml
  stable/prometheus/templates/server-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21870 stable/airflow: added horizontal pod autoscaler for Celery workers
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/templates/autoscaler-workers.yaml
  stable/airflow/templates/deployments-scheduler.yaml
  stable/airflow/templates/deployments-web.yaml
  stable/airflow/templates/statefulsets-workers.yaml
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21971 [stable/k8s-spot-rescheduler] Update executable name
  stable/k8s-spot-rescheduler/Chart.yaml
  stable/k8s-spot-rescheduler/templates/deployment.yaml
  stable/k8s-spot-rescheduler/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21980 [stable/sentry] add missing condition in templates to populate redis password env var
  stable/sentry/Chart.yaml
  stable/sentry/templates/cron-deployment.yaml
  stable/sentry/templates/hooks/db-init.job.yaml
  stable/sentry/templates/hooks/user-create.job.yaml
  stable/sentry/templates/web-deployment.yaml
  stable/sentry/templates/workers-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21981 [incubator/buzzfeed-sso] Add suport for v2.1.0
  incubator/buzzfeed-sso/Chart.yaml
  incubator/buzzfeed-sso/README.md
  incubator/buzzfeed-sso/templates/proxy-deployment.yaml
  incubator/buzzfeed-sso/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21922 [stable/datadog] incorrect indentation in cluster-agent-deployment.yaml #21921
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/templates/cluster-agent-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21989 [stable/prometheus] Fix rollingUpdate: null indentation Recreate fix for helm3
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/alertmanager-deployment.yaml
  stable/prometheus/templates/pushgateway-deployment.yaml
  stable/prometheus/templates/server-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21979 [stable/jenkins] fix yaml template rendering in kubernetes pod template JCasC
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21987 [stable/spinnaker] Fix incorrect dockerRegistry password-command quoting
  stable/spinnaker/Chart.yaml
  stable/spinnaker/README.md
  stable/spinnaker/templates/configmap/halyard-config.yaml
  stable/spinnaker/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21878 [stable/jenkins] Add support for custom ClusterIP
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/jenkins-master-svc.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21899 [stable/prometheus-operator]: Re-sync prometheus rules and grafana dashboards
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/apiserver.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kube-apiserver-slos.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kube-apiserver.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-apps.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-resources.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-storage.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/node-exporter.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XXL

#21829 [stable/prometheus-operator] Bump all docker images version
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/crds/crd-alertmanager.yaml
  stable/prometheus-operator/crds/crd-podmonitor.yaml
  stable/prometheus-operator/crds/crd-prometheus.yaml
  stable/prometheus-operator/crds/crd-prometheusrules.yaml
  stable/prometheus-operator/crds/crd-servicemonitor.yaml
  stable/prometheus-operator/crds/crd-thanosrulers.yaml
  stable/prometheus-operator/requirements.lock
  stable/prometheus-operator/requirements.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XXL

#21990 [stable/sentry] Pull S3 secrets from Secret rather than ConfigMap
  stable/sentry/Chart.yaml
  stable/sentry/README.md
  stable/sentry/templates/configmap.yaml
  stable/sentry/templates/secrets.yaml
  stable/sentry/templates/web-deployment.yaml
  stable/sentry/templates/workers-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21996 [stable/metrics-server] update metrics-server repo
  stable/metrics-server/Chart.yaml
  stable/metrics-server/README.md
  stable/metrics-server/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#22003 [stable/prometheus-operator] proper sync of rules and dashboard with upstream
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/hack/README.md
  stable/prometheus-operator/templates/grafana/dashboards-1.14/apiserver.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/pods.yaml
  stable/prometheus-operator/templates/grafana/dashboards-1.14/prometheus-remote-write.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kube-apiserver-error-alerts.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kube-apiserver-error.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kube-apiserver.rules.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-absent.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system-kubelet.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/node-time.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/prometheus.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XXL

#22002 [stable/jenkins] Fixing wrong indent in tolerations key.
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/jenkins-backup-cronjob.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#22010 [stable/prometheus-adapter] fix ClusterRole permissions
  stable/prometheus-adapter/Chart.yaml
  stable/prometheus-adapter/templates/custom-metrics-resource-reader-cluster-role.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21564 [stable/tensorflow-serving] drop time annotation
  stable/tensorflow-serving/Chart.yaml
  stable/tensorflow-serving/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test

#21804 [stable/prometheus-postgres-exporter] Add support to configure dataso…
  stable/prometheus-postgres-exporter/Chart.yaml
  stable/prometheus-postgres-exporter/README.md
  stable/prometheus-postgres-exporter/templates/deployment.yaml
  stable/prometheus-postgres-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#19535 Improve etcd statefulset template
  incubator/etcd/Chart.yaml
  incubator/etcd/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21529 Fix for url consistency
  README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21750 [stable/rethinkdb] Implement storageClass
  stable/rethinkdb/Chart.yaml
  stable/rethinkdb/templates/rethinkdb-cluster-stateful-set.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21929 [stable/verdaccio] Adding verdaccio deprecation warning
  stable/verdaccio/Chart.yaml
  stable/verdaccio/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22000 [stable/elastalert] Upgrade to Elastalert 0.2.4
  stable/elastalert/Chart.yaml
  stable/elastalert/README.md
  stable/elastalert/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#21993 Fix/empty mount dir datadog chart
  stable/datadog/Chart.yaml
  stable/datadog/templates/_helpers.tpl
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22006 [stable/datadog] fix several reported issues
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/OWNERS
  stable/datadog/README.md
  stable/datadog/docs/Migration_1.x_to_2.x.md
  stable/datadog/templates/agent-clusterchecks-deployment.yaml
  stable/datadog/templates/cluster-agent-config-configmap.yaml
  stable/datadog/templates/cluster-agent-deployment.yaml
  stable/datadog/templates/container-agent.yaml
  stable/datadog/templates/container-process-agent.yaml
  stable/datadog/templates/container-system-probe.yaml
  stable/datadog/templates/container-trace-agent.yaml
  stable/datadog/templates/containers-common-env.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#21170 [stable/jenkins] Enable Jenkins Configuration as Code auto-reload container environment variables configuration
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/jenkins-master-deployment.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#22013 [stable/newrelic-infrastructure] Explicitly define the namespace in manifests.
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/templates/configmap.yaml
  stable/newrelic-infrastructure/templates/daemonset.yaml
  stable/newrelic-infrastructure/templates/secret.yaml
  stable/newrelic-infrastructure/templates/serviceaccount.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22008 [stable/jenkins] update plugin version & sidecar container
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/ci/other-values.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#22004 [incubator/haproxy-ingress] Change service port names to meet Istio requirements
  incubator/haproxy-ingress/Chart.yaml
  incubator/haproxy-ingress/templates/controller-service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22022 [stable/sysdig] Use app.kubernetes.io labels instead of custom ones
  stable/sysdig/CHANGELOG.md
  stable/sysdig/Chart.yaml
  stable/sysdig/templates/_helpers.tpl
  stable/sysdig/templates/auditsink.yaml
  stable/sysdig/templates/clusterrole.yaml
  stable/sysdig/templates/clusterrolebinding.yaml
  stable/sysdig/templates/configmap-custom-app-checks.yaml
  stable/sysdig/templates/configmap.yaml
  stable/sysdig/templates/daemonset.yaml
  stable/sysdig/templates/secrets.yaml
  stable/sysdig/templates/securitycontextconstraint.yaml
  stable/sysdig/templates/service.yaml
  stable/sysdig/templates/serviceaccount.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#21907 [stable/minio]: add serviceAccountName in create-bucket-job to make it consistent
  stable/minio/Chart.yaml
  stable/minio/templates/post-install-create-bucket-job.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22019 [stable/sentry] Sentry ingress labels
  stable/sentry/Chart.yaml
  stable/sentry/README.md
  stable/sentry/templates/ingress.yaml
  stable/sentry/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21675 [stable/jenkins] Add `master.keepImagePlugins` option.
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/ci/other-values.yaml
  stable/jenkins/templates/jenkins-master-deployment.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21969 [stable/chartmuseum] allow for extraargs to be set
  stable/chartmuseum/Chart.yaml
  stable/chartmuseum/README.md
  stable/chartmuseum/templates/deployment.yaml
  stable/chartmuseum/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22036 [stable/home-assistant] Small fix and enhancements
  stable/home-assistant/Chart.yaml
  stable/home-assistant/README.md
  stable/home-assistant/templates/deployment.yaml
  stable/home-assistant/templates/service.yaml
  stable/home-assistant/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21864 [stable/jenkins]: use wrong type for master.runAsUser comparison (#21358)
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/jenkins-master-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21950 [stable/nginx-ingress] fixing pdb selectors to match pod labels
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/templates/controller-poddisruptionbudget.yaml
  stable/nginx-ingress/templates/default-backend-poddisruptionbudget.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22034 [incubator/azuremonitor-containers] updates related to agent 04162020 release
  incubator/azuremonitor-containers/Chart.yaml
  incubator/azuremonitor-containers/README.md
  incubator/azuremonitor-containers/templates/omsagent-rbac.yaml
  incubator/azuremonitor-containers/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22044 Buzzfeed sso/fix default allowed email domains
  incubator/buzzfeed-sso/Chart.yaml
  incubator/buzzfeed-sso/README.md
  incubator/buzzfeed-sso/templates/proxy-deployment.yaml
  incubator/buzzfeed-sso/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22054 [stable/jenkins] revert runAsUser comparison
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/ci/other-values.yaml
  stable/jenkins/templates/jenkins-master-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#22058 [stable/gocd] Bump up GoCD Version to 20.3.0
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21917 [stable/selenium] Add configurable securityContext in all selenium deployments
  stable/selenium/Chart.yaml
  stable/selenium/README.md
  stable/selenium/templates/chrome-deployment.yaml
  stable/selenium/templates/chromeDebug-deployment.yaml
  stable/selenium/templates/firefox-deployment.yaml
  stable/selenium/templates/firefoxDebug-deployment.yaml
  stable/selenium/templates/hub-deployment.yaml
  stable/selenium/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M
