Repository helm/charts, pull requests merged in 2020-06, with the labels that each got.

#22497 [stable/jenkins] Add support for installing additional plugins
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/ci/casc-values.yaml
  stable/jenkins/templates/config.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#22573 [stable/coredns] - add all options to cluster-proportional-autoscaler
  stable/coredns/Chart.yaml
  stable/coredns/README.md
  stable/coredns/templates/configmap-autoscaler.yaml
  stable/coredns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22607 [stable/grafana] Update curlimages to support other architectures
  stable/grafana/Chart.yaml
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22622 [stable/jenkins] add workingDir to default pod template
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/_helpers.tpl
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22514 Remove generation of unneeded secret
  stable/grafana/Chart.yaml
  stable/grafana/templates/deployment.yaml
  stable/grafana/templates/secret.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22610 [stable/jenkins] update plugin versions
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#22627 [stable/kubernetes-dashboard] Deprecate chart.
  stable/kubernetes-dashboard/Chart.yaml
  stable/kubernetes-dashboard/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#22524 [stable/dmarc2logstash] Update README.md to reflect new chart repository location
  stable/dmarc2logstash/Chart.yaml
  stable/dmarc2logstash/OWNERS
  stable/dmarc2logstash/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#22602 [stable/kube-state-metrics] Set runAsGroup
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
  stable/kube-state-metrics/templates/deployment.yaml
  stable/kube-state-metrics/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22616 [stable/hazelcast] Chart Deprecation
  stable/hazelcast/Chart.yaml
  stable/hazelcast/README.adoc
  stable/hazelcast/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XL

#22617 [stable/hazelcast-jet] Chart Deprecation
  stable/hazelcast-jet/Chart.yaml
  stable/hazelcast-jet/README.adoc
  stable/hazelcast-jet/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XL

#22615 [stable/kube-ops-view] Upgrade to 20.4.0
  stable/kube-ops-view/Chart.yaml
  stable/kube-ops-view/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22359 [stable/prometheus-operator] Update KubeNodeUnreachable alert to fix #21371
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system-kubelet.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21589 stable/traefik: Update version from 1.7.20 to 1.7.23
  stable/traefik/Chart.yaml
  stable/traefik/README.md
  stable/traefik/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22390 [stable/prometheus-operator]: do not allow '--manage-crds' flag in operator version >= v0.39.0
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/prometheus-operator/deployment.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22371 Drop incubator/oauth-proxy (#22370)
  incubator/oauth-proxy/.helmignore
  incubator/oauth-proxy/Chart.yaml
  incubator/oauth-proxy/README.md
  incubator/oauth-proxy/templates/NOTES.txt
  incubator/oauth-proxy/templates/_helpers.tpl
  incubator/oauth-proxy/templates/deployment.yaml
  incubator/oauth-proxy/templates/ingress.yaml
  incubator/oauth-proxy/templates/secret.yaml
  incubator/oauth-proxy/templates/service.yaml
  incubator/oauth-proxy/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#20892 [incubator/kube-registry-proxy] Update DaemonSet apiVersion to 'apps/v1' - Mandatory for K8s 1.16
  incubator/kube-registry-proxy/Chart.yaml
  incubator/kube-registry-proxy/templates/daemon.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22499 [stable/prometheus-operator] make kube-apiserver-slos configurable via defaultRules.rules.kubeApiserverSlos
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/hack/sync_prometheus_rules.py
  stable/prometheus-operator/templates/prometheus/rules-1.14/etcd.yaml
  stable/prometheus-operator/templates/prometheus/rules-1.14/kube-apiserver-slos.yaml
  stable/prometheus-operator/templates/prometheus/rules/etcd.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#21895 [stable/jenkins] 2.0.0 Release: JCasC by default
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/ci/casc-values.yaml
  stable/jenkins/ci/other-values.yaml
  stable/jenkins/ci/xml-values.yaml
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#22651 [newrelic-infrastructure] Deprecated newrelic-infrastructure chart in this repo
  stable/newrelic-infrastructure/Chart.yaml
  stable/newrelic-infrastructure/README.md
  stable/newrelic-infrastructure/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, size/M

#22626 Reverse HPA metrics order
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/templates/controller-hpa.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22648 [stable/sentry] Sentry add hook pod tolerations
  stable/sentry/Chart.yaml
  stable/sentry/README.md
  stable/sentry/templates/hooks/db-init.job.yaml
  stable/sentry/templates/hooks/user-create.job.yaml
  stable/sentry/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22642 stable/nfs-server-provisioner Add ability to specify pod Security Context settings
  stable/nfs-server-provisioner/Chart.yaml
  stable/nfs-server-provisioner/README.md
  stable/nfs-server-provisioner/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#22660 [stable/nfs-server-provisioner] "statdNodePort" is not used in services.yaml
  stable/nfs-server-provisioner/Chart.yaml
  stable/nfs-server-provisioner/templates/service.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#22141 [stable/prometheus] Fix node-exporter containerPort to hostPort
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/node-exporter-daemonset.yaml
  stable/prometheus/templates/node-exporter-service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22647 [stable/prometheus] Add configFromSecret support to StatefulSet alertmanagers
  stable/prometheus/Chart.yaml
  stable/prometheus/templates/alertmanager-statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22665 [stable/rabbitmq-ha] Upgrade RabbitMQ to 3.8.4 version
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22544 [stable/stolon] Allow password files to be used
  stable/stolon/Chart.yaml
  stable/stolon/README.md
  stable/stolon/templates/NOTES.txt
  stable/stolon/templates/keeper-statefulset.yaml
  stable/stolon/templates/secret.yaml
  stable/stolon/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22676 [stable/elastabot] Chart deprecation
  stable/elastabot/Chart.yaml
  stable/elastabot/OWNERS
  stable/elastabot/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#22629 [stable/cerebro] add conditional ingress apiVersion to replace to-be-deprecated extensions/v1beta1
  stable/cerebro/Chart.yaml
  stable/cerebro/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22674 [stable/prometheus-mysql-exporter]: fix docs typo
  stable/prometheus-mysql-exporter/Chart.yaml
  stable/prometheus-mysql-exporter/README.md
Labels: Contribution Allowed, approved, lgtm, size/XS

#22675 [stable/airflow] documentation fixes
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20404 [stable/presto] Uses official image from prestosql.io
  stable/presto/Chart.yaml
  stable/presto/README.md
  stable/presto/templates/configmap-coordinator.yaml
  stable/presto/templates/configmap-worker.yaml
  stable/presto/templates/deployment-coordinator.yaml
  stable/presto/templates/deployment-worker.yaml
  stable/presto/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22673 [stable/grafana] Update to latest grafana (7.0.1->7.0.3) and latest sidecar (0.1.99->0.1.151)
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22679 [stable/anchore-engine] Update images to latest versions
  stable/anchore-engine/Chart.yaml
  stable/anchore-engine/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#22351 [stable/sentry] Update sentry's readme to talk about the new chart
  stable/sentry/Chart.yaml
  stable/sentry/README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#22672 [stable/prometheus-operator] Allow additional volumes and volumeMounts
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/prometheus/prometheus.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22684 [stable/prometheus-operator] Apply tpl on Prometheus external url
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/prometheus/prometheus.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22688 [stable/kube-ops-view] Allow for securityContext at container-level i…
  stable/kube-ops-view/Chart.yaml
  stable/kube-ops-view/templates/deployment.yaml
  stable/kube-ops-view/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#22481 feat(migrate): Remove Falco Stable Chart
  stable/falco/.helmignore
  stable/falco/CHANGELOG.md
  stable/falco/Chart.yaml
  stable/falco/OWNERS
  stable/falco/README.md
  stable/falco/ci/ebpf-values.yaml
  stable/falco/rules/application_rules.yaml
  stable/falco/rules/falco_rules.local.yaml
  stable/falco/rules/falco_rules.yaml
  stable/falco/rules/k8s_audit_rules.yaml
  stable/falco/templates/NOTES.txt
  stable/falco/templates/_helpers.tpl
  stable/falco/templates/auditsink.yaml
  stable/falco/templates/clusterrole.yaml
  stable/falco/templates/clusterrolebinding.yaml
  stable/falco/templates/configmap-rules.yaml
  stable/falco/templates/configmap.yaml
  stable/falco/templates/daemonset.yaml
  stable/falco/templates/deployment.yaml
  stable/falco/templates/podsecuritypolicy.yaml
  stable/falco/templates/secret-certs.yaml
  stable/falco/templates/secret.yaml
  stable/falco/templates/service.yaml
  stable/falco/templates/serviceaccount.yaml
  stable/falco/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XXL

#22662 [stable/prometheus-operator] Upgrade dependencies & set group to non-root
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/requirements.lock
  stable/prometheus-operator/requirements.yaml
  stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
  stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22236 [stable/percona-xtradb-cluster] fix StatefulSet apiVersion for Kubernetes 1.16+
  stable/percona-xtradb-cluster/Chart.yaml
  stable/percona-xtradb-cluster/templates/_helpers.tpl
  stable/percona-xtradb-cluster/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22692 [stable/anchore-engine] add UI configs for 2.3.1 features
  stable/anchore-engine/Chart.yaml
  stable/anchore-engine/templates/enterprise_ui_config_secret.yaml
  stable/anchore-engine/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#22689 [stable/elastalert] Deprecate chart
  stable/elastalert/Chart.yaml
  stable/elastalert/OWNERS
  stable/elastalert/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#22678 [stable/jenkins] Only render authorizationStrategy and securityRealm if set
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/templates/_helpers.tpl
  stable/jenkins/templates/jenkins-master-svc.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#22696 [stable/consul] Deprecate stable/consul
  stable/consul/Chart.yaml
  stable/consul/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#21720 [stable/stackdriver-exporter] update k8s deployement api version
  stable/stackdriver-exporter/Chart.yaml
  stable/stackdriver-exporter/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22148 [incubator/buzzfeed-sso] Add support for GCP BackendConfig
  incubator/buzzfeed-sso/Chart.yaml
  incubator/buzzfeed-sso/README.md
  incubator/buzzfeed-sso/templates/ingress-backendconfigs.yaml
  incubator/buzzfeed-sso/templates/proxy-service.yaml
  incubator/buzzfeed-sso/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22654 [stable/minecraft] Added option to use existing persistentVolumeClaim
  stable/minecraft/Chart.yaml
  stable/minecraft/templates/datadir-pvc.yaml
  stable/minecraft/templates/deployment.yaml
  stable/minecraft/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22702 [stable/unifi] adding functionality to mount extra volumes
  stable/unifi/Chart.yaml
  stable/unifi/README.md
  stable/unifi/templates/deployment.yaml
  stable/unifi/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22583 [stable/kube-slack] Make kube-slack compatible with EKS 1.16
  stable/kube-slack/Chart.yaml
  stable/kube-slack/templates/_helpers.tpl
  stable/kube-slack/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22685 [stable/coredns] Allow extra volumes and mounts
  stable/coredns/Chart.yaml
  stable/coredns/README.md
  stable/coredns/templates/deployment.yaml
  stable/coredns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22715 [stable/datadog] Add clusterAgent.podLabels variable to add labels to the Cluster Agent Pod(s)
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/cluster-agent-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22257 Revert "[stable/fluentd] Fix missing serviceName in HPA"
  stable/fluentd/Chart.yaml
  stable/fluentd/templates/hpa.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22724 [stable/minio] remove unnecessary annotation
  stable/minio/Chart.yaml
  stable/minio/templates/deployment.yaml
  stable/minio/templates/statefulset.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22703 [stable/unifi] Add ingress for Unifi controller sevice
  stable/unifi/Chart.yaml
  stable/unifi/README.md
  stable/unifi/templates/controller-ingress.yaml
  stable/unifi/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22720 rabbitmq readiness probe fails in some cases.
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22729 [stable/mercure] Use the /healthz URL for probes
  stable/mercure/Chart.yaml
  stable/mercure/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#22491 [stable/schema-registry-ui] Enable schema-registry-ui advanced settings
  stable/schema-registry-ui/Chart.yaml
  stable/schema-registry-ui/README.md
  stable/schema-registry-ui/templates/deployment.yaml
  stable/schema-registry-ui/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22766 [stable/openebs]: add rbd to default exclude list
  stable/openebs/Chart.yaml
  stable/openebs/README.md
  stable/openebs/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/L

#22745 [stable/home-assistant] deprecating home-assistant chart
  stable/home-assistant/Chart.yaml
  stable/home-assistant/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#22760 [stable/prometheus-adapter] Allow specifying a path for the Prometheus URL
  stable/prometheus-adapter/Chart.yaml
  stable/prometheus-adapter/README.md
  stable/prometheus-adapter/templates/custom-metrics-apiserver-deployment.yaml
  stable/prometheus-adapter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22747 [stable/airflow] fixed flower extraConfigmapMounts
  stable/airflow/Chart.yaml
  stable/airflow/README.md
  stable/airflow/examples/google-gke/custom-values.yaml
  stable/airflow/examples/minikube/custom-values.yaml
  stable/airflow/templates/deployments-flower.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/M

#22295 [stable/kube-state-metrics] Support imagePullSecrets
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
  stable/kube-state-metrics/templates/deployment.yaml
  stable/kube-state-metrics/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22746 [stable/anchore-engine] fix msrc feeds value
  stable/anchore-engine/Chart.yaml
  stable/anchore-engine/templates/engine_configmap.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#22755 [incubator/druid] upgrade dependencies to latest version
  incubator/druid/Chart.yaml
  incubator/druid/OWNERS
  incubator/druid/requirements.lock
  incubator/druid/requirements.yaml
  incubator/druid/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22789 [stable/openebs]: update openebs charts to 1.11.0 release
  stable/openebs/Chart.yaml
  stable/openebs/README.md
  stable/openebs/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22727 [stable/datadog] introduce dnsConfig helm values for the different co…
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/agent-clusterchecks-deployment.yaml
  stable/datadog/templates/cluster-agent-deployment.yaml
  stable/datadog/templates/daemonset.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22800 [stable/prometheus-blackbox-exporter] Fix broken protmetheusrule
  stable/prometheus-blackbox-exporter/Chart.yaml
  stable/prometheus-blackbox-exporter/templates/prometheusrule.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22757 [stable/minio] Sanitize release namespace (#22756)
  stable/minio/Chart.yaml
  stable/minio/templates/post-install-prometheus-metrics-rolebinding.yaml
  stable/minio/templates/servicemonitor.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22791 [incubator/fluentd-cloudwatch] Skip creating secret when aws credentials are not set
  incubator/fluentd-cloudwatch/Chart.yaml
  incubator/fluentd-cloudwatch/templates/secrets.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22805 [stable/minio] update default values
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22807 Update name of CI cluster
  test/e2e.sh
Labels: Contribution Allowed, approved, lgtm, size/XS

#22641 [stable/jenkins] Add runAsUser and runAsGroup to podTemplate
  stable/jenkins/CHANGELOG.md
  stable/jenkins/Chart.yaml
  stable/jenkins/README.md
  stable/jenkins/templates/_helpers.tpl
  stable/jenkins/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22795 [stable/openvpn] Fix Go 1.14 templating
  stable/openvpn/Chart.yaml
  stable/openvpn/templates/config-openvpn.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22804 [stable/coredns] separate creation of prometheus service from operator
  stable/coredns/Chart.yaml
  stable/coredns/README.md
  stable/coredns/templates/service-metrics.yaml
  stable/coredns/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22785 [stable/graylog] support graylog server logging in JSON
  stable/graylog/Chart.yaml
  stable/graylog/README.md
  stable/graylog/templates/configmap.yaml
  stable/graylog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22728 [stable/prometheus-operator] Template grafana.additionalDataSources
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/grafana/configmaps-datasources.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22718 [incubator/azuremonitor-containers] updates related to agent ciprod05262020 and win-ciprod05262020-2 release
  incubator/azuremonitor-containers/Chart.yaml
  incubator/azuremonitor-containers/README.md
  incubator/azuremonitor-containers/templates/omsagent-crd.yaml
  incubator/azuremonitor-containers/templates/omsagent-daemonset-windows.yaml
  incubator/azuremonitor-containers/templates/omsagent-daemonset.yaml
  incubator/azuremonitor-containers/templates/omsagent-deployment.yaml
  incubator/azuremonitor-containers/templates/omsagent-rbac.yaml
  incubator/azuremonitor-containers/templates/omsagent-rs-configmap.yaml
  incubator/azuremonitor-containers/templates/omsagent-secret.yaml
  incubator/azuremonitor-containers/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#22725 [stable/prometheus-operator] Added supports of ServiceAccount annotation in alertmanager
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/alertmanager/serviceaccount.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22784 [stable/prometheus] gRPC port on headless svc
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/templates/server-service-headless.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22801 [stable/grafana] Update sidecar image configuration
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/_pod.tpl
  stable/grafana/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#22722 stable/sealed-secrets: Fallback to Helm .Release.Namespace when .Values.namespace not defined.
  stable/sealed-secrets/Chart.yaml
  stable/sealed-secrets/README.md
  stable/sealed-secrets/templates/_helpers.tpl
  stable/sealed-secrets/templates/cluster-role-binding.yaml
  stable/sealed-secrets/templates/deployment.yaml
  stable/sealed-secrets/templates/ingress.yaml
  stable/sealed-secrets/templates/networkpolicy.yaml
  stable/sealed-secrets/templates/psp-clusterrolebinding.yaml
  stable/sealed-secrets/templates/role-binding.yaml
  stable/sealed-secrets/templates/role.yaml
  stable/sealed-secrets/templates/service-account.yaml
  stable/sealed-secrets/templates/service.yaml
  stable/sealed-secrets/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22797 [stable/hazelcast] use new chart repo URL at deprecation notice
  stable/hazelcast/Chart.yaml
  stable/hazelcast/README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#22798 [stable/hazelcast-jet] use new chart repo URL at deprecation notice
  stable/hazelcast-jet/Chart.yaml
  stable/hazelcast-jet/README.md
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#22764 [stable/prometheus-node-exporter] Add relabelings config for ServiceMonitor
  stable/prometheus-node-exporter/Chart.yaml
  stable/prometheus-node-exporter/README.md
  stable/prometheus-node-exporter/templates/monitor.yaml
  stable/prometheus-node-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22763 [stable/graylog] Add root username to k8s secret
  stable/graylog/Chart.yaml
  stable/graylog/templates/secret.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22809 [stable/prometheus-operator] Bump Grafana version to 5.2.0
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/requirements.lock
  stable/prometheus-operator/requirements.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#22586 [stable/prometheus-operator] Scraping kubelet for /metrics/resource/v1alpha1
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/exporters/kubelet/servicemonitor.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22758 [stable/nginx-ingress] Add support for an internal load balancer along with an external one
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/ci/daemonset-internal-lb-values.yaml
  stable/nginx-ingress/ci/deployment-internal-lb-values.yaml
  stable/nginx-ingress/templates/controller-service-internal.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#22812 [stable/minio] Support imagePullSecrets
  stable/minio/Chart.yaml
  stable/minio/README.md
  stable/minio/templates/deployment.yaml
  stable/minio/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22649 [stable/kube-state-metrics] Version bump to 1.9.7
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
  stable/kube-state-metrics/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/XS

#22767 [stable/spinnaker] Fix kubeconfig s3 bucket configuration in spinnaker chart
  stable/spinnaker/Chart.yaml
  stable/spinnaker/templates/hooks/install-using-hal.yaml
  stable/spinnaker/templates/statefulsets/halyard.yaml
  stable/spinnaker/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22788 [incubator/druid] Remove the incubating label and update related infos for Apache Druid
  incubator/druid/Chart.yaml
  incubator/druid/README.md
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22773 [stable/prometheus-operator] fix invalid image pull policy for admission webhook patch image
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22825 [stable/grafana] Fixed label selector in install note
  stable/grafana/Chart.yaml
  stable/grafana/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22836 [stable/nextcloud] Add HPA
  stable/nextcloud/Chart.yaml
  stable/nextcloud/README.md
  stable/nextcloud/templates/hpa.yaml
  stable/nextcloud/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22802 [stable/mssql-linux] Move "imagePullSecrets" to the right indentation level
  stable/mssql-linux/Chart.yaml
  stable/mssql-linux/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#21955 [stable/elasticsearch] Deprecate Elasticsearch chart in favor of official Elastic chart.
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/README.md
  stable/elasticsearch/templates/NOTES.txt
Labels: Contribution Allowed, approved, lgtm, size/M

#22846 [stable/sematext-agent] add /dev mount
  stable/sematext-agent/Chart.yaml
  stable/sematext-agent/templates/daemonset.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#22743 [stable/spinnaker] Add psp option
  stable/spinnaker/Chart.yaml
  stable/spinnaker/templates/hooks/install-using-hal.yaml
  stable/spinnaker/templates/rbac/psp-halyard-role.yaml
  stable/spinnaker/templates/rbac/psp-halyard-rolebinding.yaml
  stable/spinnaker/templates/rbac/psp-halyard.yaml
  stable/spinnaker/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22771 nginx-ingress can now set resources for admission webhook jobs
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/admission-webhooks/job-patch/job-createSecret.yaml
  stable/nginx-ingress/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#20622 [stable/hackmd] Support 1.16 by upgrading postgresql
  stable/hackmd/Chart.yaml
  stable/hackmd/requirements.lock
  stable/hackmd/requirements.yaml
  stable/hackmd/templates/deployment.yaml
  stable/hackmd/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22839 fix issue caused by #22288
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/templates/alertmanager/ingressperreplica.yaml
  stable/prometheus-operator/templates/alertmanager/serviceperreplica.yaml
  stable/prometheus-operator/templates/prometheus/additionalPrometheusRules.yaml
  stable/prometheus-operator/templates/prometheus/ingressperreplica.yaml
  stable/prometheus-operator/templates/prometheus/podmonitors.yaml
  stable/prometheus-operator/templates/prometheus/servicemonitors.yaml
  stable/prometheus-operator/templates/prometheus/serviceperreplica.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22639 [incubator/rundeck] allow configurable nginx conf. Add example
  incubator/rundeck/Chart.yaml
  incubator/rundeck/README.md
  incubator/rundeck/templates/nginx-configmap.yaml
  incubator/rundeck/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22736 [stable/dex] Dex v2.24.0
  stable/dex/Chart.yaml
  stable/dex/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22831 [stable/seq] Support ingesting GELF
  stable/seq/Chart.yaml
  stable/seq/README.md
  stable/seq/templates/deployment.yaml
  stable/seq/templates/psp.yaml
  stable/seq/templates/service.yaml
  stable/seq/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#22852 stable/fluent-bit
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/config.yaml
  stable/fluent-bit/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22822 [stable/sentry] Add Ingress extraPaths to prepend to every host configuration
  stable/sentry/Chart.yaml
  stable/sentry/README.md
  stable/sentry/templates/ingress.yaml
  stable/sentry/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22811 [stable/rabbitmq-ha] Upgrade RabbitMQ to 3.8.5 version
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/README.md
  stable/rabbitmq-ha/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22832 [incubator/druid] Bump Apache Druid to 0.18.1
  incubator/druid/Chart.yaml
  incubator/druid/README.md
  incubator/druid/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22858 [stable/rabbitmq-ha] Added support for extraLables in the ingress.yaml template
  stable/rabbitmq-ha/Chart.yaml
  stable/rabbitmq-ha/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22860 [stable/openebs] add deprecation notice to openebs chart
  stable/openebs/Chart.yaml
  stable/openebs/OWNERS
  stable/openebs/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#22845 [stable/efs-provisioner] Add extra env variables and envFrom support
  stable/efs-provisioner/Chart.yaml
  stable/efs-provisioner/README.md
  stable/efs-provisioner/templates/deployment.yaml
  stable/efs-provisioner/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22849 [stable/prometheus] updated all prometheus docker images to latest versions
  stable/prometheus/Chart.yaml
  stable/prometheus/README.md
  stable/prometheus/requirements.yaml
  stable/prometheus/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#22248 [stable/oauth2-proxy] Add ingress extraPaths support
  stable/oauth2-proxy/Chart.yaml
  stable/oauth2-proxy/README.md
  stable/oauth2-proxy/ci/ingress-extra-paths-values.yaml
  stable/oauth2-proxy/templates/ingress.yaml
  stable/oauth2-proxy/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22867 [stable/spinnaker] Relax PSP
  stable/spinnaker/Chart.yaml
  stable/spinnaker/templates/rbac/psp-halyard.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22697 [stable/mongodb-replicaset] Add ServiceAccount option (#22694)
  stable/mongodb-replicaset/Chart.yaml
  stable/mongodb-replicaset/README.md
  stable/mongodb-replicaset/templates/mongodb-serviceaccount.yaml
  stable/mongodb-replicaset/templates/mongodb-statefulset.yaml
  stable/mongodb-replicaset/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22885 [stable/minecraft] Deprecating minecraft chart
  stable/minecraft/Chart.yaml
  stable/minecraft/README.md
Labels: Contribution Allowed, approved, lgtm, size/S

#22883 [stable/grafana] Fix grafana ingress
  stable/grafana/Chart.yaml
  stable/grafana/README.md
  stable/grafana/templates/ingress.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21882 [stable/ipfs] generated yaml syntax fixes for ipfs ingress
  stable/ipfs/Chart.yaml
  stable/ipfs/templates/ingress-api.yaml
  stable/ipfs/templates/ingress-gateway.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22726 [stable/prometheus-operator] Adding hostNetwork for operator
  stable/prometheus-operator/Chart.yaml
  stable/prometheus-operator/README.md
  stable/prometheus-operator/templates/prometheus-operator/deployment.yaml
  stable/prometheus-operator/templates/prometheus-operator/psp.yaml
  stable/prometheus-operator/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22862 [stable/spinnaker] The kubernetes account may not have access to all the namespaces.
  stable/spinnaker/Chart.yaml
  stable/spinnaker/templates/_helpers.tpl
  stable/spinnaker/templates/configmap/halyard-config.yaml
  stable/spinnaker/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22792 [stable/kube-state-metrics] Document `kubeTargetVersionOverride`
  stable/kube-state-metrics/Chart.yaml
  stable/kube-state-metrics/README.md
  stable/kube-state-metrics/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22882 [incubator/rundeck] add pvc, sa, common labels, upgrade app and chart version
  incubator/rundeck/Chart.yaml
  incubator/rundeck/README.md
  incubator/rundeck/files/nginx/nginx.conf
  incubator/rundeck/templates/_helpers.tpl
  incubator/rundeck/templates/deployment.yaml
  incubator/rundeck/templates/ingress.yaml
  incubator/rundeck/templates/nginx-configmap.yaml
  incubator/rundeck/templates/rundeck-environment-configmap.yaml
  incubator/rundeck/templates/service.yaml
  incubator/rundeck/templates/serviceAccount.yaml
  incubator/rundeck/templates/volume.yaml
  incubator/rundeck/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/L

#22908 [stable/gocd] Bump up GoCD Version to 20.5.0
  stable/gocd/CHANGELOG.md
  stable/gocd/Chart.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#22910 [stable/datadog] Bump the default version of the docker images
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/S

#22874 Align CLC configuration with other agents + bump to latest releases
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/agent-clusterchecks-deployment.yaml
  stable/datadog/templates/container-agent.yaml
  stable/datadog/templates/containers-common-env.yaml
Labels: Contribution Allowed, approved, lgtm, size/M

#22914 [stable/cerebro] Add the possibility to specify a priorityClassName for the deployment's pods
  stable/cerebro/Chart.yaml
  stable/cerebro/README.md
  stable/cerebro/templates/deployment.yaml
  stable/cerebro/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22906 stable/prometheus-cloudwatch-exporter Add shasum of secrets yaml render to annotations
  stable/prometheus-cloudwatch-exporter/CHANGELOG.md
  stable/prometheus-cloudwatch-exporter/Chart.yaml
  stable/prometheus-cloudwatch-exporter/templates/deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21942 [stable/datadog] Use dedicated endpoints for liveness and readiness probes
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/agent-clusterchecks-deployment.yaml
  stable/datadog/templates/container-agent.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#22913 [stable/datadog] Define cluster-agent container command explicitly
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/cluster-agent-deployment.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22912 [incubator/druid] Specify these configurations about druid_indexer_logs_xxx
  incubator/druid/Chart.yaml
  incubator/druid/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22871 [incubator/sso-buzzfeed] Add default interval the group cache should refresh at
  incubator/buzzfeed-sso/Chart.yaml
  incubator/buzzfeed-sso/templates/auth-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#21660 [incubator/fluentd-cloudwatch] update apiVersion to be compatible with k8s >= 1.16
  incubator/fluentd-cloudwatch/Chart.yaml
  incubator/fluentd-cloudwatch/templates/daemonset.yaml
  incubator/fluentd-cloudwatch/templates/psp.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22921 [incubator/rundeck] fixes broken deployment strategy and annotations
  incubator/rundeck/Chart.yaml
  incubator/rundeck/README.md
  incubator/rundeck/templates/deployment.yaml
  incubator/rundeck/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22686 [stable/datadog] Mount kernel headers in system-probe container
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/templates/container-agent.yaml
  stable/datadog/templates/container-process-agent.yaml
  stable/datadog/templates/container-system-probe.yaml
  stable/datadog/templates/containers-init-linux.yaml
  stable/datadog/templates/daemonset-volumes-linux.yaml
  stable/datadog/templates/system-probe-configmap.yaml
  stable/datadog/values.yaml
Labels: Contribution Allowed, approved, lgtm, size/L

#22933 [stable/graylog] Adding the ability to specify externalTrafficPolicy for LoadBalancer services
  stable/graylog/Chart.yaml
  stable/graylog/README.md
  stable/graylog/templates/tcp-service.yaml
  stable/graylog/templates/udp-service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/XS

#22944 [stable/datadog] Typo and grammar fixes in documentation
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/README.md
  stable/datadog/docs/Migration_1.x_to_2.x.md
Labels: Contribution Allowed, approved, lgtm, size/S

#22922 [stable/datadog] Handle arguments in the cluster-agent command
  stable/datadog/CHANGELOG.md
  stable/datadog/Chart.yaml
  stable/datadog/templates/cluster-agent-deployment.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22870 [incubator/druid] add enabled flag to all druid roles
  incubator/druid/Chart.yaml
  incubator/druid/README.md
  incubator/druid/templates/broker/deployment.yaml
  incubator/druid/templates/broker/service.yaml
  incubator/druid/templates/configmap.yaml
  incubator/druid/templates/coordinator/deployment.yaml
  incubator/druid/templates/coordinator/service.yaml
  incubator/druid/templates/historical/service.yaml
  incubator/druid/templates/historical/statefulset.yaml
  incubator/druid/templates/middleManager/service.yaml
  incubator/druid/templates/middleManager/statefulset.yaml
  incubator/druid/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22951 [stable/elasticsearch-exporter] Add serviceMonitor targetLabels
  stable/elasticsearch-exporter/Chart.yaml
  stable/elasticsearch-exporter/README.md
  stable/elasticsearch-exporter/templates/servicemonitor.yaml
  stable/elasticsearch-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#22977 Update service port name to follow istio convention
  stable/spark-history-server/Chart.yaml
  stable/spark-history-server/templates/service.yaml
  stable/spark-history-server/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#22958 [incubator/haproxy-ingress] Fix helm3 ClusterIP updates
  incubator/haproxy-ingress/Chart.yaml
  incubator/haproxy-ingress/README.md
  incubator/haproxy-ingress/templates/controller-metrics-service.yaml
  incubator/haproxy-ingress/templates/controller-stats-service.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#21060 [stable/spinnaker] Allow serviceAccount annotations for Halyard
  stable/spinnaker/Chart.yaml
  stable/spinnaker/README.md
  stable/spinnaker/templates/rbac/halyard-sa.yaml
  stable/spinnaker/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22983 [stable/nginx-ingress] adding backwards compatible component label key override
  stable/nginx-ingress/Chart.yaml
  stable/nginx-ingress/README.md
  stable/nginx-ingress/templates/controller-daemonset.yaml
  stable/nginx-ingress/templates/controller-deployment.yaml
  stable/nginx-ingress/templates/controller-metrics-service.yaml
  stable/nginx-ingress/templates/controller-poddisruptionbudget.yaml
  stable/nginx-ingress/templates/controller-service-internal.yaml
  stable/nginx-ingress/templates/controller-service.yaml
  stable/nginx-ingress/templates/controller-webhook-service.yaml
  stable/nginx-ingress/templates/default-backend-deployment.yaml
  stable/nginx-ingress/templates/default-backend-poddisruptionbudget.yaml
  stable/nginx-ingress/templates/default-backend-service.yaml
  stable/nginx-ingress/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/M

#22985 [stable/cluster-overprovisioner] add pod security context
  stable/cluster-overprovisioner/Chart.yaml
  stable/cluster-overprovisioner/README.md
  stable/cluster-overprovisioner/templates/deployments.yaml
  stable/cluster-overprovisioner/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/S

#22990 [stable/sematext-agent] Add option for priorityClassName
  stable/sematext-agent/Chart.yaml
  stable/sematext-agent/README.md
  stable/sematext-agent/templates/daemonset.yaml
  stable/sematext-agent/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/XS

#22986 [stable/prometheus-mysql-exporter]: Add service labels and annotations
  stable/prometheus-mysql-exporter/Chart.yaml
  stable/prometheus-mysql-exporter/README.md
  stable/prometheus-mysql-exporter/templates/service.yaml
  stable/prometheus-mysql-exporter/values.yaml
Labels: Contribution Allowed, approved, lgtm, ok-to-test, size/S

#22876 [stable/nextcloud] Add prometheus metrics exporter
  stable/nextcloud/Chart.yaml
  stable/nextcloud/README.md
  stable/nextcloud/templates/metrics-deployment.yaml
  stable/nextcloud/templates/metrics-service.yaml
  stable/nextcloud/values.yaml
Labels: Contribution Allowed, approved, lgtm, needs-ok-to-test, size/L
